### ISSUE TITLE
Run Scala Unit Tests from Visual Studio Code

### ISSUE THREAD

**Issue by oharboe** [scalameta/metals#1001]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I'd like to be able to right click on a .scala file to run the unit-tests in that .scala file.

**Describe alternatives you've considered**

Run from command line: sbt "test:testOnly *DressRehearsal*

**Additional context**

**Search terms**:

scala unit test

**Comment by olafurpg** [comment]
The latest `0.7.6+133-1dfcd90c-SNAPSHOT` release from the current master supports running tests and main functions from VS Code. This functionality is still experimental, early feedback is welcome before we release the next stable version. Please open separate issues if you encounter problems with the latest SNAPSHOT

**Comment by FloWi** [comment]
> The latest `0.7.6+133-1dfcd90c-SNAPSHOT` release from the current master supports running tests and main functions from VS Code. This functionality is still experimental, early feedback is welcome before we release the next stable version. Please open separate issues if you encounter problems with the latest SNAPSHOT

This is an awesome feature, thanks for implementing it, @olafurpg ! 
Makes my life way easier!

**Comment by oharboe** [comment]
This is a *great* feature!

Is there a way to run a test within a suite?

For instance, a ThingAMaBobTest class might contain the test "work correctly", and I'd like to be able to debug that one test specifically and not all the tests in ThingAMaBobTests

```
sbt "test:testOnly *ThingAMaBobTests* -- -z \"works correctly\""
```

**Comment by marek1840** [comment]
> Is there a way to run a test within a suite?

Unfortunatelly no, we are currently limited by the lack of a specific endpoint in the `bsp`. There is [one](https://build-server-protocol.github.io/docs/extensions/scala.html#scala-test-classes-request) for the test _classes_, but sadly nothing for the test _cases_ :(

**Comment by olafurpg** [comment]
That feature would be lovely to support but it requires custom integration per test framework (scalatest, JUnit, utest,...). 

One feature we might be missing in bsp is to know what test framework is associated with each test class but otherwise the bulk of the missing work lies on the metals side to translate source code or tests into test framework arguments.

**Comment by olafurpg** [comment]
We should open a separate ticket to continue the discussion and we may need separate tickets per test frameworks (even separate tickets per testing syntax for example in scalatest, FunSuite, FlatSpec, etc)

**Comment by oharboe** [comment]
These names are not known until  runtime, they cant be determined
statically, so how about asking the users with a dialog or I guess a
launch.json file in VSCode....

ons. 12. feb. 2020, 23:51 skrev Ólafur Páll Geirsson <
notifications@github.com>:
