### ISSUE TITLE
Scala 2.12.10 support

### ISSUE THREAD

**Issue by ashkan-leo** [scalameta/metals#1005]
**Question**

Is metals-emacs 0.7.6 compatibale with Scala 2.12.10? metals doctor says to upgrade to scala 2.12.8.

**Installation:**

- Operating system: macOS
- Editor: Emacs
- Metals version: v0.7.6

**Search terms**

2.12.10, upgrade, scala-2.12

**Comment by olafurpg** [comment]
Thank you for reporting! 2.12.10 is supported in 0.7.6, you can ignore the warning message. In the latest SNAPSHOT the warning message has been fixed to no longer recommend the downgrade.
