### ISSUE TITLE
Consider using sbt-missinglink to detect binary incompatibilities in dependencies

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#1007]
Maybe we should start using https://github.com/scalacenter/sbt-missinglink 🤔

_Originally posted by @olafurpg in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDMzNjkyNTMwNw==/comments/review_comment_

**Comment by olafurpg** [comment]
We are quite conservative with out dependencies so I think it's fine to keep the status quo for now. If we do hit on bincompat issues then we might want reconsider.

**Comment by gabro** [comment]
👍 closing for now. It’s still useful to have this and keep track of the decision
