### ISSUE TITLE
Automatic implementation for abstract methods in concrete classes

### ISSUE THREAD

**Issue by dgalichet** [scalameta/metals#1008]
**Is your feature request related to a problem? Please describe.**

Not related to a problem

**Describe the solution you'd like**

This could take place automatically or with quick action.

```scala
  trait Foo {
    def foo(i: Int): String
  }
// before
  val foo = new Foo {}

// after
  val foo = new Foo {
    def foo(i: Int): String = ???
  }
```

**Describe alternatives you've considered**

This could be triggered using completion (same way that for the exhaustive pattern match), or using a quick action.

**Additional context**

**Search terms**:

**Comment by olafurpg** [comment]
I think it would be a good idea to start by implementing this as a completion. We can additionally support this feature as a code action.

The label of this completion could be something like `implement all methods` which works similar to `match (exchaustive)`.

A good place to start looking at to implement this feature would be here https://github.com/scalameta/metals/blob/a5050d7c17d011183dad832ba786a7a7edfa9fc0/mtags/src/main/scala/scala/meta/internal/pc/Completions.scala#L1183-L1194

We can create a new `CompletionOverrideAllSuite` that works similarly as https://github.com/scalameta/metals/blob/a5050d7c17d011183dad832ba786a7a7edfa9fc0/tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala

I'm not sure in what order this completion should appear 🤔 Should it appear at the top of the completion results or should it appear below the indvidual abstract methods?

**Comment by olafurpg** [comment]
One tricky situation that we should try to handle is when different methods introduce different symbol in scope with the same name. For example
```scala
package a { class Foo }
package b { class Foo }
trait Foo {
  def one: a.Foo
  def two: b.Foo
}
class Impl extends Foo {
  // implement all methods: ensure we don't insert conflicting imports
}
```
We can do this by using the same `ShortenedNames` instance when rendering the signatures of all methods https://github.com/scalameta/metals/blob/a5050d7c17d011183dad832ba786a7a7edfa9fc0/mtags/src/main/scala/scala/meta/internal/pc/Signatures.scala#L104

After rendering all signatures, the `ShortenedNames` instance make sure we don't introduce conflicting imports.

**Comment by ckipp01** [comment]
> I'm not sure in what order this completion should appear 🤔 Should it appear at the top of the completion results or should it appear below the individual abstract methods? 

My initial thought is at the top?

**Comment by olafurpg** [comment]
I think the top makes sense, the user can filter out the "implement all methods" completion by writing the name of the specific method to override.

**Comment by ckipp01** [comment]
Couple quick questions

Thoughts on the label?
I implemented it so that if you have for example 4 abstract methods, but 2 implemented, you still get the option to implement the remaining ones. Is that alright, or do we only want it offered if non of the abstract members are implemented? If we do want it, if there is only one left to implement, there is no need to show it correct?
![abstract](https://user-images.githubusercontent.com/13974112/67714110-806dd300-f9c7-11e9-904a-55282f1993de.gif)

**Comment by olafurpg** [comment]
@ckipp01 that looks great!

> Thoughts on the label?

I think we can use something similar as IntelliJ, how about "Implement all methods (3 total)"? The completion list usually has limited horizontal space so it's good to be compact.

<img width="327" alt="Screenshot 2019-10-28 at 21 29 48" src="https://user-images.githubusercontent.com/1408093/67719650-24587e00-f9ca-11e9-8691-991aa9e3664e.png">

>  implemented it so that if you have for example 4 abstract methods, but 2 implemented, you still get the option to implement the remaining ones. Is that alright, or do we only want it offered if non of the abstract members are implemented? 

This sounds great, I would expect it to show this completion as long as there are more than one method left to complete (regardless how many are already implemented).

> if there is only one left to implement, there is no need to show it correct?

Correct, this completion item should only appear when there are more than one method to implement.

**Comment by ckipp01** [comment]
@olafurpg I noticed in intelliJ that when you have the below:

```scala
trait Foo {
    def one: String
    def two: String
    val three: String
  }

  val foo = new Foo {
     // hover in here to see message
  }
```
and you click _Implement methods_ if it gives you the option to implement all _members_, not just the methods. I don't want to assume one way or the other, but do we want to do it the same way?

If so, if the user starts typing `def` obviously targeting the methods, should the _Implement all methods_ still put in all abstract members?

**Comment by olafurpg** [comment]
> I don't want to assume one way or the other, but do we want to do it the same way?

Yeah, I think it's OK to implement val/def/var even with the label "Implement all methods". We could use the label "Implement all members" instead if you think that would help, but mirroring the IntelliJ behavior is fine as well.

> If so, if the user starts typing def obviously targeting the methods, should the Implement all methods still put in all abstract members or just the abstract methods?

I think it's OK to complete val/var even if the user typed `def` and selected "implement all methods". I'm not sure how useful it would be to have a completion that only overrides the `def` members while leaving abstract val/var members unimplemented.

**Comment by ckipp01** [comment]
Now that #1031 is merged, do we want to close this, or is there still another use case to implement. For example in the initial example, if you were to trigger a completion at the following position
```scala
  trait Foo {
    def foo(i: Int): String
  }

  val foo = new Fo@@
```
I know IntelliJ would provide a complete option to finish creating `Foo` and also have the members included. I guess this would be like a "create class with members" completion. Is that something we also want to offer?

**Comment by olafurpg** [comment]
This issue can be closed!

I think the current solution is fine. I'm not sure we should offer to complete all members when writing `new Foo@@`. As a general rule of thumb, I think completions  should not try to guess too many steps in advance (the parameter autofill completion violates this principle). The more steps you try to guess ahead of time the harder it gets to match the intuition of the user. It's better IMO to try and complete only simple steps one at a time.

Down the road, I think it would be nice to provide "implement all members" as a code action when there's a compile error about unimplemented members. However, that can be tracked in a separate feature request.
