### ISSUE TITLE
Bad interaction between local dev and remote container dev

### ISSUE THREAD

**Issue by inkytonik** [scalameta/metals#1009]
**Description**

If you start Metals on your local machine everything works fine. Then if you reopen that folder in a "remote" Docker dev container the Bloop server can't be contacted. I suspect it is because the .bloop folder created on the local machine is also used by the Docker dev instance but the information in there is not valid for the container.

**To Reproduce**

1. Check that the dev container setup is working:
  * Start with a clean unpack of the project [metals-test.zip](https://github.com/scalameta/metals/files/3753190/metals-test.zip)
  * Open VSCode in that folder with the Metals extension and the Remote Development Extension Pack installed
  * VSCode will offer to reopen in container, say yes
  * import build into Metals, bloop installs
  * metals functionality is working and there are no Bloop errors
2. Exit VSCode and remove target, .metals and .bloop folders
3. Check that local setup is working:
  * Open VSCode again in the folder
  * VSCode will offer to reopen in container, say no
  * import build into Metals, bloop installs
  * metals functionality is working and there are no Bloop errors
4. Reopen the folder in the container:
  * Invoke "Remote-Containers: Reopen in Container" command
  * VSCode reopens in the container
  * metals/bloop starts
  * eventually get "Failed to connect with build server, no functionality will work. See logs for more details"
  * see [log.txt](https://github.com/scalameta/metals/files/3753194/log.txt)

**Expected behavior**

Metals/Bloop should work both on the local machine and in the container. As things stand, to switch between local and remote development you need to manually remove at least the .bloop folder and wait for installation to happen again.

**Installation:**

- Operating system: macOS 10.14.6
- Editor: Visual Studio Code 1.39.2
- Metals version: 1.6.0

**Comment by olafurpg** [comment]
Thank you for reporting!

>  As things stand, to switch between local and remote development you need to manually remove at least the .bloop folder and wait for installation to happen again.

I believe this is working as expected, `.bloop/` config files are not portable between computers. Those config files point to jars from the local file system cache which would also need to be copied over to the remote machine. I'm not sure there is much we can do about this in Metals.

What happens when you run `sbt compile` locally first, and then `sbt compile` in the docker container?

**Comment by inkytonik** [comment]
I suppose it's a question of how much a user knows about what is in that folder. I expected that this might work, since I don't know anything about the details of the bloop setup.

`sbt compile` is fine in the sense that, starting from a clean folder, `sbt compile` locally builds as usual, then running in the same folder mounted in a container, it also builds properly. It does recompile everything, but there are no errors. It seems that the different sbt invocations clobber something however, since each time you run on local/remote it has to recompile (even if just running).

While perhaps sharing these folders is not easily possible, perhaps the Metals extension can make the user experience a bit nicer. At the moment it appears to be importing the project as normal in the container, but then gets an error about not being able to contact the Bloop server and sending the user off to the logs. Instead, could it detect that the existing folder(s) come from another machine and warn the user, let the user say "yes, please remove them and re-import the project"? At least this would avoid some confusion.

**Comment by olafurpg** [comment]
I agree the error handling in this situation could be improved. One improvement we can do on the Metals side is to include the absolute path of the workspace when digesting the build structure

https://github.com/scalameta/metals/blob/68459a7a9fede5cb56685012a2aa8f01a86a8125/metals/src/main/scala/scala/meta/internal/builds/Digest.scala#L179

This might allow Metals to detect when the container has moved to the container and prompt the user to re-import the build. Is this something you would be interested in working on @inkytonik ?

**Comment by inkytonik** [comment]
Thanks, that sounds like a useful improvement. I'd love to help out but have no free bandwidth at the moment. I'll check the issue status once our teaching semester is over in a couple of months and the (southern) summer begins...

**Comment by olafurpg** [comment]
Sure thing, I opened #1015 which should make Metals prompt you to re-import the build when moving to a docker container.
