### ISSUE TITLE
Can I use IDE features of Metals on "Java files" in mixed Java/Scala projects with sbt?

### ISSUE THREAD

**Issue by JSQQQQQQ** [scalameta/metals#1035]
**Question**
Can I use IDE features of Metals (see errors, goto definition, completions, etc) on **Java files**?
(e.g. Click 'Go to Definition' on a Java file opens a corresponding Scala file)

I have a Java/Scala project which use **sbt as its build tool**. As far as I know, Metals supports IDE features only for Scala files. Since Metals doesn't support Java files no Java plugins support sbt, VSCode + Metals + (Some Java plugins) combination isn't as useful as IntelliJ.

**Installation:**

- Operating system: Linux (Windows WSL)
- Editor: Visual Studio Code
- Metals version: v1.6.2

**Additional context**
The Java plugin I uses is Language Support for Java(TM) by Red Hat

**Search terms**
sbt, Java

**Comment by gabro** [comment]
Unfortunately not, it’s not possible yet.
There’s an open feature request tracking this here https://github.com/scalameta/metals-feature-requests/issues/5
