### ISSUE TITLE
Worksheet mode

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1040]
It would be nice if there was a "worksheet mode" that allows you to interactively evaluate toplevel statements inside the editor and see the results. 

Some challenges:

- how to extract static types and runtime values? We could build on top of the Scala REPL or mdoc (https://scalameta.org/mdoc/)
- what will be the JSON-RPC protocol? We could maybe build on top of http://dotty.epfl.ch/docs/usage/worksheet-mode-implementation-details.html or use the Debug Adapter Protocol
- how to display values in the editor? We can use VS Code decorations https://code.visualstudio.com/api/references/vscode-api#TextEditorDecorationType but that approach may not work well with multi-line output.

**Comment by olafurpg** [comment]
Have a basic working implementation that

* shows evaluated code in-line next to the code using non-editable text decoration. This works only with VS Code for now but I believe it should be possible to do the same for other editors, at least Emacs.
* evaluates code using [mdoc](https://scalameta.org/mdoc/), this gives us fine grained control over rendering of values (including for example infinite `Stream` types), diagnostics, cancellation support, and more. I'm sure it would have been possible to achieve similar functionality with `ScalaInterpreter` from Almond but I am less familiar with that API. 

A small preview

![2019-11-03 17 33 09](https://user-images.githubusercontent.com/1408093/68091859-0765f400-fe7d-11e9-9b2c-5e31fb4b1a55.gif)

Will try to open a PR as soon as I get around to clean up the branch.

**Comment by olafurpg** [comment]
@ekrich this is a "minimal" worksheet implementation to get the ball moving. The current implementation doesn't provide several features that I would love to support down the road

* evaluate parts of the document (e.g., notebook cells) to avoid repeating slow computation
* displaying rich media objects (plots, charts, progress bars, etc)
* writing documentation in the script. I believe it would be quite straightforward to extend the mdoc-based implementation to support "markdown worksheets" in a similar fashion as R Markdown https://rmarkdown.rstudio.com/

**Comment by robsonpeixoto** [comment]
How to show the type, like intellij and scala-ide?

**Comment by tgodzik** [comment]
@robsonpeixoto best to do it with Hover I think.
