### ISSUE TITLE
Organize imports feature

### ISSUE THREAD

**Issue by maciejbak85** [scalameta/metals#1042]
**Question**

Is there a way in Vscode + metals use organize imports feature which exists in intelliJ for example ?
It optimises imports and remove not used.

**Comment by ckipp01** [comment]
Thanks for the question!

There currently isn't support for this, however, there is a conversation about it over in the feature-requests repo here https://github.com/scalameta/metals-feature-requests/issues/40.

Feel free to give that an upvote or add anything that's missing from the conversation!
