### ISSUE TITLE
Dependency installation failing

### ISSUE THREAD

**Issue by rkbalu** [scalameta/metals#1046]
**Question**

I am new to scala development and i'm setting up environment using vs code + metals. I was able to compile the simple scala. When i start add the dependency using build.sbt, build is failing as below.

I am not sure what i am missing here. any help on this issue would be much appreciated.

**Screenshots**

**build.sbt:**
![image](https://user-images.githubusercontent.com/33522349/68166537-8bda7480-ff5a-11e9-8ce1-a0be06fa84e8.png)

**error**
![image](https://user-images.githubusercontent.com/33522349/68166575-a6145280-ff5a-11e9-86d5-fbb20607aa49.png)

**Installation:**

- Operating system: Windows10
- Editor: Visual Studio Code
- Metals version: v1.6.2

**Comment by tgodzik** [comment]
Thanks for reporting!

It seems that you have 2.12 Scala version set in your build and I think that library works on 2.11.12.

You should most likely do something like:
```
scalaVersion := "2.11.12"
libraryDependencies += "com.microsoft.azure" %% "azure-eventhubs-spark" % "2.3.13"

```

when you use `%%` in your dependencies the Scala version gets added automatically.

We are happy to help, however it's fastest to get an answer to questions on Scala or Scalameta discord.
