### ISSUE TITLE
Make metals activate on .sc files as well as scala files. 

### ISSUE THREAD

**Issue by Baccata** [scalameta/metals#1047]
Metals is currently activated only on Scala files. It should also be activated for `.sc` files, and work in a similar way that it does currently when editing a Scala file in isolation, when no build tool is involved.

BSP discovery should also be enabled when editing these files, to allow for integration with third party tools like ammonite. 

One of the complexity might have to do with the need to tweak the presentation compiler to avoid it erroring when the user starts writing definitions at the top level of the file. There is apparently an already existing `ScalaScript` parser available that could be used to that effect. 

Related to https://github.com/scalameta/metals-feature-requests/issues/17

**Comment by olafurpg** [comment]
Thank you for reporting! There's an open PR adding completion, hover and parameter hint support for `*.sc` scripts #1041. The PR only adds diagnostics support (red squiggles for type errors) in `*.worksheet.sc` files, however. We would need to think more carefully how to support type errors in general `*.sc` files, for example it would be great to support Ammonite scripts with `$ivy` imports.

**Comment by tgodzik** [comment]
We could make each such `*.sc` file as a single source build target with basic scala library - this would work by generating an additional `.json` file for each script during installation.

Though, not sure if that is a perfect solution.

**Comment by olafurpg** [comment]
Fixed in #1041 and is available in 0.7.6+208-90bc4909-SNAPSHOT
