### ISSUE TITLE
Fatal recursive dependency 

### ISSUE THREAD

**Issue by tampler** [scalameta/metals#1049]
Hello using VSCode 1.39.2 with Metals 1.6.2

I've set up a project with a `ProjectRef` dependency on another github. I first did `sbt +update` to resolve the reference project and than built the main project in sbt as usual.

sbt stuff works, but VSCode with Metals fail with the message: `Fatal recursive dependency detected in 'docs': List(docs, root, root)`

Here's my pet [project](https://github.com/Neurodyne/zio-actor-pet)

Thanks for a great plugin
Boris

**Comment by gabro** [comment]
Hi @tampler, thanks for reporting.

The error you're seeing is generated by Bloop when importing your build, so there's not much we can do on the Metals side I'm afraid.

For reference, this is essentially the same as https://github.com/scalameta/metals/issues/768, so it seems an issue with http dependencies. Paging @jvican on this to confirm it's the same issue.

**Comment by gabro** [comment]
@tampler in the meantime, you can try using `git` instead of `https`

```
uri("git://github.com/zio/zio-actors.git"))
```

I'm not sure that fixes the issue, but it's worth trying

**Comment by tampler** [comment]
@gabro Thanks for your hint. Moving to git won't help either. I'll rearrange my project to use submodules instead

**Comment by jvican** [comment]
In general that pattern isn't very well supported in sbt and it can cause lots of trouble. You might want to change it. I believe that changing the `root` name in your referred project to something else should remove the circular dependency. The main issue seems to be you have two `root` projects and Bloop is not capable of seeing they come from different builds.

**Comment by olafurpg** [comment]
Thank you for reporting! I believe it would be best to avoid the `ProjectRef` in general, even if you fix the cyclic issue then you will quickly hit on
https://github.com/scalameta/metals-feature-requests/issues/14 because metals doesn't work well with multiple workspace root directories.
