### ISSUE TITLE
Insert an empty line after the package declaration and before the first auto-import

### ISSUE THREAD

**Issue by floating-cat** [scalameta/metals#1054]
**Describe the bug**
If I create a new scala file, and declare a package declaration. The first auto-import would insert this import after the  package declaration like this:
```
package com.example
import scala.annotation.tailrec
```

**To Reproduce**
1. Create a new scala file.
2. Add a package declaration.
3. Write a simple code to trigger the first auto-import.

**Expected behavior**
A new empty line should be inserted before this import.
```
package com.example

import scala.annotation.tailrec
```
Most people write Scala use this code style.

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code/Emacs
- Metals version: v0.7.0

**Additional context**
Though scalafix can (may, I haven't try) fix this problem, but I think the Metals should provide this good code style by default.

**Comment by gabro** [comment]
I've transferred this issue to the main Metals issue tracker, since @ckipp01 is working on it
