### ISSUE TITLE
Exhaustive match not working with upper type bounds

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1066]
**Describe the bug**
Give the following code, if you trigger a completion at the marked position, you'll see that you can complete a basic match, but there is no option for an "exhaustive match" like you'd expect since the `Test` is a sealed trait.

```
package example

object Example extends App {
  sealed trait Test
  final case object Foo extends Test
  final case object Bar extends Test

  def testExhaustive[T <: Test](test: T): Boolean = 
    test m@@
    
}
```

You can see this in the below image
<img width="752" alt="Screenshot 2019-11-22 at 11 24 50" src="https://user-images.githubusercontent.com/13974112/69418369-d6117300-0d1a-11ea-9709-510442359cf5.png">

**To Reproduce**
1. Copy the code snippet above
2. Trigger a completion at the `@@`
3. See that no exhaustive match completion is available

**Expected behavior**
There should be an exhaustive match open that will auto-complete both the `Foo` and `Bar` cases

**Installation:**
- Operating system: macOS
- Editor: Neovim
- Metals version: Latest Snapshot

EDIT: I had a poor example and image. I've updated it now to be more clear.

**Search terms**
completion, exhaustive match, upper type bounds, metals is awesome

**Comment by olafurpg** [comment]
Metals uses an API called `Symbol.knownDirectSubclasses` to provide exhaustive match completions. The type symbol `T` does not have any known direct subclasses, but we can poke into its upper type bound to get the symbol of `Test` and use `knownDirectSubclasses`

Example:
<img width="847" alt="Screenshot 2019-11-15 at 09 32 20" src="https://user-images.githubusercontent.com/1408093/68963098-02f9df00-078b-11ea-8ae0-414504806ea9.png">

Note that `knownDirectSubclasses` requires the type to have the `sealed` modifier

**Comment by ltrojanowski** [comment]
I'll have a look at this
