### ISSUE TITLE
File is renamed even when the renamed toplevel symbol partially matches the filename

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#1074]
**Describe the bug**
Reported on Gitter by @kubukoz 

> renaming a top-level symbol can rename the file if the file ends with (symbol).scala.
> Because of that, if we're in a file like "FooBar.scala" and have this code:
> 
> ```scala
> object Bar
> 
> object FooBar
> ```
> 
> if we rename `Bar`, the file will also be renamed. 
> to be honest I'd look for exact matches of filename.scala and object filename / class filename etc.

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.7.6-master

**Additional context**

**Search terms**
rename, filename, toplevel

**Comment by tgodzik** [comment]
Thank god for @kubukoz ! Testing things that I should have in the first place :sweat_smile: 

I'll take a look, should be simple to fix.

**Comment by gabro** [comment]
@tgodzik I have already a WIP branch with it, I can push a PR soon :)

**Comment by tgodzik** [comment]
> @tgodzik I have already a WIP branch with it, I can push a PR soon :)

Cool! I will take a look when you push it then :+1:
