### ISSUE TITLE
Type parameters/aliases can't be renamed to `equals`, `hashCode`, etdc.

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1076]
**Describe the bug**
Currently renaming types follows the same limitations as methods/fields, which means they can't use certain kind of names. While that's a sane thing to do for starters, it's probably a bug as type parameters can have this kind of name and not break your code.

**To Reproduce**
1. `type Foo = Int`
2. Rename `Foo` to `equals` or any of the blacklisted names
3. You get an error

**Expected behavior**
No errors

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: local snapshot (from eecfc753249b34ecf64e54d57f510eab1dd617e1)

**Comment by olafurpg** [comment]
Thanks for reporting! I'm personally fine with saying it's "working as intended". I would prefer to be on the more conservative side with regards to what renamings are allowed and prioritize improving the most common use-cases for renaming symbols.

**Comment by kubukoz** [comment]
Fair enough!
