### ISSUE TITLE
Document how metals integrates with Debug Adapter Protocol to run applications and tests 

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals#1078]
**Describe the bug**
Metals now support running applications and tests but the feature works only  on vscode and is depending on debug adapter protocol. 

If we want this feature to work on the other editors (Atom/Vim/Sublime/Emacs), documentation needs to provided so developers can work on providing this feature. 

**Search terms**
Debugger, java, scala

**Comment by olafurpg** [comment]
Thank you for reporting! Could you take a look @marek1840 ?

**Comment by marek1840** [comment]
> Could you take a look @marek1840 ?

Certainly, I will look into it.
