### ISSUE TITLE
LSP :: Unsupported request method: textDocument/willSaveWaitUntil

### ISSUE THREAD

**Issue by kostafey** [scalameta/metals#1083]
**Describe the bug**
Save Scala file in Emacs leads to the message:
`LSP :: Unsupported request method: textDocument/willSaveWaitUntil`

Version: `org.scalameta:metals_2.12:0.7.6` Scala `2.13.1` sbt `1.3.3`

**To Reproduce**
1. Create & configure & build Scala project
2. Open any Scala file in Emacs, make some changes
3. Save it (e.g. via <kbd>M-x save-buffer</kbd>)
4. See the error in `*Messages*` buffer 
`LSP :: Unsupported request method: textDocument/willSaveWaitUntil`

**Expected behavior**
Looks like `textDocument/willSaveWaitUntil` is an ordinary LSP command:
https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/

**Comment by ayoub-benali** [comment]
The client (Emacs) should not send this request as it is not supported by the server. 
The server publish the list of available requests during initialization, so the client should later allow only what the server can handle.
I think this a bug client side.

**Comment by ckipp01** [comment]
I wasn't able to reproduce this in emacs @kostafey. Are you using [lsp-mode](https://github.com/emacs-lsp/lsp-mode) or a different client?

**Comment by kostafey** [comment]
@ckipp01, yes, it's an `lsp-mode-20191123.1747` (installed from MELPA).
I've created a related issue for the client: https://github.com/emacs-lsp/lsp-mode/issues/1199. 
Any plans for future support `textDocument/willSaveWaitUntil` command?

**Comment by ckipp01** [comment]
I'll continue to play around with this a bit to see if I can reproduce it.

>  Any plans for future support textDocument/willSaveWaitUntil command?

As far as I know, no, this currently isn't on the roadmap. However, if this is something you'd like to see added to Metals, we do have a [features request](https://github.com/scalameta/metals-feature-requests/issues) issue tracker that you can add the request to. Then we plan to work on things based on interest. So it'd help if you could provide an example of what this would offer and an example of why you'd like to see it implemented, etc.

**Comment by kostafey** [comment]
Current most straightforward workaround:
`(setq lsp-before-save-edits nil)`

**Comment by ckipp01** [comment]
Looks like a fix was just pushed in [lsp-mode](https://github.com/emacs-lsp/lsp-mode/commit/ecddf3c25013451a4fbda1c035dfe9d837de6bf1). Are you able to give this a try @kostafey and report back if it fixes your issue?

**Comment by kostafey** [comment]
@ckipp01 Yes, the latest update of the client fixes this issue.
