### ISSUE TITLE
Rename symbol not working on named parameters in constructor

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1086]
**Describe the bug**
Given the following code snippet, if I do a rename symbol on `isRenameAwesome` parameter, it doesn't seem to correctly rename the named parameter as I would expect.

```scala
package example

object Example extends App {

  class Test(isRenameAwesome: Boolean)
  val x = new Test(isRenameAwesome = true)

}
```

**To Reproduce**
1. Use the code above
2. Rename the `isRenameAwesome` parameter
3. See if the named parameter where x is created is renamed

**Installation:**
- Operating system: macOS
- Editor: Visual Vim
- Metals version: Latest Snapshot

**Additional context**
I'm not 100% sure if this is limited by this https://github.com/scalameta/scalameta/issues/1169 or if it is a different issue.

**Search terms**
rename symbol, named parameters

**Comment by ckipp01** [comment]
So I've been looking into this a bit, and I see that you have the semanticdb label added to this @tgodzik. Is that meaning the fix for this needs to happen in scalameta? I basically took the example
```scala
package example

object Main {

  class Foo(isRenameAwesome2: Boolean)
  new Foo(isRenameAwesome = true)
}
```
And only the definition of `isRenameAwesome` shows up in `SymbolOccurrence`s.
```scala
        SymbolOccurrence(Some(Range(5, 9, 5, 9)), "example/Main.Foo#`<init>`().", REFERENCE),
        SymbolOccurrence(Some(Range(4, 12, 4, 27)), "example/Main.Foo#isRenameAwesome.", DEFINITION),
        SymbolOccurrence(Some(Range(5, 6, 5, 9)), "example/Main.Foo#", REFERENCE),
        SymbolOccurrence(Some(Range(4, 8, 4, 11)), "example/Main.Foo#", DEFINITION),
        SymbolOccurrence(Some(Range(0, 8, 0, 15)), "example/", DEFINITION),
        SymbolOccurrence(Some(Range(4, 11, 4, 11)), "example/Main.Foo#`<init>`().", DEFINITION),
        SymbolOccurrence(Some(Range(2, 7, 2, 11)), "example/Main.", DEFINITION),
        SymbolOccurrence(Some(Range(4, 29, 4, 36)), "scala/Boolean#", REFERENCE)
```
Is the idea for this to be captures via semantic db and therefore fixed in scalameta, or where you thinking of taking a different approach for this to capture that reference?

**Comment by tgodzik** [comment]
It would be best to capture that on the scalameta semanticdb plugin. I tried to add the label to anything that we need to fix there.
