### ISSUE TITLE
Sort auto-completed exhaustive match'es by declaration order

### ISSUE THREAD

**Issue by sjrd** [scalameta/metals#1175]
**Is your feature request related to a problem? Please describe.**

When I use the `match (exhaustive)` autocompletion option, the auto-completed text sorts the `case`s in an order that appears arbitrary to me. Perhaps it is even random? (here it looks alphabetic but in larger examples it definitely isn't) For example I could get:
```scala
    typeRef match {
      case ClassRef(className) => 
      case PrimRef(tpe) =>
    }
```
This is a bit frustrating because I systematically have to reorder the cases to match the order of definition of the ADT, which is a logical order, and so that it is consistent in my entire codebase.

**Describe the solution you'd like**

I would like the autocompletion to sort the cases in the same order as their definitions. So since I defined `NonArrayTypeRef` as follows:
```scala
  sealed abstract class NonArrayTypeRef extends TypeRef

  /** Primitive type reference. */
  final case class PrimRef(tpe: PrimTypeWithRef) extends NonArrayTypeRef

  /** Class (or interface) type. */
  final case class ClassRef(className: ClassName) extends NonArrayTypeRef
```
I would like the autocompletion to sort the cases in the same order:
```scala
    typeRef match {
      case PrimRef(tpe) =>
      case ClassRef(className) => 
    }
```

**Describe alternatives you've considered**

Well currently I just resort them manually after using the autocompletion. It's not a big deal for a match with two cases, but it gets very annoying past 4 or 5 cases.

**Additional context**

**Search terms**:

`match` `exhaustive` `autocompletion` `autocomplete` `order` `sort`

**Comment by gabro** [comment]
This has been implemented in https://github.com/scalameta/metals/pull/1174
