### ISSUE TITLE
Improve experience of upgrading Bloop 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1190]
Currently, Metals explains to the user that that there's an old version of Bloop running on the computer. However, this message doesn't explain how to fix the problem.

It would be nice if the message explained more details how to upgrade, something like:

> You have Bloop v1.3.4 installed and Metals requires at least Bloop v1.4.0.
> If you installed bloop via a system package manager (brew, aur, scoop), please upgrade manually.
> If not, select "Turn off old server".
> Options: I'll update manually | Turn off old server | Not now

**Comment by ckipp01** [comment]
I played around with this today, and I'm curious about your thoughts on how you'd like this to actually work. I downloaded and ran an old version of bloop, and then tried to import a project. As expected, I see this.

<img width="757" alt="Screenshot 2019-12-20 at 14 54 16" src="https://user-images.githubusercontent.com/13974112/71259578-09a2e580-2339-11ea-9fb5-1655c092f71a.png">

After clicking more info, I'm then brought to Doctor, where I see the relevant information.

<img width="746" alt="Screenshot 2019-12-20 at 14 58 49" src="https://user-images.githubusercontent.com/13974112/71259754-70c09a00-2339-11ea-8d4e-c14a1b6de74b.png">

So, in this scenario, would those options you have listed...
> Options: I'll update manually | Turn off old server | Not now
appear in Doctor?

Also, what would be the difference between `I'll update manually`, and `Not Now`?

**Comment by olafurpg** [comment]
@ckipp01 those options would appear in the original `window/showMessageRequest`. Instead of pointing people to the doctor, we let the users fix the problem right away in the request.

> Also, what would be the difference between I'll update manually, and Not Now?

None. By convention, we try to always keep a "Not now" option that's safe to choose but comes at the cost of degraded user experience. We could drop the "I'll update manually" option but it wouldn't be so clear that's how the user fixes the problem 🤔
