### ISSUE TITLE
OnDemandSymbolIndex doesn't distinguish between build targets

### ISSUE THREAD

**Issue by mzarnowski** [scalameta/metals#1196]
Currently, despite having the same symbol (let's say class `foo.bar.Baz`) defined in two modules, there would be only one mapping `foo.bar.Baz -> SourceFile` in the OnDemandSymbolIndex and it would be the one being indexed last, so some race conditions could apply making some of the other features nondeterministic.

**Comment by kubukoz** [comment]
I'm not sure if this is 100% the same problem, but I noticed I see references to a symbol defined in module A in module B (if there's the same symbol in B), even if they don't share a classpath.

Renames also get applied on all the references across modules, which can be quite a problem for multi-module builds.

**Comment by tgodzik** [comment]
@kubukoz we assume that a symbol is unique within a workspace so that is kind of related problem yeah. In case of references we should most likely filter out symbols coming from unrelated build targets and that will fix renames as well.

**Comment by tgodzik** [comment]
Followed up with https://github.com/scalameta/metals/issues/2265

**Comment by tgodzik** [comment]
Fixed in https://github.com/scalameta/metals/pull/2668
