### ISSUE TITLE
Write unit tests for code actions' handling of unsaved edits

### ISSUE THREAD

**Issue by cb372** [scalameta/metals#1231]
In the discussion of #1079 it was suggested that a unit test would be useful to check that the code action does the right thing when a file has unsaved edits (i.e. the parameter names are inserted at the correct offsets).

I managed to confirm via manual testing in VSCode that the code action works as expected in the face of unsaved edits. But I tried and failed to write a test for it.

This issue is to track the missing unit test. As we write more code actions, we'll probably want to write similar tests for all of them, so it would be good to get this sorted sooner rather than later.

**Comment by tgodzik** [comment]
Code lenses seem to be working correctly and are already tested enough, let's close this. We can add the tests if needed.
