### ISSUE TITLE
Can't compile metals locally

### ISSUE THREAD

**Issue by ri-cisse** [scalameta/metals#1233]
**Describe the bug**

**To Reproduce**
1. clone metals
2. run sbt publishLocal
3. see screenshot below fro error

**Expected behavior**

Should compile correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/53084954/71586584-09fe6600-2b1b-11ea-874c-d6366f3444a1.png)

**Installation:**
- Operating system: macOS
- Editor: N/A
- Metals version: master

**Additional context**

**Search terms**

**Comment by gabro** [comment]
Hi, thanks for reporting! I can't reproduce on my machine (macOS) and the CI seems to be ok with it too. Have you tried with a `clean` before `publishLocal`?

**Comment by olafurpg** [comment]
Thank you for reporting! What happens if you disable all global plugins?

**Comment by ri-cisse** [comment]
Thanks for the quick reply.

I disabled all global plugins and clean before publishLocal. Still getting the same error.

Could this be the culprit?
![image](https://user-images.githubusercontent.com/53084954/71587726-1f758f00-2b1f-11ea-9d5b-947fac41f424.png)

**Comment by olafurpg** [comment]
@ri-cisse I am unable to reproduce, I can build the project locally. Do you have any gitignored `*.sbt` files?

**Comment by ri-cisse** [comment]
I finally got this to work by delete coursier caches `~/Library/Caches/Coursier`.

Thanks.
