### ISSUE TITLE
Worksheets hang on diagnostics without positions

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1236]
**Describe the bug**

Worksheets don't evaluate when the document has unpositioned diagnostics.
**To Reproduce**
1. Open `Foo.worksheet.sc` file
2. type
```scala
trait X[F[_]]
val x = 3
```
3. save file

**Expected behavior**

I expected evaluation to complete.

A workaround is to add the following line

```scala
import scala.language.higherKinds
```

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: 0.7.6+641-25d169c8-SNAPSHOT

**Additional context**

Reported here https://gitter.im/scalameta/metals?at=5e0c6abafd580457e7a7bd18
**Search terms**

Evaluating worksheet

**Comment by ckipp01** [comment]
I was looking at the #1237, and I don't actually fully understand why this happens. Why is it that if we have the same trait in your example in a file, it will compile fine without any diagnostics being returned, but then in a worksheet, there are diagnostics returned without a position?

**Comment by gabro** [comment]
It does return a diagnostic, a warning without a position, if I understand this correctly

**Comment by olafurpg** [comment]
The scala compiler sometimes reports diagnostics with empty positions for things like “there are deprecation warnings, enable -deprecation to see details”. 

In LSP, diagnostics must have a location to place such messages so I believe we ignore them in normal scala files.

**Comment by gabro** [comment]
Closed by #1237
