### ISSUE TITLE
When pasting at the start of  a multiline string pipe is added unnecessarily

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1244]
**Describe the bug**
When pasting in a multiline string with existing `|` a new `|` is added before the string itself/

**To Reproduce**
1.Make sure `On paste formatting` is enabled
2.Create multiline string like:
```
s"""| this is@@ a multiline
      | string
      |""".stripMargin
```
3. Paste something not multiline at the position of `@@`
4. `|` will be added before the `s"""`

**Expected behavior**
Nothing should be added there.

**Screenshots**

![image](https://user-images.githubusercontent.com/3807253/71730474-8908dc80-2e42-11ea-8aa3-3c58e07d3f20.png)

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: newest snapshot

**Search terms**
multiline on paste formatting pipe

**Comment by ckipp01** [comment]
At least the pipe is in the right position 😉 .

I see where I went wrong when I did this, and working on a fix now.

**Comment by tgodzik** [comment]
> At least the pipe is in the right position  .
> 
> I see where I went wrong when I did this, and working on a fix now.

Thanks!
