### ISSUE TITLE
Metals + Coc shows three identical autosuggest/autcomplete entries

### ISSUE THREAD

**Issue by jsatk** [scalameta/metals#1263]
**Describe the bug**
I see three of every auto-suggestion/complete when using Metals with [Coc](https://github.com/neoclide/coc.nvim).

**To Reproduce**
1. Type literally anything into a Scala file that will have autocomplete suggestions.
2. Observe that there are three identical suggestions rather than just one.

**Expected behavior**
1. Type literally anything into a Scala file that will have autocomplete suggestions.
2. Observe that there is only one suggestions.

**Screenshots**
http://i.jsatk.us/62uvPy

**Comment by ckipp01** [comment]
@jsatk I'm not sure if you've also tried the [`coc-metals`](https://github.com/ckipp01/coc-metals extension or not, but if you did, can you ensure you don't have metals registered both manually and the extension installed. If you do, that can lead to behavior like this since two engines will be feeding completion information to coc.

You can do a `:CocConfig` and `:CocLocalConfig` to check what you have under `languageserver`, and then a `:CocList extensions` to see the installed extensions. You want to make sure you don't have both existing at the same time.

**Comment by jsatk** [comment]
That might be it. I’ll check tomorrow and report back. Thanks for the prompt reply.

**Comment by jsatk** [comment]
@ckipp01 I do indeed have `coc-metals` extension installed as well as the following in my `coc-settings.json`:

```json
    "metals": {
      "command": "metals-vim",
      "rootPatterns": [
        "build.sbt"
      ],
      "filetypes": [
        "scala",
        "sbt"
      ]
    }
```

Is this incorrect? Should I remove this snippet from the `coc-settings.json`?

**Comment by jsatk** [comment]
After removing the `metals` section from `coc-settings.json`, deleting the `.metals` & `.bloop` folder, and re-importing via Coc + Metals I am down to _two_ duplicate recommendations rather than three. So improvement. But would love to get it down to only one. 
<img width="603" alt="Screen Shot 2020-01-07 at 10 41 32 AM" src="https://user-images.githubusercontent.com/1005550/71919823-66284200-313a-11ea-8dcf-403f80256ab9.png">

**Comment by jsatk** [comment]
It appears the installation instructions have changed here: https://scalameta.org/metals/docs/editors/vim.html#installing-coc-metals

I'd previously installed `metals-vim` via a coursier command.

```
./coursier bootstrap \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=coc.nvim \
  org.scalameta:metals_2.12:0.7.6 \
  -r bintray:scalacenter/releases \
  -r sonatype:snapshots \
  -o /usr/local/bin/metals-vim -f
```

After I manually `rm -f /usr/local/bin/metals-vim` I'm only getting one LSP suggestion via Coc's autosuggest.

Gonna do a bit more testing and then close this issue if doing these two things fixes it.

**Comment by ckipp01** [comment]
I'm glad you seem to have gotten it figured out @jsatk! What you did was exactly what I would have recommended. By having both the coc-metals extension installed and it manually in your `coc.settings.json` it was starting two different instances of Metals when you opened a project.

The docs were hugely updated a couple of weeks ago when `coc-metals` was released. If you have any other questions, don't hesitate to ask.
