### ISSUE TITLE
Import completions for methods should not insert parentheses

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1281]
Seems to be related to #251, but in reverse.

Edit: oops, didn't notice that's the old completions.

**Describe the bug**

When importing a method with parameters, parentheses are inserted. That's illegal in Scala and shouldn't happen.

**To Reproduce**
1. Create an object with a method taking parameters
2. Import that object's method in another object
3. See the parens appear

Here's an example of a file exhibiting this:

```scala
package example

object demo {
  def method(a: Int) = a
}

object usage {
  import demo.m<tab>
}
```

**Expected behavior**
No parentheses are inserted in imports.

**Screenshots**

![image](https://user-images.githubusercontent.com/894884/72113270-3f3b5d00-3340-11ea-8d69-3f3861b2dd7e.png)

![image](https://user-images.githubusercontent.com/894884/72113282-46fb0180-3340-11ea-8924-70d9f96cf96e.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: 0.7.6+720-7b699bd6-SNAPSHOT

**Search terms**
parentheses, suggestions, completions, imports, import

**Comment by tgodzik** [comment]
Thanks for reporting! I think this should be relatively easy to fix.

**Comment by kubukoz** [comment]
I found the place (and even a way to determine whether we're completing an import) and I think I'll have a fix soon :)

basically if `autoImportPosition` in CompletionProvider is empty, that means we're  an import. At least as far as I understand...
