### ISSUE TITLE
'test' and 'debug test' code lenses seem swapped

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#1296]
**Describe the bug**
Maybe I'm understanding this wrong, but I would expect this behavior

- `test` -> run a test suite normally
- `debug test` -> run a test suite and set breakpoints

**To Reproduce**
- Set a breakpoint in a test
- Try `test` and `debug test` code lenses
- When using `test` the breakpoint fires
- When using `debug test` the breakpoint is ignored

**Expected behavior**
See above.

**Screenshots**

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Search terms**
debug, test, breakpoint

**Comment by marek1840** [comment]
Is it also swapped for non-test cases?
Looking at the code ([test-related lenses](https://github.com/scalameta/metals/blob/master/metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala#L114) and  [main-related lenses](https://github.com/scalameta/metals/blob/master/metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala#L130)) it seems OK.

**Comment by gabro** [comment]
Fixed in the extension.
