### ISSUE TITLE
Code navigation and worksheets do not work with "Seed" build tool.

### ISSUE THREAD

**Issue by megri** [scalameta/metals#1302]
**Describe the bug**
Code navigation + worksheets is broken with this setup. Worksheets won't work at all and code navigation does not work for external definitions (libs, scala-std library etc.). Code navigation *does* work for local source code.

Compilation works, and running tests/main works. Metals' log doesn't show anything interesting from what I can see and doctor indicates that everything is working as intended. I'm guessing the bloop config seed generates is lacking somehow, but I can't figure out how.

**To Reproduce**
Please see https://github.com/megri/metals-0.8-seed-bug for a complete reproduction of the problem.

**Environment**
* Seed version 0.1.6
* Bloop version 1.4.0-RC1
* Editor: VS Code
* Metals version 0.8.0

**Comment by tgodzik** [comment]
Thanks for reporting! For code navigation it is important to include source jars  in the bloop configuration. For example in `sbt` we generate:
```
        "resolution" : {
            "modules" : [
                {
                    "organization" : "org.scala-lang",
                    "name" : "scala-library",
                    "version" : "2.12.10",
                    "artifacts" : [
                        {
                            "name" : "scala-library",
                            "path" : "/home/tgodzik/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.10.jar"
                        },
                        {
                            "name" : "scala-library",
                            "classifier" : "sources",
                            "path" : "/home/tgodzik/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.12.10-sources.jar"
                        },
                        {
                            "name" : "scala-library",
                            "classifier" : "javadoc",
                            "path" : "/home/tgodzik/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.12.10-javadoc.jar"
                        }
                    ]
                }
            ]
        }
```

So I think seed might not be generating that. As for worksheets, I am not sure what might be the issue exactly. There shouldn't be anything Build Tool specific @olafurpg any idea?

**Comment by megri** [comment]
@tgodzik Thanks for getting back.

It seems if those artifacts are only used for Metals to work, perhaps they should be added automatically just like semanticdb?

**Comment by olafurpg** [comment]
Thank you for reporting! What editor are you using?

**Comment by olafurpg** [comment]
In the reproduction repo, where did you create the worksheet file?

**Comment by megri** [comment]
@olafurpg 
Sorry, I missed telling that. I'll update the ticket.
I created the worksheet in the root of the project. It's all in the repo I linked :)

**Comment by olafurpg** [comment]
Worksheets need to be named “*.worksheet.sc”. This requirement is not very well documented on the website.

**Comment by megri** [comment]
@olafurpg That seems to work better. I note that the worksheet needs to be located inside a bloop project, so in my case I need to place the file under `src/`.

**Comment by tgodzik** [comment]
> @tgodzik Thanks for getting back.
> 
> It seems if those artifacts are only used for Metals to work, perhaps they should be added automatically just like semanticdb?

Resolving SemanticDB is implemented inside Bloop and it is rather an exception. It might be too complex to resolve the sources themselves. However, resolving sources is already being done rather easily inside Maven/Gradle/Sbt/Mill.  

Would it be possible for Seed to maybe have an additional flag to include sources? It should be simple enough via coursier to do.  I am afraid we might not have time at all to work on it on the Metals side. With the additional flag we could launch seed automatically inside Metals, which we could help with the implementation.

**Comment by megri** [comment]
First off, I apologise for the diversion. I just found there is a global Seed setting that lets it download all sources and javadocs for artifacts. It already adds scala-library.jar and with the additional configuration it also fetches the -source.jar and -javadoc.jar artifacts.

Though this conversation helped me resolve the issue, it is no longer valid and thus I'll close it.

**Comment by olafurpg** [comment]
@megri thank you for the update and reporting the issue. It’s great to have these discussions on GitHub in case other Seed users hit on similar issues.
