### ISSUE TITLE
Metals fails compilation of an sbt project with "compile-internal" inter-module dependency

### ISSUE THREAD

**Issue by antonoal** [scalameta/metals#1305]
**Describe the bug**
I've got a multi-module sbt build with one module containing a few macros. Then there's another module that depends on the macros one with "compile-internal" setting. Metals fails to recognize the dependency and fails with "object is not a member of package"

**To Reproduce**
Just import an sbt build with a compile-internal module dependency

**Expected behavior**
This started failing only in metals 0.8.0. Before that everything compiled OK.

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.8.0
- Scala 2.12

**Comment by olafurpg** [comment]
Thank you for reporting. I’m not familiar with “compile-internal”. Can you please provide more information? For example a repo that reproduces the problem or at least the sbt setttings

**Comment by antonoal** [comment]
I've created a gist here: https://gist.github.com/antonoal/1f88d0e95cb1026675d008694f966e97
In essence compile-internal allows me to wipe the module with macros out from .pom so it wouldn't be visible as a dependency to the users of my lib

**Comment by olafurpg** [comment]
Thank you for the minification. This is an sbt-bloop issues, the build import is not implemented in Metals. Can you please open an issue in the Bloop repo?

This might get closed however with working as intended since “compile-internal” is not a public sbt API. There are other ways in sbt to hide Pom dependencies, for example with “pomPostProcess”

**Comment by antonoal** [comment]
I've raised it with bloop. Btw this _is_ a public API: https://www.scala-sbt.org/1.x/docs/Macro-Projects.html
