### ISSUE TITLE
Run and Debug Options Not Available in Project Cross-Compiled for ScalaJS

### ISSUE THREAD

**Issue by adamgfraser** [scalameta/metals#1308]
**Describe the bug**
I am trying to use the new Metals functionality with Caliban (https://github.com/ghostdogpr/caliban). I am able to import the build successfully but when I do so I don't see the `run` and `debug` options that I see when creating a new workspace from scratch. I think it may have to do with the project being cross built against JVM and ScalaJS. On one occasion I did see the option but since then it has not reappeared despite numerous attempts including deleting `.bloop` and `.metals` folders and uninstalling and reinstalling Metals.

**To Reproduce**
1. Fork Caliban
2. Import the build in Visual Studio Code.
3. Navigate to an executable file (e.g. `ExampleApp.scala`)
4. See that there is no debug or run option above the definition.

**Expected behavior**
I would expect the run and debug options to be available and execute the program.

**Installation:**
- Operating system: MacOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Comment by marek1840** [comment]
Hi, thanks for reporting. 
Was the file you are trying to run compiled? We cannot provide run/debug code lenses for files which weren't compiled.

I have just tried the repository you mentioned and was able to get these results:
![caliban-1](https://user-images.githubusercontent.com/3709537/72626574-428ba580-394b-11ea-9b7f-36679c8c1b5d.png)
![caliban-2](https://user-images.githubusercontent.com/3709537/72626575-428ba580-394b-11ea-9c73-b9957d681ff3.png)

**Comment by adamgfraser** [comment]
Sorry for the delay in getting back to you. I am seeing the run and debug information now. I'm not sure what happened. I tried running and restarting several times without success but maybe some kind of cache on my system had to be updated somewhere. Anyway, thanks again for the great feature!

**Comment by tgodzik** [comment]
> Sorry for the delay in getting back to you. I am seeing the run and debug information now. I'm not sure what happened. I tried running and restarting several times without success but maybe some kind of cache on my system had to be updated somewhere. Anyway, thanks again for the great feature!

The feature is still new, so let us know if you encounter any issues again. Best would be to attach any logs or stack traces you can find. There is risk we have some race conditions that are really hard to detect.
