### ISSUE TITLE
UNRESOLVED DEPENDENCIES: ch.epfl.scala#sbt-bloop;1.4.0-RC1: not found

### ISSUE THREAD

**Issue by FereX98** [scalameta/metals#1313]
**Question**

Metals import sbt build failed to work on VSCode when using remote-SSH to a CentOS machine.
```log
INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
INFO  [warn] 	::          UNRESOLVED DEPENDENCIES         ::
INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
INFO  [warn] 	:: ch.epfl.scala#sbt-bloop;1.4.0-RC1: not found
INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
INFO  [warn] 
INFO  [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
INFO  [warn] 		ch.epfl.scala:sbt-bloop:1.4.0-RC1 (scalaVersion=2.10, sbtVersion=0.13)
INFO  [warn] 
INFO  [warn] 	Note: Unresolved dependencies path:
INFO  [warn] 		ch.epfl.scala:sbt-bloop:1.4.0-RC1 (scalaVersion=2.10, sbtVersion=0.13) (/mnt/ssd/liushi/spark-source/project/metals.sbt#L4-5)
INFO  [warn] 		  +- default:spark-source-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
INFO  sbt.ResolveException: unresolved dependency: ch.epfl.scala#sbt-bloop;1.4.0-RC1: not found
INFO  	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:320)
...(omitted)
```

**Installation:**

- Operating system: CentOS 7 (via remote-SSH from a macOS machine)
- Editor: Visual Studio Code
- Metals version: v1.7.2

**Comment by tgodzik** [comment]
Thanks for reporting, I think that version of Bloop was not released properly. I think @jvican might know more. I can't find the issue this was discussed on :/

**Comment by jvican** [comment]
Thanks for reporting, the discussion for this issue can be found in https://gitter.im/scalacenter/bloop?at=5e2678e8364db33faa05f331
  
Users that want to use sbt-bloop 1.4.0-RC1 need to use `1.4.0-RC1+10-db2d98a1` until the next release is out. I apologize for the inconvenience, the issue seems to involve a Sonatype bug

**Comment by tgodzik** [comment]
Thanks @jvican ! I'll update the version in master so that people can use latest snapshots of Metals with the snapshot of Bloop.

**Comment by olafurpg** [comment]
I am able to resolve 1.4.0-RC1 now for sbt 0.13
