### ISSUE TITLE
jvmopts and coursier repositories are not forwarded do Bloop

### ISSUE THREAD

**Issue by kczulko** [scalameta/metals#1315]
**Describe the bug**
When I've updated my metals installation to 0.8.0 (and 0.8.0 snapshot) I'm unable to properly import my project. I suspect that the issue may be related with my custom cacerts. For previous version (0.7.6) it worked fine. 

When I run my emacs, after some time I get this error:
```
INFO  started: Metals version 0.8.0+17-572f819c-SNAPSHOT in workspace '<my_workspace>'
INFO  time: initialize in 0.76s
INFO  running '/nix/store/wilpyg2acq8fglcchd1gh2340gl1hb8f-jetbrainsjdk-152b1248.6/jre/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStore=<path_to_my_cacerts> -Djavax.net.ssl.trustStorePassword=changeit -Xss2048K -jar /tmp/metals1763162161274481289/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'

...

[D] Waiting for a connection at local:///tmp/bsp-launcher1339486761166939038/bsp.socket...
The server is listening for incoming connections at local:///tmp/bsp-launcher1339486761166939038/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at <my_home>/.cache/metals/bsp.trace.json
ERROR Timeout waiting for 'build/initialize' response
ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:259)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:203)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

WARN  Stopped configuration of SemanticDB in Scala 2.12.10 projects: Error downloading org.scalameta:semanticdb-scalac_2.12.10:4.3.0
  not found: <myhomedir>/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.10/4.3.0/ivys/ivy.xml
  download error: Caught javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.10/4.3.0/semanticdb-scalac_2.12.10-4.3.0.pom
  not found: https://dl.bintray.com/scalacenter/releases/org/scalameta/semanticdb-scalac_2.12.10/4.3.0/semanticdb-scalac_2.12.10-4.3.0.pom
Jan 16, 2020 10:49:31 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
WARNING: Unsupported notification method: textDocument/willSave
```

**Steps to reproduce the behavior:**

This is how metals was installed (I tried both - snapshot and release):
```
coursier -J-Djavax.net.ssl.trustStore=<path_to_my_cacerts> -J-Djavax.net.ssl.trustStorePassword=changeit bootstrap \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=emacs \
  --java-opt -Djavax.net.ssl.trustStore=<path_to_my_cacerts> \
  --java-opt -Djavax.net.ssl.trustStorePassword=changeit \
  org.scalameta:metals_2.12:0.8.0+17-572f819c-SNAPSHOT \
  -r bintray:scalacenter/releases \
  -r sonatype:snapshots \
  -o $HOME/bin/metals-emacs -f
```

I've never used custom bloop installation. It was always embedded one. I suspect that something (bloop?) no longer respects -Djavax.net.ssl.trustStore option (or it wasn't passed somehow there?). Of course I've placed .jvmopts file in the root of my project with the following content (it worked with metals < 0.8.0):
```
-Djavax.net.ssl.trustStore=<path_to_my_cacerts>
-Djavax.net.ssl.trustStorePassword=changeit
```

Moreover, I see that something has changed when it comes to sbt-bloop installation and from now on you use additional .sbt file.
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	project/metals.sbt

nothing added to commit but untracked files present (use "git add" to track)
```

**Installation:**

Operating system: nixos
Editor: emacs
Metals version: v0.8.0 or 0.8.0+17-572f819c-SNAPSHOT

**Search terms:**
build import, javax.net.ssl.trustStore, .jvmopts

**Comment by tgodzik** [comment]
@kczulko Thanks for reporting! That might be an issue with the fact that we don't really add any jvmopts to Bloop.

A workaround would be https://github.com/scalacenter/bloop/issues/761 - but that  would mean manual installation.

I see two long term solutions here:
1. Adding an additional `Build server jvm` option similar to the already existing one
2. Reading .jvmopts and forwarding them to Bloop (though we might need to whitelist some)

I would prefer 1. 2 should most likely be done in in the Bloop sbt plugin - we should open an issue in Bloop.

**Comment by tgodzik** [comment]
And 1. would also add us a lot more flexibility.

2. might actually need to be done in Metals to. Also, it would mean we would have the same .jvmopts as for `sbt`

**Comment by tgodzik** [comment]
Actually if you copy `.jvmopts` to <user_home>/.bloop/ it should be picked up right now.

**Comment by kczulko** [comment]
@tgodzik ,
I can confirm: copying `.jvmopts` to `$HOME/.bloop` forces bloop to respect my custom jvm options. Huge thank you for your help!

Best regards,
Karol

**Comment by tgodzik** [comment]
Renamed to focus on the issue. We need to make sure that the user doesn't need to create an additional file.

**Comment by niderhoff** [comment]
> Actually if you copy `.jvmopts` to <user_home>/.bloop/ it should be picked up right now.

This does not work on Windows as it doesn't seem to pick up my ~/.bloop/.jvmopts file. Any idea how I can check that?

**Comment by tgodzik** [comment]
@niderhoff  the alternative is to set the `http_proxy` or `https_proxy` environment variable with `proxyHostname:proxyPort`.

I will try to check on windows when I get hands on it.

**Comment by tgodzik** [comment]
@niderhoff Och, that seems to be a maven issue when being run from Metals - do you have proper proxy set for it? You might have to run it via you local maven instance. It can be setup in the VS Code settings under `Metals: Maven script`

**Comment by niderhoff** [comment]
Well the proxy variables are set for me. They wouldnt be picked up by java at all. java_opts is set but it is ignored by maven (good catch) in the above but was picked up by metals. I will get working on this maven script and edit this with results.

**Comment by tgodzik** [comment]
> Well the proxy variables are set for me. They wouldnt be picked up by java at all. java_opts is set but it is ignored by maven (good catch) in the above but was picked up by metals. I will get working on this maven script and edit this with results.
> 
> FYI my system maven and intellij both respect the proxy set in ~/.m2/settings.xml. Shouldn't this be the case here, too?

Might be an issue with how we setup maven home, if look at the output it's set to:
`Dmaven.home=C:\Users\niid\AppData\Local\Temp\metals3625874264393058610`
so most likely not picking up because of that.

Maybe we shouldn't set maven home at all? Any idea what it should point to?

**Comment by niderhoff** [comment]
Maven_Home is fine. It should point to the maven binary and in our case here that is the temp folder with the maven wrapper jar. 

I somehow managed that maven picks up the .jvmopts Proxy in the working directory. And got it to download some sources. I will check later if maven also picks up the environment variable JVM_OPTS.

**Comment by tgodzik** [comment]
@niderhoff Cool! Let us know if there are any other issue - you can open up a new issue.

**Comment by logc** [comment]
FWIW, I have had timeout problems with Bloop since forever, and I finally found a way to resolve them which is surprising to me. 

Long story short:

- today I installed Bloop manually with `coursier install bloop`, 
- launched it in the foreground with `bloop server` 

and since then it has finally learnt to pick up the `mirror.properties` preferences file. The mirrors config is needed because my company uses a private repository to mirror Maven Central, as documented [here](https://github.com/scalameta/metals/pull/1356). I saw that last command force the download of a new component, called `bloop_frontend` if I recall correctly (sorry, I closed the console where I did this), and I suspect somehow this was missing from my previous attempts to get this to work (?).

My setup is: Emacs 28 on macOS 10.15.7, installed coursier with `curl -L -o coursier https://git.io/coursier-cli` which gave me version 2.0.16, and installed `metals-emacs` 0.10.2 with the command line described [on the website](https://scalameta.org/metals/docs/editors/emacs.html), which BTW is not exactly the same as in the [docs folder of this repository](https://github.com/scalameta/metals/blob/main/docs/editors/emacs.md). In order to install Bloop manually, I had to add "~/Library/Application Support/Coursier/bin" to my path, and then do the steps described further up.

**Comment by loicdescotte** [comment]
> @niderhoff the alternative is to set the `http_proxy` or `https_proxy` environment variable with `proxyHostname:proxyPort`.
> 
> I will try to check on windows when I get hands on it.

Hi, 
I had the same issue on Windows/SBT and this worked for me. It would be nice to have this information in the documentation. 

By the way I didn't find a way to make it work on WSL (tried env variables and .jvmopts)

2024.02.20 11:46:51 ERROR Timeout waiting for 'build/initialize' response
2024.02.20 11:47:03 WARN  Stopped configuration of Scala SemanticDB in 2.12.18 projects: Error downloading org.scalameta:semanticdb-scalac_2.12.18:4.8.15
