### ISSUE TITLE
Pants integration does not work with older versions of Pants

### ISSUE THREAD

**Issue by jeffverk** [scalameta/metals#1316]
**Describe the bug**

**To Reproduce**
1. Set up the new Pants integration by setting `metals.pants-targets=something::`.
2. Attempt to import the build (`lsp-metals-build-import` in Emacs).
3. Pants get invoked with the `--concurrent` option, which is not supported in older versions of Pants, causing the import to fail.

**Expected behavior**
Build imported and out-of-file completion available.

**Installation:**
- Metals version: v0.8.0

**Additional context**
The solution would be to either add an option to toggle the `--concurrent` option, or have metals auto-detect if Pants supports `--concurrent` before invoking it.

**Search terms**
Pants
0.8.0
v0.8.0
Build

**Comment by tgodzik** [comment]
Thanks for reporting! The pants integration is currently experimental and it might require some changes in the Pants itself. @olafurpg might comment more

**Comment by olafurpg** [comment]
Thank you for reporting! The Pants integration is intentionally undocumented since it's still evolving and it's not clear yet what functionality will be needed from Pants. When the integration stabilizes, I believe we will require a fairly recent version of Pants so it's best if you can upgrade.

Closing since I don't think we'll support older Pants versions.

**Comment by jeffverk** [comment]
What kind of integrations will require a more recent version of Pants? Currently, the plugin seems to run just fine if the `--concurrent` option is removed.

**Comment by olafurpg** [comment]
We currently use `./pants export-classpath export` but may replace that with `./pants export-dep-as-jar`, which was recently introduced and provides a better experience. The latest `./pants export` output also include information like `"scala_platform"` (scala-compiler.jar, and more) that is necessary for Metals. Currently, Metals falls back to Coursier when this field is missing but I would like to remove that fallback eventually.

**Comment by olafurpg** [comment]
In summary, it's best to stay on the latest Pants if you want to use Metals with Pants.
