### ISSUE TITLE
Intellisense Fails to Suggest Appropriate Options After Typing Object Definition

### ISSUE THREAD

**Issue by co-category** [scalameta/metals#1321]
When typing in an object definition e.g.

```scala
  case object Foo 
```
after typing the object identifier `Foo` I would expect Intellisense to know that if I type in the letter `e` or `ex` it should immediately suggest the full word `extends`.

**Comment by olafurpg** [comment]
Thank you for reporting! This would be a nice to have :) Superseded by the feature request https://github.com/scalameta/metals-feature-requests/issues/68
