### ISSUE TITLE
Failure Importing Build Including Scala Native on 0.8.0

### ISSUE THREAD

**Issue by adamgfraser** [scalameta/metals#1322]
**Describe the bug**
When trying to compile a project cross-built against Scala Native, the import fails with an error message:

```
INFO  [error] no clang++8, clang++-8, clang++80, clang++-8.0, clang++7, clang++-7, clang++70, clang++-7.0, clang++60, clang++-6.0, clang++50, clang++-5.0, clang++40, clang++-4.0, clang++39, clang++-3.9, clang++38, clang++-3.8, clang++37, clang++-3.7, clang++ found in $PATH. Install clang (http://www.scala-native.org/en/latest/user/setup.html)
```

**To Reproduce**
1. Open VS Code with an application cross-built against Scala Native (I experienced when working on ZIO)
2. Import build
3. Check logs

**Expected behavior**
Would expect build to be successfully imported and normal functionality to be available including run and debug.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**
Was working fine on last version of Metals. @ekrich reported that he was experiencing the issue as well.

```
adamfraser@Adams-MacBook Desktop % /usr/bin/clang++ --version              
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Search terms**
Scala Native, 0.8.0, Run, Debug, Import Build

**Comment by tgodzik** [comment]
Thanks for reporting, it should be possible to run the import manually via:
```
sbt -Dbloop.export-jar-classifiers=sources bloopInstall
```
We'll see why it's not working automatically. Which repository are you having issues with?

**Comment by tgodzik** [comment]
Closing this until we can get a proper reproduction. It does work for with ZIO.
