### ISSUE TITLE
Undo (ctrl+z) doesn't revert changes made by "Rename symbol" on different files

### ISSUE THREAD

**Issue by ColOfAbRiX** [scalameta/metals#1325]
**Describe the bug**
Undo (ctrl+z) doesn't revert changes made by "Rename symbol" on different files

**To Reproduce**

Create a case class in one file and second case class in another file.

File1.scala
```
case class Note(value: String)
```

File2.scala
```
case class Test(note: Note)
```
Then use the feature "Rename Symbol" or F2 to rename `Note` to a different name.

After the rename use "Undo" or Ctrl+Z to revert back the name to the original `Note`

**Expected behavior**
All occurrences of the symbol across all files should be reverted back

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Search terms**
refactor, rename, undo

**Comment by gabro** [comment]
Thanks for reporting! I agree this is suboptimal, but unfortunately the undo functionality is under control of the specific editor.
At least in VS Code, undo and redo only work across a single file. See this issue which also refers to rename as an example where this is problematic: https://github.com/Microsoft/vscode/issues/638

The current actionable workaround is to save everything and perform another rename back to the original symbol

**Comment by tgodzik** [comment]
I agree, we have discussed it, but we are limited currently by what LSP provides us.
