### ISSUE TITLE
Add gitignore to https://github.com/github/gitignore

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#1336]
We should have a Metals gitignore there, similarly to the one for IJ

**Comment by ckipp01** [comment]
Closed via https://github.com/github/gitignore/pull/3296

**Comment by gabro** [comment]
🙏 great!

![2020-02-10 11 50 04](https://user-images.githubusercontent.com/691940/74143684-8a74b400-4bfb-11ea-9ed7-fe06af751439.gif)

(this from the gitignore extension I use in VS Code)

I would mention this in the next releases notes and/or on Twitter!
