### ISSUE TITLE
False "Cannot rename while the code is compiling" warning

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1345]
**Describe the bug**

When I execute "rename symbol" I get a warning

> Cannot rename while the code is compiling since it could produce incorrect results.

even if there are no targets compiling. After waiting a couple minutes, I was able to run rename symbol.

**To Reproduce**
I'm only able to reproduce this on a fairly large internal codebase. Just opening here to register that I've hit on this issue and may look into it.

**Expected behavior**

Rename symbol should work when there is no ongoing compilation.

**Screenshots**

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Comment by olafurpg** [comment]
I was able to reproduce this in an open source project https://github.com/scalameta/munit, demo

![2020-01-23 23 39 48](https://user-images.githubusercontent.com/1408093/73033399-c822c000-3e39-11ea-8464-0b49e50cda19.gif)

**Comment by tgodzik** [comment]
@ltrojanowski will take a look at it. The idea is to actually try to run the compile if it's compiling to get the future, which should just quickly return if it's a nop compile.  It would be also good to see where is the race condition for the running compilations map.
