### ISSUE TITLE
Stable version is no longer stable on website

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#1353]
As reported by @olafurpg

![image](https://user-images.githubusercontent.com/691940/73118013-44a6c300-3f4e-11ea-82df-33cb614410fe.jpg)

**Comment by ckipp01** [comment]
What part of the site are you seeing this? I'm looking around in the `Using latest Metals SNAPSHOT` sections on the site, and I'm not seeing this anywhere.

**Comment by olafurpg** [comment]
@gabro thank you for opening the issue! It's weird, it looks like this got fixed in a later commit since the website looks OK now.
