### ISSUE TITLE
Missing bloop disconnection alert when exiting bloop

### ISSUE THREAD

**Issue by jvican** [scalameta/metals#1354]
**Describe the bug**
Metals doesn't detect Bloop server has disconnected.

**To Reproduce**
1. Open a project with Metals, open `build.sbt` and let Metals connect to Bloop. Don't open a Scala or Java source file.
2. In a terminal, run `bloop exit`.
3. Switch back to Metals, open a Scala file. Metals will "Load the presentation compiler".
4. When you try to do something like go to definition, Metals will say something like "Wait until compilation is finished and try again".

**Expected behavior**
I expect Metals to detect the server connection is not up anymore and that it connects to it automatically or reports me with a connection error.

**Installation:**
- Operating system: macOS
- Editor: vim / coc-metals
- Metals version: v0.8.0

**Search terms**
bloop, disconnection, exit, reconnection, server

**Comment by ckipp01** [comment]
Just hit on this today. I'm plan to start working a fix for this.

**Comment by tgodzik** [comment]
> Just hit on this today. I'm plan to start working a fix for this.

If you have any issues with that let me know, I might be able to help out.

**Comment by ckipp01** [comment]
Sure! I haven't really touched any of the bloop related stuff yet, so I'm taking it as an opportunity to familiarize myself with it. I'll probably follow-up with you when I get stuck 😆
