### ISSUE TITLE
Proxy Settings ignored

### ISSUE THREAD

**Issue by niderhoff** [scalameta/metals#1362]
**Describe the bug**
I am behind a proxy (no login necessary) and the Visual Studio Code extension doesn't seem to use the correct proxy although it is set in all kinds of places. The JVM doesn't seem to get the proxy settings.

**To Reproduce**
1. Be behind proxy
2. Start workspace with Metals.
3. See error

**Expected behavior**
One of the proxy settings is forwarded to jvm.

**Screenshots**
```
Java home: C:\Program Files\Java\jdk1.8.0_191
Using JVM options set in c:\Develop\projects\xxxx\.jvmopts
Error while downloading https://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar: Connection reset, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/argonaut-shapeless_6.2_2.12/1.2.0-M11/argonaut-shapeless_6.2_2.12-1.2.0-M11.jar: Connection reset, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-util_2.12/2.0.0-M9/case-app-util_2.12-2.0.0-M9.jar: Connection reset, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar: Connection reset, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app_2.12/2.0.0-M9/case-app_2.12-2.0.0-M9.jar: Connection reset, ignoring it`
```

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**
I've used the exact same proxy settings in other places with the JVM and it works.
It makes no difference if I start vscode from Explorer or from a terminal.
And the links above can be opened from firefox/curled from my machine so the proxy works.

- I have set the proxy settings in the metals settings:
```
 "metals.serverProperties": [
        "-Dhttps.proxyHost=proxy.myhostname.de -Dhttps.proxyPort=8080",
        "-Dhttp.proxyHost=proxy.myhostname.de -Dhttp.proxyPort=8080"
    ],
```
- and in .jvmopts
- and also bloop/.jvmopts.
- also in JAVA_OPTS= and in HTTP_PROXY

**Search terms**
proxy metals install setup vscode

**Comment by tgodzik** [comment]
Thanks for reporting! I am taking a look at it.

Does it work if you split it all to separate params? Like:
```json
 "metals.serverProperties": [
        "-Dhttps.proxyHost=proxy.myhostname.de",
        "-Dhttps.proxyPort=8080",
        "-Dhttp.proxyHost=proxy.myhostname.de",
        "-Dhttp.proxyPort=8080"
    ],
```
The same with `.jvmopts`.

**Comment by niderhoff** [comment]
Changing it the way you proposed did work for me.
However, it still is a mystery to me why all other proxy settings and vars are ignored by vscode.

**Comment by tgodzik** [comment]
> Changing it the way you proposed did work for me.
> However, it still is a mystery to me why all other proxy settings and vars are ignored by vscode.

Can't say for sure, but I think the way we run the java process must have escaped the space between the 2 settings.

**Comment by maxhillaert** [comment]
Hi I hit the same issue.    The extension config panel misleads by implying you can use a single line for the -Dhttp.proxyHost= -Dhttps.proxyHost   ..   settings.     SHould probably be explicity said you need to multi line each option

**Comment by tgodzik** [comment]
@maxhillaert created a fix https://github.com/scalameta/metals-vscode/pull/219 - would that help?
