### ISSUE TITLE
Scalafmt config absolute path is not picked up

### ISSUE THREAD

**Issue by agboom** [scalameta/metals#1366]
**Describe the bug**

Not sure if this is a bug or a feature, but at least I couldn't find any documentation about it.
The Scalafmt config path configuration (`scalafmt-config-path` in Emacs) works fine if a path relative to the workspace root is given. An absolute path is not picked up. I have a `.scalafmt.conf` in my home directory to apply formatting to all my Scala projects. Setting `scalafmt-config-path` to either `~/.scalafmt.conf` or `/home/<user>/.scalafmt.conf` results in the error:

> Unable to format since this workspace has no .scalafmt.conf file.

I can image that both local and global Scalafmt configurations are valid use cases and that one even wants to use both, so we might want Metals to prefer one over the other or something.

**To Reproduce**
In Emacs:
1. Add a `.scalafmt.conf` file to your home dir
2. Configure `scalafmt-config-path` to `~/.scalafmt.conf`
3. Open a Metals workspace (without `.scalafmt.conf` in the workspace root.
4. Execute `lsp-format-buffer`
5. Notice the error

**Expected behavior**

The absolute path to the Scalafmt is picked up.

**Screenshots**

**Installation:**
- Operating system: Linux
- Editor: Emacs
- Metals version: v0.8.0

**Additional context**

Mentioned in Gitter: https://gitter.im/scalameta/metals?at=5e315e83f301780b83437e01

**Search terms**

**Comment by ckipp01** [comment]
So this is currently be design. In both coc-metals and the VS Code extension, there is a description along with the setting that says
> Optional custom path to the .scalafmt.conf file.\n\nShould be relative to the workspace root directory and use forward slashes `/` for file separators (even on Windows).

However, I can see that an absolute path may be better fitting for this?

**Comment by gabro** [comment]
We may think of treating the path as absolute if it begins with `/` and relative to the workspace root otherwise. I don't have time to assess the impact more precisely, but I think it would be an easy fix.

**Comment by ckipp01** [comment]
Yea I actually looked into it today. However, seeing @olafurpg's message about why on Gitter does make sense.

> Aah, yes, I think we don't allow absolute paths to .scalafmt.conf
> it's best to keep a custom scalafmt.conf per workspace
> this allows other people working on the same codebase to pick up the same scalafmt configuration

However, I'm happy to work on this if it's something we think we should change.

**Comment by olafurpg** [comment]
I think it's best to not support this use-case. Scalafmt users are encouraged to check `.scalafmt.conf` into their repository so that other collaborators use the same settings. This may be inconvenient for users who work only on their personal projects with no collaborators but you never know if those projects end up getting external collaborators at some point.

**Comment by gabro** [comment]
Actually, I agree with @olafurpg. Unless some other use case for absolute Scalafmt config comes up I’m in favor of closing this as wontfix

**Comment by ckipp01** [comment]
Sounds good. I'll close this then with a won't fix.

**Comment by agboom** [comment]
> Scalafmt users are encouraged to check .scalafmt.conf into their repository so that other collaborators use the same settings.

I did not look at it like that before. I'll adjust my workflow to this.

Thanks for clarifying everyone!
