### ISSUE TITLE
Support for Scala 3

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1367]
Scala 3 is currently not support in Metals and we'd like to change that.

This issue is used to track any progress on that front.

**Comment by tgodzik** [comment]
Related PR in Bloop: https://github.com/scalacenter/bloop/pull/1165

**Comment by tgodzik** [comment]
We've just merged an initial support for Scala 3 for 0.23-RC1 version, which should provide similar features to the Dotty Language Server. However there is still loads of work to do:

Still missing:
- [ ]  shorter type names and exact method parameter names
- [ ]  exact type when it comes to generics
- [ ]  scaladocs not showing for everything
- [ ]  lacking all advanced completions and ordering/filtering
- [ ] shorter type names and exact param names
- [ ] type signatures are not handled by dotty
- [ ] pattern matching unapply method signature help
- [ ] the most outer signature help is usually found

Known issues:
- [ ]  rambo Presentation Compiler sometimes loaded for Dotty after reload
- [ ]  Bloop sometimes loads without the proper settings - especially after Bloop restart
- [ ]  warnings from Bloop don't seem to be cleaned out - only after compile error
- [ ]  some features like rename will not work with Scala 2 non-parsable code - this is due to Mtags class heavily using the Scalameta parser

Demo of what is currently working:

![demo](https://user-images.githubusercontent.com/3807253/79450980-0ddcc800-7fe6-11ea-973f-4313fa916f70.gif)

**Comment by bishabosha** [comment]
This is working very nicely for me in my initial testing. However, I found that the signature tooltip only appears for me on an enum constant if the enum is contained within an outer wrapper, and the tooltip does not show the correct definition for the first enum constant, I believe its overlapping with the invisible `$values` method which returns an array, which I saw in the semanticdb Symbols section always appears immediately before the first constant.

```scala
package example

object Outer:
  enum TestEnum:
    case A // class TestEnum: Array[example.Outer.TestEnum]
    case B // val B: example.Outer.TestEnum
    case C // val C: example.Outer.TestEnum

  enum TestEnum2:
    case Prod(a: String) // class Prod(a: String): example.Outer.TestEnum2
    case A // class TestEnum: Array[example.Outer.TestEnum]
    case B // val B: example.Outer.TestEnum
    case C // val C: example.Outer.TestEnum

enum TestEnum3:
  case A // no tooltip
  case B // no tooltip
  case C // no tooltip

```

**Comment by tgodzik** [comment]
> This is working very nicely for me in my initial testing. However, I found that the signature tooltip only appears for me on an enum constant if the enum is contained within an outer wrapper, and the tooltip does not show the correct definition for the first enum constant, I believe its overlapping with the invisible `$values` method which returns an array, which I saw in the semanticdb Symbols section always appears immediately before the first constant.
> 
> ```scala
> package example
> 
> object Outer:
>   enum TestEnum:
>     case A // class TestEnum: Array[example.Outer.TestEnum]
>     case B // val B: example.Outer.TestEnum
>     case C // val C: example.Outer.TestEnum
> 
>   enum TestEnum2:
>     case Prod(a: String) // class Prod(a: String): example.Outer.TestEnum2
>     case A // class TestEnum: Array[example.Outer.TestEnum]
>     case B // val B: example.Outer.TestEnum
>     case C // val C: example.Outer.TestEnum
> 
> enum TestEnum3:
>   case A // no tooltip
>   case B // no tooltip
>   case C // no tooltip
> ```

Looks certainly like bug, was it working the Dotty Language Server? I mostly copied the code for the main parts of the presentation compiler and wondering if it was an issue with that.

**Comment by bishabosha** [comment]
wow you are right the exact same behaviour in dotty

**Comment by tgodzik** [comment]
Thanks for finding it! I created an issue: https://github.com/scalameta/metals/issues/1634

**Comment by tgodzik** [comment]
`Bloop sometimes loads without the proper settings - especially after Bloop restart` is being fixed in https://github.com/scalacenter/bloop/pull/1253. Without the fix it loads the proper flags only 50 % of the time :( 

Rename being fixed here: https://github.com/scalameta/metals/pull/1637
Support for main methods: https://github.com/scalameta/metals/pull/1640

**Comment by tgodzik** [comment]
Closing this feature since more specific issues have been created.
