### ISSUE TITLE
Support for Scala 2.11.7

### ISSUE THREAD

**Issue by itsursujit** [scalameta/metals#1376]
I've a project that's running scala 2.11.7. I've been using IntelliJ without any issue.

I'm trying to switch VS code and use metals extension but I am not able to use as metals does not support scala 2.11.7

How would I make it work?

**Comment by ckipp01** [comment]
Hi @itsursujit, thanks for the request.

If you look on the [website](https://scalameta.org/metals/docs/editors/vscode.html) you'll see a short note about supported Scala versions.

> Scala 2.13, 2.12 and 2.11. Metals supports these Scala versions 2.13.0, 2.13.1, 2.12.10, 2.12.8, 2.12.9 and 2.11.12. Note that 2.11.x support is deprecated and it will be removed in future releases. It's recommended to upgrade to Scala 2.12 or Scala 2.13

Since 2.11.x support is already deprecated, we won't be doing any other work on supporting legacy versions of Scala.

**Comment by gabro** [comment]
@itsursujit in addition to what @ckipp01 correctly said, it's usually quite simple to upgrade to the latest 2.11 version (2.11.12), which Metals still supports.

Ideally you could also upgrade to 2.12 or 2.13, but that's a bigger effort for sure.

Is there any particular reason why you cannot upgrade?

**Comment by olafurpg** [comment]
@itsursujit Note that Metals supports 2.11.12 and will likely continue to do so for a long time even if the version is marked as deprecated. You don't have to upgrade to 2.12
