### ISSUE TITLE
Keep showing "preparing presentation compiler" at start

### ISSUE THREAD

**Issue by Michaelizm** [scalameta/metals#1377]
Using Metals version 0.8.0
Metals Doctor looks good and no error shows in metals log.

Keep showing "preparing presentation compiler" at start:

<img width="504" alt="Screen Shot 2020-02-01 at 11 56 20 PM" src="https://user-images.githubusercontent.com/10254172/73595112-a4552d80-454f-11ea-9f1f-765170448962.png">

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**
```
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home
INFO  logging to file /Users/zhangchen/Public/dengine/.metals/metals.log
INFO  started: Metals version 0.8.0 in workspace '/Users/zhangchen/Public/dengine'
INFO  time: initialize in 0.53s
Initializing Scala Debugger
INFO  skipping build import with status 'Installed'
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/zhangchen/Library/Caches/org.scalameta.metals/bsp.trace.json
INFO  time: connected to build server in 1.66s
INFO  Connected to Build server v1.4.0-RC1
INFO  time: imported build in 0.1s
INFO  time: updated build targets in 80ms
INFO  time: started file watcher in 76ms
INFO  time: indexed library classpath in 4.03s
INFO  time: indexed workspace SemanticDBs in 1ms
INFO  time: indexed workspace sources in 71ms
INFO  time: indexed library sources in 1s
INFO  time: indexed workspace in 5.27s
INFO  memory: definition index using 18.5M (0 lines Scala)
INFO  memory: references index using 505K (0 elements)
INFO  memory: workspace symbol index using 517K (9 elements)
INFO  memory: classpath symbol index using 2.33M
INFO  memory: build targets using 861K
```

**Search terms**

**Comment by tgodzik** [comment]
@Michaelizm Thanks for reporting!

I think I've seen a situation when the presentation compiler was already loaded but the window wouldn't hide. Are the completions working for you? or is it never loading in reality?

Also, did you change any configuration? `INFO memory` doesn't show up by default.

**Comment by Michaelizm** [comment]
@tgodzik  Thanks for feedback, the code completions is working fine.

I did change some config, as I can't find out if the presentation compiler had been loaded in metals log, so I tried to add `metals.serverProperties` as below to print it out, but still can't find any related in log.

```json
"metals.serverProperties": [
        "-Dmetals.verbose=on",
        "-Dmetals.statistics=all"
    ]
```

**Comment by olafurpg** [comment]
The `-Dmetals.statistics=all` setting enables quite slow memory footprint analysis so you may want to remove it :)

**Comment by tgodzik** [comment]
@Michaelizm if the completions are working you can just close the window, that means it is indeed loaded. There might be just some issue with that window not being properly closed.
