### ISSUE TITLE
Better fuzzy matching for workspace/symbol

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#138]
We should implement something like https://blog.forrestthewoods.com/reverse-engineering-sublime-text-s-fuzzy-match-4cffeed33fdb for workspace/symbol. Most importantly, I want queries like "DoSymPro" to score high for symbols like "DocumentSymbolProvider".

**Comment by laughedelic** [comment]
I was going to open the same issue for autocompletions.

**Comment by olafurpg** [comment]
If someone wants to take a stab at this, the idea is to replace this line here 
https://github.com/scalameta/language-server/blob/b546d512258aeecfd9cc2751da7bd2b2411c105a/metaserver/src/main/scala/scala/meta/languageserver/search/InMemorySymbolIndex.scala#L207

with another true/false heuristic to decide whether a name like "DocumentSymbolProvider" matches a query like "DoSymPro". It's probably best to test this by creating a new `FuzzySearchTest` suite in https://github.com/scalameta/language-server/tree/b546d512258aeecfd9cc2751da7bd2b2411c105a/metaserver/src/test/scala/tests/search
that filters out a list of names given a query.

**Comment by olafurpg** [comment]
I took a quick stab at this in https://github.com/scalameta/metals/compare/master...olafurpg:fuzzy?expand=1 The code is mostly a direct translation of the javascript code in that article with minor tweaks. It seems to work better than fuzzy-wuzzy that we currently use but I still think it requires more refinements. In particular, upper case characters in the query should be heavily penalized when they don't match an uppercase character in the search string.

**Comment by olafurpg** [comment]
Might be worth looking into porting https://github.com/farzher/fuzzysort/blob/master/fuzzysort.js

**Comment by olafurpg** [comment]
Interesting and related post https://blog.burntsushi.net/transducers/#levenshtein-automata

**Comment by olafurpg** [comment]
Superseded by https://github.com/scalameta/metals/issues/339 the criteria for `workspace/symbol` being merged is that it's already fast.
