### ISSUE TITLE
Renaming nested symbol renames file

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1380]
**Describe the bug**

When a nested symbol matches the file name, and the symbol is renamed, the file is renamed too, regardless of whether the enclosing symbol is named like the file or not.

**To Reproduce**
1. Create a file `Events.scala`:

```scala
object Events {
  object Foo {
    object Events {}
  }
}
```
2. Rename `Events.Foo.Events` to X (anything)
3. The file is now `X.scala`.

**Expected behavior**

The file isn't renamed if:
- approach A: the symbol isn't top level
- ~approach B: there is a top-level symbol with the same name, but it's not the one we're renaming.~

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Search terms**
rename, nested, file, top level

**Comment by tgodzik** [comment]
Thanks for reporting! This should be relatively easy to fix if anyone is willing:

https://github.com/scalameta/metals/blob/1c23e3f9bf757cf27974975c6012fff004e60083/metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala#L181

**Comment by kubukoz** [comment]
After 6 minutes of hard thinking, I decided approach B doesn't make sense and the simplest one is the best one. So it'll be a pretty simple change :)
