### ISSUE TITLE
"Find symbol" doesn't find type aliases

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1381]
**Describe the bug**
The "find symbol" option doesn't display aliases matching the search query.

**To Reproduce**
1. Create a file:

```scala
object Foos {
  type Bars = String
}
```

2. Search for `Bars`
3. Type alias doesn't appear.

**Expected behavior**
The type alias can be searched for (just as it can be navigated to).

**Screenshots**
![image](https://user-images.githubusercontent.com/894884/73687408-426d0300-46ca-11ea-9ead-d4078c5a68c5.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**
Symbolic... symbols also can't be searched for (`trait ~>>`). This might be a different bug though.

**Search terms**
find symbol, type alias

**Comment by kpbochenek** [comment]
On file change we use `ScalaToplevelMtags` to generate all symbols from a file. 
Digging deeper we actually don't emit type aliases at all in `ScalaToplevelMtags`

I am not creating PR yet because I am not sure of consequences of my change but this fix(adding emition of type aliases) fixes reported issue:
https://github.com/kpbochenek/metals/pull/1/files

Question 1: would it impact something else
Question 2: is 'Type' proper kind for type alias?

**Comment by olafurpg** [comment]
Thank you for reporting! The mtags-based indexer only looks at class/trait/object members. It should be able to also handle `val/def/type` members but we would need to be careful to for example not emit local symbols.

If we do this change we should also do the same for global val/var/def, not only `type`

**Comment by kubukoz** [comment]
One important consequence of this is that users of e.g. cats-effect 3 won't be able to go to `Concurrent` (which is now a type alias for `GenConcurrent[*[_], Throwable]`). Same goes for completions, which is arguably even more of a problem.

I would be really happy to see this improved in a future release :) global val/var/def also sound good, assuming we have a good definition of global. Does "anything residing in an object or package or the top level" sound good?

**Comment by nkgm** [comment]
Would it be too much to ask to extend the scope of this to all type members (defs & vals) the way IntelliJ does?

**Comment by olafurpg** [comment]
It boils down to the same problem, if you solve it for type aliases you also solve it for defs and refs.

**Comment by nkgm** [comment]
Just realised that's exactly what kubukoz suggested in his previous message. Really looking forward to this feature 🤞
