### ISSUE TITLE
Integration tests, it folder in module

### ISSUE THREAD

**Issue by maciejbak85** [scalameta/metals#1387]
**Question**

in folder module/src/it I have my integration tests, configured with sbt like in:

https://www.scala-sbt.org/1.x/docs/Testing.html#Integration+Tests

but VSCode with metals shows me that does not see those classes, everything compiles fine with sbt. What can I do with it ? thanks!

edit: rest of tests, main code etc works fine in vscode ( module/src/it ), only issue is with it tests folder

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code 1.41.1
- Metals version: v1.7.7

**Comment by tgodzik** [comment]
Thanks for reporting! I don't think Bloop currently supports integration tests.

Related issue: https://github.com/scalacenter/bloop/issues/1162

**Comment by tgodzik** [comment]
Closing this as the related Bloop issues seems to be resolved.
