### ISSUE TITLE
Code action for import not working for nested classes 

### ISSUE THREAD

**Issue by chbatey** [scalameta/metals#1389]
**Describe the bug**

When a class needs importing and it is inside an object it is not offered as a code action. Moving the class out of the object results in it being offered as a code action.

**To Reproduce**

I've created a minimal reproducer here: https://github.com/chbatey/metals-sandbox/blob/master/src/main/scala/info/batey/call/CallSite.scala

**Expected behavior**

For an import code action to be offered.

**Installation:**
- Operating system: Linux and macOS
- Editor: Emacs & vscode (only tried on macOS, not Linux)
- Metals version: v0.8.0

**Search terms**
code action
quick fix
import

**Comment by tgodzik** [comment]
Thanks for reporting and the reproduction :heart_eyes:

**Comment by tanishiking** [comment]
I could reproduce this bug with metals v0.8.0, metals-vscode 1.7.8, and reproducible example  https://github.com/chbatey/metals-sandbox/blob/master/src/main/scala/info/batey/call/CallSite.scala @chbatey thanks :)

However, I found that this had already fixed in the metals's latest master (dc7881f8987c3df25038b3025b3c3823929f4d95 at the moment), I'm not sure which commit fixed this 🤔 

### v0.8.0
![import-missing-080](https://user-images.githubusercontent.com/9353584/74097319-192af780-4b4e-11ea-8693-7f5af6d17971.gif)

### latest master
![import-missing-081-snapshot](https://user-images.githubusercontent.com/9353584/74097321-1f20d880-4b4e-11ea-87bf-0318142a779a.gif)

**Comment by tanishiking** [comment]
I also encounter this bug with metals v0.8.0.
In my case, this sometimes happens no matter where the class defined inside the object or not (especially if the class was recently defined), and in most case code action to import missing symbols works fine.

![import-missing-symbol-ex](https://user-images.githubusercontent.com/9353584/74125811-a0916d00-4c19-11ea-953b-3ff827d2c3e9.gif)
⇡ I could reproduce this bug, no matter where the class is defined, and sometimes it fixes 🤔 

---

I took a look at this phenomenon and found that this happens from `WorkspaceSymbolSearch`:

- [inverseSemanticSymbol(symbol) called from WorkspaceSymbolSearch#loadSymbolFromClassfile](https://github.com/scalameta/metals/blob/60e3d151dd80f0def1a122ff54e5c2f9e805e6cb/mtags/src/main/scala/scala/meta/internal/pc/WorkspaceSymbolSearch.scala#L81) returns `NoSymbol` for the given scalameta's symbol like `scala/meta/internal/metals/Nested.XXX#`.
- `inverseSemanticSymbol` tries to find the scalac's symbol using reflection API, but fails to find it in [inverseSemanticSymbols](https://github.com/scalameta/metals/blob/60e3d151dd80f0def1a122ff54e5c2f9e805e6cb/mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala#L318)
  - where `owner` is `Nested` (in the above case), and it tries to find `XXX` from `Nested`'s `decls`, but **`XXX` is not found even though `XXX` is defined in `Nested`** (I'm not sure why this is happening).
  - As a result `inverseSemanticSymbol` returns `NoSymbol` for `scala/meta/internal/metals/Nested.XXX#` and fail to calculate the code action for it.

I'm not familiar with scalac's reflection API, so I'm not 100% sure, but this bug might be related to 

- https://github.com/scala/bug/issues/6573
- https://github.com/scala/bug/issues/6826 ?

**Comment by tgodzik** [comment]
Just checked it out and it seems to work correctly now. Probably fixed by https://github.com/scalameta/metals/pull/2497
