### ISSUE TITLE
Code completion inside string interpolation not working in emacs

### ISSUE THREAD

**Issue by chbatey** [scalameta/metals#1394]
**Describe the bug**

No completion offered when inside a string interpolation ${} block.

I tried this in vscode and it works.

**Installation:**
- Operating system: Linux and MacOS
- Editor: Emacs
- Metals version: v0.8.0

**Additional context**

**Search terms**
String interpolation
Completion
emacs

**Comment by gabro** [comment]
@chbatey thanks for reporting! Can you enable lsp trace logs (as explained here https://scalameta.org/metals/docs/contributors/getting-started.html#json-rpc-trace) and share the relevant request/response exchange?

**Comment by chbatey** [comment]
Looks like the `textDocument/completion` is not sent when the cursor is in a string interpolation so I don't think this is a metals issue. Sorry for wasting your time.  I was only looking the workspace metals.log, will check the lsp logs in future.

**Comment by olafurpg** [comment]
Did you try manually triggering a code completion? There  are also cases in VS Code where it doesn't trigger automatic completions inside strings. There isn't much we can do on the Metals side to fix this since it's a client issue.

**Comment by chbatey** [comment]
Yep it works when invoked explicitly so nothing wrong with metals
