### ISSUE TITLE
`-encoding, utf-8` breaks metals 

### ISSUE THREAD

**Issue by Baccata** [scalameta/metals#1396]
## The bug 

Features such as jump-to-definition or auto-completio seems to break when encoding is set to "utf-8" (with a dash) instead of "utf8" in scalacOptions 

I caught it because of the following log : 

``` 
Feb 06, 2020 11:52:05 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: requirement failed: List(utf8)
java.lang.IllegalArgumentException: requirement failed: List(utf8)
	at scala.Predef$.require(Predef.scala:281)
```

### Is this really a bug ? 

I don't know whether it should be classified as a bug, but whether it is a bug or not, it is rather problematic because : 

* There is a rather famous [blogpost entry](http://tpolecat.github.io/2017/04/25/scalac-flags.html) from Rob Norris that lists a bunch of useful Scalac flags. 

* Someone has made an [SBT plugin](tpolecat/blob/master/src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala#L93)  out of it.

Both use `utf-8`

### Installation
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0
- Scala version : 2.12.10

### Search terms*

encoding
utf-8
utf8

**Comment by tgodzik** [comment]
Thanks for reporting! This is fixed already in the newest snapshot. That flag is actually wrong there, it should be `-encoding utf8`. We don't fail anymore on bad flags now.

Related: https://github.com/scalameta/metals/issues/1303
