### ISSUE TITLE
 No build targets were detected in this workspace so most functionality won't work.

### ISSUE THREAD

**Issue by tiru67** [scalameta/metals#1398]
**Question**

I am trying to use metals in vscode to setup maven multi-module project for debugging. 

**Screenshots**

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**

I define mainclass inside one of the maven modules in a pom file. 
example
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <program-class>
                                                package.classname
                                            </program-class>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
```

**Search terms**

maven
multi-module
vscode
No build targets were detected in this workspace so most functionality won't work.

**Comment by tgodzik** [comment]
Hi, thanks for reporting!

Did you run build import on the workspace?  It should be run automatically from VS Code when it detects it's a Scala project.

**Comment by tiru67** [comment]
yes i did, it builds as expected, the log end with INFO time: ran 'mvn bloopInstall' in 3.91s
one thing I observed is that the build only create .metals folder but it did not create .bloop folder, I am not sure if its required, since the metal doctor is recommending to remove those folders and retry import I mentioned it.

**Comment by tgodzik** [comment]
Not sure what's going on then. Could you paste the logs from running the command?

Do you have maybe the Scala maven plugin in the workspace? The `maven-jar-plugin` is not connected to Metals really.

**Comment by tiru67** [comment]
1. which command should I run?
2. How do I check if I have Scala maven plugin in the workspace?

**Comment by tiru67** [comment]
oh I see I just scanned the logs and found that I am missing some plugins, will fix that first and get back on it thanks.

**Comment by tiru67** [comment]
@tgodzik  I resolved the issue with missing plugin, and did progress a bit but hit another issue with our company's proxy. Here is the error log 
`WARN  Stopped configuration of SemanticDB in Scala 2.12.10 projects: Error downloading org.scalameta:semanticdb-scalac_2.12.10:4.3.0
  not found: /Users/vbo581/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.10/4.3.0/ivys/ivy.xml
  download error: Caught java.net.SocketException: Connection reset (Connection reset) while downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.10/4.3.0/semanticdb-scalac_2.12.10-4.3.0.pom
  download error: Caught java.net.SocketException: Connection reset (Connection reset) while downloading https://dl.bintray.com/scalacenter/releases/org/scalameta/semanticdb-scalac_2.12.10/4.3.0/semanticdb-scalac_2.12.10-4.3.0.pom`

We need point all the jar download via a proxy server, for exmple instead of downloading from  `https://repo1.maven.org/maven2` it should download from `https://example.company.domain:443/artifactory/maven-publicfacing`

I did trying using `Custom Repositories` - I added an item with value `https://example.company.domain:443/artifactory/maven-publicfacing` it did not work. 

let me know if I need to create a separate issue for this.

**Comment by tgodzik** [comment]
We've recently put some documentation about it on the website: https://scalameta.org/metals/docs/build-tools/proxy.html

Let me know if it helps.

**Comment by tiru67** [comment]
@tgodzik thanks a lot mirror.properties did the magic!!!!

one other question I have is this setup is working if have a main method. but what do is provide the main class while running the jar, so we dont have main method explicitly so my debugger is failing with the below error

`Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;`

so can you help me with an example debug launch configuration that I can refer to?
