### ISSUE TITLE
[object Object] in output when Dotty is enabled

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1406]
![image](https://user-images.githubusercontent.com/894884/74066789-1a4a1080-49f8-11ea-9838-28ba20557f3f.png)

Long story short, the object should probably be replaced with a file name.

**Comment by kubukoz** [comment]
Oops, this actually belongs in https://github.com/scalameta/metals-vscode. Can someone move the issue?

**Comment by gabro** [comment]
I actually fixed this in a recent PR, I'll publish a new version soon :)

**Comment by kubukoz** [comment]
That was quick 😂 thanks!

**Comment by gabro** [comment]
metals-vscode 1.7.8 on its way to the Marketplace ;)

**Comment by kubukoz** [comment]
![image](https://user-images.githubusercontent.com/894884/74067385-6fd2ed00-49f9-11ea-8a4c-e46b68e0a151.png)

Aand it's working. Quickest resolution ever...
