### ISSUE TITLE
Refactor: insert missing abstract members

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#1415]
**Is your feature request related to a problem? Please describe.**
When implementing an abstract class or trait, it's useful to complete all the abstract members with stubs.

**Describe the solution you'd like**
Given something like

```scala
trait A {
  def someMethod(a: String): Int
  def someOtherMethod(b: String): String 
}

class B extends A {
// ^^^^^^^^^^^^^^^^^
// Error: class B needs to be abstract, blabla...
}
```

I would like a code action on `B` that allows to quickly implement all abstract members with stubs, resulting in:

```scala
class B extends A {
  override def someMethod(a: String): Int = ???
  override def someOtherMethod(b: String): String = ???
}
```

**Describe alternatives you've considered**
Mostly two alternatives exist:
- copy paste the stubs from the error message generated by the compiler
- use the "Implement all members" completion (which is basically the same as the code action I'm proposing, except it's triggered differently)

**Additional context**
I think this should be a "quickfix" code action in response to the specific compiler error.

Also, I believe it makes sense to have both the completion and the code action:
- when implementing the trait for the first time the completion comes in handy, since I'm already typing
- when I'm dealing with a compiler error because I forgot a member or a new abstract member was added to the trait, then the code action is more intuitive than triggering a completion.

**Search terms**:
abstract members, traits, interface

**Comment by tgodzik** [comment]
Closed in https://github.com/scalameta/metals/pull/1379
