### ISSUE TITLE
scala compiler -Ypatmat-exhaust-depth option results in argument parsing errors

### ISSUE THREAD

**Issue by Lknechtli** [scalameta/metals#1417]
**Describe the bug**
Setting the `-Ypatmat-exhaust-depth` compiler option appears to break when there are any options following it.
In the project definition json files that bloop generates, I have a couple `-Xplugin` options following it,
and the compiler attempts to interpret them as additional integer inputs to `-Ypatmat-exhaust-depth`, resulting in an error.

Additionally, metals doesn't report the error correctly, logging messages such as:
`ERROR Unexpected error when compiling <project name>: 'null'`
with another log around the same time but not consistently before or after it:
```
Feb 11, 2020 12:00:59 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: For input string: "-Xplugin:/home/<user>/.cache/coursier<internal repo path>/repository/maven-public/com/olegpy/better-monadic-for_2.12/0.2.4/better-monadic-for_2.12-0.2.4.jar"
java.lang.NumberFormatException: For input string: "-Xplugin:<cache path>/v1/http/<internal repo path>/repository/maven-public/com/olegpy/better-monadic-for_2.12/0.2.4/better-monadic-for_2.12-0.2.4.jar"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
	at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
	at scala.tools.nsc.settings.ScalaSettings.$anonfun$YpatmatExhaustdepth$1(ScalaSettings.scala:448)
	at scala.tools.nsc.settings.MutableSettings$IntSetting.parseArgument(MutableSettings.scala:433)
	at scala.tools.nsc.settings.MutableSettings$IntSetting.tryToSet(MutableSettings.scala:443)
	at scala.tools.nsc.settings.MutableSettings.$anonfun$parseParams$8(MutableSettings.scala:158)
	at scala.tools.nsc.settings.MutableSettings.parseNormalArg$1(MutableSettings.scala:133)
	at scala.tools.nsc.settings.MutableSettings.parseParams(MutableSettings.scala:188)
	at scala.tools.nsc.settings.MutableSettings.loop$1(MutableSettings.scala:82)
	at scala.tools.nsc.settings.MutableSettings.processArguments(MutableSettings.scala:92)
```

This is the set of options generated by bloop on my project:
```
                "-deprecation",
                "-unchecked",
                "-feature",
                "-language:implicitConversions",
                "-language:reflectiveCalls",
                "-language:higherKinds",
                "-language:postfixOps",
                "-language:existentials",
                "-language:experimental.macros",
                "-Xmax-classfile-name",
                "100",
                "-Yrangepos",
                "-Ywarn-value-discard",
                "-Ywarn-macros:after",
                "-Ywarn-unused",
                "-Xfatal-warnings",
                "-Ywarn-unused-import",
                "-Ypartial-unification",
                "-Ybackend-parallelism",
                "4",
                "-Ypatmat-exhaust-depth", 
                "100",
                "-Xplugin:<cache path>/repository/maven-public/org/scalamacros/paradise_2.12.10/2.1.0/paradise_2.12.10-2.1.0.jar",
                "-Xplugin:<cache path>/repository/maven-public/com/olegpy/better-monadic-for_2.12/0.2.4/better-monadic-for_2.12-0.2.4.jar",
                "-Xplugin:<cache path>/repository/maven-public/org/scalameta/semanticdb-scalac_2.12.10/4.3.0/semanticdb-scalac_2.12.10-4.3.0.jar"
```

Changing the position of this argument in the list of scala compiler options results in a different string failing to parse into an integer. Removing the option results in no error and a successful compile.

**To Reproduce**
1. Use the `-Ypatmat-exhaust-depth` compiler option and try to compile a project using metals

**Expected behavior**
This compiler option should not result in an error

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.8.0
- Bloop: 1.4.0-RC1+33-dfd03f53"
- Scala: 2.12.10

**Additional context**
I'm not exactly sure whether this is a metals issue, bloop issue, or scala compiler issue. Compiling the project through sbt ~~(which is using bloop in our configuration)~~ alone seems to work fine though, which suggests that it's metals or bloop.

**Comment by tgodzik** [comment]
Thanks for reporting!

I think this is a Bloop issue, since Metals doesn't compile anything. But we will try to confirm and if needed move to the appropriate issue tracker.

**Comment by Lknechtli** [comment]
Do you think the `ERROR Unexpected error when compiling <project name>: 'null'` is metals or bloop? That's probably a separate issue from the compiler option failing to parse.

**Comment by tgodzik** [comment]
> Do you think the `ERROR Unexpected error when compiling <project name>: 'null'` is metals or bloop? That's probably a separate issue from the compiler option failing to parse.

That message is coming from Bloop itself, but it might be connected to some other issue in Metals. Not sure 100% yet

**Comment by tgodzik** [comment]
Actually I can reproduce and it's the `-Xmax-classfile-name` option.

It's doesn't work properly both with the presentation compiler or Bloop. Also, that option was removed in `2.13.x`, so I don't think it makes sense to try to fix it for 2.12.

**Comment by Lknechtli** [comment]
Interesting. Can confirm that removing that option makes the -Ypatmat-exhaust-depth option function correctly again. I suppose it would make sense to close this as "won't fix".

**Comment by tgodzik** [comment]
I think it's safer to remove that option from what I read around the subject.
