### ISSUE TITLE
Rename variable removes backticks in pattern matching

### ISSUE THREAD

**Issue by LGLO** [scalameta/metals#1421]
**Describe the bug**

Having:
```scala
def f(x: Int): Unit = x match {
      case `myVar` => ()
      case _ => ()
    }
```
when I rename `myVar` to `xxx`, then backticks inside case are removed. This changes semantic of pattern match.

**To Reproduce** Steps to reproduce the behavior:

1. Rename any `val` that is used in `case` clause in pattern matching

**Expected behavior**

Backticks are not removed.

**Search terms**

rename backticks

**Comment by gabro** [comment]
Hi, thanks for reporting! I’ve moved this issue to the main Metals issue tracker since this is not vscode specific.

I estimate it's an easy fix /cc @tgodzik

**Comment by LGLO** [comment]
Thank you, sir!
