### ISSUE TITLE
Folding imports sometimes folds whitespace below

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1431]
**Describe the bug**
Under some circumstances, folding a sequence of imports at the top of a file can result in the line below the imports being folded as well.

I have managed to reproduce it deterministically using the following steps:

**To Reproduce**
1. Create a file, e.g.

```scala
import cats.data.NonEmptyList
import cats.Id
import cats.Monad
import cats.Functor
import cats.Applicative

trait Demo
```

folding now will result in the right thing:

```scala
<folded>import cats.data.NonEmptyList

trait Demo
```

2. Add an empty line between some of the imports, for example:

```scala
import cats.data.NonEmptyList
import cats.Id
import cats.Monad

import cats.Functor
import cats.Applicative

trait Demo
```

3. Save the file.

4. Remove the empty line. Fold the imports.

5. This happens:

```scala
<folded>import cats.data.NonEmptyList
trait Demo
```

**Expected behavior**
Folding the code in step 4 has the same result as in step 1.

**Screenshots**

Code after removing empty line

![image](https://user-images.githubusercontent.com/894884/74479173-0185a300-4eaf-11ea-9fb5-7ee81733f983.png)

Folded

![image](https://user-images.githubusercontent.com/894884/74479215-119d8280-4eaf-11ea-80da-a227847819fc.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**

lsp trace log mentioning folding.

Before making any changes:

```
[Trace - 10:20:10 PM] Received request 'textDocument/foldingRange - (1719)'
Params: {
  "textDocument": {
    "uri": "file:///Users/kubukoz/IdeaProjects/flawless/core/src/main/scala/flawless/eval/Foo.scala"
  }
}


[Trace - 10:20:10 PM] Sending response 'textDocument/foldingRange - (1719)'. Processing request took 0ms
Result: [
  {
    "startLine": 0,
    "endLine": 4,
    "startCharacter": 6,
    "endCharacter": 23,
    "kind": "imports"
  }
]
```

After adding and removing empty line:

```
[Trace - 10:22:16 PM] Received request 'textDocument/foldingRange - (1869)'
Params: {
  "textDocument": {
    "uri": "file:///Users/kubukoz/IdeaProjects/flawless/core/src/main/scala/flawless/eval/Foo.scala"
  }
}


[Trace - 10:22:16 PM] Sending response 'textDocument/foldingRange - (1869)'. Processing request took 1ms
Result: [
  {
    "startLine": 0,
    "endLine": 5,
    "startCharacter": 6,
    "endCharacter": 23,
    "kind": "imports"
  }
]
```

*Bonus info*: Switching files and going back restores the correct folding.

**Search terms**
folding, empty line, fold, imports

**Comment by kubukoz** [comment]
Just to make sure it's not a global thing, I just checked with a normal code block and it doesn't seem to suffer from the same issue:

```scala
trait Demo {

  val foo = {
    val a = 1
    val b = 1
    val c = 1
    val d = 1 //remove a line around here
    val e = 1
    val f = 1
    val g = 1

    (a, b, c, d, e, f, g)
  }

  val bar = ()
}
```

**Comment by kpbochenek** [comment]
It looks to be a global thing but it is related to race conditions so might not always be easy to spot a pattern.

From what I noticed but not yet verified in a code when an endpoint returns `Future` it basically means a request will be processed asynchronously and client can send another requests.

With example above we can notice:
VS Code sends request: `textDocument/didChange` that returns `Future`
VS Code sends request: `textDocument/foldingRange` after first request is finished(after future is RETURNED but not necessairly completed)

There is a chance depending on what request finishes first that `foldingRange` will work on old document because `didChange` didn't update a document yet as both requests execute in parallel.


Testing with changed jsonrpc method `didChange`:
```scala
  def didChange(
      params: DidChangeTextDocumentParams
  ): CompletableFuture[Unit] = {
    params.getContentChanges.asScala.headOption match {
      case None => CompletableFuture.completedFuture(())
      case Some(change) =>
        val path = params.getTextDocument.getUri.toAbsolutePath
        buffers.put(path, change.getText)
        diagnostics.didChange(path)
        // blocking processing, updating document before future is even returned
        trees.didChange(path)
        CompletableFuture.completedFuture(())
        // previously sth. like: CancalToken { _ => trees.didChange(path) }
    }
  }
```

With this updating a document is synchronously done in `didChange` method and not asynchronously and I can see `foldingRange` request always starts after `didChange` finishes which means always work on updated document.

It is just for showing a root of a problem, we should not treat it as potential solution.

**Comment by olafurpg** [comment]
@kpbochenek the `didChange` method is not asynchronous since it evaluates everything on the calling execution context and returns `CompletableFuture.completedFuture(())`

**Comment by kpbochenek** [comment]
@olafurpg currently it looks like that:
```scala
  @JsonNotification("textDocument/didChange")
  def didChange(
      params: DidChangeTextDocumentParams
  ): CompletableFuture[Unit] =
    params.getContentChanges.asScala.headOption match {
      case None => CompletableFuture.completedFuture(())
      case Some(change) =>
        val path = params.getTextDocument.getUri.toAbsolutePath
        buffers.put(path, change.getText)
        diagnostics.didChange(path)
        parseTrees(path).asJava
    }
```
Underneath is uses:
```scala
  val parseTrees = new BatchedFunction[AbsolutePath, Unit](
    paths => CancelableFuture(paths.distinct.foreach(trees.didChange))
  )
```

So basically other requests can be processed when this future is evaluated.

**Comment by olafurpg** [comment]
You're right, the parsing happens asynchronously but `buffers.put(...)` is blocking. Maybe the folding implementation should depend on `parseTrees` or something that waits if parsing is ongoing 🤔

**Comment by olafurpg** [comment]
Folding could use `parseTrees.currentFuture()` which will for ongoing parsing if there's any, otherwise it gets the last successful future.

**Comment by kpbochenek** [comment]
In theory you can go to file X and modify it (create parseTrees.currentFuture)
Then go to file Y and modify it (queues processing of Y)
Then request for `foldingRange` is sent for 'Y'
It hooks to future for processing 'X' but should hook into processing of 'Y' which will be generated after request for X is finished.

Maybe it is good enough, just pointing potential problem.
