### ISSUE TITLE
Opening worksheet before opening a referenced file can result in compilation failures

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1433]
**Describe the bug**
If you open a project and the first file you open is a worksheet, symbols referenced in it that are defined in the workspace won't be picked up, leading to compilation errors.

**To Reproduce**
1. Create a project with a file:

```scala
package demo

//Demo.scala
object Demo {
  val a = 5
}
```

2. Create a worksheet in the same directory:

```scala
//demo.worksheet.sc
import demo.Demo.a

println(a)
```

3. Reload window (or just close+open the project), making sure the worksheet is focused first

4. See compilation errors

**Expected behavior**
The module in which the worksheet is defined is compiled before the worksheet.

**Screenshots**

![image](https://user-images.githubusercontent.com/894884/74481163-80300f80-4eb2-11ea-95f9-68403cf94d9a.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**

lsp trace log since the point of reloading:

https://gist.github.com/kubukoz/d9430fac5d0065a22482b9ff5537a22a

**Search terms**
worksheet, compile, compilation order

**Comment by ckipp01** [comment]
I started looking into this today. So when you open another file first, then switch to a worksheet and take a look at the `info.fullClasspath` that we are giving to mdoc, you'll see on top something like `<my-project>/.bloop/out/example/bloop-bsp-clients-classes/classes-Metals-Gsv4Ni3mR_igGUDEYWnxRQ==`. Then when you look there, you would see both the `META-INF` direcotry holidng your semanticDB info and also your `example` package and the classes it contains. This all works as expected.

However, when you open a worksheet first in this same workspace and you look at `<my-project>/.bloop/out/example/bloop-bsp-clients-classes/classes-Metals-Gsv4Ni3mR_igGUDEYWnxRQ==` you'll notice that the `META-INF/semanticdb` directory is actually empty and contains no semantic info. There is also no `example` directory with your classes. This is causing the issue. This part of Metals is new to me, so I'll keep diving further into this, but any insight on the best way to approach this fix would be much appreciated. Any thoughts @tgodzik?

**Comment by tgodzik** [comment]
@ckipp01 we most likely need a successful compilation first before it all can work. Most likely connected to:
https://github.com/scalameta/metals/issues/1259

when connecting to Bloop only after a first compile request will everything be copied to an apropriate place.

**Comment by olafurpg** [comment]
This sounds similar to https://github.com/scalameta/metals/issues/846 and can probably be fixed with a similar change.

Sidenote: I am curious to explore compiling worksheets with Bloop. I have a feeling we should be able to somehow generate Bloop projects for each worksheet that depend on the build so that issues like these don't pop up.
