### ISSUE TITLE
CI is flaky on master

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#144]
Last failure https://travis-ci.org/scalameta/language-server/builds/318856047 The presentation compiler is giving hard to reproduce behavior

**Comment by olafurpg** [comment]
I haven't seen this happen again on the server, I'm gonna close as "unable to reproduce" even if I suspect this may still be an issue.

**Comment by olafurpg** [comment]
Happened for the time in a while in both #182  and #181

**Comment by gabro** [comment]
This didn't happen in a good while. Let's keep an eye on it, but I'll close it for now.
