### ISSUE TITLE
Metals doesn't work with GraalVM

### ISSUE THREAD

**Issue by anasbarg** [scalameta/metals#1453]
**Describe the bug**
When using GraalVM and importing from `org.graalvm` I get the error:
`object graalvm is not a member of package org` in the editor.
Everything compiles when using SBT from the terminal.
I'm using VSCode and I tried configuring Java Home from the extension settings

**To Reproduce**
1. Install GraalVM
2. `import org.graalvm.polyglot._`

**Expected behavior**
To not get the error

**Installation:**
- Operating system: Ubuntu and Windows 10
- Editor: Visual Studio Code
- Metals version: v1.7.8

**Search terms**
GraalVM, Graal

**Comment by olafurpg** [comment]
Thank you for reporting! Those errors come from Bloop indicating that Bloop may not be running on GraalVM. Can you try restarting the Bloop server?

**Comment by anasbarg** [comment]
@olafurpg I tried to restart the bloop server and it still not working

When I run `bloop server` I get this output:
```
Defaulting on nailgun port 8212
Check if server is alive or not...
bloop v1.4.0-RC1

Using Scala v2.12.8 and Zinc v1.3.0-M4+32-b1accb96
Running on Java JDK v1.8.0_242 (/usr/lib/jvm/java-8-openjdk-amd64/jre)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
-------------------------------------------------------------------
A bloop server is already running in port 8212.

  - Do you want to spawn a bloop server in another port?
      Run `bloop server $NAILGUN_PORT`.
  - Do you want to kill the running server?
      Run `bloop ng-stop --nailgun-port $NAILGUN_PORT` or `bloop ng-stop` for short.

Questions? Reach us at https://gitter.im/scalacenter/bloop

```
Seems like it's running on Java JDK v1.8.0 not on GraalVM

**Comment by anasbarg** [comment]
Ok so I tried restarting the bloop server again while metals was running and everything worked!

**Comment by anasbarg** [comment]
The same problem is back but the solution above doesn't work anymore which is weird

**Comment by tgodzik** [comment]
What information do you get with `bloop about`, is it running on GraalVM?

**Comment by anasbarg** [comment]
> What information do you get with `bloop about`, is it running on GraalVM?

```
bloop v1.4.0-RC1

Using Scala v2.12.8 and Zinc v1.3.0-M4+32-b1accb96
Running on Java JDK v1.8.0_232 (/home/anasbarg/bin/graalvm-ce-19.2.1/jre)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```

**Comment by ckipp01** [comment]
So I was curious about this, and I've actually been running Graal with Metals for a while now and everything seems to be working ok, and I can do the import that you showed in the original issue without problem.
```
❯ bloop about
bloop v1.4.8

Using Scala v2.12.8 and Zinc v1.3.0-M4+46-edbe573e
Running on Java JDK v11.0.10 (/Users/ckipp/.sdkman/candidates/java/21.0.0.2.r11-grl)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```
Are you able to try and bump your Bloop and Graal version @anasbarg and see if you still get this issue?

**Comment by anasbarg** [comment]
It's hard for me to reproduce the problem now because I'm on a new machine now and my old machine has been formatted a while ago and I'm no longer using GraalVM in my project.
