### ISSUE TITLE
Javadoc not updated after change

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#1471]
**Describe the bug**
Function documentation displayed on mouse hover is not updated.
I can reproduce it in VS Code and Emacs that's why I raise it here, but it might be editor specific, must be checked better.

**To Reproduce**
Type in VS Code/Emacs this:
```scala
object Scaladoc {
  def fx(x: String): String = x

  fx("test")
}
```
You can see when hovering mouse over `fx("test")` it displays only signature.

Add scaladoc comment:
```scala
object Scaladoc {
  /**
    * Description of a fx
    *
    * @param x Super important param
    * @return the same
    */
  def fx(x: String): String = x

  fx("test")
}
```

Hover mouse over `fx("test")` and still only signature.

Reload window and hover again -> proper scaladoc is displayed.

Also when you already have doc displayed and change its content it doesn't refresh what is displayed after hover.

![Screenshot 2020-02-28 at 09 54 47](https://user-images.githubusercontent.com/10478402/75525642-7bba3980-5a10-11ea-877f-dd28f14619d2.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code and Emacs (the same behaviour)
- Metals version: v0.8.1

**Search terms**
hover, doc

**Comment by tgodzik** [comment]
I think I've seen the issue before, but pretty sure that we haven't fixed it.

I think Scaladoc are only indexed at the start and that's why?

**Comment by tanishiking** [comment]
I also hit this behavior and took a quick look at this.

> I think Scaladoc are only indexed at the start and that's why?

As @tgodzik mentioned, the cause of this is a lack of cache expiration in `scala.meta.internal.metals.Docstrings`: once the symbol (and it's docstring) had cached to `Docstrings.cache`, it never expired.
 https://github.com/scalameta/metals/blob/60859ccb7dfa19a077cc71bf8604adde976676fd/mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala#L26-L37

I guess we can fix this "bug" by reindexing symbols to `Docstrings` on save as `WorkspaceSymbols` does. 🤔
