### ISSUE TITLE
FindReferences/Rename wrong match

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#1474]
When overriding  method it is possible to return subtype of a type returned from parent method.

```scala
package rename

trait RETX
trait RETX2 extends RETX

trait AC {
  def fx(a: String): RETX = ???
}

class B extends AC {
  override def fx(a: String): RETX2 = ???
}

object RenameMatchMethod {
  val b: AC = new B()
  b.fx("X")
}
```

metals doesn't cope with that properly and doesn't match it.

**Comment by tgodzik** [comment]
Thanks for finding this! To fix this we need to have information about inheritance from either the presentation compiler or cache information about the inheritance hierarchy of all the classes in the workspace.
