### ISSUE TITLE
textDocument/rename

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#149]
https://microsoft.github.io/language-server-protocol/specification#textDocument_rename

The rename request is sent from the client to the server to perform a workspace-wide rename of a symbol.

Request:

method: ‘textDocument/rename’
params: RenameParams defined as follows

We should implement this in steps:
- [x] local symbols, this is easiest since we can compile the open buffer and be confident we know all references to that symbol
- [ ] global symbols, this  is harder since we need to be sure to don't miss any references in for example uncompiled projects. Before running the rename we should validate all `sources` in every compilerconfig has an up-to-date semanticdb.

**Comment by gabro** [comment]
Locals symbols are done! #150

**Comment by olafurpg** [comment]
Closing as fixed since textDocument/rename works for local symbols. Opened specific ticket to handle global symbols in #290
