### ISSUE TITLE
Metals Fails to work at all

### ISSUE THREAD

**Issue by tampler** [scalameta/metals#1493]
Ubuntu 19
VSCode 1.43.0
Metals 0.8.1
OpenJDK 11 

Today metals stopped to process my project. No errors, warnings. No code navigation, no type inference.

Totally unusable now, like a Windows text editor. 
Find the log attached

[metals.log](https://github.com/scalameta/metals/files/4319496/metals.log)

**Comment by olafurpg** [comment]
Thank you for reporting! 

> Totally unusable now, like a Windows text editor.

This is not a productive way to start a discussion. Please open a new issue that follows the "bug report" template and try to make a bigger effort to provide helpful information on what might be causing the problem.
