### ISSUE TITLE
Run whenever my code changes

### ISSUE THREAD

**Issue by veeral-patel** [scalameta/metals#1503]
Sorry if this is a beginner question, but I'd like to be able to compile and run my main function whenever my code changes, instead of just compiling (the out of the box behavior).

I can click "run" above my Main function, and it works great, but I don't like doing this whenever I change a line of code.

Thanks!

**Comment by tgodzik** [comment]
Hey, thanks for reporting! There is no way to do it currently unfortunately, but we plan to do a similar thing for testing. You would be able to watch some particular tests and run them whenever the code is compiled. Making it work with any main class would be probably easy to extend.

We haven't yet created a feature request, but you are welcome create one here: https://github.com/scalameta/metals-feature-requests

For now I would suggest (if you are using sbt) to have an sbt console running in the terminal view with `~` before the run command. `sbt ~run` I think should do the trick. It would look like this:

![image](https://user-images.githubusercontent.com/3807253/76743369-d246a800-6772-11ea-9468-d647a169d636.png)

**Comment by olafurpg** [comment]
Thank you for reporting! I agree this is a nice idea. To echo @tgodzik, Metals does not support it at the moment, please open a feature request under https://github.com/scalameta/metals-feature-requests

**Comment by tgodzik** [comment]
Closing this for now, but I highly recommend opening feature request.
