### ISSUE TITLE
Range formatting issue within a multiline string

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1509]
**Describe the bug**
When selecting part of a multiline string that needs to be formatted, the formatting only works when you select after the `|` to start the formatting. This was pointed out in #1505 by @kpbochenek .

**To Reproduce**
1. Go to multiline string that isn't formatted correctly
2. Select portion of string to format including the first `|`
3. Try to format selection
4. Doesn't format as expected unless you don't include the `|`

**Expected behavior**
Expect this to align the `|` like it should.

**Screenshots**

![image](https://user-images.githubusercontent.com/13974112/76870358-fd4afd80-683f-11ea-84ed-cac663c3a4fd.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.1

**Search terms**
Range formatting, formatting, multiline strings

**Comment by kpbochenek** [comment]
Attaching gif:

![formatselection](https://user-images.githubusercontent.com/10478402/76945730-3bf5bc00-6903-11ea-9827-3206b980b040.gif)

**Comment by ckipp01** [comment]
> Attaching gif:

Whoops, I thought I did attach the gif, but I only did the image 😬

**Comment by mlachkar** [comment]
I am currently working on this issue.
