### ISSUE TITLE
Metals SNAPSHOT only refresh compile errors when first connecting to the server

### ISSUE THREAD

**Issue by ashkan-leo** [scalameta/metals#1511]
**Describe the bug**
On Emacs, metals only refresh compile errors when first connecting to the server. This only happen on SNAPSHOT build (currently 0.8.1+48-a0208f2e-SNAPSHOT). The stable version (0.8.1) works as expected.

**To Reproduce**
1. Introduce some compile error to a a file and save.
2. Eliminate the compile error and save.
3. Observe that the error remains.
4. Now, on Emacs do `(lsp-metals-build-connect)` and see that the errors are correctly omitted. 

**Expected behavior**
The compile errors should be refreshed and omitted from the buffer as the buffer is edited. There should be no need to reconnect to the server.

**Installation:**
- Operating system: macOS
- Editor: Emacs
- Metals version: 0.8.1+48-a0208f2e-SNAPSHOT

**Additional context**
I have kept auto-save/backup files separate from source code as suggested in the installation guide.

**Search terms**
Emacs, error-report, lsp-mode, snapshot

**Comment by tgodzik** [comment]
Hey, thanks for reporting. If this only happens on snapshot I believe it might have something to do with the recent Scalameta update. I will merge the fix soon and we can confirm. I had a similar issue under newest SNAPSHOT.

**Comment by tgodzik** [comment]
@ashkan-leo Could you check with the newest snapshot `0.8.1+52-03d618e3-SNAPSHOT` ?

**Comment by tgodzik** [comment]
This should be now fixed, checked on the newest release version. Let us know if we can hel some more!

**Comment by ashkan-leo** [comment]
It is fixed. Thank you for the awesome work!
