### ISSUE TITLE
Dependency source doesn't update

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals#1512]
**Describe the bug**
When updating a dependency's version and clicking through to see a source, it's sometimes (always?) not updated to match the new jar. The source files appear to be located in the `.metals/readonly/` folder.

**To Reproduce**
1. View source from an arbitrary dependency by clicking through from some use site
2. Update same dependency to a different version
3. Repeat step 1
4. See stale source

**Expected behavior**
See updated source

**Installation:**
- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.8.1

**Comment by ckipp01** [comment]
Hi @nilskp, thanks for reporting.

In this scenario, when you update the dependency to a different version, do you get the prompt to re-import your build?

**Comment by nilskp** [comment]
@ckipp01 

I should add that I'm using Gradle.

No, with Gradle there's no prompt when updating `gradle.build`, so I click `Import build` manually.

**Comment by olafurpg** [comment]
Thank you for reporting! What happens if you `rm -rf .metals/readonly` and try to navigate again?

**Comment by nilskp** [comment]
I regularly delete the entire `.metals/` folder to resolve issues like this.

**Comment by olafurpg** [comment]
@nilskp good to know, this should be an easy fix in that case. It looks like Metals doesn't overwrite dependency files

**Comment by nilskp** [comment]
@olafurpg 

When looking at this, would it be possible to mark the source files as read-only or otherwise prevent them from being edited?

Several times I've started editing a dependency source file, because it's from another project I own, and at some point realize the editing is futile 😂

**Comment by tgodzik** [comment]
> @olafurpg
> 
> When looking at this, would it be possible to mark the source files as read-only or otherwise prevent them from being edited?
> 
> Several times I've started editing a dependency source file, because it's from another project I own, and at some point realize the editing is futile

Are you able to save the file? We already mark them as read-only. I think you can actually edit things in most clients, but you can't save them. I think it all depends on the editor itself.

**Comment by olafurpg** [comment]
@nilskp the files in `.metals/readonly` are marked as readonly in the file system on Linux and macOS and some editors display a warning when you start editing a readonly file. We don't mark the files as readonly on Windows since we hit on several cryptic IO exceptions in our CI.

**Comment by tgodzik** [comment]
I wonder if it would make sense to also use https://github.com/microsoft/vscode-extension-samples/tree/master/virtual-document-sample for displaying sources in VS Code.
We could use virtual document and there would be no need to update the sources. Though we need to fix this still for the other editors anyway.

**Comment by olafurpg** [comment]
@tgodzik I think it would be a great idea to start using virtual documents in VS Code. It's important that we still make the current file-based solution work since that's what other editors will continue to use.

**Comment by tgodzik** [comment]
Fixed in https://github.com/scalameta/metals/pull/2668
