### ISSUE TITLE
Can't go-to source for Java 11 code when Java is installed via brew

### ISSUE THREAD

**Issue by Billzabob** [scalameta/metals#1514]
**Describe the bug**
Can't go-to source for Java 11 code when Java is installed via brew.

**To Reproduce**
1. `brew cask install java11`
2. Use metals to go to definition for Java 11 specific code, Ex: `java.net.http.HttpClient`
3. Metals will say `No definition found for 'HttpClient'`

**Expected behavior**
Metals should take you to the source file.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.1

**Additional context**
This is apparently only a problem when installing Java 11 via brew. It might be related to the `src.zip` file being located in `$JAVA_HOME/lib` instead of directly in `$JAVA_HOME`.

Previously metals was reporting false errors around the Java 11 code. I had to change the `blp-server` script to call `java` directly instead of specifically calling java8. Now metals shows that the code compiles but still doesn't allow goto.

**Search terms**
java11, brew, goto

**Comment by ckipp01** [comment]
Hi @Billzabob, are you still having this issue with the newest version of Metals?

**Comment by Billzabob** [comment]
Hi @ckipp01, yes I'm on 0.9.0 and it still fails for me. Metals says it doesn't compile and go-to doesn't work. I guess I can't say whether it's a Metals or a Bloop issue. When I try to compile with Bloop I get errors like this:
```
[E] [E1] src/main/scala/dissonance/utils.scala:5:17
[E]      object http is not a member of package java.net
[E]      L5: import java.net.http.HttpClient
[E]                 ^^^^^^^^^^^^^
```

**Comment by tgodzik** [comment]
@Billzabob Do you have a repo that we could reproduce it on? Bloop should be able to compile any project and if there is an issue it would be awesome to try to fix it on out side.

**Comment by Billzabob** [comment]
This is the one I'm working on and experiencing the issue with:
https://github.com/Billzabob/dissonance
I'm guessing it's not an issue with the repo though, it's probably some sort of environmental issue. It requires Java 11 to compile. I can simply do `sbt compile` and that works fine but I can't get bloop to compile. How does bloop determine what Java version to use? My JAVA_HOME is setup to use Java 11.

**Comment by tgodzik** [comment]
I think it uses the `platform` section inside the json configuration files. And that is set based on the version that was used to run sbt and probably the same as Metals is run in. I can experiment a bit with your repo and see what's going on.

**Comment by Billzabob** [comment]
I tried using [this](https://scalacenter.github.io/bloop/docs/server-reference#custom-java-home) to get bloop to use Java 11 but it doesn't seem to work.
```
cat $HOME/.bloop/bloop.json
{
  "javaHome": "/Library/Java/JavaVirtualMachines/openjdk-11.jdk"
}

bloop about
Using Scala v2.12.8 and Zinc v1.3.0-M4+32-b1accb96
Running on Java JDK v1.8.0_172 (/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```

**Comment by tgodzik** [comment]
Bloop uses the java binary on PATH first and if it's not found there then the one used by Metals.

**Comment by Billzabob** [comment]
There is only Java 11 on my path. I even manually set the JAVA_HOME to point to Java 11 in the Metals settings. I'm getting the same compiler errors in Bloop and Metals :(

**Comment by kpbochenek** [comment]
```
λ java -version
openjdk version "11.0.6" 2020-01-14

λ bloop about
bloop v1.4.0-RC1-229-b7c15aa9

Using Scala v2.12.8 and Zinc v1.3.0-M4+42-5daa8ed7
Running on Java JDK v11.0.6 (/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home)
```

For me metals doesn't complain, bloop compiles fine, but I can confirm jumping to definition of Java classes doesn't work(gonna check why)
bloop installed via brew (don't know why 0.4.0-RC1-XX and not 0.4.1 but anyway)
```
λ brew cask install java11
Error: Cask 'java11' is unavailable: No Cask with this name exists
```
java installed normally as it doesnt look like java11 is available via brew cask

**Comment by kpbochenek** [comment]
Okay a problem is in function:
```
  private def trivialPaths(toplevel: Symbol): List[String] = {
    val noExtension = toplevel.value.stripSuffix(".").stripSuffix("#")
    List(
      noExtension + ".scala",
      noExtension + ".java",
      "java.base/" + noExtension + ".java", // For Java 11
    )
  }
```
For java 11 in will only look for sources from 'java.base' module.

`java.net.http.HttpClient` is in `java.net.http` module and will never be found.
Changing this method to:
```
  private def trivialPaths(toplevel: Symbol): List[String] = {
    val noExtension = toplevel.value.stripSuffix(".").stripSuffix("#")
    List(
      noExtension + ".scala",
      noExtension + ".java",
      "java.base/" + noExtension + ".java", // For Java 11.
      "java.net.http/" + noExtension + ".java"
    )
  }
```
allows to jump to `HttpClient` definition.
It shows that a problem is in metals and handling java11 modules.

**Comment by Billzabob** [comment]
It looks like this is my issue:
https://github.com/scalacenter/bloop/issues/933
Java 11 isn't supported by bloop on MacOS :(

**Comment by tgodzik** [comment]
@Billzabob I think that this might be the case if it's installed via brew. Running it via coursier or letting Metals install it should work.

**Comment by Billzabob** [comment]
@tgodzik Uninstalling bloop via brew and reinstalling with Coursier fixed my issue! Now I'm seeing what you guys are. It compiles for me now, but goto still doesn't work for `java.net.http.HttpClient`.

**Comment by tgodzik** [comment]
Cool! We are already fixing it in https://github.com/scalameta/metals/pull/1763
It's an issue with not taking java modules into account.
