### ISSUE TITLE
Return references in order

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1520]
**Question**

This was originally brought to my attention via @poslegm on Discord, and I think it's a valid point. Let's say you have two files:

A.scala
```scala
package example.A

trait AA
trait BB extends AA
```
B.scala
```scala
package example.B

import example.A.AA

class CC extends AA
class DD extends AA
class EE extends AA
```
If I do a go to to definition on `AA` in `A.scala` I should get a list of definitions of all the places that `AA` is found. For example, here is the response from Metals.

<details><summary>Metals Output</summary><br>

```json
[Trace - 10:19:23 PM] Sending response 'textDocument/definition - (51)'. Processing request took 5ms
Result: [
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/A/A.scala",
    "range": {
      "start": {
        "line": 4,
        "character": 17
      },
      "end": {
        "line": 4,
        "character": 19
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/B/B.scala",
    "range": {
      "start": {
        "line": 2,
        "character": 17
      },
      "end": {
        "line": 2,
        "character": 19
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/B/B.scala",
    "range": {
      "start": {
        "line": 5,
        "character": 17
      },
      "end": {
        "line": 5,
        "character": 19
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/B/B.scala",
    "range": {
      "start": {
        "line": 4,
        "character": 17
      },
      "end": {
        "line": 4,
        "character": 19
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/B/B.scala",
    "range": {
      "start": {
        "line": 6,
        "character": 17
      },
      "end": {
        "line": 6,
        "character": 19
      }
    }
  }
]
```
</details>
In some clients (coc.nvim) for example, these are displayed as is, showing the following out of order results.

<img width="777" alt="Screenshot 2020-03-20 at 22 32 47" src="https://user-images.githubusercontent.com/13974112/77208028-306ce580-6afb-11ea-8722-7c49085e12e1.png">

The same happens when you do a find references on the same symbol.

<details><summary>Metals Output</summary><br>

```json
[Trace - 10:19:52 PM] Sending response 'textDocument/references - (53)'. Processing request took 4ms
Result: [
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/A/A.scala",
    "range": {
      "start": {
        "line": 4,
        "character": 17
      },
      "end": {
        "line": 4,
        "character": 19
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/B/B.scala",
    "range": {
      "start": {
        "line": 2,
        "character": 17
      },
      "end": {
        "line": 2,
        "character": 19
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/B/B.scala",
    "range": {
      "start": {
        "line": 5,
        "character": 17
      },
      "end": {
        "line": 5,
        "character": 19
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/B/B.scala",
    "range": {
      "start": {
        "line": 4,
        "character": 17
      },
      "end": {
        "line": 4,
        "character": 19
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/B/B.scala",
    "range": {
      "start": {
        "line": 6,
        "character": 17
      },
      "end": {
        "line": 6,
        "character": 19
      }
    }
  }
]
```
</details>
<img width="777" alt="Screenshot 2020-03-20 at 22 32 56" src="https://user-images.githubusercontent.com/13974112/77208167-8b064180-6afb-11ea-8b6f-029827625ac2.png">

** Actual question **

Does it make sense / is it possbile to correctly order these before they go back to the client? VS Code orders these correctly, but this isn't working as expected for `coc-metals` users.

**Installation:**

- Operating system: macOS
- Editor: Vim
- Metals version: v0.8.3

**Search terms**

references out of order, definition out of order

**Comment by kpbochenek** [comment]
Could you explain what is a correct order of returned results? If a reference to class/method X is found in 2 places what rules should decide which one should be first on list?

as a note `@JsonRequest("textDocument/definition")` acts in 2 ways, if you are on reference/usage it will jump directly to definition because there will be only one result(one exception is class + companion object), but if you are on definition this command will call logic of 'find references' (exactly the same method as "textDocument/references")

Just to clarify 'definition results should be sorted' you mean a second case of finding references, right?

```scala
@JsonRequest("textDocument/definition")
  def definition(
      position: TextDocumentPositionParams
  ): CompletableFuture[util.List[Location]] =
    CancelTokens.future { token =>
      definitionOrReferences(position, token).map(_.locations)
    }
```

**Comment by ckipp01** [comment]
> Could you explain what is a correct order of returned results? If a reference to class/method X is found in 2 places what rules should decide which one should be first on list?

For the files, I don't really care what order the are returned in. However, I think the references in that file should be in order. In the example that I gave, notice that the reference on line 6 `class DD extends AA` is being returned before the reference on line 5 `class CC extends AA`. I'd expect that to be the other way around.

> as a note `@JsonRequest("textDocument/definition")` acts in 2 ways, if you are on reference/usage it will jump directly to definition because there will be only one result(one exception is class + companion object), but if you are on definition this command will call logic of 'find references' (exactly the same method as "textDocument/references")
>
> Just to clarify 'definition results should be sorted' you mean a second case of finding references, right?
> 
> ```scala
> @JsonRequest("textDocument/definition")
>   def definition(
>       position: TextDocumentPositionParams
>   ): CompletableFuture[util.List[Location]] =
>     CancelTokens.future { token =>
>       definitionOrReferences(position, token).map(_.locations)
>     }
> ```

Yes, exactly.

**Comment by kpbochenek** [comment]
ahh right the order in which they are placed in a file duh :P
- does it make sense: personally yes! (the same sorting is also done in intellij)
- is it possbile: yes (we get `locations: util.List[Location]` it is just a matter of grouping it by path and sorting each group by line - quick and easy but question is how that would affect performance.)

**Comment by tgodzik** [comment]
I agree it should be returned in order, I think this should simple to do. 

Probably it will be most efficient to change it it inside the reference provider here to a sorted collection:
https://github.com/scalameta/metals/blob/a4faebe5c385f656cc8c41c113fe939822969b37/metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala#L249
