### ISSUE TITLE
Pack character/line into a data type

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#156]
We often pass around character/line as two separate values.
We should probably pack those two into a dedicated data type, as suggested by @ShaneDelmore in https://github.com/scalameta/language-server/pull/146#discussion_r158514467

**Comment by olafurpg** [comment]
I think the correct data structure here is scalameta Position with an extension method 'uri: Uri'

**Comment by olafurpg** [comment]
This should also replace the ad hoc 'Cursor' case class

**Comment by olafurpg** [comment]
All ad-hoc usages of `(Int, Int)` for line/column have been removed and from now on I will try to use `scala.meta.Position` or `scala.meta.internal.semanticdb.Range` for all line/column wrappers.
