### ISSUE TITLE
Metals - Scala Language and Build Server Extension For VS Code

### ISSUE THREAD

**Issue by kevalkaneria1** [scalameta/metals#1574]
**Question**

I am having an issue on Metals - Scala Language and Build Server Extension For VS Code. I have reached out Microsoft team regarding Metal extension, but since it is third party extension, so they do not provide any support for it. I have attached error note with this issue. 

**Screenshots**
This is the error i am getting
--------------------------------------------------------------------------------------
Failed to download metals, make sure you have an internet connection and the java home 'C:\Progra`1\JAVA\jdk18`1.0' is valid. you can configure the java home in the settings. see https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an http proxy.

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v1.7.7

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Hi, thanks for reporting! 

`1.34.0` doesn't seem to be a valid Metals version.
Metals does have two different versions. One for the server, which can be seen in the Metals settings and the other is the VS Code extension version, which can be seen in the extensions.

Additionally `C:\Progra1\JAVA\jdk181.0` doesn't look like a valid Java Home, could you maybe try to set the path to a JDK by hand in the Metals javaHome setting?

**Comment by kevalkaneria1** [comment]
Thank you for quick reply

server version is 0.8.0
extension version is 1.7.7

it's unclear to me what JAVA_HOME is supposed to be if not C:\PROGRA~1\Java\JDK18~1.0 which is my standard value. do you have any more detail about the formatting? would you mind linking the issue?

apparently when I use a JAVA_HOME value other than my system default, it does not even attempt to install any of the dependencies, so I'm unsure if it is actually invalid

**Comment by tgodzik** [comment]
`C:\Progra1\JAVA\jdk181.0` just looked misspelled and I thought it might be an encoding issue or something of the kind.

Could you try updating to the newest extension `1.8.5`? We made fix there that should log more into the VS Code Output, which might be helpful to diagnose the issue.

**Comment by kevalkaneria1** [comment]
we uninstalled and tried to reinstall, it prompted me to upgrade, so I started the process, but it seems to fail silently and just re-prompts me to upgrade.

**Comment by kevalkaneria1** [comment]
Can you please reopen th

**Comment by tgodzik** [comment]
> so I started the process, but it seems to fail silently and just re-prompts me to upgrade.

So you are unable to update the extension? Maybe you also need to update the visual studio code version? I might not be able to help you out much without the update, because the errors are swallowed up currently. You also try to run Metals install maunally to see what's going on via:
```
# Make sure to use coursier v1.1.0-M9 or newer.
curl -L -o coursier https://git.io/coursier-cli
chmod +x coursier
./coursier bootstrap \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=vscode \
  org.scalameta:metals_2.12:0.8.3 \
  -r bintray:scalacenter/releases \
  -r sonatype:snapshots \
  -o /usr/local/bin/metals -f
```
Then try to run the generated executable. The way you do it will need to be different than on linux, but please take a look at the coursier website, might be helpful: https://get-coursier.io/

Alternatively, you could try removing the java home altogether, if we don't find it we might offer downloading it automatically. Lastly, it might be good to try and reinstall the JDK.  

Not sure what else can help.

**Comment by kevalkaneria1** [comment]
we have upgraded VS code 1.43.2 with latest version. I will update you soon

**Comment by tgodzik** [comment]
@kevalkaneria1 Did you manage to find any more logs?

**Comment by kevalkaneria1** [comment]
Issue still didn't get resolved. we have upgraded Vs code with latest version. also, we are using latest version of Coursier. coursier recognizes my JDK/JRE as being valid paths/installations, otherwise it would fail to execute anything.

 I can download the artifacts using curl or something, and use coursier to install them directly (though coursier might just be for downloading the artifacts) since it seems like I can download them outside of coursier. Do you know how install artifact using CURL.

**Comment by tgodzik** [comment]
How is it failing now in VS Code? There should be some log in the Metals Output, which might be helpful to solve the issue.

**Comment by tgodzik** [comment]
Those errors seem to be exactly the issue. Due to those failures, Metals is unable to start the server. Any idea why it's not being downloaded? Those are all valid links, are you able to curl them?

Maybe you are using some kind of a proxy to connect to maven central?

**Comment by kevalkaneria1** [comment]
yes we are using proxy because we are using in our work environment.

**Comment by kevalkaneria1** [comment]
HTTP proxy
Metals uses Coursier to download artifacts from Maven Central. To use Metals behind an HTTP proxy, configure the system properties -Dhttps.proxyHost=… -Dhttps.proxyPort=… in one of the following locations:

.jvmopts file in the workspace directory.
JAVA_OPTS environment variable, make sure to start code from your terminal when using this option since environment variables don't always propagate correctly when opening VS Code as a GUI application outside a terminal.
"Server Properties" setting for the Metals VS Code extension, which can be configured per-workspace or per-user.

On this 3 option do we have to configure all 3

**Comment by tgodzik** [comment]
You should only configure one option. If you use the last option, it should one property per line.

That is needed for the coursier to be able to use proxies.  There is some more information on the topic here: https://scalameta.org/metals/docs/build-tools/proxy.html

**Comment by tgodzik** [comment]
If that doesn't work, we also talk about some additional things to set here: https://github.com/scalameta/metals-feature-requests/issues/9

In particular `javax.net.ssl.trustStore` might be needed in some corporate environments.

**Comment by tgodzik** [comment]
Any luck with the proxies?

**Comment by tgodzik** [comment]
Closing this, if there are any issues we can reopen.
