### ISSUE TITLE
Auto import includes `package` for symbols in a package object

### ISSUE THREAD

**Issue by gregghz** [scalameta/metals#1588]
**Describe the bug**

For symbols defined in a package object, the `Import <symbol> from package '<package>'` code action imports the symbol as ```import <package>.`package`.<symbol>```.

**To Reproduce**
1. Import this project: https://github.com/gregghz/package-object-metals-bug
2. Go to https://github.com/gregghz/package-object-metals-bug/blob/master/src/main/scala/Main.scala#L6
3. Request the import symbol code action on `Bar`
4. Note the import added includes ``` `package` ```

**Expected behavior**

Given:

```
package metals

package object bug {
  trait Bar
}
```

the import symbol code action should add the following import:

```
import metals.bug.Bar
```

**Screenshots**

Before running the code action:

![image](https://user-images.githubusercontent.com/220801/78698969-f6039680-78b7-11ea-90e6-095492490fc5.png)

After running the code action:

![image](https://user-images.githubusercontent.com/220801/78699108-34995100-78b8-11ea-91f3-ab01ded51e83.png)

**Installation:**
- Operating system: macOS
- Editor: Emacs
- Metals version: v0.8.3

**Additional context**

**Search terms**

package object
import

**Comment by tgodzik** [comment]
Thanks for reporting! I can confirm and it does certainly look like a bug.
