### ISSUE TITLE
Create new symbol doesn't open new file after creation

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals#1599]
**Describe the bug**
The `Create new symbol...` code action creates correctly the new file but metals doesn't open it automatically in the client. In the gif bellow I had to open the file manually.

**To Reproduce**
![create-symbol](https://user-images.githubusercontent.com/1632384/79001183-4f84f300-7b4e-11ea-96d1-75990e75c582.gif)

**Expected behavior**
The newly created file should be opened like in the original PR https://github.com/scalameta/metals/pull/1528

**Installation:**
- Operating system: Linux
- Editor: Sublime
- Metals version: 0.8.3+176-14c95365-SNAPSHOT

**Comment by gabro** [comment]
Interesting: does this work the same for the "New Scala file..." command? The code action uses the same provider so I would expect the behavior to be identical.

**Comment by ayoub-benali** [comment]
`new-scala-file` isn't supported yet in https://github.com/scalameta/metals-sublime 
Calling the command returns an error:
 ```
{'code': -32603, 'message': 'Internal error.', 'data': 'java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)\n\t... 11 more\nCaused by: java.lang.NullPointerException\n\tat scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1340)\n\t... 16 more\n'}

```

Should it be called with arguments ?

**Comment by ayoub-benali** [comment]
Oh nevermind just saw this: https://github.com/scalameta/metals/blob/ca3def6a492a7cdd40e5280cc7371cd134b29fba/metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala#L201

Need to tinker a bit to get `new-scala-file` working

**Comment by gabro** [comment]
@ayoub-benali I've taken a look at the implementation and Metals uses a custom client command to open the file (IIRC that's because there's no LSP method to open a file). See https://github.com/scalameta/metals/blob/ccc307a6cf459e197d161c82c20a4a935b9baa9d/metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala#L196-L197

and

https://github.com/scalameta/metals/blob/7204180218dcea0d2bccc3e583a68ae1e9a4fb53/metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala#L108

**Comment by ayoub-benali** [comment]
OK so it is an expected behavior since the client has to support `goto-location` command https://scalameta.org/metals/docs/editors/new-editor.html#goto-location

Thank you @gabro
