### ISSUE TITLE
Unable to import a build in VS Code on Windows with spaces in user directory

### ISSUE THREAD

**Issue by kag0** [scalameta/metals#1600]
**Describe the bug**
When importing a (mill) build for the first time, an error is encountered when attempting due to trying to run something in the command prompt with an absolute path containing a space.

**To Reproduce**
1. Create a windows user with a space in the name. eg. "John Doe"
2. Open a folder containing a mill build in VS Code
3. Run `Metals: Import build`
4. Check output

**Expected behavior**
The build is imported

**Screenshots**
```
INFO  running 'C:\Users\NATHAN~1\AppData\Local\Temp\metals10549553100692239952\millw.bat --mill-version 0.6.1 --predef C:\Users\NATHAN~1\AppData\Local\Temp\metals10549553100692239952\predef.sc mill.contrib.Bloop/install'
INFO  'C:\Users\Nathan' is not recognized as an internal or external command,
INFO  operable program or batch file.
INFO  build tool exit: 1
INFO  time: ran 'mill bloopInstall' in 46ms
ERROR Mill command failed: C:\Users\NATHAN~1\AppData\Local\Temp\metals10549553100692239952\millw.bat --mill-version 0.6.1 --predef C:\Users\NATHAN~1\AppData\Local\Temp\metals10549553100692239952\predef.sc mill.contrib.Bloop/install
```

**Installation:**
- Operating system: Windows 10 17763.1098
- Editor: Visual Studio Code
- Metals (extension) version: 1.8.5

**Additional context**
Mill version: 0.6.1

Running from a local mill install using `mill -i --predef C:\Users\NATHAN~1\AppData\Local\Temp\metals10549553100692239952\predef.sc mill.contrib.Bloop/install` from the command prompt works fine. 

**Search terms**
mill vs code windows path spaces

**Comment by kag0** [comment]
OK, so debugging `millw.bat` it looks like the script is actually found and then run, and the error line is coming from the last line of the `millw.bat` script which is `%MILL% %*` but should be escaped with quotes `"%MILL%" %*`.

That aside, iirc that millw script is deprecated in favor of the wrapper that's [now part of the main mill project](http://www.lihaoyi.com/mill/#windows). @lefou is that right?

So the fix should be to have metals download https://github.com/lihaoyi/mill/releases/download/0.6.1/0.6.1-assembly instead of https://github.com/lefou/millw/blob/master/millw.bat

**Comment by lefou** [comment]
No, lefou/millw project is not deprecated. For Unix-system mills own `mill` script does almost the same, but there is no good replacement for the `millw.bat` yet. Also, `millw` tries to support more features and older mill versions.

**Comment by kag0** [comment]
Gotcha, thanks. I think an update to millw should fix things then.
