### ISSUE TITLE
Debug variables don't display `.toString`

### ISSUE THREAD

**Issue by japgolly** [scalameta/metals#1603]
Hello! I just used the debugger for the first time and WOW! Amazing work!! Thank you!

In the Debug > Variables pane, I can see all variables in scope but the annotation to the right of the variable name is `ClassName@Hash`, even for classes with `.toString` defined. I don't know that the status quo is a bug or a feature, so I'm not sure if it should be replaced, or just enhanced with the ability to further configure it.

Either way, the goal for me here would be to somehow be able to see the `.toString` values, otherwise I need to expand everything to maximum depth to be able to see the content.

The simplest solution might be to just add a dropdown for display options like `["ClassName@Hash", "toString", "both"]`. A more comprehensive solution might be to allow users to specify their own Scala function for `Any => String` (?).

**Comment by tgodzik** [comment]
Hi, thanks for reporting! This is currently not implemented and there is an open feature request https://github.com/scalameta/metals-feature-requests/issues/83

This is something that is rather higher priority and we are super interested in implementing it.
