### ISSUE TITLE
metals/inputBox request isn't sent to client

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals#1605]
**Describe the bug**
While implementing `new-scala-file` command in the sublime plugin I noticed that the server isn't sending the `metals/inputBox` request to the client.

You can see in the LSP flow bellow that file type choice is sent back to the server but the client isn't requested to show file name input field.

```
:: --> metals-sublime workspace/executeCommand(2): {'arguments': ['file:/home/ayoub/workspace/testproject/src/main/scala/example'], 'command': 'new-scala-file'}
:: <-- metals-sublime window/showMessageRequest(1): {'actions': [{'title': 'class'}, {'title': 'case-class'}, {'title': 'object'}, {'title': 'trait'}, {'title': 'package-object'}, {'title': 'worksheet'}], 'message': 'Select the kind of file to create'}
:: >>> metals-sublime 1: {'title': 'trait'}
:: <<< metals-sublime 2: {}
```

Metals is started with these properties `'-Dmetals.client=sublime', '-Dmetals.status-bar=on', '-Dmetals.execute-client-command=on', '-Dmetals.input-box=on', '-Dmetals.verbose=on'`

**Expected behavior**
Server should send `metals/inputBox` the client so the `new-scala-file` command can be completed.

**Installation:**
- Operating system:Linux
- Editor: Sublime
- Metals version: v0.8.3+176-14c95365-SNAPSHOT 
- Bloop version: 1.3.4

**Additional context**
This is all what I see in `metals.log` even thought verbose in enabled.
```
INFO  started: Metals version 0.8.3+176-14c95365-SNAPSHOT in workspace '/home/ayoub/workspace/testproject'
INFO  time: initialize in 0.35s
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher5532315681545780151/bsp.socket'...
Waiting for the bsp connection to come up...
INFO  skipping build import with status 'Installed'
INFO  Selected port 5031
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///tmp/bsp-launcher5532315681545780151/bsp.socket...
The server is listening for incoming connections at local:///tmp/bsp-launcher5532315681545780151/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/ayoub/.cache/metals/bsp.trace.json
INFO  time: connected to build server in 0.6s
INFO  Connected to Build server v1.3.4
INFO  Started Metals http server at http://127.0.0.1:5031
INFO  time: indexed workspace in 1.77s
```

**Comment by tgodzik** [comment]
Thanks for reporting!

@alekseiAlefirov Do you have any idea what is going on?

**Comment by tgodzik** [comment]
@ayoub-benali This should be now fixed, can you confirm? The snapshot version should be available soon.

**Comment by ayoub-benali** [comment]
Issue fixed. Thanks @alekseiAlefirov
