### ISSUE TITLE
Metals creates empty top-level src directories

### ISSUE THREAD

**Issue by milessabin** [scalameta/metals#1609]
Metals creates empty top-level `src/main/scala/` and `src/test/scala` directories to be able to start the file watcher.

Metals deletes the directories if they're empty but doesn't delete their parents, so if the build didn't actually have `src`, `src/main` and `src/test` directories (eg. if all sources are in sub-project directories with an empty top-level aggregating project) these will be left behind and seen by the metals user as unexpectedly created.

Some gitter discussion [here](https://gitter.im/scalameta/metals?at=5e95978efea5216d697b2f2e). @olafurpg comments: "we should probably just skip unmanaged source directories that are not used".

**Comment by milessabin** [comment]
Appears to be related to: https://github.com/scalameta/metals/pull/506.

**Comment by tgodzik** [comment]
Thanks for reporting! I can confirm that this happens, might be indeed related to the FileWatcher.
