### ISSUE TITLE
Make server respect configuration

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#161]
#158 added a comprehensive configuration, but not all settings are respected by the server.

Namely:

- [x] Hover/enabled
- [x] Scalac/enableCompletions
- [x] Scalafix/confPath
- [x] index JDK on `indexJDK=true`

**Comment by olafurpg** [comment]
I added this to the v0.1 milestone, since completion is still enabled by default even if `scalameta.scalac.enabled=false` by default.

**Comment by olafurpg** [comment]
Can we close this ticket now?

**Comment by gabro** [comment]
Yep!
