### ISSUE TITLE
Add code action to auto-import all missing symbols when there are no ambiguities

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1610]
**Is your feature request related to a problem? Please describe.**

When copy-pasting code from one file to another I get compile errors about missing imports. I currently select the code and trigger the code action multiple times for each missing symbol

<img width="606" alt="Screenshot 2020-02-19 at 12 10 19" src="https://user-images.githubusercontent.com/1408093/74843373-b55db700-5323-11ea-8871-2067a0fe9d9c.png">

**Describe the solution you'd like**

It would be nice if there was an "import all missing symbols that are unambiguous" code action that would insert imports for all missing symbols in one stop. This code action could skip imports when there are multiple candidates with the same name.

**Describe alternatives you've considered**

Trigger the code action for each individual error.

**Comment by ckipp01** [comment]
BTW @coline-lunatech is diving into this :)
