### ISSUE TITLE
Migrate client config flags to initializationOptions

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals#1614]
**Is your feature request related to a problem? Please describe.**

ST4 is in alpha since several months, multiple releases have been published and they fix several limitation the previous version has regarding LSP. By default to handle the two versions we would need a new accepted value for `metals.client`.

**Describe the solution you'd like**

But @ckipp01 had a good suggestion on [gitter](https://gitter.im/scalameta/metals?at=5e947094d021c45cc7e1f1ab) and since there was already some work in https://github.com/scalameta/metals/pull/1414. Metals should read client configuration flags from `initializationOptions`. This way metals client extensions can enable or disable features depending on the client version without having to add to Metals server properties each time. 
 
I can make a PR and would handle initially `isCompletionItemDetailEnabled`, `isExitOnShutdown` but I can add others like `statusBar`, `metals.input-box` if you have other suggestions.

**Describe alternatives you've considered**

Add a new value for `metals.client`

**Comment by ckipp01** [comment]
@ayoub-benali I think this is a good approach, and if I would have known better at the time I would have done the ones in #1414 as `initializationOptions` rather than `clientExperimentalCapabilities`. However, that doesn't prevent us from moving in that direction. I think as long as we support both for some time we may be able to migrate them all over to `initializationOptions` which could in theory almost remove the need for a lot of the server properties.

**Comment by ayoub-benali** [comment]
I can make the flags introduced in https://github.com/scalameta/metals/pull/1414 also available in `initializationOptions` with fallback to `clientExperimentalCapabilities`. What do you think ?

**Comment by ckipp01** [comment]
Yea so just reading it over again [here](https://microsoft.github.io/language-server-protocol/specification#initialize), I think yea you could probably include all of the ones below as `initializationOptions`.

- statusBar
- didFocus
- slowTask
- InputBox
- execute-client-command
- doctorFormat

Plus the extra ones you mentioned as well. As you said, we'd still want to fall back to the ones that exist as `clientExperimentalCapabilities` and also fall back to to them being set as server properties to not break clients that may be using them.
