### ISSUE TITLE
Dynamically register server capabilities

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#163]
We now statically register server capabilities on server initialization.
However, we'd like to allow users to turn on/off certain features, using the configuration introduced in #158. This means we want the registration of server capabilities to be dynamic, using [`client/registerCapability`](https://microsoft.github.io/language-server-protocol/specification#client_registerCapability)/[`client/unregisterCapability`](https://microsoft.github.io/language-server-protocol/specification#client_unregisterCapability).

The idea is to react to changes to the configuration observable, looking for the keys that enable/disable a certain server feature.

Note that if the client is well-behaved, it should be able to send certain requests only if the server has registered the capability. E.g. if the user decides to turn off the text formatting feature (maybe because they're using another separate formatter), the client should not send a request to the server.
This poses a choice in terms of implementation:
- a) we trust the client to respect the registered capabilities, and we blindly respond to the request when asked to;

 or 

- b) we go paranoid, and we check whether a feature is enabled in the configuration before executing the respective provider.

I'd tend to go with a), which means trusting the correctness of the protocol implementation from the client. This simplifies the logic on the server side, avoiding the implementation of a noop operation for every request.

**Comment by olafurpg** [comment]
I think this idea is worth revisiting in the future as we add more optional functionality to the server. After #332 there will only be goto definition to begin with and from now on I would like to ensure that new features work robustly enough that they are always enabled by default.

One concern with dynamic capability registration is that some clients like vim/emacs/sublime/... may not support it
