### ISSUE TITLE
Prepend `-J` before sending jvm properties to Bloop

### ISSUE THREAD

**Issue by SkyTrix** [scalameta/metals#1642]
**Describe the bug**

Options set in the `jvmOptions` section of launch.json are not passed to the JVM.

**To Reproduce** Steps to reproduce the behavior:

1. Create test file
```scala
package com.example

import collection.JavaConverters._

import java.lang.management.ManagementFactory
import java.lang.management.RuntimeMXBean

object Test {
  def main(args: Array[String]): Unit = {
    println(Runtime.getRuntime().maxMemory())

    val runtimeMxBean = ManagementFactory.getRuntimeMXBean
    runtimeMxBean.getInputArguments.forEach(println)
    runtimeMxBean.getSystemProperties.asScala.foreach {
      case (key, value) =>
        println(s"$key -> $value")
    }
  }
}
```

2. Create a launch.json configuration for the test file with a `jvmOptions` array
```json
{
  "version":"0.2.0",
  "configurations":[
    {
      "type":"scala",
      "name":"Test",
      "request":"launch",
      "mainClass":"com.example.Test",
      "jvmOptions":[
        "-Xmx2G",
        "-Dfoo.bar=baz"
      ]
    }
  ]
}
```
3. Run the program using the launch config
4. Notice that printed `maxMemory` is 4G instead of requested 2G and that none of the printed lines include our passed in arguments

**Expected behavior**

1. Printed memory should be 2G.
2. Among printed input arguments we should find:
```
-Xmx2G
-Dfoo.bar=baz
```

3. Among printed system properties we should find:
```
foo.bar -> baz
```

**Installation:**

- Operating system: macOS
- VSCode version: 1.44.2
- VSCode extension version: 1.8.6
- Metals version: 0.8.4

**Additional context**

**Search terms**

launch.json, jvmOptions

**Comment by tgodzik** [comment]
Fixed by https://github.com/scalameta/metals/pull/1781
