### ISSUE TITLE
java.lang.NoClassDefFoundError: difflib/myers/Equalizer

### ISSUE THREAD

**Issue by bishabosha** [scalameta/metals#1647]
**Describe the bug**

when using metals 0.8.4+62-67ef4e74-SNAPSHOT with scala/scala repo, there is a missing class when compiling library subproject

**To Reproduce**
1. clone `git@github.com:scalacenter/scala.git`
2. checkout branch `tasty_reader`
2. open VSCode
3. Import Build
4. Open `src/compiler/scala/tools/nsc/tasty/TreeUnpickler.scala`

**Expected behavior**

~For type hints to start working~
Edit: type hints did start working, but i still see this error

**Screenshots**

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version:  0.8.4+62-67ef4e74-SNAPSHOT

**Additional context**

<details>
<summary><b>Log Output</b></summary>
<br/>
```
2020.04.20 11:05:21 INFO  compiling library (531 scala sources and 33 java sources)
[Error - 11:05:23 AM] Request textDocument/foldingRange failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: difflib/myers/Equalizer
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: difflib/myers/Equalizer
	at scala.meta.internal.metals.FoldingRangeProvider.$anonfun$getRangedFor$1(FoldingRangeProvider.scala:24)
	at scala.Option.map(Option.scala:242)
	at scala.meta.internal.metals.FoldingRangeProvider.getRangedFor(FoldingRangeProvider.scala:21)
	at scala.meta.internal.pc.ScalaPresentationCompiler.$anonfun$foldingRange$1(ScalaPresentationCompiler.scala:130)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 3 more
Caused by: java.lang.ClassNotFoundException: difflib.myers.Equalizer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 8 more

2020.04.20 11:06:22 WARN  there were 37 deprecation warnings (since 2.10.0)
2020.04.20 11:06:22 WARN  there was one deprecation warning (since 2.11.0)
2020.04.20 11:06:22 WARN  there was one deprecation warning (since 2.12.0)
2020.04.20 11:06:22 WARN  there were 57 deprecation warnings (since 2.13.0)
2020.04.20 11:06:22 WARN  there were 96 deprecation warnings in total; re-run with -deprecation for details
2020.04.20 11:06:22 WARN  there were 37 feature warnings; re-run with -feature for details
2020.04.20 11:06:22 INFO  compiling reflect (162 scala sources and 3 java sources)
2020.04.20 11:06:26 INFO  time: compiled library in 1m4s
2020.04.20 11:06:54 WARN  there was one deprecation warning
2020.04.20 11:06:54 WARN  there were two deprecation warnings (since 2.10.0)
2020.04.20 11:06:54 WARN  there were four deprecation warnings (since 2.11.0)
2020.04.20 11:06:54 WARN  there were two deprecation warnings (since 2.12.3)
2020.04.20 11:06:54 WARN  there was one deprecation warning (since 2.12.5)
2020.04.20 11:06:54 WARN  there were 8 deprecation warnings (since 2.13.0)
2020.04.20 11:06:54 WARN  there were 18 deprecation warnings in total; re-run with -deprecation for details
2020.04.20 11:06:54 WARN  there were 9 unchecked warnings; re-run with -unchecked for details
2020.04.20 11:06:54 WARN  there were two feature warnings; re-run with -feature for details
2020.04.20 11:06:54 INFO  compiling compiler (311 scala sources and 5 java sources)
2020.04.20 11:06:56 INFO  time: compiled reflect in 32s
2020.04.20 11:07:46 WARN  there were 12 deprecation warnings (since 2.10.0)
2020.04.20 11:07:46 WARN  there were 14 deprecation warnings (since 2.11.0)
2020.04.20 11:07:46 WARN  there were 7 deprecation warnings (since 2.12.5)
2020.04.20 11:07:46 WARN  there were three deprecation warnings (since 2.12.7)
2020.04.20 11:07:46 WARN  there were 109 deprecation warnings (since 2.13.0)
2020.04.20 11:07:46 WARN  there were 145 deprecation warnings in total; re-run with -deprecation for details
2020.04.20 11:07:46 WARN  there were 35 unchecked warnings; re-run with -unchecked for details
2020.04.20 11:07:48 INFO  time: compiled compiler in 53s

```
</details>

**Search terms**

java.lang.NoClassDefFoundError difflib/myers/Equalizer

**Comment by tgodzik** [comment]
Thanks for reporting! That error seems to be coming from a FoldingRange request, but it looks like the classpath is incorrect maybe? Does it happen in any other files? We use that library heavily for token distance.

**Comment by tgodzik** [comment]
Ok, I checked that snapshot version and folding range seems to be working correctly still, so that seems to not be the real issue. Is there anything bad happening with the workspace? Is anything in particular broken?

**Comment by bishabosha** [comment]
I get that error whenever i open any source file, but i can still use go to definition etc

**Comment by bishabosha** [comment]
I'm still experiencing this with 0.8.4+62-67ef4e74-SNAPSHOT

**Comment by dos65** [comment]
@tgodzik 
I've also seen this on the master branch.

The reason is the usage of `FoldingRangeProvider` in [ScalaPresentationCompiler](https://github.com/scalameta/metals/blob/master/mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala#L59) .
When PC runs in the embedded mode it has a limited classpath that doesn't contain `difflib`

**Comment by olafurpg** [comment]
The java-diff-utils dependency is indeed missing on mtags even if it's defined here https://github.com/scalameta/metals/blob/67ef4e7492722191b096da047433255b33aebb13/build.sbt#L286

```
❯ cs fetch org.scalameta:metals_2.12:0.8.4 | grep diff
/Users/lgeirsson/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar
❯ cs fetch org.scalameta:mtags_2.12.11:0.8.4 | grep diff
```

**Comment by tgodzik** [comment]
> The java-diff-utils dependency is indeed missing on mtags even if it's defined here
> 
> https://github.com/scalameta/metals/blob/67ef4e7492722191b096da047433255b33aebb13/build.sbt#L286
> 
> ```
> ❯ cs fetch org.scalameta:metals_2.12:0.8.4 | grep diff
> /Users/lgeirsson/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar
> ❯ cs fetch org.scalameta:mtags_2.12.11:0.8.4 | grep diff
> ```

That's expected for `0.8.4` it was in the metals module previously. I will check why it's the case for the rambo compiler, it should be actually run with the same classpath as metals, but something might need still fixing.

**Comment by tgodzik** [comment]
```
coursier  fetch  -r sonatype:public org.scalameta:mtags_2.12.11:0.8.4+62-67ef4e74-SNAPSHOT | grep diff
/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar
```
that's for the newest snapshot

**Comment by dos65** [comment]
@tgodzik 
I don't know the reasons behind the following logic but it explains why `libdiff` might  be not added to  classpath. At least for my example project, it fetches `mtags` without dependencies.

https://github.com/scalameta/metals/blob/67ef4e7492722191b096da047433255b33aebb13/metals/src/main/scala/scala/meta/internal/metals/Embedded.scala#L213-L219

Removing it fixes the problem.

**Comment by tgodzik** [comment]
> @tgodzik
> I don't know the reasons behind the following logic but it explains why `libdiff` might be not added to classpath. At least for my example project, it fetches `mtags` without dependencies.
> 
> https://github.com/scalameta/metals/blob/67ef4e7492722191b096da047433255b33aebb13/metals/src/main/scala/scala/meta/internal/metals/Embedded.scala#L213-L219
> 
> Removing it fixes the problem.

You're right! :100: 
That was an optimization, that might not be really that needed and might no longer actually work. @olafurpg Might remember more.
