### ISSUE TITLE
Improve standalone presentation compiler integration

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1653]
Current situation with presentation compiler is as follows:

1. Get a file uri.
2. Check if it belongs to a build target.
  a. If it does, check if the Scala version is supported.
      I. If it does, create a presentation compiler with the build target classpath and it's Scala version
      II. Otherwise, fallback to b. 
  b. If it doesn't, use a "rambo" 2.12 compiler without a classpath except Scala library.

Proposal:

1. Get a file uri.
2. Check if it belongs to a build target.
  a. If it does, check if the Scala version is supported.
    I. If it is, create a presentation compiler with the build target classpath and it's Scala version
    II. Otherwise, use ScalaVersion.recommenedVersion() and create a presentation compiler with that recommended version and build target's options + classpath.
  b. If it doesn't, use a "rambo" compiler without a classpath except Scala library, although first ask for a default Scala version for the workspace if it is not already set.

For 2.a.II I think we shouldn't ask for the Scala Version, since multiple targets could have different unsupported Scala version. Alternatively, we could use the recommended Scala version  as a default suggestion for the workspace.
 
This will allow us to work specifically with Dotty snapshot versions and better support older Scala versions.

**Comment by olafurpg** [comment]
I am inclined to vote for using the same "rambo" compiler for both `2.a.I` and `2.b`. I think it's OK to support only one rambo compiler per workspace, if the user wants multiple rambo compilers with different Scala versions then they can write a build that configure those versions.

I think it makes sense to change how we select the Scala version of the rambo compiler. We can make it a user configuration option and prompt the users to select a version via metals/inputBox when we first load the compiler. The input box can be pre-populated with a default Scala version similar to how we pre-populate the Scalafmt version. We can try to be smart in how we pre-populate the version by detecting whether the open source file is using Dotty-specific syntax. Otherwise, I would stick with using the latest "stable" Scala version, which is 2.13.1 right now.

**Comment by olafurpg** [comment]
I think we can also rename "rambo" into "fallback" since that is more self-explanatory what it means. It's basically the fallback Scala version we use when we don't have a build tool telling us what Scala version to use.

**Comment by tgodzik** [comment]
> I am inclined to vote for using the same "rambo" compiler for both 2.a.I and 2.b. I think it's OK to support only one rambo compiler per workspace, if the user wants multiple rambo compilers with different Scala versions then they can write a build that configure those versions.

If we do that we will not have any completions from outside the current file or the dependencies.

My idea here is to allow people to normally work on their workspace with all Metals features. Especially with Dotty, we don't even need scalameta released for a particular version.

**Comment by tgodzik** [comment]
I did a quick test:
https://github.com/scalameta/metals/compare/master...tgodzik:fallback-scala-version?expand=1

This seems to work well for example for 2.12.7. Though, it seems with Dotty doesn't work that well.

**Comment by tgodzik** [comment]
Another reason not to use the same rambo compiler is that with a defined target we can just use existing SymbolSearch, while rambo/fallback version and only use the RamboSymbolSearch.

**Comment by tgodzik** [comment]
Discussed this online and I agree that we should use rambo in case of unsupported Scala version also because:
- we can still get incompatibilities between for example 2.12.4 and 2.12.10, so we can't really use the byte code generated by and older compiler version
- we should make sure that the correct PC version is used, since this is the only thing that we can guarantee
- we should not send a message it's ok to use old Scala versions

So this task will concentrate on:
- using fallback also for unsupported Scala versions
- adding a setting for fallback scala version or default scala version
- asking for the default if none is set - we can propose the recommended Scala version in case of unsupported Scala
