### ISSUE TITLE
Code action or completion to change a single line string into multiline one

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1660]
**Is your feature request related to a problem? Please describe.**
It's pretty difficult currently to write a multiline string, since quotes are always completed in twos and 
everything is a bit finicky.
 
**Describe the solution you'd like**
It would be good to allow completions (maybe after writing the first two quotes) that would allow to insert `"""|""".stripMargin` or just `"""`. 

**Describe alternatives you've considered**
Add a code action on a single string to convert it to multiline.

**Additional context**

**Search terms**:
multiline stripMargin quotes triple

**Comment by tgodzik** [comment]
@coline-lunatech invited you to the repository, we can assign the issue to you after you accept :)

**Comment by kpbochenek** [comment]
As an inspiration this is how it looks from Intellij side(which I also find super useful):
![multiline_string](https://user-images.githubusercontent.com/10478402/80120915-f3799000-858b-11ea-879a-7f4e5bbeb2d9.gif)

**Comment by coline-lunatech** [comment]
Awesome thanks for the inputs

**Comment by tgodzik** [comment]
I think that Intellij is forcing users a bit too much, I wouldn't automatically add pipes and `stripMargin` using onTypeFormatting. It's something we were thinking about but decided against.

Code action gives the users most choice I think.

**Comment by tgodzik** [comment]
I think we can concentrate on the code action here and improve typing of mutliline strings as suggested by @mlachkar here: https://github.com/scalameta/metals/pull/1661
