### ISSUE TITLE
cannot navigate to a scala file containing underscore inside of integer literal

### ISSUE THREAD

**Issue by bwiercinski** [scalameta/metals#1664]
**Describe the bug**

**To Reproduce**
1. Create new class
```scala
class Tests {
  val x = 100_000

  def dummy() = x
}
```
2. Somewhere else
```scala
object Tests2 {
  val x = new Tests
  x.dummy()
}
```
3. click Ctrl and hover `dummy()`
4. Nothing highlights, cannot navigate to definition
5. Remove underscore
6. Works

**Expected behavior**
Should navigate in both scenarios

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.8.4

**Additional context**
https://www.javatpoint.com/java-numeric-literals-with-underscore

**Search terms**
underscore long integer literal

**Comment by tgodzik** [comment]
Thanks for reporting! I think I might have an idea of what's going on, will try to take a quick look.
