### ISSUE TITLE
Allow running main classes defined outside the build targets

### ISSUE THREAD

**Issue by chuanzhangjiang** [scalameta/metals#1667]
how can I debug my playframwork app in vs code?

**Comment by tgodzik** [comment]
Thanks for reporting! From what I checked it's not currently possible to run play application from Metals. The play server main is not detected.

This might require some custom work, so I would suggest opening a feature request: https://github.com/scalameta/metals-feature-requests

Or alternatively upvoting https://github.com/scalameta/metals-feature-requests/issues/86
which would allow to connect to a running server.

**Comment by chuanzhangjiang** [comment]
thanks!

**Comment by dkovalenko** [comment]
Actually Bloop supports running play application, see: https://github.com/scalacenter/bloop/pull/717

Maybe

**Comment by tgodzik** [comment]
@dkovalenko Actually you are right :O 

![image](https://user-images.githubusercontent.com/3807253/81423407-ad5c2900-9154-11ea-913f-06ee53474908.png)

The only problem is that we check if a given class is contained in the build target and if it is not we throw an exception. Maybe we could actually drop that check:
https://github.com/scalameta/metals/blob/5f2b935046e718409d633b1ed717c8319c1279fa/metals/src/main/scala/scala/meta/internal/metals/BuildTargetClassesFinder.scala#L56

**Comment by dkovalenko** [comment]
Hi, just wondering if the fix was merged?
I still having trouble running play main using metals-vscode
<img width="396" alt="Screenshot 2020-07-27 at 13 12 25" src="https://user-images.githubusercontent.com/874918/88531125-09737280-d00b-11ea-965c-a18d98031fc3.png">
This is my configuration:
```
{
      "type": "scala",
      "request": "launch",
      "name": "Play main",
      "mainClass": "play.core.server.ProdServerStart",
      "args": [],
      "jvmOptions": [],
      "buildTarget": "rotator"
    }
```

**Comment by tgodzik** [comment]
The fix was not yet merged. I will try to give it a go this week.
