### ISSUE TITLE
Automatic imports doesn't import in the right position when in a package object

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1669]
**Describe the bug**

Give the following code:

```scala
package example

package object example {
  def doSomething(instant: Inst@@ant, p: Period) = ???
}
```
If I trigger a code action on the `@@` and then accept to import `java.time.Instant`, I'd expect this to be imported between the package declaration and the package object.  However, this imports in the package object. So the result is below:

```scala
package example

package object example {

  import java.time.Instant
  def doSomething(instant: Instant, p: Period) = ???
}
```

**Screenshots**

![2020-04-28 10 09 47](https://user-images.githubusercontent.com/13974112/80463750-05b34f80-8939-11ea-905d-0524e02eccd7.gif)

**Search terms**
code action, imports, package object

**Comment by gabro** [comment]
Does it do the same if you import it via completions?

**Comment by ckipp01** [comment]
> Does it do the same if you import it via completions?

Yes, it's the same behavior with a completion or a code action.
