### ISSUE TITLE
Debug test does not stop at breakpoint

### ISSUE THREAD

**Issue by arthurgreef** [scalameta/metals#1673]
**Question**

I have installed the latest Metals extension and have the following debug options. When I select "Debug test" the test suite runs but my breakpoint is ignored. Is there some setup that I am missing? Thanks.

"version": "0.2.0",
    "configurations": [
        {
            "type": "scala",
            "name": "Debug coop.rchain.rholang.interpreter.ReduceSpec",
            "request": "launch",
            "testClass": "coop.rchain.rholang.interpreter.ReduceSpec",
            "buildTarget": "rholang-test"
        }
    ]

**Screenshots**

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.8.4

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
I think everything should work here. The only thing you need to make sure is that you do invoke "Debug" instead of just run.

I you are already doing it correctly then it might be an issue with breakpoint detection. There is one know issue for sure: https://github.com/scalameta/metals/issues/1195

Do you get any warnings in `.metals/metals.log`?

**Comment by arthurgreef** [comment]
I select "Debub tests" Here are my warnings.
ERROR WARNING: An illegal reflective access operation has occurred
ERROR WARNING: Illegal reflective access by org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy (file:/home/arg/.ivy2/cache/org.lmdbjava/lmdbjava/jars/lmdbjava-0.6.1.jar) to field java.nio.Buffer.address
ERROR WARNING: Please consider reporting this to the maintainers of org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy
ERROR WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
ERROR WARNING: All illegal access operations will be denied in a future release

**Comment by arthurgreef** [comment]
Breakpoint does not work in this test file: https://github.com/rchain/rchain/blob/dev/rholang/src/test/scala/coop/rchain/rholang/interpreter/ReduceSpec.scala. It does work in the Main file. Not sure if will be fixed by the bug you reference.

**Comment by tgodzik** [comment]
We recently fixed https://github.com/scalameta/metals/issues/1195 - from what I see it should fix you issues with the ReduceSpec.scala. 

@arthurgreef Could you confirm? The bug existed if there was an inner class before the breakpoint, which seems was the case in that file.

**Comment by tgodzik** [comment]
Closing this issue as I am almost sure the new release should have helped, but I do not have time to confirm, since the project setup is quite complicated.
