### ISSUE TITLE
Scalafix in the editor

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#1675]
### Is your feature request related to a problem? Please describe.
Scalafix is a tool for automatic refactors and linting rules.

Currently, Scalafix is primarily used in batch mode, fixing or linting an entire project.

However, Scalafix would be extremely useful in the editor as well. Linting rules that are failing could be reported inline and some rules can be translated to code actions (i.e. automatic fixes).

### Describe the solution you'd like
Integration of Scalafix in Metals, similarly to how the Scalafmt integration currently works.

Ideally the integration would use https://github.com/scalacenter/scalafix/blob/master/scalafix-interfaces/src/main/java/scalafix/interfaces/Scalafix.java

I would envision this to be broken down into at least two iterations:

- linting only (just report diagnostics for failing rules)
- code actions (translate Scalafix rules into LSP Code Actions, to provide automatic fixes in the editor)

### Describe alternatives you've considered
Being sad and not having Scalafix in the editor

### Search terms
scalafix metals linting refactor quickfix organize imports

**Comment by perrin4869** [comment]
Is there a way to trigger scalafix rules other than `OrganizeImports` from metals at this point?

**Comment by ckipp01** [comment]
Hey @perrin4869, at this point there is not.
