### ISSUE TITLE
Warnings are not cleaned out for Scala 3

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1683]
**Describe the bug**
When a single warning is produced from compilation and then fixed, the warning is not cleaned out.

As a workaround, we can introduce a bug and then fix it, which will clean out the diagnostics.

**To Reproduce**
1. Create a file with:
```scala
def hello() : Unit = {
  ""
  val a = 123
}
```
2. Remove `""`
3. Warning will not be removed.

**Expected behavior**
Warning is removed.

**Screenshots**

![image](https://user-images.githubusercontent.com/3807253/80822344-d0c62780-8bda-11ea-98c1-3c8374dce84b.png)

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.8.4

**Additional context**
This might have something to do with Dotty zinc integration not working 100 %

**Search terms**
warning scala3

**Comment by smarter** [comment]
Hi! Any update on this? I'm happy to help fix things on Dotty side if the problem is on our side, but I'm not aware of any problem with our zinc integration.

**Comment by tgodzik** [comment]
> Hi! Any update on this? I'm happy to help fix things on Dotty side if the problem is on our side, but I'm not aware of any problem with our zinc integration.

Thanks! It's still an issue, it seems the warning diagnostics are only reset when the errors have also changed. I am not 100% what it's caused by, probably intersection of Bloop and zinc, but not sure exactly. This might be fixed with more work into Zinc and Scala 3 work, which I think is planned.

**Comment by smarter** [comment]
> This might be fixed with more work into Zinc and Scala 3 work, which I think is planned.

I think the scala center might work on improving incremental compilation in Zinc for Scala 3, but I don't think this is related to this issue at all. The issue is likely related to bloop but no one works on Bloop / Scala 3

**Comment by tgodzik** [comment]
> > This might be fixed with more work into Zinc and Scala 3 work, which I think is planned.
> 
> I think the scala center might work on improving incremental compilation in Zinc for Scala 3, but I don't think this is related to this issue at all. The issue is likely related to bloop but no one works on Bloop / Scala 3

I should take a look there, but I haven't had the time :/

**Comment by smarter** [comment]
I just tried using the sbt server instead of bloop and this lead to the opposite problem: no warning message being displayed at all when the build is triggered (even though I do see them in the "Metals" tab in the Output panel)

**Comment by ckipp01** [comment]
So I just took a closer look at this to see if anything has changed. Using sbt as a BSP server here seems to work as expected. You see the warning, you remove the `""` and the warning goes away.

With Bloop, it depends on what version you're using. In `1.4.8` it's as illustrated up above by @smarter that the warning isn't cleared. I create a ticket in Bloop for this https://github.com/scalacenter/bloop/issues/1509 with some info. Also note that in the newest version of Bloop used by the latest Metals snapshot, `1.4.8-19-4d9f966b`, the behavior differs again and now Bloop doesn't emit a warning at all for this.

**Comment by smarter** [comment]
> Also note that in the newest version of Bloop used by the latest Metals snapshot, 1.4.8-19-4d9f966b, the behavior differs again and now Bloop doesn't emit a warning at all for this.

Just tried it with metals 0.10.7 / bloop 1.4.9 and I see warnings showing up on save and not getting cleared on subsequent saves.

**Comment by tgodzik** [comment]
I need to finally update zinc and see if it's fixed by it.

**Comment by spangaer** [comment]
Btw, Java compilation seems to suffer from the same problem. Not sure if should add a separate ticket for that.

**Comment by tgodzik** [comment]
Could you open up a separate issue with that? Are you sure that the errors are coming from the Metals extension and not the Java language server?
