### ISSUE TITLE
No signature help inside pattern match for Scala 3

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1687]
**Describe the bug**
```
case Some(@@) =>
```

With the cursor at @@ there will be no signature help coming from the unapply of Option or any other class.

**To Reproduce**
1. Create pattern match for a class with an unapply method
2. Try to use signature help inside the pattern match
3. No signature help available

**Expected behavior**
Signature help shows the signature of an unapply method. 

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.8.4

**Additional context**
This might need to be fixed inside the Dotty compiler - might require some help from the compiler team.

**Search terms**
scala3 unapply signature help

**Comment by bishabosha** [comment]
in `0.24.0-RC1` i can hover on the argument of the `Some` pattern fine:

```scala
def foo(o: Option[String]) = o match
  case Some(s) => s + s
  case _ => ""
```

**Comment by tgodzik** [comment]
@bishabosha Hover works, that's true. Signature help on the other hand should be shown while you are writting the arguments or via `show signature help` shortcut.

**Comment by tgodzik** [comment]
Looks like has been fixed in the compiler.
