### ISSUE TITLE
No Hover on Collective Extensions

### ISSUE THREAD

**Issue by bishabosha** [scalameta/metals#1690]
**Describe the bug**
Collective extension method wrappers do not have a tooltip

**To Reproduce**
Open a fresh file foo.scala in a `0.23.0` project

```scala
object Foo:
  println("") // dummy statement because otherwise position of Foo collides with the extension

  extension on (s: String):
    def double = s + s
  end extension // no tooltip on hover

  println("") // dummy statement because otherwise position of Foo collides with the extension
end Foo
```

**Expected behavior**
A tooltip giving the name of the wrapper object

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Search terms**
scala 3, dotty, extension methods

**Comment by bishabosha** [comment]
This seems fixed for `0.24.0-RC1`

**Comment by tgodzik** [comment]
Thanks for reporting! I think we can close it if it's fixed in a later Scala version. Although I would fist add a test case here.

**Comment by tgodzik** [comment]
Closing this one - I think it's working OK now. Although there some other issues with extension methods, which I will follow up in a different issue.
