### ISSUE TITLE
Weird format of scala.Left on hover

### ISSUE THREAD

**Issue by bishabosha** [scalameta/metals#1691]
**Describe the bug**
The tooltip on hover on `Left` gives the type of its argument as its type

**To Reproduce**
Open a fresh file foo.scala in a `0.23.0` project

```scala
def foo = Left("") // tooltip: class Left: String
//        ^ cursor here
```

**Expected behavior**
A tooltip describing Left.apply

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Search terms**
scala 3, dotty, hover

**Comment by tgodzik** [comment]
Thanks for reporting! I do agree it looks weird, this should be just a fix of how we present the generic classes.

**Comment by ltrojanowski** [comment]
couldn't reproduce this with
![Screencast-2020-06-05-16_11_06](https://user-images.githubusercontent.com/3951626/83886504-707d5500-a747-11ea-9486-96ec92b97162.gif)

**Comment by bishabosha** [comment]
@ltrojanowski i copied what you did and get the same result, you must put the mouse cursor over "Left" and leave the caret on a different location of the source code

**Comment by tgodzik** [comment]
I think this is due to the fact that the `apply` there is synthetic. This might be a bit more complex.
