### ISSUE TITLE
annotations do not show correct tooltip in Dotty

### ISSUE THREAD

**Issue by bishabosha** [scalameta/metals#1693]
**Describe the bug**
annotations show the tooltip for the annotated definition, not the annotation

**To Reproduce**
Open a fresh file foo.scala in a `0.24.0-RC1` project

```scala
import annotation.infix

class Foo {
  @infix def + (that: Foo) = ???
// ^ cursor here: def +(that: Foo): Nothing
}
```

**Expected behavior**
A tooltip describing `annotation.infix`

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Search terms**
scala 3, dotty, annotation

**Comment by tgodzik** [comment]
Thanks for reporting! I can confirm, most likely issue in the presentation compiler
