### ISSUE TITLE
Code assist points out compile issues that don't exist

### ISSUE THREAD

**Issue by nsadeh** [scalameta/metals#1696]
**Describe the bug**

An error "identifier expected but '{' found" was surfaced by the Metals code assist without reason. sbt compile works and IntelliJ does not surface this issue.

Reloading developer window and restarting Bloop server fixed the issue, but not before spending unnecessary time looking for nonexistent issues in the code.

**To Reproduce**
Go through https://www.coursera.org/learn/progfun2/programming/ELLz8/json-codecs and implement `Decoder.field`

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**

I am working through https://www.coursera.org/learn/progfun2/programming/ELLz8/json-codecs (may need a Coursera account, but no pay is necessary - I am not paying). 

Implementing the following:

```scala
  def field[A](name: String)(implicit decoder: Decoder[A]): Decoder[A] = Decoder.fromFunction {
    case Obj(fields) => fields.get(name).flatMap(_.decodeAs(decoder))
  }
```

the last `}` got the error provided.

Some context code, property of Coursera and Martin Odersky/EPFL:

```scala
sealed trait Json {
  def decodeAs[A](implicit decoder: Decoder[A]): Option[A] = decoder.decode(this)
}

object Json {
  /** The JSON `null` value */
  case object Null extends Json
  /** JSON boolean values */
  case class Bool(value: Boolean) extends Json
  /** JSON numeric values */
  case class Num(value: BigDecimal) extends Json
  /** JSON string values */
  case class Str(value: String) extends Json
  /** JSON objects */
  case class Obj(fields: Map[String, Json]) extends Json
  /** JSON arrays */
  case class Arr(items: List[Json]) extends Json
}

trait Decoder[+A] {
  /**
    * @param data The data to de-serialize
    * @return The decoded value wrapped in `Some`, or `None` if decoding failed
    */
  def decode(data: Json): Option[A]
}

object Decoder extends DecoderInstances {
  def fromFunction[A](f: Json => Option[A]): Decoder[A] = new Decoder[A] {
    def decode(data: Json): Option[A] = f(data)
  }
}
```

**Comment by tgodzik** [comment]
Thanks for reporting! Sorry I haven't got to this sooner, it was in backlog to take a look here. Did this situation happen repeatedly? Did it happen since then? 

I am unable to reproduce it. Do you remember if the error came from Bloop or did it appear during typing?

**Comment by tgodzik** [comment]
Let's reopen it if we find a reliable reproduction.
