### ISSUE TITLE
Cannot import build using mill 0.6.1

### ISSUE THREAD

**Issue by meshake** [scalameta/metals#1700]
**Describe the bug**

As far as I understand metals ships with it's own mill build, which is currently at version 0.6.1. Unfortunately, this version contains a bug, where on Windows with java 8 an error is thrown when trying to import a build. See issue:  lihaoyi/mill#405

**To Reproduce**
1. Create a new folder foo with a file build.sc with the following contents:

```
import mill._, scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.13.1"
}
```

2. Open the folder in VS Code and click Import Build
3. Observe that "mill bloopinstall" runs forever and the output contains the following errors:

> 2020.05.06 14:36:20 INFO  running 'C:\Users\xxx\AppData\Local\Temp\metals3886844015490896242\millw.bat --mill-version 0.6.1 --predef C:\Users\xxx\AppData\Local\Temp\metals3886844015490896242\predef.sc mill.contrib.Bloop/install'
2020.05.06 14:36:21 INFO  Error: Could not create the Java Virtual Machine.
2020.05.06 14:36:21 INFO  Error: A fatal exception has occurred. Program will exit.
2020.05.06 14:36:21 INFO  Unrecognized VM option 'VMOptionsFile=C:\Users\xxx\Desktop\testmill\out\mill-worker-qq8Z5zqpvm7Xr\yBd+k6DpQPqRg=-1\vmoptions'

**Expected behavior**
I would expect the project to be imported with no issues

**Screenshots**

**Installation:**
- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**
It looks like this issue has been addressed on  lihaoyi/mill#791, which has been included in mill 0.6.2

**Search terms**
mill

**Comment by tgodzik** [comment]
Thanks for reporting! We should upgrade the default Mill version to 0.6.2, but in the meantime you can specify the version yourself via `.mill-version` file or by customizing the mill executable in the settings.
