### ISSUE TITLE
VSCode: Code completion in string interpolation is weird

### ISSUE THREAD

**Issue by takezoe** [scalameta/metals#1703]
**Describe the bug**

When I trigger the code completion in the string interpolation, its behavior is weird. Some completion proposals which should be available are not shown on the list of completion proposals.

For example, in the following case, `dir` is listed as expected:

<img width="1145" alt="Screen Shot 2020-05-07 at 0 17 26" src="https://user-images.githubusercontent.com/1094760/81194639-d9ae6300-8ff7-11ea-9fba-8f0a96175926.png">

However, if I type `d`, `dir` disappeared from the list somehow.

<img width="1164" alt="Screen Shot 2020-05-07 at 0 23 31" src="https://user-images.githubusercontent.com/1094760/81195355-a1f3eb00-8ff8-11ea-97a3-157deab9ceb4.png">

As long as I investigated, `MetalsLanguageServer` has always returned a proper list. So, it might not be a Metals issue.

It works properly in the following cases:

- Filter text doesn't contain `{` (`${d` doesn't work, but `$d` works)

<img width="1158" alt="Screen Shot 2020-05-07 at 0 29 38" src="https://user-images.githubusercontent.com/1094760/81195996-76bdcb80-8ff9-11ea-892a-9aa684a5fad4.png">

- String literal has `s` prefix and Scala code is inside `${...}`

<img width="1168" alt="Screen Shot 2020-05-07 at 0 24 10" src="https://user-images.githubusercontent.com/1094760/81195945-67d71900-8ff9-11ea-98f1-b9265e94b1bc.png">

**To Reproduce**

Trigger the code completion in the string interpolation on VSCode.

**Expected behavior**

Code completion works properly in the string interpolation.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Comment by tgodzik** [comment]
Thanks for tracking this down! I think I've seen the issue and forgot to report it.
