### ISSUE TITLE
Cannot import build using Mill

### ISSUE THREAD

**Issue by meshake** [scalameta/metals#1710]
**Describe the bug**
I have previously created an issue regarding a problem where Import Build was not working when using Mill 0.6.1 due to a known issue on Windows. See #1700 This issue has been fixed in version 0.6.2.

I have now tried to use Mill 0.6.2, but I still experience problems when importing the build.

**To Reproduce**
1. Create a new folder foo with a file build.sc with the following contents:

```
import mill._, scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.13.1"
}
```

2. Under foo/src create a file Test.scala with the following contents:
```
package foo

object Test extends App {
    println("Hello")
}
```

3. Now create .mill-version file (to force Metals to use Mill 0.6.2) and add this line to the file:
```
0.6.2
```
4. Open the folder in VS Code and click Import Build

5. Import fails with the following error:
```
2020.05.07 15:14:35 INFO  running 'C:\Users\xxx\AppData\Local\Temp\metals2867119147230238600\millw.bat --mill-version 0.6.2 --predef C:\Users\xxx\AppData\Local\Temp\metals2867119147230238600\predef.sc mill.contrib.Bloop/install'
2020.05.07 15:14:38 INFO  Compiling (synthetic)/ammonite/predef/interpBridge.sc
2020.05.07 15:14:44 INFO  Compiling (synthetic)/ammonite/predef/sourceBridge.sc
2020.05.07 15:14:45 INFO  Compiling (synthetic)/ammonite/predef/frontEndBridge.sc
2020.05.07 15:14:45 INFO  Compiling C:\Users\xxx\Desktop\testmill\build.sc
2020.05.07 15:14:48 INFO  Cannot resolve --mill-version. Try `mill resolve _` to see what's available.
2020.05.07 15:14:48 INFO  Failed to connect to server
2020.05.07 15:14:48 INFO  build tool exit: 1
2020.05.07 15:14:48 INFO  time: ran 'mill bloopInstall' in 13s
2020.05.07 15:14:48 ERROR Mill command failed: C:\Users\xxx\AppData\Local\Temp\metals2867119147230238600\millw.bat --mill-version 0.6.2 --predef C:\Users\xxx\AppData\Local\Temp\metals2867119147230238600\predef.sc mill.contrib.Bloop/install
2020.05.07 15:14:48 INFO  disconnected: build server
```

It looks like the **--mill-version** flag was replaced with **--version** in 0.6.2

6. As an alternative, I tried to instead work around this by specifying Mill executable in settings (Settings -> Extensions -> Metals -> Mill Script):

```
C:\Users\xxx\scoop\apps\mill\0.6.2\mill.bat -i
```

7. Now when i click Import Build I get a new exception:

```
2020.05.07 15:18:41 INFO  running 'C:\Users\xxx\scoop\apps\mill\0.6.2\mill.bat -i --predef C:\Users\xxx\AppData\Local\Temp\metals3600414389922596502\predef.sc mill.contrib.Bloop/install'
java.lang.RuntimeException: CreateProcessW() failed, error: 2
	at com.zaxxer.nuprocess.windows.WindowsProcess.prepareProcess(WindowsProcess.java:301)
	at com.zaxxer.nuprocess.windows.WindowsProcess.start(WindowsProcess.java:228)
	at com.zaxxer.nuprocess.windows.WinProcessFactory.createProcess(WinProcessFactory.java:42)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:259)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:78)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:51)
	at scala.meta.internal.builds.BloopPluginBuildTool.bloopInstall(BloopPluginBuildTool.scala:15)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:49)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1450)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1436)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020.05.07 15:18:41 INFO  build tool exit: -2147483648
2020.05.07 15:18:41 INFO  time: ran 'mill bloopInstall' in 14ms
2020.05.07 15:18:41 ERROR Mill command failed: C:\Users\xxx\scoop\apps\mill\0.6.2\mill.bat -i --predef C:\Users\xxx\AppData\Local\Temp\metals3600414389922596502\predef.sc mill.contrib.Bloop/install
2020.05.07 15:18:41 INFO  disconnected: build server
```

**Expected behavior**
It should import the build

**Screenshots**

**Installation:**
- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**
As a workaround, I can execute the bloop install command seen in step 7 manually via command line (without any problems) and then click Import Build to force the Metals to update the Packages view in VS Code. But this must be done every time the build file changes.

**Search terms**
Mill

**Comment by tgodzik** [comment]
Thanks for reporting! We are using the `-mill-version` in our tests and it's all still working, so I don't think that option changed. Could that have only changed on Windows? We are not running mill test on windows.

When running locally we have:
```
2020.05.07 17:20:32 INFO  running '/tmp/metals1355560132562392643/millw --mill-version 0.6.2 --predef /tmp/metals1355560132562392643/predef.sc mill.contrib.Bloop/install'
2020.05.07 17:20:32 INFO  Downloading mill 0.6.2 from https://github.com/lihaoyi/mill/releases ...
```

> As an alternative, I tried to instead work around this by specifying Mill executable in settings (Settings -> Extensions -> Metals -> Mill Script):
> C:\Users\xxx\scoop\apps\mill\0.6.2\mill.bat -i

Not sure about `-i` it might be escaped together with the command. Could try just setting `C:\Users\xxx\scoop\apps\mill\0.6.2\mill.bat`

**Comment by meshake** [comment]
@tgodzik Without the ```-i``` option it looks like the import only partially fails

```
2020.05.07 18:12:39 INFO  running 'C:\Users\xxx\scoop\apps\mill\0.6.2\mill.bat --predef C:\Users\xxx\AppData\Local\Temp\metals5251457380866032358\predef.sc mill.contrib.Bloop/install'
2020.05.07 18:12:40 INFO  [1/23] foo.sources 
2020.05.07 18:12:40 INFO  [4/23] mill.contrib.bloop.BloopImpl.moduleSourceMap 
2020.05.07 18:12:40 INFO  [13/23] foo.resources 
2020.05.07 18:12:40 INFO  [23/23] mill.contrib.bloop.BloopImpl.install 
2020.05.07 18:12:40 INFO  Failed to connect to server
2020.05.07 18:12:40 INFO  build tool exit: 1
2020.05.07 18:12:40 INFO  time: ran 'mill bloopInstall' in 0.97s
2020.05.07 18:12:40 ERROR Mill command failed: C:\Users\xxx\scoop\apps\mill\0.6.2\mill.bat --predef C:\Users\xxx\AppData\Local\Temp\metals5251457380866032358\predef.sc mill.contrib.Bloop/install
2020.05.07 18:12:40 INFO  disconnected: build server
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 35447'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:35447...
The server is listening for incoming connections at tcp://127.0.0.1:35447...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
2020.05.07 18:12:40 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\Users\xxx\Desktop\testmill\null\scalameta\metals\cache\bsp.trace.json
2020.05.07 18:12:40 INFO  time: connected to build server in 0.17s
2020.05.07 18:12:40 INFO  Connected to Build server v1.4.0-RC1-229-b7c15aa9
2020.05.07 18:12:40 INFO  time: indexed workspace in 0.2s
```

If I run the command manually:

C:\Users\xxx\scoop\apps\mill\0.6.2\mill.bat --predef C:\Users\xxx\AppData\Local\Temp\metals5251457380866032358\predef.sc mill.contrib.Bloop/install
```
?[34m[1/23] foo.sources ?[39m
?[1A?[2K?[9999D?[34m[4/23] mill.contrib.bloop.BloopImpl.moduleSourceMap ?[39m
?[1A?[2K?[9999D?[34m[13/23] foo.resources ?[39m
?[1A?[2K?[9999D?[34m[23/23] mill.contrib.bloop.BloopImpl.install ?[39m
Failed to connect to server
```

If I run the command manually with the ```-i``` option then the "**Failed to connect to server**" disappears.

**Comment by tgodzik** [comment]
> If I run the command manually with the `-i` option then the "**Failed to connect to server**" disappears.

What does the -i option does? Maybe we could add it by default? 

> Regarding the --mill-version flag, it doesn't seem to be able to resolve it on Windows:

It seems that --version only prints the current version, which is not what we are after. `--mill-version` is actually used in the `millw.bat` script only. So mill itself will not work with it. It should not be forwarded to mill itself. 

@lefou any idea what might be the issue here?

**Comment by tgodzik** [comment]
Or maybe we should always use `-i` on windows? Will that break anything?

**Comment by meshake** [comment]
`-i` option is interactive mode. On http://www.lihaoyi.com/mill/index.html it says:

> In some environments (such as WSL), mill might have to be run using interactive mode (-i)

**Comment by tgodzik** [comment]
> `-i` option is interactive mode. On http://www.lihaoyi.com/mill/index.html it says:
> 
> > In some environments (such as WSL), mill might have to be run using interactive mode (-i)

I will ask and maybe we can just use it always on Windows.

**Comment by meshake** [comment]
Thanks!

**Comment by lefou** [comment]
`mill -i` does not start a background mill server process to do the work but instead does everything in the current JVM. This is needed when used interactively, that's why it's called "interactive". Because the socket communication is known to not work correctly under Windows, it is safe to always use the `-i` option. The only consequence is, that the JVM always starts cold, e.g. with a somewhat slower compiler.

**Comment by lefou** [comment]
The `--mill-version` option exists only in `millw` (bat or sh, https://github.com/lefou/millw) but not in the `mill` script that comes with mill itself. But both scripts support a `.mill-verison` file as well as a `MILL_VERSION` environment variable.

**Comment by tgodzik** [comment]
Thanks @lefou ! I think it's save to set `-i` as default then. I will check the bat script on windows since this worries me:
```
2020.05.07 15:14:35 INFO  running 'C:\Users\xxx\AppData\Local\Temp\metals2867119147230238600\millw.bat --mill-version 0.6.2 --predef C:\Users\xxx\AppData\Local\Temp\metals2867119147230238600\predef.sc mill.contrib.Bloop/install'
2020.05.07 15:14:38 INFO  Compiling (synthetic)/ammonite/predef/interpBridge.sc
2020.05.07 15:14:44 INFO  Compiling (synthetic)/ammonite/predef/sourceBridge.sc
2020.05.07 15:14:45 INFO  Compiling (synthetic)/ammonite/predef/frontEndBridge.sc
2020.05.07 15:14:45 INFO  Compiling C:\Users\xxx\Desktop\testmill\build.sc
2020.05.07 15:14:48 INFO  Cannot resolve --mill-version. Try `mill resolve _` to see what's available.
2020.05.07 15:14:48 INFO  Failed to connect to server
```
looks like the param to the bat script is being forwarded to `mill` itself

**Comment by lefou** [comment]
Hm, looks suspicious. Found the following lines in the bat script:

```bat
if [%~1%]==[--mill-version] (
    rem shift command doesn't work within parentheses
```

Looks like under windows it currently does not removes the parameters before forwarding to mill. This is of course not right. I can try to fix it but I'm a bit short in time. If a fix is obvious to you/anybody I'm looking forward to it.

**Comment by meshake** [comment]
Hey, so we all don't spend time on this, I have already started looking more into this and I believe I have a fix. I will try to create a pull request soon.
