### ISSUE TITLE
When copying multiline string, pipes get inserted wrongly

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1712]
**Describe the bug**
Seems that sometime pipes will get added even if we only copy code containing a multiline string

**To Reproduce**
1. Go to metals repository
2. Go to file SbtLspSuite
3. Copy lines [29-35](https://github.com/scalameta/metals/blob/65087a2b855c25126fe0f471ee89a64032ca3e7a/tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala#L29-L35) 
4. Paste them after the test in line [67](https://github.com/scalameta/metals/blob/65087a2b855c25126fe0f471ee89a64032ca3e7a/tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala#L67)

**Expected behavior**
No pipes are added

**Screenshots**

![image](https://user-images.githubusercontent.com/3807253/81323582-e41f3a00-9095-11ea-891d-8fd2e15257a7.png)

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Search terms**
multiline string pipes

**Comment by tgodzik** [comment]
@mlachkar Could you take a look here?

**Comment by colineto** [comment]
Just an **hint** until it's fixed : `cmd + z` after paste will remove all the undesired pipes

**Comment by mlachkar** [comment]
Yes, I will have a look.
