### ISSUE TITLE
no build target for files from multi-jvm scope

### ISSUE THREAD

**Issue by kpritam** [scalameta/metals#1751]
**Describe the bug**

Does not recognise multi-jvm modules

**To Reproduce**
1. Add multi-jvm plugin in build.sbt
2. Enable MultiJvm plugin for one of the sbt module
3. Add scala file in `multi-jvm` directory
4. Error 
`2020.05.15 12:53:11 WARN  no build target for: src/multi-jvm/scala/esw/ocs/app/SequencerTest.scala`

**Expected behavior**

Code completion, goto and other metals features should work in multi-jvm scope

**Screenshots**

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! It looks like the `multi-jvm` source directory is not being added to the bloop configuration. We should report that in Bloop. A current workaround would be to 
1. Add the directory manually like:

```src
    unmanagedSourceDirectories.in(Compile) += baseDirectory
      .in(ThisBuild)
      .value / "src" / "multi-jvm" / "scala",
```
2. Run import build.
3. New code can be removed.

**Comment by tgodzik** [comment]
Reported it here: https://github.com/scalacenter/bloop/issues/1280
