### ISSUE TITLE
Add -J to JVM options automatically when running

### ISSUE THREAD

**Issue by Pradhyo** [scalameta/metals#1765]
Our project uses [pureconfig](https://github.com/pureconfig/pureconfig) and a non-default config file path by setting `config.file` as described [here](https://github.com/lightbend/config#standard-behavior).

The path works fine and the project runs as expected in Eclipse.
![](https://i.stack.imgur.com/JABnf.png)

I tried these methods to set the value but it couldn't pick it up:

1. putting this in a `.jvmopts`in the root directory
`-Dconfig.file=/path/to/config/file`

2. Setting it in the extension settings
![image](https://user-images.githubusercontent.com/7895492/82101798-831de480-96db-11ea-85a5-43c3f8c6a1f7.png)

What worked was using [System.setProperty](https://www.tutorialspoint.com/java/lang/system_setproperty.htm) right before using `pureconfig.loadConfigOrThrow`

`System.setProperty("config.file", "/path/to/config/file")`

**Comment by Pradhyo** [comment]
Got it - please close this issue as you see fit, I am good. Thanks again for the quick response!

**Comment by singh-abhijeet** [comment]
> Thanks for reporting! The `server properties` are properties needed specifically for the Metals language server and they are not used when running. You need to specify a run configuration first:
> 
> ```
>     {
>       "type": "scala",
>       "request": "launch",
>       "name": "MyMain",
>       "mainClass": "com.example.MyMain",
>       "args": [],
>       "jvmOptions": ["-J-Dconfig.file=/path/to/config/file"]
>     }
> ```

@tgodzik Hi, trying this approach for passing `--add-exports` is giving error: 
`Unrecognized option: --add-exports java.base/sun.nio.ch=ALL-UNNAMED`

This is how my launch.json looks:
```
{
    "version": "0.2.0",
    "configurations": [
      // Main class configuration
      {
        "type": "scala",
        "request": "launch",
        // configuration name visible for the user
        "name": "Launch Main",
        // full name of the class to run
        "mainClass": "SparkStreamingMain",
        // optional arguments for the main class
        "args": [],
        // optional jvm properties to use
        "jvmOptions": ["--add-exports java.base/sun.nio.ch=ALL-UNNAMED"]
      }
    ]
  }
```

Let me know how to pass [--add-exports](https://stackoverflow.com/questions/40313090/java-9-options-add-exports-vs-xaddexports-not-recognized) via jvmOpts.

**Comment by singh-abhijeet** [comment]
Thanks for the reply Tomas. I am using JDK 17.0.5 for both - Metals server
and bloop.

**Comment by tgodzik** [comment]
Does it work if you do `-J--add-exports java.base/sun.nio.ch=ALL-UNNAMED` though that should be automatic :thinking: 

Or maybe it's getting escaped:
`["--add-exports, java.base/sun.nio.ch=ALL-UNNAMED"]` <- try with coma instead of space.

**Comment by singh-abhijeet** [comment]
Adding -J gives the same error: `Unrecognized option: --add-exports java.base/sun.nio.ch=ALL-UNNAMED`

and using comma does not help either: `Unrecognized option: --add-exports, java.base/sun.nio.ch=ALL-UNNAMED`

Let me know what I am missing.

**Comment by tgodzik** [comment]
```
2022.11.23 23:13:26 INFO  Starting debug proxy for [SparkStreamingMain]
2022.11.23 23:13:29 ERROR Error: Could not create the Java Virtual Machine.
2022.11.23 23:13:29 ERROR Error: A fatal exception has occurred. Program will exit.
2022.11.23 23:13:29 ERROR Unrecognized option: --add-exports, java.base/sun.nio.ch=ALL-UNNAMED
```
There is also an option that the build was imported with a different Java version and that is used for running programs. Could you check in the doctor `Metals: Run doctor` and then click on any target to check the jvmHome?

**Comment by tgodzik** [comment]
> Unrecognized option: --add-exports, java.base/sun.nio.ch=ALL-UNNAMED

Actually, this looks like the entire option is this string including coma and spaces, which is invalid. What is your current configuration?

Should be something like:
```
{
    "version": "0.2.0",
    "configurations": [
      // Main class configuration
      {
        "type": "scala",
        "request": "launch",
        // configuration name visible for the user
        "name": "Launch Main",
        // full name of the class to run
        "mainClass": "SparkStreamingMain",
        // optional arguments for the main class
        "args": [],
        // optional jvm properties to use
        "jvmOptions": ["--add-exports", "java.base/sun.nio.ch=ALL-UNNAMED"]
      }
    ]
  }
```

**Comment by singh-abhijeet** [comment]
My config was like [this](https://github.com/scalameta/metals/issues/1765#issuecomment-1324706885), but once I updated it to 2 strings separated by comma: `"jvmOptions": ["--add-exports", "java.base/sun.nio.ch=ALL-UNNAMED"]`, **it worked!**

Thanks for the resolution Tomas, you're amazing! :)

**Comment by tonyrusignuolo** [comment]
Is there a way to make those jvm options available everywhere? I'm trying to run tests from the test explorer, but it isn't respecting the args that are in the launch.json or in my pom.xml

**Comment by tonyrusignuolo** [comment]
Both seem like logical expectations IMO. I feel like the test explorer should run the tests exactly like my CLI would, but have the option to override that config. Unless there are obvious argument against? Full disclosure, I'm a relatively new Java / Scala dev

**Comment by tonyrusignuolo** [comment]
What would supporting either (or both) of those entail and how might that effect existing functionality? Would be happy to try and contribute back, just would like some help on where to start :)

**Comment by tgodzik** [comment]
This depends on whether you are using Bloop or sbt.

If using Bloop we should make sure that `Test / javaOptions` actually contains what you need and it's forwarded to platform section of the relevant json test module in `.bloop`

For sbt, setting javaOptions should work, unless we are doing something wrong in Scala Debug Adapter.
