### ISSUE TITLE
Dotty project reports "Recursion limit exceeded." at package declaration

### ISSUE THREAD

**Issue by heksesang** [scalameta/metals#1768]
**Describe the bug**
In a Dotty project, I am seeing the following error in the package declaration (with red squiggly line under the first segment of the package):

```
Recursion limit exceeded.
Maybe there is an illegal cyclic reference?
If that's not the case, you could also try to increase the stacksize using the -Xss JVM option.
A recurring operation is (inner to outer):

  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  ...

  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala.Serializable
  find-member scala#Predef bloop
```

**To Reproduce**
1. Create a new project folder.
2. Add a `build.sc` file with the following content:
```scala
import mill._, scalalib._

object core extends ScalaModule {
  def scalaVersion = "0.23.0"
}
```
3. Add the file `core/src/mypackage/MyClass.scala` with the following content:
```scala
package mypackage

class MyClass

```
4. Import the project in VS Code.
5. Open the file `core/src/mypackage/MyClass.scala`.
6. The error appears on the first line, with squiggly line under `mypackage`.

**Expected behavior**
No error.

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.9.0+96-2e62ed4d-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! I will take a look at it. Have you tried setting a higher `-Xxss` inside `~/.bloop/.jvmopts` ? That could help for now.

**Comment by tgodzik** [comment]
@heksesang This seems to be an issues with the mill generating bad config files for Bloop:
```
        "classpath": [
            "/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/lamp/scala-library/0.23.0/scala-library-0.23.0.jar",
            "/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/lamp/dotty-library_0.23/0.23.0/dotty-library_0.23-0.23.0.jar",
            "/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar"
        ],
```

It adds `scala-library-0.23.0.jar` in classpath and jars sections. Could you report it in Mill ?

**Comment by heksesang** [comment]
Shouldn't a Dotty config file contain that library?

**Comment by tgodzik** [comment]
Dotty needs the dotty_library 0.23 but it also uses scala_library 2.13.2. However there is no such thing as scala_library 0.23. After I removed it from the Bloop config the project started working.

**Comment by heksesang** [comment]
Alright, I'll have a look at it. Will report it to the mill project. :)

**Comment by tgodzik** [comment]
Ach, I didn't realize that jar was published. This might also need to be fixed also in Dotty, but the Mill build should also not add that library.
