### ISSUE TITLE
Fresh install, BSP fails to start, socket returned with error

### ISSUE THREAD

**Issue by k3mist** [scalameta/metals#1773]
**Describe the bug**
metals in vscode fails to start the bsp server with the following error. 

I'm also getting a "no build target found for the workspace" in the doctor

```Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher8785047075043580937/bsp.socket'...
Waiting for the bsp connection to come up...
error: The command bsp --protocol local --socket /tmp/bsp-launcher8785047075043580937/bsp.socket returned with an error
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 39234'...
Waiting for the bsp connection to come up...
error: The command bsp --protocol tcp --port 39234 returned with an error
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.05.21 20:32:10 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:107)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Installation:**
- Operating system: Linux
- Editor: VSCode
- Metals version: v0.9.0
- Gradle build

**Additional context**
I'm new to vscode and metals (trying to move away from intellij). I apologize in advance for any missing information/logs (happy to retrieve it if told where). Having this issue on a fresh install.

Interestingly, I installed bloop 1.3.4 manually (saw this elsewhere on one of the bug reports) and when running bloop server in the background and restarting vscode all seems to work fine outside of the warning I get about metals 0.9 wanting to run on bloop 1.4.0-RC..

So it works (code completion, referencing, etc), just not with the vscode/metals extension backed bsp. Even working on the manual install bsp version it says it doesn't want to run on..

I thought my issue might be related to https://github.com/scalameta/metals/issues/1306

I verified `"metals.javaHome"` is set correctly. I'm using sdkman so also thought the symlink was causing an issue (shot in the dark) and used the full path to jdk, however same thing. $JAVA_HOME is also set correctly.

Kinda at a loss here since I'm not familiar with vscode or metals. Seems like a bug from my perspective being in a "fresh install" type state with this, but could very easily be my fault, not really sure.

Any help greatly appreciated, would love to get this up and running

**Comment by tgodzik** [comment]
Thanks for reporting! This is usually connected to Bloop not being able to find the `java` executable. Could you maybe start VS Code from a terminal with JAVA_HOME set? I wonder if that is the issue.
Did the build import from Gradle complete successfully also?

Alternatively you can start Bloop separately via coursier: https://scalacenter.github.io/bloop/setup#universal

**Comment by k3mist** [comment]
Thanks @tgodzik. It works when I start it from the CLI. I suppose I should have tried that lol. 

My JAVA_HOME is set/managed by `sdkman` with my paths set via .zshrc and I've never had path issues before with that. Guessing this is a VSCode related issue?

Yes, the import from Gradle works correctly. When I delete .bloop from the project directory it has no issue rebuilding, but I then get that error.

I'm perfectly fine with this workaround, but would like to know if there is a possible resolution that would allow me to start VS Code from my dock in Plasma?

I suppose I could also make bloop server part of my autostart but would prefer not.

**Comment by tgodzik** [comment]
@k3mist this was actually recently fixed and we haven't yet released a new version. We will add JAVA_HOME automatically for Metals and Bloop starting from the next release.

**Comment by k3mist** [comment]
@tgodzik thank you, great to hear!
