### ISSUE TITLE
Simplify installation

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#178]
Currently, the installation steps are a sequence of several fairly fragile steps. https://github.com/scalameta/language-server/blob/master/BETA.md Any mistake could make nothing work, or half-work with no instructions on what's missing.

We should strive for as simple installation as possible but avoid 100% automagical setup that makes it difficult to track down what went wrong. For sbt, I propose

* addSbtPlugin
* document how to enable semanticdb-scalac compiler plugin
* `> metalsSetup` via sbt, downloads source jars, emit classpath and other stuff

TODOs:

* [ ] create sbt-metals plugin from project/MetalsPlugin.scala. We can depend on the plugin in the metals build by using `unmanagedSources in Compile ++= (baseDirectory.value.getParentFile / "sbt-metals").descedantsExcept("*.scala", ..).get`

**Comment by xeno-by** [comment]
I think that requiring users to enable `semanticdb-scalac` manually is one step too much.

**Comment by cquiroz** [comment]
It would be great to streamline the process. I’d also like to have the ability to enable it without the need to change a project’s build.sbt for teams where only some users want to use semanticDb

**Comment by laughedelic** [comment]
> I’d also like to have the ability to enable it without the need to change a project’s build.sbt for teams where only some users want to use semanticDb

JFYI, you can achieve that by adding settings in a separate sbt file, for example, `ignore.sbt` and then adding this name to your global `.gitignore`.

**Comment by olafurpg** [comment]
> I’d also like to have the ability to enable it without the need to change a project’s build.sbt for teams where only some users want to use semanticDb

@cquiroz That should be doable with `semanticdbEnable`. Can you explain what your ideal installation/setup flow would be?


> I think that one sbt plugin and one command is acceptable, but additional requirements (e.g. requiring the users to configure semanticdb-scalac) are too much.

@xeno-by I'm afraid automatic installation of compiler plugins is out the question. I've tried it in sbt-scalafix and it was a mistake. Many projects set `libraryDependencies :=` and/or `scalacOptions :=` which makes it impossible for plugins to modify. An explicit installation step for the plugin makes things a lot easier from my experience, and with `semanticdbEnable` it should be doable to quickly update a running sbt session.

**Comment by cquiroz** [comment]
My comment was along the lines of "let's preserve `semanticdbEnable`, its great

**Comment by olafurpg** [comment]
Sweet, glad to hear that :)

**Comment by olafurpg** [comment]
Assuming users don't need to locally build the server or plugin, are the following steps sufficiently simple enough for a v0.1 release?

* install editor plugin in market place
* open directory
* addSbtPlugin(sbt-metals)
* `sbt semanticdbEnable *:metalsSetup`

**Comment by gabro** [comment]
They should be!

Does this mean we're going to publish an `sbt-metals` plugin?

**Comment by olafurpg** [comment]
As much as I'd love to avoid having an sbt plugin, I think we can't avoid publishing sbt-metals.

**Comment by laughedelic** [comment]
I started moving `project/MetalsPlugin.scala` to a separate subproject and realized that this way we cannot have it cross-built for sbt 0.13 and 1.0 because it requires using sbt 0.13.17. I see these options:

1. build it only for sbt 1.0
2. change whole project build to sbt 0.13 (IMO not nice 👎)
3. keep it as an independent sbt project in the repo
4. have a separate repo with an independent sbt project for it 

What do you think? I personally would prefer either option 4 or 1. Having sbt 1.0-only plugin is the simplest and I think is acceptable in the early stage of the project. Later if we completely automate setup with sbt 1.2+, we can keep around the plugin and change it to sbt 0.13 as an alternative setup for old projects.

**Comment by olafurpg** [comment]
I believe there's quite a significant number of builds still on 0.13 (including scalameta and scalafix). I think it's fine to go for option 1 and then have the 0.13 plugin as a separate sbt build/directory in the same repo. I can setup the 0.13 plugin if you setup the 1.0 plugin. Wdyt?

**Comment by laughedelic** [comment]
> I think it's fine to go for option 1 and then have the 0.13 plugin as a separate sbt build/directory in the same repo

Isn't it option 3 then? I mean, if we keep it as an independent sbt project, it can be easily cross-built for sbt 0.13/1.0, no need for duplication.

**Comment by gabro** [comment]
Closing this in favor of #220.

(tracking the sbt-metals plugin in #219)

**Comment by gabro** [comment]
As per https://github.com/scalameta/metals/issues/178#issuecomment-377811791, I vote for 3 as well
