### ISSUE TITLE
Is `remoteLogging` happening for the Ammonite integration?

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1782]
## Question

Prompted by a question on Gitter about whether or not `remoteLogging` is happening every time that Ammonite is invoked via Metals.

A relevant discussion about this can be found [here in the Ammonite Repo](https://github.com/lihaoyi/Ammonite/issues/607). It seems that this is able to be turned off by passing in `--no-remote-logging`.

@alexarchambault will have the most details on this, but when a BSP connection is established with Ammonite, is `ammonite.Main` run on every compile? If so, then I'm assuming that the default `remoteLogging = true` is there, and therefore sending statistics?

https://github.com/lihaoyi/Ammonite/blob/ef9b0a0477ff608acb432fb0c58f0a16c0240918/amm/src/main/scala/ammonite/Main.scala#L60-L77

### Follow-up Question

_If_ Ammonite is indeed being called with `remoteLogging` set to true, can we pass in `--no-remote-logging`? This would possible need to happen in https://github.com/alexarchambault/ammonite-runner?

**Search terms**

Ammonite

**Comment by ckipp01** [comment]
This is not an issue. I dove into this, and it didn't actually seem like `remoteLogging` was actually being used anywhere. Indeed, the setting is here, but it's just dead code. The actual `RemoteLogger` class that did this was removed in this commit: https://github.com/lihaoyi/Ammonite/commit/2fdd2dfe772d07cf59613a563167218936ae5013

**Comment by alexarchambault** [comment]
My bad, this slipped through in my mentions… Yeah, it seems the `remoteLogging` field is unused, and that `RemoteLogger` went away.
