### ISSUE TITLE
Document which features require which setup

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#179]
It's currently undocumented what features require which setup.
We should document clearly which installation steps are necessary for which functionality.
For example, definition/references/scalafix work mostly fine as long as semanticdb-scalac is enabled even if *:scalametaEnableCompletions didn't run. Definition to project sources requires scalametaEnableCompletions. We should also try to make the server respond with helpful diagnostics when things are not working, maybe like a "Troubleshoot" command that prints out what's configured

**Comment by gabro** [comment]
@olafurpg does the new documentation address this?

**Comment by olafurpg** [comment]
Yes. See https://github.com/scalameta/metals/blob/master/docs/overview.md
