### ISSUE TITLE
Failed to debug a scala maven project

### ISSUE THREAD

**Issue by Khalid-Nowaf** [scalameta/metals#1805]
**Describe the bug**
Running the debugger in a scala maven project produce the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Predef$
	at com.test.App$.main(App.scala:11)
	at com.test.App.main(App.scala)
Caused by: java.lang.ClassNotFoundException: scala.Predef$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

which indicate that all the dependencies, including scala are not included.

Also, the following command runs with no issues in the maven project
```
mvn compile
mvn test
mvn package
```
**To Reproduce** Steps to reproduce the behavior:

1. generate new mavan scala project ` mvn archetype:generate`
2. enter the following to filler the selection `net.alchim31.maven:scala-archetype-simple`
3. enter '1'
4. follow the rest instructions to generate the project
5. once the project created, open it with vscode and try to run the debugger 

**Expected behavior**

Scala maven projects should be runable and debugable as scala sbt project

**Comment by tgodzik** [comment]
@Khalid-Nowaf as a current workaround you can edit out `classpath: []` in the json file corresponding to the project you are trying to run. More details here: https://github.com/scalacenter/bloop/pull/1303

**Comment by Khalid-Nowaf** [comment]
Thanks for the workaround, but what about other external depdancies? Should be added and managed as well. Is there any way to make this inferred from the pom file ?

**Comment by tgodzik** [comment]
> Thanks for the workaround, but what about other external depdancies? Should be added and managed as well. Is there any way to make this inferred from the pom file ?

I think in case that there is no `classpath` in the platform settings it uses the project classpath itself. Not 100% sure, but it did always work for me without specifying any additional classpath.
