### ISSUE TITLE
Metals doesn't recognize a Java only project

### ISSUE THREAD

**Issue by Arthurm1** [scalameta/metals#1815]
**Describe the bug**
Metals/VSCode doesn't show Java only projects in the TreeView or Metals Doctor and gives an error when trying to run the project using a launch.json

Running `bloop projects` lists the Java project and `bloop run javaprojectname` works fine

**To Reproduce**
1. Create a Java only project with a mainClass to run.  I used Gradle _without_ the Scala plugin
2. On VSCode run Import Build
3. See there is no Java project under the Packages TreeView or in the Metals Doctor
4. Create a launch.json pointing to the project mainclass
5. Run the launch and get `Couldn't find a debug adapter descriptor for debug type 'scala' (extension might have failed to activate)`

**Expected behavior**
VSCode used to list the java projects as well as the Scala ones in the TreeView/Doctor - I'm not sure what version this changed in.  I have not tested the VSCode launch before.
If I add the Scala plugin and the scala-library dependency to the Gradle project and re-import into VSCode then it will appear in the TreeView and run the launch even though it is pure Java.

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**
bsptrace shows
```json
"languageIds": [
        "java"
      ]
"capabilities": {
        "canCompile": true,
        "canTest": true,
        "canRun": true
      },
      "dataKind": "scala"
```
Compared to Scala projects it is missing the `"scala"` under `"languageIds"`.  It is also missing the whole `"data"` section of the project target.  Does Metals filter on either of those?
In the Bloop JSON file there is no `"scala"` section

**Search terms**
Java

**Comment by tgodzik** [comment]
Thanks for reporting! This is expected in case of Java only projects. VS Code plugin only activates on Scala projects. This is the standard in case of Visual Studio Code plugins, they should not activate on unrelated workspaces and it was previously reported as a bug. 

We could add a manual command to enable a plugin or alternatively, you can create a Scala file, which should activate the plugin.

However, in case of Java only project I would suggest using the VS Code java plugin, which will provide much more possibilities until the java support is properly implemented for Metals. This obviously will not work with Bloop, but I don't think we do gain a lot using it on Java projects.

**Comment by tgodzik** [comment]
Added new activasion event `"onDebugResolve:scala",` which will hep in your case. It will launch Metals and run the main class. 

There is still some issue in case of java classes that I need to figure out still though.

**Comment by tgodzik** [comment]
Alright, there was also a bug in Metals that would filter out non Scala build targets and not run anything. Now, you should be able to just run a Scala configuration, which will activate Metals and try to run. There might be a race condition between the extension activating and Bloop connection starting, but you should be able to just press F5 again to have it running. Also best to specify the buildTarget in that case, because we will try to compile it if the class doesn't exist.

I will take a look later to see if the race condition is easy to fix, but it might not make too much sense to put too much effort into it.

**Comment by Arthurm1** [comment]
Thanks a lot for doing this Tomasz - I realise that Java interaction is a much lower priority than Scala IDE features.

**Comment by tgodzik** [comment]
Glad to help, it was a small enough issue.
