### ISSUE TITLE
Build server cannot run after click 'import build' at VSCode.

### ISSUE THREAD

**Issue by rchatsiri** [scalameta/metals#1816]
**Question**

VSCode cannot run bsp command line after click ``` Import build ```

**Screenshots**
20.06.11 00:08:24 INFO  skipping build import with status 'Installed'
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 15579'...
Waiting for the bsp connection to come up...
error: The command bsp --protocol tcp --port 15579 returned with an error
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.06.11 00:08:25 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:107)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)

**Installation:**
 
- Editor: Visual Studio Code
- Metals version: v0.9.0
- Windows OS
- JAVA  version: jdk-11.0.7.10-hotspot

**Additional context**
1) Search ```Metals: Java Home``` at ``` Setting dialogue```  and Add JAVA_HOME path.  
2) Add ``` sbt.bat ``` at ```Metals: Sbt Script```
3) Setting file for build with sbt by add this line.
``` addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.1")``` into ```project/plugins.sbt```. 
4) Run command line ``` sbt -Dbloop.export-jar-classifiers=sources bloopInstall ```
5) Click 'Import build' at Metals Icon besides left task bar of VSCode.

**Search terms**

#bloop #setting #bsp

**Comment by rchatsiri** [comment]
> 
> 
> Thanks for reporting! Do you have `java` on PATH ? We recently had a regression that caused JAVA_HOME that is set in Metals settings not to be used.

Should set path JAVA_HOME as main java directory? I'm setting JAVA_HOME is ``` C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot ```.  Not sure do you mean ``` C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin\ ``` or not.

**Comment by tgodzik** [comment]
> > Thanks for reporting! Do you have `java` on PATH ? We recently had a regression that caused JAVA_HOME that is set in Metals settings not to be used.
> 
> Should set path JAVA_HOME as main java directory? I'm setting JAVA_HOME is `C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot`. Not sure do you mean `C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin\` or not.

Your JAVA_HOME is correct, however when we start the build server it uses java that is on path and not the one from JAVA_HOME. This was fixed previously, but we had a regression currently.

You need to add  `C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin\` to PATH currently.

**Comment by tgodzik** [comment]
This should be fixed in 0.9.1. closing it for now. Let me know if this happens again.
