### ISSUE TITLE
`xml.Elem` incorrectly displayed in worksheets

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1835]
**Describe the bug**
When you try to use an xml literal in worksheets, you get some odd behavior where you just see a bunch of nested `Elem`s.

**To Reproduce**
1. Open a worksheet
2. Try the following:
```scala
val test = <rss></rss>
```
3. Save the worksheet
4. See behavior

<img width="1064" alt="Screenshot 2020-06-16 at 19 39 55" src="https://user-images.githubusercontent.com/13974112/84809794-bb7e4e80-b00a-11ea-9c6c-787767e94f3c.png">

**Expected behavior**
I would expect this to evaluate to something a bit more meaningful. For example, here is the output when ran in Ammonite:

```sh
@ val test = <rss></rss>
test: xml.Elem = <rss></rss>
```

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code and Vim
- Metals version: Latest snapshot

**Search terms**
worksheets, xml

**Comment by tgodzik** [comment]
Thanks for reporting! This looks like an error in pprint:
```
object MainTest extends App{
  val test = <rss></rss>
  pprint.log(test)
}
```

produces:

![image](https://user-images.githubusercontent.com/3807253/84870692-e951aa80-b07f-11ea-8a41-837a6eebdc46.png)

**Comment by tgodzik** [comment]
Looks like this issue: https://github.com/lihaoyi/PPrint/issues/33

Though, does ammonite use pprint underneath? Somebody reported this issue in pprint with an ammonite snippet :thinking:

**Comment by ckipp01** [comment]
> Looks like this issue: [lihaoyi/PPrint#33](https://github.com/lihaoyi/PPrint/issues/33)

Ah, of course, I didn't think about this being an issue with pprint.

> Though, does ammonite use pprint underneath? Somebody reported this issue in pprint with an ammonite snippet 🤔

I don't _think_ so, because when you run it with Ammonite shell, everything seems to go ok.

```
❯ amm
Loading...
Welcome to the Ammonite Repl 2.1.4 (Scala 2.13.2 Java 1.8.0_242)
@ val test = <rss></rss>
test: xml.Elem = <rss></rss>
```

**Comment by tgodzik** [comment]
I wanted to test it out myself and I was "Pity I don't have ammonite installed... wait a moment..."
`cs install ammonite`
`amm`

:smile: 

I tried out the second option:
`val x = <?xml-stylesheet href="style.xsl"?> ` and that has the same issue. Anyway I reported it in pprint just in case.

**Comment by tgodzik** [comment]
Closing this issue in favour of the pprint one.
