### ISSUE TITLE
False positive for automatic completion suggestions

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1845]
**Describe the bug**

Metals auto-completes a suggestion that compiles successfully but has buggy runtime semantics.

**To Reproduce**

Currently, when completing in this case where Metals autocompletes `processFile(isResourceFile = isLargeBanana)`. 

```scala
val isLargeBanana = true

def processFile(isResourceFile: Boolean): Unit = ()

processFile(isResourceFil@@)
```
The `isLargeBanana` variable is unrelated to `isResourceFile` even if it has the same type `Boolean`. I don't think Metals should try to guess on my behalf and insert `isLargeBanana` directly.

**Expected behavior**

I expect Metals to complete only `isResourceFile = `. It should at least provide two different alternatives with one alternative that doesn't auto-fill the name.

**Screenshots**

In this particular example, I was gonna type manually `true`.

<img width="519" alt="Screenshot 2020-06-19 at 17 27 44" src="https://user-images.githubusercontent.com/1408093/85150698-291cbb80-b253-11ea-806b-2aa2a6b6b438.png">

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
:thinking: This looks super weird. We always add the empty arg as the first completion:

```scala
      params.map(param =>
        new NamedArgMember(param)
      ) ::: findPossibleDefaults() ::: fillAllFields()
```

And I can't seem to reproduce:

![image](https://user-images.githubusercontent.com/3807253/85154972-72233e80-b258-11ea-97b7-1a97c9837aef.png)

Any idea why the default is not included? Does it happen for you on the smaller example?

**Comment by olafurpg** [comment]
I made several failed attempts to minimize the example.

I'm still able to consistently reproduce it in the large codebase, the exact line of code is here https://github.com/scalameta/fastpass/commit/f689ce2a442a5b3ed0510a1f16a7040b7bce17cb

I looked at the LSP trace logs to confirm that Metals is returning only one completions (it's not filtered out by VS Code)

```json
[Trace - 10:47:53 AM] Received request 'textDocument/completion - (13300)'
Params: {
  "context": {
    "triggerKind": 1
  },
  "textDocument": {
    "uri": "file:///Users/lgeirsson/dev/fastpass/fastpass/src/main/scala/scala/meta/internal/fastpass/pantsbuild/BloopPants.scala"
  },
  "position": {
    "line": 491,
    "character": 22
  }
}


[Trace - 10:47:53 AM] Sending response 'textDocument/completion - (13300)'. Processing request took 26ms
Result: {
  "isIncomplete": false,
  "items": [
    {
      "label": "isResourceIncluded \u003d isLarge",
      "kind": 12,
      "detail": " : Boolean",
      "preselect": true,
      "sortText": "00000",
      "filterText": "isResourceIncluded",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 491,
            "character": 10
          },
          "end": {
            "line": 491,
            "character": 22
          }
        },
        "newText": "isResourceIncluded \u003d isLarge"
      },
      "data": {
        "symbol": "local44",
        "target": "file:/Users/lgeirsson/dev/fastpass/fastpass/?id\u003dfastpass"
      }
    }
  ]
}
```

**Comment by tgodzik** [comment]
Ok, I managed to find a reproduction:
```
object Utils {
  hello(st@@)
  def hello(str : String) = ""
} 
```

it seems str is treated as a local forward reference.
