### ISSUE TITLE
Scala Metals doesn't work on VSCode Remote WSL

### ISSUE THREAD

**Issue by anu-srivastava** [scalameta/metals#1848]
**Describe the bug**
Scala Metals throw the following error when I launch VSCode on WSL2

**To Reproduce**
Launch VSCode Scala project and then reopen the window using WSL remote Ubuntu

**Expected behavior**
Scala Metal should be able to download and work

**Screenshots**
![image](https://user-images.githubusercontent.com/6879400/85187325-a21c1300-b253-11ea-90d9-333c1def46e9.png)

**Installation:**
- Operating system: Windows 10 with WSL2 Ubuntu 20.04
- Editor: Visual Studio Code
- Metals version: v1.9.0

**Additional context**
Metals works fine outside of WSL

**Search terms**
VSCode WSL failed to download Metals

**Comment by tgodzik** [comment]
Thanks for reporting! The problem is that your java home is pointing to outside of WSL, which Metals running inside it cannot access. You need to have a separate java executable for WSL. Could you try removing the setting altogether? Metals should offer to install java again then. Alternatively, you can install java inside WSL and point the java home setting to that.

**Comment by anu-srivastava** [comment]
Thanks @tgodzik that worked like charm!

**Comment by worace** [comment]
In case it helps anyone else, I had installed java within the WSL Ubuntu environment using Coursier ([instructions](https://get-coursier.io/docs/cli-java)), which puts your Java dir in coursier's cache directory. You can get this path by running:

```
cs java-home                                                                                                                                                                                                /home/your-user/.cache/coursier/jvm/adopt@1.8.0-275
```

Which is the path you should put in the "Metals: Java Home" setting.
