### ISSUE TITLE
Incorrect import in Ammonite script not detected

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1852]
**Describe the bug**
If you import something in an Ammonite script that doesn't exist, the script still compiles and no error is shown to the user.

**To Reproduce**
1. Open an Ammonite script
2. Add a couple fake imports
3. Save
4. Don't see any errors.

For example, given a simple script with the following imports:

```scala
import $file.iDontExist, iDontExist._

import java.what
```

I would expect that both of these error and produce diagnostics that both `iDontExist` doesn't exist and also that `what` is not part of `java`. 

**Installation:**
- Operating system: macOS
- Editor: Vim
- Metals version: Latest snapshot

**Search terms**
Ammonite, scripts, incorrect imports

**Comment by tgodzik** [comment]
Thanks for reporting, it seems that we are not getting any compile errors from ammonite. @alexarchambault Do you know what could cause that?

**Comment by tgodzik** [comment]
Additional problem here seems to be that with bad imports the script might never be imported and no information is displayed.

**Comment by ckipp01** [comment]
It looks like this was fixed here: https://github.com/lihaoyi/Ammonite/pull/1110

@alexarchambault any idea on when to expect a new release on the Ammonite side?

**Comment by alexarchambault** [comment]
@ckipp01 It should already be available in Ammonite `2.2.0-4-4bd225e`, no need to wait for a stable release.

**Comment by ckipp01** [comment]
> 2.2.0-4-4bd225e

Ah cool, I didn't realize. I take a peak at it there. Thanks!
