### ISSUE TITLE
Ammonite file members completions not working

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#1854]
In example:

```scala
main.sc:
import $file.Imp

Imp.<try completion here>

Imp.sc:
object ImpInst {
  val secret = "123"
}
```

should it show `ImpInst` as completion option, it is not happening right now?
Trying `Imp.ImpInst.<try completion here>` doesn't propose `secret` either.
`Imp.ImpInst.secret` <- evaluates correctly with `amm main.sc`

---

I think `.ammonite` could be added to documentation `.gitignore`

---

Creating ammonite script in one of sources directories ends up with e.g. `package scala.meta.metals` but packages are invalid in ammonite scripts(at least throws error for me running amm). It is a little weird because we don't have logic for that in metals? 

---

I just gave ammonite a try, I don't know what is 'work as expected' and what and what we simply don't support that's why it is more of a question style than issue report.

If you confirm something from a list I can move those things to separate issues / feature requests.

**Comment by tgodzik** [comment]
> should it show ImpInst as completion option, it is not happening right now?
Trying Imp.ImpInst.<try completion here> doesn't propose secret either.
Imp.ImpInst.secret <- evaluates correctly with amm main.sc

This should work, though I've seen some situations that this was not happening. Most likely the PC is not restarted at the right time.

> I think .ammonite could be added to documentation .gitignore

We could do that, yeah.

> Creating ammonite script in one of sources directories ends up with e.g. package scala.meta.metals but packages are invalid in ammonite scripts(at least throws error for me running amm). It is a little weird because we don't have logic for that in metals?

We can check the extension, but overall it's not expected that people create ammonite scripts inside their source dirs.

**Comment by tgodzik** [comment]
It does seem that searching for members inside files is a bit broken right now. I am not 100% sure why. @alexarchambault did something like this work previously? 

```
import $file.Other

Other.<completions do not pop up>
```

**Comment by tgodzik** [comment]
This was fixed recently in https://github.com/scalameta/metals/pull/2974 :tada:
