### ISSUE TITLE
Errors for java dependency files false positive

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#1855]
When jumping to a definition in java dependency library we end up with a lot of diagnostic errors for those files which we don't really care about

![2020-06-25-180737_536x206_scrot](https://user-images.githubusercontent.com/10478402/85756159-da699880-b70e-11ea-9e80-b4ceac762f2f.png)

We could potentially filter out all diagnostics for `.metals/readonly/...` ?

Is there a workaround to get rid of those errors when this situation happens right now?

I always judge if my project is compiled by a number of errors but in this case it is hard impossible to tell immediately.

**Comment by olafurpg** [comment]
@kpbochenek thank you for reporting! Do you have the Java language server installed?

**Comment by kpbochenek** [comment]
Yes! Thanks for pointing it out! Error is probably reported from `java language server` and there is nothing we can do about it :/

I will double check and if that is the case will close this issue.

**Comment by kpbochenek** [comment]
Yes they were all coming from java extension, sorry for confusion :(
