### ISSUE TITLE
Don't suggest `case class` inside partial function when doing a case statement

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1862]
**Describe the bug**
When attempting to write a case statement inside of a partial function the only completion suggest that comes from the server is `case class`. I don't think this should happen here, but I'm not sure how hard it would be to detect this. Below I have a snippet with the completion position marked with `@@`.

```scala
val myPartialFunction: PartialFunction[Int, Int] = {
	cas@@
}
```

**To Reproduce**
1. Copy the above code
2. Start typing out the case statement
3. See the `case class` completion given

**Expected behavior**
Probably just not offer any completion here?

**Installation:**
- Operating system: macOS
- Editor: Vim
- Metals version: Latest snapshot

**Search terms**
completions, partial function

**Comment by gabro** [comment]
I’m currently from my phone so I can’t verify this, but isn’t something like this legal?

```scala
val myPf: PartialFunction[Int, Int] = {
   case class A(n: Int)
   { case _ => 42 }
}
```

I know it’s contrived but I wonder if suggesting case class there is _technically_ legal or not.

(It may still make sense to avoid suggesting the keyword in that position since it’s very unlikely you wanted to write a case class in that position, but I don’t remember how hard it would be to filter it out. IIRC the keywords are suggested based on syntax, but I may be wrong)

**Comment by ckipp01** [comment]
> I’m currently from my phone so I can’t verify this, but isn’t something like this legal?
> 
> ```scala
> val myPf: PartialFunction[Int, Int] = {
>    case class A(n: Int)
>    { case _ => 42 }
> }
> ```

So that example doesn't seem to work, but as for as legality goes, I'm really not sure.

> It may still make sense to avoid suggesting the keyword in that position since it’s very unlikely you wanted to write a case class in that position

Yea, I agree with this.

**Comment by kubukoz** [comment]
I was able to get that to compile and run 😅 

```scala
object Examples extends App {

  val myPf: PartialFunction[Int, Int] = {
    case class A(n: Int)

    { case _ => 0 }
  }

  println(myPf(0))
}
```

**Comment by ckipp01** [comment]
> I was able to get that to compile and run 😅
> 
> ```scala
> object Examples extends App {
> 
>   val myPf: PartialFunction[Int, Int] = {
>     case class A(n: Int)
> 
>     { case _ => 0 }
>   }
> 
>   println(myPf(0))
> }
> ```

Wait... haha, I didn't add in the empty line..., then in compiles fine 😬

**Comment by tgodzik** [comment]
Should we close it as working as expected then?

**Comment by ckipp01** [comment]
> Should we close it as working as expected then?

I personally sort of agree with what @gabro said above:

> (It may still make sense to avoid suggesting the keyword in that position since it’s very unlikely you wanted to write a case class in that position, but I don’t remember how hard it would be to filter it out. IIRC the keywords are suggested based on syntax, but I may be wrong)

Depending on how hard it would be, I think it may be better to not offer this suggest here.

**Comment by kubukoz** [comment]
Personally I don't mind having the word suggested there - it's a valid position and maybe the language server shouldn't go the territory of "what's likely or not". As a new user I would probably have preferred if the IDE suggested all possible options, much like a parser with good error reporting would.

**Comment by ckipp01** [comment]
It's not something I feel strongly about, so if people think it's good to leave as is, then I'm fine with closing.

**Comment by tgodzik** [comment]
I don't think we should remove that option, but it might be useful to improve the support the support for partial functions in particular. So maybe we can move it to feature requests to add a similar support here as for the `match` expressions?

**Comment by ckipp01** [comment]
I'll go ahead and close this.
