### ISSUE TITLE
Document new metals-model-refresh argument

### ISSUE THREAD

**Issue by kurnevsky** [scalameta/metals#1863]
It was added in https://github.com/scalameta/metals/commit/a821715e949ca87e48cc5b41fe70815789eae405 but docs specify no arguments: https://github.com/scalameta/metals/blob/bb8420ade90cf32eb12038d4e0d0e0bf604883fc/metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala#L100-L106

It's not very clear what it's used for and we got bug reported in https://github.com/emacs-lsp/lsp-metals/pull/12

Also probably we should notify other clients about this change.

cc @tgodzik

**Comment by kpbochenek** [comment]
Thanks for catching it!

I think this parameter should not be leaked to outside world in a client command as it is added to only make tests work correctly.

For now I would say you should simply ignore this parameter and I will try to see if we should revert back to have this command parameter-less.

Most clients/json parsers simply ignore additional parameters, it is much easier to keep backward compatibility in that case(but also as in this case might miss some problems)

**Comment by kurnevsky** [comment]
We can easily ignore it but I'd not ignore them by default because this usually means that something has changed with a command and we should handle it differently and make use of this new parameter.

**Comment by kpbochenek** [comment]
will do my best :crossed_fingers:
