### ISSUE TITLE
Foreign mill modules aren't recognized in bloop

### ISSUE THREAD

**Issue by kag0** [scalameta/metals#1886]
From https://github.com/lihaoyi/mill/issues/876, this might be a better place for the issue.

Creating a build like 

```scala
// ./build.sc
import mill._, scalalib._
import $file.bar.build
object foo extends ScalaModule {
    def scalaVersion = "2.13.1"
    def moduleDeps = Seq(bar.build.bar, baz)
}
object baz extends ScalaModule {
    def scalaVersion = "2.13.1"
}

// ./bar/build.sc
import mill._, scalalib._
object bar extends ScalaModule {
    def scalaVersion = "2.13.1"
}
```

Causes warnings in bloop 
> Missing projects 'bar', may cause compilation issues in project 'foo'

and indeed, metals has issues with highlighting although compiling from mill directly works OK.

Tested on linux with mill 0.6.3, VS Code, and metals 0.9.1

**Expected behavior**
Editor recognizes imports from foreign modules.

**Comment by kpbochenek** [comment]
Metals executes command in sbt/mill/(other supported build tool) to export projects configuration.
Based on this bloop is doing compilation and Metals uses semanticdb generated by bloop to provide all functionality.

Maybe export of configuration performed by mill is not correct in this situation?

**Comment by ckipp01** [comment]
I looked into this a bit today and it indeed does look like this is an issue in the contrib module since with this exact setup, there is no `.bloop/bar.json` being created. As you would expect, in the `.bloop/foo.json` there is actually information that is supposed to be linking them. You can see this in the `classpath` key:

```json
        "classpath": [
            "/Users/ckipp/Documents/scala-workspace/mill-test/.bloop/out/bar/classes",
            "/Users/ckipp/Documents/scala-workspace/mill-test/.bloop/out/baz/classes",
            "/Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar"
        ],
```
However, when you look in `.bloo/out`, there is bar classes. I'm sort of in favor of closing this here, since this fix will need for happen in the contrib moduel if I understand the issue correctly.

**Comment by tgodzik** [comment]
I agree with @ckipp01 - without Bloop configuration for `bar` we are unable to compile it, hence Metals will not work properly. It would be best if `bloopInstall` was also run for the foreign module and put into `.bloop` config inside the main workspace. We could also work on some changes inside Bloop to support additional `.bloop` directory that we could generate ourselves by searching for `build.sc` inside the workspace and start multiple Bloop connections, but it would be less complicated to support the feature inside Mill itself. Especially that we will not have time in the near future to work on fixing this in Metals.

Alternatively, you could use the Mill BSP server, but that doesn't offer the same amount of features as Bloop does. However, if you added semanticdb plugin and -Yrangepos it should work almost as well.

**Comment by tgodzik** [comment]
Most likely this should be fixed on the Mill side, so closing the issue here. Feel free to reach out to us if you feel we can do something on the Metals side.
