### ISSUE TITLE
Show user 'import build popup' status and allow reenabling it

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#1887]
If import build popup is disabled display it in metals doctor(with date when it will be enabled or that it is disabled forever) - similar to multiple builds choice.

Add mechanism to reenable 'import build popup' (metals command or Build Commands action or both) - just remove entry in db for this notification.

**Comment by ckipp01** [comment]
I was thinking about this a bit today. What do you think of the following:

1. We have the information displayed in the doctor what choice was made. Maybe in another table? Something like

Metals Doctor
-------------
These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

      buildTarget      |    scalaVersion    |     diagnostics    |   gotoDefinition   |     completions    |   findReferences   |   recommendation  
------------------------------------------------------------------------------------------------------------------------------------------------------
       root-test       |       2.12.11      |         ✅         |         ✅         |         ✅         |         ✅         |                
         root          |       2.12.11      |         ✅         |         ✅         |         ✅         |         ✅         |                


The are the following choices that have been made and stored

prompt        | choices made
--------------|-------------
buildTool     | sbt
import build  | Don't show again

Then we could maybe have a `metals.resetPrompt` command that could take an optional parameter of a prompt so you could send in `metals.resetPrompt buildTool` which will reset that decision. Or, you don't send anything in, and then is sends you the prompts. So in this case it would send like:

Which topic would you like to reset?:
1. buildTool
2. import build

The reason I suggest this route is that it could be done all through the LSP spec basically using a combination of Doctor and `showMessageRequest`. What do you think?

**Comment by kpbochenek** [comment]
This sounds like a good generic mechanism. ResetPrompt with optional notification choice is a way to go.

A table is good for showing choices and actions to reset them but I think it is also good to have description like that:

"You imported you build using sbt configuration in build.sbt . Would you like to use other build tool? (<reset link>)"
"Changes to your build configuration won't show re-import popup. Would you like to enable automatic re-import popup? (<enable>)"

To be more in interaction with user, but that in a sense duplicates information and might be confusing.

**Comment by ckipp01** [comment]
> "You imported you build using sbt configuration from build.sbt . Would you like to use other build tool? (< reset link >)"

So are you envisioning this reset link actually being displayed in Doctor?

**Comment by kpbochenek** [comment]
![2020-07-06-214248_837x239_scrot](https://user-images.githubusercontent.com/10478402/86633993-a4ab9600-bfd1-11ea-9966-b986aa171dd1.png)

**Comment by ckipp01** [comment]
So my main reason for not showing it this way is that it gets a bit hairy for clients that aren't getting the html. For example, in coc-metals I just get the JSON, and parse the text and display it in a temp buffer to the user. So having a link attached to that becomes much more difficult. What are your thoughts on how this would work for a client getting the json returned?

**Comment by kpbochenek** [comment]
This would be done for clients supporting html. For clients working with JSON they would only see current state and would have to as you said execute dedicated command to reset this.

**Comment by ckipp01** [comment]
> This would be done for clients supporting html. For clients working with JSON they would only see current state and would have to as you said execute dedicated command to reset this.

Gotcha. That makes sense 👍

**Comment by kpbochenek** [comment]
Implemented in https://github.com/scalameta/metals/pull/1897
