### ISSUE TITLE
Not all giter8 templates are showing up in New Scala Project 

### ISSUE THREAD

**Issue by justinhj** [scalameta/metals#1889]
**Describe the bug**
Was trying out the new Scala Project command in VS Code. One of the giter8 templates on the wiki page does not seem to in the drop down list. Others may be missing, but this is the only one I found so far.

**To Reproduce**
In VS Code's command palette chose Metals: New Scala Project
scroll down to the bottom and choose Discover More
type fp-starter-pack in the search

**Expected behavior**
justinhj/fp-starter-pack.g8 is included on the wiki page at https://github.com/foundweekends/giter8/wiki/giter8-templates
but does not appear in the search. You can use the template by typing it manually.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.1

**Additional context**

**Search terms**
New Scala Project

**Comment by kpbochenek** [comment]
Good catch!

![2020-07-03-113035_555x227_scrot](https://user-images.githubusercontent.com/10478402/86455277-a864c180-bd20-11ea-9c68-8909fc1bb968.png)

That's because we match with regex and expect description in parenthesis after a link and in this particular case there is no description.

**Comment by kpbochenek** [comment]
Okay I updated a template to have description, it should show now in a list.

We cannot simply change regex to treat `(description)` as optional because that would include all links on this page not only g8 templates.
Maybe check if suffix is `g8` would be good enough?

**Comment by justinhj** [comment]
Many thanks! I thought it was something like that, I should have investigated more but it was a bit late here.

**Comment by tgodzik** [comment]
We should fix the regex to cover more cases, it should be simple enough.
