### ISSUE TITLE
evaluate expression

### ISSUE THREAD

**Issue by franziskakuehn** [scalameta/metals#1904]
**Question**

1. question:
In debug mode with Scala Metal by setting up a launch.json I get 'an implementation is missing' by evaluating expression in debug console panel and by adding watch variables.

**Screenshots**
![image](https://user-images.githubusercontent.com/64410388/87290216-ff774d00-c4fd-11ea-84fc-0c39e120c1cf.png)

2. question:
Databricks is recommending setting the breakpoint options to Thread and not to All in IDEA to avoid network timeouts , is there a similar possibility in debug mode with scala metal in vsc?
By using databricks-connect (https://docs.databricks.com/dev-tools/databricks-connect.html#:~:text=%20Databricks%20Connect%20%201%20Overview.%20Databricks%20Connect,workspace%20URL.%20User%20token%3A%20A%20personal...%20More%20)

I really would like to proceed using vsc with scala metal, everything is working much more memory efficient.

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v1.9.1
- scala 2.11 and java 8 due to databricks-connect restrictions
**Additional context**

Working with databricks-connect 

**Search terms**

Scala Metal Debug Evaluate expressions

**Comment by tgodzik** [comment]
Thanks for reporting! Expression evaluation endpoint is currently not supported. There is a feature request in Metals: https://github.com/scalameta/metals-feature-requests/issues/83

**Comment by franziskakuehn** [comment]
I see, thx, was convinced I checked all issues:)

Is there an ETA? Its major imho.

**Comment by tgodzik** [comment]
No ETA currently. I would love to take a look, but I can't promise any particular timeline.

**Comment by franziskakuehn** [comment]
Ok, thank you.
