### ISSUE TITLE
Metals seem to don't work on Mint 20 with VSC

### ISSUE THREAD

**Issue by stepaniukm** [scalameta/metals#1909]
**Describe the bug**
I've recently installed update to Linux Mint 20 and Metals doesn't work there with VSC. Options like `import build` disappeared from menu. The most importantly I don't receive any code suggestions so it's frustrating to develop an app.

**Screenshots**
https://imgur.com/ARQ1Pcz
https://imgur.com/a/78NPd9H

**Installation:**
- Operating system: Linux Mint 20
- Editor: Visual Studio Code
- Metals version: v0.9.1

**Additional context**
VSC version: 1.47
Scala version: 2.13.3
sbt version: 1.3.13
JDK version: 14.0.1

**Comment by kpbochenek** [comment]
JDK 14 is not supported, we only support 8 and 11

**Comment by stepaniukm** [comment]
You mean as of version 0.9.1? I downgraded to 0.9 and it works

**Comment by kpbochenek** [comment]
We are not officially supporting JDK 14 and not testing against it -> It might be related to that or it might actually be something else.

Could you tell me what VSCode metals extension version do you have? (e.g. 1.9.1 for me)
![2020-07-13-221803_681x85_scrot](https://user-images.githubusercontent.com/10478402/87349642-ed75c880-c556-11ea-9ee2-6b528e6d3436.png)

Could you remove `.bloop` `.metals` inside your workspace and try opening a project again? Do you have any errors in `.metals/metals.log`?

Is it possible to install JDK11 and try if it fixes your issue with v0.9.1?

**Comment by stepaniukm** [comment]
Yeah, of course in VSC I had issues with version 1.9.1 and with 1.9 works fine.
I had already removed `.metals` and `.bloop` before I made this issue. No errors in `metals/metals.log`

Switching to JDK11 didn't change anything. Still, no Metals options, when using extension 1.9.1 and everything's fine on 1.9

**Comment by tgodzik** [comment]
Thanks for reporting! Do you see maybe any issues in the Output (metals) or in the extension host logs? It looks like the extension or the server itself is not starting. There should be a trace of it somewhere 🤔

**Comment by stepaniukm** [comment]
Okay, sorry for messing up a bit, but now I'm confused as after a little back and forth with installing versions of extension and JDK it "clicked" with setup: JDK11 and metals-vscode 1.9.1 and I have no idea why what was the issue previously with exact same setup and after rebooting.

**Comment by kpbochenek** [comment]
I will close this issue now, glad everything worked out in the end :)

btw. keep in mind there is a version of vscode-metals extension and metals itself.
vscode-metals latest version is 1.9.1
metals latest version is 0.9.1

Next time if you find any problems please attach both versions to firstly rule out any version incompatibilities.
