### ISSUE TITLE
Installing metals with a private corporate repository 

### ISSUE THREAD

**Issue by rynoterblanche** [scalameta/metals#1931]
**Question**

Can coursier bootstrap install from a private repository if URL authentication is not allowed on that repo?

I can successfully setup a .jvmopts file in my workspace with a path to my mirrors and I can see that the mirrors are being used. However it seems my credentials file is being ignored since my private repo returns a 401 HTTP unauthorised.

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v1.9.1

**Additional context**

My .jvmopts file looks like this:
```
-Dcoursier.mirrors=C:\\rt\\coursier\\mirror.properties
-Dcoursier.credentials=nexus.rt.org username:password
```

My mirror.properties file looks like this;
```
central.from=https://repo1.maven.org/maven2
central.to=https://nexus.rt.org:8081/nexus/content/groups/prd
ivy2Local.from=https://repo.typesafe.com/typesafe/ivy-releases
ivy2Local.to=https://nexus.rt.org:8081/nexus/content/groups/prd
```
I've also tried a credentials.properties file that looked like this:
```
nexus.username=username
nexus.password=password
nexus.host=nexus.rt.org
```
for this file I adjusted jvmopts as follows: `-Dcoursier.credentials=file:\\\C:\\rt\\coursier\\credentials.properties`

I wondered if my credentials were ignored during redirection so I also updated my credentials file by adding: `nexus.pass-on-redirect=true`

Thanks!

**Comment by tgodzik** [comment]
Thanks for reporting!

I haven't much experimented with mirrors and credentials, the only help I can offer is the coursier website https://get-coursier.io/docs/other-credentials which I guess you already checked.

Have you maybe tried some alternative approaches like:
- putting the credential file into the default location
- using the environment variable `COURSIER_CREDENTIALS`
- maybe using the non-mirrored host or no host at all? Could be a bug.
?

We haven't had much chance to test out proxy integration unfortunately, so it would be awesome to make it work in your case and document that.

@alexarchambault do you know if mirror should work with credentials?

**Comment by tgodzik** [comment]
@rynoterblanche Were you able to solve the issue? You might be able to ask in a coursier or sbt channel. It might be an issue that someone there encountered.

**Comment by rynoterblanche** [comment]
@tgodzik thanks for checking back on this

Unfortunately I was not able to find why my credentials are not forwarded correctly to my configured coursier mirror.

As a workaround I wrote a small coursier API wrapper that is configured to use my repo / creds and that fetches and pre-caches all the dependencies for coursier & metals (I do all this as part of a dockerfile that builds a vs code devcontainer with the Scala Metals extension and so far the dev container is working well for me barring some issues with the bloop server)

**Comment by tgodzik** [comment]
Did you open an issue in coursier? Would be good to do it, since it seems like a problem that could be effecting more people.

**Comment by tgodzik** [comment]
I will close the issue here, let me know if there is anything we will need to do on our side!

**Comment by rugobal** [comment]
Is there any solution to this? I have the same problem. I'm not able to set the courier.credentials property/variable

**Comment by tgodzik** [comment]
What kind of error do you get? Would you be willing to open a new issue with as much as data possible?

**Comment by rugobal** [comment]
Hi,

I was able to make it work eventually by using thet COURSIER_CREDENTIALS
env variable.

Thanks,
Ruben
