### ISSUE TITLE
Is there another way to install or configure metals without using the powershell?

### ISSUE THREAD

**Issue by mrlujanero** [scalameta/metals#1932]
Hi!

As the title says "Is there another way to install or configure metals without using the powershell?". I've installed this extension in all my laptops and worked fine. However, my job laptop has the poweshell blocked by policy, and each time I try to open a Scala project it shows the following error:

**Screenshots**

![image](https://user-images.githubusercontent.com/13558391/87800829-2fe91f00-c84f-11ea-89db-7ae579e8d791.png)

Is there a way to fix it or to not use powershell?

Many thanks in advance.

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v1.9.2

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! It looks like coursier bootstrap that we are using to download Metals server is using powershell itself. 

I found a possible answer here: https://github.com/coursier/coursier/issues/1387

It looks like you should be able to add `-Dcoursier.cache=C:\Users\username\AppData\Roaming\Coursier`  and that would not run powershell from what I understand. Could you try it out?

**Comment by alexarchambault** [comment]
Not sure, but `-Dcoursier.config-dir=C:\Users\username\AppData\Roaming\Coursier`, and maybe also `-Dcoursier.data-dir=C:\Users\username\AppData\Roaming\Coursier`, might be needed to.

**Comment by mrlujanero** [comment]
Hi guys!

Many thaks for your answers. I've tried both and it seemed they worked, since it downloaded all the dependencies in those folders. However, it still fails on starting the metals server. It says that has tried to start five times, and if I check the log file says cannot run program "powershell.exe" :s.

Regards,
Ramon.

**Comment by tgodzik** [comment]
Did you add all 3? `-Dcoursier.cache`, `-Dcoursier.config-dir` and `-Dcoursier.data-dir` ? I wonder if powershell is also used by `spawn` :thinking:

**Comment by mrlujanero** [comment]
Yes, and also tried with spawn:

![image](https://user-images.githubusercontent.com/13558391/87928706-8a6bc080-ca85-11ea-89e2-04311b03cbba.png)

**Comment by tgodzik** [comment]
I am a bit at a loss here then. Would it be possible for your infrastructure team to enable powershell? It is a standard Windows tool, so there should not be any real risk here.

**Comment by tgodzik** [comment]
>  It says that has tried to start five times, and if I check the log file says cannot run program "powershell.exe" :s.

Coming think about this, it actually looks like it's VS Code trying to run powershell. We supply LanguageClient class with server options to run and it seems it uses powershell underneath (that's what says it started 5 times). I think it uses this library https://nodejs.org/api/child_process.html#child_process_default_windows_shell
Maybe you could specify COM_SPEC variable to use `cmd.exe`? 

Anyway, I don't think it's a Metals issue and since you are able to download the dependencies it doesn't seem to be coursier issue either. We can reopen the issue if it turns out there is something we should do in Metals itself.
