### ISSUE TITLE
Rename for local symbol of a parameter name doesn't work

### ISSUE THREAD

**Issue by jvican** [scalameta/metals#194]
When I try to rename `expectedHtml` to `expected` in:
  
```scala
def checkPandoc(name: String, original: String, expectedHtml: String): Unit = {
  // use of all the parameters
}
```
  
I get:
  
```
Rename for global symbol _root_.vork.markdown.BaseMarkdownSuite#checkPandoc(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V.(expectedHtml) is not supported yet. Only local symbols can be renamed.
```
  
I expect this to succeed since it's a local symbol.

**Comment by laughedelic** [comment]
I suspect the reason for it that you could use this name in some other files when calling `checkPandoc` with named args. So the concern is the same as with global symbols.

**Comment by gabro** [comment]
I hit on the same issue yesterday, I think @laughedelic's explanation makes sense: if you take named parameters into account the symbol is not local.

**Comment by olafurpg** [comment]
Correct, you can reference the parameter symbol from external files as a named argument `checkPandoc(expectedHtml = ...)`. This is working as expected.

Implementing rename for global symbols should be totally doable, we are simply being extra conservative to avoid incorrect renames.
