### ISSUE TITLE
`metals.enableStripMarginOnTypeFormatting` not being taken into account

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1943]
**Describe the bug**
When a user turns on `metals.enableStripMarginOnTypeFormatting`, and they hit enter at the following position:
```scala
val test = """|@@"""
```
This will add the pipe and the `.stripMargin` even though the setting is set to false via User Configuration.

**To Reproduce**
1. Create the above code snippet
2. Ensure `metals.enableStripMarginOnTypeFormatting` is set to false
2. Hit return at `@@`
3. See that `.stripMargin` is added

**Expected behavior**
I would expect `.stripMargin` not to be added when this setting is turned off.

**Installation:**
- Operating system: macOS
- Editor: Vim
- Metals version: v0.9.2

**Search terms**
onTypeFormatting, stripMargin, multiline string

**Comment by tgodzik** [comment]
Thanks for reporting! Just checked and I can confirm. Maybe I could fix this during the livestream tomorrow :thinking:

**Comment by ckipp01** [comment]
> Thanks for reporting! Just checked and I can confirm. Maybe I could fix this during the livestream tomorrow 🤔

That's a good idea! It should be small enough one to possibly get done as well in not too much time.
