### ISSUE TITLE
Docs missing `compile-clean` command

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/metals#1969]
**Describe the bug**
[Documentation](https://scalameta.org/metals/docs/editors/new-editor.html#metals-server-commands) misses `compile-clean` command description.

**To Reproduce**
1. Decide to do full re-compilation of a Metals project
2. Go to https://scalameta.org/metals/docs/editors/new-editor.html#metals-server-commands
3. Try to find a command for your task
4. Only `compile-cascade` matches, but it's not what you want

**Expected behavior**
To have `compile-clean` documented.

**Installation:**
- Operating system: Linux
- Editor: Vim
- Metals version: v0.9.2

**Comment by kpbochenek** [comment]
Thanks for reporting!

It is a matter of adding `CleanCompile` in `ServerCommands.scala` to this list 
```
def all: List[Command] =
    List(
      ImportBuild,
      ...
      ```

**Comment by kpbochenek** [comment]
docs were updated and it is now visible on website
