### ISSUE TITLE
Parameter names hints

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#197]
Inspired by https://twitter.com/kot_2010/status/966212862711615490

This is not a feature covered by LSP, but since we should have the information necessary to pull this off, it's probably worth it.

## Server side
The idea is to implement a custom server-to-client notification (similar to `textDocument/publishDiagnostics`) which publishes updated hints whenever they become available from a freshly indexed semanticdb.
We could name this notification `textDocument/publishParameterNamesHints`.

Such notification would be sent only for the currently open buffers.

A `ParameterNameHint` can be something like

```
case class ParameterNameHint(pos: Position, name: String)
```

which is all that is required for a client to draw it.

## Client side
On the client, it depends on the specific capabilities. I have experimented with the text decoration API of VSCode and I've reached a satisfactory result.

![](http://g.recordit.co/WC1dB6tU4i.gif)

The feature can be a bit strange while typing, so it's probably more useful as something to toggle on on demand. The client should have a command (and possibly a keybinding) that can display or ignore the hints coming from the server.

**Comment by olafurpg** [comment]
I think this is a cool idea worth investigating. Let's close this ticket however to keep the issue tracker focused on the current priorities of the project. I've added the "revisit" label in case somebody is interesting in looking into this again.
