### ISSUE TITLE
VS Code icon showing for other editors in sbt file

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1973]
**Describe the bug**
I haven't been able to fully reproduce this consistently yet, but I'll keep trying. However, just to have it logged, when navigating around sbt files, hovering, etc. I saw this status multiple times while using coc-metals. It looks like somewhere we aren't checking for the correct icon, and instead showing what appears to be the vs code one?

```sh
[Trace - 09:14:54 PM] Sending notification 'metals/status'
Params: {
  "text": "$(info) Partial navigation",
  "tooltip": "This external library source has compile errors. To fix this problem, update your build settings to use the same compiler plugins and compiler settings as the external library.",
  "command": "metals-diagnostics-focus"
}
```

**Expected behavior**
I would expect to not see the `$(info)`.

**Installation:**
- Operating system: macOS
- Editor: Visual Vim
- Metals version: v0.9.2+73-4f1a1628-SNAPSHOT

**Search terms**
status, icon, sbt support

**Comment by tgodzik** [comment]
It seem to be inside `PartialNavigation`, we might need to go over Messages and see if there are any other such icons.

Not sure where does the error come from though.
