### ISSUE TITLE
Migrate codebase to 2.13

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1974]
Creating this to track it since one doesn't exist yet. I think it'd be a good idea to do a migration from 2.12 to 2.13 in the Metals code base. One of the current blocks that I see is that `bloop-launcher` is not cross compiled to 2.13. There is a ticket for it [here](https://github.com/scalacenter/bloop/issues/1295).

**Comment by tgodzik** [comment]
Done in https://github.com/scalameta/metals/pull/3631 :tada:

**Comment by kpodsiad** [comment]
Do we want `Migrate codebase to 3` ticket? ;)

**Comment by tgodzik** [comment]
Let's maybe hold off for a bit still 😅
