### ISSUE TITLE
Goto Definition not working as expected in sbt files.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1981]
**Describe the bug**
Executing a goto definition on a `SettingKey` doesn't seem to ever bring you to the right definition. The hover on a specific key works fine, but the definition always is off.

**To Reproduce**
1. Create a new `Hello World` project with the New Scala Project functionality
2. Open the `build.sbt` and do a `BuildImport`.
3. Execute a goto definition on any `SettingKey`

**Expected behavior**
I would expect this to go to the right `SettingKey` definition site.

**Screenshots**
Notice that all three times I attempt this, they are all wrong.

![2020-08-09 20 11 33](https://user-images.githubusercontent.com/13974112/89738917-abb83f00-da7c-11ea-89e9-8c78dcb44611.gif)

**Installation:**
- Operating system: macOS
- Editor: Vim
- Metals version: `0.9.2+81-63198fd6-SNAPSHOT`

**Search terms**
goto definitionn in sbt

**Comment by tgodzik** [comment]
Thanks for finding this! I think I know what is going on. I will be tidying up things this week for the release so I will fix this and the documentation issues.
