### ISSUE TITLE
Update docs about sbt support.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1983]
***Describe the Task***

Currently in the documentation we don't really have any information about sbt support. I know this isn't in a stable release yet, but we should make sure to add some information about it before that. I think there are a few _surprises_ people may have currently without some context. For example:

- What is supported and what is not (ex: completions, hover, goto definition supported)
- What else should be ignored now
 - This is relevant as I just had this happen to me where I sent in a pr, and realized I now had a `project/metals.sbt`, `project/project/metals.sbt`, and a `project/project/project/metals.sbt`. I didn't have the latter two ignored. Will these always be created? We should mention that they should be ignored as well.

**Comment by tgodzik** [comment]
> This is relevant as I just had this happen to me where I sent in a pr, and realized I now had a project/metals.sbt, project/project/metals.sbt, and a project/project/project/metals.sbt. I didn't have the latter two ignored. Will these always be created? We should mention that they should be ignored as well.

They need to be created to generate `.bloop` config for the meta builds. I will add docs for it, best would be to just ignore `metals.sbt`
