### ISSUE TITLE
Metals does not find semanticdb-target options for Scala 3

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#2003]
**Describe the bug**

In a Scala 3 project when the `semanticdb-target` option is set, Metals does not recognize it and it does not look for the semanticdb files in the right place.

**To Reproduce**

1. Create a Dotty project with sbt `1.4.0-M2`
2. Set `scalacOptions ++= Seq("-Ysemanticdb", "-semanticdb-target", "/home/adpi2/foo/target/meta")`
3. Start sbt
4. Open Metals

**Expected behavior**
When trying to navigate the code, Metals will print something like 
```
ERROR code navigation does not work for the file '/home/adpi2/foo/src/main/scala/foo/Main.scala' because the build target foo is missing the compiler option "-P:semanticdb:sourceroot:/home/adpi2/foo". To fix this problems, update the build settings to include this compiler option.
```
The expected behavior is that Metals extracts the semanticdb target folder from the compiler options and then it should be able to navigate the code.

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code

**Comment by tgodzik** [comment]
Thanks for reporting! `-semanticdb-target` is not enough. you should also include `-sourceroot` option pointing to the base of the directory.

The message is wrong though, since it doesn't take into account Scala 3 and we should fix that.

**Comment by adpi2** [comment]
In Scala 2.12 when you set `-P:semanticdb:targetroot` but not `-P:semanticdb:sourceroot` it works perfectly well. And so I assume it should be the case for Scala 3 as well:
 - Metals should be able to fallback to the default `sourceroot` when the option is not set
 - Metals should always be able to read the `sourcetarget` when it is set

**Comment by adpi2** [comment]
By the way I am currently trying a fix that I should be able to push in a few

**Comment by tgodzik** [comment]
> Metals should be able to fallback to the default sourceroot when the option is not set

It's not Metals, but the compiler. We do all the proper fallback in Bloop, but we can't do it inside Metals itself.
What Metals is showing is just diagnostic information, we are trying to figure out why the SemanticDB files are not produced by the compiler. The best guess here is that sourceroot is not defined.

**Comment by adpi2** [comment]
>  we are trying to figure out why the SemanticDB files are not produced

The compiler does not require the `sourceroot` and it should be the same for Metals. In the present case, the semanticdb files are produced by the compiler in the `targetroot` but Metals does not find them and so it tells that the semanticdb files are missing, which is not true.

I have a fix that is working. Metals extract the `targetroot` from the `scalacOptions` and then everything is working fine. As far as I can see, this is also how it works in Scala 2.

**Comment by tgodzik** [comment]
> > we are trying to figure out why the SemanticDB files are not produced
> 
> The compiler does not require the `sourceroot` and it should be the same for Metals. In the present case, the semanticdb files are produced by the compiler in the `targetroot` but Metals does not find them and so it tells that the semanticdb files are missing, which is not true.
> 
> I have a fix that is working. Metals extract the `targetroot` from the `scalacOptions` and then everything is working fine. As far as I can see, this is also how it works in Scala 2.

Ok cool, then the best guess was a really bat guess :sweat_smile:

**Comment by adpi2** [comment]
No worries! And, as always, thank you for your availability and reactivity! :1st_place_medal:
