### ISSUE TITLE
Use the project's Scala version

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#201]
Currently we use the Scala 2.12.4 presentation compiler, regardless of the version of the project. This makes PC-based features not work in projects with a different version of Scala (e.g. 2.11 and - in the near future - 2.13).

In order to support it we need to:

- include `scalaVersion` in `*.compilerconfig` files
- use `Jars.fetch` to get the classpath for scala-compiler with the correct scala-version

For a more detailed discussion see #200

**Comment by cquiroz** [comment]
Will this also make it work with TLS out of the box?

**Comment by gabro** [comment]
I assume you're talking about Typelevel Scala and not HTTPS (😛)

I think it would make it work as long as binaries are published, but I'm not sure of what's compatibility of semanticdb-scalac compiler plugin w.r.t. TLS.

I would expect completions to work, but diagnostics as-you-type may be still broken.

**Comment by olafurpg** [comment]
Until we figure out how to support 2.11 and 2.12 projects with the same server I opened #221 as a less ambitious solution, which is to report an error when the server encounters a 2.11 project.

**Comment by olafurpg** [comment]
In #337 we only use the PC if the scala version is 2.12 and report a helpful message when the user is on 2.11. Relevant test case https://github.com/scalameta/metals/blob/2ae2b6e37a63748e4d79058d604f44d6987ff2b1/tests/unit/src/test/scala/tests/DefinitionSlowSuite.scala#L234
