### ISSUE TITLE
Error when debugging a static method in a Java class

### ISSUE THREAD

**Issue by eugenwintersberger** [scalameta/metals#2011]
This problem shows up in Scala/Java mixed language projects. When entering a static method of a Java class no local variables are available to the debugger (at least not in VS Code) and the `metals.log` file shows the following error message

```
2020.08.19 22:09:40 ERROR [error response][variables]: an implementation is missing
```

In the case of VS Code the debugger window shows no local variables for the static method.

![image](https://user-images.githubusercontent.com/4303488/90684735-ff8b0b00-e268-11ea-99cf-92c92c19d1b9.png)

**Comment by tgodzik** [comment]
Thanks for reporting! I wonder if it's somehow connected to the expression evaluator, which is not implemented :thinking: 
Not sure how hard it will be to fix, but I will take a look at it before the next release.

**Comment by tgodzik** [comment]
After testing it, it seems I am not getting the same error. IS there any specific scenario that it's not working? Would you be able to create a small repro?

I tried:
```
public class Static{

    static int a = 123;
    static void hello(String greeting){
        System.out.println(greeting);
    }
}
```

Both breakpoints and variables are working.

**Comment by eugenwintersberger** [comment]
It seems to me that local variables in the static method cause the error. Something like this

```java
public class Static {

   static void hello(String greeting) {
      String message  = greeting + " from static class";
      System.out.println(message);
  }
}
```
in the debug view I would not see the `message` variable. Can you give this a try and if you cannot reproduce it I will try to provide a small repository reproducing this error.

**Comment by tgodzik** [comment]
I can confirm that the message variable is not available. Thanks!

This is a bit weird, because we are using the [java debug server](https://github.com/microsoft/java-debug), which I thought would have it all handled. We will need to dig in a bit.

**Comment by tgodzik** [comment]
This might be solved by https://github.com/scalameta/metals/pull/3003

**Comment by Arthurm1** [comment]
This works for me now on the latest Metals...

![image](https://user-images.githubusercontent.com/5612295/149325901-6c9973f8-6a4b-4c31-9dcf-3dfd7e9403ba.png)




But it doesn't work in the `Watch` section...

![image](https://user-images.githubusercontent.com/5612295/149325971-874ae997-8531-4c0e-88d2-1462144ac2cd.png)

**Comment by vishalovercome** [comment]
Exactly what I mentioned here - https://github.com/scalameta/metals-feature-requests/issues/194. Unfortunately Watch rarely ever works (my project is a mix of Java & Scala code)

**Comment by tgodzik** [comment]
Looks like it's trying to use Scala expression compiler for Java files, which is why this doesn't work.

I wonder if we can fall back to Java expression evalautor in this case. 

@vishalovercome did you have any issues in Scala files?

**Comment by tgodzik** [comment]
Tried to add this here: https://github.com/scalacenter/scala-debug-adapter/compare/main...tgodzik:add-java-expression-eval?expand=1

Turns out that for expression evaluator you need to be in an Eclipse project :/ Everything is super dependent on that. Anything really connected to JDT is problematic now.

**Comment by vishalovercome** [comment]
Pardon my ignorance, but can't a Scala project also be an Eclipse project? Isn't that what the sbt-eclipse plugin does?

**Comment by tgodzik** [comment]
I need to generate eclipse configuration first, which would weird for the users. We could probably work around it, but it's not a low hanging fruit which I hoped it is. This is the same problem as with interactive features for Java.

**Comment by adpi2** [comment]
> But it doesn't work in the Watch section...

"Variables" only evaluate `toString` while "Watch" treats the input as an expression and so it tries to compile it (which is not yet supported for Java). Maybe we should make an exception for expressions made of a single variable and not try to compile them at all.

**Comment by tgodzik** [comment]
Seems that the initial cause of this issue has been solved. Let us know if anything else pops up.
