### ISSUE TITLE
Make package exclusions customizable

### ISSUE THREAD

**Issue by dr0i** [scalameta/metals#2013]
**Problem**
Some libraries, although listed as included in metals in vscode, are excluded by `CompressedPackageIndex.scala` and thus cannot be referenced.

**Solution**
a) don't hardcode the exclusion of libraries
OR
b) "making this list configurable"

**Alternatives for the old behaviour**
instead of excluding libraries via `metals`' code, these exclusion should be made in the IDE.

**Additional context**
https://gitter.im/scalameta/metals?at=5f2807a061a831684634e3e2

**Search terms**:
library, libraries, packages, package, import,jdk,sun,javax,oracle,java/awt/desktop/,org/jcp,org/omg, org/graalvm, com/oracle, com/sun, com/apple,apple

**Comment by ckipp01** [comment]
After some initial conversation in #1977 I think we should approach this more in line with what you have listed as option B where this can be configurable by the client. I've started working on this so I've gone ahead and moved it into the main issue repo.

**Comment by ckipp01** [comment]
Closed with #2012
