### ISSUE TITLE
Metals unable to find Java 11 JDK

### ISSUE THREAD

**Issue by PawanKartikS** [scalameta/metals#2020]
I've just installed the metals extension from VSCode's marketplace and opened a scala file. I immediately got this error - 
```
Error: No suitable Java version found
Unable to find a Java 8 or Java 11 installation on this computer. To fix this problem, update the 'Java Home' setting to point to a Java 8 or Java 11 home directory or select a version to install automatically
```

I had JDK 14 installed but since metals explicitly mentioned JDK 11, I did go ahead and install it and configured the `java.home` property as 
```
"java.home": "/usr/lib/jvm/java-11-openjdk-11.0.8.10-2.fc32.x86_64/"
```
which is in fact the correct path. Yet, the error persists.

OS: Fedora 32

**Comment by tgodzik** [comment]
Thanks for reporting! We do use an utility library for locating java home, but it might not work with all possible configuration unfortunately.

Could you try specifying java home in the settings? The exact settings is `"metals.javaHome" : "path-to-home"` 

Also, are there any other messages in the metals output? There might be some more info there saying what else could be an issue.

**Comment by PawanKartikS** [comment]
That fixes it. I'm so sorry, not sure how I missed the configuration! Thanks!

**Comment by tgodzik** [comment]
Glad it helped! This probably means the message is not clear enough.

**Comment by bes1002t** [comment]
Is it possible to use the variable $JAVA_HOME as settings value? Because I don't wanna edit each tool if java home is changed. I would like the tool to use the PATH varibale $JAVA_HOME.

**Comment by bes1002t** [comment]
I tried different approaches and only the last one worked:

1. $JAVA_HOME (https://github.com/microsoft/vscode/issues/2809)
2. /usr/bin/java (which is actually a symlink to /usr/bin/java -> /etc/alternatives/java -> /usr/lib/jvm/java-11-openjdk-11.0.9.11-0.fc31.x86_64/bin/java)
3. /usr/lib/jvm/java-11-openjdk-11.0.9.11-0.fc31.x86_64/

Why is /usr/bin/java/ not working? Is vscode not able to dissolve symlinks?

**Comment by tgodzik** [comment]
I think `/usr/bin/java` is only a symlink to the java binary, not actual path to java home.

$JAVA_HOME should work, although VS Code will most of the time be started without the JAVA_HOME env variable. You would most likely need to to start it from terminal to have it defined.

**Comment by pfernandez** [comment]
> Glad it helped! This probably means the message is not clear enough.

I ran into the exact same confusion today: Saw  the `update the 'Java Home' setting`, went to `:CocConfig`, typed "`ja..`" and chose `java.config`.

Since the warning message isn't clear enough, maybe consider simply looking for `java.home` when `metals.javaHome` is doesn't exist.

**Comment by tgodzik** [comment]
Good idea, changed it in https://github.com/scalameta/metals-vscode/pull/644

**Comment by godenji** [comment]
> I think `/usr/bin/java` is only a symlink to the java binary, not actual path to java home.

No, in most linux distros you'll see as @bes1002t points out, something like:
> /usr/bin/java -> /etc/alternatives/java -> /usr/lib/jvm/java-18-openjdk-18.0.1.1.2-1.rolling.fc36.x86_64

Seems that vs code doesn't resolve symlinks, so your only option is to hard code the path, which is unfortunate.

**Comment by tgodzik** [comment]
How would using `/usr/bin/java` work if it was a symlink to a directory? Or do you mean something else?

We could possibly try to resolve the symlink and go up the directories to infer real java home, which might work. Would you mind raising it in VS Code repository `scalameta/metals-vscode` ?

**Comment by godenji** [comment]
> How would using /usr/bin/java work if it was a symlink to a directory?

I was incorrect, it does of course link to the java binary.

If the path resolves to a *file* named "java", then yes, you could probably traverse up to find java home. That would be a nice set-it-and-forget-it option for Linux users.

**Comment by godenji** [comment]
> Would you mind raising it in VS Code repository scalameta/metals-vscode ?

[Done](https://github.com/scalameta/metals-vscode/issues/1094)
