### ISSUE TITLE
Incorrect Scala minor version in docs for SBT

### ISSUE THREAD

**Issue by jackkoenig** [scalameta/metals#2023]
**Describe the bug**

The Docs are incorrect about supported Scala versions:
https://scalameta.org/metals/docs/build-tools/sbt.html#permanent-metalsenable
```diff
// build.sbt
 lazy val myproject = project.settings(
+  scalaVersion := "2.12.12", // or 2.11.12, other versions are not supported.
+  addCompilerPlugin(MetalsPlugin.semanticdbModule), // enable SemanticDB
+  scalacOptions += "-Yrangepos" // required by SemanticDB
 )
```
Using `2.12.12`, I get the following error:
```
error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.12.12:4.2.3
[error]   Not found
[error]   Not found
[error]   not found: /home/koenig/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.12/4.2.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.12/4.2.3/semanticdb-scalac_2.12.12-4.2.3.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/semanticdb-scalac_2.12.12/4.2.3/semanticdb-scalac_2.12.12-4.2.3.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/semanticdb-scalac_2.12.12/4.2.3/semanticdb-scalac_2.12.12-4.2.3.pom
[error] Total time: 1 s, completed Aug 25, 2020 12:19:38 PM
```
Inspecting Maven central, I found that `semanticdb-scalac_2.12.12-4.2.3` is published for Scala `2.12.10` so I just switched that that version.

Not a big problem for me, could be problematic for many though.

**To Reproduce**

See above

**Expected behavior**

That the instructions would work

**Screenshots**

NA
**Installation:**
- Operating system: Linux
- Editor: SBT
- Metals version: v0.9.3

**Additional context**

**Search terms**
SBT, ResolveException, Not found, semanticdb-scalac, Error downloading

**Comment by tgodzik** [comment]
Thanks for reporting! We should update the docs there, however the documentation is for the Metals versions up to 0.7.6. The current version is `0.9.3`, so I recommend just using the information from the previous section: https://scalameta.org/metals/docs/build-tools/sbt.html#for-latest-snapshot
