### ISSUE TITLE
Navigating to dependencies code doesn't work in worksheets

### ISSUE THREAD

**Issue by keynmol** [scalameta/metals#2029]
**Describe the bug**

Navigating to dependencies code doesn't work in worksheets, while it works for Scala standard library

**To Reproduce**
1. Create a worksheet in VS code
2. Put some code with dependencies in it, e.g.

```scala
import $ivy.`software.amazon.smithy:smithy-model:1.0.10`
import software.amazon.smithy.utils.SimpleParser
import software.amazon.smithy.model.Model

val parser = new SimpleParser("hello")
val x = List(1, 2, 3)
```
3. Try clicking on List
4. Try clicking on SimpleParser
5. Navigating to SimpleParser does not work

**Expected behavior**
Navigation to Scala std sources works as well as sources from the dependency

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.3
- The folder doesn't contain anything apart from 2 worksheets and two text files, no build definition

**Search terms**
metals, worksheet, magic import, code navigation

_
![reproduce-metals-worksheet](https://user-images.githubusercontent.com/1052965/91563106-35e61b80-e936-11ea-985b-553052b33616.gif)

**Comment by tgodzik** [comment]
Thanks for reporting! I think this is something we should take a look into before the next release. I will take a look and investigate first.

**Comment by keynmol** [comment]
I also think it's related to the way autocomplete works with worksheets: in the example below I get autocomplete for imports, but no autocomplete when I just type a symbol.

![reproduce-metals-worksheet](https://user-images.githubusercontent.com/1052965/91566362-75fbcd00-e93b-11ea-9bb9-ce5a87b2f45b.gif)

_and sorry for the awful quality... if someone can give me the correct ffmpeg flags to convert .mov to .gif without it looking like the horror show from the 90s, I'll appreciate that :)_

**Comment by tgodzik** [comment]
@keynmol The problem was connected, thanks for pointing that out. The fix is already in a PR. Worksheets inside sources should work correctly right now, which is a workaround for now.
