### ISSUE TITLE
Get a wrong scala version

### ISSUE THREAD

**Issue by Phantom1003** [scalameta/metals#2031]
**Describe the bug**
At first, my scala verion is 2.12.4, I got a message
```
2020.08.30 20:20:17 WARN  unsupported Scala 2.12.4
```
So I install the latest version of scala 2.13.3
```
> scala --version
Scala code runner version 2.13.3 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.
```
But the message is still there, and I can not get defination of classes

**Installation:**
- Operating system: ubuntu
- Editor: Visual Studio Code
- Metals version: v0.9.3

**Comment by ckipp01** [comment]
Thanks for the report @Phantom1003. The Scala version for your project is actually defined in your build definition. So for example, if you're using sbt, you'll want to look for the `scalaVersion` key in your `build.sbt`, and update that from `2.12.4` to a newer Scala version. You can read more about what I mean [here in the sbt docs](https://www.scala-sbt.org/1.x/docs/Howto-Scala.html#Set+the+Scala+version+used+for+building+the+project). Once that key is updated, you should be prompted to re-import your build, and you should see that warning go away.

**Comment by Phantom1003** [comment]
Wow, it works, thanks
Sorry for my stupid question

**Comment by ckipp01** [comment]
No worries. It's not a stupid question. Don't hesitate to ask anything else.
