### ISSUE TITLE
VSCode 'Failed to download Metals

### ISSUE THREAD

**Issue by jjmalina** [scalameta/metals#2047]
Trying to install Metals in VSCode.
I get this message: `Failed to download Metals, make sure you have an internet connection and the Java Home '/usr/lib/jvm/java-8-oracle/jre/' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.`

**To Reproduce**
Open VSCode, go to Extensions, search for Metals, click "Install". Retry by uninstalling and reloading VSCode

**Expected behavior**
Installs successfully

**Screenshots**
![Screenshot_2020-09-01_16-21-19](https://user-images.githubusercontent.com/178138/91902108-37358200-ec6f-11ea-995c-24f42c64d17f.png)

**Installation:**
- Operating system: Xubuntu 20.04.1 LTS
- Editor: Visual Studio Code 1.48.2-1598353430
- Metals version: v1.9.3

**Additional context**
AFAIK there is no HTTP proxy and I have openvpn turned off.

`JAVA_HOME` is set to `/usr/lib/jvm/java-8-oracle/jre/`

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! Could you try changing the java home to `/usr/lib/jvm/java-8-oracle`? That's my first guess since I do not see any other issues and it seems to be poiting to JRE and not the JDK

**Comment by jjmalina** [comment]
@tgodzik thanks for the quick reply! I tried that but still have the same issue

**Comment by tgodzik** [comment]
Are you sure you have a JDK installed? It looks like it can't run the java process to download the server itself. What happens if you remove the setting altogether?

**Comment by jjmalina** [comment]
Yes I do have a JDK. I removed `export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre/` and now everything works! :)

I think apt must have removed the JDK because that directory isn't there.
```
λ ls -l /usr/lib/jvm/
total 8
lrwxrwxrwx 1 root root   25 Jul 17  2019 default-java -> java-1.11.0-openjdk-amd64
lrwxrwxrwx 1 root root   21 Jan 15  2020 java-1.11.0-openjdk-amd64 -> java-11-openjdk-amd64
drwxr-xr-x 7 root root 4096 Aug 12 09:25 java-11-openjdk-amd64
lrwxrwxrwx 1 root root   20 Apr 16 04:47 java-1.8.0-openjdk-amd64 -> java-8-openjdk-amd64
drwxr-xr-x 7 root root 4096 Aug 12 09:24 java-8-openjdk-amd64
```

**Comment by tgodzik** [comment]
Glad it works!  Let us know if you get any other problems.

**Comment by don41382** [comment]
I hade the same issue. Adding the path in Visual Studio inside of the metal extension fixed my issue.

This shows how:
https://scalameta.org/metals/docs/editors/vscode.html#configure-java-version

**Comment by ConsDotPy** [comment]
I had same exact problem, environment variables in order too, but only this worked for me.

> I hade the same issue. Adding the path in Visual Studio inside of the metal extension fixed my issue.
> 
> This shows how: https://scalameta.org/metals/docs/editors/vscode.html#configure-java-version
