### ISSUE TITLE
How do I run MUnit tests from VSCode with Metals?

### ISSUE THREAD

**Issue by tovbinm** [scalameta/metals#2048]
**Question**

How do I run [MUnit](https://scalameta.org/munit/) tests from VSCode with Metals?

**Comment by kpbochenek** [comment]
Similarly to how run/debug works(https://scalameta.org/metals/docs/editors/vscode.html#running-and-debugging-your-code) you should have lenses on your test classes allowing you to run tests or you can do that with launch.json described in link

![Screenshot 2020-09-02 at 18 46 54](https://user-images.githubusercontent.com/10478402/92012397-ad5be680-ed4c-11ea-97c8-7505194f54ef.png)

What exact problems are you facing?

**Comment by tovbinm** [comment]
OK, if I manually edit `launch.json` and run it from Run configuration menu it works.

This option never appears for my test suites: <img width="134" alt="Screen Shot 2020-09-02 at 10 01 43 AM" src="https://user-images.githubusercontent.com/629845/92013935-4ebe4a80-ed03-11ea-858f-3258a62b387f.png">

**Comment by kpbochenek** [comment]
If you create a file in your source directory(not! in tests) then do you see lenses?:

![Screenshot 2020-09-02 at 19 11 47](https://user-images.githubusercontent.com/10478402/92014827-27da3580-ed50-11ea-80cf-7e76802042a4.png)

Are lenses a problem or tests?

**Comment by tovbinm** [comment]
Hmm, I can see the lenses on my app just fine: <img width="412" alt="Screen Shot 2020-09-02 at 10 15 04 AM" src="https://user-images.githubusercontent.com/629845/92015128-2cc5c780-ed05-11ea-9b0a-27622ee34879.png">

**Comment by kpbochenek** [comment]
Okay we are narrowing it, if you try a file in your tests(minimal test example):
![Screenshot 2020-09-02 at 19 19 31](https://user-images.githubusercontent.com/10478402/92015535-3bd26700-ed51-11ea-899b-d7a9b88c9922.png)

Are lenses there?

If you see them on minimal example then could you provide minimal reproduction where you don't see lenses in tests? 
Then we will be able to also check if we don't see lenses(maybe a problem is your setup) or call it a bug and take a look why lenses are not visible in this case.

**Comment by tovbinm** [comment]
Yeah, it's definitely not showing up:
<img width="406" alt="Screen Shot 2020-09-02 at 10 26 38 AM" src="https://user-images.githubusercontent.com/629845/92016166-cb065d00-ed06-11ea-8185-ac0e753abbd3.png">

**Comment by tgodzik** [comment]
> Yeah, it's definitely not showing up:

Is the code compiled? This might be an issue with semanticdb files not being available, which means either there were errors or we are having problems detecting it.

Otherwise, would it be possible that you have the code lenses setting turned offf?

**Comment by tovbinm** [comment]
How do I validate that lenses are on? Here are my settings:

<img width="821" alt="Screen Shot 2020-09-03 at 10 56 44 AM" src="https://user-images.githubusercontent.com/629845/92150415-3c601180-edd4-11ea-868d-ac0968c0e396.png">
<img width="821" alt="Screen Shot 2020-09-03 at 10 56 54 AM" src="https://user-images.githubusercontent.com/629845/92150430-41bd5c00-edd4-11ea-9a54-6338dd6adb46.png">
<img width="795" alt="Screen Shot 2020-09-03 at 10 57 02 AM" src="https://user-images.githubusercontent.com/629845/92150445-45e97980-edd4-11ea-8eeb-5420204d0a75.png">

**Comment by tgodzik** [comment]
It should be enabled as it is here:

![image](https://user-images.githubusercontent.com/3807253/92224223-cf1ab200-eea1-11ea-9448-cb34e0828884.png)

**Comment by tovbinm** [comment]
Thanks. I have it enabled.

**Comment by tovbinm** [comment]
How can I troubleshoot it further?

**Comment by tgodzik** [comment]
Not sure, do references are properly found in the project? Would you be able to minimize a code sample/project that this doesn't work on?

**Comment by tovbinm** [comment]
I just tried to create a new project to reproduce, and it works there perfectly. Probably something in my current project prevents it from appearing. Are there any logs I can look into?

**Comment by kpbochenek** [comment]
Logs are in `.metals/metals.log` but I don't think you will find any errors there.

Lenses are displayed in the same way for `Run` and `Test`. If you see `Run` lenses then it is not display issue.

If a project doesn't compile, you won't see lenses. Maybe main project compiles, but you have errors in tests and they don't compile -> you won't see lenses only in tests.
But you said you can run tests through `launch.json` which would be impossible if tests didn't compile.

Other possibility is, during code compilation we generate a database of symbols present in each file. This is done by a plugin injected into a compiler. Compiler says us that for definition of symbols X, Y, Z display test lenses for them.
But if symbols are wrongly generated for your file you might not see them. Super rare and you would have to use very uncommon scala constructs.

Without minimal reproduction project it might be hard to proceed with this because as you said it must be something specific to this single project.

**Comment by tovbinm** [comment]
The problem seems to be only reproducible on that particular project.
