### ISSUE TITLE
Organize imports

### ISSUE THREAD

**Issue by pmellati** [scalameta/metals#2052]
**Is your feature request related to a problem? Please describe.**

The editor doesn't help with organizing my imports. Also, when the editor automatically adds an import, it doesn't insert at the right location.

**Describe the solution you'd like**

* Add a new setting that allows the user to describe a strategy for organizing imports. Should be flexible enough to express:
  + The grouping of imports, and order of groups (e.g. scala std-lib imports first, java imports next, third party imports next, imports from current project last)
  + The ordering of imports within groups (e.g. alphabetical)
  + How wildcard imports should be used (e.g. if more than 6 imports from the same package, use a wildcard.)
* Add an operation to "organize imports" at will.
* If the imports (in the current file) are already organized, and the editor is adding a new import statement automatically, the new import should be added so that the imports remain organized.

**Describe alternatives you've considered**

**Additional context**

**Search terms**:

optimize imports

**Comment by gabro** [comment]
To clarify, the only thing that's still missing from the original feature request is that auto-imports won't automatically follow the configured grouping. The user still needs to run the organize import command manually. (Correct me if I'm wrong @mlachkar, @tgodzik)

Still, the main functionality is there (integrated in the editor, configurable via .scalafix.conf, etc)! I personally think the current UX is good enough, but if somebody cares about the auto-import thing, I suggest to open a smaller dedicated feature request for it

**Comment by tgodzik** [comment]
@gabro Yeah, auto import will not work. I think that might be done once we manage to run organize imports on unsaved files. We could apply edits internally and run the sort on it. That's just one idea, but might hard to do. The other option would be to duplicate the logic from organize imports rules, but I would rather not go into that direction.

**Comment by gabro** [comment]
@tgodzik if we manage to run organize imports on unsaved filed (or rather, "just saved" files which have no semanticdb produced by batch compilation yet), then I think we should treat organize imports the same as formatting (i.e. something to ran automatically on save)

I would recommend setting up the editor so that organize imports is ran on save, which in VSCode can be done with

```json
  "[scala]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  },
```

(This is currently not viable because organize imports cannot be ran right after saving, since it needs for compilation to happen first)
