### ISSUE TITLE
Unbound placeholder parameter error in worksheets with Dotty

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2076]
**Describe the bug**
Given the following code snippet in a worksheet with dotty...

```scala
def x = 1 -> 2
val (a, _) = x
```
...you'll see an error.
```
[mdoc] [E] scala.worksheet.sc:14 (mdoc generated code) Unbound placeholder
  parameter; incorrect use of _
     $doc.binder(_, 2, 8, 2, 9)

384
```

**To Reproduce**
1. Paste the code snippet above in a Dotty worksheet
2. Evaluate and see error

**Expected behavior**
This works fine in Scala 2 and is valid syntax afaik in Scala 3. This shouldn't give this error message.

**Installation:**
- Operating system: macOS
- Editor: Vim
- Metals version: `0.9.3+102-31fb9f1e-SNAPSHOT`

**Additional context**
I'm still trying to figure out what exact placeholder syntax triggers this which doesn't some of the other types of placeholder syntaxes I've tried doesn't seem to be an issue like this one is.

cc @eloots

**Search terms**
placeholder syntax, dotty, worksheets

**Comment by tgodzik** [comment]
Thanks for finding this! The problem is most likely in mdoc, I am not super sure why this is, but it should be easily reproducible in the tests.

**Comment by ckipp01** [comment]
So from looking at the evaluated document in Scala 2.x we get:
```scala
EvaluatedDocument(Input.VirtualFile("placeholder.scala", "package repl
object MdocSession extends _root_.mdoc.internal.document.DocumentBuilder {
  def app(): _root_.scala.Unit = {val _ = new App()}
  class App {
$doc.startSection();
$doc.startStatement(0, 0, 0, 14);
def x = 1 -> 2
$doc.endStatement();
$doc.startStatement(1, 0, 1, 14);
val (a, _) = x; $doc.binder(a, 1, 5, 1, 6)
$doc.endStatement();
$doc.endSection();
  }
}
```
With Dotty it looks like so:
```diff
EvaluatedDocument(Input.VirtualFile("placeholder.scala", "package repl
object MdocSession extends _root_.mdoc.internal.document.DocumentBuilder {
  def app(): _root_.scala.Unit = {val _ = new App()}
  class App {
    $doc.startSection();
    $doc.startStatement(0, 0, 0, 14);
    def x = 1 -> 2
    $doc.endStatement();
    $doc.startStatement(1, 0, 1, 14);
    val (a, _) = x
    $doc.binder(a, 1, 5, 1, 6)
+   $doc.binder(_, 1, 8, 1, 9)
    $doc.endStatement();
    $doc.endSection();
  }
}
```
I'm going to make a wild guess and say that the `$doc.binder(_, 1, 8, 1, 9)` should just be skipped like it is in Scala 2.x. At least that's the route I'm heading.

**Comment by tgodzik** [comment]
I think it should be simple to add a check here: https://github.com/scalameta/mdoc/blob/f103ee4db62a1cebcaf5265a6d771bceb842b378/mdoc/src/main/scala-3/mdoc/internal/markdown/Instrumenter.scala#L147

**Comment by tgodzik** [comment]
Do you want to take a look at it or should I try to fix it?

**Comment by ckipp01** [comment]
> Do you want to take a look at it or should I try to fix it? @ckipp01

I'm actually looking at it right now. So I'll ping you if I get stuck 😆
