### ISSUE TITLE
Document new `metals-goto-location` argument

### ISSUE THREAD

**Issue by kurnevsky** [scalameta/metals#2092]
Hi there. `metals-goto-location` contains a new argument now which is not documented:
https://github.com/scalameta/metals/blob/4892a33d44f741f12b85ec17b52456bf36d31c38/metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala#L108-L124
https://github.com/scalameta/metals/blob/9d26815263432711052d5be24b114e21e1c37a9e/metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala#L121

It's not clear what it's used for so please add a documentation for it.

**Comment by tgodzik** [comment]
Thanks for reporting! @kpbochenek could you take a look at this?

**Comment by kpbochenek** [comment]
@kurnevsky updated docs in PR.

This parameter is only used in analyzing stacktrace and so far it is handled only by VSCode.

As you analyze stacktrace you open special file `.metals/stacktrace.scala` which has lenses generated for each line like so:
![2020-09-24-180722_717x446_scrot](https://user-images.githubusercontent.com/10478402/94171143-31f3dd80-fe91-11ea-838b-5424fa5aea25.png)

It would be nic if executing action on a line would keep stacktrace visible and you would jump to location in another window.
(you execute lens action and in another window you see location)
![2020-09-24-181237_565x533_scrot](https://user-images.githubusercontent.com/10478402/94171690-d83fe300-fe91-11ea-85c2-279828b4c615.png)

I imagined client would do:
I have only one window open, I will do a split and open this location in newly created window.
I have more than one window, I will select one that is not currently active and open location there.

It makes a lot of sense for VSCode but for other editors we will have to see how it would work. Maybe we will need to improve it further.

But again this is just a flag that can be completely ignored too and nothing bad will happen :)
