### ISSUE TITLE
Allow configuring JDK path

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#210]
As suggested in https://github.com/scalameta/metals/issues/41#issuecomment-375973005 we could allow configuring the JDK path.

**Comment by olafurpg** [comment]
I think it would make sense to additionally fallback to `.orElse(sys.env("JAVA_HOME"))` if that would avoid  the need for all windows users to configure the path in settings.

**Comment by olafurpg** [comment]
If I understand correctly, we should detect Java home in the following order

- User configuration in VS Code
- `System.getProperty("java.home")`
- `System.getenv().get("JAVA_HOME")`
- Error 💥
