### ISSUE TITLE
Organize import warning message about saving the file is a bit miselading

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#2100]
I've been testing the organize imports feature, and I think the warning message we get when trying to organize imports of an unsaved file is a bit misleading.

If I understand correctly it's not really about the file being saved, rather the file being compiled (aka semanticdb has been produced). If that's the case, the warning message is a bit misleading because after saving the file the user also needs to wait for compilation to be over.

I found this while trying VSCode's `editor.codeActionsOnSave` command with this configuration:

```json
  "[scala]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  },
```

This will run the "organize imports" action right after the file is saved, but when I do that I still get the warning from Metals about saving the file first. If I save the file a second time, the action is ran correctly (because the file has been compiled in the meantime).

My proposal would be to do something similar to what we do in RenameProvider to monitor active compilations and trigger the warning based on that (rather than on the file being saved or not).

What do you think @mlachkar / @tgodzik?

---

As an aside, do we only need the semanticdb file of the current file for this to work? If that's the case maybe we can produce it using the PC and try to avoid this limitation?

**Comment by tgodzik** [comment]
Thanks for testing it out! We've been meaning to also work on producing semanticdb for unsaved files and that might also unblock SBT files. The only problem is that we need to write that semanticdb files to the filesystem, but I think that shouldn't be that problematic.

We could do the same as for the rename provider for the time being, good idea!
