### ISSUE TITLE
Error reporting when organize imports fails

### ISSUE THREAD

**Issue by pvid** [scalameta/metals#2102]
**Describe the bug**

Follow-up to https://github.com/scalameta/metals/issues/2099. The issue with actual organizing of imports has been fixed. However, it would be useful to improve error reporting in case a different error occurs

**To Reproduce**

1. Find a project using Scala 2.11.12 (For example https://github.com/scalapb/sparksql-scalapb/tree/v0.9.3 and manually change sparkSqlScalaPB scala version to 2.11.12)
2. Mess up imports in some file
3. Run organize imports
4. See that nothing happens and no error is reported

**Expected behavior**

Metals should provide clear information why organize imports failed

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: 0.9.4+15-a3d0d948-SNAPSHOT

**Additional context**

Errors encountered during fetching of `organize-imports` artifact do not get reported because of the use of a `Try(...).toOption` pattern

**Search terms**

organize imports, scalafix

**Comment by tgodzik** [comment]
Thanks for the follow up!
