### ISSUE TITLE
No auto import completions inside a string

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#2105]
**Describe the bug**

Completing:

```scala
"this is an interesting $File@@"
```

does not give us a completion that would automatically add an import.

**To Reproduce**

Just try it the above snippet.

**Expected behavior**

`java.nio.Files` is suggested

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.9.4

**Additional context**

It does work for:
```scala
s"this is an interesting $File@@"
```

**Search terms**

completion string interpolation

**Comment by eilite** [comment]
When checking the logs, I see that the metals server does not receive a `textDocument/completion` request in this case : `"this is an interesting $File"` but in that case `s"this is an interesting $File"` it does.
Could that be the cause of this issue ?

**Comment by ckipp01** [comment]
So I just quickly looked at this, and it does seem that when I try out the text I get a completion request:

<img width="780" alt="Screenshot 2020-10-12 at 19 14 16" src="https://user-images.githubusercontent.com/13974112/95773663-36a4f800-0cbf-11eb-83b7-6546c05ee201.png">

```
[Trace - 07:13:14 PM] Received request 'textDocument/completion - (123)'
Params: {
  "context": {
    "triggerKind": 1
  },
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/tester/src/main/scala/example/Main.scala"
  },
  "position": {
    "line": 4,
    "character": 28
  }
}
```
So it does look like the request is there, but more that the correct completion is coming back. I'd dive in [here](https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala) to start and try to follow where you'd imagine the completion should come from and narrow it down to where the issue may be.
