### ISSUE TITLE
Support for remote debug

### ISSUE THREAD

**Issue by romanowski** [scalameta/metals#2115]
**Is your feature request related to a problem? Please describe.**

Metals currently supports debugging when metals are in charge of running jvm (tests and mains) which is awesome got tests or small application. In many cases one need to debug application that are started by other things (e.g. jvm for Metals server itself are started from within vs code) and fro such case jvm has `agentlib:` parameter (e.g. `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005`) that allows to connect to from an outside application (or with listen mode jvm would try to connect to provided address on startup).

Intellij and other IDE supports this and for now whenever I need to use it I am forced to switch back to Intellij.

**Describe the solution you'd like**

This is well establish feature from technical point of view so I don't think there is much to describe. 
I would love to see both modes (Attach and Listen) supported but having any of those will be a huge step forward.

In terms of configuration, user should be able to specify mode, port and where to  get classpath from in some shape or form. I do not have any preferences there. 

**Describe alternatives you've considered**

As mentioned this is well establish feature in other IDEs and I don't see (but I may be wrong) need to search for alternative.

**Additional context**

Configuration window from Intellij looks like this:

![Screenshot from 2020-03-09 13-52-35](https://user-images.githubusercontent.com/3967938/76214552-429e7800-620d-11ea-82ba-7154df747f9f.png)

**Search terms**:
Remote, Debug, JDP, JDWP, Intellij

**Comment by tgodzik** [comment]
Thanks @pvid ! I see that the PR in Bloop is almost ready, so I moved the feature to the main repo.
