### ISSUE TITLE
JVM options and environmental variables in Vscode run configuration. 

### ISSUE THREAD

**Issue by pshemass** [scalameta/metals#2116]
**Is your feature request related to a problem? Please describe.**

When I run/debug application during development in many occasions I need to override system properties.

**Describe the solution you'd like**

It would be great if run configuration will support `vmArgs` and `env` the same way as java extension https://code.visualstudio.com/docs/java/java-debugging

**Comment by tgodzik** [comment]
@mwz That is a separate issue, but should be easy to do.

We would need an `envFile` value next to the env one and we could read it in Metals and add to the rest of values. 

Feel free to create a PR or feature request. It would all be a very similar issue to https://github.com/scalameta/metals/pull/2118

**Comment by mwz** [comment]
> We would need an `envFile` value next to the env one and we could read it in Metals and add to the rest of values.
> 
> Feel free to create a PR or feature request. It would all be a very similar issue to #2118

Ok, yeah it seems straightforward enough, let me have a look into that then. 👍

**Comment by tgodzik** [comment]
@mwz Let me know if you have any issues! https://scalameta.org/metals/docs/contributors/getting-started.html should have all you need
