### ISSUE TITLE
@main annotation not working under certain conditions

### ISSUE THREAD

**Issue by eloots** [scalameta/metals#2117]
**Describe the bug**

After working with Scala worksheets in Dotty exclusively for more than a week, I started working on "regular" Dotty programs again this week and encountered a problem with Scala main methods that are defined using the new `@main` annotation. Because Iv'e used methods encoded like this a lot in the past, I tried to figure out what was going on and ended up reinstalling VSC/Metals from scratch.

Still, after all the effort, the problem still persists. The good news is that I have figured out how to reproduce it and my suspicion is that the problem is specifically linked to the `@main` annotation.

**To Reproduce**

- Uninstalled VSC/Metals including saved settings by following the instructions [here](https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac).
- Dowload VSC and install. Launch VSC and install the Metals plugin.
- Open a Dotty template (`Metals: New Scala Project` and select the `lampepfl/dotty.g8` template.
    - The project is minimalistic and contains a single main method that is encoded using the new `@main` annotation
    - Out of the box, this project can be run without a problem.
- **_Edit the program by modifying the content of the main method. The change can be as simple as changing one of the string literals._**.
- Save the file and try to compile/run it.
- This results in an error in the IDE, even though the program compiles and runs just fine from the sbt shell.

My impression at this moment is that it's the `@main` annotation that somehow triggers this issue.

In any case; wrapping the main method in an object (and adding the `args: Array[String]` argument solves the issue in the IDE.

One can cycle through a working (using an old style main method declaration) and a non-working (`@main` based) version as many times as wanted.

> Note: `Main.scala` in the sample code has no package declaration in it. Adding one can make the program compile again, but the problem is re-triggered by changing the content of the main method as described above.

**Expected behavior**

`@main def` syntax should always work.

**Screenshots**

![error message](https://i.imgur.com/hS0jVsO.png)

========

![error message with problems shown](https://i.imgur.com/fWuwZMD.png)

**Installation:**

- Operating system: macOS 10.15.5
- Editor: Visual Studio Code 
- Metals version: v0.9.4
- Java version: openjdk 11.0.6 2020-01-14 - OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
- Bloop version: v1.4.4

**Additional context**

**Search terms**

@main main methods Required: scala.annotation.Annotation bloop

**Comment by tgodzik** [comment]
Thanks for reporting! I think I've seen this issue before, but was unable to pinpoint the exact reason. We might actually need to fix it in Bloop itself.

**Comment by kpbochenek** [comment]
I have raised it on bloop gitter channel a few months ago, looks like problem still exists :(
https://gitter.im/scalacenter/bloop?at=5ec6334513b79205dc896e46

**Comment by kpodsiad** [comment]
I tried to reproduce this error using steps described in https://github.com/scalacenter/bloop/issues/1380 but it seems that it's been already fixed.

@eloots in case you'll encounter this problem again let us know about it.
