### ISSUE TITLE
No completions given for user defined types in an Ammonite script

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2122]
**Describe the bug**

It seems that Ammonite isn't providing any completion items for members of self defined types.

**To Reproduce**
Given the following:

```scala
case class Test(a: Int, b: String)

class Test2 {
  def a(a: Int): Int = a
}

object Test3 {
  val a = "a"
}

val test = Test(1, "one")

test.@@ // neither a or b completions offered here.

val test2 = new Test2

test2.@@ // no a completion given here

Test3.@@ // no a completion given here
```

**Expected behavior**

I would expect member completions for all of the given examples

**Installation:**

- Operating system: macOS
- Editor: Vim
- Metals version: `0.9.4+43-6a98caf6-SNAPSHOT`

**Search terms**

Ammonite completions

**Comment by tgodzik** [comment]
Thanks for reporting! Maybe we are not giving the presentation compiler the right path to the compiled artifacts?

**Comment by AcrossForest** [comment]
Same issue for VSCode on win10.

**Comment by thinkiny** [comment]
same issume for emacs
