### ISSUE TITLE
Incorrect color highlighting of package-private modified symbol hover

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#2127]
**Describe the bug**

I'm not 100% sure this belongs in metals, maybe it's just the vscode syntax / client.

Some symbols (e.g. classes) marked as `private[pkg]`, where `pkg` is an object or package, are highlighted wrong.

**To Reproduce**

Case 1:

1. Write the code

```scala
package foo {
  private[foo] class bar

  object a {
    new foo.bar
  }
}
```

2. Hover on `bar` in `new foo.bar`

Case 2:

1. Change `foo` to be an object

2. There's no step 2

**Expected behavior**

Correct highlighting

**Screenshots**

Actual highlighting:

Case 1

![image](https://user-images.githubusercontent.com/894884/95516029-eaa43b80-09be-11eb-94df-9c0d9f203688.png)

Case 2

![image](https://user-images.githubusercontent.com/894884/95516050-f1cb4980-09be-11eb-94fd-8eee4341b43e.png)

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.4

**Search terms**

highlight, syntax, hover

**Comment by kpbochenek** [comment]
You can see here: https://github.com/scala/vscode-scala-syntax/blob/master/src/typescript/Scala.tmLanguage.ts#L849
Matching only handles `private[\S+]` which means non whitespace characters. Puting `object foo` there breaks this regex.

**Comment by tgodzik** [comment]
Thanks for reporting! This is not really an issue with the syntax highlighting as it is with us adding `package`, which is not synthetically correct. This should be fixed in Metals.

**Comment by kpbochenek** [comment]
ahh sorry, this is hover got it :+1:

**Comment by kubukoz** [comment]
Seems like this has changed:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/894884/185461548-a7915987-4b06-4dcf-9f6f-78b0722091a0.png">

I guess it's no longer incorrect, so maybe we can close this 😅

**Comment by tanishiking** [comment]
Thank you for confirming this! It's "solved" in a wired way 😅 
Closing for now, but if anyone find a same issue, feel free to open a new issue, or re-open this ticket :)
