### ISSUE TITLE
Running / Debugging doesnt work when connected to a VPN

### ISSUE THREAD

**Issue by jahan01** [scalameta/metals#2128]
When my host is connected to VPN, if I start debugging / run session from vscode it times out with below error message.

```
Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.net.SocketTimeoutException: connect timed out: <my_host_name>:65120
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
```
When VPN connection is turned off:

```
2020.10.06 23:06:46 INFO  Listening for transport dt_socket at address: 64793
2020.10.06 23:06:46 INFO  Trying to attach to remote debuggee VM localhost:64793
```

I did run some diagnosis in a worksheet to find how JVM is reading network details and below are the results. They dont change irrespective of VPN is connected or not.

1. 
```scala
import java.net.InetAddress;
val x1 = InetAddress.getLoopbackAddress();
// localhost/127.0.0.1
```

2. [Snippet from here](https://github.com/scalameta/metals/blob/e26d21f921f71e996e70a925cfc329dffc377c0c/metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala#L67)

```scala
import java.net.ServerSocket;
import com.google.common.net.InetAddresses;
import java.net.URI
import java.net.Socket
import java.net.InetSocketAddress
import java.util.concurrent.TimeUnit

val proxyServer = new ServerSocket(0) // addr=0.0.0.0/0.0.0.0,localport=54889
val host = InetAddresses.toUriString(proxyServer.getInetAddress)
val port = proxyServer.getLocalPort
val uri = URI.create(s"tcp://$host:$port") // tcp://0.0.0.0:54889
val socket = new Socket()
val address = new InetSocketAddress(uri.getHost, uri.getPort) // /0.0.0.0:54889
val timeout = TimeUnit.SECONDS.toMillis(10).toInt // 10000
```

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.4

**Comment by tgodzik** [comment]
Thanks for reporting! I not 100% sure what is going on, but for sure we should investigate.

**Comment by pvid** [comment]
I found a [bloop PR](https://github.com/scalacenter/bloop/pull/1345) concerned with a similar issue.

Is it possible that `0.0.0.0` resolves to a different network interface than the loopback one when you use your VPN? I don't know enough about networking to be honest 🤷‍♂️ .

A thing worth trying is to hardcode `127.0.0.1` as the host instead of of using `proxyServer.getInetAddress`.

**Comment by jahan01** [comment]
> Is it possible that `0.0.0.0` resolves to a different network interface than the loopback one when you use your VPN? I don't know enough about networking to be honest 🤷‍♂️ .

@pvid I don't even know networking either :)
But if you look at the below error message somehow metals is using hostname instead of `localhost`.

```
 java.util.concurrent.CompletionException: java.net.SocketTimeoutException: connect timed out: <my_host_name>:65120
     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
```

I don't understand the flow of how debugger is started by metals. So I cannot figure out how the hostname is fetched.

**Comment by ritschwumm** [comment]
0.0.0.0 means all ip addresses on the local machine, which essentially means my colleague on the next desk should have the same kind of access as i do. questionable, if you ask me.

**Comment by tgodzik** [comment]
Thanks for all the info, I changed it to always use 127.0.0.1 by default.

**Comment by jahan01** [comment]
thanks @tgodzik
