### ISSUE TITLE
Rename metalsEnableCompletions to something more accurate

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#213]
Running the task does not enable completions, so it should be called something else like `metalsCompilerConfig`

**Comment by gabro** [comment]
I prefer something short since when prefixing the *: sbt autocompletion doesn't work (is it just me?)

metalsSetup?

**Comment by laughedelic** [comment]
> since when prefixing the *: sbt autocompletion doesn't work (is it just me?)

It works for me (sbt 1.1.0). Anyway, I'm fine with either option.

**Comment by olafurpg** [comment]
metalSetup it became @gabro !
