### ISSUE TITLE
Setting up debugger in Emacs documentation

### ISSUE THREAD

**Issue by CsBigDataHub** [scalameta/metals#2153]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Documentation on how to setup debugger in emacs.

**Comment by CsBigDataHub** [comment]
@tgodzik thanks.

I am not sure, could not find anything on setting up a debugger in emacs for metals anywhere.

Here is a documentation on how to setup a debugger in emacs for other languages. https://emacs-lsp.github.io/dap-mode/page/configuration/

**Comment by tgodzik** [comment]
There is a part in out docs about DAP:
```
;; Use the Debug Adapter Protocol for running tests and debugging
(use-package posframe
  ;; Posframe is a pop-up tool that must be manually installed for dap-mode
  )
(use-package dap-mode
  :hook
  (lsp-mode . dap-mode)
  (lsp-mode . dap-ui-mode)
  )
```

Have you tried using that? It might require running a command first `debug-adapter-start`, but that should not be too difficult. More information here:

https://scalameta.org/metals/docs/editors/debug-adapter-protocol.html
