### ISSUE TITLE
How to approach the `TestingServer` as we continue to get more BSP servers

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2163]
## Discussion

Up to this point Metals has heavily relied (and will continue to rely) on Bloop for our testing server. Pretty much all of our suites that involve any type of `initialize` in the LSP sense rely on a build server connection. During the `initialize` we currently do a `bloopInstall` on the workspace and use Bloop as a build server. You can see this in the `initialize` method here:

https://github.com/scalameta/metals/blob/17ed475be308ef3f914a806af00d32e8fc39cff2/tests/unit/src/main/scala/tests/TestingServer.scala#L381-L389

With the new BSP support in sbt, especially the integrated support coming in https://github.com/scalameta/metals/pull/2154, and also seeing that Mill has also introduced BSP support, I think it's a good idea to discuss the future of how we'd like to test. While we do have tests that cover BSP discovery, we also have a lot of tests the rely on a build server being present. A couple things I've been thinking about:

1. The possibility of introducing multiple different "test servers" to use in the various tests that are specific to the build server (Bloop, sbt, Mill, maybe more?)
2. Refactoring the `TestingServer` to basically be able to "swap out" the build server
3. Do we duplicate all the LSP related tests with each server? Or do we simply make sure the connection work correctly, and focus on one build server for all the heavy LSP related stuff?
4. Other concerns I haven't yet thought about...

I'd love to get some more input and discussion on this topic to ensure that whatever additional support we continue to add for other build servers is properly tested and as stable as it currently is with Bloop.

**Search terms**

BSP servers, BSP testing

**Comment by olafurpg** [comment]
Thank you for bringing this up! I agree the current testing strategy does not scale well with the increasing number of new build servers. It would be lovely if we could somehow run existing tests against different build servers.

One possible approach would be to extend `QuickBuild` to generate sbt/mill builds. That would allow us to continue to declare the build structure via `metals.json` but have the tests run against mill/sbt instead of Bloop.

**Comment by tgodzik** [comment]
I think it would make sense to run tests with different BSP server in the slow tests. We could add there a couple of basic tests to check if everything is working. I don't think we should duplicate all the tests as we are already running a lot of them and I doubt I will be able to optimize anything further.

**Comment by adpi2** [comment]
I would like to add more tests on the integration with sbt server so I am currently trying to do something like 1. and 2. as in:

> 1. The possibility of introducing multiple different "test servers" to use in the various tests that are specific to the build server (Bloop, sbt, Mill, maybe more?)
> 2.  Refactoring the TestingServer to basically be able to "swap out" the build server

**Comment by ckipp01** [comment]
Closed via https://github.com/scalameta/metals/pull/3006
