### ISSUE TITLE
Avoid continuous compilation of generated sources when using sbt BSP

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2183]
**Describe the bug**

If you're using sbt BSP and you have a plugin `sbt-jmh` for example that generates sources, this can potentially cause continuous compilations happening. This is a follow-up of the original issue created here in [sbt](https://github.com/sbt/sbt/issues/6037). The core of the issues pointed out by @adpi2 seems to be the following:

1. Metals sends a compileRequest on bench-jmh
2. sbt replies that bench-jmh is compiled successfully
3. Metals sends a scalaMainClasses request on bench-jmh
4. sbt runs discoveredMainClasses that generates new sources
5. sbt replies that bench-jmh contains no Main classes
6. Metals detects the new generated sources and goes to step 1

This results in this:

![2020-10-30 21 53 28](https://user-images.githubusercontent.com/13974112/97756292-ee793880-1afa-11eb-914f-5c2051b93bbf.gif)

**Expected behavior**

I'd expect for these sources to be generated once, and then stop.

**Additional context**

The possible solution mentioned there by @tgodzik 

> The alternative as we discussed with @adpi2 is that because:

> The buildTarget/sources response tells if a file is generated or not. we could try to not run compilation on changes to those files.

**Search terms**

continuous compilation, generated sources, sbt BSP

**Comment by tanishiking** [comment]
Let me delve into this, as I'm unable to use sbt + BSP in my private project because of this issue.

**Comment by tanishiking** [comment]
So

- We can potentially fix this issue by https://github.com/sbt/sbt/issues/6037#issuecomment-720384726 👍 
- There's a concern about the re-compilation fired by program generation https://github.com/sbt/sbt/issues/6037#issuecomment-720426998 and I also agree with @tgodzik https://github.com/sbt/sbt/issues/6037#issuecomment-720439642 
- Looks like there's already `generated` flag in BSP https://build-server-protocol.github.io/docs/specification.html#build-target-sources-request
- TODOs
  - Checking sbt returns `generated` field or not
  - Making metals not to compile for `generated` source files.
