### ISSUE TITLE
ClassDefNotFound error only in Worksheet

### ISSUE THREAD

**Issue by jmcclell** [scalameta/metals#2187]
Trying to follow the Book of Doobie using a Worksheet, the following code produces a `ClassDefNotFound` exception when in a worksheet context. This same exact code works when input directly into ammonite's REPL or when compiled in a standard scala file via SBT.

**To Reproduce**

Create a worksheet (e.g. `book-of-doobie.worksheet.sc`) with the following code:

```scala
import $ivy.`org.tpolecat::doobie-core:0.9.0`
import $ivy.`org.tpolecat::doobie-postgres:0.9.0`
import $ivy.`org.tpolecat::doobie-specs2:0.9.0`

import cats._, cats.effect._, cats.data._, cats.implicits._
import doobie._
import doobie.implicits._

import doobie.util.ExecutionContexts
implicit val cs = IO.contextShift(ExecutionContexts.synchronous)

val xa = Transactor.fromDriverManager[IO](
  "org.postgresql.Driver",     // driver classname
  "jdbc:postgresql:world",     // connect URL (driver-specific)
  "postgres",                  // user
  "",                          // password
  Blocker.liftExecutionContext(ExecutionContexts.synchronous) // just for testing
)
```
```
[mdoc] [E] java.lang.NoClassDefFoundError: java/sql/Connection
  at doobie.util.transactor$Transactor$fromDriverManager$.apply(transactor.scala:377)                                                                          
  at repl.MdocSession$App.<init>(book-of-doobie.worksheet.sc:35)
  at repl.MdocSession$.app(book-of-doobie.worksheet.sc:3)
```

**Expected behavior**

Code should compile without error

**Installation:**

- Operating system: macOS
- Editor: nvim
- Metals version: v0.9.5 via coc-metals

**Comment by ckipp01** [comment]
Thanks for reporting @jmcclell although I'm unable to reproduce.

<img width="1080" alt="Screenshot 2020-11-03 at 08 28 18" src="https://user-images.githubusercontent.com/13974112/97958958-9ff3c480-1dae-11eb-8a39-625958014c95.png">

Could you provide a bit more information. v0.9.5 is actually the extension version for coc-metals, but could you also provide what version of Metals you're using? If you do a `metals.logs-toggle` command, and scroll up to the top of the logs, you should see a `Started: Metals version <version>.`

Also what Java version are you using?

**Comment by jmcclell** [comment]
Hi @ckipp01 - thanks for the fast response. 

The metals version in the log appears to be `0.9.4` and I'm using OpenJDK 14.

**Comment by ckipp01** [comment]
Ah, ok I was able to reproduce it. `Java.sql.Connection` should be there in 11 though according to the Java api. I'll have to dig a bit more into this situation to see what's going on. So a quick fix if you need it to work would be to use 8.

> I've also got Ammonite 2.2.0 installed, but I suspect you are embedding your own version.

So worksheets are actually powered by [mdoc](https://github.com/scalameta/mdoc), not Ammonite 😉

**Comment by jmcclell** [comment]
> So worksheets are actually powered by mdoc, not Ammonite 😉

Oh, neat. I assumed there was some connection to Ammonite because of things like `import $ivy` which I assumed were pure Ammonite inventions. :)

Thanks for looking into it and for pointing me to a workaround. Much appreciated.

**Comment by smarter** [comment]
> Ah, ok I was able to reproduce it. Java.sql.Connection should be there in 11 though according to the Java api. I'll have to dig a bit more into this situation to see what's going on.

You need to make sure that your classloader has the system classloader as a parent, see https://github.com/lampepfl/dotty/pull/11658/commits/178045e2c9e6cbc5ae894bd2d2acc82b6699ad36

**Comment by smarter** [comment]
err, actually you want the parent of the system classloader to avoid classpath pollution: https://github.com/lampepfl/dotty/pull/11658
