### ISSUE TITLE
DownloadDependencies fails when trying to download scala3-library_0.27

### ISSUE THREAD

**Issue by sideeffffect** [scalameta/metals#2201]
```
https://repo1.maven.org/maven2/org/scala-lang/scala3-library_0.27/0.27.0-RC1/scala3-library_0.27-0.27.0-RC1.pom
```
doesn't exist.

In the PR https://github.com/che-dockerfiles/che-sidecar-scala/pull/9 , logs: https://github.com/che-dockerfiles/che-sidecar-scala/pull/9/checks?check_run_id=1381752614#step:4:747

The command that causes it
```bash
METALS_VERSION="0.9.5"
...
coursier launch -r sonatype:snapshots org.scalameta:metals_2.12:$METALS_VERSION --main scala.meta.metals.DownloadDependencies
```

**Comment by ckipp01** [comment]
Thanks for reporting this @sideeffffect! I see where we went wrong.... We should be trying to pull 0.27 from org.scala-lang but rather dotty-library-*. I'll push up a fix for this in a bit.
