### ISSUE TITLE
Move .compilerconfig files to .metals/

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#222]
Currently, `*.compilerconfig` files are generated in `target/<projectname>.compilerconfig` with different `target/` for each project/configuration combination. This has the downside that

* `sbt clean` removes the config files, requring users to re-run `metalsSetup`
* it's sbt specific
* we use an esoteric file extension (.compilerconfig) to simplify file watching pattern

I propose we generate metadata files instead in the `.metals/` folder in the workspace root.

* `.metals/config/<project-name>.properties`
* remove `.metals/config/` folder on `metalsSetup` re-run to avoid stale files
* use standard .properties file extension to clearly communicate the format
* `sbt clean` does not require users to re-run `metalsSetup`

**Comment by olafurpg** [comment]
I took a stab at this here https://github.com/scalameta/metals/compare/master...olafurpg:properties?expand=1 It's mostly working but I can't seem to make goto definition in classpath work when testing manually.

This was a fairly tricky change since it required touch several different pieces. It shows that quick and dirty implementation tend to live longer than you expect them to.

**Comment by laughedelic** [comment]
@olafurpg could you submit a PR with what you have? let me know if you want any help with this. It changes the plugin code, so #219 depends on it.

**Comment by olafurpg** [comment]
@laughedelic I opened https://github.com/scalameta/metals/pull/229 as a WIP, still need more work to make sure all tests still pass.

**Comment by olafurpg** [comment]
I don't expect any more changes in MetalsPlugin.scala so you can base your work on top of that if you want :)

**Comment by laughedelic** [comment]
Cool, thanks!

**Comment by gabro** [comment]
Closed by #229
