### ISSUE TITLE
sbt-metals should not use semanticdb on scala 2.10 project

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#2250]
**Describe the bug**

I cannot import a project that is cross-built on Scala 2.10.7 because of the semanticdb plugin that is added by `sbt-metals`:
```
sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.10.7:4.3.24
```

**To Reproduce**

1. Create a Scala 2.10 project in sbt
2. Import in Metals using sbt

**Expected behavior**

sbt-metals should not try to activate the smenanticdb plugin when Scala < 2.11

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.9.5

**Search terms**

sbt, semanticdb, 2.10

**Comment by ckipp01** [comment]
Thanks for pointing this out @adpi2! This should be easy enough to fix. Although _technically_ Metals doesn't support 2.10. However, again, it should be easy to fix, so might as well.

**Comment by ckipp01** [comment]
So unless I'm missing something very obvious, this seems to be a bit trickier than I first thought. @adpi2 do you have any insight in the best way to do this in the [actual plugin](https://github.com/scalameta/metals/blob/main/sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala). Basically if a user is using sbt BSP it currently has nothing to do with the actual version of Scala they are on, we simply place the plugin. So even as you mentioned in cross-building they are going to have an issue. sbt plugins still confuse me, is there a way to just disable everything in the plugin dynamically for a specific Scala version?

**Comment by adpi2** [comment]
Hello!

> is there a way to just disable everything in the plugin dynamically for a specific Scala version?

Unfortunately I don't know how to do this and I doubt there is an easy way.

I suggest to use the following pattern:
```scala
scalacOptions := {
  if (doesSupportSemanticdb(scalaVersion.value)) {
    ???
  } else scalacOptions.value
}
```

Where `doesSupportSemanticdb` is very strict on the Scala version. 
It should return true on all of the folllowing but no other one:
  - 2.13.4
  - 2.13.3
  - 2.13.2
  - 2.13.1
  - 2.13.0
  - 2.12.12
  - 2.12.11
  - 2.12.10
  - 2.12.9
  - 2.12.8
  - 2.11.12

I am having a similar issue on a nightly build of Scala 2: 
```
sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.4-bin-8891679:4.4.0
```

**Comment by adpi2** [comment]
Thanks @ckipp01!
