### ISSUE TITLE
Metals.sbt is not getting created

### ISSUE THREAD

**Issue by domaspoliakas** [scalameta/metals#2255]
**Describe the bug**

`metals.sbt` file does not get created when using vscode remotely from windows to ubuntu. 

**To Reproduce**

1. Create a project on a ubuntu machine
2. Open VSCode on a windows machine
3. Connect to the ubuntu machine
3. Open new project
4. Click `Import build`
5. The import fails; no `metals.sbt` file is present in `project`

**Expected behavior**

`metals.sbt` file is created. 

**Screenshots**

**Installation:**

- Operating system: Ubuntu 19.10 and Windows 10 (connected via ssh) 
- Editor: Visual Studio Code
- Metals version: v0.9.6

**Additional context**

When the `metals.sbt` file is created manually everything seems to work correctly. 

The project we use is absolute barebones.

`build.sbt`:
```scala
name := "test"
```

`project/build.properties`
```
sbt.version=1.4.2
```

`src/main/scala/test/Test.scala`
```scala
package test
object Test extends App {
  println("Hello")
}
```

**Search terms**

Windows, Ubuntu, Visual Studio Code, ssh

**Comment by tgodzik** [comment]
Thanks for reporting! Does this only work when running via SSH? Does it work locally? There should really be  no difference there :thinking:

**Comment by domaspoliakas** [comment]
I tried to set up the ubuntu machine with coc-metals and that worked normally. Unfortunately this is not on my machine so I can't do more tests right now, but I'll check out if it works on a purely local (i.e. on the windows machine) project tomorrow.

**Comment by domaspoliakas** [comment]
Just tried it out using a fresh local project same as in the ticket on the windows machine, and it appears that no metals.sbt got generated on local as well.

**Comment by tgodzik** [comment]
That us super weird, I will try to reproduce on a windows machine to see what's going on.

**Comment by domaspoliakas** [comment]
I no longer have access to the machine that was suffering from this issue, so I will close this issue
