### ISSUE TITLE
Unable to use grouped imports in Scala 3 worksheets

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2256]
**Describe the bug**

Using a grouped import in a Scala 3 worksheet gives you an error.

**To Reproduce**

1. Create a Scala 3 workspace
2. Create a worksheet next to your source code
3. Try to add `import java.nio.file.{Files, Paths}`

You'll see the following error message

```
[mdoc] [E] '}' expected, but 'end of statement' found
```
**Expected behavior**

I'd expect this to work

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code and Vim
- Metals version: v0.9.6

**Search terms**

Scala 3 worksheets

**Comment by tgodzik** [comment]
Thanks for reporting! It seems that the parser positions stop at the end of Paths instead of at `}`. We can try to fix it in the Dotty parser or wait until use scalameta inside mdoc.

**Comment by ckipp01** [comment]
> We can try to fix it in the Dotty parser or wait until use scalameta inside mdoc.

If possible my vote would be to fix the parser.

**Comment by tgodzik** [comment]
> > We can try to fix it in the Dotty parser or wait until use scalameta inside mdoc.
> 
> If possible my vote would be to fix the parser.

hah! I will need to finally delve into the depths of the compiler.

**Comment by tgodzik** [comment]
We will need to migrate to scalameta parser anyway to migrate mdoc, but fixing it in the parser is something we should do anyway.

**Comment by ckipp01** [comment]
> We will need to migrate to scalameta parser anyway to migrate mdoc, but fixing it in the parser is something we should do anyway.

Yea, that was my thought exactly. We will migrate, but this should still probably be fixed. :)

**Comment by ckipp01** [comment]
So I believe this has been fixed with the later versions of mdoc. Trying this out now with the latest Metals snapshot in Scala 3 there is no issues. I'll go ahead and close this now.
