### ISSUE TITLE
Standalone worksheet goto definition not working on Scala sources

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2266]
**Describe the bug**

I think we are hitting on the exact same thing we fixed for Java in https://github.com/scalameta/metals/pull/2133, but for Scala. I'm not really sure why I didn't add a test also testing this for Scala, seems silly looking back. However giving the following code:

```scala
val a: List[Int] = List.fi@@ll(2)(2)
```

**To Reproduce**

1. Create a standalone worksheet
2. Paste in the code above
3. Try to navigate to `fill`
4. See that no definition can be found

**Expected behavior**

Brings you to the definition of `fill` in `GenTraversableFactory.scala`

**Installation:**

- Operating system: macOS
- Editor: Vim
- Metals version: v0.9.

**Search terms**

standalone  worksheets

**Comment by tgodzik** [comment]
Thanks for finding this! This should be easily fixable in the StandaloneSymbolSearch class. We might check if the Scala sources are available in the list of sources and if not download them.
