### ISSUE TITLE
Rename sbt.enabled to sbt.diagnostics.enabled

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#228]
For consistency with `scalac.diagnostics.enabled`, we should use `sbt.diagnostics.enabled`

**Comment by gabro** [comment]
Unless we mean something different. Does `sbt.enabled` also disable batch compilation on save?

**Comment by laughedelic** [comment]
This is a good idea. One may want to turn off the diagnostics from sbt, but still run some custom task/command on save. There is already `sbt.command` which could be turned off when it's an empty string.

**Comment by olafurpg** [comment]
I can imagine setting `sbt.command` to empty while keeping `diagnostics.enabled`.

**Comment by laughedelic** [comment]
Why? If sbt doesn't compile anything, it's not going to send any diagnostics. You can call `~compile` in the sbt shell manually of course, but again, why?

**Comment by olafurpg** [comment]
I think sbt sends diagnostics if I have `~core/test` in the shell. I personally might prefer `~test` since it makes it easy to change the exact command that is run on file save.

**Comment by laughedelic** [comment]
I see. I'm not sure though that it's an intended behaviour. I would expect that sbt shouldn't "broadcast" diagnostics to all clients when only one wants to compile.

**Comment by olafurpg** [comment]
Last time I tried it did broadcast all diagnostics, not sure if it's intended or not but I think it's useful.

**Comment by gabro** [comment]
I would probably have

```
sbt.enabled             # disable the integration entirely (won't try to connect and could even remove the "Sbt Connect" command on the client)
sbt.diagnostics.enable  # enable/disable diagnostics forwarding from sbt
sbt.command             # run command on save
```
