### ISSUE TITLE
Match completion not available for Scala3

### ISSUE THREAD

**Issue by asakaev** [scalameta/metals#2284]
Unable to use match completion. There is no match or exhaustive match helpers and so no generation. Maybe I just overlook to set up something or install extra extensions?

- Operating system: macOS 10.15.7
- Editor: Visual Studio Code 1.51.1
- Metals version: v0.9.7
- Metals extension v1.9.9

sbt 1.4.4 using BSP
scala 3.0.0-M2

Related:
https://github.com/scalameta/metals/pull/643

**Comment by tanishiking** [comment]
@asakaev Unfortunately, match completion is not yet available in scala3.

**Comment by tgodzik** [comment]
Thanks for reporting! @tanishiking is correct, we only have basic completions currently. I plan to work on it myself soon, but for now there is a feature request you can subscribe to: https://github.com/scalameta/metals-feature-requests/issues/112
