### ISSUE TITLE
Add a section to the docs that show all code actions

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2296]
There isn't currently a great way to know what code actions exist in Metals apart from looking in the source. I think it'd be a great idea to have a small section in the docs highlighting the code actions that Metals supports. As we continue to add in more refactoring related actions, it may be wise to have a centralized place to show those. It seems to be a somewhat common questions asked of Metals, _What refactoring support does Metals have?_

**Comment by tgodzik** [comment]
Good idea! We could also gather all we know that are not supported. It would be nice to have it in one place.

**Comment by kpodsiad** [comment]
Small description + GIF will be good enough?

**Comment by vzmerr** [comment]
Do you think the gifs should just cover the simplest scenario to convey the message, or be a mixture of multiple usage scenarios?

**Comment by tgodzik** [comment]
I think it should be a simple scenario to show case the exact purpose of the code action. Otherwise, it might get a bit too complex to get the main purpose behind it.
