### ISSUE TITLE
Plugin shows bubble to create .scalafmt.conf but doesn't create on 

### ISSUE THREAD

**Issue by abhishekvaid** [scalameta/metals#2329]
While saving if format on save is enabled, then metals balloon pops up asking giving an option to create scalafmt. But when you click on create a new .scalafmt.conf it doesn't create one. This process repeats every time you try to create a project. 

**To Reproduce**

Make a new SBT project from this build.sbt https://github.com/sysgears/scala-graphql-api-example/blob/master/build.sbt

**Comment by ckipp01** [comment]
Thanks for the report @abhishekvaid, but please stick to the issue template as it helps us help you troubleshoot. What editor are you using Metals with? What version of Metals are you using? Does this happen in all of your projects when you attempt to format without a `.scalafmt.conf` file?

**Comment by tgodzik** [comment]
Let's reopen this if we get more information.
