### ISSUE TITLE
MethodNotFoundError in worksheet when using latest Scalameta release

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#2337]
**Describe the bug**

The following worksheet crashes

```
import $ivy.`org.scalameta::scalameta:4.4.3`
import scala.meta._

implicit val D = dialects.Scala3

"""
extension (a: Int) def add = a
""".parse[Stat].get

"""
extension (a: Int) def add = a
""".parse[Stat]

```

The `implicit val D` line has the following error
```
java.lang.NoSuchMethodError: scala.meta.dialects.package$.Scala3()Lscala/meta/Dialect;
	at repl.MdocSession$App.<init>(Gitignored.worksheet.sc:11)
	at repl.MdocSession$.app(Gitignored.worksheet.sc:3)
```

**Expected behavior**

I expected the program to succeed because `dialects.Scala3` is available in the 4.4.3 release.

**Screenshots**

<img width="690" alt="Screenshot 2020-12-21 at 13 11 19" src="https://user-images.githubusercontent.com/1408093/102776027-4fe8b580-438e-11eb-8ffc-33ec84b6b38f.png">

**Additional context**

* Similar issue https://github.com/scalameta/metals/pull/2336
* The version of Scalameta that is used by Metals is older (4.4.2) where the `Scala3` dialect does not exist. This shouldn't be an issue because the user classloader should be isolated from the Metals classloader.

**Search terms**

**Comment by tgodzik** [comment]
I think this might actually be needed to be fixed in mdoc. Metals does not add anything to the classpath itself and the classloader is totally separate to the Metals one.

**Comment by tgodzik** [comment]
Just checked and it seems that the issue was the same as with https://github.com/scalameta/metals/issues/2525

The classloader used when running was the default one instead of one with the proper classpath.
