### ISSUE TITLE
Run | debug prompts appears out of position

### ISSUE THREAD

**Issue by megri** [scalameta/metals#2338]
**Describe the bug**
With the latest version of metals/VSCode I'm experiencing some issues with the `run | debug` hovers over class entrypoints. Basically the run | debug prompts appears out of position. Adding a blank line and saving repositions the prompts and sometimes they end up in the right position.

This happens with at least scala 3.0.0-M3.

**Note**
This seems to only happen when using Bloop 1.4.6. With Bloop 1.4.5 the prompts are stable

**To Reproduce**

1. Create a new scala file
2. create at least two entrypoints using `@main` annotation
3. edit code, save and wait for the run/debug prompts to appear

**Screenshots**
![image](https://user-images.githubusercontent.com/1839427/102805046-f0ed6580-43ba-11eb-8c03-7c9533920a06.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.8

**Additional context**
Build tool: mill 0.9.3/0.9.4

**Search terms**
run
debug
prompt
main

**Comment by tgodzik** [comment]
Thanks for reporting! I think that might have something to do with incremental compilation issues we've seen. I can reproduce it by adding a single method before the main and then saving again it goes back into the correct place.

**Comment by tgodzik** [comment]
Just confirmed, we are getting wrong positions for semanticdb files without any reason. Opened an issue in Scala 3:

https://github.com/lampepfl/dotty/issues/10885

**Comment by tgodzik** [comment]
It's actually fixed in 3.0.0-RC1 :tada: 

I will close it unless anyone still encounters this - then do let me know!

**Comment by megri** [comment]
I'm still seeing this unfortunately.
![image](https://user-images.githubusercontent.com/1839427/109046023-959a6500-76d4-11eb-9fa4-b4bb5095c13f.png)

**Comment by megri** [comment]
I *believe* this is fixed with release 0.10.1. At least the nightlies prior seemed to work well :)

**Comment by tgodzik** [comment]
> I _believe_ this is fixed with release 0.10.1. At least the nightlies prior seemed to work well :)

Cool! Let's close it then!
