### ISSUE TITLE
Metals still offers completion snippets when `snippetSupport` is set to false.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2343]
**Describe the bug**

When using an LSP client that passes in that it doesn't have snippet support via `CompletionClientCapabilities`, it still offers completions with snippets. For example, here is the relevant part of an initialize request that has this set to false:

```json
...
    "textDocument": {
      "synchronization": {
        "willSave": false,
        "willSaveWaitUntil": false,
        "didSave": true,
        "dynamicRegistration": false
      },
      "completion": {
        "completionItem": {
          "snippetSupport": false,
          "commitCharactersSupport": false,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "deprecatedSupport": false,
          "preselectSupport": false
        },
...
```

With `snippetSupport` set to `false` I wouldn't expect completions to be returned that contain snippets. Now if I try to complete `Instant.no@@`, here are the completion items I receive:

```json
[Trace - 00:18:59 PM] Sending response 'textDocument/completion - (2)'. Processing request took 251ms
Result: {
  "isIncomplete": false,
  "items": [
    {
      "label": "now(): Instant",
      "kind": 8,
      "detail": "(): Instant",
      "preselect": true,
      "sortText": "00000",
      "filterText": "now",
      "insertTextFormat": 1,
      "textEdit": {
        "range": {
          "start": {
            "line": 8,
            "character": 10
          },
          "end": {
            "line": 8,
            "character": 13
          }
        },
        "newText": "now()"
      },
      "data": {
        "symbol": "java/time/Instant#now().",
        "target": "file:/Users/ckipp/Documents/scala-workspace/tester/?id\u003droot"
      }
    },
    {
      "label": "now(x$1: Clock): Instant",
      "kind": 8,
      "detail": "(x$1: Clock): Instant",
      "sortText": "00001",
      "filterText": "now",
      "insertTextFormat": 1,
      "textEdit": {
        "range": {
          "start": {
            "line": 8,
            "character": 10
          },
          "end": {
            "line": 8,
            "character": 13
          }
        },
        "newText": "now"
      },
      "data": {
        "symbol": "java/time/Instant#now(+1).",
        "target": "file:/Users/ckipp/Documents/scala-workspace/tester/?id\u003droot"
      }
    }
  ]
}
```

**To Reproduce**

1. Use a client that sets `snippetSupport` to false. In my case this was while using `nvim-metals`.
2. Attempt the completion from up above
3. See snippet being offered.

**Expected behavior**

I'd expect no snippets in this scenario since if one is offered, the client won't be able to handle it correctly.

**Installation:**

- Operating system: macOS
- Editor: nvim
- Metals version: v0.9.8

**Search terms**

snippet support

**Comment by gabro** [comment]
Ah, strange. I'm pretty sure I've worked on the same issue in the past and there should be even a test suite for it 🤔

**Comment by gabro** [comment]
Wait, are you referring to the `x$1` in the method signature? Isn't that the default representation of Java parameters? I honestly don't remember, can you maybe try reproduce this with a Scala method?

**Comment by gabro** [comment]
Here's the relevant test suite by the way, if this is a bug it may be worth adding some test cases there https://github.com/scalameta/metals/blob/main/tests/cross/src/test/scala/tests/pc/CompletionSnippetNegSuite.scala

**Comment by ckipp01** [comment]
@gabro ugh, you're totally correct about it just being the method signature. I was so fixated on the $1 that I just assumed that it was a snippet without thinking much about it. Sorry for the noise 😬

**Comment by gabro** [comment]
Haha, I'm glad it wasn't a bug after all 😅
