### ISSUE TITLE
metals occasionally hangs and reports stale errors though sbt compiles fine

### ISSUE THREAD

**Issue by nkgm** [scalameta/metals#2348]
**Is your feature request related to a problem? Please describe.**
Autogenerated factory methods with long parameter lists with default values, where one has to invoke by use of named arguments.
Especially useful in scalajs facades where we tend to have long lists of properties with default values of `js.undefined`.

**Describe the solution you'd like**
When autocomplete is invoked within a method call's arguments, the named parameters should be listed. It that's too confusing to list along the other valid completions, maybe list them when the user types`=` as the first character of the argument if possible.

**Describe alternatives you've considered**
The only alternative at this moment is to depend on VSCode's generic text completion, which is pretty much useless. Another alternative is to look for the parameter in the method info popup, which for long lists with default arguments would require going through a long listing of unhighlighted text.

**Search terms**:
`autocomplete` `named arguments` `default parameter values`

**Comment by tanishiking** [comment]
I tried to reproduce in the following environment, but it works fine for me. Indeed, completion for args doesn't work if the args starts with `$` :) 
@nkgm Is my reproduction environment the same as yours? If not, is it possible to give us a minimum reproducible environment? 

<details>
<summary>Click here to show my environment</summary>

metals version: 0.9.8

```scala
// project/build.properties
sbt.version=1.4.4
```

```scala
// project/plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.3.1")
```

```scala
// build.sbt
scalaVersion := "2.13.3"
name := "scalajs-playground"
organization := "com.github.tanishiking"
version := "1.0"

enablePlugins(ScalaJSPlugin)
scalaJSUseMainModuleInitializer := true
```

```scala
// src/main/scala/Main.scala
import scala.scalajs.js

object Main {
  def main(args: Array[String]): Unit = {

  }

  def createPerson(
      name: js.UndefOr[String] = js.undefined,
      age: js.UndefOr[Int] = js.undefined
  ): Person = {
    Person(
      name.toOption,
      age.toOption
    )
  }

  case class Person(
      name: Option[String],
      age: Option[Int]
  )
}
```

</details>

![scalajs](https://user-images.githubusercontent.com/9353584/103442878-36ecd800-4c9d-11eb-8cb0-b84021f8f91d.gif)

**Comment by nkgm** [comment]
Thanks so much for taking the time to check and provide the gif capture. 
Indeed your example works in a new project, and even in the one I'm currently working on, but not with `$` just like you said. 
Not sure why it appeared not to work while drafting the issue - I always double-check code snippets before submitting. I did notice that sometimes code completion "chokes" and only gives `abc` suggestions, even though code compiles without errors (both metals and sbt.)

More importantly though, I replaced the `$` prefix with a letter, and it still doesn't seem to work for my macro generated factory object. It's a whitebox macro that instantiates and returns an anonymous class that is visible as a structural type at the call-site, compacted with long autogenerated method signatures. I can provide a working example if you'd be so keen to have a look :)

**Comment by tgodzik** [comment]
Do you have any logs when this happens? Did you see that the code actually compiled? When Bloop finishes compilation it should notify Metals and we restart the presentation compiler then. If it doesn't work it might be a number of issues related to Metals, Scala presentation compiler or Bloop, so it would be good ideally to have a reproduction or at least as much data as you can provide.

**Comment by tgodzik** [comment]
For example if it happens on a particular project it would be awesome to take a look at it if it's possible or a small excerpt otherwise.

**Comment by nkgm** [comment]
Been keeping an eye on the logs trying to isolate the issue. Unfortunately it's still very vague. It would appear that at certain points `metals` just hangs. Here is an example screenshot where a stale error is being reported by `metals` (squiggly lines in editor, and respective entry in Problems tab), even though it compiles fine with `sbt`:

![image](https://user-images.githubusercontent.com/5631881/104898870-d0e19f80-5982-11eb-9f0b-fc2a495deb67.png)

You'll notice that the compilation took place at `11:35:13`. Looking at the `metals.log` however, there is a gap from `11:29:27` to `11:47:19`:

![image](https://user-images.githubusercontent.com/5631881/104900491-c7f1cd80-5984-11eb-96df-e18f07aa568e.png)

And that's when presentation was restored (I didn't actually do anything other that moving back and forth between Chrome and VSCode while creating this issue).

I can't release the actual project I'm working on but I could create a dummy one. Please note however, that the issue happens mostly random so I'm not in a position to provide steps to reproduce just yet. I'm more than happy to do some more filtering if you'd be so kind to give me a few pointers.

**Comment by ckipp01** [comment]
🤔 so it's a bit tricky by the logs to tell what's going on mainly because I'm curious if Bloop reported the issues and they hung in Metals, or if Metals was stuck waiting for Bloop in this scenario. It'd be interesting to see if this happens again, to try and run `bloop compile <project.` while it's hanging to see if bloop compiles it right away, or for some reason it just hangs. If it does compile right away, then we know it's an issue inside Metals, but if it's hung waiting for Bloop, then it may help to point that the issue is there.

**Comment by tanishiking** [comment]
The approach @ckipp01 will be a good idea to check what's going on 👍 

By the way, It might be better to rename this issue, and separate "autocompletion for named method arguments not working for the args starts with $" topic to another issue.

**Comment by tanishiking** [comment]
I took the liberty of renaming the issue and separating the named arg completion issue to https://github.com/scalameta/metals/issues/2400
If you have a better issue title, feel free to edit the title :)

**Comment by tgodzik** [comment]
I think I've seen a situation like this - metals hanging and not sending messages - but I did not have time to debug it then. My best guess is that the JVM is stuck on something either due to memory leak (running GC all the time) or  scalameta parser when `parent code lenses` are turned on. Could you also try to see if there is anything going in the background when metals hangs? Or it would be awesome if you could provide a staktrace using `jstack` for the JVM running Metals. It might also be Bloop issue, but I think may be rather on the Metals side if no logs were printed.

Let me know if you need any help in figuring out how to run `jstack`
