### ISSUE TITLE
How to configure scala version for worksheet evaluation

### ISSUE THREAD

**Issue by zyxue** [scalameta/metals#2366]
My system has scala 2.13.4:

```
$ type -a scala
scala is an alias for scala -feature
scala is /usr/local/bin/scala

$ scala --version
Scala code runner version 2.13.4 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.
```

But somehow vscode uses a version 2.12.12 when evaluating worksheet, how do I configure scala with vscode + metal?
![image](https://user-images.githubusercontent.com/527862/103585650-4ab05e00-4e98-11eb-93ff-6f387901bc4b.png)

**Comment by tgodzik** [comment]
I will close this for now. Please don't hesitate to ask any questions if anything is not clear, you can use the `Discussions` tab in this repo.
