### ISSUE TITLE
Update documentation for 0.1.0 release

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#237]
We need to update our documentation (BETA.md and CONTRIBUTING.md) when we publish 0.1.0, since some steps will be greatly simplified (e.g. one can develop on the server without building the vscode extension locally)

I'll put this here as a reminder.

* Scala version requirements: 2.12
* sbt-errors-summary does not work with sbt integration

**Comment by laughedelic** [comment]
Done in #254
