### ISSUE TITLE
Missing valid bloop build in Emacs

### ISSUE THREAD

**Issue by ashkan-leo** [scalameta/metals#2373]
**Describe the bug**

When I open my project in Emacs, I get the "missing valid bloop build". None of the functionalities work.

**To Reproduce**

1. Open a scala project in Emacs
2. Do "build-import"
3. Observer the error

**Expected behavior**

Metals should work

**Screenshots**

<img width="1062" alt="Screen Shot 2021-01-11 at 12 10 14 PM" src="https://user-images.githubusercontent.com/10341965/104222739-52c44c80-5408-11eb-8065-1ae94b8de90f.png">
<img width="790" alt="Screen Shot 2021-01-11 at 12 07 58 PM" src="https://user-images.githubusercontent.com/10341965/104222740-548e1000-5408-11eb-9f68-af3834a83e44.png">

**Installation:**

- Operating system: macOS
- Editor: Emacs
- Metals version: 0.9.8+56-b75a7a88-SNAPSHOT

**Additional context**

I have been experiencing difficulties with metals for a few months now. My setup broke back in October (https://github.com/scalameta/metals/issues/2167) and I haven't been able to use metals since then. Any help is appreciated!

**Comment by ckipp01** [comment]
@ashkan-leo does this happen for you on any project, or just this specific one? From could you test to see if on a fresh project you are also having issues? Also, are you able to provide a bit more about this project as the Doctor recommendation points towards you using a pretty old version of sbt.

**Comment by tgodzik** [comment]
Thanks for reporting! This looks like there is a `.bloop` directory inside `project` directory, which was generated by an older sbt version. This should not be a problem when it comes to the normal sourcecode itself. Did the build import run successfully? There is no `.bloop` directory, so it looks like it didn't. What do you get in `.metals/metals/log` when running  build import?

**Comment by ashkan-leo** [comment]
Thanks for the tips.
I was able to figure out what the problem was. `global.sbt` contained some bad code and was causing the build to fail.
Now, the import finishes successfully and doctor-run doesn't show any issue.
However, I still don't get any completion when writing the code. The goto definition works, and the types are shown in Emacs minibuffer though.

**Comment by tgodzik** [comment]
If go to definition works then completions should 99% also work. Is anything shown in `.metals/metals.log` ? You could also try to check if any actual requests are being made by creating the file:

`touch -f ~/Library/Caches/org.scalameta.metals/lsp.trace.json`

It will log any request being made to metals. If there is nothing in the  `metals.log` and no completion requests being made in the `lsp.trace.json` file the most likely the issue lies on the emacs side. I am not sure how exactly emacs lsp works, but it might be the issue there? Could you try asking on emacs-lsp/lsp-mode gitter about completions?

**Comment by ashkan-leo** [comment]
Thanks @tgodzik. Do I need to enable any option in Emacs or metals in order to see the logs in `lsp.trace.json`? It remains empty when I call completion or go to a definition, etc.

**Comment by tgodzik** [comment]
You might need to restart the server for it to see it. If the file exists Metals will register any request that it gets, so it should get full with different RPC messages.  So if nothing is seen there it might be an issue with Emacs configuration? Is there anything in `metals.log`?

**Comment by ckipp01** [comment]
@ashkan-leo any update here? Can we assume that the issue has been fixed?

**Comment by ashkan-leo** [comment]
I was able to setup a project on one my laptops but the other still not working. This suggests the issue is because of the underlying system, but I can't pin point what exactly is causing this.
Let's keep this ticket open for a few more days to see if I can fix my other computer.
Thanks!

**Comment by tgodzik** [comment]
Let's close it for now, let us know if you need any additional help.
