### ISSUE TITLE
Creating new scala file doesn't escape keywords in package statement

### ISSUE THREAD

**Issue by nMoncho** [scalameta/metals#2375]
**Describe the bug**
When creating a new Scala file, if the folder in the package path contains a reserved keyword, such as `type`, the package statement won't escape that keyword.

**To Reproduce**

1. Open Scala project in VS Code
2. Create new folder at any level inside either `src/main` or `src/test`, with the name **type**
3. Create any Scala file inside that folder
4. Package declaration includes keyword without backticks.

**Expected behavior**

Package declaration should escape reserved keywords. E.g. if the new Scala file is created inside the folder path `src/main/com/example/type` then the package declaration should be ```package com.example.`type` ```

**Screenshots**

<img width="1680" alt="Screenshot 2021-01-12 at 19 26 34" src="https://user-images.githubusercontent.com/1565948/104356361-2691f400-550c-11eb-97e3-44efec45101e.png">

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.8

**Comment by ckipp01** [comment]
Thanks for the report @nMoncho! I can reproduce this locally, and from what I can tell we just don't do any checking for reserved keywords when creating the package. We should be able to fix this 👍🏼
