### ISSUE TITLE
NPE thrown when `rootUri` in `initialize` is null.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2384]
### Taken from discussions

So this seems to be a problem:
`workspace = AbsolutePath(Paths.get(URI.create(params.getRootUri))).dealias`

and `params.getRootUri` seems to be null?

_Originally posted by @tgodzik in https://github.com/scalameta/metals/discussions/2379#discussioncomment-281741_

### Description

So looking into this a bit more, I think we obviously need to address the NPE, but also think a bit about what should actually happen in the situation where `null` is given here. With Metals, there is a lot that rides on that being set, since it's what we use to define the `workspace` in the server. Then that's passed all around, the providers are created based of it, etc. In reality, if that's not set, then there are quite a few providers that may not make a bunch of sense to even make. For example, the `WorkspaceReload` wouldn't make any sense.

Grabbing some relevant stuff from the spec:

```
/**
	 * The rootPath of the workspace. Is null
	 * if no folder is open.
	 *
	 * @deprecated in favour of `rootUri`.
	 */
	rootPath?: string | null;

	/**
	 * The rootUri of the workspace. Is null if no
	 * folder is open. If both `rootPath` and `rootUri` are set
	 * `rootUri` wins.
	 *
	 * @deprecated in favour of `workspaceFolders`
	 */
	rootUri: DocumentUri | null;

	/**
	 * The workspace folders configured in the client when the server starts.
	 * This property is only available if the client supports workspace folders.
	 * It can be `null` if the client supports workspace folders but none are
	 * configured.
	 *
	 * @since 3.6.0
	 */
	workspaceFolders?: WorkspaceFolder[] | null;
``` 

Ultimately it looks like `workspaceFolders` is the only non-deprecated way to do this, but we should possible look for all 3. However, this begs the question, in what scenario should Metals really be triggered to start with all 3 of these being `null`? Even if we open a single Scala file, that can still be give as the root. I need to look a bit closer at the thread to see what was going on with Sublime, but I'm still a bit confused why Metals was even being triggered if nothing at all was open. If something was open, then the issue may actually lie with how Sublime is setting these values. Again, that doesn't excuse the NPE.

My main concern is that I don't want to do a large refactoring to account for `null` here if that literally _should_ never be the case. If it truly shouldn't be the case, we can even just do nothing and issue a warning.

**Comment by ckipp01** [comment]
So digging a bit further in to the situation in https://github.com/scalameta/metals/discussions/2379#discussioncomment-281708, all three mentioned above, `rootUri`, `workspaceFolders`, and `rootPather` were marked as `None`. So in that situation, if that's the case, what's the most reasonable thing for Metals to do if there is no workspace root that we have to work with?

**Comment by ayoub-benali** [comment]
If there is nothing for Metals to work with, just throwing a better exception is enough to debug this kind of issues ?

**Comment by ckipp01** [comment]
> If there is nothing for Metals to work with, just throwing a better exception is enough to debug this kind of issues ?

O, absolutely. Without a doubt, we can for sure give a better message in this scenario and not explode.

**Comment by ckipp01** [comment]
Closed with https://github.com/scalameta/metals/pull/2391

While we don't 100% fix the issue where no workspace is provided, we do avoid throwing a NPE and show a message now.
