### ISSUE TITLE
Update ammonite for 2.13.5

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#2392]
Currently we test Ammonite support on 2.12.12, but as soon as it's available for 2.12.13, we should switch.

Once we do it we should:
- move Ammonite212 suite back to unit tests and set V.scala212 version
- remove `2.12.12` from `publishAllMtags` invocation in `build.sbt`

**Comment by alexarchambault** [comment]
Ammonite for `2.12.13` has just been [published](https://repo1.maven.org/maven2/com/lihaoyi/ammonite-interp_2.12.13/2.3.8-32-64308dc3) (it should have been published earlier, something went wrong in its release jobs…).

**Comment by tgodzik** [comment]
Awesome, thanks! I will update the PR then.

**Comment by tgodzik** [comment]
2.12.13 is now supported, but we now are missing 2.13.5, which is not yet released.
