### ISSUE TITLE
Document VS Code client build dependencies

### ISSUE THREAD

**Issue by martijnhoekstra** [scalameta/metals#240]
The client build uses curl to fetch coursier. It would be nice if this dependency (which isn't a given on Windows) could be shed, or at least documented.

**Comment by olafurpg** [comment]
The VS Code client should be able to work without curl once it's on marketplace. Installation documentation is already tracked in #237. Does it make sense to replace this ticket with "Make VS Code plugin not depend on curl"?

**Comment by gabro** [comment]
To further clarify: the VSCode client **ships** with a coursier binary.

The `download-coursier` npm script is used during the extension bundling to get a fresh version of coursier.

To be honest, we could get rid of that script and just commit the binary in the repo.

**Comment by martijnhoekstra** [comment]
This ticket is about the build dependency only. I don't think (hope?) the VS Code client depends on curl; I'd have to check. Depending on your perspective and ticket management, this is a duplicate of #237 that can be closed, or a subitem to track individual items of that item.

I'm well aware of the impracticalities of supporting a portable build when you want to move fast, and certainly don't want to hold things up. But if none of the core developers are on Windows, it might be worth it to keep these tickets around, since if no core developers run in to the issue, it's easy to forget it exists, even if its fix is deferred to some undefined later point in time.

**Comment by olafurpg** [comment]
Is this only relevant when building the plugin locally? I propose we close it then or quickly commit the coursier binary into the repo.

**Comment by laughedelic** [comment]
Haha 😆 it's been added to the repo and removed twice already...

**Comment by olafurpg** [comment]
Running the CI on windows would nice, my experience is that it catches quite a lot of silly bugs related to URIs and file-paths that are easy to fix.  I'm fixing https://ci.appveyor.com/project/scalacenter/scalafix/build/170#L893 as we speak!

**Comment by gabro** [comment]
My fault, I guess :P Considering that we depend on an explicit version, let's just commit it and remove the curl-based script.

**Comment by olafurpg** [comment]
Can we refocus this ticket on making the build work on windows instead? @martijnhoekstra 
The best documentation IMO is a green CI for all supported platforms.

**Comment by gabro** [comment]
The CI currently doesn't even build the vscode extension on Travis, I think. I would consider that another ticket.

Fixing this one in #241. Curl is now only needed for the `start-server.sh` script, but not for building the vscode extension

**Comment by gabro** [comment]
Tracking the Windows thing in #242
