### ISSUE TITLE
"Debug test" cannot hit a break point defined in main source file

### ISSUE THREAD

**Issue by shaofengjiang** [scalameta/metals#2425]
**Describe the bug**

When I set a breakpoint in the main source file and run the unit test in the debugging mode (clicking "debug test"), the program only pauses in the unit test file and I cannot step into the source file. 

**To Reproduce** 

Attached bug.zip is a very simple project that can reproduce the issue, and the concrete steps go as follows.
[bug.zip](https://github.com/scalameta/metals-vscode/files/5858876/bug.zip)

1. Set a breakpoint at line 4 of myObject.scala.
2. Click "debug test" in myObject.test.scala.
3. The debugger pauses in myObject.test.scala instead of myObject.scala (where the breakpoint is set). Furthermore, in the call stack, myObject.doSomething(Seq) method is grayed, and it is marked as "Unknown Source" - this could be the reason that I cannot step into it.

**Expected behavior**

The debugger is expected to pause at the main source file where I set the breakpoint.

**Screenshots**

![image](https://user-images.githubusercontent.com/73434442/105553460-1c42d780-5d0e-11eb-9ce5-3b11b38f05b0.png)

**Installation:**

- Operating system: Windows 10 Pro 20H2
- VSCode version: 1.52.1
- VSCode extension version: 1.9.13
- Metals version: (found in VSCode settings, under `metals.serverVersion`) 0.9.10

**Additional context**

**Search terms**

debug, vscode, scala, breakpoint, cannot step into, unknown source

**Comment by shaofengjiang** [comment]
Thanks for the prompt reply.

However, I’m afraid the issue is only partially resolved – the latest snapshot version works on the bug.zip project, but it still doesn’t work if I add the main source in a package.

Please check the following slightly modified version of the project that can reproduce the bug.
[bug1.zip](https://github.com/scalameta/metals/files/5860899/bug1.zip)

To reproduce the bug, simply set a breakpoint at line 4 of myObject.scala and "debug test" myObject.test.scala.
![image](https://user-images.githubusercontent.com/73434442/105611803-34732f00-5dc0-11eb-94f7-48d9be330f64.png)

**Comment by tgodzik** [comment]
Ach, that is a related bug, fixing it here: https://github.com/scalameta/metals/pull/2427

**Comment by shaofengjiang** [comment]
Thank you very much! The latest snapshot version indeed solves the problem in my example.

**Unfortunately**, the debugger doesn't work if the project becomes only a little bit more complicated. In short, I created two subprojects, and if I set two breakpoints in each project, then "debug test" cannot hit any breakpoint at all. 

Again, I attach a minimal example that can reproduce the bug:
[bug2.zip](https://github.com/scalameta/metals/files/5865632/bug2.zip)

**To reproduce:**
1. Set one breakpoint at line 4 of subproj1/src/main/scala/myObject1.scala, and another breakpoint also at line 4 but at the other subproject subproj2/src/main/scala/myObject2.scala
2. "debug test" myObject1.test.scala at subproj1/src/test/scala, and you'll see no breakpoint is hit, while we expect the breakpoint in subproj1 should be hit.

**Note:** 
However, if we remove the breakpoint in subproj2, then testing on subproj1 works well (it has to be really "removed", and de-selecting it in the run & debug view still doesn't work.)

**Screenshot 1**: "debug test" does not pause at all if two breakpoints in each subproject are set.
![image](https://user-images.githubusercontent.com/73434442/105690235-67bed680-5f04-11eb-8922-d1c6fca29faf.png)

**Screenshot 2**: it works if we only have one breakpoint set.
![image](https://user-images.githubusercontent.com/73434442/105690349-8c1ab300-5f04-11eb-82ca-d3e67b4f771e.png)

**Comment by tgodzik** [comment]
Thanks for finding the edge cases! It's fine to create a new issue in a case like this, it will be easier to track it this way.

**Comment by shaofengjiang** [comment]
Thanks for the prompt reply. Yes, it makes sense to create a new issue for this, since it seems the issue is somewhat different from previous ones. Should I create a new issue, or you can help to create one?

**Comment by tgodzik** [comment]
No need in this case, I already have a fix ready. But for sure please create a new one for any future issues.

Anyway, it's really great that you keep finding these issues! Kudos for that!

**Comment by shaofengjiang** [comment]
Sure, I'll do that. Thank you for the always prompt fixes!
