### ISSUE TITLE
Misleading docs about system properties

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2439]
**Describe the bug**

It used to be that all of the new configuration added to metals also had a system property option. You can see them all on [the website here](https://scalameta.org/metals/docs/integrations/new-editor.html#metals-server-properties). However, new settings that are being added in `UserConfiguration` is still being pulled in and server property documentation for it is being made and published even though those options aren't valid. This can cause confusion. Sorry @ayoub-benali .

The issue is here:

https://github.com/scalameta/metals/blob/eed9660b66d58285106d51316a94fc8f0114902a/metals-docs/src/main/scala/docs/UserConfigurationModifier.scala#L19-L31

We should instead pull those from `MetalsServerConfig`.

**Search terms**

system properties

**Comment by ayoub-benali** [comment]
I believe [this](https://scalameta.org/metals/docs/integrations/decoration-protocol.html#initialize) section is also wrong. `decorationProvider` are part of the `initializationOptions`
