### ISSUE TITLE
null folder on Windows

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals#2451]
Doesn't seem intentional.
![image](https://user-images.githubusercontent.com/74843/106400508-64d05400-63e4-11eb-9bc0-b4795fe533f2.png)

**Comment by ckipp01** [comment]
Thanks for the report @nilskp!

So we use `sys.props("user.dir")` to grab the root of the path we put together to put the file that you're seeing in this image. Can you my chance even in a worksheet or something check what `sys.props("user.dir")` returns for you?

**Comment by ckipp01** [comment]
@nilskp are you able to drop this into a worksheet on your machine, and tell me what the result of the `cacheDir` is?

```scala
import dev.dirs.ProjectDirectories

import $dep.`dev.dirs:directories:23`

ProjectDirectories.from("org", "scalameta", "metals")
```

**Comment by snlykf** [comment]
Looks like an issue with Coursier that came up again with SBT 1.4.6: https://github.com/sbt/sbt/issues/5206

```
res0: ProjectDirectories = ProjectDirectories (Windows 10):
  projectPath   = 'scalameta\metals'
  cacheDir      = 'null\scalameta\metals\cache'
  configDir     = 'null\scalameta\metals\config'
  dataDir       = 'null\scalameta\metals\data'
  dataLocalDir  = 'null\scalameta\metals\data'
  preferenceDir = 'null\scalameta\metals\config'
  runtimeDir    = 'null'
```

Reverting back to SBT 1.4.5 fixes it for me.

**Comment by ckipp01** [comment]
🤔 honestly if that's happening, the core issue may lie with https://github.com/dirs-dev/directories-jvm. @snlykf are you able to take that output and report the issue in `dirs-dev` and we can further figure out exactly what's going on. I'm sort of assuming that this isn't actually something we can fix on the Metals side since we rely on that library to give us this info.

**Comment by nilskp** [comment]
@ckipp01 I don't usually use worksheets. Is there a way to show the output, other than hover?

![image](https://user-images.githubusercontent.com/74843/106470549-398e4900-6466-11eb-8cba-a5e2bd3399db.png)

**Comment by ckipp01** [comment]
> @ckipp01 I don't usually use worksheets. Is there a way to show the output, other than hover?

So the output that can fit right after will be displayed to the right, like you're seeing, but for longer output that won't all fit in a line or for like `println` and such you need to use the hover over the decoration to see the rest.

Also depending on what you're doing, there is also the `Metals: Copy Worksheet Output` command that will copy all the output, including the hover as comments under the line. So in this situation, it'd be quite useful to just use that command, and then simply paste the output. Ha, we actually added this feature for this exact scenario.

**Comment by nilskp** [comment]
@ckipp01 Ok, thanks :-)

It feels like there's a lot of "hidden" functionality that could be exposed better, through buttons and whatnot. Not sure how well VSCode supports that type of thing.

**Comment by ckipp01** [comment]
> @ckipp01 Ok, thanks :-)
> 
> It feels like there's a lot of "hidden" functionality that could be exposed better, through buttons and whatnot. Not sure how well VSCode supports that type of thing.

🤔 we can definitely put some thought into how we can maybe expose that better since I think it's a pretty great feature. I'm not a VS Code user, so I'm unsure what a logical place for a button or something would be for that. Please do offer suggestions if you have any.

**Comment by tgodzik** [comment]
There a buttons under the `Metals` view, but nothing for `Copy worksheet output` - it would probably be better to somehow attach that to the top of the worksheet file, but not sure if that is possible.

**Comment by snlykf** [comment]
Created https://github.com/dirs-dev/directories-jvm/issues/47

**Comment by nilskp** [comment]
> There a buttons under the `Metals` view, but nothing for `Copy worksheet output` - it would probably be better to somehow attach that to the top of the worksheet file, but not sure if that is possible.

Maybe as a lens?

**Comment by tgodzik** [comment]
Lens in a top of the file would work and would be supported in larger amount of clients, I think that's a good idea. @ckipp01  ?

**Comment by ckipp01** [comment]
Yea totally, we can see what it looks like to just put it at the top of the file 👍🏼

**Comment by tgodzik** [comment]
@nilskp I created PR to address it here: https://github.com/scalameta/metals/pull/2470

I think it looks pretty good with the code lens, thanks for the suggestion!

**Comment by ckipp01** [comment]
_Create a bug report... and you get a new feature!_

**Comment by NicolasRouquette** [comment]
As @snlykf mentioned, this issue came up in https://github.com/sbt/sbt/issues/5206 

The fix in sbt 1.5.0-RC1 suggests a workaround: https://github.com/sbt/sbt/pull/6408/files#diff-b0744394c88ee5abb7d269b218cd224d0b3cdaa6bcbdb3b51540918affeda17a: 

Set `COURSIER_CACHE` to the full path of a folder.

A relative path like `.coursier` will lead to errors attempting to create a `.coursier` folder in `C:\Program Files`.
An absolute path like `C:\Users\name\.coursier` works.

**Comment by alexarchambault** [comment]
A cleaner fix is on its way in coursier itself. It should be there in the next release.

**Comment by tgodzik** [comment]
Fixed by https://github.com/scalameta/metals/pull/2652 :tada:
