### ISSUE TITLE
Show hover in VS code is not shown at the end of a val

### ISSUE THREAD

**Issue by mbesida** [scalameta/metals#2471]
**Bug description**
**Show hover** action in VS code is not applied when the cursor is set right after a `val` name. 

**To Reproduce**
On the the screenshot I applied Show hover action when the cursor is on the `val`, and it works; Also this action works when the cursor is set in front of a `val`  name. But when I set cursor right after the `val` name (on the screenshot after the name `str1`)- it doesn't work. 
When a type is set explicitly (`val str2: String`) Show hover action is applied after the `str2` also, but only if semicolon is "attached" to a val name, but if it's not "attached"(`val str2 : String`) - the behavior is the same as without the explicit type

**Expected behavior**
As of my Intelij idea background Show hover should be applied no matter where tye cursor is. As type inference is heavily used in Scala this is extremely useful to see the derived types of an expressions

**Screenshots**
![image](https://user-images.githubusercontent.com/5313583/106664142-55503700-65ad-11eb-86f9-b6848cee088e.png)

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code with WSL2 Remote extension
- Metals version: v0.9.10
- VS code extension version(Scala(Metals)) : 1.9.13

**Additional context**

Show hover action can be applied by Ctrl+K Ctrl+I shortcut on Windows as of by default

**Comment by tgodzik** [comment]
Thanks for reporting! This is most likely a behaviour coming from the presentation compiler and we would need to most likely fix it there or work around in Metals.

**Comment by tgodzik** [comment]
Fixed in #5133
