### ISSUE TITLE
sbt bloopInstall fails with exit code

### ISSUE THREAD

**Issue by kcwill2** [scalameta/metals#2475]
**Describe the bug**

in the Metals build commands "Import Build" fails with the following output:

_Initializing Scala Debugger
2021.02.03 16:24:49 WARN  Build server is not auto-connectable.
2021.02.03 16:26:34 INFO  running 'java -jar C:\Code\sbt\bin\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2021.02.03 16:26:34 INFO  sbt bloopInstall exit: -2147483648_

**To Reproduce**

1. Click on "import build"

**Expected behavior**

the build imported from sbt

**Screenshots**

**Installation:**

- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.9.8
- SBT version is 1.2.8

**Additional context**
[metals.log](https://github.com/scalameta/metals/files/5922543/metals.log)

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like something is broken with the path to sbt maybe? Did you change the `Metals: sbt script` setting?
We normally create a jar in a temporary folder like for example on my machine:
`/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals2984072979320393082/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall`

 'java -jar C:\Code\sbt\bin\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall' looks a bit weird and I am not sure where it's coming from. Does the jar exist?

**Comment by kcwill2** [comment]
Thanks or responding. I did modify the sbt script to point to our installation of SBT. The jar does exist. I tried to point to this SBT install due to our maven/ivy proxy settings. Is there a better way to do this? maybe I can Metals included SBT how to find repos.

**Comment by tgodzik** [comment]
You could add proxy settings to `.jvmopts`, which should be picked up by Metals or run `sbt  -Dbloop.export-jar-classifiers=sources bloopInstall` manually. What does happen if you run your sbt script manually?

**Comment by kcwill2** [comment]
I got it working without customizing the sbt script. I added 'override.buile.repos=true' to the .sbtopt file and included a repositories file. I may look into getting it working with the custom sbt script but this may just be simpler.

Thanks for looking into it for me.

**Comment by tgodzik** [comment]
I created a more general issue to address the overall problems with proxies https://github.com/scalameta/metals/issues/2485
