### ISSUE TITLE
Error: class scala.meta.metals.Main not found

### ISSUE THREAD

**Issue by skakker** [scalameta/metals#2478]
Hi, 

I am trying to get metals using coursier CLI. Mentioning the reproduciton steps along with the error here. 

When I run this: 

`coursier bootstrap org.scalameta:metals_2.12:0.9.8 --force-fetch -r "ivy:http://<link_to_metals>/org/scalameta/metals_2.12/0.9.8/metals_2.12-0.9.8.ivy" -o metals -f --no-default -J-Dfile.encoding=UTF-8` 

It gives the error: 

`Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at coursier.install.MainClass$.$anonfun$mainClasses$1(MainClass.scala:14)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at coursier.install.MainClass$.mainClasses(MainClass.scala:13)
	at coursier.cli.bootstrap.Bootstrap$.$anonfun$task$3(Bootstrap.scala:41)
	at coursier.util.Task$.wrap(Task.scala:84)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:49)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

This error goes away on specifying a main class, so I run: 

`coursier bootstrap org.scalameta:metals_2.12:0.9.8 --force-fetch -r "ivy:http://<link_to_metals>/org/scalameta/metals_2.12/0.9.8/metals_2.12-0.9.8.ivy" -o metals -f --no-default -J-Dfile.encoding=UTF-8 --main-class scala.meta.metals.Main`

and it writes the metals server correctly. But when I try to run the server by doing: `./metals`, it throws this error: 

`Error: class scala.meta.metals.Main not found`

Would really appreciate any help here. 

Thanks and regards!

**Comment by tgodzik** [comment]
Thanks for reporting! We do have some instructions around this for example in the emacs docs (search for `Next, build a metals-emacs`) https://scalameta.org/metals/docs/editors/emacs.html

I am not sure why the coursier command is failing though. What do you need the boostrap for?

**Comment by skakker** [comment]
Hey @tgodzik, 

Thanks for the prompt reply. Actually, when I try to install from the open-source metals, it works fine.. But here I am trying to install it from the ivy file, which we have put in our company's internal packages (it only supports ivy files and not pom files).

Does the behavior change with ivy files? 
 
I just followed the instructions which said to use bootstrap.. Is there a way we can bypass that? 

Thanks and regards :)

**Comment by skakker** [comment]
More info: 

Even when I do a coursier launch with the ivy file, it throws the same error: 

`/lsp_install/lsp/coursier launch org.scalameta:metals_2.12:0.9.8 --force-fetch -r "ivy:<repo_link>/org/scalameta/metals_2.10.9.8/metals_2.12-0.9.8.ivy" --no-default
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at coursier.install.MainClass$.$anonfun$mainClasses$1(MainClass.scala:14)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at coursier.install.MainClass$.mainClasses(MainClass.scala:13)
	at coursier.cli.launch.Launch$.$anonfun$mainClass$1(Launch.scala:240)
	at coursier.util.Task$.wrap(Task.scala:84)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:49)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by tgodzik** [comment]
This might be an issue on the Coursier side then, maybe it's better to try ans ask there? I am not 100% sure how boostraping should work with ivy files.

**Comment by skakker** [comment]
I have actually raised an issue there.. no response yet. Do you know a way we can get metals from the ivy file (if not via coursier)?

**Comment by tgodzik** [comment]
Why do you need to run it from ivy actually, is it possible to just do:
`coursier bootstrap org.scalameta:metals_2.12:0.9.8 --force-fetch -r "http://<link_to_metals>/org/scalameta/" -o metals -f --no-default` ? I don't really see that there is an option on the coursier website to do it with `ivy` prefix. Or try to generate it from local ivy if you fetch first all dependencies:
`coursier bootstrap org.scalameta:metals_2.12:0.9.8 --force-fetch -r "ivy2local" -o metals -f --no-default`

You could also experiment with adding the `--standalone` flag with would not download anything more when launching Metalse.

**Comment by skakker** [comment]
If I run it without the ivy thing, it tries to find the .pom file by default.. which is not present. We only have the .ivy file in the repository, hence the issue.

Tried with fetch first and then using `ivy2local`, but that also didnt work. Is the main class `scala.meta.metals.Main` correct? It doesn't seem to find it.

Thanks for suggesting the `--standalone` flag. I tried with it.. the bootstrap thing works, but on starting the server, it gives this error: 

`Exception in thread "main" java.io.IOException: Unable to open nested jar file 'coursier/bootstrap/launcher/jars/metals_2.12-0.9.8.ivy'
	at coursier.bootstrap.launcher.jar.i.a(Unknown Source)
	at coursier.bootstrap.launcher.g.b(Unknown Source)
	at coursier.bootstrap.launcher.g.b(Unknown Source)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.ResourcesLauncher.main(Unknown Source)
Caused by: java.io.IOException: Unable to find ZIP central directory records after reading 9309 bytes
	at coursier.bootstrap.launcher.jar.b.<init>(Unknown Source)
	at coursier.bootstrap.launcher.jar.d.a(Unknown Source)
	at coursier.bootstrap.launcher.jar.i.<init>(Unknown Source)
	at coursier.bootstrap.launcher.jar.i.<init>(Unknown Source)`

Seems like it's not able to open the ivy jar

Here is the coursier documentation for using ivy repos: https://github.com/coursier/coursier/blob/master/doc/FORMER-README.md#command-line-1

**Comment by tgodzik** [comment]
> Tried with fetch first and then using `ivy2local`, but that also didnt work. Is the main class `scala.meta.metals.Main` correct? It doesn't seem to find it.

It is correct: https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/metals/Main.scala

> Here is the coursier documentation for using ivy repos: https://github.com/coursier/coursier/blob/master/doc/FORMER-README.md#command-line-1

I don't think you can install from a single ivy file, this will simply not work. It should be then:
```
coursier bootstrap org.scalameta:metals_2.12:0.9.8 --force-fetch -r "ivy:https://<link-to-company-repo>/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]" -o metals -f --no-default 
```
with only <link-to-company-repo> replaced. The `ivy:` format is supposed to work for all artifacts that might be contained there. `[organisation]` etc. should not be replaced by actual organisation, it's more of template on how to read from this icy repository.

**Comment by skakker** [comment]
Thanks for looking into this.. I tried with it also, it downloads many files and then fails on the error: 

`Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at coursier.install.MainClass$.$anonfun$mainClasses$1(MainClass.scala:14)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at coursier.install.MainClass$.mainClasses(MainClass.scala:13)
	at coursier.cli.bootstrap.Bootstrap$.$anonfun$task$3(Bootstrap.scala:41)
	at coursier.util.Task$.wrap(Task.scala:84)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:49)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Here's the full snippet: 

sh-4.2# ./coursier bootstrap org.scalameta:metals_2.12:0.9.8 --no-default -r "ivy:<internal_artifactory_link>/artifactory/release/[orgPath]/[module]/[revision]/[module]-[revision].ivy" -o metals -f
<internal_artifactory_link>/artifactory/release/dev/dirs/directories/21/directories-21.ivy
  100.0% [##########] 1.2 KiB (1.4 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/semanticdb-scalac-core_2.12.12/4.4.2/semanticdb-scalac-core_2.12.12-4.4.2.ivy
  100.0% [##########] 2.0 KiB (2.3 KiB / s)
<internal_artifactory_link>/artifactory/release/ch/epfl/scala/bloop-launcher_2.12/1.4.6-15-209c2a5c/bloop-launcher_2.12-1.4.6-15-209c2a5c.ivy
  100.0% [##########] 2.2 KiB (2.4 KiB / s)
<internal_artifactory_link>/artifactory/release/com/geirsson/metaconfig-core_2.12/0.9.10/metaconfig-core_2.12-0.9.10.ivy
  100.0% [##########] 2.2 KiB (2.4 KiB / s)
<internal_artifactory_link>/artifactory/release/com/h2database/h2/1.4.200/h2-1.4.200.ivy
  100.0% [##########] 1.2 KiB (1.3 KiB / s)
<internal_artifactory_link>/artifactory/release/io/methvin/directory-watcher/0.10.1/directory-watcher-0.10.1.ivy
  100.0% [##########] 1.7 KiB (1.8 KiB / s)
<internal_artifactory_link>/artifactory/release/com/google/guava/guava/30.1-jre/guava-30.1-jre.ivy
  100.0% [##########] 2.8 KiB (9.1 KiB / s)
<internal_artifactory_link>/artifactory/release/com/swoval/file-tree-views/2.1.6/file-tree-views-2.1.6.ivy
  100.0% [##########] 1.2 KiB (3.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/flywaydb/flyway-core/7.3.1/flyway-core-7.3.1.ivy
  100.0% [##########] 1.1 KiB (3.4 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scala-lang/modules/scala-java8-compat_2.12/0.9.1/scala-java8-compat_2.12-0.9.1.ivy
  100.0% [##########] 1.5 KiB (4.2 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/mtags_2.12.12/0.9.8/mtags_2.12.12-0.9.8.ivy
  100.0% [##########] 3.3 KiB (10.4 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/scalameta_2.12/4.4.2/scalameta_2.12-4.4.2.ivy
  100.0% [##########] 1.9 KiB (5.8 KiB / s)
<internal_artifactory_link>/artifactory/release/io/github/alexarchambault/ammonite/ammonite-runner_2.12/0.3.0/ammonite-runner_2.12-0.3.0.ivy
  100.0% [##########] 2.0 KiB (6.1 KiB / s)
<internal_artifactory_link>/artifactory/release/org/jboss/xnio/xnio-nio/3.8.4.Final/xnio-nio-3.8.4.Final.ivy
  100.0% [##########] 1.4 KiB (4.3 KiB / s)
<internal_artifactory_link>/artifactory/release/com/outr/scribe_2.12/3.1.7/scribe_2.12-3.1.7.ivy
  100.0% [##########] 2.4 KiB (6.8 KiB / s)
<internal_artifactory_link>/artifactory/release/io/undertow/undertow-core/2.2.3.Final/undertow-core-2.2.3.Final.ivy
  100.0% [##########] 2.0 KiB (5.8 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/mdoc-interfaces/2.2.14/mdoc-interfaces-2.2.14.ivy
  100.0% [##########] 1.4 KiB (4.2 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/scalafmt-dynamic_2.12/2.7.4/scalafmt-dynamic_2.12-2.7.4.ivy
  100.0% [##########] 2.2 KiB (6.6 KiB / s)
<internal_artifactory_link>/artifactory/release/com/lihaoyi/pprint_2.12/0.6.0/pprint_2.12-0.6.0.ivy
  100.0% [##########] 1.6 KiB (5.1 KiB / s)
<internal_artifactory_link>/artifactory/release/com/thoughtworks/qdox/qdox/2.0.0/qdox-2.0.0.ivy
  100.0% [##########] 1.4 KiB (4.3 KiB / s)
<internal_artifactory_link>/artifactory/release/net/java/dev/jna/jna-platform/5.6.0/jna-platform-5.6.0.ivy
  100.0% [##########] 1.5 KiB (4.8 KiB / s)
<internal_artifactory_link>/artifactory/release/org/eclipse/lsp4j/org.eclipse.lsp4j/0.10.0/org.eclipse.lsp4j-0.10.0.ivy
  100.0% [##########] 1.8 KiB (5.4 KiB / s)
<internal_artifactory_link>/artifactory/release/com/lihaoyi/ujson_2.12/1.2.2/ujson_2.12-1.2.2.ivy
  100.0% [##########] 1.4 KiB (4.0 KiB / s)
<internal_artifactory_link>/artifactory/release/net/java/dev/jna/jna/5.6.0/jna-5.6.0.ivy
  100.0% [##########] 1.2 KiB (3.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scala-lang/scala-library/2.12.12/scala-library-2.12.12.ivy
  100.0% [##########] 1.2 KiB (3.3 KiB / s)
<internal_artifactory_link>/artifactory/release/com/lihaoyi/requests_2.12/0.6.5/requests_2.12-0.6.5.ivy
  100.0% [##########] 1.5 KiB (4.5 KiB / s)
<internal_artifactory_link>/artifactory/release/ch/epfl/scala/bsp4j/2.0.0-M13/bsp4j-2.0.0-M13.ivy
  100.0% [##########] 1.7 KiB (5.1 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scala-sbt/ipcsocket/ipcsocket/1.3.0/ipcsocket-1.3.0.ivy
  100.0% [##########] 1.7 KiB (4.9 KiB / s)
<internal_artifactory_link>/artifactory/release/com/outr/scribe-slf4j_2.12/3.1.7/scribe-slf4j_2.12-3.1.7.ivy
  100.0% [##########] 1.9 KiB (5.7 KiB / s)
<internal_artifactory_link>/artifactory/release/io/get-coursier/interface/1.0.2/interface-1.0.2.ivy
  100.0% [##########] 1.2 KiB (3.7 KiB / s)
<internal_artifactory_link>/artifactory/release/com/zaxxer/nuprocess/2.0.1/nuprocess-2.0.1.ivy
  100.0% [##########] 1.5 KiB (4.5 KiB / s)
<internal_artifactory_link>/artifactory/release/ch/epfl/scala/scalafix-interfaces/0.9.24/scalafix-interfaces-0.9.24.ivy
  100.0% [##########] 1.5 KiB (3.9 KiB / s)
<internal_artifactory_link>/artifactory/release/org/openjdk/jol/jol-core/0.14/jol-core-0.14.ivy
  100.0% [##########] 1.1 KiB (3.2 KiB / s)
<internal_artifactory_link>/artifactory/release/org/eclipse/lsp4j/org.eclipse.lsp4j.debug/0.10.0/org.eclipse.lsp4j.debug-0.10.0.ivy
  100.0% [##########] 1.8 KiB (5.0 KiB / s)
<internal_artifactory_link>/artifactory/release/org/jsoup/jsoup/1.13.1/jsoup-1.13.1.ivy
  100.0% [##########] 1.4 KiB (5.2 KiB / s)
<internal_artifactory_link>/artifactory/release/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.ivy
  100.0% [##########] 1.2 KiB (4.1 KiB / s)
<internal_artifactory_link>/artifactory/release/org/jboss/logging/jboss-logging/3.4.1.Final/jboss-logging-3.4.1.Final.ivy
  100.0% [##########] 1.2 KiB (3.7 KiB / s)
<internal_artifactory_link>/artifactory/release/org/jboss/xnio/xnio-api/3.8.4.Final/xnio-api-3.8.4.Final.ivy
  100.0% [##########] 1.9 KiB (5.8 KiB / s)
<internal_artifactory_link>/artifactory/release/com/lihaoyi/geny_2.12/0.6.2/geny_2.12-0.6.2.ivy
  100.0% [##########] 1.2 KiB (3.3 KiB / s)
<internal_artifactory_link>/artifactory/release/com/lihaoyi/upickle-core_2.12/1.2.2/upickle-core_2.12-1.2.2.ivy
  100.0% [##########] 1.7 KiB (5.3 KiB / s)
<internal_artifactory_link>/artifactory/release/com/outr/perfolation_2.12/1.2.0/perfolation_2.12-1.2.0.ivy
  100.0% [##########] 1.4 KiB (4.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scala-lang/modules/scala-collection-compat_2.12/2.2.0/scala-collection-compat_2.12-2.2.0.ivy
  100.0% [##########] 1.5 KiB (4.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/mtags-interfaces/0.9.8/mtags-interfaces-0.9.8.ivy
  100.0% [##########] 1.5 KiB (4.4 KiB / s)
<internal_artifactory_link>/artifactory/release/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.ivy
  100.0% [##########] 1.4 KiB (1.8 KiB / s)
<internal_artifactory_link>/artifactory/release/com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.ivy
  100.0% [##########] 1.2 KiB (2.3 KiB / s)
<internal_artifactory_link>/artifactory/release/com/outr/moduload_2.12/1.0.3/moduload_2.12-1.0.3.ivy
  100.0% [##########] 1.7 KiB (5.7 KiB / s)
<internal_artifactory_link>/artifactory/release/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.ivy
  100.0% [##########] 1.4 KiB (4.8 KiB / s)
<internal_artifactory_link>/artifactory/release/com/lihaoyi/sourcecode_2.12/0.2.1/sourcecode_2.12-0.2.1.ivy
  100.0% [##########] 1.2 KiB (3.6 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scala-lang/scala-compiler/2.12.12/scala-compiler-2.12.12.ivy
  100.0% [##########] 2.1 KiB (6.0 KiB / s)
<internal_artifactory_link>/artifactory/release/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-confl…
  100.0% [##########] 1.9 KiB (6.8 KiB / s)
<internal_artifactory_link>/artifactory/release/org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc/0.10.0/org.eclipse.lsp4j.jsonrpc-0.10.0.ivy
  100.0% [##########] 1.5 KiB (2.6 KiB / s)
<internal_artifactory_link>/artifactory/release/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.ivy
  100.0% [##########] 2.7 KiB (9.3 KiB / s)
<internal_artifactory_link>/artifactory/release/org/jboss/threads/jboss-threads/3.1.0.Final/jboss-threads-3.1.0.Final.ivy
  100.0% [##########] 1.7 KiB (5.2 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/parsers_2.12/4.4.2/parsers_2.12-4.4.2.ivy
  100.0% [##########] 1.7 KiB (2.9 KiB / s)
<internal_artifactory_link>/artifactory/release/org/lz4/lz4-java/1.7.1/lz4-java-1.7.1.ivy
  100.0% [##########] 1.3 KiB (3.7 KiB / s)
<internal_artifactory_link>/artifactory/release/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.ivy
  100.0% [##########] 1.6 KiB (5.6 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/scalafmt-interfaces/2.7.4/scalafmt-interfaces-2.7.4.ivy
  100.0% [##########] 1.3 KiB (3.9 KiB / s)
<internal_artifactory_link>/artifactory/release/org/eclipse/lsp4j/org.eclipse.lsp4j.generator/0.10.0/org.eclipse.lsp4j.generator-0.10.0.ivy
  100.0% [##########] 1.8 KiB (4.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/typelevel/paiges-core_2.12/0.3.0/paiges-core_2.12-0.3.0.ivy
  100.0% [##########] 1.4 KiB (4.5 KiB / s)
<internal_artifactory_link>/artifactory/release/com/lihaoyi/fansi_2.12/0.2.9/fansi_2.12-0.2.9.ivy
  100.0% [##########] 1.4 KiB (4.1 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scala-lang/scalap/2.12.12/scalap-2.12.12.ivy
  100.0% [##########] 1.4 KiB (4.2 KiB / s)
<internal_artifactory_link>/artifactory/release/com/typesafe/config/1.4.0/config-1.4.0.ivy
  100.0% [##########] 1.2 KiB (4.1 KiB / s)
<internal_artifactory_link>/artifactory/release/io/get-coursier/coursier-launcher_2.12/2.0.0-RC6-23/coursier-launcher_2.12-2.0.0-RC6-23.ivy
  100.0% [##########] 1.5 KiB (4.8 KiB / s)
<internal_artifactory_link>/artifactory/release/org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc.debug/0.10.0/org.eclipse.lsp4j.jsonrpc.debug-0.10.0.ivy
  100.0% [##########] 1.8 KiB (5.9 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0.ivy
  100.0% [##########] 1.4 KiB (4.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.ivy
  100.0% [##########] 1.1 KiB (2.2 KiB / s)
<internal_artifactory_link>/artifactory/release/org/eclipse/xtend/org.eclipse.xtend.lib/2.19.0/org.eclipse.xtend.lib-2.19.0.ivy
  100.0% [##########] 1.8 KiB (6.4 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/trees_2.12/4.4.2/trees_2.12-4.4.2.ivy
  100.0% [##########] 2.1 KiB (7.0 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scala-lang/scala-reflect/2.12.12/scala-reflect-2.12.12.ivy
  100.0% [##########] 1.5 KiB (4.5 KiB / s)
<internal_artifactory_link>/artifactory/release/com/google/code/gson/gson/2.8.2/gson-2.8.2.ivy
  100.0% [##########] 1.2 KiB (3.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/wildfly/client/wildfly-client-config/1.0.1.Final/wildfly-client-config-1.0.1.Final.ivy
  100.0% [##########] 1.8 KiB (5.2 KiB / s)
<internal_artifactory_link>/artifactory/release/org/wildfly/common/wildfly-common/1.5.2.Final/wildfly-common-1.5.2.Final.ivy
  100.0% [##########] 1.2 KiB (1.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.19.0/org.eclipse.xtext.xbase.lib-2.19.0.ivy
  100.0% [##########] 1.5 KiB (5.5 KiB / s)
<internal_artifactory_link>/artifactory/release/org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.19.0/org.eclipse.xtend.lib.macro-2.19.0.ivy
  100.0% [##########] 1.6 KiB (4.7 KiB / s)
<internal_artifactory_link>/artifactory/release/com/thesamet/scalapb/scalapb-runtime_2.12/0.10.9/scalapb-runtime_2.12-0.10.9.ivy
  100.0% [##########] 2.5 KiB (6.8 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/common_2.12/4.4.2/common_2.12-4.4.2.ivy
  100.0% [##########] 1.7 KiB (4.7 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/fastparse_2.12/1.0.1/fastparse_2.12-1.0.1.ivy
  100.0% [##########] 1.9 KiB (4.8 KiB / s)
<internal_artifactory_link>/artifactory/release/com/thesamet/scalapb/lenses_2.12/0.10.9/lenses_2.12-0.10.9.ivy
  100.0% [##########] 1.7 KiB (5.4 KiB / s)
<internal_artifactory_link>/artifactory/release/org/scalameta/fastparse-utils_2.12/1.0.1/fastparse-utils_2.12-1.0.1.ivy
  100.0% [##########] 1.7 KiB (5.3 KiB / s)
<internal_artifactory_link>/artifactory/release/com/google/protobuf/protobuf-java/3.11.4/protobuf-java-3.11.4.ivy
  100.0% [##########] 1.3 KiB (3.6 KiB / s)
<internal_artifactory_link>/artifactory/release/com/lihaoyi/fastparse_2.12/2.3.0/fastparse_2.12-2.3.0.ivy
  100.0% [##########] 1.6 KiB (2.8 KiB / s)
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at coursier.install.MainClass$.$anonfun$mainClasses$1(MainClass.scala:14)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at coursier.install.MainClass$.mainClasses(MainClass.scala:13)
	at coursier.cli.bootstrap.Bootstrap$.$anonfun$task$3(Bootstrap.scala:41)
	at coursier.util.Task$.wrap(Task.scala:84)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:49)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tgodzik** [comment]
Can't help you there unfortunately, seems you might have some broken artifacts in the private repository, but not sure 100 %.

**Comment by skakker** [comment]
Okay, thank you so much for trying :)

**Comment by tgodzik** [comment]
Since, it seems not specific to Metals itself I will close this for now. You can follow https://github.com/scalameta/metals/issues/2485 which tackles issues with proxies mirrors etc.

**Comment by skakker** [comment]
Hey @tgodzik

Thanks for trying to help out here. One workaround we were trying is getting the metals executable from the marketplace first and then run the executable. Do you know if there is a way to get the executable and then on server start, it doesn't try to contact the marketplace? That will also work for our use case. 
So I got metals from the marketplace and then when invoked the executable, it still tries to contact the marketplace: 

`metals 
Error while downloading https://repo1.maven.org/maven2/com/google/code/gson/gson/2.7/gson-2.7.jar: Connection refused (Connection refused), ignoring it
Error while downloading https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar: Connection refused (Connection refused), ignoring it
Error while downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar: Connection refused (Connection refused), ignoring it
Error while downloading https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar: Connection refused (Connection refused), ignoring it
Error while downloading https://repo1.maven.org/maven2/ch/epfl/scala/bsp4j/2.0.0-M4/bsp4j-2.0.0-M4.jar: Connection refused (Connection refused), ignoring it
Error while downloading https://repo1.maven.org/maven2/com/geirsson/coursier-small_2.12/1.3.3/coursier-small_2.12-1.3.3.jar: Connection refused (Connection refused), ignoring it`

If there's a way to override this behavior (get everything before and then don't contact the marketplace on server start), that would be great! 

Thanks :)

**Comment by tgodzik** [comment]
I think that might require mirrors: https://get-coursier.io/blog/2019/07/05/1.1.0-M14.html#mirrors

The executable there is a minimal coursier jar that tries to boostrap itself by directly downloading some needed files. This should work with mirrors if outside web is not available.

We do have also a feature request that is connected: https://github.com/scalameta/metals-feature-requests/issues/159

However, we haven't done any work on it really.

**Comment by skakker** [comment]
For anyone following this thread, this is what worked finally: 
./coursier bootstrap org.scalameta:metals_2.12:0.9.8 --no-default -r "ivy:http://<artifactory-link>/[orgPath]/[module]/[revision]/[module]-[revision].[ext]|http://<artifactory-link>/[orgPath]/[module]/[revision]/[module]-[revision].ivy" -o metals -f
