### ISSUE TITLE
Unexpected -J prefix in debugSession/start request

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#2489]
**Describe the bug**

When starting a debug session, Metals add a `-J` prefix to all the jvm options. This was originally made for Bloop in #1781. The problem is that it's an implementation detail of Bloop that should not leak out of it.

**To Reproduce**

1. Create the run properties
```
{
    "type": "scala",
    "request": "launch",
    "name": "MyMain",
    "mainClass": "com.example.MyMain",
    "args": [],
    "jvmOptions": ["-Dconfig.file=/path/to/config/file"]
 }
```
2. Activate BSP tracing by creating the `/home/piquerez/.cache/metals/bsp.trace.json`
3. Click the `run` button above the `com.example.MyMain` class
4. The `debugSession/start` request in the BSP traces contains:
```
"jvmOptions": [
  "-J-Dconfig.file=/path/to/config/file"
],
```

**Expected behavior**

Metals should not add the `-J` prefix

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.9.10

**Comment by tgodzik** [comment]
Thanks for reporting! Let's fix it once the Bloop PR is merged and release.
