### ISSUE TITLE
Better names for types in hover/completions in Scala 3

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#2495]
**Is your feature request related to a problem? Please describe.**
Currently, Scala 3 shows the  fully qualified name for each type, which sometimes causes it not to show everything that is needed.

"com.something.very.long.ButUniqueName" should show most likely just "ButUniqueName"

**Describe the solution you'd like**
This should work as it worked in Scala 2

**Search terms**:
hover completions scala3

**Comment by tgodzik** [comment]
First part of the functionality was merged in https://github.com/scalameta/metals/pull/2504

We still need to add auto imports for the signatures to always be shorter irrelevant of whether the symbol is in scope or not. We should also make types shorter for completions.

**Comment by tanishiking** [comment]
I finally started taking a look at prettifying names for type in completions.
I'll work on it this month 💪 

Here are rough TODOs.

- [ ] Pretty print method symbol
  - [ ] shorten signature and print it 
    - https://github.com/scalameta/metals/blob/45eaa4151ac5f54cabddce73de3d888d5157b1f3/mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala#L329
  - [ ] hide implicit evidence param
  - [ ] print context bounds 
    - https://github.com/scalameta/metals/blob/45eaa4151ac5f54cabddce73de3d888d5157b1f3/mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala#L390-L396
  - [ ] (not needed for completion) print default value 
    - https://github.com/scalameta/metals/blob/45eaa4151ac5f54cabddce73de3d888d5157b1f3/mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala#L399
- [ ] Pretty print other symbols
  - dealias type alias
    - https://github.com/scalameta/metals/blob/45eaa4151ac5f54cabddce73de3d888d5157b1f3/mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala#L234
- [ ] Compute type parameters based on the qualifier.	
  - https://github.com/scalameta/metals/blob/45eaa4151ac5f54cabddce73de3d888d5157b1f3/mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala#L258-L262

**Comment by tgodzik** [comment]
Ok cool, thanks for the info!

**Comment by tgodzik** [comment]
@tanishiking do you think we can close this? We have better signatures currently and I would open new issues if we find any problematic cases.

**Comment by tanishiking** [comment]
> I would open new issues if we find any problematic cases.

Yeah, let's close this.
