### ISSUE TITLE
InferredTypeAction does not work with backticked types

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#2496]
**Describe the bug**

Add type annotation will not currently work with backticked types for example `class Pac-kage`. I started looking at this, but seems we would need to write our own type printer as suggested here: https://github.com/scalameta/metals/blob/c328449d6c87dfdeb79196a5c8b18ae9477082cc/mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala#L169

**To Reproduce**

Add test suite to InsertInferredTypeSuite:

```
  checkEdit(
    "val-backticks",
    """|object A{
       |   case class `Pac-kage`(a: Int) 
       |   val <<k>> = `Pac-kage`(1)
       |}""".stripMargin,
    """|object A{
       |   case class `Pac-kage`(a: Int) 
       |   val k: `Pac-kage` = `Pac-kage`(1)
       |}""".stripMargin
  )
 ```

**Expected behavior**

Types are properly backticked.

**Search terms**

backtick backticks inferred type annotation

**Comment by tgodzik** [comment]
Btw. @mlachkar is working on a related issue in scalafix

**Comment by kasiaMarek** [comment]
This is resolved for Scala 2, and should now only be fixed in Scala 3.
