### ISSUE TITLE
Completions should insert parentheses () when completing methods with arguments

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#251]
```scala
List(1).len<COMPLETE>
// obtained == expected
List(1).length/*cursor*/


List(1).lengthC<COMPLETE>
// obtained
List(1).lengthCompare/*cursor*/
// expected
List(1).lengthCompare(/*cursor*/)
```
The parentheses bring you straight into filling out the argument list with signatureHelp.

This should be doable with InsertTextFormat from CompletionItem https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

A good place to start would be to look here

https://github.com/scalameta/metals/blob/405ee8f44fbddf2b7f025bd4bb6ef9aaf736293f/metals/src/main/scala/scala/meta/metals/providers/CompletionProvider.scala#L90

To test this change see here https://github.com/scalameta/metals/blob/405ee8f44fbddf2b7f025bd4bb6ef9aaf736293f/metals/src/test/scala/tests/compiler/CompletionsTest.scala#L168-L199

**Comment by ShaneDelmore** [comment]
It would be nice to have this be an option.  I’m not a fan of writing List(1, 2, 3).map and having it assume () when I actually want {}, it’s just so easy to type the ( or { and get the auto-close that I want.  I agree the () are nice when the param is not a block though.

**Comment by kubukoz** [comment]
For a nullary function with parentheses, the result should be `()<cursor>`, right?

For the case of `List.map`, I would guess that: unless the argument list only has one parameter (which is a lambda/SAM), we can also put parentheses and the cursor inside as in `(<cursor>)`.

**Comment by olafurpg** [comment]
Metals doesn't support completions anymore. Completions may get added back in the future but for now I think it's best to close completion-related tickets.
