### ISSUE TITLE
Not a valid key: bloopInstall

### ISSUE THREAD

**Issue by babysnakes** [scalameta/metals#2517]
**Describe the bug**

Today I had to completely reset a project I'm working on (delete all non git files) and when I tried to re-import it it failed with the following error:

```
2021.02.16 11:45:42 INFO  [error] Not a valid command: bloopInstall
2021.02.16 11:45:42 INFO  [error] Not a valid project ID: bloopInstall
2021.02.16 11:45:42 INFO  [error] Expected ':'
2021.02.16 11:45:42 INFO  [error] Not a valid key: bloopInstall
2021.02.16 11:45:42 INFO  [error] bloopInstall
2021.02.16 11:45:42 INFO  [error]             ^
2021.02.16 11:45:42 INFO  sbt bloopInstall exit: 1
2021.02.16 11:45:42 INFO  time: ran 'sbt bloopInstall' in 14s
2021.02.16 11:45:42 ERROR sbt command failed: /Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/j3/vx4pz_7s7qq5zpw2knby1khm0000gn/T/metals1088693572816316014/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall
```

I tried cloning other projects into new clean directories and they all failed with the same errors. Note that because of some limitations I'm using old versions (see below). Also, the same projects are working in an already imported environments - It's just that I can't import new projects.

This is a work project so I can't share it, however I'll cooperate in any way I can to help solve this issue.

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.10
- Scala: 2.11.12
- JDK: 1.8.0_xxx
- Sbt: 1.2.7

Please help 😄

**Comment by tgodzik** [comment]
Thanks for reporting! It seems that the Bloop sbt plugin is not added to the build definition. Do you have the `project/metals.sbt` and what are its contents?

**Comment by babysnakes** [comment]
I don't have it. At one time during my troubleshooting I was surprised that I didn't have it but I forgot about it when I reported ...

**Comment by babysnakes** [comment]
Ok, seems to be my error. A couple of months ago I had a problem with versions and I had to play with metals.sbt trying to force specific version. Checking the metals options I saw that it marked as not to create metals.sbt. Disabling this feature fixed the issue.

Sorry for the false reporting and much much thanks for an amazingly fast response (for the second time in 2 months).

**Comment by babysnakes** [comment]
Closing ...
