### ISSUE TITLE
Smarter sbt server detection

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#253]
Currently whenever `sbt.enabled` is `true` we try to connect to the server right away. This has the annoying effect of showing an error whenever opening a project without sbt running.

A better approach would be to try to connect to sbt only when the server has started. It's possible to detect the sbt server starting by watching for `project/target/active.json` which gets created/deleted whenever the server starts.

This is a good starting point:

https://github.com/scalameta/metals/blob/fb166f1d81eb77ebd9c6b3ee95e65fb58a907eec/metals/src/main/scala/scala/meta/metals/MetalsServices.scala#L456

Concerning the file watching, it needs to be added to the VSCode client here (and similarly in other clients)

https://github.com/scalameta/metals/blob/fb166f1d81eb77ebd9c6b3ee95e65fb58a907eec/vscode-extension/src/extension.ts#L49

**Comment by laughedelic** [comment]
Another related idea is to check sbt version in `project/build.properties` and stand still if it's less than 1.1 (i.e. don't try to connect and don't report errors). A friendly warning could be shown if user explicitly calls `sbt connect` command on a <1.1 project. Does it deserve a separate (good first) issue?

**Comment by gabro** [comment]
No I think it's a good idea, also in scope with this issue
