### ISSUE TITLE
Scala 3: rename skips anonymous `using`

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#2533]
**Describe the bug**

Renaming a type that's used in a `using` parameter with just a type (no name) ignores that parameter.

**To Reproduce**

1. Create a file:

```scala
trait Foo

def bar(using Foo) = 42
```

2. Compile
3. Rename `Foo` to anything else, e.g. `Baz`:

```scala
trait Baz

def bar(using Foo) = 42
```

4. See compilation errors: `Not found: type Foo`

**Expected behavior**

The `using` parameter's type is renamed as well.

**Screenshots**

-

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.10+151-aaa761e5-SNAPSHOT

**Additional context**

- Scala version: 3.0.0-M3

**Search terms**

dotty, scala3, scala 3, rename symbol

**Comment by tgodzik** [comment]
Thanks for reporting! It seems that we are missing the occurence for `Foo`:

```
src/main/scala/Test.scala
-------------------------

Summary:
Schema => SemanticDB v4
Uri => src/main/scala/Test.scala
Text => empty
Language => Scala
Symbols => 5 entries
Occurrences => 5 entries

Symbols:
a/Foo# => trait Foo
a/Foo#`<init>`(). => primary ctor <init>
a/Test$package. => final package object a
a/Test$package.bar(). => method bar
a/Test$package.bar().(x$1) => implicit param x$1

Occurrences:
[0:8..0:9) <= a/
[2:0..2:0) <= a/Foo#`<init>`().
[2:6..2:9) <= a/Foo#
[4:0..4:0) <= a/Test$package.
[4:4..4:7) <= a/Test$package.bar().
```

We need to fix it in the compiler.

**Comment by tgodzik** [comment]
Reported here: https://github.com/lampepfl/dotty/issues/11498
