### ISSUE TITLE
VS Code, gradle - init script repositories cannot be overriden

### ISSUE THREAD

**Issue by moonkev** [scalameta/metals#2535]
**Describe the bug**

Currently when using metals with VS Code and gradle, metals will attempt to run the gradle bloopInstall task using an automatically generated init script.  This init script only contains a reference to maven central repository.  If you are behind a corporate proxy, there are ways to set proxy settings for gradle in multiple ways, including user and project based settings files.  However, in some instances users are not able to access maven central even through a proxy and are forced to use Nexus or Artifactory to download their artifacts.   In this event you are unable to initialize bloop.  Even if you run bloopInstall outside of your project, each time you reload VS Code or want to reimport (i.e. due to dependency changes) metals will attempt to run using the auto generated init script.

**To Reproduce**

Simply import a bloop project using gradle into visual studio code.  If you look at the metals output you will see the gradle command is being given an auto generated init script which you cannot control

**Expected behavior**

A user has the ability to either specify alternative repositories to use (possibly using the same extra repositories that can be specified for coursier.  Alternatively a user had the ability to turn off the init script, in which they would then need to manually add the bloop plugin dependency and respective plugin applications to their gradle configuration.

**Installation:**

- Operating system: Windows 10 
- Editor: Visual Studio Code
- Metals version: v0.9.10

**Additional context**

This issue was originally discussed here: https://github.com/scalameta/metals/discussions/2474#discussioncomment-387935

I looked through the metals code to see about the possibility of adding the coursier alternative repositories to the build script here - https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala

However, I did not see the coursier repositories exposed via UserConfiguration as many other configuration options are.   I'm guessing this will need to be passed somehow from the VS Code extension.

CURRENT WORKAROUND: 
Luckily the user currently has the ability to specify an alternative gradle script to run.  Given this you can create a custom script that ignores the init-script parameters and run with your own gradle configuration which contains required bloop setup.

**Search terms**

Visual Studio Code, Metals, Gradle, Bloop, Init Script

**Comment by tgodzik** [comment]
Thanks for reporting and the great description!

**Comment by tgodzik** [comment]
@ajzawawi it would be super cool if you were able to help out here. We have two possibilities here:
- add an option to not add Bloop plugin to Gradle at all, similar like we have for sbt - `bloopSbtAlreadyInstalled`. We could use a new option `bloopAlreadyInstalled` that would work for both sbt and gradle. We would need to probably also take into account `bloopSbtAlreadyInstalled` for migration purposes.
- use the custom repositories settings - the format used there is coursier specific, we could use Coursier API to translate those repositories to something Gradle can understand and add it additionally to the init script. It's also possible that the repository settings are similar in both Coursier and Gradle, which would mean that not much work is needed here.

I would vote for the second option as it would allow users to not add the additional plugin by default.

What do you think?

**Comment by ajzawawi** [comment]
I think adding`bloopAlreadyInstalled` would make the settings more consistent across the board.

**Comment by moonkev** [comment]
Not sure if this is a regression in metals itself or the VSCode extension, but it seems that with since 0.10.0 the custom gradle script is broken.  Every time it fails in the log with `gradle bloopInstall exit: -2147483648`.

I've tried giving relative and absolute path for the alternative script.  I've tried making the script no-op, simple echo, explicit return type and nothing.  I modified the alternative script to just redirect an echo to a file, which never gets written, so looks like its never being executed.  This is with

Windows 10
Metals 0.10.1
VSCode 1.54.3
VSCode Metals Extension v1.10.2

**Comment by tgodzik** [comment]
@moonkev do you get any errors in the logs?

**Comment by moonkev** [comment]
Hi @tgodzik 

You can ignore this.  I tried to replicate this on my mac (the windows PC above is my work machine) and was able to repro the exact same error if I gave it a wrong path.

```
2021.04.20 14:12:59 INFO  gradle bloopInstall exit: -2147483648
2021.04.20 14:12:59 INFO  time: ran 'gradle bloopInstall' in 2ms
2021.04.20 14:12:59 ERROR Gradle command failed: bloop-gradlew --console=plain --init-script /var/folders/46/wss1jwx95kv2405m5tf1g8ww0000gn/T/metals8571275031448408710/init-script.gradle bloopInstall
```

So I figured for whatever reason, windows it just wasn't able to read or execute the file from the path.  The oddest thing to fix it was I set it to executable in Cygwin, which I didn't think would really have any bearing on windows itself being able to batch script, but wouldn't you know it, that fixed it.  Apologies for the false alarm.
