### ISSUE TITLE
Duplicate diagnostics getting reported from Dotty and Bloop

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2549]
**Describe the bug**

Given a small code snippet with an error while using Scala 3 and Bloop..
```scala
object Main {
  val x =
}
```

Duplicated diagnostics are reported
```
[Trace - 07:39:54 PM] Sending notification 'textDocument/publishDiagnostics'
Params: {
  "uri": "file:///Users/ckipp/Documents/scala-workspace/dotty-tester/src/main/scala/Main.scala",
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 2,
          "character": 9
        },
        "end": {
          "line": 3,
          "character": 0
        }
      },
      "severity": 1,
      "source": "bloop",
      "message": "expression expected but \u0027}\u0027 found"
    },
    {
      "range": {
        "start": {
          "line": 2,
          "character": 9
        },
        "end": {
          "line": 2,
          "character": 9
        }
      },
      "severity": 1,
      "code": "18",
      "source": "dotty",
      "message": "expression expected but \u0027}\u0027 found"
    }
  ]
}
```

This causes editors to see this as two separate diagnostics displaying both when in reality they are one in the same.
**To Reproduce**

1. Fresh Scala 3 project
2. Copy code
3. Save and look at trace file

**Expected behavior**

I'd expect this to be reported once

**Screenshots**

<img width="500" alt="Screenshot 2021-02-24 at 19 42 27" src="https://user-images.githubusercontent.com/13974112/109049337-756ca500-76d8-11eb-85fb-77a4b9c9c355.png">

**Installation:**

- Operating system: macOS
- Editor: Vim
- Metals version: v0.10.0

**Search terms**

Scala 3 duplicate diagnostics

**Comment by tgodzik** [comment]
Thanks for finding this, we do try to deduplicate the errors coming from the parser and the compiler, but it might not work perfectly in case of the Dotty parser itself.

**Comment by tgodzik** [comment]
It's actually being done here: https://github.com/scalameta/metals/blob/8c24e5d2b909dda88f39312c66089195b5e36e9c/metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala#L194
We might add additional logic to handle this case.

**Comment by ckipp01** [comment]
> It's actually being done here:
> 
> https://github.com/scalameta/metals/blob/8c24e5d2b909dda88f39312c66089195b5e36e9c/metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala#L194
> 
> We might add additional logic to handle this case.

Ahh ok cool. I'm actually looking at some diagnostic stuff right now for #2550 and I can probably tackle this one as well.

**Comment by ckipp01** [comment]
Totally random, but in this example given, Bloop says the diagnostic range goes until 0 of the next line which is different from what's coming from the compiler. Is that right?
