### ISSUE TITLE
Invalid implicit parameter lens

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#2555]
**Describe the bug**

Showing the inferred implicit parameters seems to show the wrong method call's parameters in certain situations, e.g. scalatest specifications.

**To Reproduce**

1. Write this to a file

```scala
// to avoid a dependency to reproduce this
object ScalatestMock {
  class SRF
  implicit val subjectRegistrationFunction: SRF = new SRF()
  class Position
  implicit val here: Position = new Position()
  implicit class StringTestOps(name: String) {
    def should(right: => Unit)(implicit config: SRF): Unit = ()
    def in(f: => Unit)(implicit pos: Position): Unit = ()
  }
  implicit def instancesString: Eq[String] with Semigroup[String] = ???
}

trait Eq[A]
trait Semigroup[A]

class DemoSpec {
  import ScalatestMock._

  "foo" should {
    "checkThing1" in {
      checkThing1[String]
    }
    "checkThing2" in {
      checkThing2[String]
    }
  }

  "bar" should {
    "checkThing1" in {
      checkThing1[String]
    }
  }

  def checkThing1[A](implicit ev: Eq[A]) = ???
  def checkThing2[A](implicit ev: Eq[A], sem: Semigroup[A]) = ???
}

```

~(using scalatest 3.2.2, should be possible to reproduce with stub methods)~ - added subs

2. Enable implicit parameter hints
3. Observe hints

**Expected behavior**

Something along the lines of

```scala
  "foo" should {
    "checkThing1" in {
      checkThing1[String](instancesString)
    }(here)
    "checkThing2" in {
      checkThing2[String](instancesString, instancesString)
    }(here)
  }(subjectRegistrationFunction)

  "bar" should {
    "checkThing1" in {
      checkThing1[String](instancesString)
    }(here)
  }(subjectRegistrationFunction)
```

**Screenshot - actual behavior**

![image](https://user-images.githubusercontent.com/894884/109207488-76213c00-77a9-11eb-94a3-8671bd7e0309.png)

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.0

**Additional context**

none

**Search terms**

highlighting, implicit parameter hints, lenses, code lenses, lens

**Comment by kubukoz** [comment]
Synthetics on hover also seem to "stack up":

## Case 1

![image](https://user-images.githubusercontent.com/894884/109207613-9d780900-77a9-11eb-93a1-7d045356d8aa.png)

## Case 2

![image](https://user-images.githubusercontent.com/894884/109207676-ad8fe880-77a9-11eb-8824-78b2a743c801.png)

**Comment by tgodzik** [comment]
I think they stack up because the actual ranges spand the whole braces, we might need to fix it for hovers to take into account only the end. The other issue might be related to semanticdb. Thanks for reporting!

**Comment by kubukoz** [comment]
This seems to look better these days:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/894884/185460316-282e3e4d-efb6-4d72-9c47-5b177fd6d7e3.png">

but `(here)` still shows up in the wrong place, IMO - it's a parameter to `in`, not `checkThing1`. Seems like weird ordering too ;)
