### ISSUE TITLE
Inferred type lens doesn't match hover

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#2559]
**Describe the bug**

I encountered a situation where the inferred type being shown in a code lens doesn't match the type in the on-hover window.

**To Reproduce**

1. Import this project in metals: https://github.com/pitgull/pitgull/tree/2e96c29483ba82b98a2a05a9842633e448e7f1a7
2. Open `src/main/scala/io/pg/actions.scala`
3. Enable inferred type hints
4. Look at `val approve`'s inferred type

At this time I'm not able to minimize this to a simple snippet.

**Expected behavior**

`F[Unit]` is shown

**Screenshots**

![image](https://user-images.githubusercontent.com/894884/109311551-3f4d3380-7846-11eb-98d3-7ecb2728fd7b.png)

![image](https://user-images.githubusercontent.com/894884/109311568-44aa7e00-7846-11eb-8ff6-29b5b1e7583b.png)

"Insert type" works correctly:

![image](https://user-images.githubusercontent.com/894884/109311599-4ecc7c80-7846-11eb-9f26-61c29bc79575.png)

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.0

**Additional context**

none

**Search terms**

none

**Comment by kubukoz** [comment]
Checked again in 0.10.1, it's changed types again! :D

![image](https://user-images.githubusercontent.com/894884/115772962-021da180-a3b0-11eb-86a7-148117f607ab.png)

**Comment by tgodzik** [comment]
> Checked again in 0.10.1, it's changed types again! :D
> 
> ![image](https://user-images.githubusercontent.com/894884/115772962-021da180-a3b0-11eb-86a7-148117f607ab.png)

This is a fun one :O

**Comment by jkciesluk** [comment]
I think its fine now
<img width="505" alt="image" src="https://github.com/scalameta/metals/assets/72950514/ba17f041-c651-4e34-a631-219a1ba13293">
Could you check if it works for you?

**Comment by kubukoz** [comment]
On the latest snapshot I don't seem to be getting any type hints at all... on 1.1.0, at the linked commit (2e96c29483ba82b98a2a05a9842633e448e7f1a7) it's still

<img width="787" alt="image" src="https://github.com/scalameta/metals/assets/894884/5b9114ae-0c50-4d6b-90e2-c4fe7551e2e3">

but on main, with 1.1.0, it's

<img width="791" alt="image" src="https://github.com/scalameta/metals/assets/894884/2d67ddb5-2da7-4789-aef2-493ece1f16a1">

"Insert type" still works correctly. Looks like there's a lot of the `[]`s now:

<img width="426" alt="image" src="https://github.com/scalameta/metals/assets/894884/f99bc1a0-1837-4627-8717-055b10be948f">

<img width="729" alt="image" src="https://github.com/scalameta/metals/assets/894884/f07c1a1b-7440-47cb-994b-da64803e69f6">

<img width="609" alt="image" src="https://github.com/scalameta/metals/assets/894884/889524c0-97d7-4d68-8d00-0c69f63bab6a">

**Comment by tgodzik** [comment]
@kubukoz the linked commit will not work since we no longer release for that version and we moved synthetic decorations to the presentation compiler. If you check the main with the newest snapshot you should see it works properly.

**Comment by tgodzik** [comment]
Let's close this as fixed, let us know if this is still an issue after the next release.
