### ISSUE TITLE
Scala 3 - hover prints full path to package for toplevel symbol

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#2561]
**Describe the bug**

For the following sample:
```scala
val (a, b) = (1, false)
```

Hover on `(a, b)` contains the following text:
```
package object /home/dos65/projects/metals/samples/scala3/src/main/scala/Main$package: (Int, Boolean)
```

**Expected behavior**

Hover should be:
```
package object $packageName: (Int, Boolean)
```

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.0

**Comment by tanishiking** [comment]
Thank you for reporting!
Hmm, I set up a new Scala3 project using  https://github.com/scala/scala3.g8 (scala version 3.0.0-RC1) with the following environment, but I couldn't reproduce it.

- OS: OSX 10.15.7
- Editor VSCode 1.53.2
- Metals version: v0.10.0

(Actually, I couldn't even hover on the tuple,  I could hover on `a` and `b` though)

![scala3-hover](https://user-images.githubusercontent.com/9353584/109647035-34730580-7b9c-11eb-8258-acbdf92e5c16.gif)

Is it possible to share the reproducible setup? @dos65

**Comment by tgodzik** [comment]
The issue is reproducible with a toplevel val without the object `main`

```scala
//Main.scala
val (a, b) = (1, false)
```

The toplevel symbols are a bit weird when it comes to the actual symbol that is constructed.

**Comment by tgodzik** [comment]
Raised it in https://github.com/lampepfl/dotty/issues/11919
