### ISSUE TITLE
Failed to downloand metals on Linux

### ISSUE THREAD

**Issue by karol-wolonciej** [scalameta/metals#2575]
### bug description

after installing from visual studio code marketplace I get this message

> Failed to download Metals, make sure you have an internet connection and the Java Home '/usr/lib/jvm/jdk-14.0.1' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.

I have no idea why it tries to take SDK version  '/usr/lib/jvm/jdk-14.0.1' I dont even have that version

### installation system
* ubuntu 18.04 lts
* visual studio about:
> Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-135-generic

### Additional context
* I have an internet connection
* I have Java Home set 
> $ echo $JAVA_HOME
/home/karol/.sdkman/candidates/java/current
$ sdk current java
Using java version 8.0.232-trava
$ java -version
openjdk version "1.8.0_232b09"
OpenJDK Runtime Environment (build 1.8.0_232b09-201911100919-dcevm8u232b09)
Dynamic Code Evolution 64-Bit Server VM (build 25.232b09-bdcevm8u23209, mixed mode)

* I am not behind proxy

### metals output
> Java home: /usr/lib/jvm/jdk-14.0.1
Metals version: 0.10.0

### vscode settings.json 
> "java.home": "/usr/lib/jvm/java-8-openjdk-amd64",

my first issue ever

**Comment by tgodzik** [comment]
Thanks for reporting! Is it possible that '/usr/lib/jvm/jdk-14.0.1' is set in the workspace settings? They override user settings, so we would use that `javaHome` in Metals.

**Comment by karol-wolonciej** [comment]
unfortunately not.
workspace settings.json look like this
```javascript
{
    "git.ignoreLimitWarning": true,
    "[json]": {

        "editor.quickSuggestions": {
            "strings": true
        },
        "editor.suggest.insertMode": "replace"
    },
    "launch": {

        "configurations": [],
        "compounds": []
    },
    "json.schemas": [
    {
        "fileMatch": [
            "/myfile"
        ],
        "url": "schemaURL"
    }
    ],
    "[java]": {

        "editor.suggest.snippetsPreventQuickSuggestions": false
    },
    "java.project.referencedLibraries": [],
    "terminal.integrated.fontWeightBold": null,
    "files.watcherExclude": {
        "**/target": true
    },
    "[jsonc]": {

        "editor.quickSuggestions": {
            "strings": true
        },
        "editor.suggest.insertMode": "replace"
    }
}
```
user settings.json look like this

```javascript
{
    "terminal.integrated.rendererType": "dom",
    "python.pythonPath": "/usr/bin/python3",
    "extensions.autoUpdate": false,
    "window.zoomLevel": 0,
    "editor.cursorBlinking": "smooth",
    "jupyter.appendResults": false,
    "todohighlight.isEnable": true,
    "workbench.colorTheme": "Monokai Dimmed",
    "vsicons.dontShowNewVersionMessage": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.errors.incompleteClasspath.severity": "ignore",
    "java.configuration.checkProjectSettingsExclusions": false,
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmDelete": false,
    "python.jediEnabled": false,
    "java.home": "/usr/lib/jvm/java-8-openjdk-amd64",
    "files.watcherExclude": {
        "**/.bloop": true,
        "**/.metals": true,
        "**/.ammonite": true
    },
    "editor.minimap.enabled": true,
    "launch": {
    
        "configurations": [],
        "compounds": []
    }
}
```

**Comment by tgodzik** [comment]
I wonder if it's a weird interaction with sdkman? We use https://www.npmjs.com/package/locate-java-home to find the default.

You can use `metals.javaHome` setting to instruct metals to use a specific version.

**Comment by karol-wolonciej** [comment]
I set `metals.javaHome` and it worked. It's not sdkman because I had this problem long before I installed it. Maybe `locate-java-home npm` cant find the proper version?
