### ISSUE TITLE
Invalid syntax error in ammonite multi-stage scripts

### ISSUE THREAD

**Issue by usommerl** [scalameta/metals#2595]
**Describe the bug**
Ammonite has a feature that allows you to divide a script into separate compilation units (See [multi-stage scripts](https://ammonite.io/#Multi-stageScripts)). This is sometimes required, for instance, when you need to add a dependency resolver. Within an Ammonite script, you can use the `@` symbol to indicate the beginning of a separate compilation unit. However, Metals flags the following line as an error because it expects an identifier after the `@` symbol.

**To Reproduce**

Use the following ammonite script and import it with metals:

```
// Ammonite 2.3.8, scala 2.13.4

interp.repositories() ++= Seq(coursierapi.MavenRepository.of("https://jitpack.io"))
@
import $ivy.`io.circe::circe-json-schema:0.1.0`

import io.circe.schema.Schema

val schema = Schema.loadFromString("{}")
println(schema.isSuccess)
```

**Expected behavior**

No errors are reported.

**Screenshots**

![issue_metals_2](https://user-images.githubusercontent.com/4050763/110795202-e1254500-8276-11eb-8ecf-2c202713ed43.png)

**Installation:**

- Operating system: Linux
- Editor: Vim
- Metals version: v0.10.0

**Search terms**

ammonite
multi-stage scripts

**Comment by tgodzik** [comment]
Thanks for reporting! This is related to https://github.com/scalameta/scalameta/issues/2155 and needs to be fixed in scalameta first.

**Comment by kitbellew** [comment]
> Thanks for reporting! This is related to [scalameta/scalameta#2155](https://github.com/scalameta/scalameta/issues/2155) and needs to be fixed in scalameta first.

not sure it should be part of scalameta. after all, it's not part of standard scala. another tool could feasibly come up with a different way to split portions of scala code. scalafmt handles this for `.sc` files, by splitting on `@`.

**Comment by tgodzik** [comment]
> > Thanks for reporting! This is related to [scalameta/scalameta#2155](https://github.com/scalameta/scalameta/issues/2155) and needs to be fixed in scalameta first.
> 
> not sure it should be part of scalameta. after all, it's not part of standard scala. another tool could feasibly come up with a different way to split portions of scala code. scalafmt handles this for `.sc` files, by splitting on `@`.

Hmm... I haven't thought about it this was, but it seems a lot of things are blowing up if we try to split it. I think it might be easier in the end to handle it in the parser. Just add a dialect feature for Ammonite that would just ignore it.

**Comment by tribbloid** [comment]
also affect me, which renders sc files unusable.

The matrix at https://scalameta.org/metals/docs/ should mark support  to ammonite scripts as "incomplete"

**Comment by ckipp01** [comment]
I just added a small note about this in the docs @tribbloid.

**Comment by kitbellew** [comment]
> > > Thanks for reporting! This is related to [scalameta/scalameta#2155](https://github.com/scalameta/scalameta/issues/2155) and needs to be fixed in scalameta first.
> > 
> > 
> > not sure it should be part of scalameta. after all, it's not part of standard scala. another tool could feasibly come up with a different way to split portions of scala code. scalafmt handles this for `.sc` files, by splitting on `@`.
> 
> Hmm... I haven't thought about it this was, but it seems a lot of things are blowing up if we try to split it. I think it might be easier in the end to handle it in the parser. Just add a dialect feature for Ammonite that would just ignore it.

i think you need a new parser, one which returns `Seq[Source]` or a new type altogether, rather than a new dialect. `@` separates ammonite code into rather independent pieces.
