### ISSUE TITLE
Nothing happens when `testFile` is triggered and no semanticdb exists for that path

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2598]
**Describe the bug**

When using the new `testFile` functionality, there is logic that captures the various possible states and shows that to the user. For example if the workspace has errors, if there are no tests in that file etc. One that isn't handled well is if there is no semanticdb for a given path. @alexcardell pointed this out to me on Gitter that when this is the case, nothing really happens in the UI, but in the logs you see

```
SEVERE: Internal error: java.lang.Exception: Semanticdb not found for path.                                         
```

I'm curious what your thoughts are @tgodzik on what to show to the user in this case? Showing "No semanticdb found for this path" is probably not clear at all to the average user, so I'm a bit unsure of what to return. _Or_ do we just leave this case up to the client to handle? I ask because it's the only one that we don't handle here:

https://github.com/scalameta/metals/blob/dc0da653ead60396832d8b783e152acae368b38f/metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala#L408-L447

**Expected behavior**

A clearer message for the user, but I'm not sure what it should be.

**Search terms**

semanticdb dap testFile

**Comment by tgodzik** [comment]
Do any test classes actually exist in this scenario? If semanticdb does not exist then it's highly probably that the code is not compiled either, so we should first check available test classes. If the code is compiled, but semanticdb does not exist I would point to the doctor or alternatively fallback to `ClassFinder`.

**Comment by ckipp01** [comment]
From what was reported, yes there were tests there. That my also my though, the was issues that was causing the project to not be compiled and therefore no semanticdb being produced. However, we do check for errors before we hit that point. I'll try to play around with this a bit. Maybe just saying there is an issue and pointing to the doctor is a good idea.
