### ISSUE TITLE
Overview for Contributors

### ISSUE THREAD

**Issue by tpolecat** [scalameta/metals#261]
I think an overview of all the moving parts (with boxes-and-arrows diagram) would be helpful for potential contributors.

**Comment by olafurpg** [comment]
You mean something like this?


![scalameta 2flanguage-server 2](https://user-images.githubusercontent.com/1408093/38434917-608eef78-39d0-11e8-83b0-855369422150.png)

**Comment by olafurpg** [comment]
That's a rough reflection of the current structure, some things I expect to evolve are

* there will be a per-project persistent SQL index for definition/references to make subsequent startups faster and lower memory usage
* BSP might make importing the build smoother https://github.com/scalacenter/bsp/blob/master/docs/bsp.md

Heads up, https://github.com/scalameta/metals/issues/239 will likely touch a large part of the codebase. That's the biggest blocking issue for v0.1

**Comment by olafurpg** [comment]
Are there any parts in particular that you are interested in?

**Comment by olafurpg** [comment]
The diagram is not in the repo, we should include it in contributor.md.

The best place to start is likely https://github.com/scalameta/metals/blob/e5bbcd2d23aa14f82090905eccb345d6b6f4f5c7/metals/src/main/scala/scala/meta/metals/MetalsServices.scala#L107-L374 I had never used Monix when starting this project but I found observables were a nice abstraction to encode some of the streaming notifications that come from the editor/build.

**Comment by olafurpg** [comment]
The codebase has been rewritten from scratch so everything from my comments above are no longer relevant.

Docs on building the repo are here https://scalameta.org/metals/docs/contributors/getting-started.html I'm happy to answer further question on gitter https://gitter.im/scalameta/metals and follow-up on that to improve the contributing docs.
