### ISSUE TITLE
[Scala3] No definition for extension parameter symbol

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#2627]
In #2600 ScalaMtags got initial support for extension methods but it doesn't cover parameters -https://github.com/scalameta/metals/blob/8f78cf55fc46e8b6fcdb7061b57b8dc4900a94df/mtags/src/main/scala-2/scala/meta/internal/mtags/ScalaMtags.scala#L248-L250

This issue is just a reminder to complete `extension methods` after [this issue in Scala3](https://github.com/lampepfl/dotty/issues/11690) will be fixed.

**Comment by tanishiking** [comment]
Gonna work simultaneously with https://github.com/scalameta/metals/issues/3133 as the issue requires a fix also in mtags .
