### ISSUE TITLE
Stale diagnostic in downstream targets 

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#2670]
Diagnostic isn't cleaned for downstream projects in case if an error arises in upstream targets.

For example, there are two targets: `a`, `b` where `b` depends on `a` an there is an error in `b`
```scala
// a/src/main/scala/example/Foo.scala
package example
trait Foo {
  def foo: Int
}

class Foo1 extends Foo {
  def foo: Int = 42
}

// b/src/main/scala/example/Bar.scala
package example
class Bar extends Foo
// ^[error] class Bar needs to be abstract, since method foo in trait Foo of type => Int is not defined"
```

Then if `trait Foo` will be deleted from `a` an error in `b` will be the same and it even possible to run `Implement all members`
```scala
package example
class Foo1 extends Foo {
                   //^[error] not found type: Foo
  def foo: Int = 42
}

// b/src/main/scala/example/Bar.scala
package example
class Bar extends Foo
//^[error] class Bar needs to be abstract, since method foo in trait Foo of type => Int is not defined"
```

It isn't really critical but sometimes the old error is rendered at the top in `Problems` list that adds some confusion.

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.0

**Comment by tgodzik** [comment]
Thanks fro reporting! That is actually expected, since we don't want to run cascade compile by default.  However, I think we can improve this behaviour for errors - we could detect if an error is in a downstream project and also run the compilation there.

**Comment by dos65** [comment]
@tgodzik it probably won't work. At least that's how sbt/bloop clients behave.
In the case that I described if you run `compile b` they both will produce errors only about `a`. But I'm not really familiar with this part of BSP.

**Comment by tgodzik** [comment]
I mean, if there are errors in files that are contained in downstream projects, we can calculate it directly and manually run via BSP. So that should work ok.
