### ISSUE TITLE
Rename doesn't work in for-comprehension when it contains "=" operator

### ISSUE THREAD

**Issue by chessman** [scalameta/metals#2679]
```
    for {
      abc <- List("a", "b", "c")
      _ = println("print!")
    } yield abc
```

**To Reproduce**

Case 1:

1. Place a cursor on the first "abc".
2. Call lsp-rename and type "cba".
3. Result: only the first "abc" is renamed.

Case 2:

1. Place a cursor on the second "abc" (after yield).
2. Call lsp-rename and type "cba".
3. Result: the first "abc" is renamed to "cbaabc".

But if I remove `_ println("print!")`, it works correctly.

**Expected behavior**

"abc" should be renamed to "cba" for all occurrences.

**Installation:**

- Operating system: Linux
- Editor: Emacs
- Metals version: v0.10.0

**Comment by dos65** [comment]
Thanks for reporting! I'm able to reproduce that.

It also behaves strangely on renaming reference to `yield <<abc>>`  but in this case it append new name to existing
```scala
for {
  first <- List("a", "b", "c")
  _ = println("print!")
} yield <<f@@irst>>

// result
for {
  firstsecond <- List("a", "b", "c")
  _ = println("print!")
} yield second
```

**Comment by tgodzik** [comment]
It seems that the value is wrongly identified in semanticdb as being different variable:
```
  Vector(
    SymbolOccurrence(Some(Range(3, 8, 3, 15)), "scala/Predef.println(+1).", REFERENCE),
    SymbolOccurrence(Some(Range(0, 7, 0, 8)), "_empty_/A.", DEFINITION),
    SymbolOccurrence(Some(Range(2, 4, 2, 7)), "local0", DEFINITION),
    SymbolOccurrence(Some(Range(2, 11, 2, 15)), "scala/collection/immutable/List.", REFERENCE),
    SymbolOccurrence(Some(Range(4, 10, 4, 13)), "local1", REFERENCE)
  ),
```
`local1` and `local0` is the same thing really. We should fix it in semanticdb.

**Comment by kasiaMarek** [comment]
https://github.com/scalameta/metals/pull/5132
