### ISSUE TITLE
Rename doesn't work for classOf

### ISSUE THREAD

**Issue by chessman** [scalameta/metals#2681]
```
  case class Test(s: String)
  val a = classOf[Test]
```

**To Reproduce**

Case 1:

1. Try to rename the case class.
2. Result: the case class is renamed, `classOf[Test]` is not renamed.

Case 2:

1. Try to rename "Test" in classOf.
2. Result: emacs shows a message "'lsp-rename' is invalid here".

**Expected behavior**

The class inside `classOf` is also renamed.

**Installation:**

- Operating system: Linux
- Editor: Emacs
- Metals version: v0.10.0
- Scala: 2.12.13

**Comment by tgodzik** [comment]
Thanks for reporting! This is caused by https://github.com/scalameta/scalameta/issues/1909

We've put some time into figuring that one out, but seems we need to fix it in the compiler itself.

**Comment by tgodzik** [comment]
This is now working and there us a test for it.
