### ISSUE TITLE
Renaming constructor parameters works strange with inheritance

### ISSUE THREAD

**Issue by chessman** [scalameta/metals#2683]
There might be a few bugs.

```
  class A(abc: String)
  class B(abc: String) extends A(abc)
```

When I rename constructor parameters of any class, I get

```
  class A(abc2: String)
  class B(abc2: String) extends A(abc)
```

Both constructors are modified but the parameter passed to superclass is not.

I expect that only one constructor is modified and the passed parameter is also changed if renaming happens in class B.

When I do renaming in "extends A(abc)", I get something weird:

```
  class abc2(abc: String) extends A(abc2)
```

**Installation:**

- Operating system: Linux
- Editor: Emacs
- Metals version: v0.10.0
- Scala: 2.12.13

**Comment by tgodzik** [comment]
Thanks for reporting! That seems to be partly fixed in the soon-to-be release. The only remaining issue seems to be a test case:
```
  renamed(
    "inherit",
    """|/a/src/main/scala/a/Main.scala
       |  class A(<<abc>>: String)
       |  class B(<<abc>>: String) extends A(<<ab@@c>>)
       |""".stripMargin,
    newName = "cba"
  )
```
If we rename from the abc reference, it will be a symbol:
`_empty_/B#`<init>`().(abc)`, which doesn't actually have a definition and we revert to presentation compiler definition, which seems to return wrong ranges here. Definition is needed here in order to find the exact inheritance hierarchy.

We should fallback to `_empty_/B#abc.` for primary constructor params.

**Comment by chessman** [comment]
@tgodzik I checked on v0.10.1, now it handles "extends A(abc)". But it still renames parameters in all classes when renaming was called only on one of them.

Example:
```
  class A(ab@@c: String)
  class B(abc: String) extends A(abc)
```
produces
```
  class A(cba: String)
  class B(cba: String) extends A(cba)
```
But I expect
```
  class A(cba: String)
  class B(abc: String) extends A(abc)
```
Since this parameter is private, it should not affect parent from child and vice versa.

**Comment by tgodzik** [comment]
> @tgodzik I checked on v0.10.1, now it handles "extends A(abc)". But it still renames parameters in all classes when renaming was called only on one of them.
> 
> Example:
> 
> ```
>   class A(ab@@c: String)
>   class B(abc: String) extends A(abc)
> ```
> 
> produces
> 
> ```
>   class A(cba: String)
>   class B(cba: String) extends A(cba)
> ```
> 
> But I expect
> 
> ```
>   class A(cba: String)
>   class B(abc: String) extends A(abc)
> ```
> 
> Since this parameter is private, it should not affect parent from child and vice versa.

Ah right! I haven't really thought about it. We should fix it together with the other issue.

**Comment by tgodzik** [comment]
Also, we can now use a new field in semanticdb that points to parent symbols, which should also solve this problem.

**Comment by tgodzik** [comment]
Fixed most likely by https://github.com/scalameta/metals/pull/3047
