### ISSUE TITLE
Unexpected import when using insert inferred type and the import has been renamed

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2686]
**Describe the bug**

When using the new insert inferred type code action and you are importing something that is already in scope, but the import was renamed, it will insert the old un-renamed import package.

**To Reproduce**

Take a look in the Metals code base for example in `InsertInferredType.scala` and try to insert the inferred type where the `@@` is down below.

```scala
import org.eclipse.{lsp4j => l}

class InsertInferredType(trees: Trees, compilers: Compilers)
    extends CodeAction {

  import InsertInferredType._
  override def kind: String = l.CodeActionKind.QuickFix

  override def contribute(
      params: l.CodeActionParams,
      token: CancelToken
  )(implicit ec: ExecutionContext): Future[Seq[l.CodeAction]] = Future {

    def insertInferTypeAction(title: String): l.CodeAction = {
      val code<<@@>>Action = new l.CodeAction()
```

I'd expect for this to give me:

```scala
      val codeAction: l.CodeAction = new l.CodeAction()
```

But what I really get is:

```scala
      val codeAction: lsp4j.CodeAction = new l.CodeAction()
```

1. Go to the file in Metals
2. Insert the inferred type
3. See result

**Installation:**
- Metals version: v0.10.1

**Search terms**

insert inferred type with renamed package

**Comment by tgodzik** [comment]
Thanks for finding that one! Seems it might be an issue with auto imports. Does it work with `implement all abstract members` action?

**Comment by ckipp01** [comment]
> Does it work with implement all abstract members action?

This seems to work as expected. Given:

```scala
import java.time.{Instant => I}

trait Main {
  def a: I
  def b: I
}

class Thing extends Main {
}
```
When I trigger the code action I get:

```scala
import java.time.{Instant => I}

trait Main {
  def a: I
  def b: I
}

class Thing extends Main {

  override def a: I = ???

  override def b: I = ???

}
```
So that looks good.
