### ISSUE TITLE
"Implement all members" not working on nested traits

### ISSUE THREAD

**Issue by shotexa** [scalameta/metals#2707]
**Describe the bug**

"Implement all members" on traits is not working when this trait is nested inside an object but works when the trait is on top 
level

**To Reproduce**

Use this code:
```scala
object Outer {

  trait Nested {
    def foo: String
  }
}

trait TopLevel {
  def bar: String
}

new TopLevel {}
new Outer.Nested {}
```

1. Place your cursor on the line where `new TopLevel {}` is written
2. A popup will appear, similar to this:
  - <img width="489" alt="Screen Shot 2021-04-13 at 10 36 50 PM" src="https://user-images.githubusercontent.com/12943302/114603518-dfe99c80-9ca8-11eb-954b-5212f52c6039.png">
3. Click "quick fix"
4. You will be prompted with the "Implement all members" option, click it
  - <img width="376" alt="Screen Shot 2021-04-13 at 10 38 53 PM" src="https://user-images.githubusercontent.com/12943302/114603887-525a7c80-9ca9-11eb-888c-5844372c99b2.png">
5. The definition of `new TopLevel {}` will be populated like this
  - <img width="334" alt="Screen Shot 2021-04-13 at 10 41 27 PM" src="https://user-images.githubusercontent.com/12943302/114603937-656d4c80-9ca9-11eb-825a-fdb1df7755ba.png">
6. Repeat all steps from 1 to 4 for `new Outer.Nested {}`
7. The definition of `new Outer.Nested {}` will not be populated the same way as the definition of `new TopLevel {}` 

**Expected behavior**
On a step 7, the definition of `new Outer.Nested {}` should be populated the same way as the definition of `new TopLevel {}` 

**Video**

https://user-images.githubusercontent.com/12943302/114604672-415e3b00-9caa-11eb-9e5f-b35da63a3fc5.mov

**Installation:**

- Operating system: macOS Big Sur Version 11.2.3
- Editor: Visual Studio Code
- Metals version: v0.10.1

**Additional context**

I used bloop as a build server.

**Comment by tgodzik** [comment]
Thanks for reporting! The actual problem seems to be that the `Implement all members` do not work if there are `.` used.

This will work:
```scala
object Main{
  object Outer {
  trait Nested {
    def foo: String
  }
}

import Outer.Nested
  new Nested {}
}
```

**Comment by mdbergmann** [comment]
Hi.

I just was to look if there is already a bug raised.
"Implement all members" doesn't work here also for abstract classes, but only for traits.
Is this known?

**Comment by tgodzik** [comment]
> Hi.
> 
> I just was to look if there is already a bug raised.
> "Implement all members" doesn't work here also for abstract classes, but only for traits.
> Is this known?

That's mostly likely caused by the same thing.
