### ISSUE TITLE
2021.04.15 10:36:06 WARN  Could not find java sources in None. Java symbols will not be available.

### ISSUE THREAD

**Issue by matheussbernardo** [scalameta/metals#2724]
**Describe the bug**

I cant go to java sources

**To Reproduce**

**Expected behavior**

**Screenshots**

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.10.1

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! This usually means that JDK sources are not available in your `JAVA_HOME/lib` directory.

Are you able to find them? You might need to install them separately as explained [here](https://stackoverflow.com/questions/2896727/where-to-find-java-jdk-source-code)

**Comment by matheussbernardo** [comment]
Solved!

**Comment by PhilParisot** [comment]
Hey @matheussbernardo how did you solve this issue? I'm having the same on Ubuntu 20.04

**Comment by tgodzik** [comment]
source jar are not downloaded by default in some distributions. I am adding info to show what was searched in https://github.com/scalameta/metals/pull/3606

@PhilParisot Are you using some symlinks etc to set the Java path?

**Comment by PhilParisot** [comment]
Hey @tgodzik I got it fixed by installing `sudo apt insall openjdk-11-source`.

Thanks for the quick reply!
