### ISSUE TITLE
[Bug] Cannot view the value of the expression in debugging

### ISSUE THREAD

**Issue by XuJinNet** [scalameta/metals#2725]
**Describe the bug**

When debugging, i want to view the value of a expression, but it report "an implementation is missing".

**Screenshots**

![image](https://user-images.githubusercontent.com/442382/114880256-7dbda280-9e34-11eb-8424-6c650d7dac81.png)

**Installation:**

- Operating system: Windows 10 + WSL2
- Editor: Visual Studio Code
- Metals version: v0.10.1
- JDK: Oracle JDK 8

**Comment by tgodzik** [comment]
Thanks for reporting! This is not a bug actually, it will not work until Expression Evaluator is implemented. You can subscribe to https://github.com/scalameta/metals-feature-requests/issues/83 to be up to date. We are currently working on it, but can't promise any real timeline.
