### ISSUE TITLE
Incorrect symbol information

### ISSUE THREAD

**Issue by AurimasAnskaitis** [scalameta/metals#2742]
**Describe the bug**

In VsCode, listing all symbols gives wrong information when there are multiple objects inside top object.
I suspect that related issue is that such symbols are not suggested for import in quick fix list.

**To Reproduce**

This is the repository where the bug is reproduced.
https://github.com/AurimasAnskaitis/metalsBug
After project import, press Ctrl+T and enter "C2" (C2 is a case class). Observe the path shown for this symbol.
It should be A.B2.C2 but is quite different.

**Expected behavior**

**Screenshots**

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: current stable version shipped with vscode, but I notice this bug for a long time, and only now it was reproduced in minimal project.

**Comment by tgodzik** [comment]
Thanks for reporting! So in case someone has different shortcuts, we are talking about the workspace symbol functionality:

![image](https://user-images.githubusercontent.com/3807253/116281855-66fb4200-a78a-11eb-9a81-dd921de71a15.png)

I can confirm that this is the case.
