### ISSUE TITLE
Can't debug if file with Scalafix config was found

### ISSUE THREAD

**Issue by sergeda** [scalameta/metals#2748]
**Describe the bug**

Now it's not possible to find out why Scalafix config was not used during Optimize Import

**To Reproduce**

1. Point metals.scalafixConfigPath to non-existing file
2. Try to use Optimize Import feature
3. There is no log in metals.log

**Expected behavior**

Error should be logged to metals.log

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code
- Metals version: v0.10.2

**Additional context**

This function should be modified https://github.com/scalameta/metals/blob/5c96ad297cd20bbdf5b58bebdde67bf9c0a07d08/metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala#L134-L139

**Search terms**

Scalafix

**Comment by tgodzik** [comment]
Thanks for reporting! This should be a simple fix, I will take a quick look.
