### ISSUE TITLE
Tests are failing on Windows

### ISSUE THREAD

**Issue by martijnhoekstra** [scalameta/metals#276]
Tests are failing on Windows. Some failures seem spurious (i.e. tests themselves are broken, around line endings in multiline strings giving wrong offests with /r/n line endings), while others seem to be based around actual defects around `Uri`. In project `metals`

```
Tests: 115, Passed: 99, Failed: 16
[info]
[error] Failed tests:
[error]         tests.search.SymbolIndexTest
[error]         tests.mtags.JavaMtagsTest
```

in project `integration`

```
Tests: 1, Passed: 0, Failed: 1
[info]
[error] Failed tests:
[error]         tests.sbtserver.SbtServerTest
```

**Comment by olafurpg** [comment]
CI runs tests on Windows for every pull request. It may be that some functionality is still not working well on Windows but in that case we can open specific issues for those cases so they can be fixed individually.
