### ISSUE TITLE
Value class inside an object gives error: "value classes may not be a member of another class - mdoc"

### ISSUE THREAD

**Issue by njlbenn** [scalameta/metals#2764]
**Describe the bug**

In a worksheet I encounter the error `value classes may not be a member of another class - mdoc` when I try to define a Value Class inside an object.

**To Reproduce**

Try to insert code like the following into a worksheet:

```
object Foo {
  case class Bar(b: Int) extends AnyVal
}
```

The worksheet in this case fails to compile and the error displayed is "value classes may not be a member of another class - mdoc"

**Expected behavior**

That this compiles as it does, say, in the vanilla Scala REPL

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

object Foo {
  case class Bar(b: Int) extends AnyVal
}

// Exiting paste mode, now interpreting.

defined object Foo
```

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.2

**Additional context**

The worksheet is in a standalone context -- i.e. it is not part of a Scala project -- and I have explicitly set the `fallbackScalaVersion` to be 2.13.5

**Comment by tgodzik** [comment]
Thanks for reporting! This is an issue in mdoc, looking at it here https://github.com/scalameta/mdoc/pull/492

For now the best workaround is to have the value class inside normal source and just import it into a workshett.

**Comment by olafurpg** [comment]
FWIW, you can try to not use `AnyVal`. I would be surprised if you notice a performance difference when evaluating your worksheet.

**Comment by njlbenn** [comment]
> FWIW, you can try to not use `AnyVal`. I would be surprised if you notice a performance difference when evaluating your worksheet.

@olafurpg ah, this was just some toy code to demonstrate the use of `AnyVal` - the use wasn't motivated by performance. So the bugfix isn't critical for me. Just thought I would report it

**Comment by tgodzik** [comment]
We need to fix it differently or document it as unsupported in the worksheets.
