### ISSUE TITLE
No autocompletion or import quickfix for types with backticks

### ISSUE THREAD

**Issue by chessman** [scalameta/metals#2768]
**Describe the bug**

**To Reproduce**

1. Add akka-http to dependencies.
2. Write `` `Set-Cookie` ``.

No autocompletion or import suggestions.

**Expected behavior**

Autocompletion during typing and a suggestion about importing `` akka.http.scaladsl.model.headers.`Set-Cookie` `` should appear.

**Installation:**

- Operating system: Linux
- Editor: Emacs
- Metals version: v0.10.2

**Comment by tgodzik** [comment]
Thanks for reporting! This is the same issue as https://github.com/scalameta/metals/issues/2496

Both use the same mechanism for imports.
