### ISSUE TITLE
Problems moving to scala 3.0.0-RC3 with sbt as build processor for metals

### ISSUE THREAD

**Issue by DavidGoodenough** [scalameta/metals#2776]
taking an existing scala-2 project and moving to scala-3 if I select sbt as the build processor it timesout.  Rebuilding the bspConfig helps but it still says that the project is misconfigured and when I ask for more details it shows the doctor with everything ticked but the following recommendation:-

Add the compiler option "-P:semanticdb:sourceroot:/home/david/src/OpenBusiness/UblBase" to ensure code navigation works.

**Comment by DavidGoodenough** [comment]
The problem however persists.  When I choose sbt as BSP it times out, when I choose Bloop it works.  The message was the only diagnostic I could see.  If there is more information in a log somewhere please let me know what to look at.

**Comment by DavidGoodenough** [comment]
The problem still seems to exist in the current metals snapshot.  It is still trying to connect after 5 minutes, and in the .metals/metals.log is just says that it timed out and is retrying.  Is there anything I can do to get more information?

**Comment by DavidGoodenough** [comment]
Eventually it gave up and returned:-
```
2021.05.17 12:01:25 ERROR Timeout waiting for 'build/initialize' response
2021.05.17 12:01:25 ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:369)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:283)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

**Comment by tgodzik** [comment]
There shouldn't be any changes to how sbt BSP works recently. Just to confirm, it was broken in v0.10.2 and is still broken in the SNAPSHOT? what is your system and sbt version?

**Comment by DavidGoodenough** [comment]
The only thing that changed was that I started using first scala 3.0.0-RC3 and now 3.0.0.  Up until that change I could use sbt as a BSP with no problems, it was faster than bloop.  But as soon as I moved to 3 of any kind it just stopped worked.  And this is over multiple projects.
I am running on Linux (Debian sid up to date), Java 11, vscodium.

**Comment by tgodzik** [comment]
@adpi2 any idea what can cause sbt not allow Metals to connect ?

@DavidGoodenough do you still have the dotty plugin? (it it no longer needed)

**Comment by DavidGoodenough** [comment]
No, these were 2.13.5 projects and I did not try 3 until 3.0.0-RC3 with sbt 1.5.1, so no dotty plugin.

**Comment by DavidGoodenough** [comment]
@tgodzik Does it matter that I am using an old style "flat" build.sbt files?  I found a reference to this old flat style leading to this kind of problem searching for "no build target: using presentation compiler with only scala-library: 2.12.13"  which I found in .metals/metals.log.  I have tried updating to the style recommended in the Sbt manual (i.e. wrapping all the settings in 
```
lazy val root = project.in(file("."))
  .settings(
<comma separated list of settings>
)
```
but it made no difference.

**Comment by DavidGoodenough** [comment]
Correction.  After I told it to attempt to build the bsp config and it now seems to work.  I will try the same with the other projects I am working on

**Comment by DavidGoodenough** [comment]
The problem came back, so whatever the bsp config did obviously got undone, but no messages in the log give a hint as to what it might be

**Comment by tgodzik** [comment]
Do you have maybe a project that it reliably fails on? Maybe it's the Scala 3 sample project? or doe sit work there?

**Comment by adpi2** [comment]
You can also try to run the argv command in the `.bsp/sbt.json` manually and see if it fails or if it prints an error.

**Comment by DavidGoodenough** [comment]
@adpi2 You may have hit the jackpot.  The argv reads:-
```
/usr/lib/jvm/java-11-openjdk-amd64/bin/java","-Xms100m","-Xmx100m","-classpath","/tmp/metals18014374008384808451/sbt-launch.jar","xsbt.boot.Boot","-bsp","--sbt-launch-jar=/tmp/metals18014374008384808451/sbt-launch.jar
```
and in /tmp there are six metals* directories, each with an identical sbt-launch.jar, they were even all created at the same time:-
```
/tmp/metals14404064187890208509:
-rw-r--r--  1 david david 1394954 May 21 10:32 sbt-launch.jar

/tmp/metals14450364274530651704:
-rw-r--r--  1 david david 1394954 May 21 10:01 sbt-launch.jar

/tmp/metals15234631072776552504:
-rw-r--r--  1 david david 1394954 May 21 10:34 sbt-launch.jar

/tmp/metals303140741420779490:
-rw-r--r--  1 david david 1394954 May 21 11:50 sbt-launch.jar

/tmp/metals3568556089914030377:
-rw-r--r--  1 david david 1394954 May 21 11:50 sbt-launch.jar

/tmp/metals5242734500449640221:
-rw-r--r--  1 david david 1394954 May 21 10:35 sbt-launch.jar
```
(I edited this output to eliminate the . and .. files).  Running diff on the files shows that they are all identical.

But the important thing is that none of these directories have the name in the argv classpath!

**Comment by DavidGoodenough** [comment]
Given that /tmp is cleared on each reboot and otherwise every 10 days on a Debian system, why are the jar files being stored there with names hard coded into the argv file?

**Comment by adpi2** [comment]
@tgodzik is it Metals that creates and clears those `sbt-launch.jar`?

**Comment by tgodzik** [comment]
Good catch!

Metals uses that sbt jar to run sbt commands when no sbt script is specified. You should be able to fix that in the settings and rerun generating config.

Longer term, since this is being written to `.bsp` directory, we might want to save that jar to `.metals` directory in that case. Previously, that was not an issue with Bloop import.

**Comment by DavidGoodenough** [comment]
How much do I need to put in the settings?  Is it just java -jar /usr/share/sbt/bin/sbt-launch.jar ?

**Comment by tgodzik** [comment]
If you va SBT on path it should be enough to put 'sbt'

**Comment by DavidGoodenough** [comment]
@tgodzik That seems to have done the trick, at least for now.  We will see when I reboot tomorrow morning - but obviously as I am no longer using /tmp this should work.

**Comment by ckipp01** [comment]
I actually just looked at this. The change necessary to store this in `.metals/` is pretty simple and seems to work. However, before sending a PR for this, I want to make sure this is actually what we want to do @tgodzik seeing that this will create this `sbt-launch.jar` in _every_ workspace then.

Sort of a related questions, but I don't think this is fully working as intended:

https://github.com/scalameta/metals/blob/195e88162d040462a7e51c603ce59881f940b9fa/metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala#L35-L39

We actually have this set to `deleteOnExit`, which seems to not actually be working?

**Comment by tgodzik** [comment]
> seeing that this will create this sbt-launch.jar in every workspace then.

Could we only create it only if we are generating bsp config?

> We actually have this set to deleteOnExit, which seems to not actually be working?

Hmm... I thought that it's working, I can't find too many metals dir in my tmp.

**Comment by ckipp01** [comment]
> Could we only create it only if we are generating bsp config?

Yea, that's doable.

> Hmm... I thought that it's working, I can't find too many metals dir in my tmp.

😬 I see literally over 20 in mine.

**Comment by tgodzik** [comment]
That might be system dependent then :thinking:

**Comment by DavidGoodenough** [comment]
@ckipp01 Presumably the jar is being downloaded by coursier (or the like), why not just use it direct from wherever they store it?

**Comment by ckipp01** [comment]
> @ckipp01 Presumably the jar is being downloaded by coursier (or the like), why not just use it direct from wherever they store it?

I know historically there were issues with using `sbt` because it didn't always resolve correctly on windows. Basically having full control over it gives us the greatest guarantee that sbt will behave the way we need it to insure that things like `sbt bloopInstall` work the way we want them to. For most user, just using `sbt` may work fine, but there may be a handful that it doesn't, and it'd probably be pretty difficult to debug.

**Comment by tgodzik** [comment]
> @ckipp01 Presumably the jar is being downloaded by coursier (or the like), why not just use it direct from wherever they store it?

I am not sure if coursier can download the launcher jar, it's not a normal sbt artifact.
