### ISSUE TITLE
Autocomplete's import mechanism resolves incorrect prefix

### ISSUE THREAD

**Issue by kovacshuni** [scalameta/metals#2777]
Autocomplete inserts wrong classname with fully qualified name but with an additional classname that is not relevant at all, hence making a compilation error. Plus the import doesn't happen on top of the file, just the inline action is happening and it's incorrect.

**To Reproduce**

Trying to type `Reduci`... a dropdown comes down, with the relevant Reducible to import. Good until now.
```
  private def values[F[_]: Reducible, A: util.Put](f: Fragment, fs: F[A]): Fragment =
    fs.toList.map(a => fr0"$a").foldSmash1(f ++ fr0"VALUES ((", fr"),(", fr"))")
```

When I hit enter
```
  private def values[F[_]: ConnectionIO.cats.Reducible, A: util.Put](f: Fragment, fs: F[A]): Fragment =
    fs.toList.map(a => fr0"$a").foldSmash1(f ++ fr0"VALUES ((", fr"),(", fr"))")
```

This is what is inserted/autocompleted. `ConnectionIO.cats.Reducible` makes no sense. Import on top of the file doesn't happen. Happened multiple times, in all other classes, deterministically I think.

**Expected behavior**

Autocomplete `Reducible`
Import on top of the file `cats.Reducible`

**Screenshots**

![Screen Shot 2021-05-13 at 11 19 04](https://user-images.githubusercontent.com/1782646/118106445-e8371380-b3dd-11eb-8d04-03eb1565e12e.png)

![Screen Shot 2021-05-13 at 11 19 15](https://user-images.githubusercontent.com/1782646/118106456-eb320400-b3dd-11eb-89db-88e25a19dad6.png)

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.2

**Search terms**

autocomplete, import, prefix, broken, incorrect, dropdown, package, path, classname,

**Comment by tgodzik** [comment]
Thanks for reporting! This is already fixed in https://github.com/scalameta/metals/issues/2736 and will be released with the new version, which is coming up around the Scala 3.0.0 release (so soon). You can use a SNAPSHOT version to test it out.

**Comment by kovacshuni** [comment]
Thank you, Sorry for the double

**Comment by tgodzik** [comment]
No worries, it's better to report it, it's a bug that shows up differently each time.
