### ISSUE TITLE
[Scala3] PC - implement `completionItemResolve`

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#2778]
That should fix the appearance of [parameters in java method](https://github.com/scalameta/metals/pull/2728/files#diff-bc062509d1f058362f8a7d42786ea2cd967d8740ee3493db5e46f25f004aa6dbR97-R102) / default parameter values in scala methods  + documentation.

Note: this will require to complete `inverseSemanticdbSymbol` implementation for scala 3 - [link](https://github.com/scalameta/metals/pull/2728/files#diff-f3acf80356cda52b391ba942de811673a383488c2b5d52e0688c4c298d235e8aR50-R66)

**Comment by simlei** [comment]
Made a MRE for demonstrating it's not yet there, in the context of NVIM + nvim-metals. Would love this feature!
https://github.com/simlei/MRE_fetchlibdocs

**Comment by tgodzik** [comment]
Actually, this was fixed in https://github.com/scalameta/metals/pull/3914
