### ISSUE TITLE
Completions, higher-kinded types and match types

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#2810]
**Describe the bug**

Completions don't show up on members of a higher-kinded type if it's been applied with a match type (at least with non-standard types).

**To Reproduce**

1. Create a file with this content:

```scala
trait IO[A] {
  def map[B](f: A => B): IO[B]
}

case class User[F[_]](age: F[Int])

type M[A] = A match {
  case Int => IO[Int]
}
```

2.  Now add:

```scala

def demo(x: M[A]) =
  x.age
```

and try to run completions on `.age`.

**Expected behavior**

Seeing `map` in the completions

**Screenshots**

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/894884/118808444-d2c45c80-b8a9-11eb-9e9c-15aa5a3ec17b.png">

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.3

**Additional context**

The methods show up if `M[A]` results in different types, but I'm under the impression we only see members of some supertypes. For example, `List[Int]`:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/894884/118808731-18812500-b8aa-11eb-8327-c7710cc5cea3.png">

The `foldLeft` method on LinearSeq (the one I can navigate to) isn't deprecated - the one I see is probably from `IterableOnceOps` (that one is deprecated).

**Search terms**

match types, type matching, hkd, higher kinded data, completions

**Comment by tgodzik** [comment]
Thanks for reporting! I think match types are currently not that well supported in Dotty, we need to follow up in the compiler to see what's going on.

**Comment by tanishiking** [comment]
I confirmed this is fixed by https://github.com/lampepfl/dotty/pull/14639 in the latest nightly Scala3 version, thanks @rochala !
I'll add a test on Metals side
