### ISSUE TITLE
Unable to see argument names of a method

### ISSUE THREAD

**Issue by bilal-fazlani** [scalameta/metals#2811]
**Unable to see argument names of a method**

When 

**trying to use an existing method with one or more arguments in Scala 3**

1. Type a method name
2. Open parentheses 
3. Type a comma

**Expected behavior**

Should see argument names of the method

**Screenshots**

![image](https://user-images.githubusercontent.com/3396271/119030153-27112e80-b9c7-11eb-8388-f9251b04db2f.png)

![image](https://user-images.githubusercontent.com/3396271/119031190-7146df80-b9c8-11eb-9753-d2ca585490c6.png)

**Installation:**

- Operating system: macOS BigSur
- Editor: Visual Studio Code
- Metals version: v1.10.5
- Scala version: 3.0.0

**Comment by dos65** [comment]
Thanks for reporting!

It' because LSP method `completionMethod/resolve` isn't implemented for Scala3 - #2778

**Comment by tgodzik** [comment]
Thanks for reporting! As @dos65 it's related to the other issue. You can follow it for updates.
