### ISSUE TITLE
Metals process doesn't exit after closing VS Code

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#2820]
1. Open Vscode and wait when Metals fully start
2. Do Reload Window (CTRL +R ) / Close editor
3. Check processes: ` ps ax | grep metals` - there will be handed one

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.3

**Additional context**

The interesting thing that this situation doesn't happen in the case of the usual exit from VSCode.
It might be related to `PC` shutdown. I noticed that the hanging process has one running `PC` thread.

**Comment by tgodzik** [comment]
Thanks for reporting! I think I found it recently also, but this might be more to do with the metals-vscode plugin? Or alternatively we can add a timeout in the shutdown method to make sure it's always shutdown?

**Comment by dos65** [comment]
__Update__: I just found that the same happens even in case if the editor was closed in the usual manner.
Will change the title.

@tgodzik Are you about `ScalaPresentationCompiler.shutdown` method?
According to `thread dump`, PC thread stucks at [`waitForMoreWork`](https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-2/scala/tools/nsc/interactive/MetalsGlobalThread.scala#L24)

**Comment by tgodzik** [comment]
Maybe shutdown is never run? I meant the shutdown method in the MetalsLanguageServer, it should cancel everything and exit.

**Comment by dos65** [comment]
I will try to investigate it deeper.

I've already tried to fix it but without success and `cancel` were called correctly.

**Comment by MRandl** [comment]
Is this the same as #2722 ? If so this is a known feature

**Comment by dos65** [comment]
@MRandl it's a different one. In this case, I can confirm that a dangling process is Metals itself
