### ISSUE TITLE
Help users to setup Metals

### ISSUE THREAD

**Issue by laughedelic** [scalameta/metals#284]
I suggest that we check several things that Metals should have if everything is setup well:
* presence of `.metals/buildinfo/*` directories
* presence of `**/*.semanticdb` files
* anything else?

Then there are 2 possibilities: 
* just warn the user about this and tell them that most features won't work + link to the relevant docs
* if the project happens to use sbt 1.1+,
    + but it's not connected, tell user to launch sbt,
    + if it's connected, check that sbt-metals is active and _suggest_ (`showMessageRequest`) or just automatically run `metalsSetup` (or only `semanticdbEnable`),
    + if sbt-metals is not detected, warn about it and link to the relevant docs

The non-interactive warning is good because it helps first-time users or those who _forgot_ to read the docs 😉  
And an interactive warning through sbt integration let's you get ready in fewer manual steps.

Related: https://github.com/laughedelic/atom-ide-scala/issues/35

**Comment by laughedelic** [comment]
About sbt-metals detection: I wanted to use `sbt/setting`, query `*/commands` and check if `metalsSetup` or `semanticdbEnable` are present. But this didn't work: https://github.com/sbt/sbt/issues/4092.

As a workaround we can add some setting key in sbt-metals (for example, `semanticdbVersion`) and query it. Actually exposing `semanticdbVersion` could be also good to check that the running version of Metals is compatible with the sbt-metals user has and warn if they use too old version.

Another thing I wanted to introduce in #278, but didn't do because of this sbt-metals detection issue is running `semanticdbEnable` every time we connect to sbt.

**Comment by gabro** [comment]
I like anything that goes in the direction of a better UX, so 👍 to the general spirit of this issue.

What do you suggest is a proper entry point for running these checks?

I was also thinking of a `metalsDoctor` command that prints a report in the form of:

```
sbt
> metalsDoctor
[info] ✅ buildinfo is present for all projects/tasks
[info] ✅ semanticdb-scalac is enabled
[info] 🤔 no `.semanticdb` files found. Suggestion: run `sbt compile`
[info] ℹ️ can't retrieve diagnostics from this sbt version (0.13.17). Suggestion: upgrade to sbt 1.1+ to get enable diagnostics.
```

And so on.

**Comment by laughedelic** [comment]
> What do you suggest is a proper entry point for running these checks?

I think it should happen in the server during workspace initialization (when server server reads buildinfo files, semanticdbs and sbt's active.json). It could also happen on every connection to the sbt server, probably in some reduced form, see my comment above about running `semanticdbEnable` this way.

The weak point in general is users with sbt 0.13 that didn't run `sbt metalsSetup`: we cannot do it for them through sbt server. We can only communicate them that they forgot to do something from the server: for instance check the presence of `.metals/buildinfo` on workspace initialization and send a `window/showMessage` telling them to add sbt-metals if they didn't yet and run `sbt metalsSetup`.

> I was also thinking of a metalsDoctor command that prints a report

I like positive checks output and helpful suggestions 👍 I only think that it should be an improvement to the existing `metalsSetup` command. This way we have one answer to all questions related to the sbt setup: doesn't matter if you're doing it first time or rerunning because something doesn't work, just run `metalsSetup` and if something goes wrong you will see a helpful warning and a suggestion on how to fix it.

**Comment by olafurpg** [comment]
I think this is a great idea! Let's close this ticket however to keep the issue tracker focused on the current priorities of the project. Some things will change in the coming week around installation, for example `sbt metalsSetup` may no longer be necessary. I've added the "revisit" label in case somebody is interesting in looking into this again. I will definitely keep this in mind while working on the new BSP-based "import project" workflow.
