### ISSUE TITLE
Support project view in TVP panel for Scala 3

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2859]
I am not sure this is a bug or the feature isn't support for scala 3 yet.
I created a new sbt project using scala3.g8 template. Then I created some classes and objects in the Main.scala file.
The project explorer only detected the package, nothing else were shown unlike the Libraries section,

![image](https://user-images.githubusercontent.com/42483897/120860899-9df61c00-c5b0-11eb-9c10-604d8273f6e8.png)

_Originally posted by @Fubuchi in https://github.com/scalameta/metals/discussions/2855_

**Comment by ckipp01** [comment]
To add a little more context, I'd expect this to work in Scala 3 like it does in Scala 2. However, even after some more classes I've been unable to get TVP to show local stuff in the tree view.

Steps to recreate:

1. create a new scala3 project using the metals new project functionality.
2. Go to `Main.scala` and then open the TVP panel. 
3. See that nothing is there under `example`.
4. To test further, add another `object Foo` with a couple members
5. Also see they don't appear in the TVP panel.

**Comment by dos65** [comment]
The reason is that TVP uses `ScalaSig` that works only for scala2. For Scala3 we need to start reading tasty.

**Comment by ches** [comment]
> The reason is that TVP uses `ScalaSig` that works only for scala2. For Scala3 we need to start reading tasty.

So this applies for the Libraries section where dependencies are built with Scala 3, I assume. If I'm on the right track then [`ClasspathSymbols.scala`][1] is the place to start.

For Scala 3 files local to a project, I imagine [`Signature` and `SymbolInformation` support][2] will open the way for this?

Could this extraction from JARs, abstracting over ScalaSig or TASTy, be in a SemanticDB utility along the lines of scalameta/scalameta#1566?


[1]: https://github.com/scalameta/metals/blob/03704c17b5397bd8feb4771d0bedf9a6dfe0a660/metals/src/main/scala/scala/meta/internal/tvp/ClasspathSymbols.scala
[2]: https://github.com/lampepfl/dotty/issues/12766

**Comment by dos65** [comment]
@ches The only that is currently required is to add support of reading Tasty files at the place where TVP uses ScalaSig.

Everything related to Semanticdb already works well and shouldn't be connected with this thing.
