### ISSUE TITLE
Does not connect after GenerateBspConfig

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#2866]
**Describe the bug**

Metals does not connect to sbt server after running `GenerateBspConfig` in a freshly cloned project

**To Reproduce**

1. Clone new project (or run `git clean -dfx`)
2. Open VS code and wait for Metals to start 
3. Don't clik `Import build` in the "New sbt workspace" notification
4. Run `GenerateBspConfig`
5. Metals does not connect to sbt server
6. It does not connect either after running `BspSwitch` or `ConnectBuildServer`

**Expected behavior**

Metals should connect and import the build after running `GenerateBspConfig` or `BspSwitch`

**Screenshots**

Logs are
```text
...
2021.06.09 16:17:01 WARN  Build server is not auto-connectable.
2021.06.09 16:17:27 INFO  sbt 1.5.2 found for workspace.
2021.06.09 16:17:30 INFO  [info] welcome to sbt 1.5.2 (AdoptOpenJDK Java 1.8.0_275)
...
2021.06.09 16:17:41 INFO  [success] Total time: 0 s, completed Jun 9, 2021 4:17:42 PM
2021.06.09 16:17:41 INFO  sbt bspConfig exit: 0
2021.06.09 16:17:42 INFO  time: ran 'sbt bspConfig' in 15s
2021.06.09 16:17:42 WARN  Build server is not auto-connectable.
```

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.10.4

**Additional context**

https://github.com/scalameta/metals/blob/ab10007589114d6cf29764f3c8d8dd7486160446/metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala#L38-L40

The root cause is probably that `explicitChoiceMade` is false. Maybe it should be mutated to true when running `GenerateBspConfig` or `BspSwitch`.

**Search terms**

sbt server bsp switch

**Comment by ckipp01** [comment]
Thanks for the report @adpi2 I was able to just verify that. It's odd since if you do a `bloopInstall` with bloop first, and then do the `BspSwitch`, then it works fine. So I think you're right and in the scenario where you start without ever doing a `bloopInstall` something funky is going on.
