### ISSUE TITLE
Problem with trait context bound

### ISSUE THREAD

**Issue by ireina7** [scalameta/metals#2874]
**Metal keeps reporting error when using trait context bounds**
Whenever I use context bounds on trait type parameters, metal reports: `] expected but : found` but my compiler complained nothing.

**To Reproduce**

Here's my code:
```scala
enum Ordering:
  case Less, Equal, Great

trait Eq[A]:
  def equal(x: A, y: A): Boolean
  extension (a: A) 
    def ===(b: A) = equal(a, b)
    def =/=(b: A) = !equal(a, b)

trait Ord[A: Eq]:
  def compare(x: A, y: A): Ordering
  extension (a: A)
    def <(b: A) = compare(a, b) == Ordering.Less
    def >(b: A) = compare(a, b) == Ordering.Great
```
When hovering my mouse over `[A: Eq]`, Metal complains error: `] expected but : found`.

**Expected behavior**

No error

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.10.6

**Additional context**

none

**Search terms**

scala3, context bound

**Comment by dos65** [comment]
Thanks for reporting!
That's indeed an issue with scalameta parser.
