### ISSUE TITLE
`Insert Type Annotation` not available in `Scala 3` sources despite correct inference

### ISSUE THREAD

**Issue by otto-dev** [scalameta/metals#2875]
**Describe the bug**

`Insert Type Annotation` not available in `Code Actions` when the project uses `Scala 3`.

The type is correctly inferred on hover, but inserting this type is not supported.

![DeepinScreenshot_select-area_20210613140013](https://user-images.githubusercontent.com/44302748/121794932-e9af6200-cc4f-11eb-909d-039790f01eaf.png)
(`no code action available`)

Type inferrence:
![DeepinScreenshot_select-area_20210613140029](https://user-images.githubusercontent.com/44302748/121794938-f3d16080-cc4f-11eb-89f7-7d45bb840780.png)

**To Reproduce**

`build.sbt`
```
scalaVersion := "3.0.0"
version := "0.1.0"
```
`src/main/scala/example/Example.scala`
```scala
package example

object Example {
  val test = "foobar"
}
```

**Expected behavior**

(Scala 2)

![DeepinScreenshot_select-area_20210613135934](https://user-images.githubusercontent.com/44302748/121794918-c4225880-cc4f-11eb-83d0-ba6d9b463838.png)
**Screenshots**

**Installation:**

- Operating system: Linux
- Editor: Neovim and Vim with `coc-metals` `v1.0.6`
- Metals version: `v0.10.4`

**Comment by otto-dev** [comment]
Turns out there is a 1-2 second window a few seconds after `vim` startup where I can trigger the `Insert type annotation` code action, which executes correctly. :thinking:

**Comment by ckipp01** [comment]
Hi @otto-dev! Thanks for the report. Support for this in Scala 3 was actually just merged in a few days ago https://github.com/scalameta/metals/pull/2825. You can use it right away if you use the latest [snapshot](https://scalameta.org/metals/docs/editors/vim.html#using-latest-metals-snapshot) or wait for the next release.

**Comment by otto-dev** [comment]
Thanks, can confirm that inferred type insertion works in the snapshot.

Keep up the good work. :+1:

**Comment by armeltd** [comment]
Hello !

I can't figure out how have this "Insert infered type" action (I am on scala 2).

![image](https://user-images.githubusercontent.com/29709300/125683925-aa978488-44c8-4499-8974-53fbc6f7c8de.png)

Seeing the screenshot in the comment above that should be possible. There is something I must be missing.  Should it be supported out of the box ?

OS: Linux
vim version: NVIM v0.5.0
node version: v12.22.0
coc.nvim version: 0.0.80-aa24232066
coc-metals: 1.0.7
scala: 2.13.5

**Comment by otto-dev** [comment]
You are using the wrong `<Plug>`  @armeltd. Use this:

```
xmap <Space>a  <Plug>(coc-codeaction-selected)
nmap <Space>a  <Plug>(coc-codeaction-cursor)
```

Note this is a coc issue, so it doesn't really belong here.
