### ISSUE TITLE
No match completion offered in Scala 3

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2878]
**Describe the bug**

Given the following code

```scala
def greeting(a: Option[Int]) = a  matc@@
```

I'd expect to get a completion option for `match`.

**Expected behavior**

The same behavior as in Scala 2, get the completion item for `match`.

**Screenshots**

**Installation:**

- Operating system: macOS
- Editor: All
- Metals version:  0.10.4+59-e4b554b4-SNAPSHOT

**Additional context**

This might be what is affect match types here as well https://github.com/scalameta/metals/issues/2810

**Search terms**

Scala 3 match completions

**Comment by tgodzik** [comment]
So this is currently in the feature requests repo with the rest of unimplemented Scala 3 features. https://github.com/scalameta/metals-feature-requests/issues/175

We might need to create an entry in the docs documenting what is currently available and point to scala 3 feature requests?

**Comment by ckipp01** [comment]
Ahh sorry, I totally forgot to check there. My bad.

> We might need to create an entry in the docs documenting what is currently available and point to scala 3 feature requests?

Yea I think that's a good idea. I've been meaning to do some other doc updates so I can probably tackle this this week.

**Comment by tgodzik** [comment]
Thanks!
