### ISSUE TITLE
Scala Play Controller Classes Are Not Picked Up After Indexing

### ISSUE THREAD

**Issue by mikail-khan** [scalameta/metals#2896]
**Describe the bug**
After importing and indexing this project: https://github.com/hmrc/cds-reimbursement-claim-frontend , searching for any controller class by using the Ctrl-T feature in the Visual Code fails.

**To Reproduce**

1. Clone this repo: https://github.com/hmrc/cds-reimbursement-claim-frontend
2. Import the project
3. Wait for indexing to complete
4. Type in Ctrl-T and search for any controller class 

**Expected behavior**
1. Should find any controller class that is searched for

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code
- Metals version: v0.10.4

**Comment by dos65** [comment]
Thanks for reporting!
Could you add more details? Is there any error in logs?


I've just tried to open this project and everything works fine.

**Comment by mikail-khan** [comment]
urgh! - I re-cloned the project and rebuilt it and now I don't get the problem.
