### ISSUE TITLE
Support rename for global symbols

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#290]
Following up from offline discussions at ScalaSphere.

Currently, metals supports rename for local symbols only. This means it's possible to rename a variable inside a block, but not possible to rename a top-level class/object/def. 

The way I imagine rename will work is that we'll use the symbol index to find all references to the symbol being renamed. We already have a symbol index, however several challenges need to be addressed first before we blindly start using it

* Validate that SemanticDB files are up-to-date to prevent half-complete renames
  * use token edit distance for slightly stale SemanticDBs 
  * abort rename if compilation is required
* Rename companion object/class together
* Rename synthetic apply/copy parameters for case classes when renaming case class fields
* Rename filename when renaming the only top-level symbol in a file
  * LSP does not support this by default, investigate what extension to use to make it work in vscode/atom.

@ShaneDelmore would you be interested to take on this ticket?

**Comment by ShaneDelmore** [comment]
I believe I would be in a good position to take on this ticket, but give me a few days to get back to the US and confirm with the rest of my team that I am able to take this on.

**Comment by olafurpg** [comment]
The current VS Code milestone has a proposal to allow `WorkspaceEdit` to create/rename/delete files https://code.visualstudio.com/updates/v1_25#_workspaceedit-can-createrenamedelete-files

> WorkspaceEdit can create/rename/delete Files
> We have added a proposed API that extends WorkspaceEdit so that it can be used to create, rename, and delete files or folders. This is useful for complex refactorings, for example renaming a file when a type is being renamed, but should also enable other scenarios.

I suspect this will eventually make it into LSP once validated.

**Comment by ShaneDelmore** [comment]
I completely forgot about this, so sorry!  I’m not working on LSP this quarter and won’t be tackling this after all so it’s good to hear there is progress.

**Comment by olafurpg** [comment]
Metals doesn't support rename anymore. Rename may get added back in the future but for now I think it's best to close this ticket to keep the issue tracker focused. We can revisit this once we have solid "find all references" working.
