### ISSUE TITLE
Metals starts up in every project on macOS

### ISSUE THREAD

**Issue by philsherry** [scalameta/metals#2902]
## Describe the bug

Metals starts up in *every* project on macOS, no matter what kind of file is in the project. 

Not all of my projects are Scala-related, but Metals is showing up anyway.

I’d settle for a `.metalsignore` file as long as it was respected.

## To Reproduce

1. I open any project.
2. I wait for the Output window to stop scrolling as Metals downloads things and does stuff.
3. I see a `.metals` directory appear in the root of the project. 

## Expected behavior

I expect Metals to only kick in when it’s a Scala project, as detailed here:

> “The extension activates when the main directory contains `build.sbt` or `build.sc` file, a Scala file is opened, which includes `*.sbt`, `*.scala` and `*.sc` file, or a standard Scala directory structure `src/main/scala` is detected.”

## Screenshots

<img width="358" alt="VS Code’s file explorer, showing zero scala files in the projcet, but metals has crowbarred its way in there." src="https://user-images.githubusercontent.com/272769/123605539-db3a7c00-d7f3-11eb-823d-c01d6ac5c11f.png">

## Installation

- Operating system: `macOS 11.4 (20F71)`
- Editor: `Visual Studio Code v1.57.1`
- Metals version: `v0.10.4`

## Additional context

This log output is from the project in the screenshot:

```log
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/
Metals version: 0.10.4
2021.06.28 09:18:57 INFO  logging to file /Users/philsherry/Projects/HMRC/hmrc--accessibility/accessibility-audits-ddcnls/.metals/metals.log
2021.06.28 09:18:57 INFO  Started: Metals version 0.10.4 in workspace '/Users/philsherry/Projects/HMRC/hmrc--accessibility/accessibility-audits-ddcnls' for client Visual Studio Code 1.57.1.
2021.06.28 09:18:57 INFO  Flyway Community Edition 7.9.0 by Redgate
2021.06.28 09:18:58 INFO  Database: jdbc:h2:file:/Users/philsherry/Projects/HMRC/hmrc--accessibility/accessibility-audits-ddcnls/.metals/metals (H2 1.4)
2021.06.28 09:18:58 INFO  Successfully validated 3 migrations (execution time 00:00.051s)
2021.06.28 09:18:58 INFO  Creating Schema History table "PUBLIC"."flyway_schema_history" ...
2021.06.28 09:18:58 INFO  Current version of schema "PUBLIC": << Empty Schema >>
2021.06.28 09:18:58 INFO  Migrating schema "PUBLIC" to version "1 - Create tables"
2021.06.28 09:18:58 INFO  Migrating schema "PUBLIC" to version "2 - Server discovery"
2021.06.28 09:18:58 INFO  Migrating schema "PUBLIC" to version "3 - Jar symbols"
2021.06.28 09:18:58 INFO  Successfully applied 3 migrations to schema "PUBLIC", now at version v3 (execution time 00:00.255s)
2021.06.28 09:19:00 INFO  time: initialize in 2.9s
Initializing Scala Debugger
2021.06.28 09:19:00 INFO  Flyway Community Edition 7.9.0 by Redgate
2021.06.28 09:19:00 INFO  Database: jdbc:h2:file:/Users/philsherry/Projects/HMRC/hmrc--accessibility/accessibility-audits-ddcnls/.metals/metals (H2 1.4)
2021.06.28 09:19:00 INFO  Successfully validated 3 migrations (execution time 00:00.004s)
2021.06.28 09:19:00 INFO  Current version of schema "PUBLIC": 3
2021.06.28 09:19:00 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2021.06.28 09:19:00 WARN  Build server is not auto-connectable.
2021.06.28 09:19:00 WARN  no build tool detected in workspace '/Users/philsherry/Projects/HMRC/hmrc--accessibility/accessibility-audits-ddcnls'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
```
## Search terms

Metals starts up in every project on macOS.

**Comment by tgodzik** [comment]
Thanks for reporting, Metals is activated by the following:
```
  "activationEvents": [
    "onCommand:metals.new-scala-project",
    "onDebugResolve:scala",
    "onLanguage:scala",
    "workspaceContains:build.sbt",
    "workspaceContains:build.sc",
    "workspaceContains:project/build.properties",
    "workspaceContains:src/main/scala",
    "workspaceContains:*/src/main/scala",
    "workspaceContains:*/*/src/main/scala"
  ],
```
so most likely the issue lies within VS Code itself. You should be able to see what activates the extension in "Output -> Log (Extension host)". However, VS Code is known to activate an extension if any of the condition times out.

I am afraid there might be nothing to do on our side.

**Comment by philsherry** [comment]
Could a `.metalsignore` file work? I realise this is most likely quite an undertaking, so I'm prepared for a polite refusal here.

**Comment by tgodzik** [comment]
> Could a `.metalsignore` file work? I realise this is most likely quite an undertaking, so I'm prepared for a polite refusal here.

You can already disable Metals within certain workspaces, that's inside the extension tab. `Disable (workspace)` should be somewhere around the Metals extension tab.

**Comment by tgodzik** [comment]
However, Metals should not be activated in unrelated workspaces, so if you are able to check the extension host, that might be helpful to figure out what's going on.

**Comment by tgodzik** [comment]
Something like this should pop up:
```
[2021-06-25 15:00:54.708] [exthost] [info] ExtensionService#_doActivateExtension scalameta.metals {"startup":true,"extensionId":{"value":"scalameta.metals","_lower":"scalameta.metals"},"activationEvent":"workspaceContains:build.sbt"}
```

**Comment by philsherry** [comment]
Yep, I have this in there: 

`[2021-06-28 09:18:35.022] [exthost] [info] ExtensionService#_doActivateExtension scalameta.metals {"startup":true,"extensionId":{"value":"scalameta.metals","_lower":"scalameta.metals"},"activationEvent":"workspaceContainsTimeout:*/src/main/scala,*/*/src/main/scala"}`

**Comment by tgodzik** [comment]
So that one seems to be an issue with VS Code. It shouldn't really timeout on checking this depth of directories in a small workspace. Probably something weird is going on but nothing we can fix on the Metals side without changing the current behaviour.

Best to work around it by disabling metals in certain workspaces or enabling it only in some.
