### ISSUE TITLE
Organize import raises server error with - zip END header not found

### ISSUE THREAD

**Issue by EveryonePrint-dev** [scalameta/metals#2903]
**Describe the bug**

When issuing 'organize imports' in LSP client The following error is raised on server side.

(:jsonrpc "2.0" :id 33 :error
          (:code -32603 :message "Internal error." :data "java.util.concurrent.CompletionException: scala.meta.internal.metals.ScalafixProvider$ScalafixRunException: Unable to load symbol table: zip END header not found\n	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)\n	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)\n	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)\n	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)\n	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)\n	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)\n	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n	at java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: scala.meta.internal.metals.ScalafixProvider$ScalafixRunException: Unable to load symbol table: zip END header not found\n	at scala.meta.internal.metals.ScalafixProvider.$anonfun$organizeImports$2(ScalafixProvider.scala:89)\n	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)\n	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)\n	... 4 more\n"))

**To Reproduce**

- I've deleted '.bloop' folder in project.
- run `gradlew bloopInstall` to create new project definitions
- open LSP client and open a .scala file
- wait until diagnostics of the file are transferred
- make small change and save to trigger compilation
- issue 'organize imports'
- error above is shown

**Expected behavior**

The imports get organized.

**Installation:**

- Operating system: macOS Big Sur
- Editor: Emacs
- Metals version: v0.10.4

**Additional context**

This seems to fail for other files in the same module.
On other modules this operation can succeed.

**Search terms**

organize imports

**Comment by dos65** [comment]
Thanks for reporting!

Could you try to clean up gradle cache (`~/.gradle`)?
This error might happen because of having some corrupted jars files in the classpath.

**Comment by dos65** [comment]
I faced the same thing in [bloop](https://github.com/scalacenter/bloop) repo.
At least in `frontend` module, any invocation of organize import fails with the same error as in original report

**Comment by tgodzik** [comment]
Maybe it's something on the classpath? We can print the classpath given to scalafix and see if anything doesn't look right.

**Comment by tgodzik** [comment]
@mlachkar did you see this issues with scalafix before?

**Comment by mlachkar** [comment]
I will try later this afternoon on bloop to reproduce the error.

**Comment by tgodzik** [comment]
Thanks!

**Comment by tgodzik** [comment]
It seems to always happen with Bloop, this might be some classpath issue maybe? We can try to fix it on the Metals side, but I think this might also happen via sbt.

**Comment by EveryonePrint-dev** [comment]
I've tried to wipe .bloop, .gradle and .metals, to have everything be compiled from scratch.
But the error persists.
So this is a bloop issue?

**Comment by mlachkar** [comment]
Hello, finally we had the time to check: 
Scalafix receives a classpath containing `.md` files, then it fails to parse them as jars.
One solution would be to send the classpath without the resource files or just filter anything that is not a jar.
