### ISSUE TITLE
Implicit parameter hints don't appear in top-level generator positions

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#2904]
**Describe the bug**

Implicit hints don't appear for implicit parameters in a certain position of a for comprehension.

**To Reproduce**

1. Create a file

```scala
object Scratch {
  def foo(implicit s: Numeric[Int]) = List(1, 2, 3, s.zero)
  for { _ <- foo } yield ()

  def x = foo
}
```

2. Compile
3. Enable implicit parameter hints
4. Only `def x = foo` has an implicit parameter hint

**Expected behavior**

`foo` call in the forcomp shows the Numeric instance used

**Screenshots**

<img width="597" alt="image" src="https://user-images.githubusercontent.com/894884/123846241-665f6300-d915-11eb-95de-a963b881670a.png">

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.4

**Additional context**

Hints appear if they're not in the top-level position, e.g. if it was `_ <- List(foo)`, we'd be seeing the hint.

**Search terms**

enumeration, generator, for comprehension, implicits

**Comment by tgodzik** [comment]
Thanks for reporting! This seems to be an issue within semanticdb, we are not producing the correct synthetic information when in a for comprehension.

**Comment by kpodsiad** [comment]
Closed by https://github.com/scalameta/metals/pull/3974?

<img width="594" alt="Screenshot 2022-07-30 at 07 48 15" src="https://user-images.githubusercontent.com/37124721/181876766-d930fea6-9145-4be6-804c-01b61a08d873.png">

@kubukoz reopen issue if I'm wrong
