### ISSUE TITLE
Type hints don't appear on synthetic .apply

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#2905]
**Describe the bug**

Inferred type hints don't show up for calls to `apply` methods that are automatically expanded from `(...)` calls.

**To Reproduce**

1. Create a file:

```scala
case class T[A, B](a: A, b: B)

object Umm {
  val x = T(42, "a")
  val y = T.apply(42, "a")

}
```

2. Compile
3. Turn on type hints
4. Wait for hints to show up
5. There's only a hint on `apply` if it's called explicitly

**Expected behavior**

There would be a type hint on `T(...)` as well.

**Screenshots**

<img width="512" alt="image" src="https://user-images.githubusercontent.com/894884/123847566-049ff880-d917-11eb-9a4f-2e9dcc74ee93.png">

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.4

**Additional context**

none

**Search terms**

all the words already appeared in this description 😅

**Comment by tgodzik** [comment]
Thanks for reporting! Fixing it in https://github.com/scalameta/metals/pull/2906

I disabled it for tuples though, since it seems there is no sensible place to include types there and that unfortunately influences doing `Tuple2(1, 2)`, but hopefully not that many people use it.

**Comment by kubukoz** [comment]
Interesting, can we use the AST of the expression instead of just the type to determine whether it should show things (Tuple2) or not (`(,)`)?

**Comment by tgodzik** [comment]
That would require checking the tree for each synthetic occurrence, which is something I would like to avoid. The other Option is checking the source file itself... maybe that would work.

**Comment by tgodzik** [comment]
I changed it to check if the actual Tuple name exists at synthetic location.
