### ISSUE TITLE
Goto definition broken for shapeless3 kind objects

### ISSUE THREAD

**Issue by esuntag** [scalameta/metals#2909]
**Describe the bug**

Goto definition seems to be broken for the kind objects in  shapeless3.derivining (shapeless3.deriving.{K0, K1, K11, K2}

**To Reproduce**

In the following code snippet, vscode displays the correct type information for `K0` but will not let me go to defintion. It works fine for other shapeless 3 classes like `Complete`. I am using the latest version of shapeless3 (3.0.1)
```
import shapeless3.deriving._

trait Eq[A]:
  def eqv(l: A, r: A): Boolean

object Eq:
  given eqGen[A](using inst: K0.ProductInstances[Eq, A]): Eq[A] with
    def eqv(l: A, r: A): Boolean = inst.foldLeft2[Boolean](l,r)(true)(
      [t] => (acc: Boolean, eq: Eq[t], t0: t, t1: t) => Complete(!eq.eqv(t0, t1))(false)(true)
    )
```

**Expected behavior**

Control+click should pull up the source file for `K0`

**Screenshots**

The type is inferred correctly:
![image](https://user-images.githubusercontent.com/3589174/124019895-9e1ee700-d9b7-11eb-9734-16e6115f301e.png)
However it doesn't seem to be finding the source.

**Installation:**

- Operating system: Windows with WSL 2.0 (Ubuntu kernel)
- Editor: Visual Studio Code
- Metals version: v1.10.6

**Additional context**

N/A

**Search terms**

Shapeless, goto definiton

**Comment by tgodzik** [comment]
Thanks for reporting! @dos65 does you PR help with the issue here?

**Comment by tgodzik** [comment]
Ok, it seems it should actually be fixed as of yesterday. Could you check with Metals version `0.10.4+112-9098c2a1-SNAPSHOT` ?

**Comment by esuntag** [comment]
Thanks, it seems to be working now with that version.

**Comment by tgodzik** [comment]
Cool! We will probably do a release together with 3.0.1
