### ISSUE TITLE
[Scala3] No completions after newline + dot in VScode

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#2919]
~~It seems that there is an issues in `CompletionPos` calculation~~

```scala
val a = List(1, 2)
  .m@@  // <- no completion
```

According to traces, metals actually returns completions but they are filtered out by VScode by some reason.
It's needed to check what wrongs with their data.

**Comment by ckipp01** [comment]
Just to make sure I did test this in nvim-metals and it indeed shows.

<img width="991" alt="Screenshot 2021-07-01 at 20 58 51" src="https://user-images.githubusercontent.com/13974112/124176458-32b84080-daaf-11eb-82fb-298dd0eb52bd.png">

**Comment by tgodzik** [comment]
Looks like maybe text edit is wrong:
```
      textEdit = Either [
        left = TextEdit [
        range = Range [
          start = Position [
            line = 3
            character = 0
          ]
          end = Position [
            line = 3
            character = 6
          ]
        ]
        newText = "map"
      ]
        right = null
      ]
```

it shouldn't start at 0, but at 5 like in Scala 2

**Comment by tgodzik** [comment]
```scala
  checkEdit(
    "using".only,
    s"""|object O{
        |  val a = List(1, 2)
        |    .m@@
        |}
        |""".stripMargin,
    """|map[B, That](f: Int => B)(implicit bf: CanBuildFrom[List[Int],B,That]): That
       |mapConserve[B >: Int <: AnyRef](f: Int => B): List[B]
       |companion: GenericCompanion[List]
       |""".stripMargin,
    filter = str => {pprint.log(str);str.contains("map[")}
  )
```
looks completely broken because of the above.
