### ISSUE TITLE
VScode - Organize Import as CodeAction doesn't work

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#2923]
Triggering code action on the line with `Unused Import` warning returns `No code action available.`
However, there are trace with `textDocument/codeAction` repsonse:

<details>
  <summary>Trace</summary>
  <pre>
  [Trace - 11:31:17 PM] Received request 'textDocument/codeAction - (24)'
Params: {
  "textDocument": {
    "uri": "file:///home/dos65/projects/metals/metals/tests/unit/src/test/scala/tests/BspSwitchLspSuite.scala"
  },
  "range": {
    "start": {
      "line": 6,
      "character": 18
    },
    "end": {
      "line": 6,
      "character": 18
    }
  },
  "context": {
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 6,
            "character": 0
          },
          "end": {
            "line": 6,
            "character": 34
          }
        },
        "severity": 2,
        "source": "bloop",
        "message": "Unused import"
      }
    ]
  }
}

[Trace - 11:31:17 PM] Sending response 'textDocument/codeAction - (24)'. Processing request took 75ms
Result: [
  {
    "title": "Organize imports",
    "kind": "source.organizeImports",
    "edit": {
      "changes": {
        "file:///home/dos65/projects/metals/metals/tests/unit/src/test/scala/tests/BspSwitchLspSuite.scala": [
          {
            "range": {
              "start": {
                "line": 0,
                "character": 0
              },
              "end": {
                "line": 56,
                "character": 0
              }
            },
            "newText": "package tests\n\nimport scala.meta.internal.metals.Messages._\nimport scala.meta.internal.metals.MetalsEnrichments._\nimport scala.meta.internal.metals.ServerCommands\n\nimport bill.Bill\n\nclass BspSwitchLspSuite extends BaseLspSuite(\"bsp-switch\") {\n\n  test(\"switch\".flaky) {\n    cleanWorkspace()\n    Bill.installWorkspace(workspace.toNIO)\n    for {\n      _ \u003c- server.initialize(\"\")\n      _ \u003d {\n        client.messageRequests.clear()\n        assertConnectedToBuildServer(\"Bill\")\n      }\n      _ \u003c- server.executeCommand(ServerCommands.BspSwitch.id)\n      _ \u003d {\n        assertConnectedToBuildServer(\"Bill\")\n        assertNoDiff(\n          client.workspaceShowMessages,\n          BspSwitch.onlyOneServer(\"Bill\").getMessage()\n        )\n      }\n      _ \u003d {\n        client.messageRequests.clear()\n        assertConnectedToBuildServer(\"Bill\")\n        Bill.installWorkspace(workspace.toNIO, \"Bob\")\n      }\n      _ \u003c- server.executeCommand(ServerCommands.ConnectBuildServer.id)\n      _ \u003d {\n        assertConnectedToBuildServer(\"Bob\")\n        assertNoDiff(\n          client.workspaceMessageRequests,\n          SelectBspServer.message\n        )\n        assertNoDiff(client.workspaceShowMessages, \"\")\n\n        client.messageRequests.clear()\n        client.showMessageRequestHandler \u003d { params \u003d\u003e\n          params.getActions.asScala.find(_.getTitle \u003d\u003d \"Bill\")\n        }\n      }\n      _ \u003c- server.executeCommand(ServerCommands.BspSwitch.id)\n      _ \u003d {\n        assertNoDiff(client.workspaceShowMessages, \"\")\n        assertConnectedToBuildServer(\"Bill\")\n      }\n    } yield ()\n  }\n}\n"
          }
        ]
      }
    }
  }
]
</pre>
</details>

- Editor: Visual Studio Code (1.56.2 / 1.57.1)
- Metals version: v0.10.4

**Comment by tgodzik** [comment]
I suspect that this is due to the OrganizeImports kind being set, I wonder if we change it to quickfix for unused imports it would work :thinking:
