### ISSUE TITLE
Worksheet taking forever to evaluate in nightly builds (OSX, VSCode)

### ISSUE THREAD

**Issue by Swoorup** [scalameta/metals#2928]
**Describe the bug**

Worksheet appears to be taking forever to evaluate in OSX. 

**To Reproduce**

1. Use any worksheet.
2. Close and reopen the worksheet in VSCode.
3. Observe the forever evaluation.
![image](https://user-images.githubusercontent.com/3408009/124360338-99cf2400-dc6c-11eb-8395-e479323f2cb4.png)

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: 0.10.4+118-c2380821-SNAPSHOT

**Additional context**

I tried restarting my PC, killing java process and retesting to no avail. This doesn't happen on 0.10.4 release though.

**Search terms**

Hangs, Metals, OSX

**Comment by Swoorup** [comment]
Sample worksheet used: 

```scala
import cats.effect.unsafe.IORuntime

import cats.*
import cats.implicits.*
import cats.effect.std.*
import cats.effect.syntax.spawn.*
import cats.effect.*
import fs2.Stream
import scala.concurrent.duration.*


def measure[F[_]: Clock: Monad, A](effect: => F[A]) = 
  for {
    start   <- Clock[F].monotonic
    r       <- effect
    end     <- Clock[F].monotonic
  } yield (r, end - start)

// def createRateLimiter[F[_]](period: Duration, maxCallsPerPeriod: Int, effect: => F[T]) = 

given IORuntime = IORuntime.global
val app = IO.println("dhsds")

measure(app)
  .map(_ => ())
  .unsafeRunSync()
```

**Comment by tgodzik** [comment]
@Swoorup this might be caused by my recent changes. Thanks for raising this! We'll make sure to revert/change it before the next release.
