### ISSUE TITLE
Website gitpod examples don't work

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2932]
**Describe the bug**

When trying to use the "TRY ONLINE WITH GITPOD" functionality on the homepage of the website, it opens up the projects, but there are some errors and Metals isn't installed. When the project opens up you see the following errors in the workspace:

<img width="668" alt="Screenshot 2021-07-05 at 16 48 12" src="https://user-images.githubusercontent.com/13974112/124489010-cee48f00-ddb0-11eb-89d7-ec0bfd0e992e.png">

**Comment by tgodzik** [comment]
Thanks for checking! I guess the reason is that they want to use the openvsx extensions, but not sure if they can be preinstalled for a user.

**Comment by tgodzik** [comment]
Ok, it should be fixed now! We can now always rely on the latest extension, which is awesome. Also fixed in the gitpod sample repo.

**Comment by ckipp01** [comment]
> Ok, it should be fixed now! We can now always rely on the latest extension, which is awesome. Also fixed in the gitpod sample repo.

You're too speedy @tgodzik ⚡
