### ISSUE TITLE
Metals Doctor + `not yet supported` warning for Scala 3

### ISSUE THREAD

**Issue by agilesteel** [scalameta/metals#2946]
Scala 3.0.1 just came out and metals (vscode) works just fine with it, but the popup asking to downgrade Scala to 3.0.0 still appears and the doctor says that `go to definition` and `completions` won't work, but they do.

Expected behavior: no false negatives.

**Comment by dos65** [comment]
Thanks for reporting!

Actually, it shouldn't work as we haven't released Metals with `3.0.1` support yet.

I guess that completions and definitions might work only if there is some bug related to `PresentationCompiler` caches.
I suppose that it won't work if you restart metals server. Could you confirm that?

**Comment by agilesteel** [comment]
I restarted the server and even reimported the build. It still works like a charm.

**Comment by dos65** [comment]
Oh, yes you right. It works but in this case Metals fallbacks on the latest supported Scala 3 version.

It seems that this `not supported` case for Scala 3 is different from Scala2. We don't need to release and upgrade scalameta for scala 3 so it should work well in most cases.

Probably in this case warning should say:
```
You are using Scala version 3.0.1. Some latest language features might be not supported in this version of Metals.
In case if something doesn't work, please downgrade to Scala version 3.0.0 for the moment until the new Metals release.
```
@tgodzik wdyt?

**Comment by tgodzik** [comment]
Good idea! :+1:

**Comment by tgodzik** [comment]
This should work properly now, since we try to download mtags for the Scala version first and only then show the warning.
