### ISSUE TITLE
Go To Source does not work for Scala3 library classes

### ISSUE THREAD

**Issue by scf37** [scalameta/metals#2949]
**Describe the bug**

Go to source in Scala 3 fails even on simplest cases

**To Reproduce**

Import simple `scalaVersion := 3.0.0` project to vscode, write simple code, Ctrl-click `newBuilder`

**Expected behavior**

going to `newBuilder` definition

**Screenshots**

![image](https://user-images.githubusercontent.com/1148465/125153431-4ec97b00-e15c-11eb-98bb-54ae052c7cf2.png)

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v1.10.6

**Additional context**

Is Scala3 support still in beta? I'm encountering multiple issues with go to source, autocomplete, compilation (`sbt compile works`, compilation from vscode does not)

**Search terms**

scala3, go to source

**Comment by dos65** [comment]
Thanks for reporting!

Go to definition for Scala3 should work well on this version if there is no compile errors in your project.
It seems that something goes wrong with bsp service. Could you restart bloop/sbt process?

**Comment by scf37** [comment]
Closing vscode, killing all tooling processes, deleting all vscode files from the project, and then reimporting hepled.
But!
After verifying goto source works for newBuilder, I added another line of code and goto source broke again...
![image](https://user-images.githubusercontent.com/1148465/125157182-12a11500-e172-11eb-870e-5aa20f4bda32.png)

**Comment by dos65** [comment]
@scf37 Could you check if there are any error messages in logs?

Also, if you are using bloop you could try to [install it's cli](https://scalacenter.github.io/bloop/setup) and run `bloop compile`. Maybe it will show the exact error.

**Comment by scf37** [comment]
hmmmm what is build target and how to set it?
```
.[0m2021.07.10 11:23:56 WARN  no build target for: /home/asm/mywork/scala3-vscode/src/main/scala/Main.scala.[0m
.[0m2021.07.10 11:23:58 INFO  no build target: using presentation compiler with only scala-library: 2.12.14.[0m
.[0m2021.07.10 11:23:59 INFO  running '/home/asm/dev/jdk1.8.0_181/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals8636422745701501176/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'.[0m
Jul 10, 2021 11:24:00 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: file%3A%2F%2F%2Fhome%2Fasm%2Fmywork%2Fscala3-vscode%2Fsrc%2Fmain%2Fscala%2FMain.scala:1: error: ; expected but : found
object Main:
           ^
file%3A%2F%2F%2Fhome%2Fasm%2Fmywork%2Fscala3-vscode%2Fsrc%2Fmain%2Fscala%2FMain.scala:1: error: ; expected but : found
object Main:
           ^
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
```

**Comment by dos65** [comment]
> hmmmm what is build target and how to set it?

It's a project in sbt. According to logs this source file doesn't belong to any project.

The reason might be in build definition misconfiguration.
You could check that by running `sbt run`. If it won't find any main classes then you need check your `build.sbt`

**Comment by scf37** [comment]
```
$ sbt run
[info] welcome to sbt 1.5.2 (Oracle Corporation Java 1.8.0_181)
..........
[info] running main 
Hello, world!
```

```
$ cat build.sbt 
scalaVersion := "3.0.0"
```

```
$ cat src/main/scala/Main.scala
object Main:
    @main
    def main(): Unit = 
        println("Hello, world!")
        val b = Seq.newBuilder[String]
        val r = b.result()
```

There is nothing else

**Comment by dos65** [comment]
@scf37 It looks like project wasn't imported. Could you run `import  build ` and check logs?

Also, you can try the latest SNAPSHOT version - `0.10.4+150-a5639d69-SNAPSHOT`. There were fixes around importing sbt build recently.

**Comment by scf37** [comment]
Found it!
Autocomplete only works after saving. So Ctrl+S first, then Ctrl+click on newly typed code.

**Comment by scf37** [comment]
bloop.settings.json in my project:
```
{
    "semanticDBVersion": "4.4.20",
    "supportedScalaVersions": [
        "2.13.6",
        "2.12.14",
        "2.12.13",
        "2.12.12",
        "2.12.11",
        "2.12.10",
        "2.13.3",
        "2.13.4",
        "2.13.5",
        "2.11.12",
        "2.12.8",
        "2.12.9",
        "2.13.0",
        "2.13.1",
        "2.13.2"
    ]
}
```

I guess there is no scala3 support.

**Comment by tgodzik** [comment]
Scala 3 has built in semanticdb support, so this is no longer needed.

Things should also work even without saving, however if Metals doesn't know it's Scala 3 then there might be some issues. Do you still get the warnings in Metals logs? Can you paste the output of importing the project? That should be in the same logs

**Comment by scf37** [comment]
Here is demo project
[scala3-vscode.tar.gz](https://github.com/scalameta/metals/files/6795629/scala3-vscode.tar.gz)
1. unpack and go to project directory
2. type `code .`
3. click `Import build`
4. metals.log will contain abovementioned exceptions
Ubuntu 20.04.2 LTS / Oracle JDK 1.8.0_181 64 bit / SBT 1.5.2

**Comment by dos65** [comment]
@scf37 I can't reproduce this problem on attached sources. You need to attach your logs. Otherwise we can't investigate what happens.

**Comment by scf37** [comment]
Entire project workspace, with logs and build files.
[scala3-vscode.tar.gz](https://github.com/scalameta/metals/files/6799564/scala3-vscode.tar.gz)

**Comment by tgodzik** [comment]
It looks like there were some parsing issue in the start (it is expected since the default without import is Scala 2), but later on there are no errors at all after import. Maybe you could try with the new release? Might work better for your case. I haven't managed to reproduce it either.

**Comment by tgodzik** [comment]
Could you check out with the newest Metals version and let us know?

**Comment by scf37** [comment]
Works correctly for v1.10.8

**Comment by tgodzik** [comment]
Thanks!
