### ISSUE TITLE
Unexpected error when opening a gatling project

### ISSUE THREAD

**Issue by MisterLight** [scalameta/metals#2954]
Im just following  this guide to develop a gatling project in vscode:

https://www.james-willett.com/gatling-vscode/

I just install metal and create and new project with maven, using the gatling archetype v 3.6.1.

At first looks like it´s working, when I open a .scala file, the plugin detect this and ask me for import the build.

But when is downloading the build, give me the following error and I dont know what could I do:

ERROR Unexpected error when compiling data-test: 'null'

Belllow you can see my folder tree,  Is the one that generate the gatling archetype

<img width="425" alt="imagen" src="https://user-images.githubusercontent.com/46331533/125437214-c2800b25-efbf-4e09-826f-7a6b9901cbe5.png">

Also the metals.log file prompt this: 

<img width="1101" alt="imagen" src="https://user-images.githubusercontent.com/46331533/125437786-e7c59499-8909-454f-8cf6-c858d66de972.png">

**Comment by tgodzik** [comment]
Thanks for reporting! This seems like an error with the export to Bloop build server. Could you push that reproduction to a repository somewhere so that we can take a look? Alternatively, installing Bloop CLI via coursier might help to find the underlying issue. You should be able to do `bloop compile --verbose`, which might shed a light on what's going on exactly.

**Comment by tgodzik** [comment]
Let's reopen this if we get a bit more information.

**Comment by sid-maddy** [comment]
@tgodzik, I have the same issue and ran `bloop compile --verbose`. Here's the output.
[bloop.log](https://github.com/scalameta/metals/files/8466679/bloop.log)

Also, here's the log generated by the metals LSP
[metals.log](https://github.com/scalameta/metals/files/8466685/metals.log)

For reference, I'm using metals with Neovim, configured with [the default configuration for Metals from nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/metals.lua).

**Comment by tgodzik** [comment]
Could you try to see if this also happens with the newest Bloop version `1.4.13-70-d6f16202`?

You can change the `Metals: Bloop version` setting and restart when prompted. CLI should also correctly connect to the new server.

**Comment by sid-maddy** [comment]
Actually, the `bloop compile --verbose` command, whose output I've attached in the previous comment, is `1.4.13` (not sure about the `-70-d6f16202` suffix.)
```sh
❯ bloop help
bloop 1.4.13
Usage: bloop [options] [command] [command-options]


Available commands: about, autocomplete, bsp, clean, compile, configure, console, help, link, projects, run, test
Type `bloop 'command' --help` for help on an individual command

Type `--nailgun-help` for help on the Nailgun CLI tool.
```

Also, the version of `bloop-launcher` that was installed with `metals` is `1.4.13` (assuming this is the server version.)
```sh
❯ cs resolve metals | rg bloop
ch.epfl.scala:bloop-launcher_2.12:1.4.13:default
```

P.S. `Metals: Bloop version` must be a setting provided by the VSCode extension. I tried changing the `version` property in the project configuration file generated in the `.bloop` directory, but it didn't seem to affect the Bloop version used. Let me know if that's incorrect.

**Comment by sid-maddy** [comment]
Tried to configure `metals` to use the development version of `bloop`, but it didn't seem to register it, even after multiple server restarts.

I did try compiling the project using the development version of `bloop` from `coursier`, but that fails to compile the project as well.

[bloop-development-version.log](https://github.com/scalameta/metals/files/8490860/bloop-development-version.log)

**Comment by tgodzik** [comment]
I will take a look at the sample you provided then, thanks!

**Comment by sid-maddy** [comment]
Managed to configure `metals` to use the development version of `bloop`, though it doesn't fix the issue.
BTW, should this issue be moved to the [Bloop](https://github.com/scalacenter/bloop) repo?

**Comment by sid-maddy** [comment]
Had to add that to the `<configuration>` section of the `scala-maven-plugin` to make it work.
Thanks! Didn't know that was needed (new to the Maven/Scala ecosystem.)

Works with both stable and development versions of Bloop.

**Comment by tgodzik** [comment]
Glad to hear it!

**Comment by slandelle** [comment]
> I checked https://github.com/gatling/gatling-maven-plugin-demo-scala, and it seems it's missing the Scala version and some dependencies are using 2.13 artifacts. This might be related to some issues with different defaults, but you should always add the Scala version being used.
> 
> I managed to compile after adding to properties:
> 
> <scala.version>2.13.8</scala.version>

Hi,

One of the scala-maven-plugin maintainer here.

I beg to differ here. This property is not the solution.
Neither maven nor IntelliJ need this property to correctly resolve the correct Scala version based on the dependency tree. Bloop should be able to achieve the same.

This `scala.version` property is only used when the scala-library is not already pulled (which IMHO is a design error but sadly something we have to live with for backward compatibility reasons).

**Comment by tgodzik** [comment]
Ach, right, that seems more like a workaround. Looks like we need an update in the Bloop maven plugin (we depend upstream on the scala maven plugin)

Though it seems I am not able to make it work properly when the only scope set is `test` and it seems due to https://github.com/davidB/scala-maven-plugin/blob/627772b0c968693f6226b72c2e0ea7172ec795a1/src/main/java/scala_maven/ScalaMojoSupport.java#L382

If I change the scope to compile, I can make it work. Any idea what's going on? Is it correct in the maven scala plugin? As far as I know the compile scope will just be empty in this case, but it doesn't seem to be an issue for the vanila scala maven plugin

**Comment by tgodzik** [comment]
Trying to fix it here https://github.com/scalacenter/bloop/compare/main...tgodzik:fix-maven?expand=1

But two things remain:
- the test scope seems not enough
- multi module started failing if we don't set anything in the parent version (is it expected?)  as for example in https://github.com/scalacenter/bloop/blob/main/integrations/maven-bloop/src/test/resources/multi_scala/pom.xml
