### ISSUE TITLE
In one Ammonite script file cannot recognize another sc file's variable and methods when attempt use code completed.

### ISSUE THREAD

**Issue by LoranceChen** [scalameta/metals#2973]
**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

1. create one sc file: `MyScript.sc`:
```
// Ammonite 2.4.0, Scala 2.13.6 

println("Hello World!!")

val myCount= 12345

def myFunc = {
  "hello world!"
}
```
2. create second sc file: `MyScript2.sc`, the problem is there is not proper tips for `myCount` or `myFunc` when input `MyScript.`
```
// Ammonite 2.4.0, Scala 2.13.6 

import $file.MyScript

MyScript.
```

**Expected behavior**
give tips for `myCount` or `myFunc` when input `MyScript.`

**Screenshots**
![image](https://user-images.githubusercontent.com/8775828/125950282-39f7901c-2010-49d7-b692-e76a6dc3331f.png)

**Installation:**
- Operating system: windows10
- VSCode version: 1.58.2
- VSCode extension version: 
- Metals version: (found in VSCode settings, under `metals.serverVersion`) metals: 1.10.7

**Additional context**

**Search terms**
ammonite script metals scala

**Comment by ckipp01** [comment]
Btw this is probably the same issue as in https://github.com/scalameta/metals/issues/2122. It's not limited to getting completions from another script, the issue actually exists in the same file if you try to complete from user defined types.

**Comment by tgodzik** [comment]
> Btw this is probably the same issue as in #2122. It's not limited to getting completions from another script, the issue actually exists in the same file if you try to complete from user defined types.

Thanks Chris, this prompted me to recheck what's going on and I think I got it fixed. And it was all my fault! :sweat_smile:

**Comment by ckipp01** [comment]
> Thanks Chris, this prompted me to recheck what's going on and I think I got it fixed. And it was all my fault! 😅

Ha, just as much our fault as well for not catching it. Glad you figured it out!
