### ISSUE TITLE
"-print-lines" breaks auto-completion

### ISSUE THREAD

**Issue by yuriy-yarosh** [scalameta/metals#2977]
**Describe the bug**

"-print-lines" dotty arg breaks auto-completion.

**To Reproduce**

Use these scalacOptions 

```scala
ThisBuild / scalacOptions ++=
  "-encoding" :: "UTF-8" ::
    "-unchecked" ::
    "-explain" ::
    "-rewrite" ::
    "-new-syntax" ::
    "-pagewidth" :: "180" ::
    "-print-lines" ::
    "-Yexplicit-nulls" ::
    "-Ycheck:all" ::
    "-Xmax-inlined-trees" :: "4000000" ::
    "-Xmax-inlines" :: "128" ::
    Nil
```

Results in

```scala
import cats.effect.`                       |Clock`
```

**Expected behavior**

We shouldn't get proper autocompletion 
```scala
import cats.effect.Clock
```

**Screenshots**

![screenshot](https://i.imgur.com/yk3YUj7.png)

**Installation:**

- Operating system: Arch
- Editor: Visual Studio Code
- VSCode Metals plugin version: v1.10.7
- sbt-bloop 1.4.8-19-4d9f966b

**Comment by tgodzik** [comment]
Thanks for reporting! Not sure why it's happening, but we can for sure just filter those options out. They are not needed by teh presentation compiler.

Fixing it in https://github.com/scalameta/metals/pull/2979

**Comment by yuriy-yarosh** [comment]
NP, Tomasz.
Thanks for the followup and the fix.
