### ISSUE TITLE
MultlineStringFormatter - wrong `stripMargin` position

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#2983]
Given the following snippet:
```scala
val x = List(1, 2, 3)
val y = 
    s"""|abc @@${x.mkString(s"\n")}"""
```

After putting a newline at `@@` it adds `.stripMargin` to nested string interpolation expr:
```scala
  val x = List(1, 2, 3)
  val y = 
    s"""|abc 
        |${x.mkString(s"\n".stripMargin)}"""
```

Expected result:
```scala
  val x = List(1, 2, 3)
  val y = 
    s"""|abc 
        |${x.mkString(s"\n")}""".stripMargin
```

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.5

**Comment by kpodsiad** [comment]
I'll look at it because I already know what the problem is - it's nested interpolations that mess up with token handling.
