### ISSUE TITLE
Mention required VSCode plugins in the installation instructions

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#299]

**Comment by laughedelic** [comment]
I think those plugins are supposed to be installed automatically. Doesn't it work when you run it in debug mode?

**Comment by kubukoz** [comment]
I ran it in debug mode and for some reason I didn't have them (an error was showing up in the debugged instance)

**Comment by laughedelic** [comment]
OK. Could you submit a PR adding missing steps to the docs?

**Comment by kubukoz** [comment]
Sure, I'll just check if it was something env-specific (I may have had the Scala plugin installed and removed before) and follow up with a PR

**Comment by gabro** [comment]
Just a quick update on this: the report is correct. The required dependencies are not installed automatically in dev (the dotty LSP extension faced the same issue)

**Comment by gabro** [comment]
Actually, it's already gone on master.

**Comment by olafurpg** [comment]
`package.json` has a dependency on `scala-lang.scala`, the outline functionality is now built into vscode so the plugin we previously used is no longer needed. Let's close this as fixed.

**Comment by gabro** [comment]
@olafurpg The original issue was about the lack of instructions for manual, which is still the case. One has to install `scala-lang.scala` manually in order for the `metals` extension to work in development. Anywyay, I suspect those instructions will be removed/rewritten soon, so I'm ok with keeping this closed

**Comment by olafurpg** [comment]
Aah, you are right. Reopened, I will open a PR soon updating docs.
