### ISSUE TITLE
VS Extension: Try to resolve serverVersion, alert user if not found

### ISSUE THREAD

**Issue by benhutchison** [scalameta/metals#303]
Plan: Extend this [code](https://github.com/scalameta/metals/blob/652cf98f0dc3c4a1861a5e583c9bf9188c54b6e4/vscode-extension/src/extension.ts#L26-L42), add a `coursier resolve` to check if the server version exists before launching it, and reply to user with informative msg if resolve fails

Arose from [gitter](https://gitter.im/scalameta/metals?at=5af003fa40f24c43045acb87)

**Comment by laughedelic** [comment]
I think `coursier fetch` could be better: you can both show the progress while the server artifacts are being downloaded and show an error message if something goes wrong. See is what the Dotty LSP plugin [does](https://github.com/dotty-staging/dotty/blob/5dc5a7a7f4b1b549ea4fa5e8422d8f601803ca7d/vscode-dotty/src/extension.ts#L49-L52).
