### ISSUE TITLE
worksheets use relevant sbt file

### ISSUE THREAD

**Issue by stumash** [scalameta/metals#3031]
**Describe the feature**

I open a worksheet inside of an existing scala project with an sbt file. I can import code from the project in the worksheet.

**Potential ways to implement?**

I'm not even sure why it doesn't work out of the box, don't know enough here

**Additional context**

n/a

**Search terms**

I think they're already here. Feel free to update this

**Comment by ckipp01** [comment]
I'm going to go ahead and close seeing that his hasn't had any activity since my reply. If you do still have issues with this and the above isn't clear, please do let us know.

**Comment by stumash** [comment]
hey, sorry for the no-reply. very rude of me. you're absolutely right that it already works. good call closing this.

thanks again
