### ISSUE TITLE
Completion with default parameters doesn't work correctly

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals#3048]
**To Reproduce**

```scala
class Main extends App {
  def methodWithDefault(aezakmi: Boolean = true)


  met@@
}
```
In the completion, default value is shown as `{}` instead of `true`

**Expected behavior**
Completion shows valid default parameter value

**Screenshots**
<img width="713" alt="Screenshot 2021-08-17 at 13 01 09" src="https://user-images.githubusercontent.com/37124721/129715121-30877b93-1a51-40d3-80bd-ec5ba0db2997.png">

**Comment by kpodsiad** [comment]
Actually, it's not only boolean parameters but all types are not displayed correctly.

**Comment by tgodzik** [comment]
This is fixed and shows up after completionItemResolve
