### ISSUE TITLE
[Scala3] Using `???` in worksheet may result in spurious postfixOps errors

### ISSUE THREAD

**Issue by griggt** [scalameta/metals#3056]
**Describe the bug**

Using `???` in a Scala 3 worksheet written in significant indentation (optional braces) style, in some instances will spuriously complain about needing a `scala.language.postfixOps` import, and fail to compile.

**To Reproduce**

Create a Scala 3 worksheet with the following code:

```scala
def fixIt =
  val step1 = "minimize the problem"
  ???
  // profit
```

This results in two errors when the worksheet is compiled:

```
postfix operator `???` needs to be enabled
by making the implicit value scala.language.postfixOps visible.

value ??? is not a member of String
```

**Expected behavior**

The worksheet should compile without error.  The same code pasted into a regular `.scala` file works just fine.

**Installation:**
- Scala: 3.0.1
- Editor: Visual Studio Code 1.59.1
- Metals version: 0.10.6-M1+38-9f8ccde2-SNAPSHOT

**Additional context**

The problem goes away if the block is enclosed in braces.

This may actually be an mdoc bug, I'm not exactly sure how worksheets are implemented.

**Comment by griggt** [comment]
This might be fixed by scalameta/mdoc#530 (assuming I've done the following experiment correctly)

With a locally built and published snapshot of Metals, bumping the mdoc dependency to 2.2.22+2-6ac66175-SNAPSHOT made the problem go away.

It's not at all clear to me why that PR would fix it though.  Was the bug actually in the Scala 3 compiler?

**Comment by tgodzik** [comment]
Thanks for reporting! I think it's not yet fixed in mdoc, but this shouldn't be a big issue. I think the code generated with `???` doesn't add newline properly.

**Comment by kasiaMarek** [comment]
Closing this, since this seems to work now, also the code generated by `mdoc` doesn't seem to be missing a `newline`.
