### ISSUE TITLE
`*` is not the first suggestion in import autocompletion

### ISSUE THREAD

**Issue by Kordyjan** [scalameta/metals#3057]
**To Reproduce**

1. type `import scala.collection.*`
2. press `Enter` to start a new line

The line would be completed with `*#:` which is not what's desired in most cases.

**Expected behavior**
`*` should be the first suggestion 

**Screenshots**
<img width="529" alt="obraz" src="https://user-images.githubusercontent.com/11855167/130317871-083ca19f-10cc-4167-87fb-9292b11d7ac9.png">

**Comment by tgodzik** [comment]
Thanks for reporting! This should probably be a part of keywords completions fro Scala 3. But I think due to the usability issues this is currently a bug.

**Comment by objektwerks** [comment]
**1.** Open a Scala 3 source file. **2.** Type import scala.* **3.** Depress the return key --- and a random type will be inserted after the *.  And that's it. I've even seen it happen a _few_ times after typing for and return key for a **for** **comprehension**.
