### ISSUE TITLE
Don't run Ammonite with Scala 3

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3071]
**Describe the bug**

Currently, Scala 3 support for Ammonite doesn't work and we should fallback to Scala 2.13 even when in Scala 3 workspace. Otherwise, we will get exceptions and it will be difficult for users to understand what is going on.

**To Reproduce**

1. Create ammonite script in a Scala 3 workspace 
2. Try to start an ammonite server
3. See errors.

**Expected behavior**

Metals falla back to the last supported versions

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.10.5

**Additional context**

**Search terms**

ammonite build server scala3

**Comment by ckipp01** [comment]
Just to tie these together, I started work on getting support for Scala 3 in ammonite-runner in hopes we can still support it instead of disabling it https://github.com/alexarchambault/ammonite-runner/pull/127/files

**Comment by lucag** [comment]
Why not supporting [scala-cli](https://scala-cli.virtuslab.org) instead? 

* It works wonderfully for all versions of Scala
* Supports dependences in comments (so that a scala-cli scrip is still valid Scala
* Its feature list is long: see the link above!

**Comment by ckipp01** [comment]
Hi @lucag Metals should already support `scala-cli` as you can see in the [docs](https://scala-cli.virtuslab.org/docs/getting_started#ide-support).

**Comment by tgodzik** [comment]
Btw. I have done some work on this in https://github.com/scalameta/metals/compare/main...tgodzik:metals:update-ammonite-runner?expand=1

Though we are getting wrong Scala version for the build target

**Comment by tgodzik** [comment]
The fix should be here https://github.com/com-lihaoyi/Ammonite/pull/1278
