### ISSUE TITLE
Not able to run basic hello-world example

### ISSUE THREAD

**Issue by Alexander770** [scalameta/metals#3076]
Please ask a question using [GitHub Discussions](https://github.com/scalameta/metals/discussions/new)

The main issue tracker is reserved for bug reports and issues with an assigned milestone.

It seems like issue with Java. I tryied to reinstall, change versions nothing help. Please help me to fix it:

Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Debugging is not supported because bloop server is running on a JRE C:\Program Files\Java\jre1.8.0_281 with no support for Java Debug Interface: 'JDI implementation is not provided by the vendor'. To enable debugging, install a JDK and restart the bloop server.

**Comment by ckipp01** [comment]
Hey @Alexander770, I responded in https://github.com/scalameta/metals/issues/3075. Let's try to keep the conversation in one place. I'll close this and you can continue any more questions you have there.

**Comment by Alexander770** [comment]
Thanks

Can you send me a link to proper JDK for windows 10?

**Comment by ckipp01** [comment]
There are many different ways that you can install a JDK.

- Just download from Oracle like so https://docs.oracle.com/en/java/javase/11/install/installation-jdk-microsoft-windows-platforms.html#GUID-DAF345BA-B3E7-4CF2-B87A-B6662D691840
- Or use something like https://sdkman.io/

You'll have to do a quick search for more detailed instructions on "Installing a JDK on Windows".
