### ISSUE TITLE
vscode-extension doesn't compile anymore

### ISSUE THREAD

**Issue by Cardu** [scalameta/metals#308]
to reproduce it just git clone the clean repo, then:

`cd vscode-extension`
`npm install`
`npm run build`

(tested with npm version: 6.1.0)

in the logfile, I see:

```
25 error code ELIFECYCLE
26 error errno 1
27 error metals@0.1.0 build: `vsce package`
27 error Exit status 1
28 error Failed at the metals@0.1.0 build script.
```

**Comment by gabro** [comment]
Thanks for reporting, I can confirm this is an issue after successfully replicating this on my machine. 
I suspect it's an easy fix, I'll get to it soon.
