### ISSUE TITLE
Wrong activeSignature in `signatureHelp` for overloaded method 

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#3081]
It seems that `activeSignature` selection isn't based on already applied argument types.
Example:
```scala
object x {
  def foo(i: Int, s: String): Unit = ???
  def foo(i: Boolean, s: Int, x: Double): Unit = ???

  foo(false, @@) // <- active is : `foo(i: Int, s: String): Unit`
                 //    should be `foo(i: Boolean, s: Int, x: Double): Unit`
}
```

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.5

**Comment by tgodzik** [comment]
Thanks for reporting! I checked it quickly and it seems the symbol being found by the compiler will fit the number of parameters first and only the type second. We should be able to improve it by using something like:

https://github.com/scalameta/metals/compare/main...tgodzik:test-sig?expand=1

But I don't want to spend too much time on it right now, I can take a look at a later point or if anyone wants to pick it up this should be interesting to work on.
