### ISSUE TITLE
Something is off with the 0.10.6 indent on paste

### ISSUE THREAD

**Issue by spangaer** [scalameta/metals#3108]
6 Images say 6000 words right? ;)

![metals_v0 10 6_indent-bug](https://user-images.githubusercontent.com/677147/132642057-d56dfebf-cb0e-4a3c-aa46-0f90928f59bb.gif)

**Comment by tgodzik** [comment]
Thanks for finding this! We will try to fix it as soon as possible. If it's problematic you can disable `Formatting on paste` option in the settings.

**Comment by spangaer** [comment]
Had read that in the release notes indeed, but thanks for reminding.

The only thing I could think though: "So hate optional braces"  🤷‍♂️

**Comment by tgodzik** [comment]
Optional braces are being highly disputed, but this feature should help out also when printing in normal blocks (unless it breaks :fearful: )

**Comment by dos65** [comment]
Hmm. @tgodzik did you reproduce that? I didn't

**Comment by tgodzik** [comment]
Yeah, you need to paste something after a def.

**Comment by spangaer** [comment]
Input source
![image](https://user-images.githubusercontent.com/677147/132648556-a90d34b2-b05a-4a7e-8023-e3c3c4b416da.png)

And Scala 2.12.10, should those make any difference.

**Comment by dos65** [comment]
Still without success even after upgrading vscode to the latest one.
Maybe it somehow depends on platform.
Ok, I'll wait a fix from @tgodzik
