### ISSUE TITLE
Upgrade does not work behind proxy

### ISSUE THREAD

**Issue by liar666** [scalameta/metals#3110]
**Describe the bug**

I'm behind a proxy, I use Emacs + LSP to access `metals` functionalities.

Recently `metals` has tried to upgrade, but fails, with following messages in Emacs:
```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Error while downloading https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar: Connection timed out (Connection timed out), ignoring it
Error while downloading https://repo1.maven.org/maven2/ch/epfl/scala/bsp4j/2.0.0-M13/bsp4j-2.0.0-M13.jar: Connection timed out (Connection timed out), ignoring it
Error while downloading https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-interfaces/0.9.27/scalafix-interfaces-0.9.27.jar: Connection timed out (Connection timed out), ignoring it
Error while downloading https://repo1.maven.org/maven2/com/geirsson/metaconfig-core_2.12/0.9.11/metaconfig-core_2.12-0.9.11.jar: Connection timed out (Connection timed out), ignoring it

Process metals stderr finished
```
Seems that metals from within Emacs does not take into account System proxy (`*_proxy` env vars), nor Emacs config-file proxy.

I discovered that metals is installed in `/home/gmuller/.emacs.d/.cache/lsp/metals/metals`

Running it in terminal leads to same result.

**To Reproduce**

0. Be behind a proxy
1. Open a scala file in Emacs configured with LSP + older LSP-metals.
2. LSP-metals will try to install/upgrade metals
3. Timeouts will be reached because proxy is not used

**Expected behavior**

System/Emacs Proxy config should be used => install/upgrade should be successful

**Screenshots**

**Installation:**

- Operating system: Linux
- Editor: Emacs
- Metals version: v0.10.7

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! Did you try to ask about this in https://github.com/emacs-lsp/lsp-metals ? It might be better to report it there.

**Comment by tgodzik** [comment]
Most likely the tool that is being used is coursier, you might find some tips here https://scalameta.org/metals/docs/troubleshooting/proxy or as suggested before in lsp-metals. Closing for now, let me know if there is anything we need to do on the server side.

For some proxy/mirrors related issues you might want to follow https://github.com/scalameta/metals/issues/2485
