### ISSUE TITLE
I have to restart server and re-import project every 30 minutes or so

### ISSUE THREAD

**Issue by hoangong** [scalameta/metals#3113]
**Describe the bug**

Metals has some problem. I don't know exact what caused but it happens very randomly. I have to close IDE and terminal all java process then re-import the project to fix the issue. This is the error I have when I see the problem and tried to restart server
```
2021.09.11 21:31:55 INFO  time: Connected to build server in 2.47s
2021.09.11 21:31:55 INFO  Connected to Build server: sbt v1.4.9
2021.09.11 21:31:55 INFO  Processing
2021.09.11 21:32:05 INFO  Disconnecting from sbt session...
2021.09.11 21:32:05 INFO  Shut down connection with build server.
2021.09.11 21:32:05 INFO  Attempting to connect to the build server...
2021.09.11 21:32:05 ERROR Failed to connect with build server, no functionality will work.
scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: WorkspaceBuildTargetsResult.  Boxed InterruptedException
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:237)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:229)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**

1. Do the coding but then auto complete not working.
2. Click on Metals tab, restart server
3. Check the log and see the above error

**Expected behavior**

Metals should not stop working and it should allow restart server without terminate all java processes. It seems java processes were not terminated correctly by metals

**Screenshots**

**Installation:**

- Operating system: macOS Intel
- Editor: Visual Studio Code
- Metals version: v0.10.7

**Additional context**

**Search terms**

**Comment by dos65** [comment]
@1mdc Could you try to upgrade to the latest sbt - 1.5.5? Maybe it's some kind of issue with sbt-bsp-server

**Comment by 1mdc** [comment]
Thanks for the quick response. If that is because of sbt BSP I think I cannot do much at the moment because my team is still using a play framework version which is not compatible with sbt 1.5.x

**Comment by dos65** [comment]
@1mdc 
I realized that it might an issue on metals side if you say that autocompletion stop working. Even if smth goes wrong with bsp server autocompletion should continue work.
 
Are there any error in log/ `~.metals/metals.log`?

**Comment by tgodzik** [comment]
Did you manage to update to a newer sbt version? We haven't had any issues with disconnection in sbt 1.5.x

**Comment by tgodzik** [comment]
Let's open this up again if issues show up with the newest sbt version
