### ISSUE TITLE
code navigation does not work for the file ...

### ISSUE THREAD

**Issue by 1mdc** [scalameta/metals#3128]
**Describe the bug**

```
[0m2021.09.15 16:44:33 INFO  Connected to Build server: Bloop v1.4.8-114-e47368ed[0m
[0m2021.09.15 16:44:35 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.09.15 16:44:37 WARN  no build target for: ....scala[0m
[0m2021.09.15 16:44:38 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.09.15 16:44:39 INFO  time: Imported build in 3.77s[0m
Sep 15, 2021 4:44:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2
Sep 15, 2021 4:44:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 6
Sep 15, 2021 4:44:41 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 8
[0m2021.09.15 16:44:46 ERROR code navigation does not work for the file '....scala' because the SemanticDB file '....scala.semanticdb' doesn't exist. There can be many reasons for this error. [0m
[0m2021.09.15 16:44:46 ERROR code navigation does not work for the file '....scala' because the SemanticDB file '....scala.semanticdb' doesn't exist. There can be many reasons for this error. [0m
[0m2021.09.15 16:44:47 INFO  time: code lens generation in 6.13s[0m
[0m2021.09.15 16:44:47 INFO  time: code lens generation in 7.23s[0m
[0m2021.09.15 16:44:47 INFO  time: code lens generation in 2.03s[0m
[0m2021.09.15 16:44:52 ERROR code navigation does not work for the file '....scala' because the SemanticDB file '....scala.semanticdb' doesn't exist. There can be many reasons for this error. [0m
[0m2021.09.15 16:45:25 WARN  invalid jar: ...-sources.jar[0m
[0m2021.09.15 16:45:31 INFO  time: indexed workspace in 51s[0m
[0m2021.09.15 16:45:32 INFO  no build target: using presentation compiler with only scala-library: 2.12.8[0m
[0m2021.09.15 17:18:12 INFO  Deduplicating compilation of ClientServices from bsp client 'Metals 0.10.6' (since 33m 39.332s)[0m
```

**To Reproduce**

1. Right click on a class
2. Go to references
3. Nothing happens

**Expected behavior**

**Screenshots**

**Installation:**

- Operating system: macOS Intell
- Editor: Visual Studio Code
- Metals version: v0.10.6

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! This looks like an issue with the file in question. We are not detecting it to be a part of any build target or there might be errors when trying to compile it.

Do you see anything in the problems view?

**Comment by 1mdc** [comment]
The problem view does not have any error.  
<img width="1215" alt="Screenshot 2021-09-15 at 17 31 28" src="https://user-images.githubusercontent.com/5703525/133473135-a69f288d-a3ea-4ce6-a032-647073d8b52c.png">

The whole project is compiling fine from the command line, so I think the file itself does not have any error. I tried to restart build server and cascade compile, but it still same error.

**Comment by 1mdc** [comment]
I have this error in a few classes. Majority of other classes are still working fine.

**Comment by tgodzik** [comment]
Anything specific about those files? Are they in sources? Do they all belong to a single module?

`�[0m2021.09.15 16:45:25 WARN  invalid jar: ...-sources.jar�[0m` seems a bit worrying, if that's where the definition is coming from then it will not work for anything coming out of that jar.

**Comment by Arthurm1** [comment]
You might also be getting this message because Metals hasn't finished initialising which is indicated by this message...
`�[0m2021.09.15 16:45:31 INFO  time: indexed workspace in 51s�[0m`
which comes after your errors.

**Comment by 1mdc** [comment]
I don't think that is because of source file because of indexing. I tried it even after indexing it still have the same issue.

However, I got this fixed now by updating my project to the sbt 1.3.x to 1.5.5. I think somethings may not compatible between old sbt version and metals/bloop.

Thank you for helping!

**Comment by tgodzik** [comment]
1.3.x should work, but it might be some particular behavior causing issues here. Without any kind of a small repro we might not be able to help out here.

**Comment by ckipp01** [comment]
Since you got this working I'm going to go ahead and close. If you do happen to hit on this again and have a reproduction, please do reopen!
