### ISSUE TITLE
[Scala 3] Rename extension parameter does not work

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3133]
**Describe the bug**

```scala
  extension (sbd: String)
    def double = sbd + sbd
    def double2 = sbd + sbd
  end extension
```

Renaming will `sbd` only rename the ones in one of the method.

**To Reproduce**

Use the above code snippet

**Expected behavior**

All occurrences of `sbd` are renamed.

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.6

**Additional context**

This is caused by the fact that extension methods generate separate method with different parameters for each method in the extension group. This is also related to https://github.com/scalameta/scalameta/issues/2443

For now we could try searching for all occurences of symbols at the definition of the main parameter, since the main parameter will have a separate occurrence generated for each method.

**Search terms**

scala 3 extension group

**Comment by tanishiking** [comment]
In the discussion https://github.com/scalameta/scalameta/issues/2443 we decided to deal with this problem on Metals side, I'll take a look if it's feasible option :)
