### ISSUE TITLE
Show tasty doesn't work for tasty files

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3135]
**Describe the bug**

When clicking on the tasty file it's not possible to currently read it.

**To Reproduce**

1. Classes directory inside `.bloop` directory
2. Click on any tasty file.
3. Run `Show tasty` command
4. See error about the file not belonging to build target.

**Expected behavior**

We should seach build targets for a class directory that belongs to it or as a fallback use the highest Scala 3 version available. I think we should always be able to read it with the highest versio? @kordyjan ?

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.7

**Search terms**

scala 3 tasty show

**Comment by tgodzik** [comment]
We should also see if when opening tasty files in VS Code we could automatically display tasty instead. Currently it ask to open it and only if you try to open it with txt editor you will be able to run the command.

**Comment by tgodzik** [comment]
Fixed by https://github.com/scalameta/metals/pull/3107

**Comment by tgodzik** [comment]
OR  maybe, let's keep it open, the actual Show tasty command doesn't work yet. We should reuse the same logic as in #3107

**Comment by kpodsiad** [comment]
> We should also see if when opening tasty files in VS Code we could automatically display tasty instead. Currently it ask to open it and only if you try to open it with txt editor you will be able to run the command.

Any chance that you know how to do this?

**Comment by tgodzik** [comment]
> > We should also see if when opening tasty files in VS Code we could automatically display tasty instead. Currently it ask to open it and only if you try to open it with txt editor you will be able to run the command.
> 
> Any chance that you know how to do this?

Looks like we can use https://code.visualstudio.com/api/extension-guides/custom-editors

Example: https://github.com/Microsoft/vscode-extension-samples/tree/main/custom-editor-sample

**Comment by kpodsiad** [comment]
Thanks @tgodzik, I'll look at them!
