### ISSUE TITLE
Show tasty works only for classes named the same as the file

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3136]
**Describe the bug**

If we are in a file with multiple classes and none of them is named as the file (or we have not classes at all), Metals will not find the proper tasty file.

**To Reproduce**

1. Create a file name `Main.scala`
2. Add example contents:

```scala
class NotMain
class AlsoNotMain
```
3. Run `Show tasty` command
4. See error about not being able to find the tasty file.

**Expected behavior**

Proper file is shown based on the cursor positio.

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.7

**Additional context**

There are two way we can solve it:
- try to get that info by using the `ClassFinder` class, but it doesn't work perfectly for all inner classes or anonymous one
- use the same mechanism that was implemented for scala debug adapter

**Search terms**

tasty scala 3

**Comment by keynmol** [comment]
After discussion on discord, it seems like it's sensitive to package vs. file structure

    Operating system: MacOS
    Editor: Neovim
    Metals version: v0.10.7


https://user-images.githubusercontent.com/1052965/133847054-23774bd8-33d3-4190-8c1d-6c4823db7058.mov
