### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#314]
To follow up on https://github.com/scalameta/lsp4s/issues/8. lsp4s has removed several dependencies that we still use in metals but can get rid of

- [ ] logback
- [ ] groovy (for logback)
- [ ] scala-logging
- [ ] circe-generic
- [ ] circe-generic-extras

**Comment by gabro** [comment]
To recap, they are all replaced by scribe and circe-derivation, right?

**Comment by olafurpg** [comment]
Correct. We actually use circe-generic specific features in for the metals `Configuration` that is not supported by circe-derivation so I think we can skip that part and only remove scala-logging and friends.

**Comment by olafurpg** [comment]
Superseded and resolved in https://github.com/scalameta/lsp4s/issues/8

We'll use whatever lsp4s gives us.
