### ISSUE TITLE
[Scala3] Completions with empty query have wrong scope

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#3140]
Having the following sample:
```scala
class Foo {
  val bar = "sadasd"
  b@@  //<-  work correct `bar` is presented
  @@    // <- no `bar`
}
```

The reason of this that `MetalsInteractive.contextOfPath` doesn't handle the case when cursor is just inside `Template` and there is no additional tree inside.

**Installation:**

- Metals version: v0.10.7

**Comment by tgodzik** [comment]
This works correctly now :tada:
