### ISSUE TITLE
Invalid end position in textDocument/format breaks emacs lsp-mode

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#315]
Reported in https://github.com/scalameta/metals/issues/234#issuecomment-399705495

I think we should just compute a valid end position.

**Comment by yyadavalli** [comment]
@gabro any thoughts on how this could be done? I tried looking at `InputEnrichments.scala` and `DocumentFormattingProvider.scala` to see if it is possible and couldn't find it.

**Comment by gabro** [comment]
@yyadavalli I believe something along the lines of https://github.com/prettier/prettier-vscode/blob/master/src/PrettierEditProvider.ts#L227-L230
should work, but done in Scala.

**Comment by olafurpg** [comment]
`scala.meta.Input` has a package private index to convert line numbers to offsets that might come in handy https://github.com/scalameta/scalameta/blob/8f77c6a75c149fb3be75bcc314293132108cbf03/scalameta/inputs/shared/src/main/scala/scala/meta/internal/inputs/InternalInput.scala#L13
