### ISSUE TITLE
javap viewer not always working

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3150]
**Describe the bug**

When in a `.scala` file and attempting to view the decompiled version of it via the newly added javap functionality, I'm hitting on it not really ever being able to find the class. It seems to not be taking packages into account. I see this is being worked on for TASTy stuff in https://github.com/scalameta/metals/pull/3148, but I figured I'd also make sure we have this reported for the javap functionality as well.

**To Reproduce**

1. In a project that is very minimal, `src/main/scala/<a handful of scala files>`
2. Create a `Thing.scala` with a package name.
3. The command that I'm issuing is sending in a URI like this: 
```
[Trace - 09:29:27 PM] Received request 'workspace/executeCommand - (10)'
Params: {
  "command": "metals.file-decode",
  "arguments": [
    "metalsDecode:file:///Users/ckipp/Documents/scala-workspace/sanity/src/main/scala/Thing.scala?decoder\u003djavap"
  ]
}
```
4. The returned error is `Error: class not found: Thing.class`

<img width="849" alt="Screenshot 2021-09-21 at 21 17 39" src="https://user-images.githubusercontent.com/13974112/134235492-92ca29ee-136b-4cbe-a4a3-b9299dc6f75e.png">

Notice a few things in the screen shot, it seems to be looking in the wrong dir not taking into account the package name.

I did also test this with the changes in https://github.com/scalameta/metals/pull/3148, but that seemed to return `Error: class not found: sanity.class`, so for some reason looking for the package name class.

**Expected behavior**

Correctly find the class file.

**Installation:**

- Operating system: macOS
- Editor: Vim -- Note that this isn't merged yet. I'm hitting on these issues as I'm trying to add support for this here: https://github.com/scalameta/nvim-metals/pull/226
- Metals version: latest snapshot

Note that for the same file, the semanticdb viewers both work.

**Comment by tgodzik** [comment]
This is a very similar issue to https://github.com/scalameta/metals/issues/3136

I think we can solve them both at the same time. @kpodsiad is looking into using ClassFinder for that.
