### ISSUE TITLE
Metals extension in VSCode fails to open giter8 templates behind http proxy

### ISSUE THREAD

**Issue by sdennyk** [scalameta/metals#3153]
I'm a new user of metals extension in VSCode. I'm executing metals server behind a http proxy through metals extension in VSCode. Per documentation, I have configured the Metals Server Properties as below (the proxyHost and port have been masked for illustration purpose)

    "http.proxyAuthorization": null,
    "metals.serverProperties": [
        "-Xmx512m",
        "-Dhttps.proxyHost=proxy.domain.com",
        "-Dhttps.proxyPort=port",
        "-Dhttps.proxyStrictSSL=False",
        "-Dhttp.proxyHost=proxy.domain.com",
        "-Dhttp.proxyPort=port",
        "-Dhttp.proxyStrictSSL=False"
    ],
    "http.proxyStrictSSL": false,
    "metals.javaHome": "C:\\Program Files\\RedHat\\java-11-openjdk-11.0.8-2" 

Initially I had problem with starting metals server but after configuring the metals Server Properties, that has been resolved. However I'm still getting a giter8 error "cannot open git-upload-pack". Looks like the metals extension is not able to open the giter8 templates. Do I need to configure any other http proxy property. Any input is much appreciated.

The metals log is as follows:

INFO  Started: Metals version 0.10.7 in workspace 'C:\Users\username\source_code\snowpark' for client Visual Studio Code 1.57.1
INFO  time: initialize in 1.45s
WARN  Build server is not auto-connectable
WARN  no build tool detected in workspace 'C:\Users\username\source_code\snowpark'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt.
ERROR https://github.com/scala/hello-world.g8.git: cannot open git-upload-pack
INFO  time: ran 'giter8.Giter8' in 23s

**Comment by ams1** [comment]
Hi, I've also hit the exact same thing - working behind a proxy and trying to create a New Scala project. Any possible workarrounds until the bug is fixed?

P.S.: Great initiative with the extension!

**Comment by kpodsiad** [comment]
Hi @ams1. I'm afraid that currently there is no workaround for this bug. 

However, I'm working on simplifying proxy set up and I'll fix this bug too!
