### ISSUE TITLE
Migrate LSPLogger to scribe

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#317]
LSPLogger is as a custom sl4j transport that logs messages to the client via the LSP, which allows editors to show them to the user. VSCode, for example, does in the Output panel for Metals.

Moving to Scribe requires rewriting that bit of functionality, so that messages are send to both the metals.log file and the LSP client.

I have already a working implementation of this, which I'll PR as soon as we merge the lsp4s migrations, which scrambles some dependencies around.

**Comment by olafurpg** [comment]
Superseded by #318 which will involve migrating logging to scribe.
