### ISSUE TITLE
Syntax errors when opening "scala/scala3.g8"

### ISSUE THREAD

**Issue by mbovel** [scalameta/metals#3181]
**Describe the bug**

Scalameta incorrectly assumes Scala 2 when opening "scala/scala3.g8".

**To Reproduce**

1. `sbt new scala/scala3.g8`
2. `cd [project-dir]`
3. `code .`
4. Error: `expected start of definition (scalameta)` (see screeshot).

Note: quitting and re-opening VSCode solves the problem.

**Expected behavior**

No errors when opening for the first time.

**Screenshots**

<img width="571" alt="Screenshot 2021-10-04 at 13 34 35" src="https://user-images.githubusercontent.com/777748/135846226-6a4c6108-57aa-47bb-af31-09e91e0501ba.png">

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.10.11

**Comment by tgodzik** [comment]
Thanks for reporting! This is due to the fact that the default version of Scala used is Scala 2.12, which will report issues before importing the project. We changed that in the most recent master, but you should also be able to run build import and modify the file to get that error to disappear.

This should be fixed with the next release.

**Comment by mbovel** [comment]
Thanks for the quick answer! So will this work out of the box with the next Metals release? Do you know when it will be released?

> you should also be able to run build import and modify the file to get that error to disappear.

Yes that works.

**Comment by mbovel** [comment]
> Most likely we will be shipping a new release next week.

Ok, cool!

> You should also be able to change the metals fallback version in the user settings so it should work out of the box in new workspaces.

Excellent, thanks for pointing out this setting. I added `"metals.fallbackScalaVersion": "3.0.2"` to `.vscode/settings.json` in [the project in question](https://gitlab.epfl.ch/lamp/cs210-worksheets), so that it already works from the first opening for all its users.

**Comment by caldempsey** [comment]
This is happening for me on a fresh install.

**Comment by caldempsey** [comment]
<img width="697" alt="image" src="https://github.com/scalameta/metals/assets/8885269/ce57fbe8-1ee3-4cb6-9ad8-157ff74720af">

**Comment by caldempsey** [comment]
oh the fix was using the 'pre-release version' that doesn't seem right... cc @tgodzik

**Comment by tgodzik** [comment]
This should not be an issue unless your project uses Scala 2. We default to scala 3 as far as I know. You send us the logs to see what is going on
