### ISSUE TITLE
textDocument/documentHighlight highlights unrelated symbols in build.sbt

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#3197]
**Describe the bug**

Moving my mouse over an sbt setting highlights lot of unrelated names in build.sbt.

**To Reproduce**

1. Move cursor over an sbt symbol like `settings` in build.sbt

**Expected behavior**

It should only highlight other usages of the `settings` symbol.

**Screenshots**
![CleanShot 2021-10-13 at 13 05 14](https://user-images.githubusercontent.com/1408093/137121513-eb65730e-c89f-40b0-ac5c-a7ca961931a9.gif)

**Installation:**

- Operating system: macOS
- Editor: VS Code
- Metals version: v0.10.7

**Comment by tgodzik** [comment]
We moved document highlight to presentation compiler, so this will no longer happen.
