### ISSUE TITLE
Snapshot build 0.10.7+94-7bd4dd41-SNAPSHOT appears to leak file handles

### ISSUE THREAD

**Issue by dickwall** [scalameta/metals#3201]
**Describe the bug**

I have been trying out version `0.10.7+94-7bd4dd41-SNAPSHOT` as it enables readable toStrings on the debugger (which works great by the way)!

However I noticed that repeated debugging sessions were failing to start with this version, and after some trial and error I noticed that the problem appeared to be `Too Many Open Files` in the Java process. This seems to be related to the SNAPSHOT build above (not sure if it is just related to the toString debug enhancement or something else, but I wanted to notify you before this version hits the mainstream).

Using standard version 0.10.7, after several restarts of the debugger, the two Java PIDs have the following file handle counts:

```
(base) dwall@L10441 ~ % lsof -p 28155 | wc -l
    2489
(base) dwall@L10441 ~ % lsof -p 28165 | wc -l
     753
```

However when running the snapshot version above, even after one debugging session, the number of file handles open in one of the processes was much higher:

```
(base) dwall@L10441 ~ % lsof -p 13335 | wc -l
    2535
(base) dwall@L10441 ~ % lsof -p 13344 | wc -l
   10749
```

This quickly exhausts any reasonable limit on the number of files per process and causes the debugger session (or any run session, including running tests) to fail.

**To Reproduce**

1. Enable the `0.10.7+94-7bd4dd41-SNAPSHOT` version in the vscode settings (Metals Server) and restart vscode/metals
2. Open a reasonably large, complex Scala project
3. Start the debugger
4. Check the number of files open from both java processes (find the java PIDs and `lsof -p <pid> | wc -l`)
5. Stop and restart the debugger a few times and watch the number growing. You may see the debugger fail to start once the number of open files is very high.

**Expected behavior**

With 0.10.7 (mainline) the number of open file handles is stable and reasonable (under 1000 even on a large project)

**Screenshots**

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.7 / v0.10.7+94-7bd4dd41-SNAPSHOT

**Additional context**

Making sure this is caught before it reaches v0.10.8

**Search terms**

Too many open files, debugger won't start

**Comment by dos65** [comment]
I've tried to reproduce it on Metals repo but it seems that after several debug sessions the number of opened files doesn't change nor at Metals process nor at Bloop.

@dickwall Could you add main class name to processes you reported?

**Comment by dickwall** [comment]
OK - with the snapshot build version:

```
dwall            34964 ...  scala.meta.metals.Main
dwall            34974 ...  bloop.Server 8212
```

And the open files count, prior to running the debugger at all:

```
(base) dwall@L10441 ~ % lsof -p 34964 | wc -l
     927
(base) dwall@L10441 ~ % lsof -p 34974 | wc -l
    1489
```

And after starting the debugger the first time:

```
(base) dwall@L10441 ~ % lsof -p 34964 | wc -l
    1982
(base) dwall@L10441 ~ % lsof -p 34974 | wc -l
    6861
```

after stopping the debugger:

```
(base) dwall@L10441 ~ % lsof -p 34964 | wc -l
    1979
(base) dwall@L10441 ~ % lsof -p 34974 | wc -l
    6855
```

and after starting a second time:

```
(base) dwall@L10441 ~ % lsof -p 34964 | wc -l
    1982
(base) dwall@L10441 ~ % lsof -p 34974 | wc -l
   10392
```

also got this in the metals log:

```
2021.10.14 16:56:21 INFO  Starting debug proxy for [REDACTED]
2021.10.14 16:56:22 ERROR java.nio.file.FileSystemException: /Users/dwall/dev/REDACTED/.bloop/b2b-common/bloop-bsp-clients-classes/classes-Metals-yfpCCZGdSzKP9Q8rYw9XwQ==/REDACTED: Too many open files
2021.10.14 16:56:22 INFO  Closing debug server tcp://0.0.0.0:55772
```

sorry for the redactions, but I'm working on company code and better safe than sorry :-)

the debugger was started with the following launch json, (but with a few renames...):

```
    {
      "type": "scala",
      "name": "Debug Scheduler",
      "request": "launch",
      "mainClass": "com.some.server.SomeServer",
      "buildTarget": "some-machine",
      "args": ["-config", "testing", "-http.port=:7072", "-admin.port=:9992"]
    },
```

this was the same launch json used for both 0.10.7 and this snapshot.

I'm happy to help more, but will be limited with what I can share about the project code. I'll see if I can make it happen the same with an open source project over the weekend so that I give you a specific environment to recreate it if you are still unable to reproduce.

**Comment by adpi2** [comment]
Update: I think the root cause is that the inputStreams [here](https://github.com/scalacenter/scala-debug-adapter/blob/8fbd52d435b45d9bfeab040875745af08b7271a7/core/src/main/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUp.scala#L268) and [here](https://github.com/scalacenter/scala-debug-adapter/blob/8fbd52d435b45d9bfeab040875745af08b7271a7/core/src/main/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUp.scala#L87) are never closed. So I am fixing and validating that.
