### ISSUE TITLE
Silencer plugin affecting worksheet evaluation

### ISSUE THREAD

**Issue by stumash** [scalameta/metals#3215]
**Describe the bug**

worksheets are not evaluating and showing the results as virtual text

**To Reproduce** Steps to reproduce the behavior:

1. Open a scala project with an sbt file and everything
2. Verify that various LSP/Metals-related functionality is working (go to def, show help, etc.)
3. Open an existing `*.worksheet.sc` file
4. Autocomplete still works in it, and the lsp status bar says it's evaluating, but there is no virtual text showing the evaluations

**Expected behavior**

virtual text shows the value of lines of code

**Screenshots**

no virtual text 
![image](https://user-images.githubusercontent.com/13181078/138149053-a4b1f5cd-5030-416a-8ab3-7b5c9d39fcdb.png)

but yes autocomplete
![image](https://user-images.githubusercontent.com/13181078/138149110-2d2d524d-af89-4051-91e8-871aacd403c3.png)

**Installation:**

- Operating system: macOS
- Nvim version: NVIM v0.5.1
- Commit of nvim-metals: ab78a00c1db8c8b
- Metals version: metals 0.10.6-M1

**Additional context**

my configs
```lua
vim.lsp.set_log_level("debug")
local nvim_lsp = require('lspconfig')

local servers = { "rust_analyzer", "tsserver", "pylsp" }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
    flags = { debounce_text_changes = 150 },
    on_attach = function(client)
      require'aerial'.on_attach(client)
    end,
  }
end
```

```vim
"""" NVIM-METALS: config for scala language server, metals
" useful for restarting metals
nnoremap <leader>ore :!rm -rf .metals .bloop project/metals.sbt<CR>:MetalsRestartServer<CR>
" silence messages about stuff I think?
set shortmess-=F
```
```lua
_G.metals_config = require("metals").bare_config
_G.metals_config.capabilities = require'cmp_nvim_lsp'.update_capabilities(vim.lsp.protocol.make_client_capabilities())
_G.metals_config.settings = { showImplicitArguments = true }
_G.metals_config.init_options.statusBarProvider = "show-message"
_G.metals_config.on_attach = function(client, bufnr) require'aerial'.on_attach(client) end
```
```vim
augroup lsp
  autocmd!
  autocmd FileType scala,sc,sbt lua require("metals").initialize_or_attach(_G.metals_config)
augroup END
```

**Search terms**

worksheet
evaluation
virtual text
completion

**Comment by ckipp01** [comment]
Transfered this over to the main repo since it's not `nvin-metals` specific looking at the logs. By chance are you using https://github.com/ghik/silencer in your build? From looking at the logs it seems to be chocking on that, although I'm not sure why. To verify this, if you just go to a scratch workspace and create a worksheet does it work for you?

**Comment by stumash** [comment]
ah! good idea! you're right! it worked in a blank repo!

but why would metals get affected by the particular dependencies of my scala project?

**Comment by ckipp01** [comment]
> yes I'm using that

What version of Scala are you using? As of 2.12.13 this plugin is obsolete as it's no build into the language with `@nowarn`. So my quick answer would be try to get rid of it. However, I'll try to see if I can reproduce this to understand why it's affecting worksheet evaluations.

**Comment by stumash** [comment]
I'm on 2.12.12 😳

**Comment by stumash** [comment]
If it's of any use, whenever I open it in a new scala project with this `silencer` dependency, it tells me there's something wrong and to hit 1 to see diagnostic info (metals doctor). The doctor says everything is fine though, and there's nothing suspicious in the logs until I go try a worksheet

**Comment by tgodzik** [comment]
I think the reason here might be that we compile mdoc only for the most recent 2.12.x version, which is not perfect but seems to work ok for the part of the compiler that mdoc uses. This might cause issues with  other plugins :thinking: that use API that changed, but not sure exactly why.
