### ISSUE TITLE
Exception when hover nonexistent case class

### ISSUE THREAD

**Issue by chessman** [scalameta/metals#3245]
**Describe the bug**

I found a case where HoverProvider throws an exception.It doesn't affect UX much, but I guess it would be good to fix.

**To Reproduce**

1. Write `val a = A(1)` where A is not defined.
2. Put cursor on `1`.
3. See exception in logs:

```
Oct 31, 2021 12:11:29 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
	at scala.meta.internal.pc.HoverProvider.toHover(HoverProvider.scala:222)
	at scala.meta.internal.pc.HoverProvider.hoverOffset(HoverProvider.scala:128)
	at scala.meta.internal.pc.HoverProvider.$anonfun$hover$1(HoverProvider.scala:24)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.pc.HoverProvider.hover(HoverProvider.scala:24)
```

**Expected behavior**

No exceptions.

**Installation:**

- Operating system: Linux
- Editor: Emacs
- Metals version: v0.10.8

**Additional context**

scala 2.13.6, Ammonite

**Comment by dos65** [comment]
Thanks for reporting! That's a bug.

The only thing, is that I'm wondering how it happened on Emacs as this branch only executes for range hover request which was implemented specifically only for VS Code and for nvim.

@chessman could you [collect traces](https://scalameta.org/metals/docs/contributors/getting-started/#json-rpc-trace) reproducing this issue and share them? I think it would be useful to look how Emacs send hover request to ensure that we didn't break anything after introducing specific processing for range hovers.

**Comment by chessman** [comment]
@dos65 there are bsp and lsp traces https://gist.github.com/chessman/3dd294024813bfa640aa9a247d1d376b

**Comment by dos65** [comment]
@chessman Thanks! I was a bit confused that according to stacktrace this shouldn't happen for Emacs editor but after you provided lsp-traces I found a bug on our side
