### ISSUE TITLE
No autocomplete suggestions for methods on Scala 3

### ISSUE THREAD

**Issue by justf0rfun** [scalameta/metals#3246]
**Describe the bug**

On a simple project I get no autocomplete suggestions for methods on a given symbol when project is configured to Scala 3.

**To Reproduce**

1. Create a project
2. Configure it for Scala 3 with Mill or with SBT
3. Open the project folder with VSCode
4. Create a Scala source file
5. Create a Scala symbol representing an object e.g. a String literal followed by the dot for the dot notation `"".`
6. Press Ctrl + Space to get autocomplete suggestions.

**Expected behavior**

I would expect, to see VSCode displaying a list of autocomplete suggestions to choose from.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/3073919/139585046-8203ea52-fdde-4712-a8d1-ae3222d42468.png)

**Installation:**

- Operating system: Lubuntu Linux 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=20.04
    DISTRIB_CODENAME=focal,
    DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
    Linux buero 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Editor: Visual Studio Code 1.61.2
- Metals version: v0.10.8

**Additional context**

When I set the Scala version to 2.13.6 suggestions work fine. When I set the Scala version to 3.x. I do not get suggestions. I tried it with Mill and with SBT and it is the same. I wonder that there is no issue filed, yet. Am I the only one that encounters this behavior? I would expect the mistake on my side, but the project is so small and simple that there isn't much room for mistakes left.

I found the following in metals.log but it does not occur repeatedly when trying to get suggestions multiple times. In may be totally unrelated. I can't judge.

> Okt. 31, 2021 1:45:02 NACHM. scala.meta.internal.pc.CompilerAccess handleError
SCHWERWIEGEND: null
java.lang.NullPointerException
	at scala.meta.internal.pc.HoverProvider.toHover(HoverProvider.scala:222)
	at scala.meta.internal.pc.HoverProvider.hoverOffset(HoverProvider.scala:128)
	at scala.meta.internal.pc.HoverProvider.$anonfun$hover$1(HoverProvider.scala:24)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.pc.HoverProvider.hover(HoverProvider.scala:24)

> Okt. 31, 2021 1:45:02 NACHM. scala.meta.internal.pc.CompilerAccess handleError
SCHWERWIEGEND: null
java.lang.NullPointerException
	at scala.meta.internal.pc.HoverProvider.toHover(HoverProvider.scala:222)
	at scala.meta.internal.pc.HoverProvider.hoverOffset(HoverProvider.scala:128)
	at scala.meta.internal.pc.HoverProvider.$anonfun$hover$1(HoverProvider.scala:24)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.pc.HoverProvider.hover(HoverProvider.scala:24)

**Search terms**

auto complete suggestion method

**Comment by dos65** [comment]
@justf0rfun Thanks for reporting!

Which scala 3 version do you use?
I'm able to reproduce it, the completions list for `s.@@` is incorrect but in my case it isn't empty.

**Comment by dos65** [comment]
@justf0rfun I want' correct. Everything works fine, tested in on all Scala3 versions: `3.0.0` -> `3.1.0`.

I have no idea what might be wrong. Could you attach the full `.metals/metals.log`?

**Comment by ckipp01** [comment]
Seeing that this has been a couple months and we haven't received any more info I'm going to go ahead and close since it's not actionable with the current info. Please do report back if you have more info and we can re-open.

**Comment by vzmerr** [comment]
Just for the reference of future users: make sure you have enabled "show methods" in VSCode completion settings.
