### ISSUE TITLE
Lose type info for circe semi-auto derivation with @JsonCodec annotation

### ISSUE THREAD

**Issue by ye-will** [scalameta/metals#3257]
**Describe the bug**

Seems type infer was broken with circe's @JsonCodec annotation.

**To Reproduce**

There's no auto completions for val `json`, but NO problem was detected in PROBLEMS window of vscode.

```scala
package example

import io.circe.generic.JsonCodec
import io.circe._
import io.circe.syntax._

@JsonCodec case class Foo(bar: String, baz: Map[String, String])

object Hello extends App {
  val bucket = Foo("bar", Map("a" -> "A", "b" -> "B"))
  val json = bucket.asJson                              // expected `Json` but got `Any` here
  val check = json.isInstanceOf[Json]
  println(check)
}
```

However, these code works correctly.

```scala
package example

// import io.circe.generic.JsonCodec
import io.circe._
import io.circe.generic.semiauto._
import io.circe.syntax._

case class Foo(bar: String, baz: Map[String, String])

object Hello extends App {
  implicit val fooDecoder: Decoder[Foo] = deriveDecoder
  implicit val fooEncoder: Encoder[Foo] = deriveEncoder
  val bucket = Foo("bar", Map("a" -> "A", "b" -> "B"))
  val json = bucket.asJson                              // works
  val check = json.isInstanceOf[Json]
  println(check)
}
```

**Expected behavior**

**Screenshots**

**Installation:**

- Operating system: macOS (M1 chip) / Linux
- Editor: Visual Studio Code
- Metals version: v0.10.8
- Java Version: Oracle JDK 17 2021-09-14 LTS (Mac) / OpenJDK 11 AMD64 (Linux)

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! Does it work if you put `JsonCodec` annotated class in a separate file? I think this might be an issue with macros not being processed by the presentation compiler in Metals, which could be on purpose as macros break the trees that we use for completions.

**Comment by ye-will** [comment]
It's OK now while putting `@JsonCodec` in a separate file, thanks.

**Comment by tgodzik** [comment]
Closing it as it's working as expected. It's not perfect at all, but I don't think we'll be able to fix this any time soon.
