### ISSUE TITLE
"debug"/"debug test" not working on VS Code within Windows

### ISSUE THREAD

**Issue by marciocg** [scalameta/metals#3262]
**Describe the bug**

Debug session freezes and doesn't executes properly.
**To Reproduce**

1. Go to any .scala file
2. Click on 'debug' or 'debug test'
3. See error

Debug toolbar is inactive and keys F10/F11 can't be used on debug session. The line with breakpoint isn't attached for inspection.

Screenshot of the disabled debug toolbar:
![image](https://user-images.githubusercontent.com/4554906/139964452-1d406753-4e22-4680-bf82-4d65f1a255c9.png)

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.10.8 and it's newest snapshots until 02/11

**Additional context**
There's an **IllegalArgumentException** on the .metals/metals.log 
[metals.log](https://github.com/scalameta/metals/files/7464485/metals.log)
:

**Comment by dos65** [comment]
Thanks for reporting!
This one is already fixed in #3238 and will be released soon

**Comment by tgodzik** [comment]
> Thanks for reporting! This one is already fixed in #3238 and will be released soon

Actually, just checked and it's a different error https://github.com/scalameta/metals/pull/3263

Should have fixed it together.
