### ISSUE TITLE
Drop unstable features that nobody is working on

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#327]
Metals currently supports completions and diagnostics-as-you-type by using the presentation compiler. This functionality is not enabled by default because it doesn't work well, in particular for multi-module builds and longer running coding sessions. There is no ongoing effort to make this functionality work robustly so I propose to remove it altogether. Keeping the functionality is a maintenance burden both code-wise and documentation-wise.

Any objections?

**Comment by gabro** [comment]
Kill them with 🔥

**Comment by xeno-by** [comment]
No objections.

**Comment by olafurpg** [comment]
What do you think @laughedelic ?

**Comment by laughedelic** [comment]
+1! Let's do it.

**Comment by Daenyth** [comment]
It'll always be in git if someone wants to resurrect it later.
