### ISSUE TITLE
Organize imports fails with by-type given import

### ISSUE THREAD

**Issue by erdnaxeli** [scalameta/metals#3283]
**Describe the bug**

When using a by-type given import, the "organize imports" action on VSCode fails with the following error:

> 2021.11.11 23:08:04 ERROR given UrlContentFetcher (of class scala.meta.Importee$Given$ImporteeGivenImpl)
> scala.meta.internal.metals.ScalafixProvider$ScalafixRunException: given UrlContentFetcher (of class scala.meta.Importee$Given$ImporteeGivenImpl)
> 	at scala.meta.internal.metals.ScalafixProvider.$anonfun$organizeImports$1(ScalafixProvider.scala:113)
> 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
> 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
> 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.lang.Thread.run(Thread.java:829)
> 
> [Error - 23:08:04] Request textDocument/codeAction failed.
>   Message: Internal error.
>   Code: -32603 
> java.util.concurrent.CompletionException: scala.meta.internal.metals.ScalafixProvider$ScalafixRunException: given UrlContentFetcher (of class scala.meta.Importee$Given$ImporteeGivenImpl)
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
> 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
> 	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
> 	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
> 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: scala.meta.internal.metals.ScalafixProvider$ScalafixRunException: given UrlContentFetcher (of class scala.meta.Importee$Given$ImporteeGivenImpl)
> 	at scala.meta.internal.metals.ScalafixProvider.$anonfun$organizeImports$1(ScalafixProvider.scala:113)
> 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
> 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
> 	... 4 more
> 
> 

**To Reproduce**

Create a new scala3 project, then

Toto.scala
```Scala
trait Toto

given Toto with {}
```

`Main.scala`
```Scala
import toto.{given Toto}
```

Execute the "organize imports "action.

**Expected behavior**

It works :)

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.14

**Additional context**

**Search terms**

**Comment by dos65** [comment]
@erdnaxeli Thanks for reporting! This one was fixed in #3273
Until the next release, you can switch on the snapshot version of Metals - `0.10.9+30-f4bd2700-SNAPSHOT` which includes this fix
