### ISSUE TITLE
Scaladoc does not autocomplete on Scala 3 (works on Scala 2.13.7)

### ISSUE THREAD

**Issue by scilari** [scalameta/metals#3285]
**Describe the bug**
 
Instead of suggesting and autocompleting Scaladoc, Metals suggests random Scala completions, making the feature unusable. 

**To Reproduce**

1. Create new Scala project with Metals using template scalameta.mill-scala-seed.g8
2. Test Scaladoc autocomplete with the default Scala version 2.13.7 => Works as expected
3. Change Scala version in build.sc to 3.1.0
4. Test Scaladoc autocomplete again, and see it failing

**Expected behavior**

Metals should autocomplete Scala 3 Scaladocs as with Scala 2.13.x.

**Screenshots**
![Scala 2.13.7 correct suggestion](https://user-images.githubusercontent.com/9742230/141658229-0c74fb81-a0e8-4b1a-a2a5-62a6152be552.png)
![Scala 2.13.7 correct autocompletion](https://user-images.githubusercontent.com/9742230/141658242-1750288b-6e0a-4cb9-8caf-23f9cbbe0846.png)
![Scala 3.1.0 fail](https://user-images.githubusercontent.com/9742230/141658264-29916519-e102-4a0b-b73d-f59ee9e31fe7.png)

**Installation:**

- Operating system: Windows with WSL 2 and Ubuntu 20.04.3 LTS
- Editor: Visual Studio Code
- Metals version: v0.10.9

**Search terms**

Scaladoc autocomplete

**Comment by ckipp01** [comment]
Thanks for the report @scilari! This isn't yet implemented for Scala 3. You can see the feature request for it here: https://github.com/scalameta/metals-feature-requests/issues/181
