### ISSUE TITLE
Only one user can use metals on ubuntu20.04

### ISSUE THREAD

**Issue by pyzxwjj** [scalameta/metals#3301]
**Describe the bug**

Metals works well for the first user on ubuntu, but it cannot connect to the server for the other users on the same server.

Log
> [0m[36m[T][0m bloop.data.Project$ProjectReadException: Failed to load project from /home/test_java6/SpinalTemplateSbt/.bloop/mylib-test.json
> [0m[36m[T][0m 	bloop.data.Project$.fromBytesAndOrigin(Project.scala:193)
> [0m[36m[T][0m 	bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:256)
> [0m[36m[T][0m 	bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:60)
> [0m[36m[T][0m 	monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
> [0m[36m[T][0m 	monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
> [0m[36m[T][0m 	monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
> [0m[36m[T][0m 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [0m[36m[T][0m 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [0m[36m[T][0m 	java.lang.Thread.run(Thread.java:748)
> [0m[36m[T][0m Caused by: java.nio.file.AccessDeniedException: /home/test_java6/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.12/scala-compiler-2.11.12.jar
> [0m[36m[T][0m 	sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
> [0m[36m[T][0m 	sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
> [0m[36m[T][0m 	sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
> [0m[36m[T][0m 	sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
> [0m[36m[T][0m 	sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
> [0m[36m[T][0m 	sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
> [0m[36m[T][0m 	java.nio.file.Files.readAttributes(Files.java:1737)
> [0m[36m[T][0m 	bloop.ScalaInstance.$anonfun$hashCode$1(ScalaInstance.scala:82)
> [0m[36m[T][0m 	scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
> [0m[36m[T][0m 	scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
> [0m[36m[T][0m 	scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
> [0m[36m[T][0m 	scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
> [0m[36m[T][0m 	scala.collection.TraversableLike.map(TraversableLike.scala:286)
> [0m[36m[T][0m 	scala.collection.TraversableLike.map$(TraversableLike.scala:279)
> [0m[36m[T][0m 	scala.collection.AbstractTraversable.map(Traversable.scala:108)
> [0m[36m[T][0m 	bloop.ScalaInstance.<init>(ScalaInstance.scala:78)
> [0m[36m[T][0m 	bloop.ScalaInstance$.newInstance$1(ScalaInstance.scala:152)
> [0m[36m[T][0m 	bloop.ScalaInstance$.$anonfun$apply$7(ScalaInstance.scala:157)
> [0m[36m[T][0m 	java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
> [0m[36m[T][0m 	bloop.ScalaInstance$.apply(ScalaInstance.scala:157)
> [0m[36m[T][0m 	bloop.data.Project$.$anonfun$fromConfig$1(Project.scala:210)
> [0m[36m[T][0m 	scala.Option.flatMap(Option.scala:271)
> [0m[36m[T][0m 	bloop.data.Project$.fromConfig(Project.scala:205)
> [0m[36m[T][0m 	bloop.data.Project$.fromBytesAndOrigin(Project.scala:187)
> [0m[36m[T][0m 	bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:256)
> [0m[36m[T][0m 	bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:60)
> [0m[36m[T][0m 	monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
> [0m[36m[T][0m 	monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
> [0m[36m[T][0m 	monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
> [0m[36m[T][0m 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [0m[36m[T][0m 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [0m[36m[T][0m 	java.lang.Thread.run(Thread.java:748)
error: The launcher failed to establish a bsp connection, aborting...
[0m2021.11.19 14:43:59 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)

**To Reproduce**
1. User A opens a scala project on ubuntu server using vscode via remote ssh extension. Go to definition, auto complement work well. 
2. User B opens another project.  The metals displays "Failed to connect with build server, no functionality will work. 
**Expected behavior**

**Screenshots**

**Installation:**

- Operating system: Utuntu20
- Editor: Visual Studio Code
- Metals version: v1.10.15

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! This is a current limitation of Bloop, but we are actually working on making it possible to use multiple Bloop servers on one machine.

As a current workaround you could use sbt or mill BSP servers.

I think there should be a way of changing the default port for Bloop, but I can't find it currently.

**Comment by pyzxwjj** [comment]
> 

thank you for your reply.

**Comment by ckipp01** [comment]
Since this isn't really a bug, but rather a limitation of Bloop atm, I'll go ahead and close since there some work arounds, using sbt as a  BSP server for example. If you have any other questions on this, don't hesitate.

**Comment by dos65** [comment]
Maybe transfer it to bloop?
It's not just a limitation but also a security issue

**Comment by ckipp01** [comment]
Well from my understanding in the past there is nothing actually keeping 2 Bloop servers from running. It _can_ already happen, but we don't do it and the site make site sound like it's impossible. I'm unaware of the security issue. What's the issue @dos65?

**Comment by tgodzik** [comment]
> Well from my understanding in the past there is nothing actually keeping 2 Bloop servers from running. 

I think there is no way to have it currently, since both will try to use the same port. Using named sockets would solve it.

The security issue is that Bloop could be started by a different user that has root access and connencted to by clients that don't have that access (I think.)

**Comment by dos65** [comment]
@ckipp01 

> What's the issue 

I haven't tried it yet but the following should be possible: you could put a project into `/tmp` and run code with an access to home directory of user who started bloop.

**Comment by ckipp01** [comment]
Gotcha, thanks for explaining. I went ahead and transferred it over to Bloop.

**Comment by davidmlw** [comment]
Hi, There. Is this issue with some new progresses? It is really an limitation of metals for mutliusers in one server. As I know Bloop supprt environment `BLOOP_PORT` to start multiple server in one machine. But metals, didn't respect the env var.

**Comment by tgodzik** [comment]
@davidmlw did Bloop start with the correct port and did Metals not connect to it? I think for Metals we might be using a configuration property that you would need to add to server properties `-Dmetals.bloop-port=1234`

**Comment by davidmlw** [comment]
@tdudzik I confirm that bloop CLI respect the BLOOP_PORT var and start muliple servers. Currently I use metals from Emacs and Vscode, both of them will not respect BLOOP_PORT and different users will conflict the default bloop port in metals.

It is better that metals can support a scheme, respeting an environment var or start with a parameter, then Emacs and Vscode can use this capability.
