### ISSUE TITLE
Doctor show false warnings on ammonite scripts

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals#3305]
**Describe the bug**
Doctor commands shows a false positive warning message when using standalone ammonite scripts and ammonite is used as BSP.

**To Reproduce**

1. Create any ammonite file outsite of a project
2. Run doctor command
3. Notice false warnings
```
No build server found. Try to run the generate-bsp-config command.

These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.
```
Also this warning although the code navigation works fine
![image](https://user-images.githubusercontent.com/1632384/142876726-8ef74c8a-9588-46c8-a442-f530b535300f.png)

**Expected behavior**
No false warnings

**Installation:**

- Operating system: Linux
- Editor: Sublime
- Metals version: 0.10.9+54-3f211b03-SNAPSHOT
- Scala version 2.13.7

**Search terms**
ammonite, doctor, BSP

**Comment by tgodzik** [comment]
Thanks for reporting! This is most likely one of the cases with Ammonite we forgot to cover.

**Comment by ayoub-benali** [comment]
I don't know if it is related but I noticed this log line from metals as well: 
`INFO  no build target: using presentation compiler with only scala-library: 3.1.0`
 
I don't know if scala 3.1.0 is really used or the message is wrong

**Comment by tgodzik** [comment]
> I don't know if it is related but I noticed this log line from metals as well: `INFO no build target: using presentation compiler with only scala-library: 3.1.0`
> 
> I don't know if scala 3.1.0 is really used or the message is wrong

I think the message is wrong, I hoped I fixed it, but it seems I haven't unfortunately. That's the default Scala version fro standalone files and for second or two before connecting to the build server Metals thinks that the file doesn't belong to any build target.

**Comment by ayoub-benali** [comment]
Just realized another issue:   
Goto definition effectively does **not** work properly unless `// scala 2.13.7` is added to the script. This makes part of the warnings true.
But setting the version fixes the problem but the warming remains.
