### ISSUE TITLE
metals.sbt duplicated during initial project import

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/metals#3306]
**Describe the bug**

When I import new project in vim I get 3 identical files:

```
$ find . -name metals.sbt
./project/project/project/metals.sbt
./project/project/metals.sbt
./project/metals.sbt
```

**Expected behavior**

```
$ find . -name metals.sbt
./project/metals.sbt
```

**Installation:**

- Operating system: Linux
- Editor: Vim 8.2 8023428
- Metals version: v0.10.9
- coc-nvim: 0.0.80-03c9add7cd
- node: v14.17.6
- coc-metals: 1.0.11

**Search terms**

metals.sbt duplication

**Comment by ckipp01** [comment]
Hey @arbitrary-dev, so this is actually working as expected. To give a bit of insight into what is going on here, the first `project/metals.sbt` is needed to be able to import your build definition. Then you want to actually have support for your sbt files, meaning your meta-build, which means we also need to add the plugin one layer above that. Then, you also probably want support for the files in your `project` dir, so we need to then add another one basically in your meta meta build. As long as you just have any `metals.sbt` file in your .gitignore this should be an issue. Hope that clears it up.
