### ISSUE TITLE
The debugger and the debuggee are running in different versions of JVMs. You could see wrong source mapping results.

### ISSUE THREAD

**Issue by danielbasso** [scalameta/metals#3331]
When trying to run a project (sometimes not even debugging) I keep getting this warning on vscode:

```
[Warn] The debugger and the debuggee are running in different versions of JVMs. You could see wrong source mapping results.
Debugger JVM version: 14.0.2
Debuggee JVM version: 11.0.13
```

The solution seems simple, all I want to is use the `Debugger JVM ` as the 11.0.13. But I can't find where I change this setting.  Help please.

**Comment by tgodzik** [comment]
Thanks for reporting! The java home can be set in https://scalacenter.github.io/bloop/docs/server-reference#custom-java-home

**Comment by danielbasso** [comment]
Thank you @tgodzik . It seems to have worked, but now the project won't start:

```
2021.12.01 15:19:50 INFO  running '/tmp/metals316815665837120773/gradlew --console=plain --init-script /tmp/metals316815665837120773/init-script.gradle bloopInstall'
2021.12.01 15:19:52 INFO  > Task :configureBloopInstall
2021.12.01 15:19:52 INFO  > Task :bloopInstall
2021.12.01 15:19:52 INFO  
2021.12.01 15:19:52 INFO  BUILD SUCCESSFUL in 1s
2021.12.01 15:19:52 INFO  2 actionable tasks: 2 executed
2021.12.01 15:19:52 INFO  time: ran 'gradle bloopInstall' in 1.75s
2021.12.01 15:19:52 INFO  Attempting to connect to the build server...
2021.12.01 15:19:52 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

Sorry, I work with Java for years, but the Scala + Bloop + Metals combination isn't that easy to get.

**Comment by tgodzik** [comment]
Maybe the java home is set incorrectly? Otherwise, you can just remove the added JSON to get back to where you started.

We are working actively to simplify it all.

**Comment by danielbasso** [comment]
Ok ,that is what I've tried so far:

1) F1 > "Java: Configure Java Runtime":
![image](https://user-images.githubusercontent.com/20959177/144448791-cd626ddf-bd12-43c9-a387-854767fc6a76.png)

`build.gradle`:

```
sourceCompatibility = 1.11
targetCompatibility = 1.11
```
Didn't work, same warning.

2) Settings > Metals: Java Home:

![image](https://user-images.githubusercontent.com/20959177/144449073-1fc3d936-b947-42cb-b574-0fc4b695ba90.png)

Didn't work, same warning.

3) When I run the project, there are two files inside `.bloop` : `bloop.settings.json` and `myprojectname.json`:

![image](https://user-images.githubusercontent.com/20959177/144450412-597fdcb9-17d6-4624-b016-b0fe7667f05e.png)

I tried to place this config

```json
{
  "javaHome": "/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk"
}
```

inside both of them, the project runs, but the warning persist.
  
  4) If I create a file called `bloop.json` insde `.bloop` with the `javaHome` config, the project won't start, as mentioned above.
  
My reasoning is that to change the Java debugger version is a Java config, not a Metals one, but I can't find it anywhere...

**Comment by tgodzik** [comment]
That's separate setting, Metals doesn't use Java Language Server currently.

Could you try to update to newest Metals snapshot? https://scalameta.org/metals/docs/ and changes server version settings.

The snapshot version should print the issues with connection to Bloop in detail.

**Comment by danielbasso** [comment]
> Could you try to update to newest Metals snapshot? https://scalameta.org/metals/docs/ and changes server version settings.
> 
> The snapshot version should print the issues with connection to Bloop in detail.

Hi. Did it:

![image](https://user-images.githubusercontent.com/20959177/144479640-d4d0e808-322c-467e-80e4-589eff37d766.png)

Reloaded the window and then:

![image](https://user-images.githubusercontent.com/20959177/144479784-abc7c24f-b657-4e1d-a3ff-38ca02101786.png)

And:

![image](https://user-images.githubusercontent.com/20959177/144479908-5b481ead-4c05-4b23-b004-2c1daad7cea7.png)

![image](https://user-images.githubusercontent.com/20959177/144479953-76353bd0-603e-4d99-b24d-afc4177f883f.png)

**Comment by tgodzik** [comment]
@danielbasso sorry I wasn't too specific. I meant that if you define javaHome in bloop.json and it fails to connect we should be able to see the reason for it under the newest snapshot.

**Comment by danielbasso** [comment]
> @danielbasso sorry I wasn't too specific. I meant that if you define javaHome in bloop.json and it fails to connect we should be able to see the reason for it under the newest snapshot.

Ok, so I created a file called `bloop.json` insde `.bloop` with the `javaHome` config. Checked the logs and the error was accusing missing filds in the json that were the same fields present on `myprojectname.json` (also inside `.bloop`). So I just copied the fields, run the project, it compiled successfully, and the warning persists.

**Comment by tgodzik** [comment]
> > @danielbasso sorry I wasn't too specific. I meant that if you define javaHome in bloop.json and it fails to connect we should be able to see the reason for it under the newest snapshot.
> 
> Ok, so I created a file called `bloop.json` insde `.bloop` with the `javaHome` config. Checked the logs and the error was accusing missing filds in the json that were the same fields present on `myprojectname.json` (also inside `.bloop`). So I just copied the fields, run the project, it compiled successfully, and the warning persists.

Where did you create the `bloop.json` file? For me it's `/home/tgodzik/.bloop/bloop.json`, did you create it in your workspace by any chance?

**Comment by danielbasso** [comment]
> Where did you create the `bloop.json` file? For me it's `/home/tgodzik/.bloop/bloop.json`, did you create it in your workspace by any chance?

Hi! I don't have bloop installed in my machine, but this isn't a requirement, as stated [here](https://scalacenter.github.io/bloop/docs/ides/metals#installation-requirements):

>If you don't have Bloop installed locally, Metals will automatically start a Bloop server for you.

I think if this is the case, the `.bloop` folder it uses is inside the project directory. So yeah, I created in my workspace.

But just to make sure, I've created `.bloop` inside my home, also created a `bloop.json` file with the javaHome setting, restarted vscode, but no dice.

**Comment by tgodzik** [comment]
Did you run `Metals: Restart build server` afterwards? 

> Hi! I don't have bloop installed in my machine, but this isn't a requirement, as stated here:

It's not require, but the only difference is that you don't have the Bloop cli, everything else is the same, so the server should pick up bloop.json in home.

>I think if this is the case, the .bloop folder it uses is inside the project directory. So yeah, I created in my workspace.

`.bloop` only contains config files for modules, so if you add another json it will think you added a new target, so this is not a right place to add anything manually.

**Comment by danielbasso** [comment]
> Did you run `Metals: Restart build server` afterwards?

That's it! The warning is gone. Thank you for your kindness and patience. And sorry, I'm a beginner in the bloop world.

So, solution recap to anyone out there:

1. Create .bloop folder inside your home, a bloop.json file inside it and write the javaHome config (as stated in the first reply);

2. Run `Metals: Restart build server` in Vscode (as stated in the last reply).

**Comment by tgodzik** [comment]
> That's it! The warning is gone. Thank you for your kindness and patience. And sorry, I'm a beginner in the bloop world.

No worries! This is way too complex, we should try and simplify it in the future. We already had a lot of discussions about, but having an easy way of switching JVMs is a complex topic :sweat_smile:
