### ISSUE TITLE
Merging with ENSIME?

### ISSUE THREAD

**Issue by schlichtanders** [scalameta/metals#336]
just curious about what the status is about bringing efforts together with http://ensime.github.io/ notably

It is great to have many awesome tools out there to work with Scala, however one awesome tool is for certain better then many so-so-awesome tools

In haskell finally effort is going together into one project https://github.com/haskell/haskell-ide-engine and I was very happy to see this.
I would wish the same for scala

**Comment by laughedelic** [comment]
Hi @schlichtanders. Before we get into any explanations or discussion, have you seen the thread in https://github.com/scalameta/metals/pull/295? Also take a look at the announcement in the [v0.1.0 release notes](https://github.com/scalameta/metals/releases/tag/v0.1.0). I think this may help to clarify the current situation.

**Comment by schlichtanders** [comment]
thanks for the two pointers! I see

Then happy experimenting :)

**Comment by olafurpg** [comment]
Thanks for reporting @schlichtanders ! As @laughedelic mentioned, this topic was already discussed in #295 :)
