### ISSUE TITLE
Metals inside VSCODE uses the wrong JDK on Fedora by default

### ISSUE THREAD

**Issue by silviobierman** [scalameta/metals#3373]
**Describe the bug**

When JAVA_ROOT is not set Metals does not select the system default JDK on Fedora (35). Because of a LibreOffice dependency Fedora needs an installed OpenJDK11 but apart from that I mostly use an OpenJDK17 which comes from a running version OpenJDK package. The JDK17 is set as the system default but Metals selects the JDK11 version anyway.

**To Reproduce**

Start VSCODE/Metals on a Fedora install with multiple JDKs. The output-tab shows which Java home Metals is using.

**Expected behavior**

Setting JAVA_ROOT is very cumbersome. The running version OpenJDK changes the name of the java directory inside /usr/lib/jvm/ with each OpenJDK update which means the JAVA_ROOT setting needs to be changed accordingly very frequently.

I think Metals should honor my system default JDK setting whichever version that is. If it is not compatible I prefer it bail out with an error over having it select any other JDK on its own.

**Installation:**

- Operating system: Fedora 35, OpenJDK11, OpenJDK17
- Editor: Visual Studio Code
- Metals version: v0.10.9

**Search terms**

VSCODE, JDK version

**Comment by dos65** [comment]
Thanks for reporting!

In case if `java` from `$PATH `points to jdk17 on your system it might be fixed if we merge [this](https://github.com/scalameta/metals-languageclient/pull/382).
Would it fit for you case?

**Comment by silviobierman** [comment]
Typically Linux will have /usr/bin in $PATH and a /usr/bin/java that is a symbolic link to /etc/alternatives/java that in turn is a symbolic link to the default java binary. To translate this to something akin to JAVA_HOME one would need to follow the symbolic links and translate the resulting path that points to the java executable into a path that points to its containing directory. That should work.

**Comment by dos65** [comment]
@silviobierman yep, I used the approach as you described. I asked that because I wasn't 100% sure that there is no difference between Fedora and debian-based distros in this mechanic.

So, as scalameta/metals-languageclient#382 was merged I think we can close this issue.
