### ISSUE TITLE
Discover Changes To A Type Hierarchy 

### ISSUE THREAD

**Issue by mikail-khan** [scalameta/metals#3386]
**Bug**

Metals fails to pick up changes to a type hierarchy. 

**To Reproduce**

```scala
sealed trait A
object A{
 final case class B() extends A
}

def foo(a: A) = a match // use the IDE's code completion feature here to figure out all the cases 
{
  case B() => ???
}

```
☝️ all ok - Now if I change the definition of A

```scala
sealed trait A
object A{
 final case class B() extends A
 final case class C() extends A
}
```

and do the code completion again, I get

```scala
def foo(a: A) = a match // use the IDE's code completion feature here to figure out all the cases 
{
  case B() => ???
}
```

i.e. the IDE fails to pick up that C has been added.

**Expected behavior**
Code completion feature should pick up the changes to the definition.

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.9

**Comment by ckipp01** [comment]
Just confirming that I can reproduce this and as mentioned on Discord restarting the PC does fix the issue.  Thanks for reporting @mikail-khan!

**Comment by tgodzik** [comment]
Just checked and this seems fixed.
