### ISSUE TITLE
auto-imports can break scala-cli scripts 

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3399]
**Describe the bug**

When using https://scala-cli.virtuslab.org/ if you have some code like

```
// using Scala 3.1.0
```

And then you trigger an auto-import, it will insert the import above the directive since it thinks it's just a comment, and then can lead to broken scripts.

**To Reproduce**

1. Copy the above
2. Auto import something
3. You now changed your scala version

**Expected behavior**

I'd expect for Metals to be able to know that `// using Scala 3.1.0` is a directive and not import above it.

**Comment by dos65** [comment]
I think respecting comment at the beginning of file and placing first import after it should works well.
There is also a rare case when file starts from the long license-comment
