### ISSUE TITLE
No code completion / code suggestions

### ISSUE THREAD

**Issue by silviobierman** [scalameta/metals#3419]
The Scala editor does not provide any suggestions when typing the . character. Nothing happens and when I press CTRL+SPACE I see a small box that says "No suggestions.". Neither Scala methods from my own sources nor methods from predefined Scala/Java classes are shown.

- Operating system: Linux (Fedora 35)
- Editor: Visual Studio Code
- Metals version: v0.10.9
- JDK: OpenJDK 17 (I tried switching to OpenJDK 11 but that does not change a thing)

This is the content of my output Window after startup:

Java home: /usr/lib/jvm/java-17-openjdk-17.0.1.0.12-2.rolling.fc35.x86_64
Metals version: 0.10.9
2021.12.30 16:53:12 INFO  logging to file /home/silvio/java_root/projects/scripture/.metals/metals.log
2021.12.30 16:53:12 INFO  Started: Metals version 0.10.9 in workspace '/home/silvio/java_root/projects/scripture' for client Visual Studio Code 1.63.2.
2021.12.30 16:53:14 INFO  time: initialize in 1.13s
Initializing Scala Debugger
2021.12.30 16:53:14 INFO  Flyway Community Edition 8.0.2 by Redgate
2021.12.30 16:53:14 INFO  Database: jdbc:h2:file:/home/silvio/java_root/projects/scripture/.metals/metals (H2 1.4)
2021.12.30 16:53:14 INFO  Successfully validated 3 migrations (execution time 00:00.018s)
2021.12.30 16:53:14 INFO  Current version of schema "PUBLIC": 3
2021.12.30 16:53:14 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2021.12.30 16:53:14 INFO  Attempting to connect to the build server...
2021.12.30 16:53:14 INFO  skipping build import with status 'Installed'
2021.12.30 16:53:16 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/silvio/.cache/metals/bsp.trace.json
2021.12.30 16:53:16 INFO  Attempting to connect to the build server...
2021.12.30 16:53:17 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/silvio/.cache/metals/bsp.trace.json
2021.12.30 16:53:17 INFO  time: Connected to build server in 2.78s
2021.12.30 16:53:17 INFO  Connected to Build server: Bloop v1.4.11
2021.12.30 16:53:24 WARN  Could not find java sources in None. Java symbols will not be available.
2021.12.30 16:53:24 INFO  time: indexed workspace in 7.27s
2021.12.30 16:53:25 INFO  no build target: using presentation compiler with only scala-library: 2.12.15

**Comment by silviobierman** [comment]
I tried that. It shows nothing but green checks...

![Screenshot from 2021-12-30 17-03-58](https://user-images.githubusercontent.com/734637/147768275-ef95debf-1017-4d06-9f11-98a5c75c84b0.png)

**Comment by tgodzik** [comment]
Could you check if there is anything popping up in `.metals/metals.log` Some exceptions don't get forwarded correctly to the output tab.

**Comment by silviobierman** [comment]
Wait what? I checked the settings for "suggest" and under "Metals" found an option "Edit in settings.json". That takes me to a file with that name that contains a bunch of:

    "editor.suggest.showClasses": false,
    "editor.suggest.showConstants": false,
    "editor.suggest.showCustomcolors": false,
    "editor.suggest.showConstructors": false,
    "editor.suggest.showEnumMembers": false,
    "editor.suggest.showEnums": false,
    "editor.suggest.showEvents": false,
    "editor.suggest.showFiles": false,
    "editor.suggest.showColors": false,
    "editor.suggest.showDeprecated": false,
    "editor.suggest.showFields": false,
    "editor.suggest.showFolders": false,
    "editor.suggest.showFunctions": false,
    "editor.suggest.showIcons": false,
    "editor.suggest.showInterfaces": false,
    "editor.suggest.showIssues": false,
    "editor.suggest.showKeywords": false,
    "editor.suggest.showMethods": false,
    "editor.suggest.showModules": false,
    "editor.suggest.showOperators": false,
    "editor.suggest.showProperties": false,
    "editor.suggest.showReferences": false,
    "editor.suggest.showSnippets": false,
    "editor.suggest.showStructs": false,
    "editor.suggest.showTypeParameters": false,
    "editor.suggest.showUnits": false,
    "editor.suggest.showUsers": false,
    "editor.suggest.showValues": false,
    "editor.suggest.showVariables": false,
    "editor.suggest.showWords": false,
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "editor.wordBasedSuggestions": false,
    "editor.suggestOnTriggerCharacters": false,

I have no idea where that comes from! But changing "methods" to true does change the behavior. So I am on to something here. Do I need to change this all to true? Can I somehow revert all my settings to default or something?

**Comment by tgodzik** [comment]
That's super weird, looks like global VS Code settings, they should not be set by default. You could remove them to make them fo to default.

**Comment by silviobierman** [comment]
Thank you. I will delete them all and see what happens.

**Comment by silviobierman** [comment]
Yes! That restores all the suggestion behavior I used to have. Thank you very much!

**Comment by tgodzik** [comment]
It's super weird it happened, maybe it was contributed by someone in `.vscode` directory?
