### ISSUE TITLE
Odd completion given back

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3421]
**Describe the bug**

I'm only able to reproduce this while using `scala-cli` and Scala 3. Given the following piece of code:

```scala
// using scala 3.1.0

def thing() = ??? // same behavior happens if this is implemented

@main def run() = {

  val thing = ???

}
```

When you try to implement the `val thing` and start typing `thi` you'll see this as a completion option given:

```json
  {
    "label": "thing: \u003cerror Not found: thi\u003e",
    "kind": 5,
    "detail": "\u003cerror Not found: thi\u003e",
    "sortText": "00000",
    "filterText": "thing",
    "textEdit": {
      "range": {
        "start": {
          "line": 6,
          "character": 14
        },
        "end": {
          "line": 6,
          "character": 17
        }
      },
      "newText": "thing"
    },
    "additionalTextEdits": []
  }
```

**To Reproduce**

1. Create a scala-cli script like above
2. Try implementing the `val thing` with `thi`
3. See the funky `thing: <error Not found: thi>` completion label.

Note t
**Expected behavior**

I wouldn't expect `thing` to have this label here.

**Screenshots**

<img width="472" alt="Screenshot 2021-12-30 at 21 09 42" src="https://user-images.githubusercontent.com/13974112/147785314-e74dc059-3ab6-473e-a378-f810204a1bdb.png">

**Installation:**

- Operating system: macOS
- Editor: nvim-metals
- Metals version: 0.10.9+249-88f3b27d-SNAPSHOT

**Search terms**

**Comment by ckipp01** [comment]
I'm also seeing this in other situations for example I just noticed this:
<img width="719" alt="Screenshot 2021-12-31 at 13 07 02" src="https://user-images.githubusercontent.com/13974112/147822539-199f32a6-02e2-40d7-b8e9-cb76ee84af99.png">

I made a spelling mistake here and tried to match on `deps` instead of `dep`, but for some reason I'm seeing that error message in my completion item.

**Comment by tgodzik** [comment]
We can probably check if the type is an error, let me check that.
