### ISSUE TITLE
Hover and insert type annotation shows error

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3422]
**Describe the bug**

Given the following piece of code when in Scala 3:

```scala
final case class Dependency(
    org: String,
    name: Option[String],
    version: Option[String]
)

object Dependency {
  def apply(org: String) = Dependency(org, None, None)
  def apply(org: String, name: String) = Dependency(org, Some(name), None)
}
```

You'll get diagnostics on the apply that:

```
Overloaded or recursive method apply needs return type
```
Then when you try to use the insert type annotation code action on `apply` you end up with:

```scala
  def apply(org: String): <error unspecified error> = Dependency(org, None, None)
```
You can also see the `<error unspecified error>` in the hover on `apply` as well.

**Expected behavior**

This error shouldn't be shown to the user in the hover, and it for sure shouldn't be inserted as the type

**Installation:**

- Operating system: macOS
- Editor: nvim-metals
- Metals version: 0.10.9+249-88f3b27d-SNAPSHOT
- Scala version: 3.1.0

**Comment by tgodzik** [comment]
Thanks Chris for noticing these issues, every time I've seen it I was busy with something else and forgot to file it.
