### ISSUE TITLE
Goto definition (references) returning end marker

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3476]
### Describe the bug

When I want to see the usage of a class I often just trigger a goto definition on the class name or do a find references on it. I noticed that in Scala 3 this returns the end marker of that class as well as the usage site.

### Reproduction steps

1. Ope the Scala 3 `CompletionProvider.scala` in Metals.
2. Do a goto defintion on `CompletionProvider`
3. See the following two results returned

```
[Trace - 00:37:49 PM] Sending response 'textDocument/definition - (1194)'. Processing request took 9ms
Result: [
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/scalameta-org/metals/mtags/src/main/scala-3/scala/meta/internal/pc/CompletionProvider.scala",
    "range": {
      "start": {
        "line": 336,
        "character": 4
      },
      "end": {
        "line": 336,
        "character": 22
      }
    }
  },
  {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/scalameta-org/metals/mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala",
    "range": {
      "start": {
        "line": 160,
        "character": 12
      },
      "end": {
        "line": 160,
        "character": 30
      }
    }
  }
]
```

### Expected behavior

In this situation I really only want the one usage in `ScalaPresentationCompiler`, but instead now I get a window showing me both options. I'd imagine that the end site isn't that useful, but I could maybe be convinced it is. Either way, is this the expected behavior? I wasn't expecting to see this.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.10.9+294-f0c357ed-SNAPSHOT

**Comment by tgodzik** [comment]
This is kind of expected behaviour since the end marker has a reference to that symbol. This also allows the rename to work correctly in that case. We would need to special case it otherwise and filter it out (which might not be simple.)

**Comment by ckipp01** [comment]
> This is kind of expected behaviour since the end marker has a reference to that symbol. This also allows the rename to work correctly in that case. We would need to special case it otherwise and filter it out (which might not be simple.)

Ahh I didn't think about the rename case. Alright, I'll close.
