### ISSUE TITLE
Metals won't run/debug main after X successful runs

### ISSUE THREAD

**Issue by Arthurm1** [scalameta/metals#3477]
### Describe the bug

This is intermittent, but after successfully running and stopping a java main class a few times, the app will refuse to run again and I'll get log messages...
`ERROR java.nio.file.FileSystemAlreadyExistsException`

Full log...
```
2022.01.06 14:13:20 INFO  tracing is enabled: /root/.cache/metals/dap-server.trace.json
2022.01.06 14:13:20 INFO  tracing is enabled: /root/.cache/metals/dap-client.trace.json
2022.01.06 14:13:20 INFO  Starting debug proxy for [XXX]
2022.01.06 14:13:23 ERROR java.nio.file.FileSystemAlreadyExistsException
2022.01.06 14:13:23 INFO  Closing debug server tcp://0.0.0.0:39565
```

There's no stack trace.  The error is appearing in the bsp trace so I guess it's from Bloop?

I have to restart Bloop (not Metals) to be able to run the app again.

I guess this has something to do with `FileSystems.newFileSystem` being called on an already open `jar`

I'm running under Windows + WSL2

Can I enable more logging somehow to get the full trace?

### Expected behavior

I'd expect the app to run as many times as I want

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

0.10.9+294-f0c357ed-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for finding this! I think it may have something to do with https://github.com/scalacenter/scala-debug-adapter

@adpi2 it's that error again :scream: Any idea where it might be coming from exactly?

**Comment by adpi2** [comment]
Yeah it probably comes from the scala-debug-adapter, or potentially from Bloop too. On the debug-adapter side, it seems all file-systems are correctly closed though.

Also it could be a problem of concurrency: we try to open a file-system while it is being used by another thread. However it would not be so deterministic: here it seems it stops working completely after some time.

@Arthurm1 can you give us the version of Bloop you are using. It is written in Metals Doctor section.

**Comment by Arthurm1** [comment]
Build server currently being used is Bloop v1.4.11-30-75fb3441

**Comment by vishalovercome** [comment]
I've faced this issue several times and while restarting usually works, eventually bloop and metals go into a restart loop after which VSCode will kill metals. Restarting VSCode makes this problem go away.

In the past I created an issue about worksheets that stop working just like that. Maybe these are related 🤷🏽

**Comment by tgodzik** [comment]
Trying to reproduce it, but I run a Java mian over 20 times, tried with breakpoint etc but nothing works. We might try and print the stack trace in that situation.

@Arthurm1 what is the Java version you are using? Would you be able create a reproduction that this eventually happens on?

**Comment by Arthurm1** [comment]
I think I've found the reason...

I've got a dependency on javaFX.
`"org.openjfx:javafx-controls:17.0.1:win"`
`"org.openjfx:javafx-controls:17.0.1:linux"`

 This brings in 3 jars...
`javafx-controls-17.0.1-linux.jar`
`javafx-controls-17.0.1.jar`
`javafx-controls-17.0.1-win.jar`

These are all in `entries` which is accessed in parallel [here](https://github.com/scalacenter/scala-debug-adapter/blob/05c451e42ff325334e7c20c0d69871a0767ccba5/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookUpProvider.scala#L64)

This stack trace shows this leads to all the source jars being opened in parallel..,
```
ch.epfl.scala.debugadapter.internal.IO$.withinJarFile(IO.scala:31)
ch.epfl.scala.debugadapter.internal.ClassEntryLookUp$.getAllSourceFiles(ClassEntryLookUp.scala:225)
ch.epfl.scala.debugadapter.internal.ClassEntryLookUp$.$anonfun$apply$1(ClassEntryLookUp.scala:137)
scala.collection.immutable.List.flatMap(List.scala:366)
ch.epfl.scala.debugadapter.internal.ClassEntryLookUp$.apply(ClassEntryLookUp.scala:137)
ch.epfl.scala.debugadapter.internal.SourceLookUpProvider$.$anonfun$apply$2(SourceLookUpProvider.scala:73)
```

The problem is that all 3 of these jars point to the same source jar: `javafx-controls-17.0.1-sources.jar` and it's that jar that is now being opened simultaneously in this parallel loop.  I imagine this is fairly unusual but it is valid.

So I guess there should be some kind of distinct run on the source entries first?

**Comment by adpi2** [comment]
@Arthurm1 That's a good catch! Thanks a lot for investigating it.

> So I guess there should be some kind of distinct run on the source entries first?

Right, we need to read all `SourceFile` from the list of distinct source entries and then we can build the `ClassEntryLookup`.

May I propose you to open a pull request to https://github.com/scalacenter/scala-debug-adapter?
