### ISSUE TITLE
SymbolPrefixes are messing up other util packages

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3478]
### Describe the bug

When you have code that is in another util package and there is a conflicting import, the symbol prefix for `java/util` screws up your import.

You can reproduce this with the following snippet:
```scala
// using scala 3.1.0
// using lib org.scala-lang::scala3-compiler:3.1.0

import dotty.tools.dotc.interfaces.SourceFile

@main def Main: Unit =
// <-- try to complete `SourceFile` here from the util package
```

You'll end up with the following:

```scala
// using scala 3.1.0
// using lib org.scala-lang::scala3-compiler:3.1.0

import dotty.tools.dotc.interfaces.SourceFile
import dotty.tools.dotc.{util => ju}

@main def Main: Unit =
  ju.SourceFile
```

### Expected behavior

I'd expect the fully qualified name just be inserted in place or something like `util.SourceFile`

```scala
// using scala 3.1.0
// using lib org.scala-lang::scala3-compiler:3.1.0

import dotty.tools.dotc.interfaces.SourceFile
import dotty.tools.dotc.{util => ju}

@main def Main: Unit =
  dotty.tools.dotc.util.SourceFile
```

### Version of Metals

0.10.9+295-ad8c7778-SNAPSHOT

### Extra context or search terms

My guess is the issue is right here:

https://github.com/scalameta/metals/blob/ad8c7778e75a48267d3723efe36ef0eccf4c6a6b/mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala#L61-L66

I think in this case `util` is the simple name and the keys here are simple names so it incorrectly thinks the `util -> ju` entry matching when it shouldn't.

**Comment by dos65** [comment]
@ckipp01 Thx for the investigation! Looks like a source of issue
