### ISSUE TITLE
Typing in VSCode always executes command to refresh test-exporer

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#3501]
### Describe the bug

Reproduction step:
- Enable: `Files: Auto Save: afterDelay`
- Start watching traces: `tail -f ~/.cache/metals/lsp.trace.json`
- Open any file and start typing with a delay (one char per sec)
- Notice that CPU usage gets higher
- Notice  `window/executeCommand` with the following result constantly appears:
  ```
  [Trace - 00:45:09 PM] Sending response 'workspace/executeCommand - (268)'. Processing request took 1000ms
  Result: [
    {
    "targetName": "unit-test",
    "targetUri": "file:/home/dos65/projects/metals/metals/tests/unit/?id\u003dunit-test",
    "discovered": [
      {
        "prefix": "tests",
        "children": [
          {
            "fullyQualifiedName": "tests.AnalyzeStacktraceLspSuite",
            "className": "AnalyzeStacktraceLspSuite",
            "location": {
              "uri": "file:///home/dos65/projects/metals/metals/tests/unit/src/test/scala/tests/AnalyzeStacktraceLspSuite.scala",
              "range": {
                "start": {
                  "line": 2,
                  "character": 6
                },
                "end": {
                  "line": 2,
                  "character": 31
                }
              }
            },
            "kind": "suite"
          },

  ```

### Expected behavior

It seems that at least this command shouldn't be executed if testing tab isn't opened but I think there might be some additional optimizations.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.0

**Comment by kpodsiad** [comment]
Is this happening with `Code Lenses` too? Refreshing tests via Text Explorer shouldn't be much more expensive since they both share the same mechanism - tests are refreshed after every compilation.

**Comment by dos65** [comment]
@kpodsiad nope. I set explorer to `Code Lenses` and cpu spikes disappeared. I can look at it more detailed at it a bit later.

**Comment by tgodzik** [comment]
Do you have autosave on ? I can't seem to reproduce it :thinking:

**Comment by dos65** [comment]
@tgodzik 
> Do you have autosave on ?

Yes

**Comment by vishalovercome** [comment]
Probably this is happening under both Code Lens as well as Test Explorer (explained in the thread above)
