### ISSUE TITLE
mac | hello-world | unable to run code

### ISSUE THREAD

**Issue by LingarajVB** [scalameta/metals#3511]
Hello,
I am also facing the same issue, I have java installed on mac and i was trying hello-world project but its not working.

<img width="481" alt="Screenshot 2022-01-14 at 7 57 26 PM" src="https://user-images.githubusercontent.com/39855043/149532336-9649df61-c06d-44f4-b57c-b1161e055f93.png">

getting the following error:

<img width="941" alt="Screenshot 2022-01-14 at 8 00 33 PM" src="https://user-images.githubusercontent.com/39855043/149532274-f888c04c-caa9-4e93-ab1c-d5f72d876d02.png">

PS: i did not install bloop on mac since metals has the utility with it and since its forcing me to update mac while installing which i am hesitant to do it.

Please let me know if this has been worked around by anybody else?
Thank you so much for any help in advance 👍 

_Originally posted by @LingarajVB in https://github.com/scalameta/metals/issues/3075#issuecomment-1013174001_

**Comment by kpodsiad** [comment]
Hey @LingarajVB. It seems that Bloop is being started with a JRE instead of the JDK.
Could you paste the output from running: `bloop about` and `echo &JAVA_HOME`?

**Comment by LingarajVB** [comment]
@kpodsiad 
Thanks for letting me know but as i mentioned i did not install bloop externally because it is asking me to force update my mac.

**Comment by LingarajVB** [comment]
Okay!!!!
So here is what I did, I made sure that all of the below java versions are pointing to same java home (not the jdk but java home, for example : /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home) 


metals (settings > metals settings > metals java home) === this fixed my actual issue
bloop (bloop.settings.json)
hello-world.json (platform.config.home).  === this fixed below issue
hello-world-test.json (platform.config.home)  === this fixed below issue

<img width="936" alt="Screenshot 2022-01-14 at 8 47 37 PM" src="https://user-images.githubusercontent.com/39855043/149540525-3428dd6c-ed41-4c25-8084-a3fb87dbe408.png">


@kpodsiad Thank you for helping me stick around with JAVA_HOME fixing 👍

**Comment by LingarajVB** [comment]
> Metals are able to start bloop and then you should be able to run `bloop about` in your terminal.

No, This did not work.
And, about the previous issue, i was surprised that when i removed java_home that i set in metals settings (letting it use the default) my run did not work.
does it mean i should make sure bloop and metals are using same java jre or java home?

**Comment by tgodzik** [comment]
> > Metals are able to start bloop and then you should be able to run `bloop about` in your terminal.
> 
> No, This did not work. And, about the previous issue, i was surprised that when i removed java_home that i set in metals settings (letting it use the default) my run did not work. does it mean i should make sure bloop and metals are using same java jre or java home?

They don't need to use the same JVM, but Bloop does require a JDK.

> Metals are able to start bloop and then you should be able to run bloop about in your terminal.

`bloop about` will only work if you install the CLI manually.

> metals (settings > metals settings > metals java home) === this fixed my actual issue
> bloop (bloop.settings.json)
> hello-world.json (platform.config.home). === this fixed below issue
> hello-world-test.json (platform.config.home) === this fixed below issue

When metals run import they will do so using the specified Java version and that version will later be used for running the application or tests. You should not set the `hello-world.json` manually as this will be overriden the next time you do an import.

**Comment by kpodsiad** [comment]
Happy to hear that everything worked ;) I was writing an answer but I see that @tgodzik was quicker :D

I can recommend [sdk man](https://sdkman.io/) for managing among others JDK's, it updates everything for you and allows you to change jdk's easily.

Most of the time you don't have to worry about mismatch between debugger and debugge version, it only affects positions in the Java standard library.

**Comment by LingarajVB** [comment]
@kpodsiad 
Thank you for letting me know about sdkman. i will check it out.

@tgodzik 
Thanks for coming back on this so quick.
If you think my java is correctly setup (as in the first picture, in the first comment of this thread),
i dont know what else is wrong, just now i tested, when i removed java_home that i set up in Metals settings, it started failing.
Yah, i removed bloop java_home that i had set in bloop json, it seems to be working fine but not sure why is it not working when i removed java_home from metals settings. please let me know if you have anything to say ?

**Comment by arturopala** [comment]
I'm successfully using [jenv](https://www.jenv.be/) to manage JVMs on my mac

**Comment by LingarajVB** [comment]
> I'm successfully using [jenv](https://www.jenv.be/) to manage JVMs on my mac
