### ISSUE TITLE
The performance is very slow when used for a long time & CPU usage higher(>80%)

### ISSUE THREAD

**Issue by yaoqiang-se** [scalameta/metals#3530]
### Describe the bug

I am VS Code + Metals, and upgrade Metals to latest version(v0.11.0), there never feel slowly before

I think maybe relations with  #3379 

step:
1) open vscode at morning, and coding well
2) sleep PC at lunch, ~ 2h later
3) go back work, update code and save
4) output show `compiling root (1 scala source)`, then very very slowly, and CPU usage >90%
5) restart vscode, it just works

the details logs:
Jan 17, 2022 11:11:45 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2005
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path DeviceModule.scala with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\modules\DeviceModule.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\modules\DeviceModule.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c updating C:\Users\xxx\Workspace\Code\Lisa\app\modules\DeviceModule.scala in TypedPath(path: C:\Users\xxx\Workspace\Code\Lisa\app, exists: true, isFile: false, isDirectory: true, isSymbolicLink: false)
com.swoval.files.FileCacheDirectoryTree$4@356b1447 running callback com.swoval.files.FileCacheDirectoryTree$6@79b840a0
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path DeviceModule.scala with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\modules\DeviceModule.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\modules\DeviceModule.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c updating C:\Users\xxx\Workspace\Code\Lisa\app\modules\DeviceModule.scala in TypedPath(path: C:\Users\xxx\Workspace\Code\Lisa\app, exists: true, isFile: false, isDirectory: true, isSymbolicLink: false)
com.swoval.files.FileCacheDirectoryTree$4@7bdd60c2 running callback com.swoval.files.FileCacheDirectoryTree$6@488b767c
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path bloop-internal-classes with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\.bloop\root\bloop-internal-classes, Modify)
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path bloop-internal-classes with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\.bloop\root\bloop-internal-classes, Modify)
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path bloop-internal-classes with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\.bloop\root\bloop-internal-classes, Modify)
Jan 17, 2022 1:42:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2105
Jan 17, 2022 2:17:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2264
2022.01.17 14:17:36 INFO  time: code lens generation in 10s[0m
Jan 17, 2022 2:17:41 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2273
Jan 17, 2022 2:17:46 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2279
Jan 17, 2022 2:17:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2285
2022.01.17 14:17:52 INFO  time: code lens generation in 10s[0m
Jan 17, 2022 2:17:54 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2287
Jan 17, 2022 2:18:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2289
Jan 17, 2022 2:18:04 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2293
Jan 17, 2022 2:18:04 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2281
Jan 17, 2022 2:18:08 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2295
2022.01.17 14:18:15 INFO  time: code lens generation in 11s[0m
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path DeviceService.scala with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c updating C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala in TypedPath(path: C:\Users\xxx\Workspace\Code\Lisa\app, exists: true, isFile: false, isDirectory: true, isSymbolicLink: false)
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path DeviceService.scala with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree$4@25af8a06 running callback com.swoval.files.FileCacheDirectoryTree$6@1ea97353
com.swoval.files.FileCacheDirectoryTree@2194761c received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c updating C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala in TypedPath(path: C:\Users\xxx\Workspace\Code\Lisa\app, exists: true, isFile: false, isDirectory: true, isSymbolicLink: false)
com.swoval.files.FileCacheDirectoryTree$4@e62cb34 running callback com.swoval.files.FileCacheDirectoryTree$6@1dc97412
Jan 17, 2022 2:18:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2301
Jan 17, 2022 2:18:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2310
Jan 17, 2022 2:18:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2312
Jan 17, 2022 2:18:28 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2307
2022.01.17 14:18:31 INFO  time: code lens generation in 22s[0m
2022.01.17 14:18:40 INFO  time: code lens generation in 24s[0m
Jan 17, 2022 2:18:41 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2318
Jan 17, 2022 2:18:41 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2328
2022.01.17 14:18:43 INFO  time: code lens generation in 26s[0m
Jan 17, 2022 2:18:49 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2324
2022.01.17 14:18:55 INFO  time: code lens generation in 27s[0m
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path DeviceService.scala with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c updating C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala in TypedPath(path: C:\Users\xxx\Workspace\Code\Lisa\app, exists: true, isFile: false, isDirectory: true, isSymbolicLink: false)
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path DeviceService.scala with kind ENTRY_MODIFY
com.swoval.files.FileCacheDirectoryTree$4@446f3217 running callback com.swoval.files.FileCacheDirectoryTree$6@1189e222
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c updating C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala in TypedPath(path: C:\Users\xxx\Workspace\Code\Lisa\app, exists: true, isFile: false, isDirectory: true, isSymbolicLink: false)
com.swoval.files.FileCacheDirectoryTree$4@92aa04c running callback com.swoval.files.FileCacheDirectoryTree$6@5f152c9f
com.swoval.files.NioPathWatcherService@66b3dbcc received event for path DeviceService.scala with kind ENTRY_MODIFY
com.swoval.files.NioPathWatcher@1ab43a52 received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c received event Event(C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala, Modify)
com.swoval.files.FileCacheDirectoryTree@2194761c updating C:\Users\xxx\Workspace\Code\Lisa\app\services\device\DeviceService.scala in TypedPath(path: C:\Users\xxx\Workspace\Code\Lisa\app, exists: true, isFile: false, isDirectory: true, isSymbolicLink: false)
com.swoval.files.FileCacheDirectoryTree$4@62d752e0 running callback com.swoval.files.FileCacheDirectoryTree$6@3c91346a
Jan 17, 2022 2:19:11 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2331
2022.01.17 14:19:11 INFO  time: code lens generation in 30s[0m
2022.01.17 14:19:18 INFO  time: code lens generation in 29s[0m
Jan 17, 2022 2:19:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2337
Jan 17, 2022 2:19:24 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2343
Jan 17, 2022 2:19:25 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2323
2022.01.17 14:19:27 INFO  time: code lens generation in 16s[0m
Jan 17, 2022 2:19:32 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2346
Jan 17, 2022 2:19:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2352
2022.01.17 14:19:48 INFO  time: code lens generation in 23s[0m
2022.01.17 14:19:58 INFO  time: code lens generation in 26s[0m
2022.01.17 14:20:02 INFO  time: code lens generation in 21s[0m
Jan 17, 2022 2:20:08 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2363
Jan 17, 2022 2:20:08 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2360
Jan 17, 2022 2:20:14 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2367
2022.01.17 14:20:23 INFO  time: code lens generation in 14s[0m
2022.01.17 14:20:55 INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\Users\xxx\Workspace\Code\Lisa\.metals\lsp.trace.json or c:\Users\xxx\Workspace\Code\Lisa\null\scalameta\metals\cache\lsp.trace.json[0m
2022.01.17 14:20:56 INFO  logging to file C:\Users\xxx\Workspace\Code\Lisa\.metals\metals.log[0m
2022.01.17 14:20:56 INFO  Started: Metals version 0.11.0 in workspace 'C:\Users\xxx\Workspace\Code\Lisa' for client Visual Studio Code 1.63.2.[0m
2022.01.17 14:20:56 INFO  Parse release: 11.0.2[0m
2022.01.17 14:21:00 INFO  time: initialize in 4.01s[0m
2022.01.17 14:21:05 INFO  Attempting to connect to the build server...[0m
2022.01.17 14:21:05 INFO  skipping build import with status 'Installed'[0m
2022.01.17 14:21:05 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\xxx\Workspace\Code\Lisa\.metals\bsp.trace.json or c:\Users\xxx\Workspace\Code\Lisa\null\scalameta\metals\cache\bsp.trace.json[0m
2022.01.17 14:21:05 INFO  Attempting to connect to the build server...[0m
2022.01.17 14:21:05 INFO  Attempting to connect to the build server...[0m
2022.01.17 14:21:05 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\xxx\Workspace\Code\Lisa\project\project\.metals\bsp.trace.json or c:\Users\xxx\Workspace\Code\Lisa\null\scalameta\metals\cache\bsp.trace.json[0m
2022.01.17 14:21:05 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\xxx\Workspace\Code\Lisa\project\.metals\bsp.trace.json or c:\Users\xxx\Workspace\Code\Lisa\null\scalameta\metals\cache\bsp.trace.json[0m
2022.01.17 14:21:05 INFO  time: Connected to build server in 0.52s[0m
2022.01.17 14:21:05 INFO  Connected to Build server: Bloop v1.4.12[0m
2022.01.17 14:21:05 INFO  time: Imported build in 0.39s[0m
com.swoval.files.NioPathWatcherService@7534f6fc registering C:\Users\xxx\Workspace\Code\Lisa\project
com.swoval.files.NioPathWatcherService@7534f6fc creating new watch key for C:\Users\xxx\Workspace\Code\Lisa\project
com.swoval.files.NioPathWatcherService@7534f6fc registration for C:\Users\xxx\Workspace\Code\Lisa\project succeeded
com.swoval.files.NioPathWatcher@3d9c8693 registered C:\Users\xxx\Workspace\Code\Lisa\project\src\main\scala-2 with max depth 2147483647
com.swoval.files.FileCacheDirectoryTree@38a1323a registered C:\Users\xxx\Workspace\Code\Lisa\project\src\main\scala-2 with max depth 2147483647
com.swoval.files.FileTreeRepositoryImpl@446b2c22 registered C:\Users\xxx\Workspace\Code\Lisa\project\src\main\scala-2 with max depth 2147483647
com.swoval.files.NioPathWatcherService@7534f6fc registering C:\Users\xxx\Workspace\Code\Lisa\project\project
com.swoval.files.NioPathWatcherService@7534f6fc creating new watch key for C:\Users\xxx\Workspace\Code\Lisa\project\project
com.swoval.files.NioPathWatcherService@7534f6fc registration for C:\Users\xxx\Workspace\Code\Lisa\project\project succeeded
com.swoval.files.NioPathWatcher@3d9c8693 registered C:\Users\xxx\Workspace\Code\Lisa\project\project\src\main\scala with max depth 2147483647

### Expected behavior

work well

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.0

**Comment by tgodzik** [comment]
This should be fixed in the current version, let me know if that is not the case still.
