### ISSUE TITLE
JavaInteractiveSemanticDb - jdk version inferring issue

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#3536]
### Describe the bug

It was reported [here](https://github.com/scalameta/metals/issues/3500#issuecomment-1013722332).

Currently, we detect jdk version by reading `$JVM_HOME/release` and `version` field value from it.
We expected that it should works for Jdk11+ version but it seems there is no guarantee that `release` file will be presented in jdk-distributive.

As a solution if there is no `release` file we can try to obtain it from the running `java --version`.

### Version of Metals

v0.11.1

**Comment by tgodzik** [comment]
Thanks for raising this! We already do the same thing in Bloop, so this shouldn't be hard to fix.

**Comment by kpodsiad** [comment]
Is this related?
I have metals.javaHome pinpointed to the `/Users/kpodsiadlo/.sdkman/candidates/java/current` which resolves to the
```shell
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```
but when I try to enter some Java class, for example, `Charset.java` (`InteractiveSemanticdbs` -> `Charset`) I get

```shell
2022.03.30 11:44:25 WARN  Running javac-semanticdb failed for jar:file:///Users/kpodsiadlo/.sdkman/candidates/java/8.0.322-zulu/src.zip!/java/nio/charset/Charset.java. Output:
error: module not found: java
1 error
```

**Comment by dos65** [comment]
@kpodsiad looks like a different one. In your case you have jdk `17.0.2` while sources are `8.0.322`. Could you turn it into another issue?

Do you have anything special in your setup? Or it's enough just to setup zulu-17.0.2 using sdkman to reproduce that?

**Comment by moberer** [comment]
Regarding the relevancy of this issue:
On openSUSE the Java directory does not have a release file.
Therefore one can not currently use Metals on openSUSE.

**Comment by moberer** [comment]
> We could fallback to jsut using `java -version` and caching that result

Is there any particular reason to not just use this approach in all cases?
Because I see no reason to rely on any other, potentially wrong sources than the actual java binary.

**Comment by tgodzik** [comment]
The primary reason is that it's usually faster to just read a file instead of running a separate process.

**Comment by moberer** [comment]
Excuse my possible lacking understanding, but isn't this a one-time job, to do at startup?

**Comment by tgodzik** [comment]
> Excuse my possible lacking understanding, but isn't this a one-time job, to do at startup?

Yeah, that might have been premature optimization on out part :sweat_smile:

**Comment by zmerr** [comment]
Hey, instead of going the `ShellRunner` path, do you think it would have been a better idea to simply do System.getProperty("java.version”) according to [this](https://stackoverflow.com/questions/5103121/how-to-find-the-jvm-version-from-a-program)

**Comment by tgodzik** [comment]
> Hey, instead of going the `ShellRunner` path, do you think it would have been a better idea to simply do `System.getProperty("java.version”)` according to [this](https://stackoverflow.com/questions/5103121/how-to-find-the-jvm-version-from-a-program)

We already discussed it with @zmerr but I think it's important to sum up that this unfortunately will not work because the Metals Java home might be different than that of the project.

**Comment by tanishiking** [comment]
After Metals drop the java 8 support in the future, [Runtime.version()](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Runtime.html#version()) will be a handy way to obtain the runtime version I guess.

(for `<=8`, we can use something like `Runtime.getRuntime.getClass.getPackage.getImplementationVersion()` but for `>=9` it starts returning `null`, it may no longer read the version from manifest file 🤔 )

**Comment by zmerr** [comment]
@tanishiking thank you so much  for the input. So does this give us the Metals’ jdk version or that of the java installed on user’s machine. It seems that the goal is to capture the latter.

**Comment by tanishiking** [comment]
I think the goal of this issue is to capture the JDK version that runs Metals (the former one), and I guess Runtime provides us with a former one (I haven't confirmed though).

**Comment by tgodzik** [comment]
> I think the goal of this issue is to capture the JDK version that runs Metals (the former one),

We actually want the JDK used for the project, so when we switch to Metals built-in JDK it will be different that the one used for project.

**Comment by tanishiking** [comment]
> We actually want the JDK used for the project, so when we switch to Metals built-in JDK it will be different that the one used for project.

Ahhh, I got it, then `Runtime` won't work as we want unfortunately anyway.
