### ISSUE TITLE
Scala 3 underscore completions

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3559]
### Describe the bug

Given a minimal piece of code like this in Scala 3:

```scala
  case class Foo(a: Int, b: Int)
  val foo = Foo(1, 2)

  foo.@@
```
When you trigger a completion at `@@` you'll notice that there are completions returned that included the `_1`, and`_2` methods that are generated by the compiler as the top options. While these are valid I guess:

_cfr output_
```java
public int _1() {
    return this.a();
}

public int _2() {
    return this.b();
}
```
It's arguably not what the user wants. Should we maybe filter these out?

<img width="585" alt="Screenshot 2022-01-22 at 13 01 05" src="https://user-images.githubusercontent.com/13974112/150637787-ab33070f-8dc0-4f3e-b1eb-8ea46682e529.png">

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.1+21-04405c04-SNAPSHOT

**Comment by dos65** [comment]
@ckipp01 I've checked this. There are `_1` and `_2` in completions items but they comes after `a`, `b` that is correct.
Maybe there is some issue with ordering in nvim?

I don't think that we should remove these method from completion as they are valid options.

**Comment by ckipp01** [comment]
> I don't think that we should remove these method from completion as they are valid options.

yea agree.

As for the ordering, it looks like the completion framework I'm using is trying to do some smart stuff with it. Either way, I'll close.

**Comment by fiatjaf** [comment]
Irrelevant to Metals, but for anyone arriving here with the same issue, this seems to be an issue with sorting of autocomplete options on https://github.com/hrsh7th/nvim-cmp (or maybe other editor completers have similar issues):

You can customize sorting by passing an array of sorting functions to `sorting.comparators` on setup. [These are the defaults](https://github.com/hrsh7th/nvim-cmp/blob/6e1e3865158f340d6cd3936937eb56947b5a90f9/lua/cmp/config/default.lua#L49-L63).

I've fixed this one for me by making sure `Field`s (kind 5) are always shown before `Method`s (kind 2):

```lua
local cmp = require'cmp'
local compare = require'cmp.config.compare'
local cmp_types = require'cmp.types.cmp'
cmp.setup({
  -- ...other stuff here
  sorting = {
    comparators = {
      function (a, b)
        if a:get_kind() == 5 and b:get_kind() == 2 then
          return true
        elseif a:get_kind() == 2 and b:get_kind() == 5 then
          return false
        end
        return nil
      end,
      compare.exact,
      compare.score,
      compare.kind,
      compare.recently_used,
      compare.locality,
      compare.offset,
      compare.sort_text,
      compare.length,
      compare.order
    }
  }
})
```

Result:

![2022-05-23-164640_515x256_scrot](https://user-images.githubusercontent.com/1653275/169894724-96cac2bd-d542-4d95-ad9b-e35298fca93d.png)
