### ISSUE TITLE
insert type annotation doesn't conform to type hints

### ISSUE THREAD

**Issue by doofin** [scalameta/metals#3561]
### Describe the bug

when try to insert type annotation ,the type hints are correct which is Future[Unit], but the action just give Any:

```
val t = for { a <- Future(1) } yield ()
```

### Expected behavior

inserted type annotation should be same as the type hints

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

"0.11.2-SNAPSHOT"

**Comment by tgodzik** [comment]
Thanks for reporting! I can't seem to reproduce it in Scala 2 or Scala 3. Could you add a bit more information? For example what is the Scala versions and maybe the whole sample that this fails in.

**Comment by doofin** [comment]
Thanks for quick reply ! I also try to reproduce it in other places,but it didn't show up. It's a mixed scalajs /jvm project, and the bug occurs in a simple method of an object in scala js part. I tried to look at metals.log but nothing special is printed. How can I get more debug info?

**Comment by tgodzik** [comment]
Does this happen always in JS projects or only in that specific one? Can you reproduce it for example using https://scala-cli.virtuslab.org/ or sbt ? It should be possible to use it with JS

**Comment by doofin** [comment]
I might worked out a minimal sample  for that ,it seems related to implicits:
```scala
import scala.scalajs.js
import scala.concurrent.Future
import scala.concurrent.ExecutionContext

// https://github.com/scala-js/scala-js-macrotask-executor
trait jsImplicits {

  // implicit def futureRT: ExecutionContext =
  // org.scalajs.macrotaskexecutor.MacrotaskExecutor.Implicits.global

  // implicit def futureRT: ExecutionContext =
  implicit def futureRT: ExecutionContext =
    scala.concurrent.ExecutionContext.global

  implicit def p2future[a](p: js.Promise[a]): Future[a] = {
    p.toFuture
  }
}

object jsImplicits extends jsImplicits
```

Then import it somewhere

```scala
import jsImplicits._

object someObj {
  def test2 = {
    val t: Any = for { a <- Future(1) } yield ()
  }
}
```

**Comment by tgodzik** [comment]
So it seems that the problem is that you don't do:
`import scala.concurrent.Future` 

future is undefined in that scope, so that is why you are getting `Any`

**Comment by doofin** [comment]
Sorry for my lapse,I have this `import scala.concurrent.Future` in the example ,it still annotate `Any`

**Comment by doofin** [comment]
It's not hover on type. In this one the hover doesn't work either.  I guess it's due to bugs in imlicits resolution,but the show inferred type still works:
![image](https://user-images.githubusercontent.com/6041353/151029979-b880dfa5-4bbe-4a71-ba81-1c6f4cd8ea43.png)

**Comment by tgodzik** [comment]
` show inferred type ` is using the last compiled state here, which is why it works.

**Comment by tgodzik** [comment]
It seems we would be unable to fix it, if the presentation compiler resolves the type to `Any` there is nothing we can do about it. We cannot block insert type if there are compilation errors, since in a lot of cases this will work.

**Comment by doofin** [comment]
Should we instead use the info from last compiled state similar to show inferred type ?

**Comment by tgodzik** [comment]
> Should we instead use the info from last compiled state similar to show inferred type ?

It would be hard to figure out whether we should use the old or if maybe the code was changed and type is different now. This will also only work if you compiled and then broke the code, which might not be that often.

**Comment by doofin** [comment]
Should we add a config key for this ? The old is actually not that different from the new one.Would be glad to help

**Comment by tgodzik** [comment]
> Should we add a config key for this ? The old is actually not that different from the new one.Would be glad to help

I would rather avoid adding a setting here, since we try to not grow the settings too much and the bahaviour here could cause a lot of flakiness.
