### ISSUE TITLE
Launching Play-Seed Projects

### ISSUE THREAD

**Issue by dubielt1** [scalameta/metals#3575]
### Describe the bug

There is no clear avenue for launching Play Framework projects / applications with Metals, as far as I can tell.

I am using VSCode Remote Containers for development, so I do not have Java / SBT / etc. installed on my base Windows OS.

Repro:
1. Install VSCode
2. Open a workspace
3. Re-Open workspace in Container
4. Select default Java 8
5. After Container is built and opened, install Metals Extension
6. Create a Scala Play project: Metals -> New Project -> default Play Seed

devcontainer.json below is the default Java 8 config, with the Metals extension added to extensions:
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/java-8
{
	"name": "Java 8",
	"build": {
		"dockerfile": "Dockerfile",
		"args": {
			// Use the VARIANT arg to pick a Debian OS version: buster, bullseye
			// Use bullseye when running on local arm64/Apple Silicon.
			"VARIANT": "buster",
			// Options
			"INSTALL_MAVEN": "false",
			"INSTALL_GRADLE": "false",
			"NODE_VERSION": "lts/*"
		}
	},

	// Set *default* container specific settings.json values on container create.
	"settings": {
		"java.home": "/docker-java-home",
		"java.import.gradle.java.home": "/usr/local/sdkman/candidates/java/current",
		"java.configuration.runtimes": [{
			"default": true,
			"name": "JavaSE-1.8",
			"path": "/usr/local/sdkman/candidates/java/current"
		}]
	},
	
	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"vscjava.vscode-java-pack",
		"scalameta.metals"
	],

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "java -version",

	// Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode",
	"features": {
		"git": "latest"
	}
}
```

In a typical scenario with sbt installed, Play framework can be launched with `sbt run`. But installing sbt/build tools in the container myself would obviate the need for Metals (or at least part of its functionalities).

I am happy to add to the docs, if there is a scenario where Metals can launch the Play application

### Expected behavior

Metals can launch Play Framework applications

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.12.0

### Extra context or search terms

Play framework
launch config
VS Code Containers

**Comment by tgodzik** [comment]
Thanks for reporting! Good news is that it is possible to launch Play projects in Metals thanks to:
https://github.com/scalameta/metals/issues/1667

Something like this in `.vscode/launch.json` should work:
```
{
      "type": "scala",
      "request": "launch",
      "name": "Play main",
      "mainClass": "play.core.server.ProdServerStart",
      "args": [],
      "jvmOptions": [],
      "buildTarget": "rotator"
    }
```
However, it is not obvious. We should most likely improve the user experience here, the minimum thing we can do is have a preconfigured play launch configuration. We can look into that.

**Comment by dubielt1** [comment]
Hi Tomasz, thank you for the quick reply!

I've created a `.vscode/launch.json` like described in your comment.

If I try to F5 or Ctrl-F5 while `HomeController.scala` file is open and has context, I get the below error (excerpt):

```
[Error - 6:22:30 PM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.DebugProvider$NoRunOptionException$: There is nothing to run or test in the current file.
```

Any tips?

Thanks!

**Comment by dubielt1** [comment]
@tgodzik - correct me if I am wrong, but one major downside here is that we lose the "hot reload" the play framework provides, since we are launching the Prod Server?

Would be nice if there was some entry point into the dev server, if only for semantic reasons, but looking through the play framework code I don't see a straightforward way to do so.

**Comment by tgodzik** [comment]
> @tgodzik - correct me if I am wrong, but one major downside here is that we lose the "hot reload" the play framework provides, since we are launching the Prod Server?
> 
> Would be nice if there was some entry point into the dev server, if only for semantic reasons, but looking through the play framework code I don't see a straightforward way to do so.

Unfortunately, you are right. I am not sure how to even make it work with the dev server. It looks like the server itself is started in sbt here: https://github.com/playframework/playframework/blob/fe4861300034eb0625867de3d33c4671635fc82a/dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala#L77

Maybe it would be possible to do with sbt BSP? Though I am afraid that might be a lot more work. The best way to do it is currently to run the dev server in sbt (with added debug flags if needed)

**Comment by tgodzik** [comment]
I added the configuration snippet here: https://github.com/scalameta/metals-vscode/pull/863

It should be a bit easier to discover. We don't have any custom integrations for any tools yet, so not sure even if we want to go that way (we try to rein in the scope a bit.), I opened upa feature request in https://github.com/scalameta/metals-feature-requests/issues/252 

I will close this issue in favour of that.
