### ISSUE TITLE
Expired GPG key error when installing metals from emacs lsp-mode

### ISSUE THREAD

**Issue by lancelet** [scalameta/metals#3583]
### Describe the bug

When trying to fetch metals via the LSP mode in doom emacs, I encountered the following error:

```
LSP :: Finished downloading /Users/jmerritt/.emacs.d/.local/etc/lsp/metals/coursier...
LSP :: Starting to download https://raw.githubusercontent.com/coursier/launchers/master/coursier.asc to /Users/jmerritt/.emacs.d/.local/etc/lsp/metals/coursier.asc...
Contacting host: raw.githubusercontent.com:443
Wrote /Users/jmerritt/.emacs.d/.local/etc/lsp/metals/coursier.asc
LSP :: Finished downloading /Users/jmerritt/.emacs.d/.local/etc/lsp/metals/coursier.asc...
LSP :: Verifying signature /Users/jmerritt/.emacs.d/.local/etc/lsp/metals/coursier.asc...
LSP :: Server metals install process failed with the following error message: (error Failed to verify GPG signature: Signature made by expired key CD1B9D8DC84ECA56 Alexandre Archambault (Travis CI coursier) <alexandre.archambault+traviscicoursier@gmail.com>).
```

I'm not sure exactly where the error originates (it may be from Coursier, and not Metals, I think), but I was able to circumvent it by doing:

```
mkdir -p ~/.emacs.d/.local/etc/lsp/metals
pushd ~/.emacs.d/.local/etc/lsp/metals
coursier bootstrap org.scalameta:metals_2.12:0.11.1 -o metals -f
popd
```

### Expected behavior

Expected installation of metals via lsp-mode to work.

### Operating system

macOS

### Editor/Extension

Emacs (lsp-metals)

### Version of Metals

v0.11.1

**Comment by ckipp01** [comment]
Thanks for the report @lancelet! Just to tie this all together it looks like this has been reported upstream as well.

- https://github.com/emacs-lsp/lsp-metals/issues/65
- https://github.com/coursier/coursier/issues/2346

This will need to be fixed upstream but we can leave this open until it's resolved in case anyone else hits on it.

**Comment by ckipp01** [comment]
> Looks like we can close this one? Or am I missing something?

Probably, as there isn't anything we can do here. This would need to be handled in coursier and there is a workaround listed in https://github.com/coursier/coursier/issues/2346.

**Comment by tgodzik** [comment]
We should probably add an FAQ with the workaround, might be helpful?

**Comment by ckipp01** [comment]
> We should probably add an FAQ with the workaround, might be helpful?

Indeed, I'm double checking to see if we should just put it right into the default config or not. If not I can add the workaround in a note below or something.

**Comment by kurnevsky** [comment]
I removed gpg keys from lsp-metals, so there shouldn't be such errors anymore.
