### ISSUE TITLE
Hover on annotation in Scala just shows the Ref it's on

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3593]
### Describe the bug

Having a minimal piece of code like this:

```scala
import scala.annotation.nowarn

@no@@warn
class Foo
```

When you attempt to do a hover on `@nowarn` you actually get the `TypeRef` of `Foo` shown instead of the information about `@nowarn`.

<img width="281" alt="Screenshot 2022-02-01 at 10 48 01" src="https://user-images.githubusercontent.com/13974112/151946431-33224950-cd78-4210-855c-0f63c45c2ac6.png">

The tree that is returned here for this pos is:

```
TypeDef(
  name = Foo,
  rhs = Template(
    constr = DefDef(
      name = <init>,
      paramss = List(List()),
      tpt = TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Unit)],
      preRhs = Thicket(trees = List())
    ),
    parentsOrDerived = List(
      Apply(
        fun = Select(
          qualifier = New(
            tpt = TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object)]
          ),
          name = <init>
        ),
        args = List()
      )
    ),
    self = ValDef(name = _, tpt = Thicket(trees = List()), preRhs = Thicket(trees = List())),
    preBody = List()
  )
)
```
I actually stumbled onto this because of something else (trying to understand when I'd see the `Annotated` tree) and then realizing I could never see it when testing with untyped trees or typed ones. Then I looked at how Metals would show this, and it also doesn't show the annotation. Is this actually an updates issue that `Annotated` is never in the tree? 

### Expected behavior

I'd expect that this show the signature and scaladocs for `@nowarn` instead of for `Foo`.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.1+47-66ea31ef-SNAPSHOT

**Comment by tgodzik** [comment]
I dug into that recently actually and it seems that the annotation tree is in the type. 

I did fix an issue related to it in  https://github.com/lampepfl/dotty/pull/13834/files

**Comment by rochala** [comment]
This was caused by a crash:
```scala
dotty.tools.dotc.ast.Trees$Tree.tpe(Trees.scala:72)
        dotty.tools.pc.utils.MtagsEnrichments$.tryTail$1(MtagsEnrichments.scala:262)
        dotty.tools.pc.utils.MtagsEnrichments$.expandRangeToEnclosingApply(MtagsEnrichments.scala:279)
        dotty.tools.pc.HoverProvider$.hover(HoverProvider.scala:51)
        dotty.tools.pc.ScalaPresentationCompiler.hover$$anonfun$1(ScalaPresentationCompiler.scala:326)
```

It was already solved by accident with https://github.com/lampepfl/dotty/pull/19488
![image](https://github.com/scalameta/metals/assets/48657087/81186445-7f19-4d5d-a7b3-54fe97700808)

It will also be backported in the future to LTS. Also this may hide the underlying problem so it may need a bit more investigation.
