### ISSUE TITLE
Bloop launcher ignores `JAVA_HOME`

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#3624]
### Describe the bug

To reproduce:
  - install several JVMs
  - run Metals from non default one(`JAVA_HOME=$alternative code .`)
  - notice that bloop java version is different from Metals (`jcmd $bloop-process-id VM.version`)
  

### Version of Metals

v0.11.1

**Comment by tgodzik** [comment]
JAVA_HOME variable should work in most cases though we can't actually send it from Metals as Bloop is global, which is why this might not work.

Proper way of setting Java home is by setting it `~/.bloop/bloop.json`, which we could do automatically.

**Comment by kpodsiad** [comment]
> Proper way of setting Java home is by setting it ~/.bloop/bloop.json, which we could do automatically.

The value will be coming from JAVA_HOME or current metals jdk? In the second case, taking into account that users can have different jdk specified per different workspaces (https://github.com/scalameta/metals-vscode/pull/861) this setting will be constantly overwritten.

**Comment by dos65** [comment]
Fixed by https://github.com/scalacenter/bloop/pull/1671
