### ISSUE TITLE
When you save a resource it's not copied over to your classes

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3648]
### Describe the bug

In a situation where you have a `src/main/resources/file.sql` or any other type of resource there are times (especially when using DAP to run the app) that you'll want your resources to be up to date. However, there seems to be no `didSave` event sent to metals from the editor when you save one of these files. This for sure happens in `nvim-metals` and in VS Code. This can lead to confusing problems since the user expects this to be up to date just like any of their actual source.

Different clients may handle this different but it affects multiple so I'm sticking this in here.

### Expected behavior

I'd expect that if I'm in a Scala workspace and I save a resource it's copied over to my classes dir.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.1+152-63f6365d-SNAPSHOT

_Originally talked about on Discord with @tpolecat_

**Comment by ekrich** [comment]
This would be especially good for Scala Native too as we use the resources for native C/C++ and hopefully soon Rust so having the changed files copied would be excellent. So anything in `src/main/resources` or `src/test/resources`.

**Comment by dos65** [comment]
The basic case works well without any actions from Metals side, at least in bloop. Resources in classes dir are refreshed before starting debug session.

@ckipp01 Could you specify in which case it doesn't work?
Are you about the case when you started debug session and then do changes in resources being resumed on breakpoint?

**Comment by ckipp01** [comment]
> @ckipp01 Could you specify in which case it doesn't work?

I only verified that when you have a resource, change it, and then keep coding that it's not carried over on save. I didn't actually try any DAP stuff. This was a report based of the info @tpolecat was giving on Discord.

**Comment by dos65** [comment]
@tpolecat Could you specify the case when you found this thing might be useful?
Technically, it isn't hard to do on metals side but there is a chance that it's needed to be done in build tool.

**Comment by tpolecat** [comment]
The use case is that I update a `.sql` file in my resources folder and then git Ctrl+F5 to run my program and the updated resource is not visible. I have to go into the sbt console and do `copyResources`. My expectation here is that resources should be copied on save, the same way sources are compiled on save.

**Comment by tpolecat** [comment]
I'm using sbt as my build server.

**Comment by ekrich** [comment]
I think whether it is Bloop or sbt, when a resources file is saved/changed, Metals needs to send a BSP message to the build server that the file changed. At that point sbt or bloop should copy the file into the classes dir. I think if you put sbt in `~compile` mode it should copy the file if changed or at least `~run` mode.

**Comment by Arthurm1** [comment]
I see - it seems Bloop and SBT behave differently with resources dirs...

Bloop
```
Classpath
    /root/metals/metals/src/main/resources                                                                         
    /root/metals/.bloop/metals/bloop-bsp-clients-classes/classes-Metals-PfE04TneRhyeEjLfVNy9mw==                   
    /root/metals/mtags/src/main/resources                                                                          
    /root/metals/.bloop/mtags/bloop-bsp-clients-classes/classes-Metals-PfE04TneRhyeEjLfVNy9mw==                    
    /root/metals/.bloop/interfaces/bloop-bsp-clients-classes/classes-Metals-PfE04TneRhyeEjLfVNy9mw==              
...
```

SBT
```
Scala Classpath
    /root/metals/metals/target/scala-2.12/classes                                
    /root/metals/mtags/target/scala-2.12.15/classes                              
    /root/metals/mtags-interfaces/target/classes     
...
```

**Comment by dos65** [comment]
@tpolecat thx for response! As I figured out it was the issue only with Ctrl+F5 in vscode client.
Currently `run|test` code lens works well.
