### ISSUE TITLE
Error downloading org.scalameta:mtags SNAPSHOT

### ISSUE THREAD

**Issue by gcnyin** [scalameta/metals#3655]
### Describe the bug

OS: windows 11
IDE: vscode
Metals plugin version: SNAPSHOT

Open sbt project in WSL(Ubuntu 20.04), but show some errors

```
Error downloading org.scalameta:mtags_2.13.0:0.11.1+158-06755eb9-SNAPSHOT
  not found: /home/hhz-ubuntu/.ivy2/local/org.scalameta/mtags_2.13.0/0.11.1+158-06755eb9-SNAPSHOT/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalameta/mtags_2.13.0/0.11.1+158-06755eb9-SNAPSHOT/mtags_2.13.0-0.11.1+158-06755eb9-SNAPSHOT.pom
  not found: https://oss.sonatype.org/content/repositories/public/org/scalameta/mtags_2.13.0/0.11.1+158-06755eb9-SNAPSHOT/mtags_2.13.0-0.11.1+158-06755eb9-SNAPSHOT.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mtags_2.13.0/0.11.1+158-06755eb9-SNAPSHOT/mtags_2.13.0-0.11.1+158-06755eb9-SNAPSHOT.pom
```

### Expected behavior

Download metals in WSL.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.1+158-06755eb9-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! Are you using Scala 2.13.0? It's no longer supported, so bets to upgrade to the newest one `2.13.8`

**Comment by tgodzik** [comment]
IF you find any other issues please let us know, but we don't support Scala 2.13.0
