### ISSUE TITLE
Add `generated` information to `Source Directories` section of `Display build target info`

### ISSUE THREAD

**Issue by tanishiking** [scalameta/metals#3718]
### Describe the bug

This issue is a follow up from https://github.com/scalameta/metals/pull/3694#issuecomment-1063933077

Currently,`> display build target info` prints something like: 

```
Source Directories
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/src/main/java
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/src/main/scala
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/src/main/scala-2
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/src/main/scala-2.13
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/target/scala-2.13/src_managed/main
```

### Expected behavior

It would be nice if it prints like

```
Source Directories
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/src/main/java
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/src/main/scala
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/src/main/scala-2
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/src/main/scala-2.13
  /Users/tanishiking/src/github.com/tanishiking/metals/metals/target/scala-2.13/src_managed/main (generated)
```

?

FYI: https://github.com/scalameta/metals/pull/3694#discussion_r823566814

### Version of Metals

v0.11.2

**Comment by tgodzik** [comment]
Thanks for reporting! Should we enable it only for sbt or also for Bloop? For the latter we might need to modify the configuration files

**Comment by tanishiking** [comment]
I think it's ok to support only sbt at the first step (because Bloop doesn't return `generated` flags for [buildTarget/sources](https://build-server-protocol.github.io/docs/specification.html#build-target-sources-request) at least for the directories),
but in the future, yes, bloop also should be able to support this.
