### ISSUE TITLE
code action - generate companion object

### ISSUE THREAD

**Issue by tnielens** [scalameta/metals#3736]
### Is your feature request related to a problem? Please describe.

When developing in vscode, I'd like to generate a companion object snippet.

### Describe the solution you'd like

Add a "generate companion object" code action. See comparable feature in intelliJ: 
<img width="349" alt="image" src="https://user-images.githubusercontent.com/11885535/157325243-93fe4bbd-81af-4fd0-adce-6f60424b93a0.png">
Result:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/11885535/157325347-7ae95525-efac-455a-8528-a5b01899c698.png">

### Describe alternatives you've considered

Haven't found anything comparable in vscode.

### Search terms

companion object snippet generate

**Comment by ckipp01** [comment]
Transferring to the main repo since this is currently being worked on.
