### ISSUE TITLE
Too many newlines in hover when showing synthetics with Scala 3

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3740]
### Describe the bug

When hovering on a method that has an implicit param there are multiple extra new lines in the hover that is returned that aren't needed. It then renders like this:

<img width="342" alt="Screenshot 2022-03-20 at 14 50 22" src="https://user-images.githubusercontent.com/13974112/159165673-d71d522a-2549-4ad9-bdbc-bcb8d5a3d07d.png">

Notice all the extra space between `Some message` and the `With synthetics added:`. This is what the LSP response looks like:

```[Trace - 02:51:55 PM] Sending response 'textDocument/hover - (28)'. Processing request took 33ms
Result: {
  "contents": {
    "kind": "markdown",
    "value": "```scala\ndef foo(a: Int)(implicit b: Int): Int\n```\nSome message\n\n\n\n**With synthetics added**:\n```scala\nfoo(3)(example.Main.b)\n```"
  }
}
```
Notice the four `\n` in a row.

### Expected behavior

This differs from the response you get when using Scala 2. I'd expect it to be the same:

<img width="344" alt="Screenshot 2022-03-20 at 14 53 37" src="https://user-images.githubusercontent.com/13974112/159165788-06c54b11-20ee-4adc-8f06-33bc80222e70.png">

```
[Trace - 02:52:58 PM] Sending response 'textDocument/hover - (51)'. Processing request took 215ms
Result: {
  "contents": {
    "kind": "markdown",
    "value": "```scala\ndef foo(a: Int)(implicit b: Int): Int\n```\nSome message\n\n**With synthetics added**:\n```scala\nfoo(3)(example.Main.b)\n```"
  }
}
```
Notice there are 2 less `\n` in Scala 2 then when using Scala 3.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.2+86-4d583c7c-SNAPSHOT

**Comment by ckipp01** [comment]
Alright, looking closer this seems to be an upstream issue actually.

When we call `renderAsMarkdown` on `/** Some message */` it returns it back from Dotty with two extra newlines at the end. I think the best place to fix this would be there.

**Comment by tgodzik** [comment]
We could also replace too many `\n+` with `\n` as a workaround

**Comment by tgodzik** [comment]
Awesome!
