### ISSUE TITLE
[Scala 3] Code Actions for Imports Don't Work

### ISSUE THREAD

**Issue by andyczerwonka** [scalameta/metals#3744]
### Describe the bug

I don't know if this is just a feature that has yet to be added, but I'm reporting a defect simply because this feature works for Scala 2 projects.

Code completions are working, but if I copy/paste some code with missing imports, Metals does not give me any help with those missing imports.
![image](https://user-images.githubusercontent.com/138898/159273798-27a22524-f258-48d1-a20e-17c7568cf933.png)

When running the same code within a Scala 2 environment, I get the yellow light-bulb that given be import options.

### Expected behaviour

The yellow light-bulb `code action` pops up with import choices, just like it does for Scala 2 projects.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.2

**Comment by tgodzik** [comment]
Thanks for reporting! What is the exact Scala version you are using here? Also, which build server?

IT seems I can't reproduce it at all:

![metals-decompile-1647872248378](https://user-images.githubusercontent.com/3807253/159280445-2f3ff979-71c4-4d11-8680-65ed6ec75ed0.gif)

The only difference I see is that the message is different. `Not found: type` instead of `Not found: type Try`

Anything in the logs?

**Comment by andyczerwonka** [comment]
That's strange. Scala is `3.1.1` and I'm using Bloop `v1.4.13`.

My `build.sbt` is as follows:

```
ThisBuild / name := "pdf-license"
ThisBuild / organization := "com.andyczerwonka"
ThisBuild / organizationName := "Andy Czerwonka"
ThisBuild / version := "0.1.0"
ThisBuild / scalaVersion := "3.1.1"

ThisBuild / scalacOptions ++= Seq(
  "-deprecation", // emit warning and location for usages of deprecated APIs
  "-explain", // explain errors in more detail
  "-explain-types", // explain type errors in more detail
  "-feature", // emit warning and location for usages of features that should be imported explicitly
  "-indent", // allow significant indentation.
  "-print-lines", // show source code line numbers.
  "-unchecked", // enable additional warnings where generated code depends on assumptions
  "-Ykind-projector", // allow `*` as wildcard to be compatible with kind projector
  "-Xfatal-warnings", // fail the compilation if there are any warnings
  "-Xmigration" // warn about constructs whose behavior may have changed since version
)

ThisBuild / libraryDependencies ++= Seq(
  "org.apache.pdfbox" % "pdfbox" % "2.0.25",
  "com.github.scopt" %% "scopt" % "4.0.1",
  "org.scalameta" %% "munit" % "0.7.29" % Test
)

// Use scalafix to align organize imports with IntelliJ style
ThisBuild / semanticdbEnabled := true
ThisBuild / semanticdbVersion := scalafixSemanticdb.revision
ThisBuild / scalafixDependencies += "com.github.liancheng" %% "organize-imports" % "0.6.0"

lazy val app = (project in file("app"))
  .settings(
    assembly / mainClass := Some("Cli"),
    assembly / assemblyJarName := "pdf-license.jar"
  )
```
