### ISSUE TITLE
Cancel should cancel all current requests

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3754]
### Describe the bug

Currently if user cancels a compilation only one compilation is canceled while all the others still work.

### Expected behavior

All current compilations are cancelled

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.2

### Extra context or search terms

cancel compile

**Comment by kpodsiad** [comment]
I've inspected `bsp.trace.json` and there are no logs with `$/cancelRequest`. It can mean that cancelation doesn't work at all.
