### ISSUE TITLE
"Extract class to file" refactoring leaves behind end marker

### ISSUE THREAD

**Issue by keynmol** [scalameta/metals#3762]
### Describe the bug

Scala 3.1.1, Metals 0.11.2+86-4d583c7c-SNAPSHOT

_I'm having a de ja vu, I think I've reported this before..._

1. Be me
2. Have a file like this:
```scala 
class Test:
  def hello = ???
end Test

class Bla:
  def hello = ???
end Bla
```

3. Run "Extract class Bla to file Bla.scala"
4. Class is extracted okay, but the `end Bla` line remains in the main file

![2022-03-26 18 00 02](https://user-images.githubusercontent.com/1052965/160251766-0b961474-adb1-49ed-aafc-95df1b1615e4.gif)

### Expected behavior

Class is extracted cleanly, along with its end marker

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.2+86-4d583c7c-SNAPSHOT

### Extra context or search terms

code action, scala 3, end marker, extract, class, file

**Comment by tgodzik** [comment]
Thanks for reporting! This is because the end marker is included in the parent's statements, we should check this additionally.
