### ISSUE TITLE
ERROR Flag -classpath set repeatedly

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3766]
### Describe the bug

I've been having a fair amount of issues with Metals recently when working in the Dotty codebase. Mainly it just stops offering goto defintions, but I don't see any issues about missing semanticdb or the normal stuff. All that to say I've been paying more attention to the logs recently and I see a ton of:
```
2022.03.28 20:04:56 INFO  time: compiled tasty-core-test in 0.77s
2022.03.28 20:04:56 ERROR Flag -classpath set repeatedly
2022.03.28 20:04:56 ERROR Flag -classpath set repeatedly
2022.03.28 20:05:27 INFO  time: compiled scala3-compiler in 30s
```
The thing that sticks out is that there are `ERROR` here, but when I look in an simple Hello world project I also see them, but see them as WARNING.

```
2022.03.28 20:06:17 WARN  Flag -bootclasspath set repeatedly
2022.03.28 20:06:17 WARN  Flag -classpath set repeatedly
2022.03.28 20:06:47 INFO  time: compiled Sanity in 36s
```

I just wanted to throw this up here before I forgot.

### Expected behavior

I'm not sure. Is this problematic? If not, then we shouldn't be getting errors for it. If it is, then we should fix it.

### Operating system

macOS

### Version of Metals

0.11.2+112-e731195f-SNAPSHOT

**Comment by tgodzik** [comment]
I've seen it and it's most likely related to the Bloop update, but I was not able to pinpoint it exactly :/ 
Looks like maybe it's the way we invoke zinc :thinking: I need to take a look at it as well as some other issues I've been seeing.
