### ISSUE TITLE
Installation documentation is very terse

### ISSUE THREAD

**Issue by juhp** [scalameta/metals#3796]
I am still a newcomer to scala and metals, and an Emacs user.
I find the website documentation about installation is really too terse.
I think a note should be added somewhere about how to install metals from the command line.

**Comment by kpodsiad** [comment]
Hi @juhp, thanks for reporting this!
Do you manage to get the Metals working?

**Comment by ckipp01** [comment]
Thanks for the feedback @juhp. You can see some instructions on how to bootstrap metals from the command line [here](https://scalameta.org/metals/docs/editors/emacs#eglot) if you scroll down a bit. However, it's even easier than that as you can also do a `cs install metals` if you have [coursier](https://get-coursier.io/) installed.

Most of the editor-specific docs are maintained by users of that editor, so please do feel free to report back improvements or make changes as you see mistakes or opportunities. Doc updates are always very welcome. You can see how to do those [here](https://scalameta.org/metals/docs/contributors/updating-website).

**Comment by juhp** [comment]
Thanks for the helpful reply.

Would it make sense to mention `coursier install metals` as an option in a small section of the top text editors overview page?

**Comment by ckipp01** [comment]
> Would it make sense to mention coursier install metals as an option in a small section of the top text editors overview page?

Honestly probably not on the overview page. Mainly because the vast majority of users will be using a client where it automatically will install Metals for you. So I'd rather not cause confusion by putting the `coursier install metals` right out in front.
