### ISSUE TITLE
Files in sources jars with extra parent directories are not found

### ISSUE THREAD

**Issue by arobertn** [scalameta/metals#3815]
## Issue description

When working with Scala in VS Code, Metals will download sources jars and support dereferencing classes from them in code files by the "Go to definition" context menu option. However if said source jars contain extra parent directories, e.g. source files are under `src/main/java/com/...` in the jar instead of `com/...` then this silently fails and you get "No definition found". The "Language Support for Java by Red Hat" on the other hand correctly finds the source files and allows dereferencing. The attached project demonstrates this for the [bindings-rxjava](https://search.maven.org/artifact/com.daml/bindings-rxjava/2.0.0/jar) and [bindings-java](https://search.maven.org/artifact/com.daml/bindings-java/2.0.0/jar) jars which respectively have single and multiple buried roots.

## Reproduction steps

1. Set JAVA_HOME to a JDK-11 installation.
2. Install Scala (Metals) and Language Support for Java by Red Hat
3. Unpack the attached `src-jar-test.zip` and load the resulting `src-jar-test` directory into VS Code
4. Wait for the project to import
5. Open the "JarTest.java" file.
6. Note that hovering or Ctrl/Cmd hovering over the classes `DamlLedgerClient` (single-buried-root) and `TransactionFilter` (multiple roots) results in Javadoc and/or source previews, and Ctrl/Cmd-clicking goes to the source.
7. Open the "JarTest.scala" file.
8. Note that Ctrl/Cmd hovering / clicking does NOT work in the Scala file, though it WILL work for the slf4j classes.

[src-jar-test.zip](https://github.com/scalameta/metals/files/8464190/src-jar-test.zip)

### Expected behavior

I have not found anything in the [Jar file specification](https://docs.oracle.com/en/java/javase/11/docs/specs/jar/jar.html) specifically addressing this point, but in practice the Java plugins for VS Code and IntelliJ both find the sources despite the extra parent directories, and I expected Metals to do so as well.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.2

**Comment by zmerr** [comment]
It can be reproduced when JAVA_HOME is on Java 17 too.

**Comment by arobertn** [comment]
Just a note, I'm still reproducing this with the project attached above with Metals 0.11.2 which should include #5009. (Java 11 and 18 tried.)

**Comment by tgodzik** [comment]
> Just a note, I'm still reproducing this with the project attached above with Metals 0.11.2 which should include #5009. (Java 11 and 18 tried.)

We need to take another look then, thanks for letting us know!
