### ISSUE TITLE
Breakpoint not working in dependency jar

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3824]
### Discussed in https://github.com/scalameta/metals/discussions/3813

<div type='discussions-op-text'>

<sup>Originally posted by **lyfne123** April 11, 2022</sup>
Hi, I'm a new learner of Metals, I have a question that my breakpoints in dependency jar is not working.

below is my example code:
```
object TestApp extends App {
  val a = ArrayBuffer(3, 2, 6)
  a.insert(1, 32)
  a ++= ArrayBuffer(5)
}
```

I can add breakpoint in TestApp, but if I add inside ++= function, which is in`org/scala-lang/scala-library/2.12.10/scala-library-2.12.10-sources.jar!/scala/collection/mutable/ArrayBuffer.scala`, line 98, the debugger can't hit that breakpoint.

I can see it at Run & Debug panel.
<img width="473" alt="截屏2022-04-11 下午5 25 39" src="https://user-images.githubusercontent.com/70868521/162709185-5e54581c-d86e-4ac1-bac9-05825bb3d2fb.png">

Could please anyone can reply my quesion? Thanks very much!</div>

**Comment by kpodsiad** [comment]
I think the source of the problem are virtual documents.
Here's the trace from setting brekpoint in my Main:
<details>
  <summary>Source file</summary>
  
```json
{
  "type": "request",
  "seq": 6,
  "command": "setBreakpoints",
  "arguments": {
    "source": {
      "name": "TestApp.scala",
      "path": "/Users/kpodsiadlo/vl/my-app/src/main/scala/TestApp.scala",
      "sourceReference": 0
    },
    "lines": [
      8
    ],
    "breakpoints": [
      {
        "line": 8
      }
    ],
    "sourceModified": false
  }
}
```
</details>
and here's the trace from dependency:

<details>
  <summary>JAR file</summary>

```json
{
  "type": "request",
  "seq": 4,
  "command": "setBreakpoints",
  "arguments": {
    "source": {
      "name": "ArrayBuffer.scala",
      "path": "jar:file%3A///Users/kpodsiadlo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15-sources.jar%21/scala/collection/mutable/ArrayBuffer.scala"
    },
    "lines": [
      98,
      105
    ],
    "breakpoints": [
      {
        "line": 98
      },
      {
        "line": 105
      }
    ],
    "sourceModified": false
  }
}
```
</details>

See that JAR file has `jar:file%3A///` prefix and I guess that `jar` is the source of problems.

**Comment by kpodsiad** [comment]
closed via https://github.com/scalameta/metals/pull/3846
