### ISSUE TITLE
Installation problems in VSCode

### ISSUE THREAD

**Issue by mpilquist** [scalameta/metals#383]
I tried installing 0.3.1 in to VSCode -- disabled other Scala language servers.

```
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home
logging to file /Users/mpilquist/Development/project/.metals/metals.log
Unable to automatically connect to build server.
skipping build import with status 'Failed'
```

Restarting the Metals server & reconnecting to the server results in the same errors as above. Note my default Java is OpenJDK 11 but I have the path to JDK 8 specified in Metals settings.

**Comment by gabro** [comment]
Can you try and see whether manually executing the "Import build" command givws the same error?

**Comment by olafurpg** [comment]
@mpilquist are you behind a proxy? You may need to configure system properties to make it work then. It's undocumented at the moment, I've been meaning to add a section on proxies for a while.

**Comment by mpilquist** [comment]
Not behind a proxy exactly -- rather, I have to launch sbt with these args:
```
sbt -sbt-dir "$SBT_ENV_HOME" -ivy "$IVY_HOME" "$@"
```

Where `SBT_ENV_HOME/repositories` contains a bunch of custom resolvers and `SBT_OPTS` contains  `-Dsbt.override.build.repos=true -Divy.home=${IVY_HOME}`.

**Comment by gabro** [comment]
Adding configurable sbt options similarly to the Java options we already have should be easy, wdyt @olafurpg?

**Comment by olafurpg** [comment]
I opened #387 adding support for `.sbtopts`, `.jvmopts` and allowing users add custom JVM options when metals launches `sbt`. I'm not sure if this fixes your problem @mpilquist but it's a good first step.

If that doesn't do the trick we probably need another option to run the user's `sbt` command directly, but I'm hesitant to go that route since it didn't work reliably on Windows when I tried.

**Comment by mpilquist** [comment]
I think I’d need custom launcher support as I want to use the regular SBT launcher for open source projects and a special launcher for work stuff. I normally do this via a launcher launcher which checks the directory structure and passes the right args to the sbt launcher — either no args or overridden -sbt-dir and Ivy home.

**Comment by gabro** [comment]
@mpilquist from what I can tell, #387 also allows to provide a custom sbt launcher:

https://github.com/olafurpg/metals/blob/2d201096264182f20e56b3e29837739c4f6a6a7f/metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala#L34

That should satisfy your use case, right?

**Comment by mpilquist** [comment]
@olafurpg Yeah, either everyone needs a copy of the launcher script or everyone needs to configuration ~/.sbt/repositories to point to the corporate proxy. The latter works fine if you aren't doing open source work on the same machine. My launcher script is sort of a lightweight equivalent to `rbenv` which adjusts SBT & Ivy settings based on the project / directory.

The `.sbtopts` approach didn't work for me in the past, as some of the environments need global SBT config and the launcher ensures those are all configured appropriately.

**Comment by olafurpg** [comment]
@mpilquist Thanks for the context. I'll update #387 to support executing a custom `sbt` script to see if that does the trick.

**Comment by olafurpg** [comment]
The installation instructions for "Import build" have been updated to include the steps to customize the `sbt` executable.

<img width="817" alt="screenshot 2018-12-14 at 15 20 05" src="https://user-images.githubusercontent.com/1408093/50008213-c4c0d200-ffb3-11e8-8a36-f1acaf28c5ea.png">
