### ISSUE TITLE
Debugging Java with Mill using Bloop - breakpoints in Java GUI lib don't work

### ISSUE THREAD

**Issue by hmf** [scalameta/metals#3845]
**Describe the bug**

I have a Mill project that I have working correctly via Bloop. Bloop was correctly and automatically launched when the Mill build script was detected. This is a Scala 3 project. When I set breakpoints in the Scala code, the debugger pauses correctly. When I set breakpoints in the Java library code, it does not stop. I can however step into the code with no problems.

**To Reproduce** Steps to reproduce the behavior:

1. Ser several break points in the Scala source code and Java library code (Jar)
2. Click on `debug` word above the Scala object that has the `main` method (also use menu and buttons, same result)
3. When the debugger stops at the Scala breakpoint, click the debugger button to continue
4. The application runs without pausing

**Expected behavior**

I would expect the debugger to pause inside the Java code. 

**Installation:**

- Operating system: Ubunto 20.04
- VSCode version: 1.66.1
- VSCode extension version: 1.13.0
- Metals version: (found in VSCode settings, under `metals.serverVersion`) 0.11.2

**Additional context**

I am using the debugger to find out how a Java library works so as to circumvent some issues. This is a Swing GUI (plotting) and I need to set a break in the GUI's thread. 

I have searched the issues and found several entries regarding the debugger. I would like to know if debugging Java code is supported and if setting a breakpoint in another thread poses a problem. I also don't know if breakpoints within Jar files is possible. 

**Search terms**

debug, breakpoint, scala 3, stop, pause, Java, library, thread, Swing

**Comment by kpodsiad** [comment]
Thanks for raising this issue @hmf. It seems that we hit a regression in terms of debugging recently. Until some time ago, everything which you wrote was working, but currently it isn't. There are other, similar issues such as https://github.com/scalameta/metals/issues/3824.

**Comment by hmf** [comment]
@kpodsiad Thank you for such a fast response. Seeing as you already another open issue on this, if you like, I can close this one.

**Comment by kpodsiad** [comment]
If I answered all of your questions then yes, feel free to close this issue in favor of already existing ones.

In the meantime, you should probably use IntelliJ Idea to play with Swing and GUI thread.

**Comment by hmf** [comment]
@kpodsiad Ok. Will close then. Thanks.
