### ISSUE TITLE
Invalid entry CRC when attempting to install Metals on Linux

### ISSUE THREAD

**Issue by BloomnDoom** [scalameta/metals#3851]
### Describe the bug

I've installed `lsp-mode` and `lsp-metals` so when opening up a file, it prompts the installation of metals. It contacts github and starts decompressing the files, but stops a second later. The coursier log shows this:

`Im trying to install metals for scala however when i start the installation it starts decompressing the files and just exits. My scala version is 2.13.8-1

The coursier log shows this

`Exception in thread "main" java.util.zip.ZipException: invalid entry CRC (expected 0x8899ec42 but got 0xd4a7d99d) at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:409) at java.util.zip.ZipInputStream.read(ZipInputStream.java:198) at coursier.launcher.internal.FileUtil$.readFullyUnsafe(FileUtil.scala:20) at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:20) at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:10) at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:514) at scala.collection.Iterator.foreach(Iterator.scala:943) at scala.collection.Iterator.foreach$(Iterator.scala:943) at scala.collection.AbstractIterator.foreach(Iterator.scala:1431) at coursier.launcher.BootstrapGenerator$.writeZip(BootstrapGenerator.scala:112) at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2(BootstrapGenerator.scala:62) at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2$adapted(BootstrapGenerator.scala:18) at coursier.launcher.internal.FileUtil$.withOutputStream(FileUtil.scala:43) at coursier.launcher.BootstrapGenerator$.generate(BootstrapGenerator.scala:18) at coursier.launcher.Generator$.generate(Generator.scala:13) at coursier.cli.bootstrap.Bootstrap$.run(Bootstrap.scala:413) at coursier.cli.bootstrap.Bootstrap$.run(Bootstrap.scala:42) at caseapp.core.app.CaseApp.main(CaseApp.scala:149) at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:109) at coursier.cli.Coursier$.main(Coursier.scala:115) at coursier.cli.Coursier.main(Coursier.scala)
`

### Expected behavior

The lsp server should install itself properly

### Operating system

Linux

### Editor/Extension

Emacs (lsp-metals)

### Version of Metals

20220330.1958

**Comment by ckipp01** [comment]
Thanks for the report @BloomnDoom. I believe you're hitting on [this](https://github.com/coursier/coursier/issues/2398) which needs to be fixed upstream. As a workaround I believe you should still be able to install via the java launcher (coursier) instead of the native one (cs).

**Comment by BloomnDoom** [comment]
@ckipp01 Thanks for your reply. I'm on Arch linux. I've installed coursier from the site however I'm a bit confused on what to do now. Everything i need seems to to be located at ~/.local/share/coursier/bin however opening emacs still says that no server is installed. Could you please guide me on what to do next?

**Comment by ckipp01** [comment]
After the installation you should have `coursier` available to you as a command. You should then be able to do a `coursier install metals`. Hopefully this works whereas `cs install metals` will fail with the error. you mentioned. After this I _believe_ `lsp-metals` should just pick up Metals being on your path and everything should ™️ work.

**Comment by BloomnDoom** [comment]
Yep it works now. I just had to add a path to `~/.local/share/coursier/bin` first and then followed your steps. Thanks a lot!
