### ISSUE TITLE
VSCode Metals quickhelp doesnt implement methods

### ISSUE THREAD

**Issue by yadavan88** [scalameta/metals#3877]
### Describe the bug

The quickhelp suggestions in vscode with metals doesn't work. 

Steps to reproduce:
1. Create a small object extending IOApp.Simple in cats effect
2. It will show compilation error since run() is not implemented
3. Click on the bulb icon and then click on "implement all members"
4. Nothing happens

### Expected behavior

It should implement the _run()_ method in this case

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.4

### Extra context or search terms

Scala Version: 3.1.2
Bloop : v1.5.0
Java: AdoptOpenJDK 8
Metals Server version: 0.11.4

Screenshot Below:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/9131956/165690570-acb3899f-3a1d-4f64-a96d-21ccbbe51ed1.png">

**Comment by tanishiking** [comment]
@yadavan88 Thank you for reporting! Unfortunately, this feature is not yet available in Scala3 https://github.com/scalameta/metals/issues/1692 (Maybe we shouldn't show a CodeAction in Scala3 because it's confusing).
However, we are working on this feature, stay tuned!

**Comment by tanishiking** [comment]
I opened an issue not to show a quick help if the code action is not available https://github.com/scalameta/metals/issues/3877

**Comment by yadavan88** [comment]
@tanishiking Thank you very much for such a quick response.

**Comment by tanishiking** [comment]
Let me close this issue for https://github.com/scalameta/metals/issues/3878 and https://github.com/scalameta/metals/issues/1692
Again, thank you very much for reporting!
