### ISSUE TITLE
Metals does not get initialized with Cuda text

### ISSUE THREAD

**Issue by BloomnDoom** [scalameta/metals#3902]
### Describe the bug

I installed metals through coursier and then tried initializing it with cuda text, however i get this error message when opening up a file

`ReadLoopError: LSP: Scala - [Errno 10] No child processes`

I linked the path to metals for the setup of the lsp server, the path is

 `C:\Users\User\AppData\Local\Coursier\data\bin\metals.bat`

### Operating system

Windows

### Editor/Extension

Other

### Version of Metals

v0.11.5

**Comment by tanishiking** [comment]
@BloomnDoom Thank you for reporting!
Unfortunately, Metals doesn't officially support [CudaText](https://cudatext.github.io/), and it may take some more steps to run Metals on CudaText. [Integrating a new editor](https://scalameta.org/metals/docs/integrations/new-editor) page of the Metals document may help.

**Comment by BloomnDoom** [comment]
I'll check that out, thanks!

**Comment by tanishiking** [comment]
If you have any questions in the document, don't hesitate to create another issue :)
