### ISSUE TITLE
Migrate to single JDK 17 to be used by Metals

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3923]
Allowing the use of a lot of different JDK for the metals server causes more jobs to having to be run but also, but also causing issues with the Eclipse libraries already only on JDK 11 and doesn't allow to use any new features from new JDK versions.

I think we should do have a separate project JDK that would be use for running any of the builds and at the start also with Bloop.

We could follow a couple of steps:
1. Download our own binary for Metals JDK 17 and decouple javaHome (maybe rename the description)
2. Change the plugins for generating Bloop configuration to add the proper release flags to make sure it's run with a proper version.
3. Automatically set javaHome in Bloop to be the same JDK 17 as Metals uses or alternatively make Bloop also download it's own JDK.

Without the 1. step we cannot even deprecate JDK 8 since project requiring it would just stop working.

**Comment by alexarchambault** [comment]
Don't know if that can help, but you may want to download those using coursier. That way, those JVMs would be the same as the Scala CLI one, if you default to the same JVM as Scala CLI (currently `temurin:17`).

Using the coursier CLI, you can get the Java home with
```text
$ cs java-home --jvm temurin:17
```

Using the latest coursier-interface, you can get it with
```scala
val jvmManager = coursierapi.JvmManager.create()
val javaHome = jvmManager.get("temurin:17")
``` 

That said, if you use the native `cs` launcher from the client extension say, it's going to be a problem on platforms that don't have a `cs` binary (right now, it only supports Linux / macOS / Windows on x86_64, and Linux on aarch64), but it seems it might not be any worse than with jabba that you are using right now.

**Comment by kasiaMarek** [comment]
To do list:
- [ ] download JDK for Metals when needed (client side) (https://github.com/scalameta/metals-vscode/pull/1452)
- [ ] use user config java home for build server (or in case of Bloop as project's Java) (https://github.com/scalameta/metals/pull/6204)
- [ ] add proper `-release` flags for pc to offer correct completions (https://github.com/scalameta/metals/pull/6204)
- [ ] add info on project's Java version to doctor (https://github.com/scalameta/metals/pull/6226)
- [ ] make sure Bloop is correctly started with Metals JDK (also that it's properly updated)
- [ ] docs: add docs on project's java version vs Metals java
- [ ] chore: delete JDK 8 from CI and delete all JDK 8 specific conditions in tests

**Comment by kasiaMarek** [comment]
Closing this as completed.
