### ISSUE TITLE
Add installation instructions for Emacs

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#393]
I would love to update the website to document the installation instructions for Emacs using lsp-scala (https://github.com/rossabaker/lsp-scala/). I've been planning to do this for awhile but I have limited experience with Emacs so I got stuck on my first attempt and never got around to finish it.

cc/ @rossabaker

**Comment by olafurpg** [comment]
Would someone be able to help out with this? I've spent a couple hours trying to get lsp-scala working on my computer but I've never used Emacs before so it's all new to me.

- docs on updating Metals website https://scalameta.org/metals/docs/contributors/updating-website.html
- it would be great to have a screenshot/gif of Metals running inside Emacs
- we can use [`vim.md`](https://github.com/scalameta/metals/blob/cee1890f5bc73d0481b0181a085c42e87655f657/docs/editors/vim.md) as a base template
- lsp-scala instructions: https://github.com/rossabaker/lsp-scala/
 
The benefit of documenting the Emacs installation on the Metals website is that version numbers for generating the `metals-emacs` binary will stay up-to-date as new releases are published.

**Comment by olafurpg** [comment]
cc/ @coreyoconnor

**Comment by olafurpg** [comment]
Alternatively, if someone can give me a pointers on how to get started from a completely clean `~/.emacs.d` then I'd love to give it another try myself. I struggled most with installing packages.

**Comment by fommil** [comment]
I wrote extensive Learning Emacs docs over at

- http://ensime.github.io/editors/emacs/learning/
- http://ensime.github.io/editors/emacs/hacks/

that you may wish to use for your own benefit.

**Comment by olafurpg** [comment]
@fommil thanks, I got it working!

**Comment by olafurpg** [comment]
Whoops, fat thumb closed the issue while I was writing a response.

**Comment by rossabaker** [comment]
It's a little more burdensome than it ought to be because the package isn't in MELPA yet, like its dependency. I did some of the ceremonial linting to get it up to standard. I'll try to submit it to MELPA today.

**Comment by olafurpg** [comment]
I like how Emacs highlights the line that you navigate to

![2018-12-10 12 27 47](https://user-images.githubusercontent.com/1408093/49730028-6627eb00-fc77-11e8-822e-136c0b445db8.gif)

I'll open a PR soon updating the docs. The integration is not perfect yet, I can't get lsp-mode to send the correct `shutdown` and `exit` hooks. It also sends `textDocument/hover` requests even if Metals does not declare a hover provider. Those can be improved on in the future.

**Comment by olafurpg** [comment]
@rossabaker would it be possible to enable the hook by default?
```el
(add-hook 'scala-mode-hook #'lsp-scala-enable)
```
I'm not aware of another editor that require enabling the language server on a file-basis. It's more common to disable/enable the LSP package on per-project.

**Comment by fommil** [comment]
@rossabaker what do you mean "like its dependency"? https://melpa.org/#/lsp-mode

**Comment by fommil** [comment]
@olafurpg btw, just so you know, the red squiggly support is already provided, (non-ensime) emacs by sbt's lsp and/or flycheck. I suspect the docs may need to touch on disabling things or everybody is going to get conflicts and perf regressions. Spacemacs often enables stuff by default.
