### ISSUE TITLE
Out of bounds cursor position given when creating new empty scala file

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3937]
### Describe the bug

When a user attempts to create a new scala file using the `scala-file` id (Empty file), the `metals-goto-location` that is returned via the `metals/executeClientCommand` has a position that is out of bounds in the file that was actually created. This throws errors in some clients since the position is not valid. Here is an example of what a `nvim-metals` user sees:

```
Error executing vim.schedule lua callback: ...vim/HEAD-95580f3/share/nvim/runtime/lua/vim/lsp/util.lua:1047: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...vim/HEAD-95580f3/share/nvim/runtime/lua/vim/lsp/util.lua:1047: in function 'jump_to_location'
        ...te/pack/packer/start/nvim-metals/lua/metals/handlers.lua:45: in function 'handler'
        ...r/neovim/HEAD-95580f3/share/nvim/runtime/lua/vim/lsp.lua:824: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Here is the full trace:
```
[Trace - 10:55:54 AM] Received request 'workspace/executeCommand - (5)'
Params: {
  "command": "metals.new-scala-file",
  "arguments": [
    null,
    null,
    null
  ]
}


[Trace - 10:55:54 AM] Sending request 'metals/quickPick - (1)'
Params: {
  "items": [
    {
      "id": "scala-file",
      "label": "Empty file"
    },
    {
      "id": "scala-class",
      "label": "Class"
    },
    {
      "id": "scala-case-class",
      "label": "Case Class"
    },
    {
      "id": "scala-object",
      "label": "Object"
    },
    {
      "id": "scala-trait",
      "label": "Trait"
    },
    {
      "id": "scala-package-object",
      "label": "Package Object"
    },
    {
      "id": "scala-worksheet",
      "label": "Worksheet"
    },
    {
      "id": "ammonite-script",
      "label": "Ammonite Script"
    },
    {
      "id": "scala-enum",
      "label": "Enum"
    }
  ],
  "placeHolder": "Select the kind of file to create"
}


[Trace - 10:55:55 AM] Received response 'metals/quickPick - (1)' in 1200ms
Result: {
  "itemId": "scala-file"
}
Error: null


[Trace - 10:55:55 AM] Sending request 'metals/inputBox - (2)'
Params: {
  "prompt": "Enter the name for the new Empty file"
}


[Trace - 10:55:59 AM] Received response 'metals/inputBox - (2)' in 3946ms
Result: {
  "value": "Foo"
}
Error: null


[Trace - 10:55:59 AM] Sending notification 'metals/executeClientCommand'
Params: {
  "command": "metals-goto-location",
  "arguments": [
    {
      "uri": "file:///Users/ckipp/Documents/scala-workspace/sanity/Sanity/src/example/Foo.scala",
      "range": {
        "start": {
          "line": 2,
          "character": 0
        },
        "end": {
          "line": 2,
          "character": 0
        }
      },
      "otherWindow": false
    }
  ]
}
```

Behind the scenes the file that was created has the following:

```scala
package example
 
```

And notice the range that is in the c

```
"range": {
        "start": {
          "line": 2,
          "character": 0
        },
        "end": {
          "line": 2,
          "character": 0
        }
      }
```

Per the spec these are 0 based meaning that it will be translated to line 3 by the client, which doesn't exist in the file that was created.

### Expected behavior

I'd expect the position to be a valid existing position in the `metals-goto-location`.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.5+88-1cb02ef8-SNAPSHOT	

### Extra context or search terms

Sort of a tangent, but thinking about how these files are created, they are done behind the scenes this is done with an internal method `writeText`:
(https://github.com/scalameta/metals/blob/1cb02ef8cc9df3f78aa03ee61940ec777ca494ae/metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala#L524-L558) which  means that it's not done with LSP. I wonder if instead doing a [`workspaceEdit`]https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit would be a better choice since there is a `documentChanges` field that you can do a `CreateFile` with. Might be something worth exploring.

**Comment by tgodzik** [comment]
Thanks for reporting, I think VS Code might be falling back to the end of the file in this case. This should be quick to check out and fix, anyone wants to take a look?

**Comment by ckipp01** [comment]
_Interesting_, so looking at VS Code gave me a bit more insight. Looking at the `textDocument/didOpen` I do actually see there are `\n\n` so in theory, there should be 3 lines, however in Neovim for me it's only showing the two and the last newline isn't there. I think this is an issue on the client side, sorry for the noise!
