### ISSUE TITLE
[Scala 3] Add scaladoc completion

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3955]
**Is your feature request related to a problem? Please describe.**
In Scala 2 it's possible to add a completion that will create a scaladoc stub when `/*` is completed before a method/class . It would be good to have the same for Scala 3.

**Describe the solution you'd like**
The potential solutions should take a look at `ScaladocCompletions.scala` and related tests to see what needs to be supported but in general we would need:
- completion that will create s scaladoc stub should appear when the cursor is after `/*` and before a method, class, trait etc.
- it should also be possible to complete simple multiline comment when nothing exists after `/*`
- 
**Describe alternatives you've considered**
Write it manually.

**Additional context**
This is part of the effort to create proper tooling for Scala 3.

**Search terms**:
scaladoc comments completions completions scala3

**Comment by tanishiking** [comment]
I'm on it :)
