### ISSUE TITLE
VSCode cannot connect to bloop

### ISSUE THREAD

**Issue by tSte** [scalameta/metals#396]
I have VSC with this extension and running `Metals: Import build` ends up with this:
```
[0m[31m[E][0m Not a DAG, cycle detected in root -> gatling -> root 
fo [0m running 'sbt metalsEnable bloopInstall'
[34minfo [0m [info] Loading settings for project global-plugins from idea.sbt,metals.sbt ...
[34minfo [0m [info] Loading global plugins from /home/myUserName/.sbt/1.0/plugins
[34minfo [0m [info] Loading settings for project api-build from plugins.sbt ...
[34minfo [0m [info] Loading project definition from /home/myUserName/myApiProject/project
[34minfo [0m [success] Generated .bloop/api-build.json
[34minfo [0m [success] Total time: 6 s, completed Dec 10, 2018 2:56:19 PM
[34minfo [0m [info] Loading settings for project root from build.sbt ...
[34minfo [0m [info] Set current project to my-api-project (in build file:/home/myUserName/myApiProject/)
[34minfo [0m [info] Set current project to my-api-project (in build file:/home/myUserName/myApiProject/)
[34minfo [0m [info] semanticdb-scalac is enabled
[34minfo [0m [success] Generated .bloop/slickCodegen.json
[34minfo [0m [success] Generated .bloop/slickCodegen-test.json
[34minfo [0m [success] Generated .bloop/root-test.json
[34minfo [0m [success] Generated .bloop/root.json
[34minfo [0m [success] Generated .bloop/gatling.json
[34minfo [0m [success] Generated .bloop/gatling-test.json
[34minfo [0m [success] Total time: 16 s, completed Dec 10, 2018 2:56:40 PM
[34minfo [0m sbt exit: 0
[34minfo [0m time: Ran 'sbt bloopInstall' in 39s
[34minfo [0m running embedded 'bloop bsp --protocol local --socket /tmp/bsp6559789676998484745/1axt3poksxgc.socket'
[34minfo [0m bloop exit: 1
[31merror[0m Failed to connect with build server, no functionality will work.
scala.meta.internal.metals.BloopServers$NoResponse$: no response: bloop bsp
	at scala.meta.internal.metals.BloopServers.NoResponse$lzycompute$1(BloopServers.scala:302)
	at scala.meta.internal.metals.BloopServers.NoResponse(BloopServers.scala:302)
	at scala.meta.internal.metals.BloopServers.$anonfun$callBloopMain$1(BloopServers.scala:207)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I am on ArchLinux `4.19.8.a-1`, with VSC `1.29.1`.
Any idea what can cause this / how to resolve it? Thanks!

**Comment by olafurpg** [comment]
Thanks for reporting! Can see check if jars for the `bloop-frontend` module have downloaded to `~/.cache/coursier`? Do the logs contain the following message "Failed to classload bloop"?

A possible workaround might be to install bloop directly https://scalacenter.github.io/bloop/setup

**Comment by tSte** [comment]
It doesn't contain that message (at least I can't see it - I updated logs, pls, have a look). However I don't seem to have any `bloop`-related stuff in `~/.cache/coursier`. Do you suggest to manually install `bloop`?

**Comment by olafurpg** [comment]
I recommend installing Bloop with the instructions here https://scalacenter.github.io/bloop/setup It could be outdated on AUR

**Comment by tSte** [comment]
Nope, the same result. I even enabled bloop as service (it is active/running). Can this be caused by some access rights / restrictions of VSC to `bloop`? Because if I run `bloop bsp --protocol local --socket /tmp/bsp6246301264379338964/gn6harancksh.socket` from terminal, it seems to be working (or at least there are no exceptions thrown).

**Comment by olafurpg** [comment]
Are there any `.bloop/*.json` files? The logs report a warning:

```
�[0m�[31m[E]�[0m Not a DAG, cycle detected in root -> gatling -> root 
```

**Comment by tSte** [comment]
In `$HOME`? No. But I guess you aren't asking about this one.
In project's root `.bloop` dir. and in root's `.project/.bloop`? Yes. There are several `.json` and `-test.json` files in both. However `classes` and `test-classes` directories are all empty.

**Comment by tSte** [comment]
Nope, still embedded

**Comment by olafurpg** [comment]
That brings us a bit closer to see what's going on. What python do you have installed on your machine?

**Comment by tSte** [comment]
```
➜  ~ python
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831] on linux
```

**Comment by olafurpg** [comment]
Some thoughts:

- I'm surprised it doesn't pick up the installed bloop and continues to use the embedded more
- `bloop exit: 1` in the logs indicates that the `bloop bsp` command exited immediately, that log should appear when the server shuts down

Something is not going as expected, but I'm afraid it's difficult to debug without being able to reproduce.

**Comment by gabro** [comment]
@tSte can you check whether you have another version of the bloop sbt plugin installed anywhere? Either globally or in your project?

I couldn't understand why it was running the embedded version on my machine, and that turned out to be the issue.

**Comment by olafurpg** [comment]
@gabro This is likely unrelated to the sbt plugin, this error happens while establishing a bsp connection

**Comment by tSte** [comment]
@gabro I don't seem to have `bloop` in global plugins, I have it in project:
```
sbt plugins | grep bloop
bloop.integrations.sbt.BloopPlugin: enabled in root
```

**Comment by gabro** [comment]
> @gabro This is likely unrelated to the sbt plugin, this error happens while establishing a bsp connection

True, however if you have `.bloop` files generated by an older version of the plugin, when running this check

https://github.com/scalameta/metals/blob/07079ba80fb5206a4916f1263883e72fbbc83bfd/metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala#L284

then the process will throw an error and Metals will fallback to the embedded version.

Am I reading this wrong?

@tSte which version of the bloop plugin do you have on your project?

**Comment by olafurpg** [comment]
@tSte it could be that the root of the problem is
```
Not a DAG, cycle detected in root -> gatling -> root 
```

Can try to install bloop based on https://scalacenter.github.io/bloop/ (not AUR), verify that `bloop about` shows `v1.1.1` then try to run `sbt bloopInstall`. See if that works before trying to import the project with Metals. You might want to remove any `.bloop/` directories first.

**Comment by tSte** [comment]
@gabro can bloop versions differ? I sort-of doubt that I had bloop installed before, so it had to be addedby metals (I didn't install bloop before)

@olafurpg I have it installed via `wget` and it's version is `1.1.1`. `sbt bloopInstall` will successfully generate `.json` files and exits with 0.

I tried to create custom `bloop.py` and execute it in project's directory (since this seems to be what `bloopCommandLineIsInstalled` is doing). I am not sure if I should/shouldn't execute it in project's directory or somewhere else, but it exits with:
```
python bloop.py help
[E] Not a DAG, cycle detected in root -> gatling -> root 
Type `--nailgun-help` for help on the Nailgun CLI tool.
```
Does it help?

**Comment by jvican** [comment]
@tSte Could you show us your build definition? That's a fatal error that should never happen (it happens because `root` depends on `gatling` and `gatling` depends on `root`, creating a cycle; you can see that in the `dependencies` field of the JSON files).
  
A way to move forward and dignose if that's the real problem is to remove `root` from the `dependencies` in the configuration file of `gatling`, which you can find in `.bloop/gatling.json`.

**Comment by gabro** [comment]
@tSte I'm asking because Metals doesn't unconditionally add sbt-bloop to your build. It does only when `METALS_ENABLED=true`, which happens during build import.

If you see the `sbt-bloop` plugin installed in your build when launching sbt normally from your command line, it's been installed by something other than Metals.

**Comment by olafurpg** [comment]
@tSte thanks for the information, it seems the problem lies in bloop

- `sbt bloopInstall` succeeds with exit code 0
- `bloop help` and `bloop bsp` fail due  to cyclic errors in the build definition

There is not much we can do on the Metals side to fix this. I recommend trying to remove the cyclic definition in the sbt build, or you can report an issue https://github.com/scalacenter/bloop

**Comment by tSte** [comment]
@jvican Unfortunately, I can't... However I can tell you that `root` depends on two projects (none of them are `gatling`) and `gatling` depends on `root`. That's all calls of `.dependsOn` in my build. However it's truth that `gatling.json` does have `"dependencies": [ "root" ]` and vice-versa...

**Comment by olafurpg** [comment]
Seems you can only transfer issues within the same organization

**Comment by jvican** [comment]
> However I can tell you that root depends on two projects (none of them are gatling) and gatling depends on root.
  
Is `root` depending on gatling transitively in your sbt build?
  
I recommend doing `show $PROJECT/projectDependencies` in the sbt shell for eveyr dependendency of `gatling` to find if your build does indeed have a cyclic dependency. Note that `projectDependendencies` is not transitive so you need to run it for every project dependency manually.
  
If the dependency is not there, I suggest you find a reproduction and create a ticket in scalacenter/bloop's issue tracker.

**Comment by tSte** [comment]
@jvican I found why... `root` may have `dependsOn` other two projects, but it also has `aggregate` on gatling...

**Comment by jvican** [comment]
>  I found why... root may dependsOn other two projects, but it also has aggregate on gatling...
  
Yeah, that doesn't make a lot of sense :smile: Remove the aggregate and it will work.

**Comment by tSte** [comment]
@jvican yeah, it seems it will... but why is this a problem? Because `aggregate` and `dependsOn` is not the same. And I'd like to keep it that way (I want to compile `gatling` when compiling `root` too).

Note: my knowledge of SBT is limited...

**Comment by olafurpg** [comment]
@jvican has opened a PR https://github.com/scalacenter/bloop/pull/758 improving the Bloop error handling for cyclic dependencies in build definitions so issues like this will be easier to track down in the future.
