### ISSUE TITLE
Content of global Bloop JSON is not escaped

### ISSUE THREAD

**Issue by mbovel** [scalameta/metals#3968]
### Describe the bug

Discovered with a student that had set a path containing `\` characters. This resulted in an invalid JSON file.

https://github.com/scalameta/metals/blob/9378da0ffdc7e53d50abccbb84500ce40f3b2a87/metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala#L151

### Expected behavior

Should escape content of strings.

Could we use a real JSON writer for more robustness?

### Version of Metals

v0.11.5

**Comment by mbovel** [comment]
cc @adpi2

**Comment by dos65** [comment]
@mbovel Thanks for reporting!

We can switch this thing on ujson
