### ISSUE TITLE
Implement textDocument/documentSymbol

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#398]
Revamp of #93 

https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol

The document symbol request is sent from the client to the server to return a flat list of all symbols found in a given text document. Neither the symbol’s location range nor the symbol’s container name should be used to infer a hierarchy.

```typescript
interface DocumentSymbolParams {
	/**
	 * The text document.
	 */
	textDocument: TextDocumentIdentifier;
}
```

Document symbol can be implemented in a purely syntactic fashion.

It should handle non-parsing buffers by returning the last known `documentSymbol` information.

Example in VSCode:

![3c8e6e88-6d29-401c-8851-882f7bc06b94](https://user-images.githubusercontent.com/691940/49751649-33e5b000-fcae-11e8-9ba4-3431b5fa6377.jpeg)

**Comment by olafurpg** [comment]
Fixed in #424 🎉
