### ISSUE TITLE
'Implement all members' quick fix inserts method stubs before self type

### ISSUE THREAD

**Issue by robmwalsh** [scalameta/metals#3994]
**Describe the bug**
'Implement all members' quick fix inserts method stubs before self type.

**To Reproduce** Steps to reproduce the behavior:

1. Add a new abstract method to a trait or whatever which has a concrete subtype
2. Compilation of concrete class correctly fails (blah needs to be abstract, missing implementation of new method)
3. Add a self type to the concrete class
4. Try and use the quick fix to 'Implement all members'
5. Behold! New method stubs! A handy feature... but a self type needs to be the first statement :'(

**Expected behavior**
Self type should still be the first statement

**Screenshots**
Setup:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/30517573/172034470-3ca956e0-abc8-4f1c-b07b-68d590c678b4.png">
How very helpful! Thankyou, little lightbulb!
<img width="260" alt="image" src="https://user-images.githubusercontent.com/30517573/172034479-4f736461-fe70-400d-8b6c-ac3cf68fb2f9.png">
Error :( :
<img width="791" alt="image" src="https://user-images.githubusercontent.com/30517573/172034485-ca8e5767-5a16-4044-b1e9-e69079287038.png">
Expected:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/30517573/172034497-58234d27-26f2-4094-9d12-42153043d2fe.png">

**Installation:**

- Operating system: Windows using WSL remote
- VSCode version:
- 1.67.2
<img width="285" alt="image" src="https://user-images.githubusercontent.com/30517573/172034543-fdaf2a11-4218-4749-a37c-48078131f13e.png">

- VSCode extension version:
v1.17.0
- Metals version: (found in VSCode settings, under `metals.serverVersion`)
0.11.6

**Additional context**

**Search terms**

**Comment by riiswa** [comment]
Hey, I'm on it!

**Comment by tanishiking** [comment]
@riiswa Awesome! If you have any questions on anything (project setup, about codebase, testing, whatever), feel free to ask questions :)

**Comment by ckipp01** [comment]
Closed via https://github.com/scalameta/metals/pull/4009

**Comment by robmwalsh** [comment]
I'm still getting this happening on scala 3. Should I create another issue or should this one be reopened?
