### ISSUE TITLE
Empty parentheses added to completed extension method

### ISSUE THREAD

**Issue by prolativ** [scalameta/metals#4004]
### Describe the bug

```scala
extension (s: String)
  def foo = 0
val bar = "abc".fo
```
Invoking code completion on `"abc".fo` results in `"abc".foo()` (which won't compile).

### Expected behavior

The code should be completed with just `"abc".foo` without following parentheses.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.6+48-26045a93-SNAPSHOT

**Comment by prolativ** [comment]
A probably related issue:
```scala
extension (s: String)
  def bar = 0
  def bax() = 0
  def baz()() = 0
val bar = "abc".ba
```
Here the suggested completions for `"abc".ba` are all displayed as parameterless methods returning an `Int`:
```scala
bar: Int
bax: Int
baz: Int
```
but they should be displayed as
```scala
bar: Int
bax(): Int
baz()(): Int
```

**Comment by riiswa** [comment]
Hi, I think I have fixed the bug I am now trying to write a test. Is this the right file: `metals/tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala` ?

**Comment by ckipp01** [comment]
> Hi, I think I have fixed the bug I am now trying to write a test. Is this the right file: `metals/tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala` ?

Hey @riiswa, that specific suite is for the completions related to the `match` completion functionality. Check out the general `CompletionSuite.scala`, and you should be able to stick it in there. Also note how the `compat` param works as you might want different behavior with Scala 2 or Scala 3.

**Comment by tgodzik** [comment]
It's probably bet to add it to `CompletionSnippetSuite` with a `tag(IgnoreScala2)` as the extension methods don't work for Scala 2.
