### ISSUE TITLE
Don't import builds older than sbt 0.13.17

### ISSUE THREAD

**Issue by rrodseth** [scalameta/metals#401]
Submitting as requested on Gitter.
I got the error below while importing an sbt file in VS Code after installing Metals:
Turns out the project I opened did have `sbt.version=0.13.8` in `build.properties` After changing that to `1.1.6` I can  import.
>>>
/Users/rrodseth/.sbt/0.13/plugins/metals.sbt:12: error: not found: value pluginCrossBuild
    val sbtVersion = Keys.sbtBinaryVersion.in(pluginCrossBuild).value
<<<

**Comment by olafurpg** [comment]
Thanks for reporting! It's expected that Metals doesn't work with sbt 0.13.8, but it works with 0.13.17 so it's not necessary to upgrade to sbt v1 to work around the issue.

**Comment by olafurpg** [comment]
Reopened ticket to be about improving the error message for builds older than 0.13.17.
