### ISSUE TITLE
vscode-metals doesn't work for  Apache Spark

### ISSUE THREAD

**Issue by jievince** [scalameta/metals#4023]
### Describe the bug

`Go to definition` doesn't work for https://github.com/apache/spark
![image](https://user-images.githubusercontent.com/38901892/173292239-de1af070-de77-48e9-9189-cf9459488892.png)

![image](https://user-images.githubusercontent.com/38901892/173292282-2c5b08ac-4fdf-4ff2-9d0d-1d662d65a533.png)

The log: 
```
Java home: /usr/lib/jvm/java-11-openjdk-amd64
Metals version: 0.11.6
2022.06.13 14:11:02 INFO  logging to file /home/jie.wang/spark/.metals/metals.log
2022.06.13 14:11:02 INFO  Started: Metals version 0.11.6 in workspace '/home/jie.wang/spark' for client Visual Studio Code 1.68.0.
2022.06.13 14:11:02 INFO  time: initialize in 0.55s
Initializing Scala Debugger
2022.06.13 14:11:02 INFO  Flyway Community Edition 8.5.10 by Redgate
2022.06.13 14:11:02 INFO  See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.10
2022.06.13 14:11:02 INFO  
2022.06.13 14:11:02 INFO  Database: jdbc:h2:file:/home/jie.wang/spark/.metals/metals (H2 2.1)
2022.06.13 14:11:02 WARN  Flyway upgrade recommended: H2 2.1.212 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.1.210.
2022.06.13 14:11:02 INFO  Successfully validated 3 migrations (execution time 00:00.021s)
2022.06.13 14:11:02 INFO  Current version of schema "PUBLIC": 3
2022.06.13 14:11:02 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2022.06.13 14:11:02 INFO  Attempting to connect to the build server...
2022.06.13 14:11:02 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/jie.wang/spark/.metals/bsp.trace.json or /home/jie.wang/.cache/metals/bsp.trace.json
2022.06.13 14:11:02 INFO  Attempting to connect to the build server...
2022.06.13 14:11:02 INFO  Attempting to connect to the build server...
2022.06.13 14:11:02 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/jie.wang/spark/project/.metals/bsp.trace.json or /home/jie.wang/.cache/metals/bsp.trace.json
2022.06.13 14:11:03 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/jie.wang/spark/project/project/.metals/bsp.trace.json or /home/jie.wang/.cache/metals/bsp.trace.json
2022.06.13 14:11:02 INFO  skipping build import with status 'Installed'
2022.06.13 14:11:03 INFO  time: Connected to build server in 0.23s
2022.06.13 14:11:03 INFO  Connected to Build server: Bloop v1.5.0-18-003e6c7b
2022.06.13 14:11:07 INFO  no build target found for /home/jie.wang/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala. Using presentation compiler with project's scala-library version: 2.12.15
2022.06.13 14:11:08 INFO  time: indexed workspace in 4.74s
2022.06.13 14:11:08 WARN  no build target for: /home/jie.wang/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala
2022.06.13 14:11:08 WARN  no build target for: /home/jie.wang/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala
2022.06.13 14:11:11 INFO  Disconnecting from Bloop session...
2022.06.13 14:11:11 INFO  time: code lens generation in 1.67s
2022.06.13 14:11:11 INFO  time: code lens generation in 5.37s
2022.06.13 14:11:11 INFO  time: code lens generation in 2.8s
2022.06.13 14:11:13 ERROR timeout: build server 'bloop' during shutdown
2022.06.13 14:11:13 ERROR timeout: build server 'bloop' during shutdown
2022.06.13 14:11:13 ERROR timeout: build server 'bloop' during shutdown
2022.06.13 14:11:13 INFO  Attempting to connect to the build server...
2022.06.13 14:11:14 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/jie.wang/spark/.metals/bsp.trace.json or /home/jie.wang/.cache/metals/bsp.trace.json
2022.06.13 14:11:14 INFO  Attempting to connect to the build server...
2022.06.13 14:11:14 INFO  Attempting to connect to the build server...
2022.06.13 14:11:14 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/jie.wang/spark/project/project/.metals/bsp.trace.json or /home/jie.wang/.cache/metals/bsp.trace.json
2022.06.13 14:11:15 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/jie.wang/spark/project/.metals/bsp.trace.json or /home/jie.wang/.cache/metals/bsp.trace.json
2022.06.13 14:11:14 INFO  time: Connected to build server in 1.96s
2022.06.13 14:11:14 INFO  Connected to Build server: Bloop v1.5.0-18-003e6c7b
2022.06.13 14:11:14 INFO  time: Imported build in 0.13s
2022.06.13 14:11:17 INFO  time: indexed workspace in 2.67s
2022.06.13 14:11:17 WARN  no build target for: /home/jie.wang/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala
2022.06.13 14:11:18 INFO  no build target found for /home/jie.wang/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala. Using presentation compiler with project's scala-library version: 2.12.15
2022.06.13 14:11:18 INFO  time: code lens generation in 2.1s
2022.06.13 14:20:54 WARN  no build target for: /home/jie.wang/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Projection.scala
```

### Expected behavior

`Go to definition` could work well.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.6

**Comment by ckipp01** [comment]
Thanks for the report @jievince. I just tried getting spark set up, and I did hit on a few things at first, which you also may be hitting on, but it's hard to tell without more info from you.

When I first attempted to import it continued to fail since the maven enforcer would fail due to metals by default using an older version of Maven. This is something we should probably update on our side, but this was causing the build import to fail. I believe that is what is happening for you as well since when you try to navigate it doesn't recognzie that the file you're in is part of build target. I'm assuming if you looked at the Metals doctor you'd see no build targets due to the import failing. Do you remember seeing any errors about import failure?

To get around this I just set the Metals Maven Script setting to point towards `build/mvn`. After doing that I re-triggered in import which succeeded and I was then able to get code navigation.

![2022-06-13 09 04 55](https://user-images.githubusercontent.com/13974112/173298677-fc125233-9d7d-41e6-a59c-27d50252e5f4.gif)

Could you also give this a try?

**Comment by jievince** [comment]
![image](https://user-images.githubusercontent.com/38901892/173329266-acf38542-4e34-47e7-ac4e-38fdbb555160.png)
![image](https://user-images.githubusercontent.com/38901892/173330163-ecfdafa2-f93e-44f9-9726-31a3833a1876.png)


Hi @ckipp01 ,  I tried to set the Metals Maven Script setting to point towards build/mvn, and it really works. Thank you!

**Comment by tgodzik** [comment]
The previous warnings might come from the fact that, the Bloop Java Home was set previously and Metals is being run with a different Java version.

We currently try to make sure that both are run with the same one, since that makes sure that you get completions that will always compile.

**Comment by jievince** [comment]
Where to set the bloop java home? I haven't do it.
![image](https://user-images.githubusercontent.com/38901892/173348039-df2f61af-d26b-4168-b475-836723ac5418.png)

**Comment by tgodzik** [comment]
It's the same one as the usual `javaHome`. There was an issue that caused the pop up show even if you had this set properly, but should have been fixed. If you agree to apply and restart, does it show up again?

**Comment by jievince** [comment]
> It's the same one as the usual `javaHome`. There was an issue that caused the pop up show even if you had this set properly, but should have been fixed. If you agree to apply and restart, does it show up again?

It doesn't show up again.

**Comment by boneanxs** [comment]
@jievince @ckipp01 Have you met `Unable to parse configuration of mojo ch.epfl.scala:maven-bloop_2.13:1.5.2:bloopInstall for parameter useZincServer: Cannot find 'useZincServer' in class bloop.integrations.maven.BloopMojo` when building spark? I'm facing this issue using 0.11.9 when building spark3.1.2

**Comment by tgodzik** [comment]
I don't see any `useZincServer` parameter mentioned in https://github.com/davidB/scala-maven-plugin

Does it work if you remove it? What version of maven should be used for spark? You might try some earlier bloop-maven versions :thinking:

**Comment by boneanxs** [comment]
Yea, remove this works, Looks spark also remove this in https://github.com/apache/spark/pull/31647

Thanks for your kind help! @tgodzik
