### ISSUE TITLE
Append parameter names in method for simple types for Scala3

### ISSUE THREAD

**Issue by dgalichet** [scalameta/metals#4059]
### Is your feature request related to a problem? Please describe.

This feature is related to https://github.com/scalameta/metals-feature-requests/issues/184 that proposes to show parameter names for simple types

It could be nice to have a code action to append these parameters directly on the source code (according to @tgodzik ) it should be pretty simple to do)

### Describe the solution you'd like

```scala
def easyMethod(boolParam: Boolean) = ???
easyMethod(true)
```

After invoking code action, the code should be:
```scala
easyMethod(boolParam = true)
```

### Describe alternatives you've considered

the alternative is to show parameter only, without inserting it as described in https://github.com/scalameta/metals-feature-requests/issues/184

### Search terms

named parameters decorations inferred information

**Comment by tanishiking** [comment]
Are you interested in working on Scala3 support @camgraff ? If you're interested in it, let me assign it to you (you don't have to be in rush :)
