### ISSUE TITLE
Don't run `InteractiveDriver.run` every time for the same input

### ISSUE THREAD

**Issue by tanishiking** [scalameta/metals#4060]
### Describe the issue

While I CPU profile using [async-profiler](https://github.com/jvm-profiling-tools/async-profiler/), I realized that Metals (Scala3) invokes `InteractiveDriver.run` quite frequently, especially from `HoverProvider.hover`.

This is because we invoke `InteractiveDriver.run` every time when Metals uses information from presentation compilers.
For example, `HoverProvider.hover` runs `InteractiveDriver.run` for every invocations anyway.
https://github.com/scalameta/metals/blob/eab3df81d3a55445f558c959ee5d2fa24308be82/mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala#L39

It might be a big CPU saver if we don't run `InteractiveDriver.run` if the input is the same (that is likely to happen especially when we're code reading and doing hover or navigations).

### Expected behavior

Here I did a bit of experiment in HoverProvider

```diff
diff --git a/mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala b/mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
index ee590a6c38..60a88de0ac 100644
--- a/mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
+++ b/mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
@@ -26,9 +26,22 @@ import dotty.tools.dotc.interactive.SourceTree
 import dotty.tools.dotc.util.ParsedComment
 import dotty.tools.dotc.util.SourcePosition
 import org.eclipse.lsp4j.Hover
+import java.net.URI
+import dotty.tools.dotc.util.SourceFile
+import scala.collection.concurrent.TrieMap
 
 object HoverProvider:
 
+  val lastCompiled: TrieMap[URI, String] =
+    TrieMap.empty
+
+  def md5(text: String): String =
+    java.security.MessageDigest
+      .getInstance("MD5")
+      .digest(text.getBytes)
+      .map("%02x".format(_))
+      .mkString
+
   def hover(
       params: OffsetParams,
       driver: InteractiveDriver,
@@ -36,7 +49,14 @@ object HoverProvider:
   ): ju.Optional[Hover] =
     val uri = params.uri
     val sourceFile = CompilerInterfaces.toSource(params.uri, params.text)
-    driver.run(uri, sourceFile)
+    val alreadyCompiled = lastCompiled
+      .get(uri)
+      .map(_ == md5(params.text))
+      .getOrElse(false)
+
+    if !alreadyCompiled then
+      driver.run(uri, sourceFile)
+      lastCompiled.put(uri, md5(params.text))
     given ctx: Context = driver.currentCtx
     val pos = driver.sourcePosition(params)
@@ -57,7 +77,7 @@ object HoverProvider:
     then ju.Optional.empty()
     else
       val skipCheckOnName =
-        !pos.isPoint // don't check isHoveringOnName for RangeHover
+        !pos.isPoint // don't check isHoveringOnName for RangeHover aaa
       MetalsInteractive.enclosingSymbolsWithExpressionType(
         enclosing,
         pos,
```

## CPU usage
I checked the CPU usage while hovering many symbols in a file without changing any contents.
Each spike represents the process against hover requests (ignore the big spikes, they're other things). Obviously, we use a lot less CPU.

### before 
<img width="619" alt="Screen Shot 2022-06-23 at 20 04 28" src="https://user-images.githubusercontent.com/9353584/175286282-545d6313-ad6d-4700-b044-39a8f4f236e5.png">

### after
 
<img width="614" alt="Screen Shot 2022-06-23 at 20 04 37" src="https://user-images.githubusercontent.com/9353584/175286420-10dfcd23-5dea-49a8-8a1e-46365fd36486.png">

---

This is still a rough prototype, but it would be a good way to optimize Metals in Scala3 :)
Do you have any concerns?

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.7-SNAPSHOT

### Extra context or search terms

CPU / optimize

**Comment by tgodzik** [comment]
I think that is a great idea! I remember @odersky talking about some caching inside the compiler, so maybe we could somehow move it there? We can open up a discussion on the dotty repo also.

**Comment by dos65** [comment]
in general it's good idea. I would only notice that there might one case when it might work incorrect - several files and non-saved changes.
For example:
```scala
// initial
// src/main/scala/A.scala
trait A {
  def foo: Int
}
// src/main/scala/B.scala
object B:
  val a: A = _
  val v = a.foo // call hover on `v` - should show `Int`
  
// then do changes in A.scala but don't save it
// src/main/scala/A.scala
trait A {
  def foo: String
}
// src/main/scala/B.scala
object B:
  val a: A = _
  val v@@ = a.foo // hypothetically, right now it might return either `String` or `Int`
                             // it depends if there were any interaction with PC(InteractiveDriver.run) from A.scala before switching to B.scala 
                             // but if there will be a cache it will be `Int`
```

**Comment by tanishiking** [comment]
@dos65  Yeah, you're right, if `A.scala` depends on `B.scala`, and we changed `B.scala`, InteractiveDriver has to compiler `A.scala` again to obtain the latest information of the source code...

**Comment by dos65** [comment]
@tanishiking 
btw, I just realized that it's connected to signature compilation that I'm working on.
I haven't experimented with this thing yet (need to unblock bloop first) but my plan was to introduce some incremental compilation/invalidation to `PresentationCompiler`. So probably, the case I mentioned will be possible to fix after the infrastructure for signature compilation appears.

**Comment by tgodzik** [comment]
We will also probably take a look at it in the compiler.

**Comment by tanishiking** [comment]
I tried to experiment, maybe we can cache invalidate by checking the combination of file content and `runId` https://github.com/scalameta/metals/pull/4100/ 

However, I realized that this work only if we edit files only in Metals. For example, if we edit `A.scala` outside of Metals (in the @dos65's setting https://github.com/scalameta/metals/issues/4060#issuecomment-1167133998) (this often happens, e.g., `git switch other-branch`), `B.scala` won't be updated.

**We need to know if there are changes on the classpath.** Maybe I will ask is there a good way to check the changes on the classpath in the compiler to the Scala3 team later.

Related: https://github.com/lampepfl/dotty/blob/dc5a9a4e5397f31ff21d591ac7d156de4e399967/compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala#L67-L73

**Comment by tanishiking** [comment]
Closing for https://github.com/scalameta/metals/pull/4225
