### ISSUE TITLE
Scala 3 "implement all members" adds them above the class

### ISSUE THREAD

**Issue by armanbilge** [scalameta/metals#4062]
### Describe the bug

You can see the output of running "implement all members" action on `InMemoryNodeDb` right above it! 😀 

https://github.com/armanbilge/cheshire/blob/069da8e64aab69894330b7bec24cf852b5f531b8/treedb/src/main/scala/cheshire/treedb/InMemoryNodeDb.scala#L33

Should be easy to reproduce by deleting these lines and running the action yourself.
https://github.com/armanbilge/cheshire/blob/069da8e64aab69894330b7bec24cf852b5f531b8/treedb/src/main/scala/cheshire/treedb/InMemoryNodeDb.scala#L19-L30

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

0.11.6+141-a71fe7ab-SNAPSHOT

**Comment by tanishiking** [comment]
Thank you for reporting!
I could reproduce it with

```scala
trait NodeDb[F[_]]:
  type N

  extension (node: N)
    def parent: F[Option[N]]
    def leftChild: F[Option[N]]
    def rightChild: F[Option[N]]

private final class InMemoryNodeDb[F[_]] extends NodeDb[F]
```

and we got

```scala
trait NodeDb[F[_]]:
  type N

  extension (node: N)
    def parent: F[Option[N]]
    def leftChild: F[Option[N]]
    def rightChild: F[Option[N]]


override extension (node: NodeDb.this.N) def parent: Any = ???

override extension (node: NodeDb.this.N) def leftChild: Any = ???

override extension (node: NodeDb.this.N) def rightChild: Any = ???


private final class InMemoryNodeDb[F[_]] extends NodeDb[F]
```

**Comment by tgodzik** [comment]
I will take a quick look here.

**Comment by tgodzik** [comment]
It seems we could group the completions by extensionParams if it exists and create proper extensions. Another issue seems to be that we don't offer overrides for abstract extension methods.

I will leave it to you @tanishiking

**Comment by tanishiking** [comment]
@armanbilge The insert position is fixed, but the code action still works wrong with your code example 😭 
 will follow-up in https://github.com/scalameta/metals/issues/4082
