### ISSUE TITLE
Scala 3: Invalid import inserted when apply method is completed

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#4066]
### Describe the bug

If you try to complete "SimpleBuilderForString" in the place of `???` in the following code, you get an invalid import:

```scala
//> using scala "3.1.2"

object another {

  object SimpleBuilderForString extends SimpleBuilder[String]

  abstract class SimpleBuilder[P] {
    def apply[Alg[_[_, _, _, _, _]], Op[_, _, _, _, _]](s: P) = s
  }
}

object Demo {
  def a = ???
}
```

### Expected behavior

Completing this:

<img width="2162" alt="image" src="https://user-images.githubusercontent.com/894884/175785718-a677c51c-fee5-4dea-b709-ebd802621afa.png">

results in this code:

```scala
//> using scala "3.1.2"
import another.SimpleBuilderForString

object another {

  object SimpleBuilderForString extends SimpleBuilder[String]

  abstract class SimpleBuilder[P] {
    def apply[Alg[_[_, _, _, _, _]], Op[_, _, _, _, _]](s: P) = s
  }
}

object Demo {
  def a = SimpleBuilderForString
}
```

For comparison, Scala 2.13.7's handling currently results in this:

```scala
//> using scala "2.13.7"

object another {

  object SimpleBuilderForString extends SimpleBuilder[String]

  abstract class SimpleBuilder[P] {
    def apply[Alg[_[_, _, _, _, _]], Op[_, _, _, _, _]](s: P) = s
  }
}

object Demo {
  def a = another.SimpleBuilderForString
}
```

An import is inserted instead if `another` is a package.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.6+67-926ec9a3-SNAPSHOT

**Comment by kubukoz** [comment]
I think there's 2 things happening here: first of all, I don't think `apply` should be part of the import. Second of all, the parent class is imported instead of the child.

**Comment by tgodzik** [comment]
Thanks for reporting!

> I don't think apply should be part of the import.

What do you mean by that? It's just the apply completion so that you will get a proper () snippet

> Second of all, the parent class is imported instead of the child.

We should not import anything, but use the full name, I think the issue here is that look for conflicting symbols in a wrong scope or don't check all possible symbols.

**Comment by kubukoz** [comment]
Sorry, I forgot to show the actual behavior on 3.x 😅 

This import gets added:

`import another.SimpleBuilder.apply`

> It's just the apply completion so that you will get a proper () snippet

That's not the 2.x behavior though - what is more, if there were other members in `SimpleBuilderForString` or some extension methods in scope, I might be trying to call `SimpleBuilderForString.foo` and not `apply`.

I don't see why `apply` would be imported anyway, since you don't need to import the `apply` symbol to call the `apply` method on something

**Comment by tgodzik** [comment]
Thanks! We should not import apply in that case, that's a bug for sure.
