### ISSUE TITLE
Metals hides Java Home preference in VSCode

### ISSUE THREAD

**Issue by unthingable** [scalameta/metals#4094]
### Describe the bug

When setting `Metals: Java Home` property in VSCode, Metals writes it to `~/.bloop/bloop.json`. The problem is two-fold:

1. It is not immediately obvious that this is happening and that `~/.bloop/bloop.json` is the true source of Java home for Metals
2. Worse, `Metals: Java Home` setting still appears blank in VSCode even if it is set in bloop.json

This can lead to a really confusing case:
1. Set an invalid java home path in `Metals: Java Home` VSCode setting
2. Reload Metals — it fails to start
3. Attempt to set the correct path via VSCode settings — has no effect because Metals is no longer running

### Expected behavior

1. `Metals: Java Home` setting is visible in VSCode settings when path is set in `~/.bloop/bloop.json`
2. A brief mention about `~/.bloop/bloop.json` in the setting description would also help to reduce confusion

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.6

**Comment by dos65** [comment]
@unthingable 
> Attempt to set the correct path via VSCode settings — has no effect because Metals is no longer running

After changing this setting you need to reload VSCode.

**Comment by unthingable** [comment]
> After changing this setting you need to reload VSCode.

It is blank after reloading VSCode.

**Comment by kpodsiad** [comment]
> 1. It is not immediately obvious that this is happening and that `~/.bloop/bloop.json` is the true source of Java home for Metals
> 2. Worse, `Metals: Java Home` setting still appears blank in VSCode even if it is set in bloop.json

@unthingable 
`~/.bloop/bloop.json` isn't a true source of Java home for Metals. Java defined in `bloop.json` will be used for running bloop and doesn't affect the Metals one. If anything, it's the other way around. Metals write to that file to make bloop uses the same Java as Metals uses.

**Comment by tgodzik** [comment]
I think setting Java version has been stable recently, let's open up another issue if it still is a problem.
