### ISSUE TITLE
Misaligned highlights when using tabs (3 space width)

### ISSUE THREAD

**Issue by strelec** [scalameta/metals#4112]
### Describe the bug

1. set tab size = 3
2. open any Scala source and click on a symbol that occurs more than once in the file

### Expected behavior

When clicking keywords, I would expect the highlight to cover the keyword exactly.

Yet for every indent level of the line, it is one space extra to the left, which makes me assume that your plugin hardcodes tab size = 2.

You might think that this problem is only cosmetic, but it also prevents "Rename Symbol" from working, as it picks up the wrong name.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.18.0

**Comment by tanishiking** [comment]
Hi, @strelec thank you for reporting!
Which version of Scala are you using, it should be fixed in Scala 3.2.0-RC1 https://github.com/scalameta/metals/issues/3724 so if you're using Scala3.x, could you check it works correctly with Scala 3.2.0-RC1?
If you're using Scala2.x, we have to fix something.

**Comment by strelec** [comment]
I am very surprised that this is a Scala issue.

I am using latest stable, 3.1.3

Let's hope 3.2 gets officially released soon

**Comment by tanishiking** [comment]
Closing for Scala 3.2.0 is officially released :tada:
