### ISSUE TITLE
Syntax highlighting doesn't respect -Xsource

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#4133]
### Describe the bug

1. Enable the `-Xsource:3.0` scalacOption

2. Write this
```scala
true
&& false
```

3. See error: `; expected but false found`

### Expected behavior

No redness

### Operating system

macOS

### Editor/Extension

vscode

### Version of Metals

0.11.7+7-67ce8743-SNAPSHOT

### Extra context or search terms

scalameta, scalafmt

**Comment by tanishiking** [comment]
Hmm, looks like the dialect for scalameta parser used for emitting diagnostics inside Metals doesn't take `-X:source3` into account 🤔

**Comment by tanishiking** [comment]
Ah, gotcha, it has to be `-Xsource:3` instead of `-Xsource:3.0`
https://github.com/scalameta/metals/blob/ec89eac187c5c9e1358a8229ebac85b64a71a8a9/metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala#L72

**Comment by tanishiking** [comment]
As it is valid to specify `-Xsource:3.0` or `-Xsource:3.x.x`, we should recognise `-Xsource:3.x.x` as well 👍 
https://github.com/scala/scala/blob/d23424cd3aa17f7ad95b81018c70ceed2566962b/src/compiler/scala/tools/nsc/settings/ScalaSettings.scala#L105
