### ISSUE TITLE
Remember choice of "Don't show this again" for reloading builds

### ISSUE THREAD

**Issue by asflierl** [scalameta/metals#4166]
Whenever I change something in my SBT (which I use as BSP server) build, a small notification pops up in VSCode that I have to reload my build. I usually click on "don't show this again". But as soon as I reload my build - I usually do that on the console with sbtn reload - and then reconnect to SBT again with the "connect to build server" command, VSCode forgets what I have chosen before and will show that popup again after the first build.sbt change.

@kpodsiad found in code that this setting is being reset after the "connect to build server" command
@tgodzik suggested this could be changed for when SBT is the build server

**Comment by tgodzik** [comment]
Thanks for reporting! Moving it to the main repo, since I think this is a bug really.
