### ISSUE TITLE
Go To Definition and Go To Implementation not working properly

### ISSUE THREAD

**Issue by vzmerr** [scalameta/metals#4194]
### Describe the bug

In the following code in Scala 3 Completions file, we have the following problem on the `toString` method of `Symbol.Symbol`

https://user-images.githubusercontent.com/109077949/181247893-630530b5-cd5a-422b-9e01-901cf76ddb93.mov

:

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.7+61-a6299f3a-SNAPSHOT

**Comment by tgodzik** [comment]
Looks like it's the same issue as was fixed in https://github.com/lampepfl/dotty/pull/15536

We can confirm when we update metals to 3.2.0

**Comment by vzmerr** [comment]
One extra case to check
![Go To def](https://user-images.githubusercontent.com/109077949/182612839-54d9d43d-ca39-4f0d-9ce2-75b034b93fff.gif)

**Comment by tgodzik** [comment]
> One extra case to check

That is unrelated, but it does work for me. It needs the code to compile though.

**Comment by vzmerr** [comment]
> > One extra case to check
> 
> That is unrelated, but it does work for me. It needs the code to compile though.

I ran the tests, so it is compiled. I wonder why it is not working on my side. 

By the way, I guess it would be cool if we add a trouble shoot tutorial in the docs.

**Comment by vzmerr** [comment]
> Where did you run the tests though? 
sbt

**Comment by tgodzik** [comment]
> > Where did you run the tests though?
> 
> sbt

Yeah, sbt compilation is unrelated unless you use sbt server. If you use Bloop it probably didn't compile. Maybe something is shown in the problems view?

**Comment by vzmerr** [comment]
![Problem View Ammonite](https://user-images.githubusercontent.com/109077949/182635850-b5092149-2ca9-44f1-95d9-5074e03ff75e.gif)
 Yes, 66 problems

**Comment by vzmerr** [comment]
the problem might be Bloop
<img width="749" alt="Screenshot 2022-08-03 at 16 42 15" src="https://user-images.githubusercontent.com/109077949/182637083-a47a856d-be2a-4bf9-b88f-be86d9b0ab17.png">

**Comment by vzmerr** [comment]
> Try Clean compiler workspace command


after running `sbt clean` followed by `sbt compile`, the problems number  increased to 227.  

Same with `Clean Java Language Server Workspace` command.

**Comment by dos65** [comment]
@vzmerr this clean command is located in Metals ta
![Screenshot from 2022-08-03 18-29-31](https://user-images.githubusercontent.com/5816952/182647925-8af7eec0-8b98-47ba-a3a0-33499da31424.png)

**Comment by kpodsiad** [comment]
@vzmerr if you are using sbt extensively you may consider switching build server to sbt

**Comment by vzmerr** [comment]
@dos65 thanks the problems got reduced to 3
<img width="558" alt="Screenshot 2022-08-03 at 17 44 44" src="https://user-images.githubusercontent.com/109077949/182651629-7f5478bc-6a34-4577-98b8-e79ce2ff0bd6.png">

@kpodsiad 
>  if you are using sbt extensively you may consider switching build server to sbt

how do I do that?

**Comment by vzmerr** [comment]
The standard way of using Metals is with Bloop, though. So I guess for the sake of revealing the functionality of Metals from the user perspective, I have to stick to Bloop.

**Comment by dos65** [comment]
@vzmerr you need to trigger compilation once from sbt - `BuildInfo` is a generated source and only sbt can generate it

**Comment by vzmerr** [comment]
> @vzmerr you need to trigger compilation once from sbt - `BuildInfo` is a generated source and only sbt can generate it

But I did so. I ran the test.

**Comment by vzmerr** [comment]
I think I really have to make a troubleshoot doc PR

**Comment by vzmerr** [comment]
The issue got solved by deleting the `.bloop` directory and then compiling and importing build. credit to @dos65 
Also, with the newest work of Vadim on Bloop, this issue might not be encountered by users again :)

**Comment by vzmerr** [comment]
> The issue got solved by deleting the `.bloop` directory and then compiling and importing build. credit to @dos65
> Also, with the newest work of Vadim on Bloop, this issue might not be encountered by users again :)

I mean the Problems view issue, not the javadoc on hover one.

**Comment by tanishiking** [comment]
Now Scala 3.2.0 is released https://github.com/lampepfl/dotty/pull/15536
closing, if there're remained issues related to this, feel free to open a new one :)
