### ISSUE TITLE
non-members appearing as member completions for Scala 3

### ISSUE THREAD

**Issue by vzmerr** [scalameta/metals#4195]
### Describe the bug

In the following code, for `Symbol.Symbol` items that are not members of it are suggested as completions.

https://user-images.githubusercontent.com/109077949/181255145-8fbecb77-5c0e-422e-a72d-14f75c2f07b2.mov

### Expected behavior

only members of an object should be suggested as completions.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.7+61-a6299f3a-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! Those suggestions are from VS Code and can probably be turned off. It's nothing we can fix in Metals

**Comment by vzmerr** [comment]
You mean `Include Symbols`? It is turned off. There are a bunch of completion settings which are enabled by default for other languages such as Java, though.

**Comment by vzmerr** [comment]
disabling Java Completions and Intellicode Completions for Java did not change the behaviour.

**Comment by tgodzik** [comment]
I think that might be `editor.wordBasedSuggestions` setting. Anyway, it's not coming from metals
