### ISSUE TITLE
Support colors in error messages

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#420]
Currently, error messages look like this:

![image](https://user-images.githubusercontent.com/894884/50085265-d5628980-01f9-11e9-87ce-c34a3ce4a8db.png)

(I tried to copy the text but it wasn't possible)

It would be great if the color markers were stripped and/or replaced with actual coloring :)

**Comment by olafurpg** [comment]
Thanks for reporting! Are those colors are added by a compiler plugin? This can be fixed on the Metals side
by running `fansi.Str(diag.getMessage).plainText` here

https://github.com/scalameta/metals/blob/7a97d9f9602fa3a2e5d24ddb591626fb96d7639f/metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala#L337

**Comment by olafurpg** [comment]
Fixed by #445
