### ISSUE TITLE
Provide extension method code completions when typing `xxx.@@`

### ISSUE THREAD

**Issue by tanishiking** [scalameta/metals#4215]
### Describe the bug

Define an extension method like

```scala
package a
extension (num: Int)
  def increment: Int = ???
```

Try to use the extension method in another package

```scala
package b
1.i@@
```

if we type `1.i` we will have an auto-completion for `increment` extension method. However, if we type `1.@@` we don't get the completion for `increment`

### Expected behavior

> It would be ideal if it were allowed to search even with an empty query.
> Then, the user will be able to discover extension method by autocompleting

https://github.com/scalameta/metals/pull/4183#discussion_r934249157

### Editor/Extension

VS Code

### Version of Metals

0.11.7+79-d2ab7248-SNAPSHOT	

### Extra context or search terms

Follow up from https://github.com/scalameta/metals/pull/4183

extension method

**Comment by tanishiking** [comment]
- It doesn't work because we guard for an empty query [here](https://github.com/scalameta/metals/blob/d2ab724848b0c8b5c066694e5cf431c809715d34/mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala#L456), we have to remove this guard
- However, just removing `if query.nonEmpty` doesn't work
  - it calls [MetalsSymbolSearch.searchMethods](https://github.com/scalameta/metals/blob/d2ab724848b0c8b5c066694e5cf431c809715d34/metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala#L103-L112) and empty query may fail inside of it, we have to workaround it.

**Comment by robmwalsh** [comment]
I'll give this one a go

**Comment by tgodzik** [comment]
Great to hear! Let us know if you encounter any difficulties!
