### ISSUE TITLE
Not showing Javadoc on Hover in Scala 3 

### ISSUE THREAD

**Issue by vzmerr** [scalameta/metals#4227]
### Describe the bug

![Javadoc on Hover](https://user-images.githubusercontent.com/109077949/183039312-d7fa2156-4dad-43de-9d8c-a157cc7602a6.gif)

This happens in the saved workspace, despite the fact that Go to Definition is working.
The Problems view in VSCode is empty.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.7+79-d2ab7248-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! This is the same issue as https://github.com/scalameta/metals/issues/4194
