### ISSUE TITLE
metals doesn't index test folder (intended for unit tests) along with project 

### ISSUE THREAD

**Issue by egoarka** [scalameta/metals#423]

**Comment by olafurpg** [comment]
Thanks for reporting! Can you please provide more details? For example:

Imported an sbt build and ran goto definition:

- it didn't work at all
- it returned wrong results
- ...

**Comment by egoarka** [comment]
So, I realized it's my fault. I right now explicitly provided for `CubeCalculator` package name and imported it from the test, now it works well.

I just expected that it will find it for me :) 

Sorry for disturbing

**Comment by olafurpg** [comment]
Good it worked out 👍
