### ISSUE TITLE
`.scala.semanticdb` Files Littering Source Directories

### ISSUE THREAD

**Issue by godenji** [scalameta/metals#4230]
### Describe the bug

Compilation results in creation of hundreds of `.scala.semanticdb` files alongside companion `.scala` source files.

I've brought this up on Discord and most users report sementicdb files being created in `target` directory. Not sure why this is happening, but it's quite annoying when dropping down to VIM (which is often necessary due to lack of support for build.sbt `ProjectRef`s).

I have a ram disk mounted on `/tmp`; I'd expect all compiler generated files to be placed there, as has been the case for years in this setup (i.e. before adopting Metals/VS Code).

Scala 3.2.0-RC3
SBT 1.7.1
Metals 0.11.7
Fedora 36

Using SBT as the build server, suppose I could go back to Bloop, but I'd prefer to avoid double compilation (in the past editor and sbt shared same ram disk build target, with sbt running the show).

Let me know if this would be better posted in sbt issue tracker or here; it's unclear to me why this is happening, assume it's a Metals issue, so posting here.

### Expected behavior

That `.scala.semanticdb` files are generated in ram disk target, not alongside source files in source directories.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

0.11.7

**Comment by godenji** [comment]
Removing `Global / semanticdbEnabled := true` from my `/.sbt/1.0/global.sbt` reduced the number of `.scala.semanticdb` files signficantly, but there are still a handful after a `;clean;compile` (despite having gotten rid of them with `find . *.scala.semanticdb | xargs -exec rm -f`)

What am I missing if I disable semanticdb globally?

**Comment by godenji** [comment]
Think I see what's happening now.

During my VS Code journey I started out, as we all do, with Bloop as the default build server. After some time I grew frustrated with various aspects of the editing experience and switched over to sbt as the build server, which worked fine, except for the `.scala.semanticdb` file issue.

It turns out that the automatically generated `metals.sbt` file included a semanticdb plugin; that combined with setting `Global / semanticdbEnabled := true` in my `/.sbt/1.0/global.sbt` (compiler warnings suggest this action), *and* using sbt as the build server resulted in extraneous files being generated in source directories.

;tl;dr; if switching from bloop to sbt as the build server, blow away *everything* (.bloop, .bsp, .metals, metals.sbt, etc.) and start from scratch.

**Comment by tgodzik** [comment]
Thanks for reporting! You should not have to add anything manually especially to the global sbt configuration. It might cause some unexpected issues.

**Comment by tgodzik** [comment]
> I guess the question is where in the Metals codebase is `.scala.semanticdb` target folder determined? Somehow it's both build target (in my case `/tmp/sbt`) _and_ project source folders.
> 

We don't actually targetroot, it should use the defaults, which means using the target directory.

**Comment by godenji** [comment]
Right, and when I `show semanticdbTargetRoot` it correctly displays the `/tmp/sbt` build target, so how is that source folders also become an eligible target when boh vscdoe and separate terminal session are running?

It doesn't seem like an uncommon scenario, running the two processes together; certainly if you're running any kind of dev server you need a separate terminal based sbt session.

**Comment by tgodzik** [comment]
> Right, and when I `show semanticdbTargetRoot` it correctly displays the `/tmp/sbt` build target, so how is that source folders also become an eligible target when boh vscdoe and separate terminal session are running?
> 
> It doesn't seem like an uncommon scenario, running the two processes together; certainly if you're running any kind of dev server you need a separate terminal based sbt session.

I have honestly no idea how that would happen. Maybe they had a separate working directories?

**Comment by godenji** [comment]
> I have honestly no idea how that would happen. Maybe they had a separate working directories?

Interesting, you might have found the scenario that's triggering this bizarre behavior.

Myy application is built on dependent `ProjectRef`s, the top level project being the "gateway" (where Akka HTTP dev server is run from). It's from this project directory where I open terminal sbt session and fire up the dev server.

Now, in vscode I'm currently working lower down in a project that "gateway" depends on. I have yet to create vscode workspaces for any of the other `ProjectRef`s so the current project is the only one with a `project/metals.sbt` (which automatically sets `semanticdbEnabled`).

If instead of opening sbt session in the gateway project I open it in current vscode project directory then source directory pollution does not happen; from the gateway sbt session it does.

It seems there's some weird interaction between `ProjectRef`s in a top level project and dependent projects having `semanticdbEnabled` property set to *true*. That's really what it boils down to, when this flag is set in dependent projects then the top level project for some reason generates `.scala.semanticdb` files in source directories.

Still have no idea why this happens, but this seems to be the scenario that triggers it.

**Comment by godenji** [comment]
`.scala.semanticdb` files in compile target and source directories differ (i.e. always the same byte difference between target and source binaries). And that difference is accounted for at the head of the files.

In correctly located compile target version we have:
> &src/main/scala/path/to/dao/Dao.scala*h
local0*self��R"P

But extraneous source directory version has:
> Ahome/me/lab/sample/src/main/scala/path/to/dao/Dao.scala*h
local0*self��R"P

I assume that the problem is [MetalsPlugin.scala](https://github.com/scalameta/metals/blob/main/sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala) + separate sbt session. Within vscode any compilation event correctly places`.scala.semanticdb` files in compile target.

**Comment by tgodzik** [comment]
I think this might be the default location to create semanticdb files without the target flag.

**Comment by godenji** [comment]
> I think this might be the default location to create semanticdb files without the target flag.

And how would one set the target to something other than right alongside one's source files?

**Comment by tgodzik** [comment]
That's the -semanticdb-target flag. We usually set that up automatically yo the classes root.

**Comment by godenji** [comment]
Nope, same, *.scala.semanticdb* files everywhere in my sources.

Not sure what to do, there's some strange side effect happening between metals with sbt as build server and having a separate sbt terminal session running in a multi-project build. Bloop can't even compile the application so I need to use metals sbt as the build server.

On the plus side, everything does work, with the exception of this one very annoying issue :)
