### ISSUE TITLE
Implement All Members for trait instantiation with `new` not working

### ISSUE THREAD

**Issue by vzmerr** [scalameta/metals#4232]
### Describe the bug

Metals suggests t "Implement All Members" in the Quick Fix for the code below in Scala 3, but when it is selected, nothing happens
![ImplementAllMembersTrait](https://user-images.githubusercontent.com/109077949/183398215-9f54cd89-d319-40dc-9a44-d7b4712ffcfa.gif)

### Expected behavior

It should implement `def iterator: Iterator[Int] = ???` 

### Operating system

macOS

### Editor/Extension

VSCode

### Version of Metals

0.11.7+79-d2ab7248-SNAPSHOT

### Extra context or search terms

Scala 3, Implement all members, trait, new

**Comment by tgodzik** [comment]
Thanks for finding this! @tanishiking could you take a look at it?
