### ISSUE TITLE
Metals VSCode v.1.19.0 not working for scala 2.12.15

### ISSUE THREAD

**Issue by yuxuan-z19** [scalameta/metals#4242]
### Describe the bug

I was working perfectly on VSCode with Metals v1.18.0 until the extension was "forced" upgrading to v1.19.0 a few minutes ago
After I restarted VSCode, warning appears:

```bash
Stopped configuration of Scala SemanticDB in 2.12.15 projects: Missing semanticdb-scalac_2.12.15 plugin in resolved jars
/home/yeehinchong/.cache/coursier/v1/https/maven.aliyun.com/repository/central/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.jar
```

and I couldn't perform simple operations like code linting, navigation & etc.
This is what Metals Doctor shows

<img width="1001" alt="截屏2022-08-10 15 47 33" src="https://user-images.githubusercontent.com/68550432/183844860-4c69a9b5-b0dd-4f7f-8d9d-db190b7439ef.png">

The `build.sbt` file :
```scala
// See README.md for license details.

ThisBuild / scalaVersion     := "2.12.15"
ThisBuild / version          := "0.1.0"
ThisBuild / organization     := "com.xxx"

val chiselVersion = "3.5.3"

lazy val root = (project in file("."))
  .settings(
    name := "kwap",
    libraryDependencies ++= Seq(
      "edu.berkeley.cs" %% "chisel3" % chiselVersion,
      "edu.berkeley.cs" %% "chiseltest" % "0.5.3",
      "edu.berkeley.cs" %% "dsptools" % "1.5.3",
      "edu.berkeley.cs" %% "rocketchip" % "1.2.6",
      "edu.berkeley.cs" %% "hardfloat" % "1.2.4"
    ),
    scalacOptions ++= Seq(
      "-language:reflectiveCalls",
      "-deprecation",
      "-feature",
      "-Xcheckinit",
      "-P:chiselplugin:genBundleElements",
    ),
    addCompilerPlugin("edu.berkeley.cs" % "chisel3-plugin" % chiselVersion cross CrossVersion.full),
  )
```

### Expected behavior

I downgraded it to v1.18.8 and it works fine

<img width="1001" alt="截屏2022-08-10 15 56 43" src="https://user-images.githubusercontent.com/68550432/183847253-b1bafc73-57c8-461e-a0b0-851bc8c09fdc.png">

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.8

**Comment by ckipp01** [comment]
Thanks for the report @yuxuan-z19 but something seems to be borked with your build. Looking at:

```
Stopped configuration of Scala SemanticDB in 2.12.15 projects: Missing semanticdb-scalac_2.12.15 plugin in resolved jars
/home/yeehinchong/.cache/coursier/v1/https/maven.aliyun.com/repository/central/org/scala-lang/scala-library/2.12.16/scala-library-2.12.15.jar
```
It's trying to resolve the 2.12.15 jar from the 2.12.16 path, which isn't going to work, and I'm sure is also screwing up how semanticdb is being applied. Is the `build.sbt` you showed the only thing that is configuring your build, or do you have any other build-related files?

**Comment by yuxuan-z19** [comment]
@ckipp01 sorry for causing misunderstanding, it should be 2.12.15 (updated)

**Comment by tgodzik** [comment]
Thanks for reporting! Do you have a bit more logs? The version of Bloop is exactly the same so no issues should really pop up if you change Metals version. If you go back to the new version, does it happen again? Did you reimport the build around the same time?

**Comment by dos65** [comment]
I'm wondering if it might be a repo sync issue.
I'm noticed that your repo is: `maven.aliyun.com`. Does it sync `repo1.maven.org`?

Does it have an artifact copy for this path: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.15/4.5.11/ ?
Unfortunately, I can browse files at this repo. The following link https://maven.aliyun.com/repository/central/org/scalameta/semanticdb-scalac_2.12.15/4.5.11/ returns 404 for me.

**Comment by tgodzik** [comment]
Looks like the issue is not on the Metals side, but it's a repo sync issue as suggested by @dos65

**Comment by xiashiwendao** [comment]
I met the same problem, this problem is for semanticdb-scalac_2.12.10.jar download error. When I jump to
"/home/XXX/.cache/coursier/v1/https/maven.aliyun.com/repository/public/org/scalameta/semanticdb-scalac_2.12.10", found some .error file; then I  do follow:
1) drop the folder(as upper show:... .../org/scalameta/semanticdb-scalac_2.12.10)
2) execute the command as follow to down load the maven jar file to local repository:
mvn dependency:get -DremoteRepositories=https://maven.aliyun.com/repository/public -DgroupId=org.scalameta -DartifactId=semanticdb-scalac_2.12.10 -Dversion=4.7.2
3) return to vs code, re-execute "import build"

Then build successful.
