### ISSUE TITLE
Go-to implementation for anonymous classes in Scala3

### ISSUE THREAD

**Issue by agilesteel** [scalameta/metals#4246]
### Describe the bug

```scala
trait Foo: // goto implementation does NOT find anonymous class new Foo
  def foo: String // goto implementation DOES find the method implementation inside of the anonymous class new Foo

object Foo:
  lazy val make: Foo =
    new Foo: // does NOT go here
      override lazy val foo: String = // DOES go here
        "foo"
```
This was broken since forever and finally started working on the latest version `0.11.8`, but only for Scala2. In fact I initially wanted to file this bug for Scala 2, but was pleasantly surprised when I found out that it was resolved (probably by https://github.com/scalameta/metals/pull/4176).

### Expected behavior

It should list/go-to the `new` keyword on line `6`. I think it's better than going to `Foo` on the same line because in Scala3 the type can be inferred and we'd only have `new {}` or `new:`.

### Editor/Extension

VS Code

### Version of Metals

v0.11.8

**Comment by kpodsiad** [comment]
@agilesteel

**Comment by agilesteel** [comment]
I tried it before submitting and it worked 🤷‍♂️

**Comment by kpodsiad** [comment]
cc: @tanishiking as you have experience with Scala3's semanticDB too ;)

**Comment by tanishiking** [comment]
@kpodsiad Thank you very much for finding this!
Yes, I think we should emit those `local` symbol occurrences for `new Foo {}`s.

Scala3 doesn't do that because it doesn't emit symbol occurrence [if the symbol is present in the original source](https://github.com/lampepfl/dotty/blob/e560c2d6970c864ceea5607597d74cf49c443965/compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala#L358), `new Foo {}` should be marked as `presentInSource` :+1:

**Comment by kpodsiad** [comment]
Will you create an issue @tanishiking?

**Comment by agilesteel** [comment]
Please make sure that the fix handles the type inference case in Scala3, where code looks like this `new:` so there is no `Foo` to go to. I guess the cursor would/should jump to `@@new` in this case?

**Comment by tanishiking** [comment]
@agilesteel Can you share the full source code that you expect to work?

**Comment by tanishiking** [comment]
Ah, nevermind, you mean like this

```scala
object Foo {
  lazy val make: Foo =
    new {
      override lazy val foo: String = "foo"
    }
}
```

**Comment by tanishiking** [comment]
Reported in dotty repo https://github.com/lampepfl/dotty/issues/15852

**Comment by tanishiking** [comment]
I opened a PR to fix in lampepfl/dotty, this PR should fix both `val x =new Foo { ... }` and `val x: Foo = new { ... }` case :+1:

**Comment by tanishiking** [comment]
this should be fixed in the next release of Scala (3.2.1-RC2 or 3.2.1), wait for the release before closing :eyes:

**Comment by agilesteel** [comment]
Scala 3.2.1 is not out yet, but I already went ahead and tested with the latest nightly 3.2.2-RC1-bin-20221003-5d1497d-NIGHTLY and it works! 🎉

**Comment by tanishiking** [comment]
Thank you for confirming! Let me close this issue then :)
