### ISSUE TITLE
Improve error message for incorrect -P:semanticdb:sourceroot

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#425]
Minimal reproduction https://github.com/guillaumebort/minimal-metals/blob/master/.bloop/lol.json

Reported on Gitter https://gitter.im/scalameta/metals?at=5c18c5b500ab9f271108c0d2 by @guillaumebort

Observations:
- diagnostics work as expected
- the bloop JSON file has no `'resolution'` key

**Comment by guillaumebort** [comment]
Ok so adding these options to scalac:

```
"-P:semanticdb:failures:warning",
"-P:semanticdb:sourceroot:/private/tmp/minimal-metals",
"-Xplugin-require:semanticdb"
```

Seems to solve the problem.

**Comment by guillaumebort** [comment]
Looks like the `-P:semanticdb:sourceroot` one is the important one.

**Comment by olafurpg** [comment]
Good catch @guillaumebort! The bloop server has a different working directory so the relativized paths in the SemanticDB payloads are wrong without the explicit sourceroot.

I've updated the title of this ticket to improve the error message in this situation.

Note that goto definition will still not work for library dependencies without the `'resolution'` key. Here is an example how to construct `'resolution'` outside of sbt https://github.com/scalameta/metals/blob/0d504ea645c07c5c34e51b7d74c70d14366c7834/tests/unit/src/main/scala/tests/QuickBuild.scala#L131-L146

**Comment by olafurpg** [comment]
We even have a dedicated data structure for this case `NoMatchingUri`

https://github.com/scalameta/metals/blob/0d504ea645c07c5c34e51b7d74c70d14366c7834/mtags/src/main/scala/scala/meta/internal/mtags/TextDocumentLookup.scala#L63
