### ISSUE TITLE
Don't attempt to compile targets that have `canCompile` set to false

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#4254]
### Describe the bug

I just hit on this in https://github.com/com-lihaoyi/mill/pull/1977 but Metals seems to send in compile requets for all targets no matter what. I dug in a bit since I thought it'd be a quick fix and thought I could just change this:

https://github.com/scalameta/metals/blob/ab314f8f23de51b84c4415aa0f8f355c893f5502/metals/src/main/scala/scala/meta/internal/metals/Compilations.scala#L184-L196

to this:

```scala
    val targetsByBuildServer = targets
      .flatMap(target =>
        buildTargets.buildServerOf(target).map(_ -> target).toSeq
      )
      .groupBy { case (buildServer, _) =>
        buildServer
      }
      .map { case (buildServer, targets) =>
        val targets0 = targets.collect {
          case (_, target) if buildTargets.canCompile(target) =>
            target
        }
        (buildServer, targets0)
      }
```

And then add in a `canCompile` in `BuildTargets`:

```scala
  def canCompile(id: BuildTargetIdentifier): Boolean = {
    scribe.info(s"checking to see if we can compile ${id}")
    val result = data.iterable.exists(targetData => {
      pprint.log(targetData.buildTargetInfo)
      targetData.buildTargetInfo
        .get(id)
        .map[Boolean](_.getCapabilities().getCanCompile())
        .getOrElse(true)
    })
    result
  }
```
However when trying this out `builtTargetInfo` is always empty. There is a ton of stuff that recently changed here and it seems that here where this should be populated:

https://github.com/scalameta/metals/blob/ab314f8f23de51b84c4415aa0f8f355c893f5502/metals/src/main/scala/scala/meta/internal/metals/Indexer.scala#L196
`workspaceBuildTargets` this seems to add it, but I have a feeling the way we are trying to access this in `compilations` or something needs to be lazy.

### Expected behavior

I'd expect Metals to not send in a compile request to build targets that have `canCompile` set to false.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

Latest snapshot.

**Comment by tgodzik** [comment]
I'll take a look :eyes:
