### ISSUE TITLE
Stale diagnostics shown on vscode

### ISSUE THREAD

**Issue by ivanopagano** [scalameta/metals#426]
It might happen, not consistently, that existing errors displayed in the editor might not go away when the correction is made that makes the code compile again.

What I experience is that the squiggly underlines remain in place and going to the error with the key-shortcut will display the previously offending error message.

It's like something is not correctly cleaned, but it doesn't seem to happen deterministically.

**Comment by olafurpg** [comment]
Thanks for reporting! If I understand correctly

- you save a file
- compiler errors appear, as expected
- you change the file to fix errors and save
- compilation restarts and succeeds ("compiled foo (1s)" in status bar), you expect the errors to go away but they remain?

**Comment by ivanopagano** [comment]
I currently have such situation under my eyes, but I can't see if I got a successful outcome of compilation in the status bar (actually I'm not sure _where_ I should expect the message).

What I see is that also the `Problems` panel and the status bar keep showing the stale number and messages for both errors and warning now solved.

Hope this might help, I'll add a picture in a minute

**Comment by olafurpg** [comment]
@ivanopagano are those files possibly deleted? There's a known issue in that case https://github.com/scalacenter/bloop/issues/762

#430 improves the status bar reporting for compile error/success so that might improve the situation.

Another possible cause is that Metals currently sends a lot of compile notifications for files with multiple errors (one notification per error). It doesn't seem to be a big problem so far, but I've seen the problem pane jitter on large projects more than I'd like to

**Comment by ivanopagano** [comment]
No deleted files in my case.
I will keep you posted for any additional information that might help.

**Comment by gabro** [comment]
Could this be related to #438 and/or to upcoming fixes in Bloop 1.2.1? /cc @jvican

**Comment by ivanopagano** [comment]
I'm on the latest metals published and on bloop 1.2.0, and the issue appeared only once more yesterday

**Comment by olafurpg** [comment]
@ivanopagano I am able to reproduce a similar issue, see https://github.com/scalacenter/bloop/issues/785 for the details. The symptom is the same, fixed compile errors still appear in the editor.

**Comment by ivanopagano** [comment]
Great, so we need to wait for a bloop fix, thank you @olafurpg.

I think you can close the issue then.

**Comment by olafurpg** [comment]
I'm investigating a solution which would solve this on our side, which could be upstreamed down the road to bloop, so let's keep this open a bit longer ;)

**Comment by olafurpg** [comment]
I was unable to implement a workaround in Metals so I'm gonna close this issue in favor of https://github.com/scalacenter/bloop/issues/785
