### ISSUE TITLE
Use a long-lived Bloop server in CI

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#428]
The CI currently runs an embedded instance for each "slow" suite, which is a non-significant time penalty paid for each suite.

Starting a long-lived Bloop server in the CI should produce a decent speedup.

**Comment by jvican** [comment]
The launcher available in v1.2.0 should be an important contributor to make this happen: https://scalacenter.github.io/bloop/docs/launcher-reference. Metals can just run the launcher to establish a connection with a background server automatically.

**Comment by olafurpg** [comment]
This change resulted in failing tests with timeout exceptions that I can't reproduce on my machine. https://github.com/scalameta/metals/pull/453#issuecomment-452332165

Gonna close as wontfix, unless somebody wants to investigate the timeouts.
