### ISSUE TITLE
Metals formatter does not respect .scalafmt.conf on format on save

### ISSUE THREAD

**Issue by mindlid** [scalameta/metals#4283]
### Describe the bug

The default formatter for scala in vscode is set to metals, but seems to ignore `scalafmt.conf` on format on save
```jsonc
/* vscode setings.json */

"editor.formatOnSave": true,
"[scala]": {
  "editor.defaultFormatter": "scalameta.metals"
}
```

## Test case:
- Set imports to avoid expanding
> ```scala config
> version = "3.5.9"
> runner.dialect = scala3
> rewrite.rules = [Imports]
> rewrite.imports.expand = false
> rewrite.imports.sort = original
> ```
- Triggering formatting manually using palette command, works as expected
- Make a change and save, it will be formatted ignoring `scalafmt.conf` configuration

### Expected behavior

Format on save behave the same as formatting manually

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.8

**Comment by tanishiking** [comment]
Hi @mindlid 

> Make a change and save, it will be formatted ignoring scalafmt.conf configuration

How it will be formatted? it is like default scalafmt ignoring `scalafmt.conf` or just format doesn't work?
Can you check `editor.formatOnSaveMode` is `file` (not `modification`, Metals + scalafmt doesn't support incremental formatting).

Metals use `scalafmt` honoring `.scalafmt.conf` for file formatting (never ignore `.scalafmt.conf`), so I guess that your case happens because

-  `editor.formatOnSaveMode` is not `file`
- or your file is in wired place that scalafmt cannot apply

**Comment by mindlid** [comment]
@tanishiking 
https://user-images.githubusercontent.com/19735362/185777322-7532b540-b812-4153-8310-1ed42835c6cb.mov

**Comment by tanishiking** [comment]
Hmm, not sure what's going on, and I can't reproduce it. Is it possible to share a reproducible environment / project?

**Comment by mindlid** [comment]
just sent you invite

**Comment by tanishiking** [comment]
@mindlid Can't reproduce, can you include .vscode settings and .scalafmt.conf?

![formatonsave](https://user-images.githubusercontent.com/9353584/185777913-29c3f37c-9b22-4d9c-a7f0-21bd67bb3386.gif)

**Comment by tanishiking** [comment]
I noticed, if Metals **ignore** the `.scalafmt.conf`, scalafmt shouldn't format that way, there should be a configuration like

```
version = "3.5.9"
runner.dialect = scala3
rewrite.rules = [Imports]
rewrite.imports.expand = true
```

**Comment by mindlid** [comment]
just pushed the .scalafmt and .vscode

**Comment by mindlid** [comment]
![image](https://user-images.githubusercontent.com/19735362/185778237-541e0b2d-57bf-4a94-8963-4205dbe50c4b.png)

**Comment by mindlid** [comment]
i also opened the project with intellij, which generates some stuff let me clone again and open with vscode only

**Comment by mindlid** [comment]
just cloned, same import expand behaviour

**Comment by tanishiking** [comment]
Do you get the same behavior (inconsistent between format file from command palette vs format on save) in another, new project?
I'm still unable to reproduce it.

**Comment by mindlid** [comment]
yes, inconsistent behaviour, i don't have a clue, but i'm glad it's working for you, i'm on M1, Monterrey 12.5, until someone else can reproduce it will be an isolated bug

**Comment by mindlid** [comment]
by the way i remembered having the same bug on another m1 mac, i will test tomorrow on windows/linux

**Comment by mindlid** [comment]
@tanishiking got it working, i started to disable any interfering action from settings.json like 
![image](https://user-images.githubusercontent.com/19735362/185805533-d3ec5c94-52cb-4f7b-97bf-8dd533d80f83.png)
so some other global configurations don't play well when using other languages

**Comment by tanishiking** [comment]
@mindlid Good to hear you.found a solution!
organizeImport makes additional edit, so it's natural that causes different result.

**Comment by triplestepab** [comment]
I discovered that _vscode_ formats the file after the scala formatting. The problem resided in this setting and after disabling it the formatting worked as it should.

`"source.organizeImports": "always"`
