### ISSUE TITLE
Scala 3 incorrect return type suggestion for opaque type extensions

### ISSUE THREAD

**Issue by keynmol** [scalameta/metals#4339]
### Describe the bug

Not sure if it's a Metals or Scala 3 bug, but even though the precise type of the extension method is known, it returns generic type parameter name.

![Screenshot 2022-09-03 at 12 12 02](https://user-images.githubusercontent.com/1052965/188267833-0248e852-779a-42f3-99c4-6e4488a7957d.png)

Or may be this doesn't work on a fundamental level?

Code:

```scala
//> using scala "3.2.0"

object types:
  trait Opaque[H, T](using H =:= T):
    def apply(s: T): H = s.asInstanceOf[H]
    extension (h: H) def value: T = h.asInstanceOf[T]

  opaque type Hello = String 
  object Hello extends Opaque[Hello, String]

@main def hello = 
  import types.{*, given}
  val x = Hello("yes")

  x.value
```

### Expected behavior

I was hoping to see `value: String` 

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.8+55-e48b5ad4-SNAPSHOT

### Extra context or search terms

scala 3, suggestion, opaque, extension, return type

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like the issue related to https://github.com/lampepfl/dotty/issues/15730 and https://github.com/scalameta/metals/issues/4184

**Comment by rochala** [comment]
This is already fixed in dotty presentation compiler which will be default from next LTS version and Scala Next. I'll add tests for this.

![image](https://github.com/scalameta/metals/assets/48657087/88584e87-affb-4cca-bbd9-f343e1fee37c)
