### ISSUE TITLE
Scala3: "Implement all members" quick fix does not work with anonymous trait instances

### ISSUE THREAD

**Issue by unthingable** [scalameta/metals#4341]
### Describe the bug

1. ```scala
    trait Foo:
        def foo: Unit
    ```
2. `class Bar extends Foo`, save, `Implement all members`, get a class body with `override def foo: Unit = ???` 👍 
3. `val x = new Foo {}`, save, `Implement all members`, nothing happens

### Expected behavior

```scala
val x = new Foo {
    override def foo: Unit = ???
}
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.8

**Comment by tanishiking** [comment]
Thanks for reporting @unthingable !
Actually, it is duplicated with https://github.com/scalameta/metals/issues/4232 and will be fixed in the next release https://github.com/scalameta/metals/pull/4284
Sorry for the inconvenience!
