### ISSUE TITLE
Scala3: unnecessary quotes in autogenerated imports

### ISSUE THREAD

**Issue by unthingable** [scalameta/metals#4348]
### Describe the bug

When autocompleting a symbol generates an import containing a keyword, the keyword is wrapped in quotes.

Example:

```scala
import com.bitwig.`extension`.controller.api.Parameter
```

### Expected behavior

```scala
import com.bitwig.extension.controller.api.Parameter
```

At least with `extention` the quotes are unnecessary.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.18

**Comment by tgodzik** [comment]
Thanks for reporting! We should be able to not backtick the `extension` keyword in imports, that's a safe place for the soft keyword.
