### ISSUE TITLE
Case completions with keyword in scala3

### ISSUE THREAD

**Issue by jkciesluk** [scalameta/metals#4367]
### Describe the bug

When triggering completions in
```scala
List(1).map{ case new@@ }
```
It doesn't see `new` (it doesn't appear on path).
Tree looks like for 
```scala 
List(1).map{case@@ }
```
i.e.
```
CaseDef(
    pat = Literal(const = ( = null)),
    guard = Thicket(trees = List()),
    body = Block(stats = List(), expr = Literal(const = ( = ())))
  ),
```
This bug happens for other keywords too. Because of it metals sends all completions, becuase they are not filtered out by fuzzy match

### Expected behavior

`new` is correctly seen as an `Ident` or `Bind`
In scala 2 we get
```
CaseDef(
    pat = Bind(name = new_CURSOR_, body = Ident(name = _)),
    guard = <empty>,
    body = Literal(value = Constant(value = ()))
  )
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.8

**Comment by kasiaMarek** [comment]
Can you give an example of code snippet, what are the completions you get and what would you expect to get?
I think I might be misunderstanding the issue.
I was playing with such a snippet and the results are correctly filtered to include only things that start with `new`.
```
case class NewClass ()
object NewnewOne extends NewClass
object OtherTwo extends NewClass

object Demo:
  val l : List[NewClass] = ???
  val p = l.map {
    case new@@
  }
  ```

**Comment by jkciesluk** [comment]
There is a test for this https://github.com/scalameta/metals/blob/5b88c4db55f88f47f01ae0770b03755dd9888ac2/tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala#L394-L418

I'd expect to get only completions starting with "new", but all results are sent. You might not see them in the editor, because vscode filters them out, but they are still there.

**Comment by kasiaMarek** [comment]
> You might not see them in the editor, because vscode filters them out, but they are still there.
That explains it all, thanks.
