### ISSUE TITLE
Scala3: inferred type parameters shown twice

### ISSUE THREAD

**Issue by unthingable** [scalameta/metals#4372]
### Describe the bug

![image](https://user-images.githubusercontent.com/925755/189605961-8242bbf5-6b82-4775-bf2f-5c6d4c16451a.png)

Even though a parameter is explicitly specified, another `[A]` is shown.

A more complex example:

```scala
class SliderBankMode[Proxy, Param](
  override val id: String,
  val obj: Int => Proxy,
  val param: Proxy => Param,
  val barMode: Seq[BarMode],
  val stripColor: Option[Int => Int] = None,
)(using ext: MonsterJamExt, j: JamSurface, pValue: ParamValue[Param], exists: Exists[Proxy])
    extends SimpleModeLayer(id)
```
![image](https://user-images.githubusercontent.com/925755/189607016-eb04c720-8353-4298-9f1f-1d4b9191b90d.png)

Vector type is displayed correctly, but `new SliderBankMode` has two sets of parameters.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.18

### Extra context or search terms

Scala 3.2.1-RC1

**Comment by tanishiking** [comment]
@unthingable Thank you for reporting! Indeed it (after `extends C1[A]`) shouldn't be shown.

**Comment by tanishiking** [comment]
https://github.com/lampepfl/dotty/pull/16031 this PR should fix the problem :)

**Comment by tanishiking** [comment]
`3.2.1-RC2` (or `3.2.1`) should fix the issue, let's close after confirming this is fixed in the next release version.

**Comment by tgodzik** [comment]
Looks like it might end up in 3.3.x, the recent nightlies seem to work ok.
