### ISSUE TITLE
VS Code takes forever to Start Metals on Mac

### ISSUE THREAD

**Issue by tim-2022** [scalameta/metals#4378]
### Describe the bug

This sounds similar to https://github.com/scalameta/metals-vscode/issues/821 and https://github.com/scalameta/metals/issues/3508, but I don't think it's the same root cause, since those were solved by explicitly setting Metal's Java Home -- and that doesn't seem to do anything here.

I'm unable to use metals in VS Code; starting it (every time!) triggers the same JAR downloads, which seem to go on a very long time (have tried for many hours).  In a few cases, after starting off looking like it's working (I see a number of JARs download) it then stops.  But mostly, it just starts like this, and never progresses further:

```
Java home: /usr/local/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home
Metals version: 0.11.8+38-1832a3cf-SNAPSHOT
Downloading https://repo1.maven.org/maven2/org/scalameta/common_2.13/4.5.11/common_2.13-4.5.11.jar
Downloading https://repo1.maven.org/maven2/org/jsoup/jsoup/1.15.2/jsoup-1.15.2.jar
Downloading https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.equinox.registry/3.8.600/org.eclipse.equinox.registry-3.8.600.jar
Downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.19.2/protobuf-java-3.19.2.jar
```

(The output above, for example, started over 45 minutes ago, and still looks exactly like this.  But I've let it go for hours, in earlier attempts.)

Should this be interrupted, or fail, the process starts all over again, apparently not keeping any JARs which have already fully downloaded. 

The most obvious thing to suggest is a slow network connection, but I'm verified otherwise by using Maven to download many other JARs while the above process sits and does nothing.  I also manually grabbed a few of the JARs shown above (using wget, e.g. protobuf), and they download quite quickly.   I've tried this on four different networks which, otherwise, seem to be working fine: I can stream videos, etc. And I've also tried different JDKs, both Java 11 & 17, I've tried both the release and snapshot versions of the VS Code Scala Metals extension. 

Any hints?

### Expected behavior

I'd expect to see continuous process when starting Metals.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.8 and 0.11.8+38-1832a3cf-SNAPSHOT

**Comment by tanishiking** [comment]
That sounds like a network issue as the log says `Downloading...` but never says `Downloaded`, are you running your computer behind a proxy?, or usually use some custom repositories?

What happens if you try to download Metals from coursier CLI?
`coursier bootstrap org.scalameta:metals_2.13:0.11.8+96-734fbf48-SNAPSHOT -o metals -f
` (with the same java) ?

**Comment by tim-2022** [comment]
After more experimentation, seems that the repository was the problem.  You can close this, and thank you for the hint!

**Comment by tanishiking** [comment]
I'm glad that you solved the problem!
