### ISSUE TITLE
var assignments ignored when renaming

### ISSUE THREAD

**Issue by unthingable** [scalameta/metals#4467]
### Describe the bug

Related: #4093

When invoking "Rename symbol" on a `var`, LHS occurrences in assignments are ignored. Additionally, attempting to rename such occurrence has no effect.

```scala
var v5 = false

def f5: Boolean =
  v5 = true
  v5 == true
```

After renaming `v5` to `v6` (using the occurrence on the first line):

```scala
var v6 = false

def f5: Boolean =
  v5 = true
  v6 == true
```

### Expected behavior

```scala
var v6 = false

def f5: Boolean =
  v6 = true
  v6 == true
```

### Editor/Extension

VS Code

### Version of Metals

0.11.18

**Comment by tgodzik** [comment]
Thanks for reporting! I realized we don't actually properly test renaming variables. I created a PR with a fix, we should get it into the upcoming release.

**Comment by unthingable** [comment]
> Thanks for reporting! I realized we don't actually properly test renaming variables. I created a PR with a fix, we should get it into the upcoming release.

I have to say, using Metals and the attention to bug reports has been the best part of Scala development so far :-D
