### ISSUE TITLE
Get signature from presentation compiler

### ISSUE THREAD

**Issue by riiswa** [scalameta/metals#4473]
It will be useful to have a method from the presentation compiler to get the signature of a member (given his position). The code for this method can be extracted from  `HoverProvider`, and it will be used in https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/internal/metals/callHierarchy/CallHierarchyItemBuilder.scala to replace the `getSignatureFromHover` method. 

Related to the merged PR #4115.

**Comment by tgodzik** [comment]
It can also be just the hover with an additional flag not to give expression type I think. This would just require manipulating a couple of boolean values.
