### ISSUE TITLE
Opening a Scala script using Scala 3.nightly and FewerBraces, FB is not detected

### ISSUE THREAD

**Issue by carlosedp** [scalameta/metals#4482]
### Describe the bug

I have a scala-cli script using SIP-44 (FewerBraces) and use the `scala 3.nightly` directive.

While opening this script on VSCode/Metals, it showing the popup and clicking "Scala CLI", FewerBraces is not detected and shows error on it's syntax.

If I run `scala-cli setup-ide --scala 3.nightly .` before opening VSCode, the script is detected successfully.

```scala
#!/usr/bin/env -S scala-cli shebang
// checkdeps.sc
// Install [scala-cli](https://scala-cli.virtuslab.org/) to use

//> using scala "3.nightly"
//> using lib "com.lihaoyi::os-lib:0.8.1"
//> using lib "com.lihaoyi::requests:0.7.1"
//> using lib "com.lihaoyi::ujson:2.0.0"
//> using lib "com.lihaoyi::fansi::0.4.0"
//> using lib "io.kevinlee::just-semver:0.5.0"

import just.semver.SemVer
import language.experimental.fewerBraces

...
```
![image](https://user-images.githubusercontent.com/20382/193906464-f0736b88-d8c5-4695-8c64-23beafe8b6a8.png)

The project is correctly detected as Scala 3.nightly:

![image](https://user-images.githubusercontent.com/20382/193906678-12a1b6b0-c38c-4d3c-b1b2-e77769cc5224.png)

### Expected behavior

Since I have the scala `3.nightly` directive and `import language.experimental.fewerBraces`, Metals should detect the syntax.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.8+202-bd7c2e4d-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! If you change the file in any way does the error disappear? I think it might be a stale error from the parser.

**Comment by carlosedp** [comment]
> Thanks for reporting! If you change the file in any way does the error disappear? I think it might be a stale error from the parser.

Yes, it goes away! Sorry I didn't do a simple test like this before.

**Comment by tgodzik** [comment]
No worries, I just wanted to confirm. :+1:
