### ISSUE TITLE
StringIndexOutOfBoundsException on textDocument/hover

### ISSUE THREAD

**Issue by susliko** [scalameta/metals#4487]
### Summary
`textDocument/hover` sometimes crashes with `java.lang.StringIndexOutOfBoundsException` claiming start index to be larger than end index
### Steps to reproduce
1. Open [internal/metals/Compilers.scala](https://github.com/scalameta/metals/blob/56ef2390eb3fc5b56aa8c20a90310e5e7d662f17/metals/src/main/scala/scala/meta/internal/metals/Compilers.scala#L1) at any place
2. (Neovim-specific) Start Metals, Invoke `:lua vim.lsp.buf.hover()`  
3. open `.metals/metals.log`, find a stacktrace:
```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 7126, end 7105, length 29681
       ...
        at java.base/java.lang.String.substring(String.java:2707)
        at scala.meta.internal.metals.MetalsEnrichments$XtensionPositionRange.inString(Me
talsEnrichments.scala:703)
        at scala.meta.internal.decorations.SemanticdbTreePrinter.isExplicitTuple$1(Semant
icdbTreePrinter.scala:192)
        at scala.meta.internal.decorations.SemanticdbTreePrinter.$anonfun$printSyntheticI
nfo$4(SemanticdbTreePrinter.scala:197)
        at scala.meta.internal.decorations.SemanticdbTreePrinter.printTree(SemanticdbTree
Printer.scala:163)
        at scala.meta.internal.decorations.SemanticdbTreePrinter.$anonfun$printSyntheticI
nfo$3(SemanticdbTreePrinter.scala:197)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at scala.meta.internal.decorations.SemanticdbTreePrinter.gatherSynthetics$1(Seman
ticdbTreePrinter.scala:196)
        at scala.meta.internal.decorations.SemanticdbTreePrinter.tryTree$1(SemanticdbTree
Printer.scala:225)
        at scala.meta.internal.decorations.SemanticdbTreePrinter.printSyntheticInfo(Seman
ticdbTreePrinter.scala:271)
        at scala.meta.internal.decorations.SyntheticsDecorationProvider.$anonfun$addSynth
eticsHover$7(SyntheticsDecorationProvider.scala:135)
        ...
        at scala.meta.internal.decorations.SyntheticsDecorationProvider.$anonfun$addSynth
eticsHover$4(SyntheticsDecorationProvider.scala:126)
        ...
        at scala.meta.internal.decorations.SyntheticsDecorationProvider.$anonfun$addSynth
eticsHover$3(SyntheticsDecorationProvider.scala:125)
        ...
        at scala.meta.internal.decorations.SyntheticsDecorationProvider.addSyntheticsHove
r(SyntheticsDecorationProvider.scala:124)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$hover$2(MetalsLanguag
eServer.scala:1517)
        ...
```

Stacktrace points to [the code](https://github.com/scalameta/metals/blob/56ef2390eb3fc5b56aa8c20a90310e5e7d662f17/metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala#L703) that lacks a check of substring start being less than substring end

### Expected behavior

`textDocument/hover` completes without throwing any exceptions

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.9

**Comment by tanishiking** [comment]
Thank you for reporting!
I couldn't reproduce it in my environment (with VSCode), but as you mentioned, we should have `check of substring start being less than substring end` :+1:

**Comment by tgodzik** [comment]
Hmm... if we add the check then  we will not see why this happened, looks like there is a bug in the logic that searches for range.

Ach! I think I know what is going on, the range contains multiple lines and we don't seem to be handling that.

Trying a fix here https://github.com/scalameta/metals/pull/4501

**Comment by susliko** [comment]
I wonder why nobody else was able to reproduce this behavior on `Compilers.scala` file 🤔 
Meanwhile it reproduces consistently in my setup

**Comment by tgodzik** [comment]
> I wonder why nobody else was able to reproduce this behavior on `Compilers.scala` file thinking Meanwhile it reproduces consistently in my setup

Thanks! I was able to test the fix on that file.
