### ISSUE TITLE
Call hierarchy doesn't include superclass calls

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#4488]
### Describe the bug

I understand that this might be related to "find references", but it's annoying nevertheless and in an ideal world it would work:

1. Create file (tested on scala 2.13.8)

```scala
trait Service {
  def get(): Unit
}

class Impl extends Service {
  def get(): Unit = ()
}

object Demo {
  val s: Service = new Impl

  s.get()
}
```

3. Try to get the call hierarchy of `Impl.get`
4. Nothing is returned

### Expected behavior

The call to `s.get()` is found

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by riiswa** [comment]
Yes, the common part between call hierarchy and references is the symbol lookup in build targets.

**Comment by riiswa** [comment]
Hey, I did my internship defense, with a researcher in program compilation and type systems as jury. He told me that it will be difficult to manage polymorphism cases with SemanticDB and for this kind of cases it is maybe better to use the Presentation Compiler. What do you think?

**Comment by tgodzik** [comment]
> Hey, I did my internship defense, with a researcher in program compilation and type systems as jury. He told me that it will be difficult to manage polymorphism cases with SemanticDB and for this kind of cases it is maybe better to use the Presentation Compiler. What do you think?

The problem is that you would need to compile every file with the presentation compiler, which would mean compiling everything twice. Semanticdb already have the information about overriden symbols, which comes from the compiler, so that should be good enough to use.
