### ISSUE TITLE
Metals exited with status code 1 after opening build.sbt in Sublime Text

### ISSUE THREAD

**Issue by josh-s-g** [scalameta/metals#4518]
### Describe the bug

I use metals with VS Code successfully but haven't been able to get it to work with Sublime Text:

Steps to reproduce
1. Installed Sublime Text
2. Installed LSP (as per [this](https://scalameta.org/metals/docs/editors/sublime))
3. Installed LSP-metals 
4. Open a Scala project
5. Open build.sbt file

I receive this error message:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/9271916/195632567-da30ad02-0335-4592-a785-1063a15f2cbd.png">

`Restart metals` does nothing

Nothing clearly wrong in Metals Doctor in VS Code.

Is there anything that is likely to cause conflicts with Metals being used with 2 IDEs?

Thanks

### Operating system

macOS

### Editor/Extension

Sublime

### Version of Metals

0.11.9

**Comment by tgodzik** [comment]
Thanks for reporting! Are you using VS Code and Sublime at the same time with Metals server? That might not work, but I haven't really tested that ever. Does it work with sublime by itself?

**Comment by josh-s-g** [comment]
Same behaviour if I either 
(a) Open Sublime on its own
(B) Open Sublime after having opened VS code

**Comment by tgodzik** [comment]
@ayoub-benali any idea what might be happening here?

**Comment by ayoub-benali** [comment]
so Sublime and VSCode should be using different instances of Metal server. 

Can you check that you are opening the project at the root project folder ?
Also can you share the output of the "toggle log panel" command ?

**Comment by josh-s-g** [comment]
Thanks for the reply. Yes, the project is opened at the root level. The log panel output is interesting:

```
metals: The operation couldn’t be completed. Unable to locate a Java Runtime.
metals: Please visit http://www.java.com for information on installing Java.
```
Java is installed with SDKMAN, with `echo $JAVA_HOME`:

```
/Users/josh/.sdkman/candidates/java/current
```

and `java -version`:

```
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)
```

**Comment by ayoub-benali** [comment]
can you open sublime via the the terminal using `subl .` in your root directory and see if it fixes the problem.
it seems that `java_home` isn't available somehow when you open sublime via the program launcher.

Worst case you can set `java_home` in the settings

**Comment by josh-s-g** [comment]
Using `subl .` works fine, thanks. Out of interest, how do I 

> set `java_home` in the settings

?
 
Thanks

**Comment by tgodzik** [comment]
Seems like we can close the issue. `java_home` can probably be set the same way any sublime LSP settings are set.

You can probably find more information around here: https://github.com/scalameta/metals-sublime#java-version
