### ISSUE TITLE
can not find java11

### ISSUE THREAD

**Issue by pxs7** [scalameta/metals#4528]
in windows,  i have installed java and set java_home in setting,  but when downloading metas,  the warnings that java 11 cannot find out came out, 

how does this come out

**Comment by tanishiking** [comment]
Hi, @pxs7 thank you for the question!
We need some more information like

- installed java
  - which java did you install?
- and set java_home in setting
  - how did you set JAVA_HOME?
  - which setting did you mean by `in setting`?
    - it would be nice to share with a screenshot or something :+1:
- when downloading metas
  - What do you mean by "downloading metals"?
    - You mean, you're using VSCode / metals-vscode, and when you open a Scala project?
  - which editor do you use?

But more importantly, we appreciate if you follow the issue template and ask question in GitHub discussion instead :)

```
Please ask a question using [GitHub Discussions](https://github.com/scalameta/metals/discussions/new)

The main issue tracker is reserved for bug reports and issues with an assigned milestone.
```

**Comment by pxs7** [comment]
the latest vscode will be ok
