### ISSUE TITLE
mill command fails

### ISSUE THREAD

**Issue by pxs7** [scalameta/metals#4533]
### Describe the bug

2022.10.15 11:46:27 ERROR Mill command failed: E:\Program Files\mill\millw.bat  --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install

### Expected behavior

use mill build metas

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

### Extra context or search terms

Noneb

**Comment by pxs7** [comment]
use mill build meta step by step， the compile  will be ok，  but class can not  goto  definition。

use  vscode   import build  command，  the compile fails，  i search  class  config  in  meta package，  no foreign modu'le  found，  whether this cause  fails

**Comment by ckipp01** [comment]
Thanks for the report @pxs7. Could you provide a bit more info? I believe there should be more info in the logs about the failure, or does it not give you any more info why the mill command failed? Could you also include the version of Mill that you're using and the steps that you took to reproduce this?

**Comment by pxs7** [comment]
> 
i change mill verision  from  0.10.4 to  0.10.8,  import build command will be ok,   

bloop  version  1.5.4,  which is default version.

i doubt    bloop  version  just work  with  the  corresponding  mill  version

**Comment by tgodzik** [comment]
> 2022.10.15 11:46:27 ERROR Mill command failed: E:\Program Files\mill\millw.bat --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install

IS there any logs aside from these? The build import failed, which means Metals doesn't have any information about dependencies and project structure. Are you able to run the mill command manually? Maybe with `-i` and without that flag?

`\millw.bat -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install`

**Comment by pxs7** [comment]
> > 2022.10.15 11:46:27 ERROR Mill command failed: E:\Program Files\mill\millw.bat --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install
> 
> IS there any logs aside from these? The build import failed, which means Metals doesn't have any information about dependencies and project structure. Are you able to run the mill command manually? Maybe with `-i` and without that flag?
> 
> `\millw.bat -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install`

i add "--import ivy:com.lihaoyi::mill-contrib-bloop:0.10.8"  to build.sc, and  use command

  mill   mill.contrib.Bloop/install,
the command runs without any error,  but class cannot goto define, but  .bloop dir is generated. some files are also generated in   .bloop dir

**Comment by tgodzik** [comment]
Does the code compiler? You should be able to see more information when running `Metals: Run doctor` command. IS there anything in the logs about why it can't navigate the code?

**Comment by pxs7** [comment]
> 

all be ok  by switch  to the  latest vscode and mill，  many thanks
