### ISSUE TITLE
Automatically enable -Ycache-plugin-class-loader:last-modified for supported Scala versions

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#455]
I'm observing up to 3x faster compile times in scalajs-react by enabling this option, from 11s incremental compiles with it enabled up to 35s incremental compiles with it disabled.

**Comment by olafurpg** [comment]
Proposal: if Scala version supports it and the compiler option `-Ycache-plugin-class-loader:none` is not enabled, then enable `-Ycache-plugin-class-loader:last-modified`. Do the same for `-Ycache-macro-class-loader:last-modified`. The reasoning is that `last-modified` is a good default and people should explicitly enable the `none` policy if they are developing compiler plugins or macros. Any thoughts @jvican ?

**Comment by jvican** [comment]
If the reported performance gain is so high, we can enable this by default in bloop in the next version. I think it's better if in general metals does not change any scalac compiler options, given that it's out of its scope. The reason why it hasn't been enabled by default yet in 2.12.x and 2.11.x is because of https://github.com/scala/scala-dev/issues/548

**Comment by olafurpg** [comment]
@jvican that’s even better if bloop enables it by default.

**Comment by ivanopagano** [comment]
@jvican wouldn't it be feasible to enable the flag by default and adding notes on how to disable it when macros/plugins might be negatively affected?

**Comment by olafurpg** [comment]
I like the idea of having a whitelist of known safe plugins. Cache issues are a nightmare to track down. We can then update the doctor to recommend manually enabling the setting in their build when there are unknown plugins 👍

**Comment by jvican** [comment]
@ivanopagano Given the unknown impact that caching macros/plugins can have, it's better not to. Sometimes issues will be visible, sometimes they won't, so it's too risky to add the flags by default.

**Comment by jvican** [comment]
I have finished the creation of the compiler plugin list. I will proceed to open a pull request in bloop to implement the whitelisting approach.

**Comment by olafurpg** [comment]
I'm gonna close this issue in favor of delegating this feature to bloop. Thanks @jvican!
