### ISSUE TITLE
When .mill-jvm-opts doesn't end with a newline, the last parameter is ignored

### ISSUE THREAD

**Issue by phfroidmont** [scalameta/metals#4557]
### Describe the bug

Have a `.mill-jvm-opts` file to define custom JVM parameters, without a newline at the end
```
-Xss10m
-Xmx10G
```

`mill-bsp` runs a mill process with the `-Xss10m` parameter but without `-Xmx10G`

### Expected behavior

`mill-bsp` runs a mill process with all parameters defined in `.mill-jvm-opts`.

When adding a newline at the end of the file, the issue doesn't appear.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

### Extra context or search terms

mill-bsp v0.10.8

**Comment by ckipp01** [comment]
Thanks for the issue @phfroidmont although Metals doesn't have anything to actually do with the `.mill-jvm-opts` file. Metals will follow the instructions to start the BSP server that are found in the `.bsp/mill-bsp.json` file. Then it's up to the server to handle starting up correctly and doing things like reading its various files like you have listed here. You'll need to actually raise this issue over in [Mill](https://github.com/com-lihaoyi/mill).
