### ISSUE TITLE
Metals vscode on linux not showing jdk class javadoc

### ISSUE THREAD

**Issue by zhongwm** [scalameta/metals#4558]
### Describe the bug

Metals vscode on my mac can show javadoc but when on linux (manjaro ) it's not the case.

Javadoc for jdk class is not available even after I set the the settings entry "metals.javaHome".

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by ckipp01** [comment]
Hey @zhongwm if you execute `Metals: Run Doctor` do you see a warning about not being able to find your java sources? It depends on how you're installing Java on your machine but on some linux distros just installing the Java package will get you Java, but not the Java sources. However you installed Java you should see a similar package like `jdk-blah-sources` or something you can install along with it.

**Comment by zhongwm** [comment]
Yes thank you after I installed openjdk-src, openjdk[n]-src, this problem is gone.
