### ISSUE TITLE
find references for renamed import doesn't work

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#4562]
### Describe the bug

Having the following code, find-references for `X2` returns empty result
```scala
import sample.{X1 as <<X2>>}

object sample:
  class X1

def f: X2 = ???
```

### Expected behavior

There should a refernce on a result type of `def f`

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by tgodzik** [comment]
I think we could in this case do a fallback for `definition.positionOccurrences` to look at the tree and get the symbol of the import. We would also need to make sure that the actual rename ends up in the references.

Alternatively, we could add an occurrence to semanticdb for the rename.
