### ISSUE TITLE
Completion autoimport is incorrect.

### ISSUE THREAD

**Issue by rochala** [scalameta/metals#4563]
### Describe the bug

Importing apply methods provides wrong import. It only works in Scala3 as Scala2 does not provide completions for apply methods in companion objects.

to reproduce:
```scala
ListBuff@@
```
imports `import scala.collection.IterableFactory.apply`

### Expected behavior

It should properly return `import scala.collection.mutable.ListBuffer`

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

metals 0.11.9+63-adadc112-SNAPSHOT

**Comment by kubukoz** [comment]
related: #4066

**Comment by tgodzik** [comment]
Seems it's the same issue as #4066
