### ISSUE TITLE
Installation instructions not working

### ISSUE THREAD

**Issue by london-coder** [scalameta/metals#457]
Hi,
I tried to install Metals in VS Code on MacOS. Versions:
Metals 0.1.0
VS Code 1.25.1
MAC OS 10.14.2
locally installed Scala is 2.12.1

I followed the instructions on the website verbatim, and Metals does not work!

After installing Metals, I opened an existing sbt / scala project, opened several scala files and there was no "Import project" option anywhere. Furthermore, the metals.log file consisted of:
```
Jan 09, 2019 1:21:54 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.6.5.Final
Jan 09, 2019 1:21:54 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.6.5.Final
Jan 09, 2019 1:21:54 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.3.0.Beta2
INFO  Started Metals http server at http://127.0.0.1:5032
INFO  shutting down Metals
```

Which appears to offer no help in understanding why it does not work.
Is your project broken, or are the instructions wrong?
Regards,
Alan

**Comment by gabro** [comment]
Hi Alan, thanks for reporting!
0.1.0 is a very old version, so that seems to be the problem. Did you maybe try metals in the past? There may be some old artifacts lying around, causing the issue

**Comment by london-coder** [comment]
Hi Gabriele, thanks for the reply. If there are artefacts causing an issue, what are they and how can I remove them? The Metals version is the one installed from the VS Code marketplace. How can I install a later (latest?) version in VS Code?
Thanks

**Comment by london-coder** [comment]
Hi Ólafur,
Many thanks for the information. 
I did as you suggested, and the curious thing is that in the VS Code extensions list, Metals still reports version 0.1.0 even though when (re) installing form the Market place, the reported version is 1.1.3. Is there some kind of "pollution" in VS Code market place?

**Comment by olafurpg** [comment]
Have you tried upgrading vscode? I am on 1.30.2.

**Comment by gabro** [comment]
Can you also check what's the value of the serverVersion setting in VSCode?

**Comment by gabro** [comment]
To be clear:
- 1.1.3 is latest version of metals-vscode 
- 0.3.3 is the latest version of metals (this repo)

**Comment by london-coder** [comment]
Hi Guys,
Fantastic feedback and help, much appreciated.  
I have upgraded VS Code, (1.30.2), installed the latest Metals. At first, there was an error (inside VS Code) as it seems Metals picked up some random (old) version of the JDK, and not the version pointed at by $JAVA_HOME.  When I set this up manually in the Metals (Workspace) settings, it did allow me to import a project. 
Thanks again for your prompt replies. :-)

**Comment by london-coder** [comment]
...@gabro  Thanks, serverVersion set at 0.3.3

**Comment by gabro** [comment]
@london-coder great! Yeah, the Java JDK detection is still a bit rusty.

It would help if you could share some details on the Java JDK installation, e.g. How did you install Java? Are you using jenv? 

Thanks!

**Comment by london-coder** [comment]
I usually install the JDK after (Mac OS) Java Control Panel warns of an update the to JRE. I do update the $JAVE_HOME in my bash profile, but there may be some system setting (somewhere I am not aware of) that mac os sets. Oddly, when the IDE, Metals versions "lined up", and I almost had a working setup, The (Metals) console inside Code was reporting the use of java 1.8.0_11, where $JAVA_HOME was set to JDK1.8.0_191. I have not (so far) investigated why this may have happened. I manually removed the _11 version of JDK before restarting Code + Metals, whereupon Metals was able to import the project.

Perhaps it might be worth elaborating on the installation web page, in respect of "cleaning" any old artefacts from from sbt projects, or ~/.metals.  I did previously try adding Metals to Sublime Text, (that I could not get working), which may be why I had a problem using it with VS Code.

**Comment by london-coder** [comment]
<previous post> I should have clarified, that I use the Oracle JDK (not Open JDK), using the Mac OS installer from the Oracle Java site.

**Comment by olafurpg** [comment]
@london-coder we use `locate-java-home` that probably picked `_11` instead of `_191`.

**Comment by gabro** [comment]
Thank you for the details @london-coder, that helps a lot!

Yeah, `locate-java-home` lists all installed JDKs and then it's up to us to pick one.

At the moment, we select the first one, but we could be smarter and base our selection on the patch version instead.
