### ISSUE TITLE
LSP workspace configuration should handle null values in response

### ISSUE THREAD

**Issue by fiadliel** [scalameta/metals#4577]
### Describe the bug

Workspace configuration (defined [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration)) is defined such that if the client is unable to provide a configuration for a particular scope, it has to return `null`:
> If the client can’t provide a configuration setting for a given scope then null needs to be present in the returned array.

When a `null` is returned from a client, metals throws an exception instead, for example:

```
<- {"jsonrpc":"2.0","id":"1","method":"workspace/configuration","params":{"items":[{"section":"metals"}]}}
-> {"jsonrpc":"2.0","result":[null],"id":"1"}
<- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.10.29 14:21:04 ERROR Unexpected error initializing serverjava.lang.IllegalStateException: Not a JSON Object: null\n\tat com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)\n\tat scala.meta.internal.metals.MetalsLanguageServer.$anonfun$syncUserconfiguration$6(MetalsLanguageServer.scala:2711)\n\tat scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.lang.Thread.run(Thread.java:1589)\n"}}
```

### Expected behavior

I would expect no exception to be thrown, and for the startup process to continue to the next stage (e.g. with an empty config, the process currently continues like this:

```
<- {"jsonrpc":"2.0","id":"1","method":"workspace/configuration","params":{"items":[{"section":"metals"}]}}
-> {"jsonrpc":"2.0","result":[{}],"id":"1"}
<- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.10.29 14:30:06 WARN  Build server is not auto-connectable."}}
```

### Operating system

macOS

### Editor/Extension

Other

### Version of Metals

v0.11.9

### Extra context or search terms

The client is current HEAD version of the [helix editor](https://github.com/helix-editor/helix) with the default configuration.

(note one can work around the issue by creating an empty configuration for metals in the LSP config)

**Comment by tgodzik** [comment]
Thanks for reporting! We were missing one more Option wrapping. Fixing it in https://github.com/scalameta/metals/pull/4580

**Comment by fiadliel** [comment]
Thanks for the quick fix! Should work at startup for this editor now (given earlier bloop install) 🤞
