### ISSUE TITLE
importing an Ammonite script requires closing and re-opening after editing, if it failed on first try

### ISSUE THREAD

**Issue by balhoff** [scalameta/metals#4581]
**Describe the bug**

If I open an Ammonite script in VS Code, and the build import fails (such as due to a wrong Scala version specification in the header), I am not able to fix the issue by editing the file and re-importing the build. It only works if I close the file and re-open it. This is not too bad, but it was very confusing until I realized it.

**To Reproduce** Steps to reproduce the behavior:

1. Create a file called `test.sc` in an empty folder, containing this text (note there is a bad Scala version, `2.15.9`):

  ```scala
  // scala 2.15.9
  // ammonite 2.5.5
  
  @main
  def main(inputFile: os.Path) = {
    inputFile
  }
  ```

2. Open the file in a new VS Code window.
3. You will see a message in the VS Code console like this:

  ```
  2022.10.27 12:34:49 WARN  no build tool detected in workspace '/Users/jim/Desktop/metals-test'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
  2022.10.27 12:34:54 ERROR Error getting Ammonite 2.5.5 (scala 2.15.9)ammrunner.error.CoursierError: Error fetching Ammonite 2.5.5 for scala 2.15.9
  ```
5. Fix the Scala version by changing it to `2.13.9`.
6. Run `Metals: Import build` in VS Code.
7. See error in console:

  ```
  2022.10.27 12:35:30 WARN  no build target for: /Users/jim/Desktop/metals-test/test.sc
  2022.10.27 12:35:35 WARN  no build tool detected in workspace '/Users/jim/Desktop/metals-test'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
  ```
8. The script build wasn't imported; type-ahead autocomplete doesn't work.
9. Now if you close the file, and re-open it, the Ammonite build should be imported correctly, and autocomplete works.

**Expected behavior**

I expect that after correcting errors in the file, I can import the script build without closing and re-opening the file.

**Installation:**

- Operating system: MacOS 12.6
- VSCode version: 1.72.2
- VSCode extension version: 1.20.0
- Metals version: 0.11.9

**Comment by tgodzik** [comment]
Thanks for reporting! I moved it to the main repository.
