### ISSUE TITLE
goto def not working on scalaz.{Free,FreeAp}

### ISSUE THREAD

**Issue by bblfish** [scalameta/metals#4584]
### Describe the bug

I was trying to update some [source code](https://gist.github.com/camjo/d2dd391b5a44b55d407f041477341242) from an interesting talk from 2018 [An Intuitive Guide to Combining Free Monads and Free Applicatives](https://twitter.com/bblfish/status/1587052879986180097). But I found that I could goto definition on the other scalaz classes but not `Free` or `FreeAp`... I left `\/-` in the shortened example for you to try out.

I called the class `TestFree.scala` with the following content.
```scala
//> using scala "3.2.0"
import $ivy.`org.scalaz::scalaz-core:7.2.34`
import $ivy.`org.scalaz::scalaz-effect:7.2.34`
import $ivy.`org.scalaz::scalaz-iteratee:7.2.34`
import $ivy.`org.scalaz::scalaz-concurrent:7.2.34`

import scalaz.{-\/, Applicative, Coproduct, Free, FreeAp, Inject, Monad, NaturalTransformation, Nondeterminism, \/-, ~>}
import scala.language.{reflectiveCalls}
import scalaz.concurrent.Task
import Task._
import scala.util.Random

case class User(name: String, age: Int)

val c = \/-("hello")

case class ExecStrategy[F[_], A](fa: F[A]):
  val seq: Free[F, A] = Free.liftF(fa)
```

### Expected behavior

I should be ablet to `gD` in nvim to see the source of `Free` or `FreeAp` class. But nothing happens. This is also the case using VSC Insiders which downloads the latest scala metals.
On the other hand, IntelliJ jumps right to the source code.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.9

### Extra context or search terms

Here's the whole code in the directory with log files containing some long exception.

[FreeMonadAndApp.zip](https://github.com/scalameta/metals/files/9909195/FreeMonadAndApp.zip)

**Comment by bblfish** [comment]
The problem still appears in the code after I updated it to compile using Scala3:
https://github.com/bblfish/FreeMonadAndApplicative/blob/main/FreeWithFreeAp.scala

**Comment by tgodzik** [comment]
Thanks for reporting! This looks like an issue in scalameta:
```
2022.11.02 17:26:29 ERROR searching for `scalaz/Free.` failedorg.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying scala.meta.internal.trees.`package`.XtensionTreesType(tpe).isConstructable
found that scala.meta.internal.trees.`package`.XtensionTreesType(tpe).isConstructable is false
where tpe = (S ~> Free[T, *])
```
This should already be fixed in scalameta. Let's leave it open until new version is released and we can double check.

**Comment by caenrique** [comment]
Having the same problem with Fs2:

```
2022.11.10 12:46:56 ERROR searching for `fs2/Stream.` failedorg.scalameta.invariants.InvariantFailedException:
 invariant failed:
when verifying scala.meta.internal.trees.`package`.XtensionTreesType(tpe).isConstructable
found that scala.meta.internal.trees.`package`.XtensionTreesType(tpe).isConstructable is false
where tpe = (F ~> Stream[F, *])
```
