### ISSUE TITLE
Strange code folding with Scala 3

### ISSUE THREAD

**Issue by ohuu** [scalameta/metals#4629]
### Describe the bug

![image](https://user-images.githubusercontent.com/25370730/201133737-cad5b1a3-96e7-46cb-9fd8-d30ca2e6adfb.png)

This picture shows how the second fold isn't on the line that starts the function definition (the `def` line) but rather the line below it. For some reason the function definition is not seen as a fold region even though the one above is.

![image](https://user-images.githubusercontent.com/25370730/201135055-01f50a84-b4e9-42f0-9021-103f53368e0c.png)

This image shows the same code as before but with the second fold-region folded. As you can see the last line of the region isn't folded.

### Expected behavior

All `def`'s to start a fold region.

The final line of the all fold regions to be folded.

### Version of Metals

v0.11.9

**Comment by tgodzik** [comment]
Thanks for reporting! We should fold one more line in that case.
