### ISSUE TITLE
(Scala 3) invalid symbols in completions

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#4657]
### Describe the bug

In the following snippet, see completions inside the `map`:

```
//> using scala "3.2.1"

object demo {

  List(1, 3, 4).map { _ =>
    /*here*/
  }
}
```

You'll see `_$1: Int`, which will insert an underscore. That's not valid and will not compile.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/894884/202911974-64a48a1e-6b26-43a3-bba1-3a8d95608ca6.png">

Compared to Scala 2.13, where you don't get it:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/894884/202912081-5523075c-be11-4ae7-9543-d4742180da4d.png">

### Expected behavior

The `_$1: Int` completion doesn't show up.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by tgodzik** [comment]
Thanks for reporting! I looks like we are trying to suggest the synthetic name for `_`, we might need to filter some synthetics out.
