### ISSUE TITLE
Debugger & debuggee JVM version mismatch

### ISSUE THREAD

**Issue by zhongwm** [scalameta/metals#4683]
### Describe the bug

In debug cannot set debugger version.

When start debugging, debug output:
[Warn] The debugger and the debuggee are running in different versions of JVMs. You could see wrong source mapping results.
Debugger JVM version: 1.8.0_352
Debuggee JVM version: 17.0.5

in settings.json: {
  "metals.javaHome": "/usr/lib/jvm/default",
  "java.jdt.ls.java.home": "/usr/lib/jvm/default"
}

Even worse after I uninstall openjdk-8 I still get the same warning message.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

### Extra context or search terms

Happens either launch from editor or from launch.json.

**Comment by zhongwm** [comment]
Actually create a simple java file with a main in src/main/java, launch from editor, no such warning message in debug console.

**Comment by tgodzik** [comment]
Thanks for reporting! This shouldn't be a large issue unless you are debugging JDK source files. The Java version of debugger is the one of the BSP server run by Metals. If you run command `Metals: Run doctor` you should use the currently use Java version by metals to be sure. But this might actually be different than the build server, which should show up in the output (which version is used and where the configuration is located). You should be able to change it there manually and restart the build server if the metals didn't properly set that up.
