### ISSUE TITLE
LSP Semantic highlighting

### ISSUE THREAD

**Issue by ValdemarGr** [scalameta/metals#4685]
**Is your feature request related to a problem? Please describe.**

A Semantic Tokens feature has recently been added to vscode.
* https://github.com/microsoft/vscode/issues/85976
* https://github.com/microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample

**Describe the solution you'd like**

A killer feature for me in Intellij is the possibility to get context from colors.
I would like finer grained support through the new experimental token colorization.
![image](https://user-images.githubusercontent.com/22582195/71653160-40123480-2d2b-11ea-99f1-c7ace4bcfede.png)

**Search terms**:

Semantic Highlighting
Semantic Tokens
Semantic Colorization

**Comment by ckipp01** [comment]
Transferring this over to the main repo seeing that it's being worked on currently.

**Comment by tgodzik** [comment]
After merging https://github.com/scalameta/metals/pull/4444 we'll still need to work on
- [ ] semantic tokens benchmarks
- [ ] some refactors using changes made in the last few months 
- [ ] scala 3 support
- [ ] .sbt and .sc files support
- [ ] turn it on by default

**Comment by rcano** [comment]
Would it be possible to differentiate between declarations and usages for things like methods and classes in accordance to vscode selectors? this would allow much better themes that make the code easy to visually navigate.

**Comment by tgodzik** [comment]
Thanks for the question! I think we are limited by the LSP specification. I didn't see a separate flag for declaration I think 🤔

**Comment by rcano** [comment]
> Thanks for the question! I think we are limited by the LSP specification. I didn't see a separate flag for declaration I think thinking

If you scroll to the classifiers part [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-classification) you'll see `declaration`. In my VSCode `method.declaration` is validated correctly as a selector by vscode settings.

**Comment by rcano** [comment]
Also, I'm noticing there are a couple variable tokens that are not being classified as readonly:
* self types
* named parameters

**Comment by tgodzik** [comment]
@rcano could you send us the examples that do not work and report them as normal issues? It's something we should take a look at.

**Comment by tgodzik** [comment]
As for declaration/definition I am adding it here https://github.com/scalameta/metals/pull/5047.

Thanks for noticing it!

**Comment by jkciesluk** [comment]
I am changing parameters to readonly here https://github.com/scalameta/metals/pull/5049

**Comment by rcano** [comment]
I created the following issue to track the other tokens I was talking about: https://github.com/scalameta/metals/issues/5052

**Comment by tgodzik** [comment]
Semantic highlighting is now turned on by default and seems to be working well.
