### ISSUE TITLE
Abstract type reported as return type when wrapped in other type

### ISSUE THREAD

**Issue by martingd** [scalameta/metals#4686]
### Describe the bug

Consider this example:
```scala
trait Base:
    type T
    def f(t: T) = t
    def g(t: T): Option[T] = Some(t)

object Derived extends Base:
    override type T = Int

val x = Derived.f(42) // : Int = 42
val y = Derived.g(42) // : Option[T] = Some(42)
```

Metals reports the type of `y` as `Option[T]` and not as `Option[Int]` which is more precise and would better assist a programmer consuming class `Derived`.

### Expected behavior

I would expect the type for `y` to be reported as `Option[Int]` in the example above.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.20.0

### Extra context or search terms

I am not sure whether this issue is caused by dotty (the Scala 3 compiler) or Metals.

This issue might be related to #4339.

**Comment by tgodzik** [comment]
Thanks for reporting! I think there a couple of places we can show generics better.

**Comment by kasiaMarek** [comment]
It seems dotty `dealias` (in `Types`)  doesn't dealias params in an `AppliedType`. We can make a workaround for this in metals.

**Comment by martingd** [comment]
@kasiaMarek does this mean this is really a bug in dotty which should be reported?

**Comment by kasiaMarek** [comment]
> @kasiaMarek does this mean this is really a bug in dotty which should be reported?

Yes, I think so. Even if it's on purpose done this way, I’d be interested in the reasoning behind this.

**Comment by martingd** [comment]
I am not sure I know exactly what to report except copying what you wrote. :)
Would it be an idea for me to post a question on Discord in channel scala-users?

**Comment by kasiaMarek** [comment]
Oh, then don't worry about it. I'll create an issue. :)

**Comment by martingd** [comment]
Thanks. :)
