### ISSUE TITLE
Memory settings in .jvmopts is not picked up by the SBT process when using SBT as build server

### ISSUE THREAD

**Issue by JakobLyngPetersen** [scalameta/metals#4702]
### Describe the bug

[test.zip](https://github.com/scalameta/metals/files/10154345/test.zip)

1. Unzip the attached scala project. In the projects root folder it contains an .jvmopts file (with settings that are picked up by SBT when running SBT from the command line), a build.sbt file and a src folder with one file
2. Start VSCode/Metals in the projects root folder
3. Switch to using SBT as build server using the command "Metals: Switch build server"
4. (Inpecting what happens using visualvm shows that _first_ an SBT process is started (and it picks up the settings from .jvmopts). After a short while that process is terminated, and two other SBT processes are started. One is configured with `-Dsbt.io.virtual=true` and the other with `-Xms100m -Xmx100m`)
5. Open the generated file: `.bsp/sbt.json`. This file contains something like:
`{"name":"sbt","version":"1.7.1","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["C:\\Program Files\\Eclipse Adoptium\\jdk-8.0.352.8-hotspot\\jre/bin/java","-Xms100m","-Xmx100m","-classpath","C:\\path\\to\\test\\.bsp\\sbt-launch.jar","xsbt.boot.Boot","-bsp","--sbt-launch-jar=C:\\path\\to\\test\\.bsp\\sbt-launch.jar"]}`
Notice the settings `-Xms100m` and `Xmx100m`

### Expected behavior

I would expect the launched SBT BSP process to use the flags specified in `.jvmopts` (I guess the generated `.bsp/sbt.json` should be configured with those flags rather than the default `Xms` and `Xmx` flags.

NB! If I try to change the generated `.bsp/sbt.json` file manually so that it contains my custom flags, it seems to work, when I restart the build server. _But_ this file tends to get re-generated, if I close VS Code, stop all Java processes and open VS Code again. In any case, it would be a preferable option to use the settings specified in .jvmopts as that file can be checked in under source control.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.20.0

**Comment by dos65** [comment]
@JakobLyngPetersen This is the correct behaviour.
The value you see in `.bsp/sbt.json` aren't about jvm flag that will be taken by sbt-server process.
`"xsbt.boot.Boot","-bsp"` is an lightweight additional process that establishes connection between client and sbt-server and it doesn't need to use parameters from `.jvmopts`. If you look at the sbt-server process it should take correct flags.

I will close this issue. Feel free to reopen it if I was wrong in this explanation.

**Comment by tmiseikis** [comment]
@dos65 - As far as I can see Metals starts 2 sbt processes: 

1. As you say, the sbt-launch.jar that establishes connection between the client and the sbt-server. This process is always started with "-Xms100m" and "-Xmx100m" JVM arguments.
2. And the actual sbt-server process. This process seems to only have 1 JVM argument: "-Dsbt-io.virtual" and nothing else. As far as I understand, this is the process responsible for the actual compilation of Scala files and ends up with a Stackoverflow error when compiling large codebases.

This how this looks in VisualVM on my computer:

![image](https://user-images.githubusercontent.com/41424335/205740484-49a3097f-1695-4d43-ad4d-480af8cdb5d9.png)

**Comment by tmiseikis** [comment]
A related issue on sbt side, which apparently has been fixed a long time ago (but still doesn't work?): sbt/sbt#6575

**Comment by JakobLyngPetersen** [comment]
@dos65 , ok, I understand that the process I was looking at isn't the one to pick up the memory settings of `.jvmopts.` However, the core issue is still valid. I see the same as @tmiseikis points out: there are _two_ SBT processes. The one I was looking at in the original description and another one where the only JVM arguments are `-Dsbt.io.virtual=true`. I guess _that one_ is then responsible for the actual compilation. Hence, that is the process that should pick up the memory settings specified in `.jvmopts`.

So, in short, what I want to achieve (and which doesn't seem to work at the moment) is to control the memory settings of the process doing the compilation. This is possible when using bloop, and it should be possible when using sbt as a build server. I'm working on a large project that seems to cause troubles for bloop, but works fine using SBT from the command line (picking up the memory settings in `.jvmopts`). Consequently, I would like to use SBT as a build server (with those memory settings).

I hope this explains the issue further.

**Comment by dos65** [comment]
@JakobLyngPetersen Could you try to delete `.bsp/sbt.json`, then start sbt and check the content of a new created file?

I'm unable to reproduce this issue. The thing I noticed is that your `sbt.json` is a bit different and it should contain `-Dsbt.script` agrument that was added to avoid problem you described in  https://github.com/sbt/sbt/pull/6761

In my  case `sbt.json` is the following:
```
{"name":"sbt","version":"1.7.2","bspVersion":"2.0.0-M5","languages":["scala"],
  "argv":["/opt/homebrew/Cellar/openjdk@17/17.0.5/libexec/openjdk.jdk/Contents/Home/bin/java",
  "-Xms100m","-Xmx100m","-classpath","/Users/v.chelyshov/.sdkman/candidates/sbt/1.7.2/bin/sbt-launch.jar",
  "-Dsbt.script=/Users/v.chelyshov/.sdkman/candidates/sbt/current/bin/sbt","xsbt.boot.Boot","-bsp"]}
```

**Comment by dos65** [comment]
> One difference is that I'm running Windows

It might be the reason. Do you have `sbt.bat` in `PATH`? Sbt looks for it in case of Windows https://github.com/gontard/sbt/blob/780665a60c8492bc994e01f3f084ffdc03317d2f/protocol/src/main/scala/sbt/internal/bsp/BuildServerConnection.scala#L65

**Comment by JakobLyngPetersen** [comment]
@dos65 , yes `sbt.bat` is in my `PATH`.

**Comment by JakobLyngPetersen** [comment]
@dos65 , so I tried to play around with the snippet you linked to.
On my machine, when I run it, it doesn't find the path for `sbt.bat`
it seems that `sys.env.get("PATH")` returns `None` whereas `sys.en("PATH")` returns a String value with the content of my `PATH` environment variable. I have _no_ idea why it behaves like that, but it does.

So it seems that accessing the `PATH` environment variable from Scala on Windows needs to be done through `sys.env("PATH")` rather than `sys.env.get("PATH"`?

**Comment by dos65** [comment]
@JakobLyngPetersen thx for the investigations! I turned your last comment into PR - https://github.com/sbt/sbt/pull/7085

**Comment by JakobLyngPetersen** [comment]
Thank you @dos65. I guess we can close this issue for now.
