### ISSUE TITLE
Delusive NOOP go to references

### ISSUE THREAD

**Issue by prolativ** [scalameta/metals#4703]
### Describe the bug

Given a definition without any actual usage in the given project, e.g.
```scala
def foo = 1
```
running `Go to references` (or `cmd + click` on Mac) on `foo` doesn't give any visible results, creating an impression as if no action was performed at all which might suggest metals not fully working in the project.
This is however not the case: there's one reference found - the definition itself. The action is moving the cursor to the definition, but it's already there when a user clicks it so visually nothing changes.

### Expected behavior

The definition should be excluded from the search results for references and the user should see a message saying that a definition has no usages

### Operating system

macOS

### Editor/Extension

None

### Version of Metals

0.11.9+179-ea042f39-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! It looks like we don't check the `include declaration` flag currently.

**Comment by tgodzik** [comment]
Looks like this is a VS Code behaviour, so nothing we can do about it. We do check include declaration despite what I suggested first.

**Comment by kasiaMarek** [comment]
E.g. VSCode shows visual cues for this action. The action of moving cursor to the same place is marked by highlighting of the clicked name.
