### ISSUE TITLE
LSP metals won't load, stops configuration of SemanticDB in 2.13.10 projects

### ISSUE THREAD

**Issue by arigoldx** [scalameta/metals#4727]
### Describe the bug

I try to visit a file and see the following in emacs's `*Messsages*` buffer.

```
LSP :: Stopped configuration of Scala SemanticDB in 2.13.10 projects: Error downloading org.scalameta:semanticdb-scalac_2.13.10:4.4.32
  not found: /Users/arigold/.ivy2/local/org.scalameta/semanticdb-scalac_2.13.10/4.4.32/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.10/4.4.32/semanticdb-scalac_2.13.10-4.4.32.pom
```

I looked in the [maven folder](https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.10/) and, as per that second "not found" message above, there is nothing for 4.4.32

### Expected behavior

Pardon the simplicity but I expect it to load (like it used to).

### Operating system

macOS

### Editor/Extension

Emacs (lsp-metals)

### Version of Metals

1.2.0

**Comment by arigoldx** [comment]
I [checked](https://scalameta.org/metals/docs/editors/emacs) and scala version 2.13.10 looks to be supported 🤔.

**Comment by arigoldx** [comment]
I think the question is _why_ is it looking for version 4.4.32 when the only versions [in the folder](https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.10/) are versions 4.5 and 4.6 :eyes:.

**Comment by tgodzik** [comment]
That version is not expected to be used. What BSP server are you using? Is it sbt? sbt might have an older version of semanticdb configured, but it should get overriden by the metals plugin in `project/metals.sbt`

**Comment by arigoldx** [comment]
Yep, it's sbt. But I think that something is amiss because here's my `project/metals.sbt`:

```
// DO NOT EDIT! This file is auto-generated.

// This file enables sbt-bloop to create bloop config files.

addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.12")
```

**Comment by arigoldx** [comment]
Fwiw, I tried deleting the file but it was recreated exactly the same.

**Comment by tgodzik** [comment]
That's a super old version, do you have Bloop version overriden? What is the metals and Bloop version? You should be able to find that out by running the metals doctor

**Comment by arigoldx** [comment]
I don't think I have Bloop overriden and couldn't find anything when I searched.

I ran metals doctor (`lsp-metals-doctor-run`) and got the following:

> Build server currently being used is Bloop v1.4.12.

I didn't see a metals version but I see the following in my subprojects which makes me feel that metals is old too because [the docs](https://scalameta.org/metals/docs/editors/emacs) say 2.13.10 _is_ supported:

> Scala 2.13.10 is not yet supported, please downgrade to Scala 2.13.8.

I did a `list-packages` and see

> lsp-metals         1.2.0

**Comment by tgodzik** [comment]
I am not an expert in emacs, but how did you set up the metals executable? Maybe you need to redo it? 

```
Next you have to install metals server. Emacs can do it for you when lsp-mode is enabled in a scala buffer or via lsp-install-server command. Also you can do it manually executing coursier install metals and configuring $PATH variable properly.
```

you can try the second option and in that case coursier can update metals later on with one command

**Comment by arigoldx** [comment]
Thanks!

I'm not sure if it'll help with the emacs side but is 0.11.9 the current metals version as per [the main GitHub page](https://github.com/scalameta/metals)? I thought it might be good to know.

**Comment by tgodzik** [comment]
yes, that's the current stable version

**Comment by tgodzik** [comment]
Closing this as a current version of metals is needed as explained in the docs
```
Also you can do it manually executing coursier install metals and configuring $PATH variable properly.
```

https://scalameta.org/metals/docs/editors/emacs

**Comment by arigoldx** [comment]
Since I'm still stuck on this, I wanted to ask something. This was closed as per the above comment:

> Closing this as a current version of metals is needed as explained in the docs

but I actually think I have the right version of metals:

```
~  $ metals --version
metals 0.11.9

# Note:
#   Supported Scala versions:
#     Scala 3: 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.0-RC3, 3.2.0-RC4, 3.2.1-RC1, 3.2.1-RC2
#     Scala 2:
#       2.11.12
#       2.12.17, 2.12.16, 2.12.15, 2.12.14, 2.12.13, 2.12.12, 2.12.9, 2.12.10, 2.12.11
#       2.13.9, 2.13.5, 2.13.6, 2.13.7, 2.13.8, 2.13.1, 2.13.2, 2.13.3, 2.13.4
```

Maybe it's my bloop version that's old?

**Comment by tgodzik** [comment]
Metals should actually use a default version of Bloop and the support for specific Scala version is not tied to Bloop at all.

Essentially when using 0.11.9, the file generated should be:
```
// DO NOT EDIT! This file is auto-generated.

// This file enables sbt-bloop to create bloop config files.

addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.5.6")
```

and support for Scala 2.13.10 should beok within the doctor. You should also see the Metals version in the doctor aside from Bloop. Maybe it's using a wrong binary underneath actually?

**Comment by arigoldx** [comment]
Oh my, looks like I have quite a few binaries 😳

```
~  $ find / -name "metals" 2>/dev/null
/System/Volumes/Data/Users/arigold/Library/Application Support/Coursier/bin/metals
/System/Volumes/Data/Users/arigold/.emacs.d/.cache/lsp/metals
/System/Volumes/Data/Users/arigold/.emacs.d/.cache/lsp/metals/metals
/Users/arigold/Library/Application Support/Coursier/bin/metals
/Users/arigold/.emacs.d/.cache/lsp/metals
/Users/arigold/.emacs.d/.cache/lsp/metals/metals
```

I'll sort that out and hopefully that'll do it 😅.

Thanks again!

**Comment by arigoldx** [comment]
I shoulda pruned (and read through 🙄) that list above since there are a few dupes in it but I think I at least figured out the metals binary part:

```
Metals Doctor

Build server currently being used is Bloop.

Metals Java: 1.8.0_161 from Oracle Corporation located at /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre

Metals Server version: 0.11.9

These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

⚠️ No build targets were detected in this workspace so most functionality won't work.

* Make sure the workspace directory '/Users/arigold/src/0mercury' matches the root of your build.
* Try removing the directories .metals/ and .bloop/, then restart metals And import the build again.
```

I tried the two suggestions but no :game_die::game_die:.

Figured I'd keep posting fixes in case someone else stumbles across this...

..._and_ when it's all said and done, I'll update docs 👼.

**Comment by tgodzik** [comment]
> Maybe in [the emacs section within editors](https://github.com/scalameta/metals/blob/main/docs/editors/emacs.md)? 

That's always good to update! I lack the emacs expertise and can't update it myself unfortunately. (I did promise to try setting up emacs myself, but I think I might never get to it :sweat_smile: )
