### ISSUE TITLE
Compilation of dependencies sources does not work when landing from workspace/symbols

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#474]
Potentially related to #473 

### Steps to reproduce

- use `workspace/symbols` to search `scala.Option`
- try find reference or go to definition on anything

### Expected result
- the action is performed successfully

### Actual result
- PC crashes
- If the attempted action is "go to definition", it prints also

```
code navigation does not work for the file '/Users/gabro/buildo/PROJECT/api/.metals/readonly/scala/Option.scala' because it doesn't belong to a build target.
```

**Comment by olafurpg** [comment]
I can reproduce. We'll need to rethink how to infer the classpath for dependency sources 🤔
