### ISSUE TITLE
The lenses for scala-cli scripts run/debug Appear to run in the wrong Directory

### ISSUE THREAD

**Issue by LaurenceWarne** [scalameta/metals#4752]
### Describe the bug

Hi, I've noticed that `run`/`debug` lenses run within scala-cli scripts (both lenses for individual main functions and the whole script) have their working directory set to `.scala-build` rather than the directory of the script.  To reproduce, create a directory structure like so:
```
dir
└── run.sc
```

With the contents of `run.sc`:

```scala
val curDir = System.getProperty("user.dir")
println(curDir)
```
And run the script lens appearing at the top of the file.    Something like `/my/dir/.scala-build` should show up. 

### Expected behavior

I think I'd prefer it if the directory was set to the directory of the script, so it would be consistent with running:
```
$ scala-cli run.sc
```
From a terminal in the project root.  This can be annoying if you're trying to read files from the same directory as your script.

### Operating system

Linux

### Editor/Extension

Emacs (lsp-metals)

### Version of Metals

I built from master today (commit 4a2c5caa9a) - I don't think https://github.com/scalameta/metals/pull/4605 and https://github.com/scalameta/metals/pull/4729 have been released yet (:

### Extra context or search terms

My Scala-Cli version is `0.1.19`  (using Scala `3.2.1`).

Thanks!

**Comment by tgodzik** [comment]
Thanks for reporting! Could you check with the newest scala-cli 0.1.19? I think a fix for that landed there.

**Comment by LaurenceWarne** [comment]
> Thanks for reporting! Could you check with the newest scala-cli 0.1.19? I think a fix for that landed there.

I've upgraded and got the same result unfortunately, do you happen to have a link to the fix (had a quick look at the release notes but didn't see anything)?

**Comment by tgodzik** [comment]
Ach my bad, that will need another release. You should be able to test it out on nightly or wait for the next release of scalacli

**Comment by LaurenceWarne** [comment]
Just built scala-cli from source and it works now thanks!
