### ISSUE TITLE
[VSCode] Completion suggestions aren't refreshing during typing one by one character

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#4756]
### Describe the bug

I stated digging a bit what is going on and noticed that in this case  often doesn't ask LSP server for more completion even if prev result returns `isIncomplete = true`

Project setup:
```scala
// build.sbt

scalaVersion := "2.13.10"
libraryDependencies ++= List("com.typesafe.play" %% "play-json" % "2.9.3")

// src/main/scala/sample/sample.scala

package sample

class Sample {
  Json // <- issue here - no completions if you start typing `Json` one by one character
          //  in theory after having 3 char in query (`Jso@@`) there should be results  but there is no request to LSP 
  Json@@ // <- triggering it using shortcut after typing works well
}
``` 

It looks like a specific issue of vscode or metals-extension.
Extension version: Pre-release `v1.20.9`
VSCode version: 1.74.2

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.9+213-4ab55247-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like this is an issue in VS Code https://github.com/microsoft/vscode/issues/155738

I see some workaround mentioned there.

**Comment by dos65** [comment]
> Thanks for reporting! Looks like this is an issue in VS Code https://github.com/microsoft/vscode/issues/155738

> I see some workaround mentioned there.

oh, cool. It seems like in this case for VSCode we can return some fake completion like "complete typing ..." without text edit

**Comment by ckipp01** [comment]
Just confirming that I have tried this in another client (Neovim) and the issue doesn't exist there.
