### ISSUE TITLE
[sbt server] Infinite compilation loop

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#4772]
### Describe the bug

Reproduction steps:
1. Create an sbt project
2. Add a source generator in the `build.sbt`:
```scala
Compile / sourceGenerators += Def.task {
  val content = 
    s"""|object Foo
        |""".stripMargin
  val file = target.value / "generated" / "src" / "main" / "scala" / "Foo.scala"
  IO.write(file, content)
  List(file)
}
```
3. Import the project in Metals using sbt as the build server using `Metals: switch build server`

The problem here is that the `buildTarget/scalaMainClasses` request triggers the source generation (and a compilation). Metals realize that the generated source changed and so it send a new `buildTarget/compile` request and a new `buildTarget/scalaMainClasses` request. The loop never ends.

### Expected behavior

Metals should not loop. It should run `buildTarget/compile` and `buildTarget/scalaMainClasses` only once.

To fix this issue, I think we can stop watching the generated sources.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by ckipp01** [comment]
We did a similar fix like this for https://github.com/scalameta/metals/issues/2183. We can probably implement the same type of thing by checking `generated`.

**Comment by adpi2** [comment]
Thanks @ckipp01 I assigned myself to try and fix it.
