### ISSUE TITLE
Incorrect message about sbt build diagnostics when using sbt as a build server

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#4781]
### Describe the bug

When working in a brand new sbt project with sbt as your build server the Metals Doctor indications that diagnostics for the build are only syntactic. However, this is incorrect as you can get actual errors from sbt about mistakes in your build file.

_Steps to reproduce_

- `g8 scala/hello-world.g8`
- Open the project, ignore the build import
- Switch build server to sbt
- Execute the Metals doctor and you should see the following

```
### root-build
  - target type: sbt 1.8.0
  - compilation: ✅ 
  - diagnostics: ⚠️ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ❌
  - java: ⚠️ 
  - recommendation: Diagnostics and debugging for sbt are not supported currently.

### Diagnostics:
✅  - diagnostics correctly being reported by the build server
⚠️  - only syntactic errors being reported
```

- Then in your `build.sbt` change `name := "test"` to `name :=  3`
- Save and say yes to retrigger the import
- See the following diagnostic

```
Diagnostics:
type mismatch;
 found   : Int(3)
 required: String
```

### Expected behavior

I'd expect the Doctor to reflect that actual diagnostics can be reported in this situation.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.9+239-9d45bd2b-SNAPSHOT

### Extra context or search terms

This is tested with sbt 1.8.0.

**Comment by tgodzik** [comment]
Och, I assumed this was the case, I had no idea it worked! Great to hear it!
