### ISSUE TITLE
No Test Explorer or Run/Debug Code Lens on Cross Project

### ISSUE THREAD

**Issue by valencik** [scalameta/metals#4782]
### Describe the bug

1. Run `sbt new typelevel/typelevel.g8` and accept all the defaults.
2. Open the newly created project in VSCode with Metals, note no tests found:
![image](https://user-images.githubusercontent.com/5440389/210003388-0403a837-bc6e-4809-89d5-c66f1b0825d9.png)

If we change the build in `build.sbt` from

```scala
lazy val core = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .in(file("core"))
  //...
```
to 
```scala
lazy val core = project
  .in(file("core"))
```

and let Metals reimport/reindex the build, we get tests and code lens:

![image](https://user-images.githubusercontent.com/5440389/210003697-731ece12-43f1-4023-90cb-926cd132ceeb.png)

### Expected behavior

Test explorer and Code lens should show up and work as normal with crosscompiled projects

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by kasiaMarek** [comment]
This seems to be on `bloop`. Metals sends `buildTarget/scalaTestClasses` to collect information about tests but bloop just doesn't reply.

**Comment by tgodzik** [comment]
Looks like part of the problem was https://github.com/scalacenter/bloop/pull/2104 and at least the compilation would work. Can be tested with Bloop `1.5.8-4-b8701857-SNAPSHOT` <- main problem was that typelevel projects seem to have more options, which caused the bug in Bloop to show.

**Comment by tgodzik** [comment]
And it seems the other issue is https://github.com/scalacenter/bloop/pull/2107 

The node_modules directory was missing and I am not sure why and how it's setup in the project, since we need node_modules for sure.

**Comment by kasiaMarek** [comment]
Fixed on bloop side.
