### ISSUE TITLE
The `Indexing` status is hanging forever, and the extension is stalled.

### ISSUE THREAD

**Issue by dzx-dzx** [scalameta/metals#4786]
### Describe the bug

This bug seems to occur in multiple recent versions. A proxy is used to initialize the server through setting `metals.serverProperties`.

0. This bug will occur after the extension put on a notice that a new version for `metals` is available, to which I give my consent. However this is not a prerequisite: sometimes it will be triggered randomly.
1. After waiting for the download, the following happens:
  * The final log is as follows:
  ```
Java home: /usr/lib/jvm/java-17-openjdk-amd64
Metals version: 0.11.9+243-3cbb04ef-SNAPSHOT
2022.12.30 22:51:49 INFO  logging to file /home/***/###/.metals/metals.log
2022.12.30 22:51:49 INFO  Started: Metals version 0.11.9+243-3cbb04ef-SNAPSHOT in workspace '/home/***/###' for client Visual Studio Code 1.74.2.
2022.12.30 22:51:50 INFO  time: initialize in 0.57s
Initializing Scala Debugger
Release notes was not shown: not showing release notes since they've already been seen for your current version
2022.12.30 22:51:51 INFO  Attempting to connect to the build server...
2022.12.30 22:51:51 INFO  Bloop uses /usr/lib/jvm/java-17-openjdk-amd64 defined at /home/***/.bloop/bloop.json
2022.12.30 22:51:51 INFO  skipping build import with status 'Installed'
2022.12.30 22:51:51 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/***/###/.metals/bsp.trace.json or /home/***/.cache/metals/bsp.trace.json
2022.12.30 22:51:51 INFO  Attempting to connect to the build server...
2022.12.30 22:51:51 INFO  Bloop uses /usr/lib/jvm/java-17-openjdk-amd64 defined at /home/***/.bloop/bloop.json
2022.12.30 22:51:51 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/***/###/project/.metals/bsp.trace.json or /home/***/.cache/metals/bsp.trace.json
2022.12.30 22:51:51 INFO  time: Connected to build server in 0.57s
2022.12.30 22:51:51 INFO  Connected to Build server: Bloop v1.5.6
  ```
  * Buttons from the section `BUILD COMMANDS` shows up as if the server starts successfully. But the `Run doctor` button in `HELP AND FEEDBACK` becomes unresponsive.
  * Finally, in the status bar the `Indexing` keeps on for at least 2 hours.
2. Re-`Import build`, `Restart build server` or reload the vscode window does not work. But reboot the system(`wsl --shutdown` for me) seems do.

### Expected behavior

The `Indexing` will disappear in seconds. 

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9+243-3cbb04ef-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! Does it happen with a particular project or randomly in any of the projects? Can you take a look into `.metals/metals.log` if it has some more details? If I understand correctly you are using WSL 2 (or 1?) on widnows?

**Comment by dzx-dzx** [comment]
> Does it happen with a particular project or randomly in any of the projects?

Hmm... Sorry I haven't opened other projects recently, so that's not yet known.

> Can you take a look into `.metals/metals.log`

I'm afraid what has been posted is all I've got. Maybe I should attempt to modify the server version to trigger this issue again?

> If I understand correctly you are using WSL 2 (or 1?) on widnows?

WSL2.

**Comment by tgodzik** [comment]
I think the issue might be with the stuff that is downloaded by Bloop. Could you possibly add the proxy settings also to `Metals: Bloop Jvm Properties` ? Alternatively if you use sbt you can try running with sbt via BSP by using `Metals: Switch build server` command

**Comment by dzx-dzx** [comment]
I will try later. But is there a method to reproduce the problem other than modifying the server version setting, or waiting for a new one?

**Comment by dzx-dzx** [comment]
Now it happens again. The Metals version is updated to `0.11.10` and the OS is switched to Windows, and the issue appears again for a different project.

---

> Could you possibly add the proxy settings also to `Metals: Bloop Jvm Properties` ?
```
"metals.bloopJvmProperties": [
  "-Dhttp.proxyPort=###",
  "-Dhttp.proxyHost=###"
]
```
Is this what I should modify?

**Comment by tgodzik** [comment]
> Is this what I should modify?

I think so, let me know if it helps!

**Comment by dzx-dzx** [comment]
Ah great, the issue has disappeared.
It seems that `http.proxy` does nothing at all, I must use `https.proxy` instead.

**Comment by tgodzik** [comment]
Glad to hear it! We might need to update https://scalameta.org/metals/docs/troubleshooting/proxy a bit further and make more discoverable :thinking:
