### ISSUE TITLE
metals-vim: List is not implemented in gtk error

### ISSUE THREAD

**Issue by jan0sch** [scalameta/metals#479]
Hi,

I just tried metals with neovim on FreeBSD 11.2 and got the following error message:

```
[lsc:Error] StdErr from metals-vim: ^@(<unknown>:22541): GVFS-RemoteVolumeMonitor-WARNING **: 10:3...List is not implemented on interface org.gtk.Private.RemoteVolumeMonitor (g-dbus-error-quark, 19)^@
```

The rest seems to work but navigation (goto definition) does not.

### Environment

I'm using metals 0.3.3.

```
% freebsd-version -ku
11.2-RELEASE-p8
11.2-RELEASE-p8
% pkg info -E neovim
neovim-0.3.2
% pkg info | grep -i ^gtk
gtk12-1.2.10_27                Gimp Toolkit for X11 GUI (previous stable version)
gtk2-2.24.32                   Gimp Toolkit for X11 GUI (previous stable version)
gtk3-3.22.30_4                 Gimp Toolkit for X11 GUI (current stable version)
```

**Comment by gabro** [comment]
Hi @jan0sch, thanks for reporting?

Do logs say anything useful? (see https://scalameta.org/metals/docs/contributors/getting-started.html#workspace-logs)

**Comment by jan0sch** [comment]
No, looked good. Here it is just in case.

I am also not sure if it is directly related to metals or the vim-lsc plugin. :thinking: 

```
Jan 21, 2019 10:34:59 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.6.5.Final
Jan 21, 2019 10:34:59 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.6.5.Final
Jan 21, 2019 10:34:59 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.3.0.Beta2
INFO  Started Metals http server at http://127.0.0.1:5031
INFO  The server is listening for incoming connections at local:///tmp/bsp1082522203047515795/-1an0obv9tnq7z.socket...
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at ~/.cache/metals/bsp.trace.json
INFO  time: connected to build server in 0,53s
INFO  Accepted incoming BSP client connection at local:///tmp/bsp1082522203047515795/-1an0obv9tnq7z.socket
INFO  request received: build/initialize
INFO  BSP initialization handshake complete.
INFO  time: imported workspace in 3,08s
```

**Comment by gabro** [comment]
Looks look fine on the Metals side. Judging by the error you get, it seems like a vim-lsc issue, possibly related to the NeoVim integration.

You can maybe try with a vanilla `vim` installation and see whether you have the same issue.

In any case, I suggest you ask in https://github.com/natebosch/vim-lsc

**Comment by jan0sch** [comment]
With vscode it doesn't seem to work at all. However the vscode ports to FreeBSD are unofficial as far as I understand. :thinking:

**Comment by olafurpg** [comment]
How about Atom? I'm not so familiar with FreeBSD, are there differences for JDK-related applications I should be aware of? Does IntelliJ work?

**Comment by jan0sch** [comment]
IntelliJ and other java stuff works fine. But there are problems with atom, vscode, lighttable etc. Therefore I can only use unofficial builds for these.
So far I had not trouble but I want migrate from ensime to metals because for the most time I'm using vim/neovim.

**Comment by olafurpg** [comment]
We also use `java.awt.Desktop.getDesktop.browse(URI.create(url))` if you click on "Learn more" or "More information" in the doctor dialogues

**Comment by jan0sch** [comment]
The GVFS part seems to indicate that. Could you give me a pointer to the relevant code sections?
I will take a deeper look when I've some time.

**Comment by jan0sch** [comment]
For reference: The same error message appeared in the following issue: https://github.com/kpeeters/cadabra2/issues/12

**Comment by olafurpg** [comment]
Another native component we use is local UNIX domain sockets to communicate with the build server.

**Comment by olafurpg** [comment]
Here's where we open a URL https://github.com/scalameta/metals/blob/e6424034e832e2eee95e6b341643a24331ac1f72/metals/src/main/scala/scala/meta/internal/metals/Urls.scala#L28 

It's only executed if you select "learn more" in a dialogue. You can test local changes with `publishLocal` and update the coursier bootstrap command to use 0.4.0-SNAPSHOT (or version published).

**Comment by jan0sch** [comment]
After digging around a bit I think that it is likely caused by [nuprocess](https://github.com/brettwooldridge/NuProcess) so I'm going to investigate it.

**Comment by olafurpg** [comment]
@jan0sch I'm gonna move this issue to the metals-feature-requests issue tracker since we don't officially support FreeBSD. I'm happy to help you fix this issue, but even if this issue gets fixed our CI does not run tests on FreeBSD to prevent regressions in the future.
