### ISSUE TITLE
Worksheet gets stuck in loop

### ISSUE THREAD

**Issue by spamegg1** [scalameta/metals#4796]
### Describe the bug

Worksheet gets stuck in an infinite loop while evaluating the code below.

1. Create a worksheet
2. Paste the following code:
```scala
class Animal(age: Int)

class Rabbit(age: Int) extends Animal(age):
  val id = Rabbit.tag
  Rabbit.tag += 1
  def getId = id

object Rabbit:
  val basic = Rabbit(0)
  var tag: Int = 0

val peter = Rabbit(2)
```
3. Save file, wait for the worksheet to evaluate:
![Screenshot_from_2023-01-01_22-40-18](https://user-images.githubusercontent.com/4255997/210231701-4cba6cfb-255a-4dbc-8fa5-a450c039497b.png)

### Expected behavior

Evaluation of the worksheet should complete in a few seconds.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.20.0

**Comment by tgodzik** [comment]
Thanks for reporting! This might require some work in scalameta/mdoc

**Comment by spamegg1** [comment]
#6262 has the negative side effect of being unable to run computations in worksheets that take longer than 30 seconds. Is there a way to control the timeout length?

**Comment by kasiaMarek** [comment]
> Is there a way to control the timeout length?

Not yet, I guess I didn't expect anyone to need over 30 sec for worksheet eval.
