### ISSUE TITLE
incorrect syntax error highlight for if expression

### ISSUE THREAD

**Issue by doofin** [scalameta/metals#4810]
### Describe the bug

for metals v0.11.10 and vscode-metals v21.0:  
![image](https://user-images.githubusercontent.com/6041353/210547280-d13efab8-b850-4930-a85b-4787fe4aadf0.png)

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.10

**Comment by tgodzik** [comment]
Thanks for reporting! Could you add the problematic snippet, so that we can check it out and maybe add to some tests?

**Comment by doofin** [comment]
```scala
def hammingDistance(x: String, y: String) = {
    x.zip(y).map((a, b) => if a == b then 0 else 1).sum
  }
```

**Comment by tgodzik** [comment]
Looks like maybe it's a stale error, does it go away if you remove and readd the code? Is the code correctly treated as Scala 3? Anything in the logs that might have failed and maybe led to the issue with stale error?

**Comment by doofin** [comment]
Thanks,the problem seems to be an unresolved dependency in sbt that metals just quietly failed without warnings,now it's fine.
