### ISSUE TITLE
ERROR No project associated with URI after indexing

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals#4824]
### Describe the bug

Metals sends an error after indexing the project even in a fresh project
```
:: <-  metals metals/status: {'text': 'Indexing⠇'}
metals: 2023.01.06 14:43:40 INFO  time: indexed workspace in 7.84s
:: <-  metals window/logMessage: {'type': 4, 'message': '2023.01.06 14:43:40 INFO  time: indexed workspace in 7.84s'}
metals: 2023.01.06 14:43:40 ERROR No project associated with Uri(file:/Users/ayoub.benali/Workspace/hello-world-template/?id=hello-world-template-test)
metals: 2023.01.06 14:43:40 ERROR No project associated with Uri(file:/Users/ayoub.benali/Workspace/hello-world-template/project/?id=hello-world-template-build)
:: <-  metals window/logMessage: {'type': 4, 'message': '2023.01.06 14:43:40 ERROR No project associated with Uri(file:/Users/ayoub.benali/Workspace/hello-world-template/?id=hello-world-template-test)'}
:: <-  metals window/logMessage: {'type': 4, 'message': '2023.01.06 14:43:40 ERROR No project associated with Uri(file:/Users/ayoub.benali/Workspace/hello-world-template/project/?id=hello-world-template-build)'}
metals: 2023.01.06 14:43:40 INFO  {
  "jsonrpc": "2.0",
  "id": "9",
  "error": {
    "code": -32600,
    "message": "No project associated with Uri(file:/Users/ayoub.benali/Workspace/hello-world-template/project/?id\u003dhello-world-template-build)"
  }
}
metals: 2023.01.06 14:43:40 INFO  {
  "jsonrpc": "2.0",
  "id": "9",
  "error": {
    "code": -32600,
    "message": "No project associated with Uri(file:/Users/ayoub.benali/Workspace/hello-world-template/?id\u003dhello-world-template-test)"
  }
}
```
Steps to reproduce: 
1. `sbt new scala/hello-world.g8`
2. open the created project with your editor example `subl .`
3. Import build when prompted
4. notice the logged error with `?id\u003` at the end of the URI

This problem doesn't happen with `0.11.10` so the regression should be in one the more recent PRs

### Operating system

macOS

### Editor/Extension

Sublime

### Version of Metals

0.11.10+24-3dd9d896-SNAPSHOT

**Comment by ckipp01** [comment]
Thanks for the report @ayoub-benali. Does that happen for you on a fresh hello world project?

**Comment by tgodzik** [comment]
`\u003` seems to be correct, it's just encoded `=` and it has always been there :thinking: Are you maybe able to pinpoint which change broke it for you?

**Comment by ayoub-benali** [comment]
> Thanks for the report @ayoub-benali. Does that happen for you on a fresh hello world project?

Yes it happens with a fresh `sbt new scala/hello-world.g8`, I edited the issue.

**Comment by ayoub-benali** [comment]
> Are you maybe able to pinpoint which change broke it for you?
@tgodzik where can I find the list of the snapshot releases after `0.11.10` ?

**Comment by tgodzik** [comment]
Actually, it seems I can reproduce also :thinking:

**Comment by tgodzik** [comment]
Looks like https://github.com/scalameta/metals/pull/4777 broke it :O

**Comment by tgodzik** [comment]
Though I have no idea how :sweat_smile:

**Comment by tgodzik** [comment]
Ach, I think I know what is happening, we are asking for a build target on a wrong connection. I will try to take a look at it a bit later unless anyone has time now.
