### ISSUE TITLE
Scala 3: Missing go-to-definition when type parameter is inferred

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#4834]
### Describe the bug

In some situations, it appears that Metals doesn't provide a definition for a constructor call where a type parameter is inferred.

To reproduce:

1.

```scala
//> using scala "3.2.1"

trait Service

object Service {
  def impl[F]: Service = new Impl("42")

  class Impl[F](s: String) extends Service
}
```

2. Look for definitions in: `def impl[F]: Service = new Im@@pl("42")`

3. See nothing

### Expected behavior

The definition for `class Impl` is provided.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.10

### Extra context or search terms

This doesn't appear to happen in Scala 2.13.10. I'm using scala-cli 0.1.19 as the build server.

LSP trace log:

```
[Trace - 11:53:03 PM] Received request 'textDocument/definition - (1304)'
Params: {
  "textDocument": {
    "uri": "file:///Users/kubukoz/projects/demos/main.scala"
  },
  "position": {
    "line": 5,
    "character": 35
  }
}


[Trace - 11:53:03 PM] Sending response 'textDocument/definition - (1304)'. Processing request took 21ms
Result: []
```

Interestingly, the `textDocument/hover` response looks fine. This can also be fixed by specifying the type parameter - `new Impl[F]` shows the right definition.

**Comment by ckipp01** [comment]
Thanks for the report @kubukoz, I'm able to reproduce this .

**Comment by kasiaMarek** [comment]
It seems to work with the latest snapshot, though I did see the issue on `0.11.10`. Can you check that it behaves as expected on with `0.11.10+166-3a9ab1d7-SNAPSHOT`?

**Comment by tgodzik** [comment]
@kasiaMarek I think that might be the fallback that works here, do you get:
`WARN  Using indexes to guess the definition of Impl` 
in the logs?

Ideally, we would have the compiler provide the definition here.

**Comment by kasiaMarek** [comment]
@tgodzik, no I don't. Also, I tried with:
```
object Demo {
  class Impl[F](s: String) extends Service
}

trait Service

object Service {
  def impl[F]: Service = new Impl("42")

  class Impl[F](s: String) extends Service
}
```
And finds only the correct one. I don't think that'd be the case for `fallback`.

**Comment by tgodzik** [comment]
Just confirmed, curious which PR fixed this :sweat_smile: I will count it as a win, thanks for checking @kasiaMarek !
