### ISSUE TITLE
Rename incorrectly replaces type parameter inside classOf

### ISSUE THREAD

**Issue by rochala** [scalameta/metals#4844]
### Describe the bug

```scala
object Test {
  classOf[String]

  def test() = {
    val testVal = "test"
  }
}
```

Rename value `testVal` and see that type `String` inside classOf is also renamed to the new value.

```scala
object Test {
  classOf[testValNew]

  def test() = {
    val testValNew = "test"
  }
}
```

It only happens when classOf is outside the scope of the renamed value.

### Expected behavior

It shouldn't rename classOf type parameter
```scala
object Test {
  classOf[String]

  def test() = {
    val testValNew = "test"
  }
}
```

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

metals 0.11.10+31-181ba661-SNAPSHOT

### Extra context or search terms

Related issue: https://github.com/scalameta/metals/issues/2681

**Comment by tgodzik** [comment]
Thanks for reporting! It seems we are incorrectly finding the symbol for the local value outside of it's scope. Most likely related to PcCollector. I will take a quick look.
