### ISSUE TITLE
Convert to named arguments shouldn't be offered for Java classes

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#4851]
### Describe the bug

Let's say you have a piece of code like this, which is creating a Java class:

```scala
new BspConnectionDetails(
  BloopServers.name,
  ImmutableList.of(),
  userConfig().currentBloopVersion,
  "",
  ImmutableList.of(),
)
```

_Code is [here](https://github.com/scalameta/metals/blob/180a254b16c6bd12ab5bf3934e880f9859466101/metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala#L226-L232) if you're curious_

If you are inside of `BspConnectionDetails` you'll notice there is a code action to convert to named arguments, which would result in in broken code:

```scala
new BspConnectionDetails(
  x$1 = BloopServers.name,
  x$2 = ImmutableList.of(),
  x$3 = userConfig().currentBloopVersion,
  x$4 = "",
  x$5 = ImmutableList.of(),
)
```

### Expected behavior

I'd expect the code action to never be offered in a situation where it'd break my code.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.10+39-180a254b-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! The only problem I see is that we will know it's actually a Java class when invoking the code action, so maybe it's ok to just show the user a message? `Named arguments can't be used on Java files` ?

**Comment by ckipp01** [comment]
> Thanks for reporting! The only problem I see is that we will know it's actually a Java class when invoking the code action, so maybe it's ok to just show the user a message? `Named arguments can't be used on Java files` ?

I think that's fine. I think that behavior is probably better than broken code 😆
