### ISSUE TITLE
Odd type inference

### ISSUE THREAD

**Issue by UtilFunction** [scalameta/metals#4858]
### Describe the bug

Take this simple example using ZIO Layers:

```scala
import zio.*

final case class Dependency()

object Dependency:
  val layer = ZLayer.fromFunction(Dependency.apply _)
```

### Expected behavior

The infered type Metals provides is:
```scala
 WithOut[() => Dependency, ZLayer[Any, Nothing, Dependency]]#Out
 ```
but should be:
```scala
ZLayer[Any, Nothing, Dependency]
```

### Operating system

Windows 11

### Editor/Extension

VSCode

### Version of Metals

v0.11.10

### Extra context or search terms

In action:
![Code_GlvVJWBMti](https://user-images.githubusercontent.com/81699220/212359913-a349eb1d-28e1-47da-a633-e7303dd9cf00.png)

**Comment by tgodzik** [comment]
Thanks for repoting! It might be an issue with how the semanticdb is generate in the compiler :thinking:
