### ISSUE TITLE
Fails to run application if JAVA_HOME contains space (Windows)

### ISSUE THREAD

**Issue by BalduinLandolt** [scalameta/metals#4862]
### Describe the bug

On any simple hello world application, when hitting the `run` button in VS Code, execution fails with the following terminal output:

```bash
 *  Executing task: C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java -Duser.dir=C:\Users\baldu\git\metals-test -classpath C:\Users\baldu\git\metals-test\.bloop\root\bloop-bsp-clients-classes\classes-Metals-8U1nbSLRSSC4ExF-lDe8hw==;C:\Users\baldu\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.8\scala-library-2.13.8.jar example.Hello  

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

 *  The terminal process "cmd.exe /c C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java -Duser.dir=C:\Users\baldu\git\metals-test -classpath C:\Users\baldu\git\metals-test\.bloop\root\bloop-bsp-clients-classes\classes-Metals-8U1nbSLRSSC4ExF-lDe8hw==;C:\Users\baldu\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.8\scala-library-2.13.8.jar example.Hello " terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

Clearly, this happens because there is a space in my `JAVA_HOME`.

When I copy the command
```bash
C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java -Duser.dir=C:\Users\baldu\git\metals-test -classpath C:\Users\baldu\git\metals-test\.bloop\root\bloop-bsp-clients-classes\classes-Metals-8U1nbSLRSSC4ExF-lDe8hw==;C:\Users\baldu\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.8\scala-library-2.13.8.jar example.Hello  
```
manually to my terminal, I get the same error.

If I add quotation marks around my java path, it works, like so:
```bash
"C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java" -Duser.dir=C:\Users\baldu\git\metals-test -classpath C:\Users\baldu\git\metals-test\.bloop\root\bloop-bsp-clients-classes\classes-Metals-8U1nbSLRSSC4ExF-lDe8hw==;C:\Users\baldu\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.8\scala-library-2.13.8.jar example.Hello
```

I think/hope this is only about escaping/quoting the java path.

### Expected behavior

When running the application, it would be nice, if the application would execute, rather than getting an error. :)

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.10

**Comment by Abhijeetmishr** [comment]
@BalduinLandolt check your java path is set in windows environment variable.

**Comment by BalduinLandolt** [comment]
@Abhijeetmishr thanks for replying so quickly. Indeed it is set (`echo %PATH%` contains it, `java --version` works, `where java` finds it, etc.).

Like I wrote in the description, the blank space must be the issue at hand:

```
java --version
```

works.

```
where java
```

gives me

```
C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java.exe
```

if I call

```
C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java.exe --version
```

I get

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

but if I call

```
"C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java.exe" --version
```

it works again.

So clearly the terminal is not happy with the blank space there either - which is the same behaviour as I get in VSCode with metals.

**Comment by tgodzik** [comment]
Could you check the newest snapshot of Metals? I think that should be fixed there. You can use `0.11.10+49-deb96896-SNAPSHOT` version. I will start working on a release next week most likely.

**Comment by mlhales** [comment]
Can confirm, release version broken for us, but snapshot version works.

**Comment by rmpasswd** [comment]
### How to update to the latest metals snapshot version in vscode:
1. Open command palette.
2. Type "user settings" and select the non-JSON option
3. Search for "server version"
4. paste the version number from https://scalameta.org/metals/docs/editors/vscode/#using-latest-metals-snapshot

![image](https://user-images.githubusercontent.com/35218856/216279105-8f602e55-3bc1-406f-9cea-d43edacfcea6.png)
