### ISSUE TITLE
Add ability to configure debug session start timeout

### ISSUE THREAD

**Issue by franekfm** [scalameta/metals#4864]
### Is your feature request related to a problem? Please describe.

when I try to run debugSession/start for a big application with many deps I am getting following error:
`java.util.concurrent.TimeoutException: Future timed out after [60 seconds]`
from this line in particular:
`  at scala.meta.internal.metals.MetalsEnrichments$XtensionScalaFuture.$anonfun$withTimeout$1(MetalsEnrichments.scala:204)`
I would love to have this timeout configurable. Currently it seems to be hardcoded to 60 seconds :(

My Metals version is `0.11.9`.

The stack trace:
```
[Error - 1:33:41 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Future timed out after [60 seconds]
  at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
  at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
  at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
  at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
  at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
  at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
  at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
  at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
  at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
  at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
  at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
  at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Future timed out after [60 seconds]
  at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
  at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
  at scala.concurrent.Await$.result(package.scala:124)
  at scala.meta.internal.metals.MetalsEnrichments$XtensionScalaFuture.$anonfun$withTimeout$1(MetalsEnrichments.scala:204)
  at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
  ... 3 more
```

### Describe the solution you'd like

`  at scala.meta.internal.metals.MetalsEnrichments$XtensionScalaFuture.$anonfun$withTimeout$1(MetalsEnrichments.scala:204)`
I would love to have this timeout configurable. Currently it seems to be hardcoded to 60 seconds :(

### Describe alternatives you've considered

stop using Metals with VSCode and get back to terrible IntelliJ IDEA :(

### Additional context

a corpo world with many constraints about version of many components or way things are done

### Search terms

vscode metals debug start timeout

**Comment by Arthurm1** [comment]
@ckipp01 I get the same error.  If I clean the project and then run something then it will timeout while still compiling the various project dependencies.
It's almost exactly 60 seconds after the compilation has begun so it makes me wonder if `targets` is empty or doesn't contain the correct targets.

Checking the logs: the `debugSession/start` BSP message does contain the correct target but the timeout occurs before a `build/taskFinish` message is sent back to Metals

**Comment by Arthurm1** [comment]
Does `compilationFinished` actually trigger compilation?  It looks like it just returns an empty future if there is no compilation running - which there isn't in my case.

See... https://github.com/scalameta/metals/blob/188f3c7c3102572ece645d515403374dce24bda8/metals/src/main/scala/scala/meta/internal/metals/Compilations.scala#L54-L59

**Comment by tgodzik** [comment]
> Does compilationFinished actually trigger compilation? It looks like it just returns an empty future if there is no compilation running - which there isn't in my case.

Compilation should have been run when the file was saved or opened at the beginning, so there we only wait until the current compilation finishes. If there was no longer a compilation running it means it finished already.

**Comment by tgodzik** [comment]
The timeout it on the start of the debug session itself, so compilation should not be an issue at all. Rather I think the debug process failed to start at all.

**Comment by Arthurm1** [comment]
> Compilation should have been run when the file was saved or opened at the beginning, so there we only wait until the current compilation finishes. If there was no longer a compilation running it means it finished already.

As an example with Project B depending on Project A....
You can change a file in A and A will recompile.  B will not as Metals doesn't cascade without a manual command to.
You can then run a VSCode predefined launch on a class in B without opening any files in B.
At this point there are no compilations running so `compilationFinished` returns immediately.
The `debugSession/start` command triggers a compilation of B.
If B takes > 60 seconds to compile then the command will fail.

This is a simplified example. With lots of projects open, a lot more compilation can happen and go past 60 seconds but the point is that here dependent projects aren't compiled or being compiled when `compilationFinished` is checked.

**Comment by franekfm** [comment]
@tgodzik it is not start debug error/fakturę. It is 60s timout problem. My debug sometimes starts fine if by a chance all this built operations completes in 59s or less. Do for me setting this timeout to whatever I want is the solution.
What actually happends in background is checking dependencies against repositories which takes around 60~70s but I do not wish to hear this nonsensem about configuring mirror etc and doing all this weeks takings setup. Complete wasze of time. If this timeout Cannon be configurable then I will get back to IntelliJ. Note of junior developers will be able to use metals thus will stuck for ages with IntelliJ.

**Comment by tgodzik** [comment]
@franekfm we do want to fix the issue, this might be the fact that the timeout is in a wrong place. It's supposed to timeout if the Java process doesn't start, which is unexpected. We don't want to have a separate configurable timeout since this is an additional thing that the user needs to worry about. The behaviour here should be:

1. Everything gets compiled and ready for running.
2. We request to start a debug session and wait 60 s for it to start.

> but I do not wish to hear this nonsensem about configuring mirror etc and doing all this weeks takings setup. Complete wasze of time. 

I am a bit lost here about what you mean. Please, try to take a bit of time to communicate clearly what is your problem.

**Comment by tgodzik** [comment]
Ach, I see what is happening here. This looks good for Bloop, but the issue is with sbt with will run the compilation before starting the session.

**Comment by ckipp01** [comment]
> This is a simplified example. With lots of projects open, a lot more compilation can happen and go past 60 seconds but the point is that here dependent projects aren't compiled or being compiled when compilationFinished is checked.

Maybe this is what we can change. For example when we grab the target here:

https://github.com/scalameta/metals/blob/1cbc85ca3c3a04b0129587f719abe11791992bbc/metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala#L132

Maybe we should just call `buildTargets.cascadeCompile(target` on it and then first start the call to start the debug server _after_ that is finished. This should account for your case I believe @Arthurm1, and then also avoid needing to worry about the 60 second thing.

I'll also reiterate that we try really hard _not_ to add settings for everything. I think this is actually a great example of a situation where we just need to think about the flow and timing of things a bit to solve the issue, not adding setting.

> but I do not wish to hear this nonsensem about configuring mirror etc and doing all this weeks takings setup. Complete wasze of time. If this timeout Cannon be configurable then I will get back to IntelliJ.

Just an fyi this isn't a great attitude to have towards maintainers that taking their time and attempting to help you with a solution that will work best for everyone.

**Comment by tgodzik** [comment]
> Maybe we should just call `buildTargets.cascadeCompile(target` on it and then first start the call to start the debug server _after_ that is finished. This should account for your case I believe @Arthurm1, and then also avoid needing to worry about the 60 second thing.

We should not need cascade compile, just `compilations.compileTargets(targets).`. `cascadeCompile` would also compile downstream projects.

**Comment by franekfm** [comment]
@tgodzik we are talking about debug session start timeouts after 60s. In effect I do debug by putting a lot of println but that is not the way to go.
I do have concerns that cascade compile will work as I have done clean compile hundread of times each time waiting for all compilations to complete and even waiting 30s or more to make sure no compilation in the queue and only than start debug. Each time I get `compiling root` in logs one line below `debugSession/start`.
```
2023.01.17 14:05:41 INFO Processing debugSession/start
2023.01.17 14:05:43 INFO compiling root
```
P.S.
I have mentioned about mirrors as I have been digging for several months around this error and I seen a lot of articles where you reply (thanks for contribution) that one of potential problems is around coursier/ivy2 performance. Those repository operations also take part in the compilation process and take a while (I was referring to some other topics found on web with your responses).

P.S.2.
So my situation is either I get debug working soon with metals or I drop it and get back to IntelliJ. From my perspective having a short term solution (while waiting for the elegant and appropriate solution) where I can set this timeout would help me a lot. Otherwise I am not able to convience anyone in the team or company to switch to VSC with metals over IntelliJ because simply they cannot debug :-/

**Comment by tgodzik** [comment]
One potential workaround could be to instead of timeout send a message request to the user asking whether they want to wait more and if not then stop connecting. Otherwise wait a bit more.

**Comment by tgodzik** [comment]
So potentially we could try something like https://github.com/scalameta/metals/compare/main...tgodzik:metals:ask-abort?expand=1

Opinions?

**Comment by ckipp01** [comment]
> Ach, I see what is happening here. This looks good for Bloop, but the issue is with sbt with will run the compilation before starting the session.

I haven't tested it yet, but is this really only for sbt? For example what about the situation that @Arthurm1 mentioned:

> You can then run a VSCode predefined launch on a class in B without opening any files in B. At this point there are no compilations running so compilationFinished returns immediately.

Wouldn't this also be an issue in Bloop?

The reason I ask is because if it's not then I'm curious to actually find out the answer to what you asked in:

> If you run compile from the sbt console twice how long does the second compilation take? Ideally it should be very quick. If it is and if it's the case and also different from within Metals that might be the issue. If it's the same slow in the console, it seems it is indeed an issue with sbt and we might need to work around it in Metals.

Because in this situation if something is messed up with the build or something isn't behaving correctly, we should try to identify the root. I've never seen this issue reported _yet_ so I'd caution making any changes unless we know it's not a one off issues in a borked build or something.

**Comment by franekfm** [comment]
from far what I've been debugging dependency checking is happening and process goes over sbt repositories to check libraries versions. From debug logs of dependency resolver I noticed it does a batch of libraries, stucks waiting for several seconds, next big batch and stucks waiting for another several seconds, etc and this dependency checking takes most of the time. I have all libs in local but still does not help.
I will let you know tomorrow about `sbt compile` done twice from console.

**Comment by franekfm** [comment]
@tgodzik, @ckipp01, so I have some more detailed information. I have enabled full logging for resolver and this is what comes out. Compile takes 3.39s `time: compiled root in 3.39s`. So this is not problem of compile but it seems to be problem of sbt as for debug it needs to build sources (which is understandable to support `Step Into`) and in case of my project it needs to analyze around 1000 "so called" modules - please notice that 0 is downloaded (all items are in local) - but anyway logs show `:: resolution report :: resolve 53811ms :: artifacts dl 15161ms`. So this is what cases the delay in starting debug session which I believe is something sbt internal? Thus exposing timeout to metals configuration in VSC?

Logs:
```
2023.01.18 11:15:26 INFO  Processing debugSession/start
2023.01.18 11:15:26 INFO  compiling root
2023.01.18 11:15:26 INFO  :: resolving dependencies :: org.scala-sbt.temp#temp-module-a859299e2e8f47fc073e311b064f0c83d7747058;2.2.0
2023.01.18 11:15:26 INFO      confs: [compile, runtime, test, provided, optional]
<some resolver logs>
2023.01.18 11:15:27 INFO  :: resolution report :: resolve 247ms :: artifacts dl 7ms
2023.01.18 11:15:27 INFO    :: modules in use:
<list of 6 modules>
2023.01.18 11:15:27 INFO      ---------------------------------------------------------------------
2023.01.18 11:15:27 INFO      |                  |            modules            ||   artifacts   |
2023.01.18 11:15:27 INFO      |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
2023.01.18 11:15:27 INFO      ---------------------------------------------------------------------
2023.01.18 11:15:27 INFO      |      compile     |   6   |   0   |   0   |   0   ||   6   |   0   |
2023.01.18 11:15:27 INFO      |      runtime     |   6   |   0   |   0   |   0   ||   6   |   0   |
2023.01.18 11:15:27 INFO      |       test       |   6   |   0   |   0   |   0   ||   6   |   0   |
2023.01.18 11:15:27 INFO      |     provided     |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:15:27 INFO      |     optional     |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:15:27 INFO      ---------------------------------------------------------------------
2023.01.18 11:15:30 INFO  time: compiled root in 3.39s
2023.01.18 11:15:30 INFO  :: resolving dependencies :: my-organization#my-artifact$sources_javadoc;1.0.0-SNAPSHOT
2023.01.18 11:15:30 INFO      confs: [compile, runtime, test, provided, optional, web-assets, web-assets-test, web-plugin, universal, universal-docs, universal-src, windows, docker, linux, rpm, debian, compile-internal, runtime-internal, test-internal, plugin, pom, scala-tool, scala-doc-tool, scoveragePlugin, docs]
<a lot of resolver logs>
[Error - 11:16:26 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Future timed out after [60 seconds]
      <stack trace>
      ... 3 more
 
2023.01.18 11:16:36 INFO  :: resolution report :: resolve 53811ms :: artifacts dl 15161ms
2023.01.18 11:16:36 INFO      :: modules in use:
<list of a lot of modules>
2023.01.18 11:16:37 INFO      ---------------------------------------------------------------------
2023.01.18 11:16:37 INFO      |                  |            modules            ||   artifacts   |
2023.01.18 11:16:37 INFO      |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
2023.01.18 11:16:37 INFO      ---------------------------------------------------------------------
2023.01.18 11:16:37 INFO      |      compile     |  439  |   0   |   0   |   0   ||  844  |   0   |
2023.01.18 11:16:37 INFO      |      runtime     |  439  |   0   |   0   |   0   ||  844  |   0   |
2023.01.18 11:16:37 INFO      |       test       |  496  |   0   |   0   |   46  ||  866  |   0   |
2023.01.18 11:16:37 INFO      |     provided     |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |     optional     |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |    web-assets    |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |  web-assets-test |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |    web-plugin    |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |     universal    |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |  universal-docs  |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |   universal-src  |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |      windows     |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |      docker      |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |       linux      |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |        rpm       |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |      debian      |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      | compile-internal |  440  |   0   |   0   |   0   ||  846  |   0   |
2023.01.18 11:16:37 INFO      | runtime-internal |  439  |   0   |   0   |   0   ||  844  |   0   |
2023.01.18 11:16:37 INFO      |   test-internal  |  497  |   0   |   0   |   46  ||  868  |   0   |
2023.01.18 11:16:37 INFO      |      plugin      |   2   |   0   |   0   |   0   ||   4   |   0   |
2023.01.18 11:16:37 INFO      |        pom       |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |    scala-tool    |   6   |   0   |   0   |   0   ||   12  |   0   |
2023.01.18 11:16:37 INFO      |  scala-doc-tool  |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |  scoveragePlugin |   0   |   0   |   0   |   0   ||   0   |   0   |
2023.01.18 11:16:37 INFO      |       docs       |   56  |   0   |   0   |   0   ||  110  |   0   |
2023.01.18 11:16:37 INFO      ---------------------------------------------------------------------
2023.01.18 11:16:37 WARN      ::::::::::::::::::::::::::::::::::::::::::::::
2023.01.18 11:16:37 WARN      ::              FAILED DOWNLOADS            ::
2023.01.18 11:16:37 WARN      :: ^ see resolution messages for details  ^ ::
2023.01.18 11:16:37 WARN      ::::::::::::::::::::::::::::::::::::::::::::::
      <list of some failed (src) and (doc) downloads>
2023.01.18 11:16:37 WARN      ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by franekfm** [comment]
@tgodzik, thanks a lot, very well-appreciated / bardzo dziękuję

**Comment by tgodzik** [comment]
I think https://github.com/scalameta/metals/pull/4873 should offer a good solution. It gets rid of the arbitrary timeout and allows users to cancel it themselves.

**Comment by franekfm** [comment]
@ckipp01 great thanks for understanding and support

**Comment by tgodzik** [comment]
@franekfm you should be able to test it out in the newest snapshot.
