### ISSUE TITLE
Inline value: function literals get inlined incorrectly

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#4872]
### Describe the bug

It seems like function literals don't have special handling when inlining values (to be expected, it's a fresh feature!).

To reproduce:

1.

```scala
@main def demo = {
  val plus1 = (x: Int) => x + 1
  println(plus1(1))
}
```

2. Focus on `val plu@@s1`
3. Inline value
4. The result is

```scala
@main def demo = {
  println((x: Int) => x + 1(1))
}

```

### Expected behavior

```scala
@main def demo = {
  println(((x: Int) => x + 1)(1))
}
```

### Operating system

None

### Editor/Extension

VS Code

### Version of Metals

0.11.10+62-8bdf8640-SNAPSHOT

### Extra context or search terms

Additionally, if the type of the parameter is inferred from the function value:

```scala
val plus1: Int => Int = x => x + 1
```

inlining drops the type info completely:

```scala
println(x => x + 1(1))
```

. Is this something Metals should try to fix? One idea (which wouldn't be specific to functions) would be to additionally add the type annotation and wrap the whole thing in parentheses:

```scala
println(((x => x + 1): Int => Int)(1))
```

**Comment by tgodzik** [comment]
Thanks for checking it out!  I think that is slight modification to the logic when to add parenthesis, though this time it's based on the type :thinking: Could you take a look @kasiaMarek ?

**Comment by kubukoz** [comment]
I'd consider basing it on the syntax... for example, if the type is a SAM, can we detect that? If it's a lambda expression it might be less ambiguous. Of course I only have a vague understanding of this, so I'm not saying you're wrong 😅
