### ISSUE TITLE
Metals suggests import for file movement

### ISSUE THREAD

**Issue by d-albrecht** [scalameta/metals#4883]
### Describe the bug

I know this isn't the intended way, but Metals suggests strange imports if I manually first change the package of some file and then (in VSCode) try to move the file to the folder matching it's package (instead of relying on Metals to move and change package at once).

1. Create a source file with some type definition (trait, class, etc)
2. Create another file that imports the first definition
3. Change the package of the first definition and manually fix the imports on the usage side.
4. Then, move the first file to the now matching folder path.
5. Metals suggests to add a redundant import of the moved class to any file that referenced the moved definitions.

```
//src/main/scala/path
package path.inner
trait Dep
//src/main/scala/path
package path
import path.inner.Dep
class Usage { def use(d: Dep): Unit = ??? }
```

After move of ``Dep``to ``path.inner.Dep``, Metals wants ``Use`` to look like:
```
//src/main/scala/path
package path
import path.inner.Dep
import path.inner.Dep
class Usage { def use(d: Dep): Unit = ??? }
```
And so far the import always is starting with the top-most package even if in my project all files use a split package definition:
```
package domain.author.project
package subproject.level1
// suggested import will be 
import domain.author.project.subproject.level1.level2.Type
// even if the following would be sufficient:
import subproject.level1.level2.Type
// or even:
import level2.Type
```

### Expected behavior

Given that in scala path and package don't have to match, I think Metals should be much more flexible when it comes to files moving between folders. Especially if I don't intend for the package to change upon movement. And in case the movement actually changes the package, Metals should only add new import clauses, if the existing ones don't cover the moved type definitions already.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.21.0

**Comment by tgodzik** [comment]
Thanks for reporting! Ans sorry for not getting back to you, we should be able to figure out if the import is already present and not add it then.
