### ISSUE TITLE
Worksheet doesn't support scala-cli

### ISSUE THREAD

**Issue by leonbur** [scalameta/metals#4885]
### Describe the bug

Worksheet doesn't accept scala-cli directives such as

```scala
//> using lib "com.lihaoyi::requests::0.8.0"

val r = requests.get("https://api.github.com/users/lihaoyi")
```
I get `Not Found: requests` on the `requests.get` line.

regular `.scala` files are running with directives as expected

metals doctor:
```
Build server currently being used is scala-cli v0.1.20.

Metals Java: 19 from Eclipse Adoptium located at /home/bloodnut/.sdkman/candidates/java/19-tem

Metals Server version: 0.11.10
```

### Expected behavior

Worksheet should recognize scala-cli directives.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

0.11.10

**Comment by ckipp01** [comment]
Thanks a lot for the report @leonbur! This is something we're aware of that's currently not supported. There'd need to be some changes made in mdoc for this to work. We have a feature request that you can 👍🏼 [here](https://github.com/scalameta/metals-feature-requests/issues/308).
