### ISSUE TITLE
 Worksheet doesn't support ansi color in pprint

### ISSUE THREAD

**Issue by doofin** [scalameta/metals#4886]
### Describe the bug

Currently,using pprint in Worksheet will add gibberish(ANSI escape code) to  output :
![image](https://user-images.githubusercontent.com/6041353/213946890-ade82088-7ad8-40f8-8ed7-dbe18ba6771e.png)

### Expected behavior

Worksheet should support ANSI colors in pprint

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.10

### Extra context or search terms

Worksheet,pprint

**Comment by tgodzik** [comment]
Thanks for reporting! Worksheets already use pprint (at least for Scala 2) and there should be no reason to use it there.

We should however try and strip the ansi codes from the rendered output. This might be better to fix in mdoc itself.

**Comment by kasiaMarek** [comment]
I think it's more reasonable we handle this not mdoc since most tools handle ANSI colours (even `assertNoDiff` ignores those).
