### ISSUE TITLE
Cannot navigate library source on Windows if the library version includes a `+` sign

### ISSUE THREAD

**Issue by Atry** [scalameta/metals#4896]
### Describe the bug

Reproduction steps

1. Git clone https://github.com/Atry/html.scala/tree/0df608834dcf0dcdcae32d60f23a4c9560ddbf0a
2. Import it from Metals
3. In VSCode, Ctrl + Click the import statement at https://github.com/Atry/html.scala/blob/0df608834dcf0dcdcae32d60f23a4c9560ddbf0a/html/src/main/scala/com/yang_bo/html/package.scala#L75

Then I saw the file name instead of the actual source file:
![Screenshot_20230124_091238](https://user-images.githubusercontent.com/601530/214485257-fa68d07b-314e-40d7-9ba1-a63b383c1576.png)

### Expected behavior

I expect I should see the actual content of `Dsl.scala` file, not the JAR file name.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

1.21.0

### Extra context or search terms

Note that there is the JAR file is actually located at `C:\Users\atry\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\thoughtworks\dsl\dsl_sjs1_3\2.0.0-M2%2B339-69c389a4\dsl_sjs1_3-2.0.0-M2%2B339-69c389a4-sources.jar`, while the URL of the editor is `file:C:\Users\atry\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\thoughtworks\dsl\dsl_sjs1_3\2.0.0-M2%2B339-69c389a4\dsl_sjs1_3-2.0.0-M2%2B339-69c389a4-sources.jar!\com\thoughtworks\dsl\Dsl.scala`. Because the file URL is unescape automatically, the editor is attempt to open `C:\Users\atry\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\thoughtworks\dsl\dsl_sjs1_3\2.0.0-M2+339-69c389a4\dsl_sjs1_3-2.0.0-M2+339-69c389a4-sources.jar`, which does not exist.

**Comment by tgodzik** [comment]
Thanks for reporting! This might actually be fixed already in the snapshots, but I will try to confirm.

**Comment by tgodzik** [comment]
Ok no, this is not fixed yet. But that's a great reproduction!
