### ISSUE TITLE
"Go to definition" does not work in `derives` clause

### ISSUE THREAD

**Issue by nikololiahim** [scalameta/metals#4903]
### Describe the bug

1. Paste the following code in the editor:
```scala
//> using scala "3.2.1"
import scala.deriving.Mirror

trait Show[A]:
  def show(a: A): String

object Show:
  inline def derived[T](using Mirror.Of[T]): Show[T] = new Show[T]:
    override def show(a: T): String = a.toString

case class Box[A](value: A) derives Show
```

2.Right-click on `Show` in `derives Show` on line 11, choose "Go to definition"
3. No definition is found
<img width="567" alt="image" src="https://user-images.githubusercontent.com/45356788/214829783-d72395b5-bcdc-49ce-9daa-93a9a94e1357.png">

### Expected behavior

The "Go to definition" should either take the cursor to the trait Show, or the object where the `derived` method is defined.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.10

### Extra context or search terms

scala 3, derives, go to definition

**Comment by tgodzik** [comment]
Thanks for reporting! The good news that recent improvements will make this work, the bad news is that it seems it's the compiler having issues with the dervies tree. I will dig into that.
