### ISSUE TITLE
publishLocal failed with scala 3.2.2

### ISSUE THREAD

**Issue by doofin** [scalameta/metals#4920]
### Describe the bug

while testing metals with scala 3,publishLocal doesn't seem to work (will give "823 errors found")

to reproduce : 

```
sbt
++3.2.2
publishLocal
```

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

0.11.11-SNAPSHOT

**Comment by ckipp01** [comment]
Hey @doofin! There's some helpful messages from sbt when you first start the project that should give you some hints. Basically you'll want to do the following:

```
sbt
publishLocal <-- fully publishes Metals with support for the version of Scala it's built with (2.13.10)
++3.2.2 mtags/publishLocal <-- publishes the part of metals needed to support a specific Scala version
```

You can also fine some more useful information [here](https://scalameta.org/metals/docs/contributors/getting-started). If that doesn't solve your problem, feel free to report back!

**Comment by doofin** [comment]
thanks,but it doesn't seem to work when I set `"metals.serverVersion": "0.11.11-SNAPSHOT"` and restart server in vscode . Literally,`++3.2.2 mtags/publishLocal` looks like just mtags rather than the whole metals server ?  I want to manually test inside vscode.

**Comment by ckipp01** [comment]
>  Literally,++3.2.2 mtags/publishLocal looks like just mtags rather than the whole metals server ? I want to manually test inside vscode.

Correct, that's why I mentioned the `publishLocal` first. Since that' publishes the actual server plus the necessary mtags. So you need to do both commands.

> It would also be nice that the doc mentions the location of the metals binary invoked by vscode.

Well that's sort of the thing, there is no binary location or anything. It simply puts together the necessary Metals classpath and runs it uses coursier.
