### ISSUE TITLE
Running tests now fails in v1.21.0

### ISSUE THREAD

**Issue by KeithGrant** [scalameta/metals#4929]
### Describe the bug

Press "run" link in ZIOSpecDefault derived test object and large cmd text file appears in terminal with comment that command line is too long.

Windows 10
VS Code 1.74.3
Scala 3.2.1
ZIO 2.0.6 sbt test plugin

### Expected behavior

Expect test object to run and display test results in debug console. Note this feature does work in metals version 1.20.0 

[termina.txt](https://github.com/scalameta/metals/files/10549032/termina.txt)

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.21.0

**Comment by tgodzik** [comment]
Thanks for reporting! This should be fixed in the newest snapshots, alternatively you can use `debug` which will be the same behaviour as `run` previously if you don't set any breakpoints.

**Comment by KeithGrant** [comment]
Please note that tests do execute correctly when using the "run and debug" tool and the testing tool. It just doesn't run with the run link in the test source code.
