### ISSUE TITLE
scala-cli: completions in scripts put imports before directives

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#4939]
### Describe the bug

Reproduction steps:

1. Create a file with the `.sc` extension (worksheet or not, doesn't matter)
2.
```scala
//> using scala "2.13.10"
//> using lib "org.typelevel::cats-core:2.9.0"

object demo {
  Monoid@@
}
```
3. Run a quick fix at `@@` (cursor position) to add an import for `cats.kernel.Monoid`
4. The import is inserted in line 1:
```scala
import cats.kernel.Monoid
//> using scala "2.13.10"
//> using lib "org.typelevel::cats-core:2.9.0"

object demo {
  Monoid
}
```

### Expected behavior

The import is placed after the directives:

```scala
//> using scala "2.13.10"
//> using lib "org.typelevel::cats-core:2.9.0"
import cats.kernel.Monoid

object demo {
  Monoid
}
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.10+110-49e01859-SNAPSHOT / 0.11.10

### Extra context or search terms

- this doesn't happen in `.scala` files
- it happens in both scala 2.13.10 and 3.2.2

**Comment by kubukoz** [comment]
I guess it's not just scala-cli, but "anything that has directives". I saw Mill is [playing with the idea](https://github.com/com-lihaoyi/mill/pull/1969) of switching to directives too.

**Comment by kubukoz** [comment]
I'm still seeing this in 1.0.0 :(

**Comment by tgodzik** [comment]
Looks like the fix worked in the previous version of Scala CLI and broke again :/

**Comment by tgodzik** [comment]
Actually, this failed for me on an older version of Scala CLI, which version of Scala CLI are you using?

Metals 1.0.0 + Scala CLI 1.0.2 works ok. `1.0.0-RC2` was broken for me.

**Comment by kubukoz** [comment]
hmm I'm on 1.0.1, let me check and report back.

**Comment by kubukoz** [comment]
Looks like it's resolved, thanks!
