### ISSUE TITLE
Ignored tests sometimes don't even show up in the Testing tab

### ISSUE THREAD

**Issue by d-albrecht** [scalameta/metals#4975]
### Describe the bug

I use AnyWordSpec-style scalatests to validate aspects of my project. But some tests are especially stressing either on system resources or on user time, so I wanted to ignore them (for now). Some tests are grouped in a class that all should be ignored, so I annotated the whole class, one test was in another class with other tests that still should run, so I ignored this single testcase. Despite the explanation and examples on the scalatest site, the individually ignored testcase doesn't show up in the Testing tab at all anymore.

Steps to reproduce:
1. Create a scalatest test-class with test cases
2. See that in the editor's Testing tab, all testcases are listed
3. Either ignore the whole class (by annotating ``org.scalatest.Ignore``) or ignore a single test case (by replacing the ``in`` "keyword" with ``ignore``)
4. Come back to the Testing tab and see that in the first case all test cases are still listed but (at least after the next test run) are marked as skipped, or in the second case are gone completely.

### Expected behavior

All ignored tests should still be discovered and properly listed in the Testing tab.

> Note that marking a test class as ignored won't prevent it from being discovered by ScalaTest. Ignored classes will be discovered and run, and all their tests will be reported as ignored. This is intended to keep the ignored class visible, to encourage the developers to eventually fix and “un-ignore” it.

See for reference: [AnyWordSpec](https://www.scalatest.org/scaladoc/3.2.15/org/scalatest/wordspec/AnyWordSpec.html) (under "Ignored tests")

Based on the shown examples the same should be true for individually ignored test cases.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.21.0

**Comment by tgodzik** [comment]
Thanks for reporting! I see a couple of issues with test explorer right now, we will need to look closer at some point.
