### ISSUE TITLE
High CPU usage on idle in vscode

### ISSUE THREAD

**Issue by p-pavel** [scalameta/metals#4987]
### Describe the bug

Metals seems to eat CPU cores indefinitely even without user interaction.

OS: macOS Ventura 13.2.1, Apple Silicon.

I saw this behaviour in different code bases. I think I can reliably reproduce it:

```
 git clone git@github.com:Atry/scalajs-all-in-one-template.git
```
go to the directory, start VSCode, import project, open Main.scala, try to edit `html` interpolated strings (causing error highlighting) then fix the code.

metals constantly eating ~135% CPU cores. This can easily go to all available cores.

### Expected behavior

This should not happen

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.10

### Extra context or search terms

metals output contains bloop errors

```
2023.02.18 23:22:35 INFO  file:///Users/ppavel/Projects/test1/js/src/main/scala/views/Main.scala:48:5: stale bloop error: Exception occurred while executing macro expansion.
scala.MatchError: dotty.tools.dotc.core.Types$PreviousErrorType@3e8e5a83 (of class dotty.tools.dotc.core.Types$PreviousErrorType)
	at scala.quoted.runtime.impl.printers.Extractors$ExtractorsPrinter.visitType(Extractors.scala:242)
	at scala.quoted.runtime.impl.printers.Extractors$.showType(Extractors.scala:12)
	at scala.quoted.runtime.impl.QuotesImpl$$anon$18.show(QuotesImpl.scala:3025)
	at scala.quoted.runtime.impl.QuotesImpl$$anon$18.show(QuotesImpl.scala:3024)
```

**Comment by tgodzik** [comment]
Thanks for reporting! I think I know what is going on, most likely recursive inline is not being handled properly.
