### ISSUE TITLE
Scala 3 autocomplete not available

### ISSUE THREAD

**Issue by charlesbthomas** [scalameta/metals#4988]
### Describe the bug

Autocompletion for classes in a project do not consistently work when using scala 3.

For example, when I generate the most basic of scala 3 projects using `sbt new scala/scala3.g8` and add a test class `MyClass` to a package `foo`, that class is not discoverable in my editors autocompletion results. Normal utils are available such as things like `Future`, etc. 

[Here is my lua config for nvim-metals](https://github.com/charlesbthomas/.dotfiles/blob/master/nvim/lua/charlie/plugins/metals.lua)

See these example screenshots:

#### Example showing missing autocomplete:

<img width="1106" alt="Screen Shot 2023-02-18 at 6 49 15 PM" src="https://user-images.githubusercontent.com/20322135/219906052-8903fa3e-ec97-4b74-a7d1-9cac83e7f25a.png">

#### Example showing this works when in an identical scala 2 project:

<img width="962" alt="Screen Shot 2023-02-18 at 6 52 53 PM" src="https://user-images.githubusercontent.com/20322135/219906214-18420b47-8d63-450f-9b17-3f2b23fd702f.png">

---

Additionally, this also is the case when in **VSCODE**. Does this mean that this might be a bug in metals itself?

#### VSCode Example

Note that the available option is not a module, but is coming from my text buffer.

<img width="1094" alt="Screen Shot 2023-02-18 at 6 55 55 PM" src="https://user-images.githubusercontent.com/20322135/219906271-86887540-1001-4714-b858-52dfa15849df.png">

### Expected behavior

For autocompletion to show available modules as reported from LSP, just like in scala 2.

### Operating system

macOS

### Version of Metals

v0.11.10

### Commit of nvim-metals

latest

**Comment by dos65** [comment]
@charlesbthomas I see that there is an error in `Test.scala`.
Could you fix this error to turn project into compiled one and check if MyClass become available in completions?

**Comment by charlesbthomas** [comment]
No workspace errors -- project can fully compile. No autocomplete. 

I'd note that it would be odd if that did cause the suggestions to work, if there was. I frequently work in very large scala 2 code bases and compilation errors don't break code suggestions unless they are from dependent sbt subprojects.

Here is the code pushed up, so that you can see the full project configuration. It is literally a hello world scala 3 template: https://github.com/charlesbthomas/scala3-scratch

![Screen Shot 2023-02-19 at 4 03 48 PM](https://user-images.githubusercontent.com/20322135/219977853-5ed2f8ce-8c5c-496c-a738-328495f76b04.png)

**Comment by charlesbthomas** [comment]
Another detail I find interesting is that if I start to type out the fully qualified name of the class (package name included). Autocomplete DOES work in both editors. Obviously, this is not ideal. The preference would be to be able to type out the simple name and it appear in the suggestions via fuzzy search, the add the import for you on select. That is the behavior for scala 2 projects.

#### Neovim
![Screen Shot 2023-02-19 at 9 04 33 PM](https://user-images.githubusercontent.com/20322135/220000266-0aa72e07-578b-4a6d-aebc-f9c063c46a5b.png)

**Comment by tgodzik** [comment]
Thanks for reporting this! Turns out we didn't suggest importing classes even though `new` keyword is no longer needed. Fixing it in https://github.com/scalameta/metals/pull/5000

**Comment by charlesbthomas** [comment]
@tgodzik does this mean it should currently be working with case classes as well?

**Comment by tgodzik** [comment]
I added a test for that so it should work correctly in all possible cases.
