### ISSUE TITLE
Huge mem allocation / OutOfMemoryError

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#5001]
### Describe the bug

I have `-Xmx512m` jvm setting for Metals server.
On the latest snaphot I'm gettin OOM in the following case:

- open metals repo
- wait for build build connecting
- open `tests/unit/src/test/scala/tests/ScalaToplevelLibrarySuite.scala`
- put cursor at `class Sca@@laToplevelLibrarySuite`
- notice OOM / huge mem allocation

![Screenshot from 2023-02-21 21-34-35](https://user-images.githubusercontent.com/5816952/220430875-7477fba2-0df7-45ff-9d93-d705d3903b4a.png)

### Expected behavior

No OOM / less memory consumption

### Operating system

Linux

### Editor/Extension

None

### Version of Metals

0.11.10+166-3a9ab1d7-SNAPSHOT

**Comment by tgodzik** [comment]
Good catch! Dug around a bit and https://github.com/scalameta/metals/pull/5008 fixes it.
