### ISSUE TITLE
No variable substitution in VS Code extension configuration

### ISSUE THREAD

**Issue by guilhem-dvr** [scalameta/metals#5003]
### Describe the bug

Hi!

I use Metals in VS Code and I have set up the `metals.scalafmtConfigPath` setting to `${workspaceFolder}/.scalafmt.conf`, but when saving a file I get the following error:

![image](https://user-images.githubusercontent.com/93586454/220621878-b357a475-abec-404c-be14-72beff72ec17.png)

And if I click on `Create .scalafmt.conf`, I get a folder `${workspaceFolder}` at the root of my workspace with a default `.scalafmt.conf` file:
![image](https://user-images.githubusercontent.com/93586454/220622110-2210f889-723d-4aaa-9d53-f3395f636016.png)

### Expected behavior

No errors and working variable substitution.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.21.0

**Comment by tgodzik** [comment]
Thanks for reporting! I don't think ${workspaceFolder} works in the settings (looks like a limitation on VS Code side), but the workspace folder is the default, so you don't need to set up anything. If you want you can also use a relative path. 

Creating the folder is not expected, but it does sounds like a correct thing to do if the folder doesn't exist.

**Comment by guilhem-dvr** [comment]
Indeed, nothing to do with Metals, I read VS Code too fast I guess.
Thanks!

**Comment by tgodzik** [comment]
No worries, this is a valid issue to raise, thanks for doing it!
