### ISSUE TITLE
Metals (or vscode) reuse of the debug console process mix-up env

### ISSUE THREAD

**Issue by Odomontois** [scalameta/metals#5025]
### Describe the bug

Whenever I use the vscode run configurations with the "testing" support, both launch configurations and tests run in the same Debug Console. This has an interesting side-effect: when some launch tasks set environment variables described in the launch.json, those variables are visible to the following tests executed from the "Testing" tab.

To reproduce:

1. Clone the [repro repo](https://github.com/Odomontois/metals-repro-test-envs)
2. Run the only test (should succeed)
3. Run the only launch configuration
4. Run the test again (should fail)

### Expected behavior

Test should succeed independently of previously run launch configurations

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.11

**Comment by kpodsiad** [comment]
Thanks for reporting @Odomontois! 
It is issue with bloop, it this behavior bother you can switch to sbt as build server (by executing `switch build server` command)

When running main class via DAP bloop is executing following lines:
- starts forker [here](https://github.com/scalacenter/bloop/blob/3b76970c191624fdeb47ad9a9f5820fa39d00651/frontend/src/main/scala/bloop/engine/tasks/Tasks.scala#L229) 
- forker codes [mutates](https://github.com/scalacenter/bloop/blob/3b76970c191624fdeb47ad9a9f5820fa39d00651/frontend/src/main/scala/bloop/exec/JvmProcessForker.scala#L115) `CommonOptions` which is a case class with mutable field (yay!)

That `CommonOptions` belong to `State` which is bloop's representation of build target, hence after running Main class, ENV is set for the target thus it affects tests :(
