### ISSUE TITLE
Using sbt as bsp server does not on windows work if installed to path with spaces

### ISSUE THREAD

**Issue by GiGurra** [scalameta/metals#5027]
### Describe the bug

If you

- Install sbt to a path with spaces (default path includes spaces, `program files (x86)`) 
- switch to sbt as bsp server

It will fail to start the sbt bsp server. The .metals/sbt.json looks correct.

Reinstalling sbt to a non-standard path without spaces fixes the issue

### Expected behavior

It should be possible to have sbt installed to its default installation path, which includes spaces

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

0.11.11

**Comment by tgodzik** [comment]
@GiGurra this should be fixed in the next release, you should be able to test it out in a SNAPSHOT later today
