### ISSUE TITLE
Metals client: couldn't create connection to server.

### ISSUE THREAD

**Issue by Balthazar-Maignan** [scalameta/metals#5036]
### Describe the bug

I downloaded a project from my school website, and imported it into vs code.
Then metals showed me this message : Metals client: couldn't create connection to server.
I tried to click on "start metals" manually but nothing seems to happen.
Also, the Terminal doesn't know the word sbt wich I usually use to run a file for the first time.

see logs : 
Java home: C:\Program Files (x86)\Java\jre1.8.0_361
Metals version: 0.11.11
Erreur : impossible de trouver ou charger la classe principale scala.meta.metals.Main
[Info  - 9:13:28 AM] Connection to server got closed. Server will restart.
[Error - 9:13:28 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:13:28 AM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Erreur : impossible de trouver ou charger la classe principale scala.meta.metals.Main
[Info  - 9:13:29 AM] Connection to server got closed. Server will restart.
[Error - 9:13:29 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:13:29 AM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Could not launch Metals Language Server:
Pending response rejected since connection got disposed
Release notes was not shown: not showing release notes since they've already been seen for your current version
Erreur : impossible de trouver ou charger la classe principale scala.meta.metals.Main
[Info  - 9:13:29 AM] Connection to server got closed. Server will restart.
[Error - 9:13:29 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:13:29 AM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:13:29 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Erreur : impossible de trouver ou charger la classe principale scala.meta.metals.Main
[Info  - 9:13:29 AM] Connection to server got closed. Server will restart.
[Error - 9:13:29 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:13:29 AM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:13:29 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Erreur : impossible de trouver ou charger la classe principale scala.meta.metals.Main
[Error - 9:13:29 AM] The Metals server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 9:13:29 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:13:29 AM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:13:29 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

### Expected behavior

When I import a project on my school computer, metals start normally and ask to import the build.sbt file, which I do and then the usual fonctionnalities work fine.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.22.0

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like the Metals process can't start (Main is not found). I wonder if it would help if you added a path to JDK instead of just JRE? That can be set in the settings of VS Code within the metals section `metals.javaHome`.

Otherwise, the issue might be related to the space in the path, but last time I checked it worked correctly.

**Comment by tgodzik** [comment]
Closing this for now, since there was no response.

**Comment by bblfish** [comment]
That was helpful for me. I also had metals.javaHome pointing to a non-existent directory. Perhaps the error message should tell about that variable.

**Comment by som-snytt** [comment]
Don't forget to click "Remote" where it says "Also modified in Remote" (for WSL).

There, on the Remote tab, it will say "Also modified in User", but FSR clicking it does not return to the previous setting.
