### ISSUE TITLE
Semantic highlighting readonly tokens support

### ISSUE THREAD

**Issue by rcano** [scalameta/metals#5052]
### Describe the bug

As part of the new semantic highlighting functionality, many tokens that are marked as variables, are not correctly tagged as readonly. When you want to setup coloring rules to differentiate between mutable and immutable variables, this incorrect tagging makes the code look weird. Here's a screenshot outlining the issue:
![image](https://user-images.githubusercontent.com/759769/225112841-530d1394-6a9c-4ecf-8ada-4797b62a94ee.png)

Note: I don't know why `tap` or `setMargin` show up as red as well, the token inspector says they are variables, when they clearly are methods.

When calling methods using named parameters, the named parameter suffers this as well.

Here are the rules used:

```json
"editor.semanticTokenColorCustomizations": {
  "rules": {
      "variable": "#ff0000",
      "variable.readonly": "#009B00",
      "*.deprecated": {
          "strikethrough": true
      },
      "parameter": "#919563",
      "type": "#7E0021",
      "typeParameter": "#2ca087",
      "interface": {
          "italic": true,
          "foreground": "#7E0021"
      },
      "class": {
          "bold": true,
          "foreground": "#7E0021"
      },
      "enum": {
          "foreground": "#7E0021",
          "bold": true
      },
      "struct": {
          "foreground": "#009B00",
          "bold": true
      },
      "decorator": {
          "foreground": "#919563",
          "bold": true
      },
      "method": {
          "bold": false
      }

  }
}
```

### Expected behavior

the tokens pointed to by the arrows in the image, as well as the name of a parameter when using named parameters, should be readonly variables

### Operating system

None

### Editor/Extension

None

### Version of Metals

v0.11.11

### Extra context or search terms

semantic highlighting

**Comment by tgodzik** [comment]
Thanks for reporting! @jkciesluk is already fixing part of it in https://github.com/scalameta/metals/pull/5049

**Comment by tgodzik** [comment]
@jkciesluk I think this is fixed now?
