### ISSUE TITLE
in vs code i have problem , my scala server crashed 5 times in 3 minutes what should i do?

### ISSUE THREAD

**Issue by Parmida1318** [scalameta/metals#5056]
### Expected behaviour:

**Operating system:**
Mac OS X

**Java version:**
17

**Editor/extension:**
Visual Studio Code v1.76.2

**Metals version:**
0.11.11

### Workspace information:

 - **Scala versions:** 3.2.0; 2.12.17
 - **Build server:** Bloop v1.5.6
 - **All build tools in workspace:** Bloop; sbt

**Comment by tgodzik** [comment]
Thanks for reporting! Do you see anything else in the Metals logs in the output?

Does it break on every project? Do you maybe have some `.jvmopts` that may interfere with the Metals properties?

**Comment by tgodzik** [comment]
Let us know if you can provide any additional information, closing for now.
