### ISSUE TITLE
Custom Bsp Built Tool not able to be auto-started or auto-connected

### ISSUE THREAD

**Issue by crt-31** [scalameta/metals#5064]
### Describe the bug

Hello. We have built a custom Build Server that implements BSP, however Metals is not auto-starting it, and instead gives errors: 
_Build server is not auto-connectable_ 
and 
_the build tool Bazel is not supported by Metals, please open an issue if you would like to contribute to improve the situation._

I have just a single *.json file in my .bsp folder, so I would expect that Metals would have no problem auto-starting the single configured Build Server.

Note that I'm using VSCode, and everything works great once I press the "restart build server" button. But I would like to make it so we don't have to press that button everytime we load the app.

### Expected behavior

Metals should auto-start and auto-connect to a custom build server when there is a single build server configured (a single *.json in the .bsp folder). Also should be able to select between two custom build servers and remember that so it will again, auto-start and auto-connect to it. 

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.11

**Comment by tgodzik** [comment]
Thanks for reporting! The issue here is that we don't yet properly support Bazel and on the other hand we do discover it. We should probably exclude Bazel from the check that causes the warning.

**Comment by tgodzik** [comment]
We will be working on this, if nothing changes by the next month please do ping me.

**Comment by tanishiking** [comment]
This isn't a general solution, but for bazel-bsp we can workaround by the following patch

```diff
diff --git a/metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala b/metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
index 416156684..2bbf2c57f 100644
--- a/metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
+++ b/metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
@@ -36,7 +36,7 @@ final class BuildTools(
   // Bloop since Metals thinks it's in state that's auto-connectable before the
   // user is even prompted.
   def isAutoConnectable: Boolean = {
-    isBloop || (isBsp && all.isEmpty) || (isBsp && explicitChoiceMade())
+    isBloop || (isBsp && all.isEmpty) || (isBsp && explicitChoiceMade()) || (isBsp && isBazel)
   }
   def isBloop: Boolean = {
     hasJsonFile(workspace.resolve(".bloop"))
```

**Comment by crt-31** [comment]
FYI, I tried the changes in latest Snapshot (4/17/23), and this scenario seems to work as expected now, thanks!
Can we keep this ticket open till #5139 is complete, and I'll retry this.

As an aside, would it be better to make this solution more general by not having special isBazel check? Would it be feasable to just say that if there is a custom bsp.json file, then always allow it to be used, and maybe not even try to detect other buildtools?

**Comment by tanishiking** [comment]
@crt-31 Thank you for confirming!

> would it be better to make this solution more general by not having special isBazel check?

I'm on the fence (that's why I kept this issue open), while it would be better to make this solution more general, I'm not sure how many cases we appreciate the general solution (How many other build tools support BSP?).
Maybe we can close this issue for now, and re-open / create another one when we need to support another BSP server 🤔

**Comment by tanishiking** [comment]
Closing for https://github.com/scalameta/metals/pull/5139
