### ISSUE TITLE
Scala metals 0.11.11 taking infinite time to download in vscode

### ISSUE THREAD

**Issue by AnuragGupta93** [scalameta/metals#5079]
### Describe the bug

Facing this issue from a while now. From the last update of metals 0.11.11, whenever I open Vscode, the download starts and go on for infinite time while the side pop of downloading Metals 0.11.11 alert.

The download is just stick after this:

Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home
Metals version: 0.11.11
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.13/0.11.11/metals_2.13-0.11.11.pom

### Expected behavior

The download should not take this amount of time. And even if takes and dependent on download some other dependency, it should show me where it is taking this much time so that I can debug the issue from my end.
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/35900375/227710175-93fadea6-3411-4a1d-a5cc-c8d178e3d2ee.png">

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.11

**Comment by tgodzik** [comment]
Thanks for reporting! Does it happen with any other Metals versions? Do you have a proxy or any other specific network settings?

You can alternatively use [coursier](https://get-coursier.io/) to download Metals via:
`cs fetch org.scalameta::metals:0:11:11`
it might also show some more errors.

**Comment by AnuragGupta93** [comment]
Yeah, I reverted back to scala metals extension version: 1.21.0 which is using metals v0:11:10 and that is working fine for me.

Also using coursier, I am getting error:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/35900375/227713391-81104879-96e5-45cc-a8a5-5fd8e8447e58.png">

**Comment by ckipp01** [comment]
> You can alternatively use [coursier](https://get-coursier.io/) to download Metals via:
cs fetch org.scalameta::metals:0:11:11

By the way this should be:

```diff
- cs fetch org.scalameta::metals:0:11:11
+ cs fetch org.scalameta::metals:0.11.11

**Comment by AnuragGupta93** [comment]
@ckipp01 Even with the coursier, I am not able to download the package (it is stuck there). I am not behind any vpn or proxy. So, not sure what the issue can be.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/35900375/227762653-27595a42-0574-4097-91a8-e6db0ffae815.png">

Tried with the other version but that seems to be working fine.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/35900375/227762687-f7201794-1a8a-4e7f-98ec-5f604354c01b.png">

**Comment by ckipp01** [comment]
@AnuragGupta93 can you give it a few `-v` and try again and see what it shows you?

```sh
cs fetch org.scalameta::metals:0.11.11 -v -v -v
```

**Comment by AnuragGupta93** [comment]
Getting this as output:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/35900375/227765518-f9a1fbe5-d8c2-4e8a-8ec2-9f0f57451c48.png">

**Comment by tgodzik** [comment]
That's super weird, could you maybe try removing the part of cache that contains scalameta projects?

Should be under `~/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/`

Alternatively, you could switch to a snapshot version such as `0.11.11+41-1c11dfdf-SNAPSHOT` in metals.serverVersion setting

**Comment by tgodzik** [comment]
This doesn't seem to be related to Metals, if cleaning the cache didn't help you might consider opening the issue in coursier
