### ISSUE TITLE
Does not use config file from project directory

### ISSUE THREAD

**Issue by jakeorr** [scalameta/metals#509]
I'm using a multi-root workspace setup in vscode. I add project folders to my workspace, and don't have a single root workspace. When I install metals, it creates a .metals/ directory in my workspace's first project folder any only looks for the config file there.

https://code.visualstudio.com/docs/editor/multi-root-workspaces

**To Reproduce** Steps to reproduce the behavior:

1. Close workspace in vscode
2. File > Add Folder to Workspace...
3. Select a project folder that *does not* contain a .scalafmt.conf and build.sbt
4. File > Add Folder to Workspace...
5. Add a second project folder that contains a .scalafmt.conf and build.sbt
6. Open the build.sbt file in the second project folder, save it
7. A .metals/ directory is added to the first project folder
8. Vscode displays an error: "Unable to format since this workspace has not .scalafmt.conf file...."

**Expected behavior**

I expect .scalafmt.conf to be used from the project directory of the file I am editing. I do not expect the .metals/ directory to be added to the first project directory. I would expect it to be added to my user home directory or the project with the file I'm editing.

**Screenshots**

![workspace structure](https://duaw26jehqd4r.cloudfront.net/items/072t3Y0h2u0b1F311L1b/Screen%20Shot%202019-01-31%20at%201.08.32%20PM.png)

**Installation:**

- Operating system: macOS
- VSCode version: 1.30.2
- VSCode extension version: 1.2.0
- Metals version: 0.4.0

**Comment by gabro** [comment]
@olafurpg apart from the `.scalafmt.conf` file, Metals seems to be creating a `.metals` directory in the wrong projects. I the example above, I would expect `.metals` to be created in `spark-common`, but it's created in `zoltar` (a front-end project) instead.

**Comment by olafurpg** [comment]
The `.metals` directory is created in the `rootUri` directory from the initialize request, which I think is a reasonable default. The alternative would be to try and guess which of the `workspaceFolders` should be the "main" workspace.
