### ISSUE TITLE
Reload workspace and reindex on Bazel build configuration has changed

### ISSUE THREAD

**Issue by tanishiking** [scalameta/metals#5144]
### Describe the bug

- Enter https://github.com/tanishiking/bazel-playground/tree/main/01-scala-tutorial
- launch bazel-bsp `cs launch org.jetbrains.bsp:bazel-bsp:2.6.1 -M org.jetbrains.bsp.bazel.install.Install`
- Open the project with Metals (`0.11.11+85-56c00d26-SNAPSHOT`) (server version should be https://github.com/scalameta/metals/commit/56c00d26b797f9828b7b76b1ed61f40d210bceae)
- Type `pp` somewhere in `lib/src/main/scala/Greeting.scala`, and `pprint` will be completed
- Remove `pprint` from `deps` in `BUILD` file. (Metals should show popup to ask users reindex the workspace).
- Type `pp` somewhere in `lib/src/main/scala/Greeting.scala` and `pprint` SHOULD NOT be completed because it's no longer in the scope, but it will be completed.

https://user-images.githubusercontent.com/9353584/231940785-593e203e-44ca-40f5-b242-408825f4dcc3.mov

### Expected behavior

When we edit `BUILD` file, Metals should ask users to reload workspace / reindex symbols (And if we add new dependencies to the BUILD, Metals should reindex the symbols for the new dependencies. Same applies to the removing deps).

While https://github.com/scalameta/metals/pull/3233/ did the job by defining [BazelDigest](https://github.com/scalameta/metals/pull/3233/files#diff-f3ca62198bb53913e788d4ec6316491676ac18813c4771da3a1cbc469caa5925), but I have a few concerns

- (1) Observe `WORKSPACE` and `BUILD` files isn't sufficient
  - In practical projects, we use a lot of starlark files `*.bzl` and `BUILD.bazel` files also need to be checked, maybe some more? 🤔 
- (2) With [projectview settings](https://github.com/JetBrains/bazel-bsp/blob/master/executioncontext/projectview/README.md) we shouldn't reload workspace if the updated Bazel file is excluded by projectview
  - this should be an extended goal
- (3) It would be neat if bazel-bsp can notify Metals by [buildTarget/didChange](https://build-server-protocol.github.io/docs/specification/#build-target-changed-notification)
  - With `buildTarget/didChange`, we can solve (2) because server knows which build targets are affected by the recent change.
  - However, I'm not sure this is feasible option, since I think Bazel cannot know there's a build change until we invoke `bazel build`. And I'm not sure we can know the build configuration has changed via BEP.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.11+85-56c00d26-SNAPSHOT

### Extra context or search terms

Bazel, BSP, reindex

**Comment by ckipp01** [comment]
Sort of related to 3 would be if something like this was implemented https://github.com/build-server-protocol/build-server-protocol/discussions/502, so then Bazel could just tell Metals which files to watch.
