### ISSUE TITLE
File Watcher is causing very slow Indexing stage with large codebase

### ISSUE THREAD

**Issue by crt-31** [scalameta/metals#5160]
### Describe the bug

On our very large codebase (Projects(338)/Libraries(883)), the indexing stage is taking 14 minutes, which seems really slow. It appears that the culprit is "starting file watcher" stage. It became slow once I enabled semanticdb generation in my build... without the semanticdb enabled it was only 2min. 

I presume the semanticdb generation is adding a bunch more directories and files that need to be watched, but still, 14 minutes vs 2 min doesn't seem right. 

Here's the times from the log file (note the file watcher times):

> **With SemanticDb enabled**
> 2023.04.19 20:00:28 INFO  time: reset stuff in 1ms
> 2023.04.19 20:00:29 INFO  time: updated main build targets in 1.72s
> 2023.04.19 20:00:29 INFO  time: updated ammonite build targets in 160μs
> 2023.04.19 20:00:29 INFO  time: updated scala-cli build targets in 88μs
> 2023.04.19 20:00:29 INFO  time: post update build targets stuff in 0.86s
> 2023.04.19 20:12:22 INFO  time: started file watcher in **11m51s**
> 2023.04.19 20:12:45 INFO  time: indexed library classpath in 23s
> 2023.04.19 20:12:54 INFO  time: indexed workspace SemanticDBs in 9s
> 2023.04.19 20:13:41 INFO  time: indexed workspace main sources in 46s
> 2023.04.19 20:13:41 INFO  time: indexed workspace ammonite sources in 792μs
> 2023.04.19 20:13:41 INFO  time: indexed workspace scala-cli sources in 445μs
> 2023.04.19 20:13:57 INFO  time: indexed library sources in 15s
> 2023.04.19 20:13:57 INFO  time: indexed library sources in 1ms
> 2023.04.19 20:13:57 INFO  time: indexed library sources in 987μs
> 2023.04.19 20:13:57 INFO  time: indexed workspace in 13m28s
> 

> 
> **Without SemanticDB enabled**
> 2023.04.19 20:38:40 INFO  time: reset stuff in 1ms
> 2023.04.19 20:38:42 INFO  time: updated main build targets in 1.74s
> 2023.04.19 20:38:42 INFO  time: updated ammonite build targets in 143μs
> 2023.04.19 20:38:42 INFO  time: updated scala-cli build targets in 81μs
> 2023.04.19 20:38:42 INFO  time: post update build targets stuff in 0.92s
> 2023.04.19 20:38:53 INFO  time: started file watcher in **9.93s**
> 2023.04.19 20:39:17 INFO  time: indexed library classpath in 24s
> 2023.04.19 20:39:17 INFO  time: indexed workspace SemanticDBs in 47ms
> 2023.04.19 20:40:05 INFO  time: indexed workspace main sources in 47s
> 2023.04.19 20:40:05 INFO  time: indexed workspace ammonite sources in 947μs
> 2023.04.19 20:40:05 INFO  time: indexed workspace scala-cli sources in 543μs
> 2023.04.19 20:40:22 INFO  time: indexed library sources in 16s
> 2023.04.19 20:40:22 INFO  time: indexed library sources in 969μs
> 2023.04.19 20:40:22 INFO  time: indexed library sources in 849μs
> 2023.04.19 20:40:22 INFO  time: indexed workspace in 1m41s
> 

Interestingly, the actual indexing seems really fast.

### Expected behavior

File watcher initialization would not take more than twice the time when semanticdbs are enabled vs when they are disabled.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.11

**Comment by tgodzik** [comment]
Thanks for reporting! It would probably be good to take a look at the actual flame graph here to see what is it spending the most time on. We can also add some more debug.

I wonder if setting `-Dmetals.macos-max-watch-roots=32` to a different value than the default might help, default is 32. You can also set `-Dmetals.loglevel=debug` to get more information.

**Comment by crt-31** [comment]
setting debug loglevel didn't provide me any more information. Also, I'm on Windows, so  macos-max-watch-roots isn't in play.

**Comment by tgodzik** [comment]
`macos-max-watch-roots` was intended for MAC, but it might also help out here. I think the name is actually wrong.

**Comment by crt-31** [comment]
So, I did some investigation, and I narrowed the issue down to Metals calling swoval PathWatcher.register(). I created [swoval issue #161](https://github.com/swoval/swoval/issues/161) hopefully the swoval guys can look into this.

also, looking at code the macos-max-watch-roots only affects macos.

**Comment by tgodzik** [comment]
I wonder though if we could use the same mechanism here to make the watching initialization faster. :thinking: 

Let's see first if anyone in swoval will be able to help out, thanks for investigating this!

**Comment by tgodzik** [comment]
You should be able to check a new SNAPSHOT version of Metals once the current build finishes https://github.com/scalameta/metals/actions/runs/4817707881

**Comment by crt-31** [comment]
Fyi, still have the issue with 0.11.12+19-66e5f3ce-SNAPSHOT

**Comment by crt-31** [comment]
We diagnosed the issue and fixed it... it is available in swoval 2.1.11.

So now someone just needs to bump the version used by Metals.

**Comment by tgodzik** [comment]
It's bumped, thank you very much for pursuing it! You can check the newest snapshot once it's out to confirm if it helps. 

Needs this release to finish https://github.com/scalameta/metals/actions/runs/6259564708

**Comment by tgodzik** [comment]
@crt-31 could you confirm?
