### ISSUE TITLE
"Go to implementations" and "Go to references" stopped working 

### ISSUE THREAD

**Issue by programaker** [scalameta/metals#5176]
### Describe the bug

After updating to Metals 0.11.12, the commands "Go to implementations" (Command + F12) and "Go to references" (Shift + F12) are not working anymore.

To cause the bug, I just tried the commands above against one of the methods of a trait, and the result was a small tooltip saying there was no implementations/references for that method - but there is one implementation and ~12 references.

I had to revert back to 0.11.11.

I'm using sbt v1.8.2 as build server.

### Expected behavior

The expected behavior is the same as 0.11.11, which is finding the implementations and references of the trait's methods.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

### Extra context or search terms

Go to implementations 
Go to references

**Comment by programaker** [comment]
I don't have any `.metals/.reports` folder yet:
<img width="613" alt="Screenshot 2023-04-24 at 21 26 59" src="https://user-images.githubusercontent.com/83928/234096679-11081ffc-01c6-4434-bdd8-22abdb8207f0.png">

The project compiles and everything seems to work (except these 2 features I'm reporting).

The strangest thing I could find in `metals.log` was:
```
Apr 24, 2023 9:26:29 PM scala.meta.internal.pc.CompilerAccess retryWithCleanCompiler
INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
```
I'm also using Scala 2.13.10 and JDK 19.0.2 from Eclipse Adoptium.
Metals Doctor also doesn't show anything wrong.

**Comment by tgodzik** [comment]
> ```
> 
> INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
> ```

Does this log happen more than once? 

Is it only one project or the features doesn't work with any of them? 

One possibility is that metals doesn't work with JDK 19, but I can't be sure since we only test with 17. You could try that. 

Also, we could try printing semanticdb for a file with the references that you are looking for, maybe it's missing, but not sure why that would happen if the project compiles. You can use the command `Metals: Show Semanticdb detailed` or right click on the file and there should be `Metals analyze source` submenu there.

**Comment by programaker** [comment]
I've tried 2 other projects (both in Scala 3). In one of them the problem happens, but in the other it works.

The difference between them is the sbt server. The project where it works is using Bloop.

**Comment by programaker** [comment]
`Show Semanticdb detailed` works.
Java version seems unlikely, as v0.11.11 was working fine with JDK 19

**Comment by tgodzik** [comment]
My hope was that we don't have semanticdb, because we use that for both features, but if it's there we should be able to find the references correctly :thinking: 

Any chance you could shed a light on how does the project look like? Maybe a small reproduction that it also fails with?

**Comment by programaker** [comment]
I was able to reproduce the issue also on my personal machine, using the Octogato project.

**Comment by programaker** [comment]
I made an experiment:
- deleted ~/.sbt
- reverted Metals to 0.11.11 and let it recreate the ~/.sbt folder
- copied ~/.sbt as ~/.sbt_bkp
- set Metals back to 0.11.12
- deleted ~/.sbt
- renamed ~/.sbt_bkp to ~/.sbt

Now the commands are working!
0.11.11 generates something in ~/.sbt that is missing in 0.11.12
It will probably stop working after closing the project or something...

**Comment by tgodzik** [comment]
I cannot reproduce the problem locally with https://github.com/programaker/Octogato :thinking: and we don't really write anything to the global .sbt directory, so this shouldn't be an issue.

Maybe the flags somehow change? If you run the doctor for each version and check the project configuration (click on the name) does it look the same?

**Comment by programaker** [comment]
Got the `.metals-buildtargets` for both versions, run a `diff -y` between them and nothing. They are identical.

I've installed sbt via coursier instead of brew (probably irrelevant to the problem, but...)

**Comment by tgodzik** [comment]
If we can't figure it out I will try to add some more reports to have that automatically reported to file.

**Comment by programaker** [comment]
BREAKING NEWS: I've deleted a bunch of folders - `.bloop`, `.metals`, `.bsp`, `target`, `project/project` (basically as if opening the app in Metals for the 1st time), and it worked!

It wasn't very scientific, as I can't tell which folder deletion solved the issue (maybe the targets, as the semanticdb files live there 🤔)

**Comment by tgodzik** [comment]
Glad it worked for you! We need to add however more reporting so we can find the root cause of this

**Comment by programaker** [comment]
Meanwhile, I'll try to fix other projects and see if I can find exactly what worked

**Comment by programaker** [comment]
I was the `target` folders - all of them. Didn't have to remove everything when fixing the same project on my personal machine

**Comment by tgodzik** [comment]
I wonder why that was, we didn't change anything in regards to reading semanticdb. Let me know if that happens again, we will try to add some reporting in the meantime.

**Comment by benjhm** [comment]
Just to say, I have the same problem - since 11.12 "Find references" (and hence any refactoring) stopped working.  
Am also using sbt 1.8.2 for bsp, scala 3.3.0-rc4, and java 17 - it's a js/jvm cross-project.   Tried deleting folders as suggested above, also tried swapping sbt<->bloop, none solved it, so I reverted  to 11.11, and find references works again.

**Comment by programaker** [comment]
It's me again! 

Even though deleting all "target" folders (using `find . -name "target" -type d -exec rm -rf {} \;`) and `"Restarting build service"` (I think I didn't mention this step before) worked for me, it was not a permanent solution. Find references stopped working again.

Repeating the steps above fix the problem again - for now

**Comment by MrLIVB** [comment]
Same, scala 2.13.8, java 1.8, sbt 1.6.2, after some time go to implementation and go to reference just stops working, deleting target folders helps, but then it repeats  
Managed to find these message in logs, but not sure if it's connected to issue:
```
2023.05.12 16:30:41 WARN  Could not find semantic tokens for: ...
May 12, 2023 4:30:41 PM scala.meta.internal.pc.CompilerAccess retryWithCleanCompiler
INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
```

**Comment by tgodzik** [comment]
I think I managed to reproduce it, I will look into it today or after the weekend. Sorry for the inconvenience!

**Comment by tgodzik** [comment]
I found a nasty bug in https://github.com/scalameta/metals/pull/5222/files this should probably fix a lot of things.

**Comment by tgodzik** [comment]
You can check out the newest snapshot to see if this was fixed. If not I will need to dig in some more

**Comment by programaker** [comment]
Ok, got the version `0.11.12+42-ed1333b0-SNAPSHOT` and started coding.

After some time, the "Semantic Highlight" stopped working (usually in the middle of typing something, when there's still compiling errors to fix), and with it also the Hover/type-at-point (probably code completion stopped too, but didn't check this time). 

However, there are good news: even after the highlight and hover crashed, "Find References" and "Find Implementations" were still working! So the protagonist issue might be solved!

I'm trying now with the "Semantic Highlight" disabled to see if the situation changes. I miss the colors but 🤷🏻‍♂️

**Comment by tgodzik** [comment]
> Ok, got the version `0.11.12+42-ed1333b0-SNAPSHOT` and started coding.
> 
> After some time, the "Semantic Highlight" stopped working (usually in the middle of typing something, when there's still compiling errors to fix), and with it also the Hover/type-at-point (probably code completion stopped too, but didn't check this time).
> 
> However, there are good news: even after the highlight and hover crashed, "Find References" and "Find Implementations" were still working! So the protagonist issue might be solved!
> 
> I'm trying now with the "Semantic Highlight" disabled to see if the situation changes. I miss the colors but 🤷🏻‍♂️

Would be great to see what's going on there, this means usually that the presentation compiler isn't able to recover the errors. We could do some fallbacks for semantic highlight, but if compiler is having too many issues then we might need to fix it there :thinking:  Does it start working again after fixing the compilation issues? Are those compilation issues across multiple files or just one?

**Comment by programaker** [comment]
It doesn't recover after fixing the errors.  

I'm working on a single file (a test class) but when the highlight stops, it does so for all open files (didn't try to open a another).

By the way, it's stable without Semantic Highlight so far...

**Comment by programaker** [comment]
Meanwhile, there's a new snapshot: `0.11.12+45-45df705d-SNAPSHOT`

**Comment by programaker** [comment]
The issue with "find references and implementations" seems to be fixed 🎉 
It's not breaking anymore, even when other features stop working.

The problem with hover, code-completion and semantic-highlight might be another story, and I'm using a Snapshot after all, so no guarantees...

**Comment by tgodzik** [comment]
> The problem with hover, code-completion and semantic-highlight might be another story, and I'm using a Snapshot after all, so no guarantees...

This should work, maybe not if the code is too broken (although some fixes are coming https://github.com/scalameta/metals/pull/5219 which is an approach the same as presentation compiler, but for the entire workspace)

**Comment by tgodzik** [comment]
Do you get any logs in `.metals/metals.log` or in `.metals/reports` when this starts to happen? Ideally when the code is compiling again we should get everything working nicely. What seems to be happening is that the compiler is broken and we should most likely force a restart (which should already happen after successful compile though)

Any additional info would be useful. It could be in another issue to not polute this one.

**Comment by programaker** [comment]
Besides the `Could not find semantic tokens for file` mentioned above, nothing new. I got the `0.11.12+46-703b2b28-SNAPSHOT` and it's being stable for hours. If it breaks again, I'll check the `.metals` folder for more clues (maybe in another issue as you suggested, as find references is not breaking anymore).

**Comment by tgodzik** [comment]
Ok, the first one should be fixed in https://github.com/scalameta/metals/pull/5238

The second one is most likely related to something in the compiler and we would need a reproduction, which might be hard to find. We should save the file in the reports, so that it can be later minimized before sending to us.

**Comment by tgodzik** [comment]
Although most likely that was one off and the compiler might sometimes break in case of weird code (that happens during typing)

**Comment by programaker** [comment]
Currently using Metals `0.11.12+62-2f85dfa0-SNAPSHOT` (the one with #5238) since this morning. Pretty stable so far; hover, syntax highlight and completion didn't break even after a refactoring and branch merging.

The original problem also never came back, so I'll close this issue 🎉. If I experience the other problems discovered here again, I'll open new issues for them!
