### ISSUE TITLE
"illegal start of definition identifier" from scala-cli shebang

### ISSUE THREAD

**Issue by phrmoy** [scalameta/metals#5179]
Hello,
Inserting a shebang in .scala file such as

#!/usr/bin/env -S scala-cli shebang --java-opt -Xms256m --java-opt -XX:MaxRAMPercentage=80 --dependency com.rmet::scground:0.1.0

yields a "illegal start of definition identifier".

It has been indicated to me once that this was a bug. I searched issues for it but I could not find anything reported yet.

Using Metals v1.23.0.

Thank you.

**Comment by phrmoy** [comment]
Thanks for caring for this. Has the fix made it into the current version of Metals yet? I am on v1.23.4
 and I am still facing the same issue.

<img width="576" alt="image" src="https://github.com/scalameta/metals/assets/3697931/fe1e95a9-d276-4f1f-b788-4f5fe7a8ed42">

**Comment by tgodzik** [comment]
This is under snapshot versions like the ones showed in https://scalameta.org/metals/docs/
