### ISSUE TITLE
semantic highlighting not working

### ISSUE THREAD

**Issue by andyczerwonka** [scalameta/metals#5190]
### Describe the bug

![image](https://user-images.githubusercontent.com/138898/235309710-12cf8f2f-2573-4b99-8f52-17193ff39553.png)

I tried to fix it via removing ./.bloop ./.metals ./.bsp , restarted, and same thing.

Not all files. When I navigate elsewhere, it seems to work okay.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

**Comment by andyczerwonka** [comment]
There was a comment above, e.g.

```
    /*
        This comment was

        removed and it started working just fine
     */
```

Once removed, it starts working again.

**Comment by andyczerwonka** [comment]
If you remove the blank line in the comment, it works fine.

**Comment by jkciesluk** [comment]
Hi, it was fixed in https://github.com/scalameta/metals/pull/5178
I should work fine in pre-release

**Comment by tgodzik** [comment]
Thanks for reporting @andyczerwonka ! I can confirm this was fixed in the newest snapshot.
