### ISSUE TITLE
Empty line in multiline string breaks semantic coloring

### ISSUE THREAD

**Issue by lolgab** [scalameta/metals#5224]
### Describe the bug

Having an empty line (without spaces) in a multiline string breaks the semantic coloring that becomes all wrong.

Here an example video:
https://github.com/scalameta/metals/assets/5793054/4022b2a3-4439-40a3-9912-f8f64837b3a2

To reproduce you need to add:
```scala
  """

  """
```

in a Scala file, and the coloring changes drastically.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

**Comment by jkciesluk** [comment]
Hi, this was fixed in https://github.com/scalameta/metals/pull/5178 and should be working in pre-release version

**Comment by tgodzik** [comment]
> Oh, I'm sorry. I should have trying on the latest SNAPSHOT

That would be cool, but you really don't have to. We can always check it out oursleves
