### ISSUE TITLE
Scala 3 multi-module sbt project and completion issues

### ISSUE THREAD

**Issue by yzia2000** [scalameta/metals#5225]
### Describe the bug

When I have a project structure like below:

```
external-lib-a

core (depends on external-lib-a)
extras (depends on core)
examples (depends on core and extras)
```

Then auto-complete cannot suggest functions from `external-lib-a` in the module `examples` when calling functions from `core` and `extras` which reference `external-lib-a`. This problem cannot be reproduced on 2.13 but I see it happening on 3.2.2.

Example project in case you want to try - https://github.com/yzia2000/zio-amps (try auto-completions in this file https://github.com/yzia2000/zio-amps/blob/main/examples/src/main/scala/zio/amps/examples/tradeAggregator/TradeAggregator.scala).

I can also reproduce this issue on both the sbt and bsp backends as well on both vscode and neovim.

Haven't deep dived into what the core problem and all the features apart from auto-completions affected but would love to help or use pointers.

### Expected behavior

Above mentioned environment  should have auto-completions work like in 2.13.

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.12

**Comment by yzia2000** [comment]
I would love to contribute by submitting a PR or sharing more information if needed

**Comment by tgodzik** [comment]
Thanks for reporting! I checked out the repo but I can't find any issues. What do you mean by:

> Then auto-complete cannot suggest functions from external-lib-a in the module examples when calling functions from core and extras which reference external-lib-a. 

Could you provide an example of what doesn't work?

**Comment by yzia2000** [comment]
> Thanks for reporting! I checked out the repo but I can't find any issues. What do you mean by:
> 
> > Then auto-complete cannot suggest functions from external-lib-a in the module examples when calling functions from core and extras which reference external-lib-a.
> 
> Could you provide an example of what doesn't work?

@tgodzik In the screenshot, the `Subscriber.subscribe` function is implemented in an sbt module part of the project. It returns an object of type ZStream (from zio-stream, an external library I am using in this project) but I am unable to access autocompletions for members of the returned object. However it does give me diagnostics like errors and warnings after saving the file. Do I provide another example?

![image](https://github.com/scalameta/metals/assets/42372397/a2655e5e-20fa-43d0-8aba-e9018643d4f2)
