### ISSUE TITLE
Metals offers auto-completion of extension methods that "do not exist" due to @targetName

### ISSUE THREAD

**Issue by phrmoy** [scalameta/metals#5249]
### Describe the bug

@targetName("buildLongFormatFromArraySeqMap") def buildLongFormat

Metals is offering "buildLongFormatFromArraySeqMap" as an auto-completion when we cannot, in fact, call "foo.buildLongFormatFromArraySeqMap," instead, we can only call "foo.buildLongFormat."

And or so, this is my understanding. 

Metals version: v1.23.1

Pedro

### Expected behavior

Metals should offer only "foo.buildLongFormat" in the auto-completion tab.

### Operating system

None

### Editor/Extension

None

### Version of Metals

v1.23.1

**Comment by kasiaMarek** [comment]
I tried with such a simple example:
import scala.annotation.targetName
      |class Vec[T]():
      |  @targetName("append") def add(ys: Vec[T]): Vec[T] = ???
      |
      |val v1 = Vec[Int]
      |val m = v1.a@@
