### ISSUE TITLE
Cancelling compilation doesn't always cancel compilation

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#5251]
### Describe the bug

I noticed that when working in codebases that take quite some time to compile, when I try the cancel compilation command it doesn't always work. For example I recently tried this in Dotty and looking at the LSP logs I see:

```
[Trace - 05:45:09 pm] Received request 'workspace/executeCommand - (30)'
Params: {
  "command": "metals.compile-cancel"
}


[Trace - 05:45:09 pm] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2023.05.21 17:45:09 INFO  compilation cancelled"
}


[Trace - 05:45:09 pm] Sending response 'workspace/executeCommand - (30)'. Processing request took 1ms
Result: {}

[Trace - 05:45:09 pm] Sending notification 'metals/status'
Params: {
  "text": "Compiling scala3-compiler 1m36s (0%)"
}
```

Notice that I'm still getting notifications about compilation after the "INFO compilation cancelled". 

### Expected behavior

I'd expect a cancel compilation request to cancel all ongoing compilation.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.12+61-88c5e82e-SNAPSHOT

### Extra context or search terms

This was using sbt as my build server.

**Comment by tgodzik** [comment]
I think that cancelling i closely related to progress. So there is a check for cancel whenever work advances, there is no actual forcing of compilation stop.

Though I wonder whether this is Bloop or sbt? I think only Bloop has an actual support for cancelling. It should also get a notification about that. If it doesn't we might need to fix something on the Metals side.

**Comment by tgodzik** [comment]
Looks like this is the same issue as https://github.com/scalameta/metals/issues/5643 and we are waiting for the fix in dotty itself
