### ISSUE TITLE
`tests.debug.BreakpointScalaCliDapSuite` fails pretty consistently on the windows 17 job

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#5254]
### Describe the bug

Looking at the Ci runs, `tests.debug.BreakpointScalaCliDapSuite` is failing almost every run on the windows 17 job. For example you can see this [here](https://github.com/scalameta/metals/actions/runs/5040565708/jobs/9039464474?pr=5252).

### Expected behavior

This test should be fixed or made less flaky.

### Operating system

None

### Editor/Extension

None

### Version of Metals

head

**Comment by tgodzik** [comment]
Looks like it might be all the ScalaCLI tests:
```
2023.05.22 16:30:56 INFO  BSP server: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000243e4170000, 1835008, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
2023.05.22 16:30:56 INFO  BSP server: #
```
we start 2x Bloop which might cause problems with memory.

**Comment by tgodzik** [comment]
I haven't seen this fail in a while, I will take a look the next time I see it.

**Comment by tgodzik** [comment]
Ach also, we no longer run this on Windows.
