### ISSUE TITLE
Bloop struggles to compile mtags-java

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#5280]
### Describe the bug

So this might be hard to test with VS Code since it supports this, but I'm pretty sure this is related to the changes that are necessary in clients shown [here](https://github.com/scalameta/metals-vscode/pull/1395). The issue is that starting Metals this way is easy if the client knows about it, but there are clients that totally won't be aware of this. I'm thinking some of the more unpopular ones like [Helix](https://helix-editor.com/), but they _do_ have some Metals users. For example I just hit on this with `nvim-metals` since I don't have that implemented yet. The issue is that when I open the Metals code base now I see this in my doctor (I removed a bunch of irrelevant stuff):

```
## Metals Info
  - Metals Server version: 0.11.12+77-cce28f19-SNAPSHOT
  - Metals Java: 17.0.7 from Eclipse Adoptium located at /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
  - Build server currently being used is Bloop v1.5.6.

These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

## Build Targets

### mtags-java
  - target type: Scala 2.13.10
  - compilation: ❌
  - diagnostics: ✅ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ✅ 
  - java: ✅ 

## Explanations

### Compilation status:
✅  - code is compiling
❌ - code isn't compiling, open problems tab to see detailed compilation errors

### Java Support:
✅  - working non-interactive features (references, rename etc.)
```
According to this, `mtags-java` isn't compiling. However, interactive is ✅ and every other module also have full ✅  giving me the assumption that everything is working. However, if I look at my workspace errors I do see a ton of issues in `mtags-java`, 99 of them to be exact:

<img width="858" alt="Screenshot 2023-05-28 at 14 00 29" src="https://github.com/scalameta/metals/assets/13974112/60b8cd87-8d96-4c81-8920-4d1e31415ab3">

Almost all of them have to do with not have the `com.sun` imports. This is problematic because it also affects navigation all around the codebase. For example if I'm in `BspConnector` and I try to find reference I see the trigger to compile `mtags-java`, but it fails  and then nothing happens. So essentially I have almost no navigation in the codebase even though the Doctor shows me full ✅ for all interactive and semanticdb. There is actually a couple different issues here:

1. The doctor doesn't seem to be reporting correctly. Inside of Metals I have tons of features not working, when lots of them should be marked as ❌ since I can't navigate around for anything relying on `mtags-java`.
2. There is a question about the architecture of the java support. It's fair to say that arguable Metals should take care of what is needed to offer support for certain features. If a client doesn't support something, that's fine but I don't think that should be able to bork a workspace. I brought something related up [here](https://github.com/scalameta/metals-vscode/pull/1395#issuecomment-1555964220), but I really wish clients didn't need to have special logic to start Metals in a certain way. This really has nothing to do with capabilities in the LSP sense, but instead this forces clients to special case starting the server, or they don't get specific support. This doesn't feel right. I really wish it was possible for Metals to be started in a vanilla way by all clients, and it take care of what is needed to offer support. 

### Expected behavior

- I would expect any LSP client to be able to open the Metals codebase and work on it
- I would expect the Doctor to accurately show the status of the workspace.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.12+77-cce28f19-SNAPSHOT

### EDIT

I left a bunch of the stuff up above, but what really seems to be happening is that Bloop is struggling with mtags-java. I've gone ahead and updated the title for this.

**Comment by tgodzik** [comment]
Thanks for reporting! Actually, this is related to Bloop, which seems to be having problems compiling the java-mtags module. I don't think it's related to the client options. You should be able to workaround it by using sbt BSP or JDK8/11 (though the experience varies). I need to take a look at that, but didn't have time.

**Comment by ckipp01** [comment]
> Thanks for reporting! Actually, this is related to Bloop, which seems to be having problems compiling the java-mtags module. I don't think it's related to the client options. You should be able to workaround it by using sbt BSP or JDK8/11 (though the experience varies). I need to take a look at that, but didn't have time.

Ahhh, you're correct! Switching to sbt BSP did indeed solve everything. I've updated the description.
