### ISSUE TITLE
Installation does not fully work behind corporate proxy server

### ISSUE THREAD

**Issue by jliverman** [scalameta/metals#529]
I've setup my JAVA_FLAGS, http_proxy, https_proxy and ftp_proxy (as well as my no_proxy) settings in my shell environment and under Java's Mission Control applet. I've also configured the VScode "http.proxy" variable. For my system to work "completely" I've also had to setup my corporate proxy for apt, git and docker individually. I normally don't have problems once I configure my proxy correctly. 

However, Metals gave me issues. The extension installed fine from the VScode extensions sidebar. But in the background once it got to the "Downloading Metals" state, it failed. I was unable to locate the "correct" configuration to get it working, so I manually ran the "fetch" operation on the command-line (stolen from the VScode "OUTPUT" tab along with a little "ps -ef" snooping). Metals installed fine and I was able to "Go to definition", "Peek definition", etc.

However, then I got the "Downloading Bloop" message and could not figure out what command-line needed to be ran (I saw what was attempting to download using the VScode "OUTPUT" tab, but I'm not really a Java/Bloop guy so I had no idea where to download Bloop or how to properly install/configure it for Metals; BTW I've only recently started using Scala so I'm really a complete n00b). I finally had to boot my machine on an outside network and physically bypass my corporate proxy to get Bloop installed. After Bloop was installed I could import my sbt build and everything seems to work as advertised. Metals is way faster than ENSIME et al from what I can tell... I LIKE IT!! Anyway...

Metals should either 1) be setup to respect current configurations regarding the proxy (i.e. the VScode "http.proxy" variable, JAVA_FLAGS or Java's Mission Control settings) 2) create it's own proxy configuration variable (a la "java.jdt.ls.vmargs" for the Red Hat VScode Java extension; which I also have configured, by the way) or 3) provide instructions for manual installation/download of both Metals and Bloop on their website.

Please save the next person the trouble I had by addressing at least 1 of my points above. Or if I have failed to do something straightforward to help myself (given the above explanation) then please let me know so I can learn something.

Thank you!

**Comment by olafurpg** [comment]
Thanks for reporting! See https://github.com/scalameta/metals-vscode/issues/70 and https://github.com/scalameta/metals-feature-requests/issues/9. I opened https://github.com/scalameta/metals/pull/530 to document how to use Metals behind an HTTP proxy. We could add support for `JAVA_FLAGS` alongside `JAVA_OPTS` here https://github.com/scalameta/metals-vscode/blob/f8a49bae54af41a722beab860495879de7431dd2/src/getJavaOptions.ts#L22

**Comment by olafurpg** [comment]
I opened two issues in the VS Code extension to further improve the experience for users behind an HTTP proxy
