### ISSUE TITLE
Completions in iskra don't seem to work anymore

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#5293]
### Describe the bug

Hi! I think this is a regression because I saw it working back in November 2022, but it doesn't seem to work anymore.

To reproduce:

1. Create a file, e.g. `main.scala`:
```scala
//> using lib "org.virtuslab::iskra:0.0.3"
//> using scala "3.3.0"
import org.virtuslab.iskra.api.*
import org.virtuslab.iskra.api.given

given spark: SparkSession = SparkSession
  .builder()
  .master("local")
  .appName("my-spark-app")
  .getOrCreate()

object demo {

  case class Foo(x: Int, y: Int)

  val df = Seq(Foo(1, 420), Foo(2, 50)).toTypedDF
  df.select {
    val sum = ($.x + $.y).as("sum")
    ($.x, $.y, sum)
  }

}
```

2. Try to do completions in `    val sum = ($.<CURSOR>x + $.y).as("sum")`
3. Nothing shows up

### Expected behavior

`x` and `y` are available fields in the completions

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.12, 0.11.12+91-8ed12f69-SNAPSHOT

### Extra context or search terms

build tool: scala-cli 1.0.0

Also, other features like hover and "insert type annotation" don't work either, but navigation is fine (I can click on `x` in `$.x` and the cursor moves to the field definition in the case class).

**Comment by kubukoz** [comment]
Notably, it seems like navigation works based on indexes, whatever that means:

<img width="805" alt="image" src="https://github.com/scalameta/metals/assets/894884/5540c7ae-e640-4eb4-bc41-400727b4ef63">

I also see this in the logs:

```
2023.05.31 18:04:26 INFO  no build target found for /Users/kubukoz/projects/demos/main.scala. Using presentation compiler with project's scala-library version: 3.3.0
```

which is strange, because my bsp config was made from `scala-cli compile .`, and the BSP config file looks like this:

```json
{
  "name": "scala-cli",
  "argv": [
    "/nix/store/pas8xp5gbrnfkl6xjw9mrak81fqirmw4-scala-cli-1.0.0/bin/scala-cli",
    "bsp",
    "--json-options",
    "/Users/kubukoz/projects/demos/.scala-build/ide-options-v2.json",
    "/Users/kubukoz/projects/demos"
  ],
  "version": "1.0.0",
  "bspVersion": "2.1.0-M3",
  "languages": [
    "scala",
    "java"
  ]
}
```

I have confirmed that `/nix/store/pas8xp5gbrnfkl6xjw9mrak81fqirmw4-scala-cli-1.0.0/bin/scala-cli` is a legit path to the scala-cli binary, and my `ide-options-v2.json` is `{}`.

**Comment by kubukoz** [comment]
confirmed, 0.11.11 and Scala 3.2.2 works fine.

**Comment by jkciesluk** [comment]
For me it works fine if I publish snapshot locally, but not on latest pre-release (0.11.12+96-4a67b645-SNAPSHOT)
<img width="699" alt="image" src="https://github.com/scalameta/metals/assets/72950514/40783a81-2361-4855-bc96-e2fa082a8026">

**Comment by tgodzik** [comment]
Are you sure your code code is up to date with the main branch? You should also make sure that you publish mtags correctly for the version used in the snippet.

**Comment by kasiaMarek** [comment]
Looking at commits https://github.com/scalameta/metals/commit/9e781aef0f4ce1c17e072810d25a230c1766cb56 was the most invasive one and I checked that it stopped working after those changes.

**Comment by tgodzik** [comment]
> Looking at commits [9e781ae](https://github.com/scalameta/metals/commit/9e781aef0f4ce1c17e072810d25a230c1766cb56) was the most invasive one and I checked that it stopped working after those changes.

I can confirm, it breaks with that commit :thinking:
