### ISSUE TITLE
Incorrect error messages breaking project, looping build

### ISSUE THREAD

**Issue by EliasNym** [scalameta/metals#5313]
### Describe the bug

Have been using Metals for close to a year. Today when i got back to work, errors are all over the place.
I have absolutely no idea what to do or how to debug this...

I've ran: reimporting build, restarting build server, run doctor, recompile workspace..
i've restarted IDE, and the computer and switched build server, but nothing helps.

Metals Doctor:
![Screenshot 2023-06-07 at 11 30 45](https://github.com/scalameta/metals/assets/72249329/6ab95231-9fc5-4169-97a9-21e40f92c465)

Here is a picture of error message telling me that basic Duration values do not exist, casually followed by giving me the signature for this "non-existing" value.. If i click "goto definition" it will open up Java.time.Duration and show me this exact function..

![Screenshot 2023-06-07 at 11 17 29](https://github.com/scalameta/metals/assets/72249329/c4700475-9ecc-4ec3-9438-297e75e11ba9)

Also, all the proper error messages are missing.. there is known error in a file i was working on yesterday, but thats all cool and working if you ask the IDE.

This quick and dirty test code does not work at all, but no errors here!
![Screenshot 2023-06-07 at 11 24 56](https://github.com/scalameta/metals/assets/72249329/9da46d63-e122-4491-8a84-1296417f653b)

Also logs seem to loop this same thing over and over and over..
It logs the non-existing errors, but none of the real errors, and then starts over again.

Jun 07, 2023 11:16:55 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 678
2023.06.07 11:17:55 ERROR 5 errors found
2023.06.07 11:17:57 INFO  time: compiled root-test in 2m22s
2023.06.07 11:17:57 INFO  Processing buildTarget/jvmRunEnvironment
2023.06.07 11:17:57 INFO  compiling root
2023.06.07 11:17:57 INFO  time: compiled root in 721μs
2023.06.07 11:17:57 INFO  compiling root-test
2023.06.07 11:17:57 INFO  compiling 187 Scala sources to.../target/scala-2.13/test-classes ...
2023.06.07 11:18:11 ERROR.../test/models/JsonProgramSpec.scala:125:60: value toSecondsPart is not a member of java.time.Duration
2023.06.07 11:18:11 ERROR         s"a ${programDuration.toMinutes}m${programDuration.toSecondsPart}s program" should {
2023.06.07 11:18:11 ERROR                                                            ^
2023.06.07 11:18:11 ERROR ...//test/models/JsonProgramSpec.scala:126:93: value toSecondsPart is not a member of java.time.Duration
2023.06.07 11:18:11 ERROR           s"not be finished at ${belowThresholdDuration.toMinutes}m${belowThresholdDuration.toSecondsPart}s (${programDuration.minus(belowThresholdDuration).toSeconds}s remaining)" in {
2023.06.07 11:18:11 ERROR                                                                                             ^
2023.06.07 11:18:11 ERROR .../test/models/JsonProgramSpec.scala:126:158: value toSeconds is not a member of java.time.Duration
2023.06.07 11:18:11 ERROR           s"not be finished at ${belowThresholdDuration.toMinutes}m${belowThresholdDuration.toSecondsPart}s (${programDuration.minus(belowThresholdDuration).toSeconds}s remaining)" in {
2023.06.07 11:18:11 ERROR                                                                                                                                                              ^
2023.06.07 11:18:11 ERROR ...//test/models/JsonProgramSpec.scala:130:79: value toSecondsPart is not a member of java.time.Duration
2023.06.07 11:18:11 ERROR           s"be finished at ${thresholdDuration.toMinutes}m${thresholdDuration.toSecondsPart}s (${programDuration.minus(thresholdDuration).toSeconds}s remaining)" in {
2023.06.07 11:18:11 ERROR                                                                               ^
2023.06.07 11:18:11 ERROR ...//test/models/JsonProgramSpec.scala:130:139: value toSeconds is not a member of java.time.Duration
2023.06.07 11:18:11 ERROR           s"be finished at ${thresholdDuration.toMinutes}m${thresholdDuration.toSecondsPart}s (${programDuration.minus(thresholdDuration).toSeconds}s remaining)" in {
2023.06.07 11:18:11 ERROR                                                                                                                                           ^
2023.06.07 11:19:49 ERROR 5 errors found
2023.06.07 11:19:49 INFO  time: compiled root-test in 1m52s

### Expected behavior

Not showing non-existing errors, but to show actual errors..

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.12

**Comment by EliasNym** [comment]
Fixed with @kasiaMarek Thank you!

**Comment by kasiaMarek** [comment]
I’d not close it quite yet. The following flow should still be fixed:
1. use sbt build tool
2. change java home
3. restart metals server/ restart IDE
The change of java home is not reflected in the build tool.

**Comment by kasiaMarek** [comment]
So most of the confusion comes from the fact that metals never stops the `sbt` build server ([`build/shutdown` doesn't kill the server](https://github.com/sbt/sbt/issues/6723)). To stop the server you have to explicitly run `sbt -client shutdown`. This becomes problematic when you switch java versions, since metals will still connect to the build server started before the change. I think the following should be done:

1. `Restart build server` should work for `sbt`, so in case the user needs to restart it for `sbt` they don't have to kill java processes/know to run `sbt -client shutdown`,
2. we should make sure that `java home` setting change this is reflected in the generated `.bsp/sbt.json` (similarly to how the change is handled for `bloop`),
3. possibly shutdown `sbt` build server on metals shutdown (we can have a setting to override this behaviour).

CC: @tgodzik
