### ISSUE TITLE
 Timeout waiting for 'build/initialize' response

### ISSUE THREAD

**Issue by passion123** [scalameta/metals#5333]
Hi all，while i want to use metals plugin on the eclipse theia to debug scala，it shows the below error，
 
![image](https://github.com/scalameta/metals/assets/9447543/7fe63140-e780-4a56-aa23-7991eb355aec)
My versions as below ：
Scala 2.11.8-2.11.12（limited by spark）
metals：all versions has been tried
eclipse theia：1.36.0

Do u have any ide on solving this?

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like we couldn't start the build server, are there any more logs pointing to the reason of that? Usually it's caused by missing dependencies, which it was unable to download.

Do you have an example workspace this fail in?

**Comment by passion123** [comment]
No,i don't have a workspace online. I guess it's caused by missing dependencies,but could't find what dependencies they are and located in, so that i can't upload these dependencies offline.
my versions are:
 jdk: 8  11  17
Scala 2.11.8-2.11.12（limited by spark）
metals：all versions has been tried
eclipse theia：1.36.0.
**I have another ubuntu server ，which can build the metals server,but also meets an issues is “ java.util.concurrent.CompletionException: java.lang.ClassNotFoundException”，but the *.scala file is existed. do you have some advice on the new issue ?**

**Comment by tgodzik** [comment]
Could you post the full logs? There should be a bit more info there.

**Comment by passion123** [comment]
Hi ，Here is the whole log：
2023.06.07 03:14:36 INFO Attempting to connect to the build server...
2023.06.07 03:14:36 INFO Bloop uses /usr/lib/jvm/java-8-openjdk-amd64/jre defined at /home/theia/.bloop/bloop.json
2023.06.07 03:14:35 INFO skipping build import with status 'Failed'
2023.06.07 03:14:36 INFO tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/project/Test/.metals/bsp.trace.json or /home/theia/.cache/metals/bsp.trace.json
2023.06.07 03:14:37 INFO no build target found for /home/project/Test/src/main/java/com/test/VehiclePassVerificationScalaModel.scala. Using presentation compiler with project's scala-library version: 3.2.2
2023.06.07 03:14:40 INFO time: code lens generation in 3.64s
Error, couldn't show release notes for Metals 0.11.12
Timeout occured during get request at https://api.github.com/repos/scalameta/metals/releases/tags/v0.11.12
2023.06.07 03:14:56 ERROR Timeout waiting for 'build/initialize' response
2023.06.07 03:14:56 WARN Retrying connection to the build server Bloop
2023.06.07 03:14:56 INFO Bloop uses /usr/lib/jvm/java-8-openjdk-amd64/jre defined at /home/theia/.bloop/bloop.json
2023.06.07 03:14:56 INFO tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/project/Test/.metals/bsp.trace.json or /home/theia/.cache/metals/bsp.trace.json
2023.06.07 03:15:16 ERROR Timeout waiting for 'build/initialize' response
2023.06.07 03:15:16 WARN Retrying connection to the build server Bloop
2023.06.07 03:15:16 INFO Bloop uses /usr/lib/jvm/java-8-openjdk-amd64/jre defined at /home/theia/.bloop/bloop.json
2023.06.07 03:15:16 INFO tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/project/Test/.metals/bsp.trace.json or /home/theia/.cache/metals/bsp.trace.json
2023.06.07 03:15:36 ERROR Timeout waiting for 'build/initialize' response
2023.06.07 03:15:36 WARN Retrying connection to the build server Bloop
2023.06.07 03:15:36 INFO Bloop uses /usr/lib/jvm/java-8-openjdk-amd64/jre defined at /home/theia/.bloop/bloop.json
2023.06.07 03:15:36 INFO tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/project/Test/.metals/bsp.trace.json or /home/theia/.cache/metals/bsp.trace.json
2023.06.07 03:15:56 ERROR Timeout waiting for 'build/initialize' response
2023.06.07 03:15:56 WARN Retrying connection to the build server Bloop
2023.06.07 03:15:56 INFO Bloop uses /usr/lib/jvm/java-8-openjdk-amd64/jre defined at /home/theia/.bloop/bloop.json
2023.06.07 03:15:56 INFO tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/project/Test/.metals/bsp.trace.json or /home/theia/.cache/metals/bsp.trace.json
2023.06.07 03:16:16 ERROR Timeout waiting for 'build/initialize' response
2023.06.07 03:16:16 WARN Retrying connection to the build server Bloop
2023.06.07 03:16:16 INFO Bloop uses /usr/lib/jvm/java-8-openjdk-amd64/jre defined at /home/theia/.bloop/bloop.json
2023.06.07 03:16:16 INFO tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/project/Test/.metals/bsp.trace.json or /home/theia/.cache/metals/bsp.trace.json
2023.06.07 03:16:36 ERROR Timeout waiting for 'build/initialize' response
2023.06.07 03:16:36 ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.TimeoutException
at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:530)
at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:439)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

2023.06.07 03:16:36 WARN no build target for: /home/project/temp/src/main/java/com/test/Test.scala

**Comment by tgodzik** [comment]
`Timeout occured during get request at https://api.github.com/repos/scalameta/metals/releases/tags/v0.11.12`

Looks like there is a very limited internet access here, which is why the build import might have failed and Bloop server is not being downloaded.

**Comment by passion123** [comment]
It‘s OK after 3 days without any action，perhaps the server net cause the issue.Thx all you for support

**Comment by tgodzik** [comment]
Let us know if you find out the reason behind this!

**Comment by passion123** [comment]
> Let us know if you find out the reason behind this!

Not exactly. I guess it caused by some dependencies missed with the bloop plugin
