### ISSUE TITLE
No `case` completion offered in specific situation

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#5339]
### Describe the bug

When trying to complete `case` in a very specific piece of code where I'd expect to be able to get a `case` completion, I don't get one. You can reproduce this by trying to completion `case` in this snippet of code:

https://github.com/scalameta/metals/blob/8e1ae555ece337466dd59b3f6267d1c013f10bf3/metals/src/main/scala/scala/meta/internal/metals/codeactions/ActionableDiagnostic.scala#L40-L43

Trying to complete `case` there doesn't give you `case` as a completion option. I'm assuming this happens in this situation because it has no clue what the actual `case` value would be, but I believe we should also just complete `case` here in then?

### Expected behavior

I'd expect `case` as a completion option.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.12+111-b6724aa5-SNAPSHOT

### Extra context or search terms

This a follow-up to https://github.com/scalameta/metals/pull/5336.

**Comment by jkciesluk** [comment]
Right, it's because this is not a sealed trait, so we can't generate cases automatically, I agree we should show `case` 
 keyword completion there. Do you think we should also show it even if there are cases available?

**Comment by ckipp01** [comment]
> Right, it's because this is not a sealed trait, so we can't generate cases automatically, I agree we should show `case` keyword completion there. Do you think we should also show it even if there are cases available?

Yea I went back and forth. I think yea, we probably should. In this scenario having a `case` is valid there, so ideally we'd do a keyword completion and offer `case`.
