### ISSUE TITLE
Sudden Metals server crash (Code: -32097) on JVM 11.

### ISSUE THREAD

**Issue by daymo** [scalameta/metals#5356]
### Describe the bug

After using `run` and `debug` in VS Code for a while the Metals server suddenly crashes. It won't restart and VS code needs to be restarted to work around it. It might be related to `org.scalafmt.util.TreeOps`.

Java version:
11.0.19

Scala version:
3.3.0

# Metals output
```bash
2023.06.20 11:44:26 INFO  time: compiled jvm in 0.62s
[Error - 11:44:30 AM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 11:44:30 AM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 11:44:30 AM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 11:44:31 AM] Connection to server got closed. Server will not be restarted.
[Error - 11:44:31 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:44:31 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:44:31 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:44:31 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```  

The crash log can be found here.
https://pastebin.com/rnLsZ8nj

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

**Comment by tgodzik** [comment]
Thanks for reporting! Could you attach the logs here? I can find anything under the link you provided.

**Comment by daymo** [comment]
Sure, here is the missing log...

```bash
2023.06.20 11:43:51 INFO  time: compiled jvm in 0.6s[0m
2023.06.20 11:44:26 INFO  compiling jvm (1 scala source)[0m
2023.06.20 11:44:26 INFO  time: compiled jvm in 0.62s[0m
Jun 20, 2023 11:44:28 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: NoDenotation.owner
java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2576)
	at scala.meta.internal.pc.MetalsInteractive$.enclosingSymbolsWithExpressionType(MetalsInteractive.scala:261)
	at scala.meta.internal.pc.HoverProvider$.hover(HoverProvider.scala:98)

2023.06.20 11:44:30 INFO  Shutting down server[0m
2023.06.20 11:44:30 INFO  shutting down Metals[0m
``

**Comment by ckipp01** [comment]
@daymo this should hopefully be addressed via #5360. When CI finishes and this produces a snapshot are you willing to give it a try to see if you still see any errors in your logs?

**Comment by daymo** [comment]
@ckipp01 Sure thing.

**Comment by tgodzik** [comment]
Did you manage to reproduce the issue? The newest snapshot version is `0.11.12+161-977d53e3-SNAPSHOT`

**Comment by daymo** [comment]
@tgodzik Here is what I did. I switched `Scala (Metals)` VS Code extension to `Pre-release v1.23.6` and it say it uses `Metals 0.11.12`. I would've expected to see some SNAPSHOT label on it but there isn't any. How can I make sure I'm using `0.11.12+161-977d53e3-SNAPSHOT`? With the current Pre-release version of Scala metals I haven't seen the build server crash yet but it was hard to reproduce. I'm trying... In case I'm doing something wrong here please tell me how to install and use the latest `SNAPSHOT` version.

**Comment by tgodzik** [comment]
You can change the version in the VS Code settings, just search for `metals.serverVersion`. If you have a prerelease version it should suggest the update automatically.

**Comment by daymo** [comment]
@tgodzik I needed to explicitly set the `Metals: Server Version` to the SNAPSHOT version and then it prompted me to reload the VS Code window.  But I have it now and will test it.

**Comment by daymo** [comment]
@tgodzik Tested it for two days now and I didn't see the crash again. I think it is fixed. Thank you. 

PS: I got automatically prompted for the new SNAPSHOT version. It asked me to to update. Nice.

**Comment by tgodzik** [comment]
Great to hear that!
