### ISSUE TITLE
[metals][VisualStudioCode] Unable to create scala project: Project creation template is not visible  

### ISSUE THREAD

**Issue by raiajithkumarr** [scalameta/metals#5357]
### Describe the bug

Hi Team,
Recently I installed metals from visual studio code extension.
Please see below screen shot related to it.

![image](https://github.com/scalameta/metals/assets/22548964/fec75532-93bc-43d2-89cb-7727d20fe60b)

### Expected behavior

It should show Scala project creation template under packages.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.23.5

**Comment by raiajithkumarr** [comment]
I got reason after installing the metals extension and after reloading vs code we need to create empty folder or open any folder where we want to create scala project. 
then only we will be able to see create project option

**Comment by tgodzik** [comment]
Yes, that's the current limitation, we would need to make metals also work without any directory or use a temporary one.

Connected to https://github.com/scalameta/metals-vscode/issues/357
