### ISSUE TITLE
Incorrect text edit for Scala3 trait member completions

### ISSUE THREAD

**Issue by rochala** [scalameta/metals#5361]
### Describe the bug

```scala
trait Foo {
  def foo: String
}

object Bar extends Foo {
  def@@
}
```

Completions for trait members when they are triggered on `def` are not working correctly.
The returned text edit is wrong. It is only present in Scala 3.
It works correctly if we get the completion from the definition name e.g.
```scala
trait Foo {
  def foo: String
}

object Bar extends Foo {
  def fo@@
}
```

At first I thought this is the issue with the IDE, but it seems that returned JSON contains wrong lines.

### Expected behavior

```scala
trait Foo {
  def foo: String
}

object Bar extends Foo {
  defdef foo: String = ???
}
```

this is the response from the server:
```json
[Trace - 06:32:41 PM] Sending response 'completionItem/resolve - (139)'. Processing request took 7ms
Result: {
  "label": "def foo: String",
  "kind": 2,
  "tags": [],
  "detail": ": String",
  "documentation": {
    "kind": "markdown",
    "value": ""
  },
  "sortText": "00000",
  "filterText": "def foo: String",
  "insertTextFormat": 2,
  "textEdit": {
    "range": {
      "start": {
        "line": 4,
        "character": 19
      },
      "end": {
        "line": 5,
        "character": 5
      }
    },
    "newText": "def foo: String \u003d ${0:???}"
  },
  "additionalTextEdits": [],
  "data": {
    "kind": 1,
    "target": "file:/Users/jrochala/Projects/scala-cli-playground/.scala-build/?id\u003dproject_bd2c96d2de",
    "symbol": "_empty_/Foo#foo()."
  }
}

```

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.12

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like `filterText` is wrong here, right?

**Comment by rochala** [comment]
Text edit starts on the wrong line I suppose:
```
  "textEdit": {
    "range": {
      "start": {
        "line": 4,
        "character": 19
      },
```

**Comment by tgodzik** [comment]
Hmm.... might be. I also checked in VS Code and it seems this is filtered out due to filter text.

**Comment by rochala** [comment]
Yeah, it completely depends on how IDE implements how completions are accepted. I can either use filter string or use text edit.
