### ISSUE TITLE
Metals warning about "some directories cannot be formatted" ignores project.layout

### ISSUE THREAD

**Issue by mdedetrich** [scalameta/metals#5363]
### Describe the bug

When I try to import the following project https://github.com/mdedetrich/incubator-pekko with this [`.scalafmt.conf`](https://github.com/mdedetrich/incubator-pekko/blob/main/.scalafmt.conf) file I get the following warning message

![image](https://github.com/scalameta/metals/assets/2337269/24d3039e-bfa1-445c-81ad-e01e9af12cb8)

### Expected behavior

Since I am using [`project.layout = StandardConvention`](https://github.com/apache/incubator-pekko/blob/45e3da0160b94ed127ce1e2cd09c5869118011dc/.scalafmt.conf#L77) this warning shouldn't need to appear since that configuration in scalafmt automatically applies the correct dialect depending on the folder structure, i.e. if you have sources in a `scala-3` folder then it will apply the scala 3 `dialect` to all sources in that folder (see https://scalameta.org/scalafmt/docs/configuration.html#projectlayout)

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.23.0

**Comment by tgodzik** [comment]
Thanks for reporting! We should for sure exclude it.
