### ISSUE TITLE
Broken connection to build server after sleeping in macOS

### ISSUE THREAD

**Issue by jvican** [scalameta/metals#537]
**Describe the bug**

**To Reproduce**
1. Work on a project for a few minutes.
2. Close the lid of your laptop.
3. Open it up and introduce a compilation error in VS Code
4. Metals does not send compilation requests (checked in the logs), possibly because of a broken socket connection to the build server

**Expected behavior**

Metals shows the compilation error correctly even after suspending/sleeping the computer. If the connection is broken, an automatic reconnection should happen.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.4.4+19-4724f2ae-SNAPSHOT

**Comment by mudsam** [comment]
Thanks! Are you using embedded or installed bloop? Does it throw exceptions or is it just silent?

**Comment by jvican** [comment]
Installed bloop, the build server is already running in the machine. It's just silent, no exception are logged.

**Comment by mudsam** [comment]
__

> Installed bloop, the build server is already running in the machine. It's just silent, no exceptions are logged.

If you know, which connectivity type are you using for bsp? TCP or Unix domain socket?

**Comment by jvican** [comment]
Bloop supports both but if I'm not mistaken the default on macOS is unix local sockets.

**Comment by mudsam** [comment]
@jvican Could you check if this is still an issue after PR #566? I was unable to reproduce the issue.

**Comment by jvican** [comment]
I've reproduced sometimes but haven't seen it lately, let's be optimistic and assume it doesn't happen for now, I'll reopen if it happens again.
