### ISSUE TITLE
Hovering over symbol doesn't always work

### ISSUE THREAD

**Issue by Arthurm1** [scalameta/metals#5374]
### Describe the bug

Hovering over methods doesn't always bring back docs due to parent docs sometimes not being checked.

Create a file with...
```scala
  val foo = new java.util.ArrayList[Int]()
```

Hover over `ArrayList`.  It correctly returns the docs.

Now add `sort` to file...
```scala
  val foo = new java.util.ArrayList[Int]()
  foo.sort(null)
```

Hover over `sort`.  No docs.

When you hover over `ArrayList`, `DocStrings` indexes not just the constructor symbol but the entire class.  So `java.util.ArrayList#sort` is added to the cache but it's added with no docs as the docs are in the parent method `java.util.List#sort`.

Then when hovering over `sort`, the docs are returned from the cache and they are empty and the parents then aren't checked.

I was thinking of changing this but I wasn't sure about performance here.  Could the parents be checked everytime the docs are empty or is that slow and an additional cache would be needed?

### Expected behavior

Docs of parent method would be shown

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

**Comment by tgodzik** [comment]
Thanks for reporting!

> I was thinking of changing this but I wasn't sure about performance here. Could the parents be checked everytime the docs are empty or is that slow and an additional cache would be needed?

This should be perfectly fine for hover and in most places we use docs, since we usually do it lazily. I thought this is done currently, but maybe I forgot about an edge case.
