### ISSUE TITLE
Test runner doesn't work with backticked JUnit test cases

### ISSUE THREAD

**Issue by rochala** [scalameta/metals#5378]
### Describe the bug

```scala
//> using test.dep com.github.sbt:junit-interface:0.13.3

import org.junit.Test

class Tests {
  @Test
  def test: Unit = {
    junit.framework.Assert.assertEquals(1, 2)
  }

  @Test
  def `test-backticked`: Unit = {
    junit.framework.Assert.assertEquals(1, 2)
  }

}
```
Running the first test case via code lens works only on non-backticked test cases.
The output:
```
Test Tests.test ignored
Test Tests.test$minusbackticked ignored
Execution took 0ms
2 tests, 2 ignored
All tests in Tests passed

===============================================
Total duration: 0ms
All 1 test suites passed.
===============================================
```

### Expected behavior

It should work on backticked test cases for both running and debugging.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

metals 0.11.12+134-80315695-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! I wonder if the change to $minus is something common to all the frameworks or just junit :thinking:
