### ISSUE TITLE
Implement all members in the presence of an end marker 

### ISSUE THREAD

**Issue by Quafadas** [scalameta/metals#5408]
### Describe the bug

Before
![Screenshot 2023-07-05 at 13 22 21](https://github.com/scalameta/metals/assets/24899792/9fd060e2-be73-46d7-ac6c-db6a3788cc78)

After
![image](https://github.com/scalameta/metals/assets/24899792/29f59ec2-3a87-4074-93e8-caa3d17cd5fb)

### Expected behavior

Implementation is before end marker

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v.0.11.12

**Comment by tgodzik** [comment]
Thanks for finding this one!
