### ISSUE TITLE
No results from textDocument/documentSymbol when using scala-cli

### ISSUE THREAD

**Issue by zhranklin** [scalameta/metals#5411]
### Describe the bug

I'm using nvim-metals and a plugin named symbols-outline, which shows the structure of the code and dependents on 'textDocument/documentSymbol' data from lsp.

But now there are no result from textDocument/documentSymbol when editing scala-cli worksheet. lsp_document_symbols in Telescope also return nothing. It works fine in structured project other than worksheet.

### Expected behavior

It should list the symbols when calling lsp_document_symbols with Telescope

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.12

### Extra context or search terms

textDocument/documentSymbol

documentSymbol

**Comment by zhranklin** [comment]
Oh sorry I mean scala-cli script. filename: `t2.sc`, file:

```scala
#!/usr/bin/env -S scala-cli shebang
//> using dep "com.lihaoyi::os-lib:0.8.0"
//> using scala 2.13.10
def main(i: Int, s: String) = {
  s"Hello! ${s * i} ${os.pwd.last}."
}
def aaa(t: String) = a
class A {
  def b: String
}
```

It's not urgent for me now, because I've found another plugin(aerial.nvim) to show the structure properly, which get data from treesitter besides the lsp. You can solve this problem as you wish! Thanks!

**Comment by tgodzik** [comment]
Thanks! I can reproduce it with the file you attached.
