### ISSUE TITLE
Reuse scala presentation module from the compiler

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#5427]
### Describe the bug

With https://github.com/scalameta/metals/pull/5423 we started using the presentation compiler module (migrated from metals) alongside the compiler. However, that is only for the nightlies, next step is to change mtags in Metals into a wrapper module around the presentation compiler. This will allow us to add new features to the presentation compiler interface and only then migrate them to the actual compiler, which lessens the burden for outside contributors and lets us experiment more easily.

Because of recent changes in the compiler, the nightlies are no longer compiling for Metals, but since we don't need them that urgently (and they are supported), we can disable publishing and testing them for the time being. 

As a part of this feature we will add back testing on the nightlies, so that we can easily catch any incompatibilities (there shouldn't be too many of them)

### Extra context or search terms

presentation compiler scala 3

**Comment by tgodzik** [comment]
CC @rochala

**Comment by rochala** [comment]
I think we can close this.

**Comment by tgodzik** [comment]
Thanks for letting know!
