### ISSUE TITLE
Metals displays the wrong type.

### ISSUE THREAD

**Issue by phrmoy** [scalameta/metals#5461]
### Describe the bug

I have turned on the types to be displayed explicitly without having to hover over the variable. However, I am encountering cases where the wrong type is being shown. In the example below, the type displayed over hovering (the correct type) is different than the type being shown explicitly.

<img width="638" alt="image" src="https://github.com/scalameta/metals/assets/3697931/fb8e259b-6e9b-4612-91b4-42467a7038bb">

### Expected behavior

Expected both types displayed to be the same correct type.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

**Comment by tgodzik** [comment]
Does the project compile though? Were the types not properly updated or were they always wrong?

**Comment by phrmoy** [comment]
The code at the time of the screenshot was not compiling, exactly because of this type mismatch. And unfortunately for me, I had to go chase down this definition because the code was not breaking exactly there, not even on the same source file. So, the compilation was running, and the staleness of the wrongly shown type remained.

**Comment by tgodzik** [comment]
Unfortunately that's currently expected since the feature relies on compiled artifacts, which could be changed in the future

**Comment by kitbellew** [comment]
if it doesn't compile, perhaps not show type at all? or indicate lack of confidence with some markings (`: ?Type?`).

**Comment by tgodzik** [comment]
We are working on switching some of the functionality to the presentation compiler, so it should show the most up to date information as it's invoked on the current state of the code.
