### ISSUE TITLE
Documentation Popup is empty for symbol named methods

### ISSUE THREAD

**Issue by walesho** [scalameta/metals#5469]
### Describe the bug

Documentation popup comes up empty for "symbol named methods". 

![image](https://github.com/scalameta/metals/assets/92475279/44984084-cdd9-49b8-97ba-fabb83c3dfc1)

### Expected behavior

Documentation should be displayed as shown in the image below. 

<img width="808" alt="image" src="https://github.com/scalameta/metals/assets/92475279/e3c14ed5-988e-45ff-aaa7-5b96e0ad2644">

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.0.0

**Comment by tgodzik** [comment]
Thanks for reporting! I can reproduce this and it seems there are proper docs to show.
