### ISSUE TITLE
Member completions are not backtick aware

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#547]
**Describe the bug**
Some members require backticks when accessed. Member completion should insert the backticks when completing such members, but this is currently not happening.

**To Reproduce**

```scala
case class Backticks(`type`: String)
val b = Backticks("tpe")
b.ty@@
```

Result:

```scala
case class Backticks(`type`: String)
val b = Backticks("tpe")
b.type // invalid code
```

**Expected behavior**

```scala
case class Backticks(`type`: String)
val b = Backticks("tpe")
b.`type`
```

**Screenshots**
![image](https://user-images.githubusercontent.com/691940/54084418-993e5100-4330-11e9-81b5-92cba797f078.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.5.0-SNAPSHOT

**Search terms**
backtick, reserved identifiers, completions

**Comment by olafurpg** [comment]
Related https://github.com/scalameta/metals/issues/545. We can keep the label unchanged but customize the `textEdit` to insert the properly backticked code.

**Comment by gabro** [comment]
Yep, I agree the label should stay without backticks.

**Comment by gabro** [comment]
Another case to keep in mind: spaces in between backticks.

![image](https://user-images.githubusercontent.com/691940/54086772-c6006180-434c-11e9-99db-c384418d2ad9.png)
