### ISSUE TITLE
Implement textDocument/documentHighlight

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#549]
Spec: https://microsoft.github.io/language-server-protocol/specification#textDocument_documentHighlight

<img width="755" alt="Screenshot 2019-03-10 at 12 47 25" src="https://user-images.githubusercontent.com/1408093/54084576-ad834d80-4332-11e9-8b1b-815d355d10bd.png">

We already have the available data in `ReferencesProvider` so I estimate this requires not too much effort.

**Comment by olafurpg** [comment]
@tgodzik is working on this feature in https://github.com/tgodzik/metals/pull/1 🎉

**Comment by tgodzik** [comment]
Opened a PR to metals repo in https://github.com/scalameta/metals/pull/621

**Comment by olafurpg** [comment]
Fixed in #621 by @tgodzik
