### ISSUE TITLE
Metals is not properly escaping spaces in directory names in config

### ISSUE THREAD

**Issue by peteslater** [scalameta/metals#5507]
### Describe the bug

When working on Scala projects I find that Metals, when used in VS Code, does not correctly escape directory names with spaces in.

This means that some compiler errors do not show in VS Code. Errors in the main codebase seem to work fine but errors in test code do not display at all.

When running Metals Doctor and clicking through to a test directory in a project, the config is correct in places and incorrect in others.

```
Base Directory
  file:///home/me/My Directory/some-project/
```

```
Classes Directory
  file:///home/me/My%20Directory/some-project/.bloop/some-project/bloop-bsp-clients-classes/test-classes-Metals-FD61ptECRdCx8YvqDoeqQw==/
```

If I remove the space in the directory name, and re-import the project using Metals in VSCode, I can see compilation errors.

So the issue is the space in the directory name.

I find it odd that the config escapes the directory name in some places but not in others.

### Expected behavior

I expect that Metals can handle spaces in directory names correctly.
This would mean that compilation errors can be displayed in a VS Code editor.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.0.0

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like an issue when generating Bloop config :thinking: I will try and reproduce it.

**Comment by tgodzik** [comment]
I created an sbt project in a directory with space, it all seems to work ok. Are you still able to reproduce, could you show us a minimal project this fails on?

Sorry for the long wait.
