### ISSUE TITLE
cannot bootstrap metals 1.0.0

### ISSUE THREAD

**Issue by Sciss** [scalameta/metals#5525]
### Describe the bug

My old code, I'm trying to actualise

     coursier bootstrap org.scalameta:metals_2.13:0.10.3 -o metals -f

according to https://scalameta.org/metals/docs/editors/vim#files-and-directories-to-include-in-your-gitignore

     coursier bootstrap org.scalameta:metals_2.13:1.0.0 -o metals -f

### Expected behavior

should install

### Operating system

Linux

### Editor/Extension

None

### Version of Metals

v1.0.0

### Extra context or search terms

```
$ coursier bootstrap org.scalameta:metals_2.12:1.0.0 -o metals -f
Resolution error: Error downloading org.scalameta:metals_2.12:1.0.0
  not found: /home/hhrutz/.ivy2/local/org.scalameta/metals_2.12/1.0.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalameta/metals_2.12/1.0.0/metals_2.12-1.0.0.pom
```

Last version I see on maven central is 0.9.9 ?

**Comment by tgodzik** [comment]
Thanks for reporting! You need to use the `_2.13` suffix as suggested in the docs.

**Comment by Sciss** [comment]
apologies, now I see it was moved from Scala 2.12 to 2.13
