### ISSUE TITLE
Don't load presentation compiler until build target has compiled successfully

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#553]
Features like completions require the build to compile successfully at least once in order to include results for symbols in the workspace. Currently, we don't check this requirement before loading the presentation compiler leading to "no completion suggestion" responses when the user hasn't compiled the project, which can easily happen during the first build import. We should report a more helpful message in this case.

**Comment by gabro** [comment]
Ideally, this should also use dynamic registration for editors that support it.
It would allow the editor to skip sending the completion request entirely when the server is not ready yet

**Comment by olafurpg** [comment]
This hasn't been an issue in my experience since the compilation progress is indicated in the status bar and you can still sometimes get useful completion results with a partial classpath. Closing as wontfix.

**Comment by jvican** [comment]
> you can still sometimes get useful completion results with a partial classpath
  
In my experience, the presentation compiler works well with projects that have not yet compiled successfully but that have at least been compiled once (almost all of the cases) so :+1: on closing the ticket
