### ISSUE TITLE
Zinc repository does not work with Metals when using default SBT export to Bloop

### ISSUE THREAD

**Issue by jackkoenig** [scalameta/metals#5539]
### Describe the bug

1. Clone zinc
```bash
git clone https://github.com/sbt/zinc
cd zinc
# Commit probably doesn't matter but at time of filing issue it was
# git checkout ae52a6839e7fb96f033d4ab9962c0dfffe9628ec
```
2. Open project in VSCode
3. Click "Import Project"
4. Open a file like `zinc/src/main/scala/sbt/internal/inc/IncrementalCompilerImpl.scala`

Wait and then you will see `Problems` show up:
<img width="561" alt="Screen Shot 2023-08-09 at 9 26 16 PM" src="https://github.com/scalameta/metals/assets/8584418/71a9442a-43ee-4dae-b377-c7fe8a7fd70a">

Switching to sbt-bsp works quite well so this is presumably just an issue in the Bloop export.

### Expected behavior

I would expect Metals to support the project out-of-the box. Switching the default to sbt-bsp might be a sufficient solution.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.24.0

### Extra context or search terms

Probably not relevant but my workspace is running on a Linux server and I am using VSCode over SSH from my MacOS laptop.

**Comment by tgodzik** [comment]
Looking at zinc repo again it seems that there is no explicit information that zincCore depends on zincPersistCore. I don't even know this could be fix.

I think the only sensible solution here is to use sbt BSP :/

Unless anyone can tell me how to get the relation between those project, the only dependency I can see is:
`Compile / packageBin := (zincPersistCore / Compile / assembly).value,` but I don't understand how we could handle it.

Closing this as I don't think we will be able to make it work unless some sbt guru shows up.

**Comment by jackkoenig** [comment]
This all makes sense, thanks for looking into it!
