### ISSUE TITLE
Semantic tokens misaligned on a build.sbt file

### ISSUE THREAD

**Issue by keynmol** [scalameta/metals#5553]
### Describe the bug

I've not managed to trivially reproduce it, but the source where it happens is here: https://github.com/indoorvivants/sn-bindgen-web/blob/main/build.sbt#L223

<img width="757" alt="CleanShot 2023-08-15 at 14 19 14@2x" src="https://github.com/scalameta/metals/assets/1052965/3c4caf23-f39c-4737-91a7-fdbfc8fab0b6">

### Expected behavior

Tokens are positioned correctly

### Operating system

None

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.0.0+59-0074f74d-SNAPSHOT

### Extra context or search terms

semantic tokens, build.sbt, misalignment, positions

**Comment by jkciesluk** [comment]
Thanks for reporting!
it looks like there is an issue with `s-strings` with triple quote, but only if the closing quote is at the start of the line
```scala
s"""
this breaks
"""
val x = 1
```

```scala
s"""
this doesn't
 """
val x = 1
```
