### ISSUE TITLE
Broken semantic tokens

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#5555]
### Describe the bug

I'm not sure exactly what the actual issue is here, but looking at a code snippet in an open source project you can see that the semantic highlighting sort of just assigns orange to everything when I don't think it should. It also seems to highlight some works in the comments, which it also shouldn't.

To reproduce this I'm using the [Zinc codebase](https://github.com/sbt/zinc) and opening [IncrementalCompilerImp.scala](https://github.com/sbt/zinc/blob/develop/zinc/src/main/scala/sbt/internal/inc/IncrementalCompilerImpl.scala). I'm using sbt as my build server and the project is fully compiling. Normally just using treesitter I see:

 
<img width="594" alt="Screenshot 2023-08-16 at 10 10 05" src="https://github.com/scalameta/metals/assets/13974112/a5e8f05d-ed14-440b-acd6-920bd6713e9d">

With semantic highlighting from Metals I see:

<img width="594" alt="Screenshot 2023-08-16 at 10 07 30" src="https://github.com/scalameta/metals/assets/13974112/1f82abad-93d5-404e-ac9f-4ce9cfc0c460">

In this example notice that `logger` and `in` are highlighted in the comments. Also there are a bunch of things that are orange that I wouldn't expect.

### Expected behavior

I'd expect Metals not to highlight things like this in the comment unless they are code blocks and I'd expect the highlighting to more or less match what I had before and be more accurate, not less than treesitter.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.0.0+59-0074f74d-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting!

> semantic highlighting sort of just assigns orange to everything when I don't think it should. 

orange in your case is probably readonly vals, right? I think the PC Collector might be having a problem with that file and not returning all semantic info. We should either fix it or try to not return semantic tokens in those cases.

> It also seems to highlight some works in the comments, which it also shouldn't.

We do highlight scaladoc in the comments, that I think is ok.

**Comment by ckipp01** [comment]
> We do highlight scaladoc in the comments, that I think is ok.

Ahhh so it's just highlighting the name of the args, duh. Gotcha.

**Comment by jkciesluk** [comment]
> > We do highlight scaladoc in the comments, that I think is ok.
> 
> Ahhh so it's just highlighting the name of the args, duh. Gotcha.

It should also highlight `@param` and `@return` as keywords, it's weird it doesn't.
Also, `import` has different colour than other keywords, which is weird because we don't specify it in semantic tokens. 
I will take a closer look at this

**Comment by jkciesluk** [comment]
I checked it and it doesn't work for me at first too, but after doing `import build` manually, everything started working as it should:
![image](https://github.com/scalameta/metals/assets/72950514/28ce4acd-32a8-45f4-bc97-ba68fb4be509)

**Comment by tgodzik** [comment]
@ckipp01 could this be due to https://github.com/scalameta/metals/issues/5539 ? If the code doesn't fully compile, then semantic highlight might indeed show wrong things, which is expected and should improve with early compilation being done for Scala 3

**Comment by ckipp01** [comment]
> @ckipp01 could this be due to #5539 ? If the code doesn't fully compile, then semantic highlight might indeed show wrong things, which is expected and should improve with early compilation being done for Scala 3

That was my original thought, but when using sbt as your build server it does fully compile. I was just playing around with this based off what @jkciesluk was able to figure out and I think what is happening is that when you first open the project and it's not fully imported via sbt it gives you the highlighting I posted, but then when it's fully imported then everything seems alright. I guess this sort of begs the question of should it really send any token before it's fully imported?

**Comment by jkciesluk** [comment]
> I guess this sort of begs the question of should it really send any token before it's fully imported?
I thinks it's reasonable not to send anything if the build is not imported. Or maybe we should not send only if build import is in progress?

**Comment by tgodzik** [comment]
We could wait for the build server promise or potentially figure out if there is too many error types and in that case fail quicker in the PC Collector?

**Comment by iusildra** [comment]
I think I can reuse this issue, otherwise I'll open another one. When dealing with extension method, it correctly highlights the method call when the `extension` is top-level, but if it is nested in the companion object then it appears as a field
![image](https://github.com/scalameta/metals/assets/64749208/09e66275-f853-4f77-989f-a1130ac3e4f9)

**Comment by tgodzik** [comment]
Thanks for finding this @iusildra ! I think this warrants another issue, since it's an actual error we can fix while the issue at hand is that we should refrain from showing semantic tokens if something is not yet working on the classpath

**Comment by jkciesluk** [comment]
fixed by https://github.com/scalameta/metals/pull/5985

**Comment by jjbavdb** [comment]
Managed to fix this with a workaround, which was intermittently glitching my Emacs Eglot + Metals.
Now the language server works reliably!!

```emacs-lisp
  (defun my/eglot-disable-metals-semantic-refresh (orig-fn server)
    (let* ((caps (funcall orig-fn server))
           (workspace (plist-get caps :workspace))
           (tokens (plist-get workspace :semanticTokens)))
      (when tokens
        (plist-put tokens :refreshSupport :json-false))
      caps))

  (advice-add 'eglot-client-capabilities :around #'my/eglot-disable-metals-semantic-refresh)
```
