### ISSUE TITLE
Bad indent of import for autocompleted ident (if there's already an import)

### ISSUE THREAD

**Issue by som-snytt** [scalameta/metals#5567]
### Describe the bug

When I click on completion in context window, an import is added with incorrect indentation if there is already an import at that location.

via `sbt-scoverage-samples`:
```
package subpackage2.validators {

  import subpackage1.exceptions.OrderException
import scala.annotation.unused

  class OrderValidator(@unused name: String) {
    def validate = throw new OrderException("trebuchet explosion")
  }

}
```
Self-contained:
```
package p {

  import scala.collection.mutable
import scala.annotation.unused

  class C {
    def f(@unused x: String) = mutable.Map.empty[Int, Int]
  }
}
```
If there is no existing import, then the indent is correct.

### Expected behavior

Correct indentation, such that it compiles under Scala 3. Cross-compilation was how I noticed the problem.

In `sbt-scoverage-samples`, I made 2.13.11 the "primary" Scala version in order to use Scala 2 warnings.

I did not try the edit under Scala 3, or with header-style `package` statement.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.0.0

### Extra context or search terms

Using WSL 2 Ubuntu 20.

**Comment by kasiaMarek** [comment]
Thanks for the report. Seems we just forgot to skip empty lines when calculating the indentation for auto position. Fix is on the way 🚑
