### ISSUE TITLE
[Scala3] No workspace completions after `derives`

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#5619]
### Describe the bug

It seems that Metals returns LSP completion list with `isComplete: true` in case if completions are called right after derives with a single char 
```scala
//> using scala 3
//> using using lib "io.circe::circe-core::0.14.16"

// continue to type `Decoder
case class Abc(i: Int) derives D@@ // < `+D` no completions there will be no recomputed completions 
case class Abc2(i: Int) derives De@ // <- `+e` - same - no completions
case class Abc3(i: Int) derives Dec@ // <- `+c` - completions appears - `io.circe.Decoder`
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.0.1

**Comment by kasiaMarek** [comment]
It's that the desired behaviour? We only start showing workspace completions when at least three chars are typed. Or am I missing something?

**Comment by dos65** [comment]
@kasiaMarek 
> It's that the desired behaviour? 
I'm not sure but fells like it sin't general

> We only start showing workspace completions when at least three chars are typed. Or am I missing something?

Yep, we do search after having at least `three chars`. 
However, if there are less than tree chars the returned lsp result should have `isIncomplete: true` value to allow future `complete` request when you will add more chars - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion

So, it feels like in described case Metals returns `isIncompelte: false`

**Comment by kasiaMarek** [comment]
I can't really reproduce this example. For me it returns no completions under 3 chars but as soon as I type the third one compilations appear and in the trace, the lsp response looks as it should:
```
Sending response 'textDocument/completion - (144)'. Processing request took 103ms
Result: {
  "isIncomplete": true,
  "items": []
}
```

**Comment by kasiaMarek** [comment]
Sorry, @dos65, I feel like I still don't see what is the problem. Looking at lsp log, Metals is returning `"isIncomplete": true` after the first, the second, and even third letter is typed for the example you've provided.

**Comment by tgodzik** [comment]
This is back to https://github.com/microsoft/vscode/issues/155738 we had a workaround, but that proved to not work 100%. We might want to try and modify it on the VS Code side

**Comment by tgodzik** [comment]
Alternatively, we should show completions even if less than 3 letters are typed if there is nothing else in scope.

**Comment by tgodzik** [comment]
Another option is to always send at least a certain amount of completions, limit to a max of 100 etc. if we have a short prefix.

**Comment by filipwiech** [comment]
@tgodzik If that helps, then as far as I know that's roughly what for example Rust Analyzer LSP is doing. For short completions with less than 3 typed characters simple prefix match with limited number of results is used, whereas for 3 and more typed characters a standard fuzzy matching is employed. :+1:

**Comment by tgodzik** [comment]
> @tgodzik If that helps, then as far as I know that's roughly what for example Rust Analyzer LSP is doing. For short completions with less than 3 typed characters simple prefix match with limited number of results is used, whereas for 3 and more typed characters a standard fuzzy matching is employed. 👍

I got the idea from one of the microsoft issues, so there might be some Analyzer contributors there :sweat_smile:
