### ISSUE TITLE
Inconsistent syntax highlighting with extension method

### ISSUE THREAD

**Issue by iusildra** [scalameta/metals#5630]
### Describe the bug

Extension methods from top-level `extension` are correctly highlighted, but if it is nested in the companion object then it appears as a field
![image](https://github.com/scalameta/metals/assets/64749208/72c7cc8d-6014-4819-8663-210a06cb7577)

### Expected behavior

Extension method defined in companion object should appear as a method

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.0.1+22-acf9aec2-SNAPSHOT

### Extra context or search terms

Semantic highlighting

**Comment by kasiaMarek** [comment]
Thanks for the report. In the first example also highlight and go to definition don't work.

**Comment by iusildra** [comment]
Is there a link between metals presentation compiler's and dotty's ? It seems it's the same code but I do not see any submodule

**Comment by kasiaMarek** [comment]
The presentation compiler is getting moved from metals to dotty. You can read more [here]( https://contributors.scala-lang.org/t/stable-presentation-compiler-api/6139). And [here](https://github.com/lampepfl/dotty/pull/17528) is the initial commit that adds pc to dotty. We are currently in this, a bit awkward, transition state, where the presentation compiler is maintained both in dotty and metals. We have to keep both up to date until the release of LTS 3.3.2, and even after that, it seems prudent to provide bug fixes for older versions such as 3.2.2 for a while longer.
