### ISSUE TITLE
Refactor -> Extract class does not extract class level Scaladocs

### ISSUE THREAD

**Issue by davesmith00000** [scalameta/metals#5632]
### Describe the bug

If you use the `Refactor -> Extract class` function to move a class to it's own file, then the extract works correctly, including moving companion objects, but the Scaladocs above the class are left behind.

Example below with screenshots.

Steps to reproduce:

1. Have a scala file with two classes, the second of which isn't named the same as the file.
2. Add Scala docs above the second one.
3. Use refactor -> extract to move it to it's own file.
4. Notice that the Scaladocs remain in the original file.

### Expected behavior

Class level scaladocs should follow the class into the new file.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

0.11.1+74-558d667d-SNAPSHOT

### Extra context or search terms

Class called `IndigoGameMetadata` is in a file called `IndigoOptions` and I want to move it out.
![image](https://github.com/scalameta/metals/assets/908709/b02c47cf-18c8-4217-b4c4-da27d180df45)

So I use refactor:
![image](https://github.com/scalameta/metals/assets/908709/4d207f77-1bb9-45b3-bf20-9f83ee95d4b9)

Which works...
![image](https://github.com/scalameta/metals/assets/908709/2b0c962a-b816-47f2-922b-3911750a88c8)

But my docs didn't survive the journey...
![image](https://github.com/scalameta/metals/assets/908709/8ade72ac-2ed3-4478-aff2-717f54044cde)

**Comment by kasiaMarek** [comment]
Thanks for the report, scaladoc should definitely be moved with the class.
