### ISSUE TITLE
Scaladoc entity links are rendered as plaintext

### ISSUE THREAD

**Issue by jvican** [scalameta/metals#564]
**Describe the bug**
When Scaladoc comments contain `[[foo]]`-like references to methods, the docstring rendering doesn't show them as code, which makes them difficult to parse.

**Expected behavior**
`[[` is rendered as if it was code enclosed in backticks.

**Screenshots**
![2019-03-13 14 55 17](https://user-images.githubusercontent.com/2462974/54284402-2804d500-45a0-11e9-8aea-a8d320fd24bd.jpg)

<img width="723" alt="Screen Shot 2019-03-13 at 2 30 23 PM" src="https://user-images.githubusercontent.com/2462974/54284256-e7a55700-459f-11e9-93fd-2b0800843d8d.png">

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.4.4-92

**Comment by olafurpg** [comment]
Thanks for reporting! Any chance you could take a look @mudsam ?

**Comment by mudsam** [comment]
Will do

**Comment by jvican** [comment]
That's good enough for me, I'd say it even makes more sense to show them as links than code. If they could be both it would be better, but can live with that fix :+1:

**Comment by olafurpg** [comment]
Fixed in #627, thank you @mudsam 🙏
