### ISSUE TITLE
Name conflicts on export

### ISSUE THREAD

**Issue by iusildra** [scalameta/metals#5649]
### Describe the bug

If a class has a field named `X` and an exported method from `X` also named `X`, the compiler fails with naming errors, but it is not shown in metals. Instead, it shows a weird inferred type

```scala
case class A() {
  def a = 42
}

case class B(a: A) {
  export a.*
}

@main def Test = // typed as => Int & A
  val b = B(A())
  b.a
```

The compiler fails with

```
-- [E120] Naming Error: /home/lucasn/Scala/codinGame/src/main/scala/ThereIsNoSpoon/Test.scala:8:11 
8 |  export a.*
  |           ^
  |           Double definition:
  |           val a: ThereIsNoSpoon.A in class B at line 7 and
  |           final def a: Int in class B at line 8
1 error found
Errors encountered during compilation
```

### Expected behavior

Show the error

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.0.1+27-38181619-SNAPSHOT

**Comment by kasiaMarek** [comment]
Thanks, for the report. If I copy the code provided by you, metals shows the error as expected. Though the inferred type is also visible but I wouldn't really treat it as error more as best-effort typing. If you're not getting diagnostics, it may indicate that something got stuck. Are you getting any other errors if you write non-compiling code? Which BSP are you using? Can you see any issues in the metals logs?

**Comment by iusildra** [comment]
Hum, yeah, something probably got stuck at the time because now I can't reproduce it anymore, and I couldn't find anything relevant in the logs :frowning_face:

**Comment by kasiaMarek** [comment]
I'm closing this then. But if you'll find any relevant information about what happened or it keeps happening just open another issue.
