### ISSUE TITLE
Coursier in sbt super-project causes import failure in VSCode

### ISSUE THREAD

**Issue by jodersky** [scalameta/metals#567]
**Description**
If [coursier is enabled in the sbt super project](https://get-coursier.io/docs/sbt-coursier.html#along-other-plugins), importing the base project into VS Code will cause metals to fail.

VS Code output:

>[info] Set current project to coursier-kill-metals (in build file:/home/jodersky/src/coursier-kill-metals/)
[error] Not a valid command: metalsEnable
[error] Not a valid project ID: metalsEnable
[error] Expected ':'
[error] Not a valid key: metalsEnable
[error] metalsEnable
[error]             ^
sbt exit: 1

**Example**
Try cloning and importing the bare-bones project https://github.com/jodersky/coursier-kill-metals

**Comment by olafurpg** [comment]
Thanks for reporting! @alexarchambault do you have an idea what might be going on here? I have experienced the same issue using Metals in the scalameta/metals repo and the same error has been reported here https://github.com/scalameta/mdoc/issues/155#issuecomment-473035374

**Comment by olafurpg** [comment]
FWIW, the sbt-metals plugin is cross-published for sbt 0.13.x and 1.x and the source code is ~100 lines of code in a single file https://github.com/scalameta/metals/blob/master/sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala it brings in the sbt-bloop plugin as a library dependency but we don't explicitly reference any sbt-bloop classes in the sbt-metals implementation.

**Comment by alexarchambault** [comment]
Trying to reproduce that, things have been working fine for me for now…

**Comment by alexarchambault** [comment]
It seems to be a regression since sbt-coursier `1.1.0-M12`, the versions prior to that that I tested seem fine (`1.1.0-M7`, `1.1.0-M11`, …).

**Comment by olafurpg** [comment]
@alexarchambault Thanks for tracking down the root issue! A workaround is to use coursier 1.1.0-M11 until the fix from https://github.com/coursier/sbt-coursier/pull/47 has been released

**Comment by alexarchambault** [comment]
It’s (just) been released, in `1.1.0-M13-2`.

**Comment by jodersky** [comment]
Thanks!

**Comment by ayoub-benali** [comment]
I can confirm that `1.1.0-M13-2` fixes the issue
