### ISSUE TITLE
Can't run test with special characters

### ISSUE THREAD

**Issue by mbovel** [scalameta/metals#5670]
### Describe the bug

```scala
//> using scala 3.3.1
//> using test.dep org.scalameta::munit::1.0.0-M10

class MyTests extends munit.FunSuite:
  test("sum"):
    println("Run test 'sum'")
    assert(2 + 2 == 4)

  test("2 + 2 == 4"):
    println("Run test '2 + 2 == 4'")
    assert(2 + 2 == 4)
```

![image](https://github.com/scalameta/metals/assets/777748/938cc5af-c8d3-4e17-93a8-a79438422d79)

### Expected behavior

Clicking the "Run Test" button of the individual test named `2 + 2 == 4` should run this test and ignore the others. Instead, it ignores all tests.

Note that it works fine with the test named `sum`.

Reproduced in an SBT project and on multiple machines.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.0.1

**Comment by tgodzik** [comment]
Thanks for reporting! It's probably related to the other issue you were dealing with @kasiaMarek ?

**Comment by mbovel** [comment]
Note: no problem from the CLI:

```
➜  ~/metals-tests scala-cli test . --test-only 'MyTests' -- "*sum*"
Run test 'sum'
MyTests:
  + sum 0.012s
➜  ~/metals-tests scala-cli test . --test-only 'MyTests' -- "*4*"  
Run test '2 + 2 == 4'
MyTests:
  + 2 + 2 == 4 0.012s
➜  ~/metals-tests scala-cli test . --test-only 'MyTests' -- "*=*"
Run test '2 + 2 == 4'
MyTests:
  + 2 + 2 == 4 0.011s
➜  ~/metals-tests scala-cli test . --test-only 'MyTests' -- "*+*"
Run test '2 + 2 == 4'
MyTests:
  + 2 + 2 == 4 0.012s
```

**Comment by kasiaMarek** [comment]
> Thanks for reporting! It's probably related to the other issue you were dealing with @kasiaMarek ?

Yeah, it might be. Though the fix was only concerned with junit. I'll take a look.
