### ISSUE TITLE
On large worksheet output, the hover text is formatted wrong

### ISSUE THREAD

**Issue by spamegg1** [scalameta/metals#5679]
### Describe the bug

I was going through the [Scala Toolkit tutorial](https://docs.scala-lang.org/toolkit/os-read-file.html). Here we read a dictionary on Linux systems into a string.

1. Open a worksheet with the Toolkit loaded.
2. Use this code
```scala
val path: os.Path = os.root / "usr" / "share" / "dict" / "words"
val content: String = os.read(path)
```
3. Hover over `content` to see wrong formatting (looks like it is leaking the underlying Markdown):
![hover2](https://github.com/scalameta/metals/assets/4255997/a9f6f726-b77e-4970-8c47-fb57a1b401f9)

### Expected behavior

Should format correctly, like it does any other string.
![correct2](https://github.com/scalameta/metals/assets/4255997/dff0b510-e4eb-4690-8854-2984e501093d)

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.0.1

### Extra context or search terms

hover, text, string, worksheet

**Comment by spamegg1** [comment]
Sure:
```scala
//> using toolkit latest

val path: os.Path = os.root / "usr" / "share" / "dict" / "words"
val content: String = os.read(path)
```

**Comment by kasiaMarek** [comment]
That seems to be a VS Code thing. If the content is too long (about 100000 chars) VS Code trims the content, making the markdown incorrect. We can simply trim the hover message ourselves when it's too long.
