### ISSUE TITLE
"Insert type annotation" does not respect aliased imports

### ISSUE THREAD

**Issue by ghostbuster91** [scalameta/metals#5682]
### Describe the bug

Given following import:
`import cats.parse.{Parser => P}`

and a method:
```scala
def read(txt: String) = {
  P.string("a").parseAll(txt)
}
```
after calling "Insert type annotation" code action on the `read` method the code looks as follows:

```scala
def read(txt: String): Either[Parser.Error, Unit] = {
  P.string("a").parseAll(txt)
}
```
and the code no longer compiles

### Expected behavior

Ideally metals should notice that the `Parser` type has been renamed during the import and adjust code action accordingly.

The expected code should look like:
```scala
def read(txt: String): Either[P.Error, Unit] = {
  P.string("a").parseAll(txt)
}
```

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v1.0.1

### Extra context or search terms

Insert type annotation, code action, aliased import

**Comment by tgodzik** [comment]
Thanks for reporting! What Scala version are you using?

**Comment by ghostbuster91** [comment]
> Thanks for reporting! What Scala version are you using?

3.3.1
