### ISSUE TITLE
imporovement: switch to `workspace/configuration`

### ISSUE THREAD

**Issue by kasiaMarek** [scalameta/metals#5699]
### Problem
It would be useful to have settings per workspace folder (as proven by [this](https://github.com/scalameta/metals-feature-requests/issues/66)).

### Solution
Currently we are using [DidChangeConfiguration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration) to get information about the current user configuration.

We should switch to [`workspace/configuration`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration), which allows for having scopes for settings.

**Comment by tgodzik** [comment]
The only problem I see is that we would send those requests too often since we rely heavily on up to date settings in a lot of places.

**Comment by kasiaMarek** [comment]
Actually, it can be solved differently. We can still subscribe to `DidChangeConfiguration` to know when to ask for changes. That's recommended in the docs to allow the server to cache the settings.
