### ISSUE TITLE
Depdendencies autocompletion for scala cli introduces excessive colon

### ISSUE THREAD

**Issue by Kordyjan** [scalameta/metals#5717]
### Describe the bug

https://github.com/scalameta/metals/assets/11855167/a8e766df-d4de-40cb-9b12-26d27ba9c780

1. Write `//> using lib org.eclipse.jgit:org.eclipse.jgit:`
2. Invoke autocompletion
3. Accept any version number

Metals will put an excessive `:`, making dependency impossible to resolve.

### Expected behavior

There is only one colon between the artifact id and version number.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

 v1.0.1+71-0d2739f6-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! @jkciesluk could you take a look?

**Comment by jkciesluk** [comment]
It looks like https://github.com/scalameta/metals/pull/5373 broke this. Here https://github.com/scalameta/metals/issues/5300 i thought the `::` syntax before version is always valid, but actually it works only if there is also `::` before artifact.
