### ISSUE TITLE
Implement missing members incorrectly renders Tuple1

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#5754]
### Describe the bug

In scala 2.13 PC incorrectly renders Tuple1 at least in `implement members` code action (probably the same should happen in `infer type`)
Example:
```scala
trait Foo[A] {
  def foo(a: A): Int
}

val a = new Foo[Tuple1[Int]] // <- execute `implement members` code actions
// generated code:
val a = new Foo[Tuple1[Int]] {
   def foo(a: (Int,)): Int // <- error `(Int,)` should be written as `Tuple1`
}
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.0.1

**Comment by kasiaMarek** [comment]
This seems to be a Scala 2 compiler bug. Calling `toLongString` (or `toString()`) on `List[Tuple1[Int]]]` produces `List[(Int,)]`. I'm guessing that's the culprit: https://github.com/scala/scala/blob/bf45e199e96383b96a6955520d7d2524c78e6e12/src/reflect/scala/reflect/internal/Types.scala#L2657. I'm not sure that workarounds in metals would make much sense for this.
cc: @tgodzik
