### ISSUE TITLE
'Quick fix' for new classes is not working

### ISSUE THREAD

**Issue by brndt** [scalameta/metals#5760]
### Describe the bug

1. Create random class/object
2. Try to use it in another package, IDE doesn't suggest to import it, as if it doesn't exist:
<img width="1342" alt="Screenshot 2023-10-17 at 20 21 37" src="https://github.com/scalameta/metals/assets/21007364/25d578f9-380d-47d9-aacd-9910a3c6953d">

4. Move random class/object to other package
5. IDE starts to suggest to import it from the package where it's located:
<img width="1324" alt="Screenshot 2023-10-17 at 20 22 29" src="https://github.com/scalameta/metals/assets/21007364/b467ea6d-24f9-4893-8e23-c13c65c079bd">

### Expected behavior

IDE should suggest to make an import of a new created class/object without having to move it to another package

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.1.0

**Comment by tgodzik** [comment]
Thanks for reporting. We usually need to compile the project before things get suggested to be imported. But we should be able to improve the behaviour here.

**Comment by brndt** [comment]
New class creation doesn't trigger compilation of the project, does it? The problem is that I should move to other package every new class I create before I can import it. I suppose it's something that triggers re-compilation.

**Comment by brndt** [comment]
@tgodzik as far as I can see, now creating a new file upon successful compilation, the IDE suggests you to import it. Is it possible to do an import even in the case of unsuccessful compilation?
This is a trivial case - the code does not compile because you miss some class, but after creating it there is no way to import it, which is why you have to temporarily comment sections of the code that broke compilation (in order to let IDE 'register' a new file), and then uncomment it again in order to be able to import a new file. It's not very developer friendly.

**Comment by tgodzik** [comment]
We are working on that! So hopefully it will be possible soon.
