### ISSUE TITLE
Error requesting workspace reset

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#5761]
### Describe the bug

In some situations, trying to reset the workspace results in error logs and not an actual clean.

I don't know what exactly triggers this scenario, but I have a workspace copy that seem to work:

[demo.tar.gz](https://github.com/scalameta/metals/files/12939229/demo.tar.gz)

1. Open metals in the workspace unpacked from the above tarball
2. Run "Metals: clear caches and reimport project"
3. See logs:
```
2023.10.17 20:58:24 WARN  Error requesting workspace reset
scala.concurrent.Future$$anon$2: Future.filter predicate is not satisfied
```

### Expected behavior

Workspace is reset.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.1.0

**Comment by jkciesluk** [comment]
Could you check if it works on latest snapshot? (1.1.0+14-74646c7b-SNAPSHOT)

**Comment by kubukoz** [comment]
It appears to work :)
