### ISSUE TITLE
Run CodeLens does not respect Bloop-configured JVM

### ISSUE THREAD

**Issue by harpocrates** [scalameta/metals#5780]
In my project's Bloop config, I have:

```json
        "platform": {
            "name": "jvm",
            "config": {
                "home": "C:\\Users\\Alec\\MyJdks\\jdk\\jdk-11.0.16.1+1",
                "options": [
                ]
            },
            "mainClass": [
            ],
            "resources": [
            ]
        },

```

However, when I click "run" in the CodeLens, I see that metals-vscode is using the version of Java that corresponds to `JAVA_HOME` instead.

**Expected behavior**

I'd expect the CodeLens to run the main method using the Java version configured in the corresponding Bloop projects JVM configuration (eg. as `bloop run` would do).

**Installation:**

- Operating system: reproduced on Windows, though likely platform independent
- VSCode version: 1.81.1
- VSCode extension version: 1.24.5
- Metals version: 1.0.0

**Comment by tgodzik** [comment]
Well, this seem to be actually quite easy to do and I totally forgot
