### ISSUE TITLE
Renaming of local functions misses end marker

### ISSUE THREAD

**Issue by keynmol** [scalameta/metals#5797]
### Describe the bug

![CleanShot 2023-10-28 at 13 31 28](https://github.com/scalameta/metals/assets/1052965/70c4cfd1-23e3-429c-a44e-fdb32cfe1e16)

### Expected behavior

As with top level functions, I expect the end marker to be renamed as well (just like with top level function)

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.1.0+39-f985a070-SNAPSHOT

### Extra context or search terms

rename, end marker, function, scala 3

**Comment by tgodzik** [comment]
Thanks for reporting! I think the issue might be that for local values we use the presentation compiler. We might need to get the end marker position from the unttped tree.
