### ISSUE TITLE
Missing error message when running Java 11

### ISSUE THREAD

**Issue by cquiroz** [scalameta/metals#582]
**Describe the bug**
On a certain project, I use metals and while metals/bloop can install and run successfully the editor cannot navigate nor shows all errors.

Looking at `bloop projects` we can see the projects and metals log shows a successful import. However metal doctor looks empty and when trying to navigate it shows messages like:

`WARN  code navigation does not work for the file '/Users/cquiroz/Projects/ocs3/modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala' because it doesn't belong to a build target.`

**To Reproduce**
1. Check out https://github.com/gemini-hlsw/ocs3 
2. Open atom and import
3. Try to navigate

**Expected behavior**
Metals working correctly

**Screenshots**
![img2](https://user-images.githubusercontent.com/3615303/54682569-077fd200-4aee-11e9-891a-3142a1b7aa44.png)
![img1](https://user-images.githubusercontent.com/3615303/54682570-077fd200-4aee-11e9-94c8-ae0f59968714.png)

**Installation:**
- Operating system: macOS
- Editor: Atom
- Metals version: v0.4.3

**Additional context**
Gitter discussion:
https://gitter.im/scalameta/metals?at=5c8fadf49d9cc8114adece33

**Search terms**
navigation, metals

**Comment by olafurpg** [comment]
Thank you for reporting! It is very helpful to have a repo that I can clone and run Metals myself 🙏 

Is there a specific file where navigation doesn't work? I am unable to reproduce in the files I opened

![2019-03-20 13 22 57](https://user-images.githubusercontent.com/1408093/54683959-4ecc8980-4b13-11e9-9551-6109725e4a49.gif)

**Comment by theqabalist** [comment]
I was able to reproduce this behavior on macros. In my case I had an external drive mounted at /Volumes/drive, and symlinked into my home at ~/drive. Launching atom from a project in the symlinked directory would recreate this behavior for me. Referring to the project through the canonical /Volumes/drive version alleviated the problem. I did not test symlink only to verify if that's the problem or if symlink to a mount is the issue.

**Comment by theqabalist** [comment]
also @olafurpg, given the same constraints I was not able to reproduce in vscode, since that's what your gif shows. So it seems to be specific to atom and it's interaction with metals. OP is also using atom.

**Comment by MateuszKubuszok** [comment]
@theqabalist do you use sbt to generate bloop? if so it might be related to https://github.com/sbt/sbt/issues/4552

**Comment by laughedelic** [comment]
I tried it on the referred project and it worked for _some_ subprojects, for example:
- works in `modules/ephemeris/src/main/scala/gem/horizons/HorizonsClient.scala`
- doesn't work in `modules/ephemeris/src/main/scala/gem/horizons/HorizonsClient.scala` (no target generated by bloop)

I don't think it's an Atom-specific problem.

**Comment by olafurpg** [comment]
@cquiroz in what source file does navigation not work for you? This might be an issue in sbt-bloop not detecting the declared sbt projects. I notice for example that build.sbt doesn't explicitly bind `lazy val coreJS = core.js`, I'm not sure if that has an effect.

Code navigation for cross-built projects is also not well supported, there is a feature request about it here https://github.com/scalameta/metals-feature-requests/issues/13

**Comment by cquiroz** [comment]
@olafurpg For example I don't get navigation on files on the module `seqexec_server`, e.g. on 
https://github.com/gemini-hlsw/ocs3/blob/develop/modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala

That module is jvm only (btw it has some java files, perhaps that is the reason)

**Comment by olafurpg** [comment]
@cquiroz I am unable to reproduce in Atom, navigation works fine for me in `SeqTranslate.scala`. Have you tried `rm -rf .metals .bloop`?

![2019-03-29 15 33 52](https://user-images.githubusercontent.com/1408093/55240032-37d71700-5238-11e9-8de4-9005dce3a40f.gif)

**Comment by cquiroz** [comment]
I did a deep review reinstalling and installing stuff and I think I found the reason. I installed OpenJDK 11 a while ago and forgot about it. I use 1.8 normally on the shell but I think Atom was still picking 11 and that failed

Thanks for checking this. Would it be good to add this to the documentation (maybe it is already there)

**Comment by olafurpg** [comment]
The server reports an error using `window/showMessage` saying

```scala
  def isUnsupportedJavaVersion: Boolean =
    scala.util.Properties.isJavaAtLeast("9")
  def warnUnsupportedJavaVersion(): Unit = {
    if (isUnsupportedJavaVersion) {
      val javaVersion = System.getProperty("java.version")
      val message =
        s"Unsupported Java version $javaVersion, no functionality will work. " +
          s"To fix this problem, restart the server using Java 8."
      languageClient.showMessage(new MessageParams(MessageType.Error, message))
      scribe.error(message)
    }
  }
```

when trying to connect to the build server. I wonder how we can make the message easier to discover 🤔

**Comment by cquiroz** [comment]
I don't recall seeing that. I got this message that got me thinking
```
ERROR WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/cquiroz/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.8/protobuf-
java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by olafurpg** [comment]
I just tried running Metals with Java 11 and got the following error

> Unsupported Java version 11.0.1, no functionality will work. To fix this problem, restart the server using Java 8.

Please reopen if you are able to provide a reproduction where Metals running on Java 9+ does not show that message.
