### ISSUE TITLE
Go to definition doesn't work for type when instantiating anonymous class

### ISSUE THREAD

**Issue by ghostbuster91** [scalameta/metals#5833]
### Describe the bug

I know that there is something more to it, as goto-def works usually when called in this context.

Full project to reproduce issue: https://github.com/ghostbuster91/demos/tree/decl-ref-2

Video demonstrating the issue: [Kooha-2023-11-13-10-50-18.webm](https://github.com/scalameta/metals/assets/5662622/8a3be947-f671-4eb5-8042-b55a1848009f)

Steps to reproduce:
1. import project
2. navigate to `ClientA` or `ClientB`
3. press go-to-definition on `Backend` from:
   ```scala
    private val dummy = new Backend[List] {
   ```
4. instead of going to the definition a popup is presented with following possibilities:
  - the import line from clientA file
  - the same line itself from clientA
  - the import line from clientB file
  - the analogical line from clientB

### Expected behavior

Calling go-to-definition should just open the definition as there is no ambiguity. 

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v1.1.0

### Extra context or search terms

The issue on occurs for scala 2.13.x . It does not occur for scala3.

One additional note: in the original project I have these two files `clientA` and `clientB` which are almost identical. Goto definition works correctly in one file while it doesn't work in the other one. 

metals doctor output:
```
## Metals Info
  - Metals Server version: 1.1.0
  - Metals Java: 19.0.2 from N/A located at /nix/store/dipa1yq31y6h5yranjscclyn24rwcrjs-openjdk-19.0.2+7/lib/openjdk

Below are listed the build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

## Workspaces

### Workspace: /home/kghost/workspace/demos
 - Build definition is coming from sbt.
 - Build server currently being used is Bloop v1.5.11.

## Build Targets

### root
  - target type: Scala 2.13.11
  - goto functionality: metalsDecode:file%3A%2F%2F%2Fdemos%2Froot.metals-buildtarget
  - compilation: ✅ 
  - diagnostics: ✅ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ✅ 
  - java: ✅ 

### root-test
  - target type: Scala 2.13.11
  - goto functionality: metalsDecode:file%3A%2F%2F%2Fdemos%2Froot-test.metals-buildtarget
  - compilation: ✅ 
  - diagnostics: ✅ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ✅ 
  - java: ✅ 

### http4s
  - target type: Scala 2.13.11
  - goto functionality: metalsDecode:file%3A%2F%2F%2Fdemos%2Fhttp4s.metals-buildtarget
  - compilation: ✅ 
  - diagnostics: ✅ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ✅ 
  - java: ✅ 

### http4s-test
  - target type: Scala 2.13.11
  - goto functionality: metalsDecode:file%3A%2F%2F%2Fdemos%2Fhttp4s-test.metals-buildtarget
  - compilation: ✅ 
  - diagnostics: ✅ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ✅ 
  - java: ✅ 

### demos-build
  - target type: sbt 1.9.4
  - goto functionality: metalsDecode:file%3A%2F%2F%2Fdemos%2Fdemos-build.metals-buildtarget
  - compilation: ✅ 
  - diagnostics: ⚠️ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ❌
  - java: ✅ 
  - recommendation: Diagnostics and debugging for sbt are not supported currently.

### demos-build-build
  - target type: sbt 1.9.4
  - goto functionality: metalsDecode:file%3A%2F%2F%2Fdemos%2Fdemos-build-build.metals-buildtarget
  - compilation: ✅ 
  - diagnostics: ⚠️ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ❌
  - java: ✅ 
  - recommendation: Diagnostics and debugging for sbt are not supported currently.
```

search terms:

goto-definition

**Comment by tgodzik** [comment]
Thanks for reporting! I don't seem to be able to reproduce. Did any renaming etc. was involved before? Might  be related to the other issue you raised with semanticdb stacktrace?

The weirdest part is that we don't really have a logic that would make go to definition show imports or the same line :thinking:

**Comment by ghostbuster91** [comment]
> Thanks for reporting! I don't seem to be able to reproduce. Did any renaming etc. was involved before?

No. I am able to reproduce the issue on the fresh checkout.


> Might be related to the other issue you raised with semanticdb stacktrace?

I don't know. 

> The weirdest part is that we don't really have a logic that would make go to definition show imports or the same line 🤔

Let me know what kind of other information would you like me to provide. Some logs from the metals? bloop version? jdk version?

**Comment by tgodzik** [comment]
The logs would probably be awesome to have. You could add the debug flag to get more info if possible. That is `-Dmetals.loglevel=debug`

**Comment by ghostbuster91** [comment]
[metals.log](https://github.com/scalameta/metals/files/13430546/metals.log)
[lsp.trace.json](https://github.com/scalameta/metals/files/13430547/lsp.trace.json)
These logs captures opening already imported project, navigating to file, and calling goto def on the backend symbol in one of the clients. 

Let me know if you need logs from the clean import.

**Comment by ghostbuster91** [comment]
together with @rochala we were able to find that the symbol in presentation compiler has no position. However, our fruitful debugging session was interrupted by a logging issue. 

I am sure that @rochala can explain it better than me, so I am going to skip the details. 

For anyone else reading it, rest assured, we will continue the investigation.
