### ISSUE TITLE
`documentHighlight` in map is reversed

### ISSUE THREAD

**Issue by PeuTit** [scalameta/metals#5840]
### Describe the bug

While navigating in my project, I saw that the highlight for a variable in a `map` function was not correct. Looking closely, I noticed that the highlight section is actually reversed. The screenshot below illustrates it:

![Screenshot 2023-11-16 at 10 20 12](https://github.com/scalameta/metals/assets/22703571/2fe401cf-cc88-4dcc-a17e-64cf6860f8c5)

The complete response looks like this:
```
[Trace - 10:13:48 AM] Received request 'textDocument/documentHighlight - (31)'
Params: {
  "textDocument": {
    "uri": "file:///Users/titouan/Documents/work/perso/scala/scala-cli-test-project/files.scala"
  },
  "position": {
    "line": 6,
    "character": 5
  }
}


[Trace - 10:13:48 AM] Sending response 'textDocument/documentHighlight - (29)'. Processing request took 3ms
Result: [
  {
    "range": {
      "start": {
        "line": 5,
        "character": 22
      },
      "end": {
        "line": 5,
        "character": 27
      }
    },
    "kind": 3
  },
  {
    "range": {
      "start": {
        "line": 6,
        "character": 4
      },
      "end": {
        "line": 6,
        "character": 9
      }
    },
    "kind": 2
  }
]
```

You can reproduce with a minimal `scala-cli` build and the following code:

```
//> using scala 2.13.12

object Hello {
  "string".map { char: Char =>
    char
  }
}
```

### Expected behavior

The highlight range should be on the `char` variable.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.1.0

### Extra context or search terms

Same Behaviour when opening the same project in VSCode.

**Comment by tgodzik** [comment]
Thanks for reporting! We need to take a look into that. The actual issue seems to be that the positions are not correct.
