### ISSUE TITLE
Action to add an import to the Scala-CLI script puts it before the shebang.

### ISSUE THREAD

**Issue by arturopala** [scalameta/metals#5854]
When editing an `.sc` file and `Import XYZ from ...` action is executed, the import statement is added before the shebang statement breaking the script.

Before:
<img width="845" alt="Screenshot 2023-11-18 at 12 48 48" src="https://github.com/scalameta/metals/assets/250927/9338ef11-8712-4373-94ba-51e48352cc38">

After:
<img width="845" alt="Screenshot 2023-11-18 at 12 48 25" src="https://github.com/scalameta/metals/assets/250927/0e1376c1-84b0-43f6-bb05-502d2710cad7">

### Expected behaviour:

A new import statement should be added to the imports section.

**Operating system:**
Mac OS X

**Java version:**
17.0.1

**Editor/extension:**
Visual Studio Code v1.84.2

**Metals version:**
1.1.0+92-a07ab91c-SNAPSHOT

### Workspace information:
 - **Scala versions:** 3.3.1
 - **Build tools:** 0. scala-cli
 - **Build servers:**
    0. scala-cli v1.0.5
 - **All build tools in workspace:**

**Comment by kasiaMarek** [comment]
Do you have a reproduction? It seems to work as expected for me.
