### ISSUE TITLE
Cannot discover test frameworks

### ISSUE THREAD

**Issue by doofin** [scalameta/metals#5866]
### Describe the bug

I got an error while work on cross jvm/js project in Scala 2.13: 

`Encountered an error in the build server: Cannot discover test frameworks, missing node_modules in test project, expected them at ~/proj/js/node_modules`

try to search in metals code base, but unable to find where this error comes from

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.1.0

**Comment by tgodzik** [comment]
Thanks for reporting! This is coming from Bloop actually, I think it relies on having the node_modules set up by sbt first :thinking:

**Comment by doofin** [comment]
The actual problem seems to be that the code in test contains errors and which is not compiled, fixing the test removes this error

**Comment by tgodzik** [comment]
Will close it here and fix in Bloop
