### ISSUE TITLE
Go to Implementation doesn't find anonymous instantiations with SAM conversion

### ISSUE THREAD

**Issue by filipwiech** [scalameta/metals#5868]
### Describe the bug

Recently I was confused as Metals couldn't find any implementation of a type in the project, even thought it had to be used *somewhere*. Turns out that Go to Implementation is unable to find anonymous instantiations if SAM conversion is applied. Example, only `test3` and `test4` are shown when trying to search for the `MyTestTrait` implementations:
```scala
// applies to abstract classes too
trait MyTestTrait {
  def compute(input: Int): Int
}

// MyTestObject could be a class, trait, etc.
object MyTestObject {

  val test1: MyTestTrait = (input: Int) => input + 1
  def test2: MyTestTrait = (input: Int) => input + 2

  val test3: MyTestTrait = new MyTestTrait {
    def compute(input: Int): Int = input + 3
  }
  def test4: MyTestTrait = new MyTestTrait {
    def compute(input: Int): Int = input + 4
  }

}
```
Tested on Scala 2.13.

### Expected behavior

All implementations are shown by Metals, including the `test1` and `test2` in the provided code sample.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

1.1.0+100-58b80be5-SNAPSHOT

### Extra context or search terms

go to implementation, SAM, anonymous type, class, trait

**Comment by kasiaMarek** [comment]
Thanks for the report. Go to implementation bases on `SemanticDB`, which doesn't produce an anonymous class for  SAM conversion both in Scala 2 and Scala 3.

**Comment by tgodzik** [comment]
We also have an issue already about that, but thanks for reminding us!

**Comment by filipwiech** [comment]
@kasiaMarek Thank you for the explanation! :+1:  Is there an upstream ticket that could be tracked? :slightly_smiling_face: 
@tgodzik Oops, sorry about that, my bad for not noticing this earlier. I've filed the issue late at night after getting a reproduction and haven't thought to check. :sweat_smile:

**Comment by tgodzik** [comment]
I raised it in https://github.com/scalameta/scalameta/issues/3394
