### ISSUE TITLE
Navigating to the (re)exported method definition leads to the type enclosing the export instead of the definition source.

### ISSUE THREAD

**Issue by arturopala** [scalameta/metals#5892]
Navigating to the (re)exported method definition leads to the type enclosing the export instead of the definition source.

In the following example code, when I click on `.foo` in line 2, then the focus goes to line 5 instead of 15. 
This also works the same way in a multiple scala files setup.

```scala
class Test extends A {
  assert("Hello".foo == "HelloFoo")
}

trait A {
  export A.*
}

object A {
  export B.*
}

object B {
  extension (value: String) 
    def foo: String = s"${value}Foo"
}
```

### Expected behaviour:

Navigation should lead to the method definition.

**Operating system:**
Mac OS X

**Java version:**
17.0.1

**Editor/extension:**
Visual Studio Code v1.84.2

**Metals version:**
1.1.0+119-d5889c8a-SNAPSHOT

### Workspace information:
 - **Scala versions:** 3.3.1
 - **Build tools:** 0. scala-cli
 - **Build servers:**
    0. scala-cli v1.0.5
 - **All build tools in workspace:** sbt

**Comment by kasiaMarek** [comment]
scala 3 compiler fix https://github.com/scala/scala3/pull/19494

**Comment by tgodzik** [comment]
Should we close it then as `fixed-upstream` ?

**Comment by kasiaMarek** [comment]
Not fixed yet, compiler fix enables us to fix this, there have to be some changes in Metals too.
