### ISSUE TITLE
sbt auto-stop not triggered

### ISSUE THREAD

**Issue by dre-hh** [scalameta/metals#591]
**Describe the bug**
Calling `:LanguageClientStop` on autozimu/LanguageClient-neovim does not stop the sbt
process. Metals is stopped correctly.

The project is using openjdk-11 with `scalacOptions ++= Seq("-target:jvm-1.8")`
After starting metals with a jdk8, there are 2 java processes running. metals from java 8 and an openjdk-11 eleven sbt process. Stopping the server only exits the former but not the latter  

**To Reproduce**
1.  create a project with  `scalacOptions ++= Seq("-target:jvm-1.8")`
2. create metals wrapper script for starting metals on with jdk8 
e.g when using asdf `ASDF_JAVA_VERSION=8.172 ~/bin/metals-vim`
3. switch java to openjdk 11 with a java version manager
4. Open a scala file in a project and execute  `:LanguageClientStart` 
5. Execute `:LanguageClientStop `

NOTE: neovim language has by default auto-start and auto-stop enabled and  `LanguageClientStart` on opening a scala file and `LanguageClientStop` on closing

**Expected behavior**
All java processes are stopped

**Screenshots**

**Installation:**
- Operating system: macOS Mojave 10.14.3
- Editor: neovim/0.3.4
- Metals version: v0.4.0

**Additional context**
`asdf` as version manager with recent `jdk 1.8` and `openjdk-11`

**Search terms**
auto-stop neovim LanguageClient-neovim openjdk

**Comment by dre-hh** [comment]
Sorry for the noise folks. I just saw, that openjdk-11 is started when i just open a scala file even with auto-start disabled. i suppose this is from the vim-scala plugin, which was part of the install documentation

**Comment by olafurpg** [comment]
Thanks for reporting! To clarify, when you say “sbt process” do you mean the background sbt process started by the “import build” command?

**Comment by dre-hh** [comment]
I just identified the process is started  `ale` plugin (syntax checking). please close the issue, i will report there. metals works like charm so far

**Comment by olafurpg** [comment]
Sounds good 👍
