### ISSUE TITLE
Auto-import inserts imports between methods and their modifiers 

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#593]
**Describe the bug**
When auto-completing a method parameter type from the workspace scope, the import is placed on the line immediately above the method, regardless of potential modifiers such as annotations.

**To Reproduce**
![2019-03-27 15 09 21](https://user-images.githubusercontent.com/691940/55082740-8652ad00-50a2-11e9-8b93-53d4d2417208.gif)

**Expected behavior**
The import is inserted above the existing modifiers

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.5.0-SNAPSHOT

**Search terms**
auto-import, decorators, modifiers

**Comment by olafurpg** [comment]
Thanks for reporting! I'm able to reproduce, fix coming soon.
