### ISSUE TITLE
Metals starts in non-Scala projects

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scalameta/metals#5931]
### Describe the bug

1. Create a new empty folder
2. Open it in VS Code with Metals installed
3. Metals will start and create the `.metals` directory, even though this is not a Scala project

With such behavior, when working with non-Scala projects, one needs to keep Metals disabled, since it's going to pollute the project directory with the `.metals` folder, and reduce the real estate of the files explorer tab by opening irrelevant controls.

https://github.com/scalameta/metals/assets/2614813/41b2b40f-98c7-42f7-900d-5dd9d5c9fb80

### Expected behavior

If a project is not a Scala project (that is, no sbt, scala or sc files are there), do not start the metals server, do not display metals in the Files Explorer tab, and do not create the `.metals` directory inside the project.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.1.0

**Comment by ritschwumm** [comment]
(maybe) interestingly, this only happens when the extension tab is visible

**Comment by tgodzik** [comment]
> (maybe) interestingly, this only happens when the extension tab is visible

That's exactly it. VS Code does it automatically without Metals specifying this condition. There is nothing we can do aside from maybe fixing the behaviour with creating .metals in that case. PReviously raised here https://github.com/scalameta/metals-vscode/issues/1439
