### ISSUE TITLE
Apache Spark build error: "'17' is not a valid choice for '-target'"

### ISSUE THREAD

**Issue by nchammas** [scalameta/metals#5933]
I'm trying to load the [Apache Spark project][1] at commit `82a02321b873cc67a521e98e25b9b07fd84b5684` into VS Code using Metals and get code navigation to work. The build fails with this error:

[1]: https://github.com/apache/spark

```
2023.12.10 14:56:35 INFO  compiling spark-tags_2.13 (2 scala sources and 8 java sources)
2023.12.10 14:56:35 ERROR Build server error: '17' is not a valid choice for '-target'
2023.12.10 14:56:35 ERROR Build server error: bad option: '-target:17'
```

I believe this is a reference to this line, though I am not sure: https://github.com/apache/spark/blob/b28988dbc6ff0d9b95059825a0a77fa6ce5e5c75/pom.xml#L2977

I have set the following settings to ensure that Metals is using the Spark project's configurations for sbt and mvn, to no avail:

```
"metals.javaHome": "/path/to/.sdkman/candidates/java/current"
"metals.sbtScript": "/path/to/spark/build/sbt"
"metals.mavenScript": "/path/to/spark/build/mvn"
```

My `.sdkmanrc` setup:

```
java=17.0.9-tem
scala=2.13.12
```

How can I debug this further? I doubt that `17` is truly invalid as a target. I assume the Apache Spark project has a working build.

### Workspace information:
 - **Operating system:** Mac OS X
 - **Editor/extension:** Visual Studio Code v1.85.0
 - **Metals version:** 1.1.0
 - **Java version:** 17.0.9
 - **Scala versions:** 2.13.12
 - **Build tools:** 0. mvn
 - **Build servers:** 0. Bloop v1.5.11
 - **All build tools in workspace:** Bloop; sbt; Maven

**Comment by nchammas** [comment]
I think I figured it out. There was _another_ configuration for the Java home under this path:

```
/home/.bloop/bloop.json
```

It was pointed to Java 1.8. Deleting that file and restarting VS Code caused Metals / bloop to regenerate that file, but this time with the correct Java 17 home I had configured directly in VS Code.

Note that the Metals Doctor did not indicate anything about Java 1.8 being used, though I did see it fly by in one of the lengthy logs that Metals output after one of my many attempts to reset its state. I also had to be sure to pick Maven and not sbt as the build system for the project (since Apache Spark supports both).

I can now use code navigation normally, and I don't get errors about `-target` anymore (though Java does now warn that `-target` is deprecated in favor of `-release`).

**Comment by tgodzik** [comment]
You should get a notification to restart Bloop to JDK 17, did you see it at any point? We suggest an update if  Bloop Java is different than Metals one. Though I see some people weren't getting those notifications. The logic is quite complex there, so probably we need to rethink how we set Java to use.

**Comment by nchammas** [comment]
Not that I recall. I tried several times to reset Metals's state, restart VS Code, etc. before I happened to notice the Java 1.8 line in the logs. Nothing called out to me from the VS Code UI, though I might have just missed it.
