### ISSUE TITLE
Metals doesn't find all definitions depending on how the variable is used

### ISSUE THREAD

**Issue by SkyTrix** [scalameta/metals#5939]
**Describe the bug**

Depending on how a variable is used, Metals is unable to go to the correct definition or find back the references. 

**To Reproduce** Steps to reproduce the behavior:

The behavior is best demonstrated in metals-vscode version 1.20.0 using Metals 0.11.9:

Here you can see that I can jump to the definition of `dummy` when used in `route2` and `route3`. However, when used in `route`, it finds two definitions: the `apply` method in `scala.Function1` and and an implicit method `addDirectiveApply` in Akka's `Directive` object.

When looking for references, it also only shows the usage in `route2` and `route3`.

![metals-0 11 9](https://github.com/scalameta/metals-vscode/assets/889203/a399f1ad-b1ec-407b-9ef7-07758d42dfd6)

In metals-vscode version 1.27.0 using Metals 1.2.0 this behavior further regresses: it can only find the definition when executed from `route3`.

![metals-1 2 0](https://github.com/scalameta/metals-vscode/assets/889203/126a76f8-7e80-47ff-ac48-1740760508fc)

**Expected behavior**

Ideally, Metals is able to jump to the definition for all cases shown in the example.

**Installation:**

- Operating system: Windows
- VSCode version: 1.85.0
- VSCode extension version: 1.27.0
- Metals version: 1.2.0

**Search terms**

definitions, references

**Comment by tgodzik** [comment]
Thanks for reporting! This is something worth investigating, the additional definitions are connected to the additional code compiler generates and might be helpful sometimes, but it seems in this case they are not.

**Comment by kasiaMarek** [comment]
Self contained reproduction:
```Scala
case class A(f: Int => Int)

object A {
  implicit def toF(a: A): Int => Int = a.f
}

object Test {
  val g = new A(_ + 1)
  val re = g(1)
}
```
This is a bug in Scala 2 semanticDB:
Is:
```
[...]
[10:11..10:12) => _empty_/A.toF().

Synthetics:
[10:11..10:12) => *.apply
  apply => scala/Function1#apply().
[10:11..10:12) => toF(*)
  toF => _empty_/A.toF().
 ```

Should be:
```
[...]
[10:11..10:12) => _empty_/Test.g.

Synthetics:
[10:11..10:12) => *.apply
  apply => scala/Function1#apply().
[10:11..10:12) => toF(*)
  toF => _empty_/A.toF().
```

**Comment by tgodzik** [comment]
Scalameta has been released and the fix is in Metals
