### ISSUE TITLE
Latest release wrongly reported as snapshot

### ISSUE THREAD

**Issue by gvolpe** [scalameta/metals#5952]
### Describe the bug

The [latest page](https://scalameta.org/metals/latests.json) is reporting the following:

```json
{
  "release": "1.2.0+13-615add64-SNAPSHOT",
  "snapshot": "1.2.0+13-615add64-SNAPSHOT"
}
```

I have some automated scripts that depend on this page, and my Metals version was [wrongly upgraded](https://github.com/gvolpe/nix-config/pull/248) to this snapshot.

### Expected behavior

The release should still report `1.2.0`.

### Operating system

None

### Editor/Extension

None

### Version of Metals

N/A

**Comment by tgodzik** [comment]
Looks like this was caused by a `501`:

```
2023.12.15 16:15:23:291 sbt-bg-threads-1 ERROR docs.Snapshot.latest:34
    unexpected error fetching SNAPSHOT version
    org.jsoup.HttpStatusException: HTTP error fetching URL. Status=501, URL=[http://repo1.maven.org/maven2/org/scalameta/metals_2.13/]
```

It's back to normal. I added PR that adds a retry, but overall it might safer for your workflow to use maven directly or via coursier. You can handle an error easier there.

**Comment by gvolpe** [comment]
Thanks!
