### ISSUE TITLE
Long project compilation in some cases

### ISSUE THREAD

**Issue by nikpivkin** [scalameta/metals#5966]
**Describe the bug**

Hi! I am new to Scala development. If I comment out the line `implicit val logger: Logger[IO] = Slf4jLogger.getLogger[IO]` then the project will compile infinitely. The compile timer goes up to 30 seconds (sometimes even higher), then resets to 0 and so on indefinitely.

**To Reproduce** Steps to reproduce the behavior:

1.  `sbt new scala/scala3.g8`
2. Add dependencies:
```sbt
libraryDependencies += "org.typelevel" %% "log4cats-slf4j"   % "2.6.0",
libraryDependencies += "org.typelevel" %% "cats-effect" % "3.5.2",
libraryDependencies += "io.github.apimorphism" %% "telegramium-core" % "8.69.0",
libraryDependencies += "io.github.apimorphism" %% "telegramium-high" % "8.69.0",
```
3. Main.scala:
```scala
import org.typelevel.log4cats.Logger
import org.typelevel.log4cats.slf4j.Slf4jLogger
import org.http4s.blaze.client.BlazeClientBuilder
import cats.effect.{IO, IOApp}
import cats.effect.kernel.Sync
import cats.effect.ExitCode
import cats.effect.kernel.Async
import cats.Parallel
import telegramium.bots.high.Api
import telegramium.bots.high.LongPollBot
import telegramium.bots.Message
import telegramium.bots.ChatIntId
import telegramium.bots.high.BotApi
import telegramium.bots.BotCommand
import telegramium.bots.high.implicits._

class Bot[F[_]: Logger](implicit
    bot: Api[F],
    asyncF: Async[F],
    parallel: Parallel[F]
) extends LongPollBot[F](bot) {

  import cats.syntax.functor.*

  override def onMessage(msg: Message): F[Unit] = 
    import cats.implicits._
    sendMessage(
            chatId = ChatIntId(msg.chat.id),
            text =  msg.text.getOrElse("")
    ).exec.void.handleErrorWith(e => Logger[F].error(e)("failed to send message"))
}

object HelloWorld extends IOApp {
  import cats.implicits._
  
  implicit def logger[F[_]: Sync]: Logger[F] = Slf4jLogger.getLogger[F]

  override def run(args: List[String]): IO[ExitCode] = {
    BlazeClientBuilder[IO].resource.use { httpClient =>
      implicit val api: Api[IO] =
        BotApi(httpClient, baseUrl = s"https://api.telegram.org/botSometoken")
      // implicit val logger: Logger[IO] = Slf4jLogger.getLogger[IO]
      val bot = new Bot()
      bot.start().as(ExitCode.Success)
    }
  }
}
```

**Expected behavior**

The compilation will complete successfully and in a reasonable amount of time.

**Screenshots**

<img width="161" alt="image" src="https://github.com/scalameta/metals-vscode/assets/100182843/5545cac2-5f43-4476-be5c-e01498841284">

The highlighting of the commented line is also broken (but this probably does not apply to your project):
<img width="590" alt="image" src="https://github.com/scalameta/metals-vscode/assets/100182843/7249855a-d4a5-4c46-a5e5-6beb9006e026">

**Installation:**

- Operating system: mac M1
- VSCode version: 1.85.1
- VSCode extension version: 1.27.0
- Metals version: 1.2.0

**Comment by tgodzik** [comment]
Thanks for reporting! It looks like I can't compile this with `sbt compile` either, so the problem look like a compiler one. I will try to get some more insight here from the compiler team.

**Comment by tgodzik** [comment]
The issue with the comment comes most likely from the same space, as the same compiler is used and VS Code is using old tokens while waiting for the compilation to finish.

**Comment by tgodzik** [comment]
I raised an issue in the compiler https://github.com/lampepfl/dotty/issues/19320

There is nothing we can do on the Metals side, but thanks for letting us know anyway!
