### ISSUE TITLE
Different UX for hovering over extension methods with type arguments 

### ISSUE THREAD

**Issue by arainko** [scalameta/metals#5976]
### Describe the bug

```scala
// using scala 3.3.1

sealed trait ExtensionProvider {
  extension [A] (self: A) {
    def typeArg[B <: A]: B
    def noTypeArg: A
  }
}

object Repro {
  def usage[A](f: ExtensionProvider ?=> A => Any): Any = ???

  usage[Option[Int]](_.typeArg[Some[Int]].value.noTypeArg.typeArg[Int])
}
```

1. Hover over `.noTypeArg` without clicking anything - symbol and expression information will be presented almost immediately,
2. Hover over `.typeArg[Some[Int]]` or `.typeArg[Int]` - nothing is shown, to make it work:
    1. Click the expression you're trying to get the information about two times,
    2. Move your mouse cursor off the expression,
    3. Hover over the expression once again and the information will be presented.

**BONUS** just hovering over the underscore shows the information about the invocation of `.typeArg[Some[Int]]`, presumably due to how extension method calls are desugared? 

### Expected behavior

Hovering over extension methods with type arguments should behave in the same way as hovering over extensions without type arguments.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

1.2.0+12-644090c2-SNAPSHOT

### Extra context or search terms

extension method hover

**Comment by jkciesluk** [comment]
Hi, thanks for reporting.

> BONUS just hovering over the underscore shows the information about the invocation of .typeArg[Some[Int]], presumably due to how extension method calls are desugared?

Probably its connected to the second issue https://github.com/scalameta/metals/issues/5977, in both the span is moved to the whitespace, but here semantic highlight works correctly 🤔 .
I will take a look at both issues.
