### ISSUE TITLE
Semantic highlighting and symbol information broken for extension methods with inferred type arguments

### ISSUE THREAD

**Issue by arainko** [scalameta/metals#5977]
### Describe the bug

```scala
// using scala 3.3.1

sealed trait ExtensionProvider {
  extension [A] (self: A) {
    def typeArg[B <: A]: B
    def inferredTypeArg[C](value: C): C
  }
}

object Repro {
  def usage[A](f: ExtensionProvider ?=> A => Any): Any = ???

  usage[Option[Int]](_.typeArg[Some[Int]].value.inferredTypeArg("str"))

  usage[Option[Int]](_.typeArg[Some[Int]].value.inferredTypeArg[String]("str"))
}
```
Using `inferredTypeArg` and actually allowing the compiler to infer the type breaks semantic highlighting and hover information of the expression just before it (`.value` in this case) - explicitly specifying the type argument fixes the problem. Here's a short video showcasing the problem:

[Screencast from 12-24-2023 01:41:18 PM.webm](https://github.com/scalameta/metals/assets/46346508/e14bf020-d7ba-484e-a871-07841c5940e6)

### Expected behavior

Extension methods with inferred type arguments should behave the same as ones with explicitly provided type args.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

1.2.0+12-644090c2-SNAPSHOT

### Extra context or search terms

semantic highlighting extension method

**Comment by jkciesluk** [comment]
Hi, thanks for reporting.
It looks like `inferredTypeArg` with inferred type argument has incorrect span and because of this we don't see its occurrence where it should be.
We will look into it.
