### ISSUE TITLE
Auto-import inserts import in-between multiline case class parameters

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#599]
**Describe the bug**
Auto-import inserts import in-between multiline case class parameters

**To Reproduce**
![2019-03-30 15 43 11](https://user-images.githubusercontent.com/691940/55277624-ad0f1e80-5302-11e9-925a-747c29484898.gif)

**Expected behavior**
import is inserted above the case class

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.5.0-SNAPSHOT

**Search terms**
auto-import case class

**Comment by olafurpg** [comment]
Thanks for reporting! Pending fix in https://github.com/scalameta/metals/pull/600
