### ISSUE TITLE
No code lenses or main class when using shebang

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#6017]
### Describe the bug

```scala
#!/usr/bin/env -S scala-cli shebang

//> using toolkit latest
//> using dep com.lihaoyi::requests:0.8.0


import upickle.default.*
import requests.*

object Main extends App {

    println(get("https://httpbin.org/get"))
    println(write(Seq(1, 2, 3)))
    println(12)
}
 ```

Runs from the cmd, but not from Metals

### Expected behavior

Project can be run in Metals

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.2.0

### Extra context or search terms

shebang run debug

**Comment by tgodzik** [comment]
We should also make sure that the scripts work with shebang

**Comment by kasiaMarek** [comment]
https://github.com/scalameta/metals/pull/6039 resolves this for Scala 3. For Scala 2 this needs an upstream fix, since semanticdb is not created properly.
