### ISSUE TITLE
DebugProvider is not using .jvmopts when launching test via right click

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/metals#6026]
### Describe the bug

I have a .jvmopts file with jvm flags

When I launch a test from vscode via Run Test (right click from the guter) it fails (because the jvm flags are not set)

![image](https://github.com/scalameta/metals/assets/921490/350f0cdb-f440-459f-8a26-467e1237e925)

If I run via the test explorer it succeed (because the jvm flags are set)

### Expected behavior

both test options should set jvm flags

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.2.0+71-b6841c5a-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! We should check if `.jvmopts` are added when using things like sbt and make sure our behaviour matches it, so there are not surprises.

**Comment by gchudnov** [comment]
bumped into the same issue when trying to write tests in a project that is using Apache Arrow. It is requiring `--add-opens=java.base/java.nio=org.apache.arrow.memory.core,ALL-UNNAMED` to be set, and it is set in `.jvmopts`, however when running just a single test as mentioned above, these options are not considered...

**Comment by gchudnov** [comment]
Wanted to dig a bit deeper here (the issue really bothers me), it would be great to get some guidance where to look.

**Comment by tgodzik** [comment]
This might be relevant: 
https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala#L723

we already read from env file there, so should be ok to read from jvmopts.

Although, for test explorer it's probably: 
https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala#L764

You should be able to add it via `testSuites.copy(jvmOptions = ...)` and probably it would be good to add in both above places plus envFile, which is a pretty close logic.

**Comment by gchudnov** [comment]
Thank you, will check!
