### ISSUE TITLE
Scala 3: Imports in worksheets inserted before directives

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#6027]
### Describe the bug

This is a reincarnation of #4939, but specifically in Scala 3 worksheets.

To reproduce:

1.

```scala
//> using scala "2.13.10"
//> using lib "org.typelevel::cats-core:2.9.0"

object A {
  Future<cursor>.successful(1)
}
```

2. Complete Future to the `scala.concurrent` variant

3. Look at outcome

```scala
import scala.concurrent.Future
//> using scala "3.3.1"
//> using lib "org.typelevel::cats-core:2.9.0"

object A {
  Future.successful(1)
}
```

### Expected behavior

```scala
//> using scala "3.3.1"
//> using lib "org.typelevel::cats-core:2.9.0"
import scala.concurrent.Future

object A {
  Future.successful(1)
}
```

### Operating system

macOS

### Editor/Extension

None

### Version of Metals

1.2.0

### Extra context or search terms

- this is with Scala-cli 1.1.0
- doesn't seem to happen in 2.13 or in normal scripts
- I tried to apply due diligence and reproduce in a failing test (based on https://github.com/scalameta/metals/pull/4940) but when using a worksheet it wasn't even able to provide quickfixes (or at least the test said so): https://github.com/scalameta/metals/compare/main...kubukoz:metals:failing-test-6027?expand=1

**Comment by tgodzik** [comment]
Thanks for reporting! Worksheets aren't currently aware of using directives, which is most likely why this case was not handled. However, we should probably insert imports after any kinds of comments.
