### ISSUE TITLE
Incorrect `activeParameter` in type declarations for signature help.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#6040]
### Describe the bug

Given a minimal piece of code like this:

```scala
trait Test[A, B] {
  def doThing[C](f: B => Test[A@@, C]) = ???
}
```

Assume the user triggers a signature help indicated at the position of `@@`. Current the request and the response looks like this:

```
[Trace - 01:40:58 PM] Received request 'textDocument/signatureHelp - (11)'
Params: {
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/minimal/Test.scala"
  },
  "position": {
    "line": 1,
    "character": 30
  }
}


[Trace - 01:40:58 PM] Sending response 'textDocument/signatureHelp - (11)'. Processing request took 88ms
Result: {
  "signatures": [
    {
      "label": "Test[A, B]: Test",
      "parameters": [
        {
          "label": "A"
        },
        {
          "label": "B"
        }
      ]
    }
  ],
  "activeSignature": 0,
  "activeParameter": 1
}
```

Notice the `activeParameter` is `1` when it should be `0` causing this to display incorrectly:

<img width="363" alt="Screenshot 2024-01-23 at 13 43 47" src="https://github.com/scalameta/metals/assets/13974112/f278fc42-aa71-4111-89aa-853791031034">

### Expected behavior

I'd expect this to return `0` as the active parameter.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.2.0+77-ecb7dcfd-SNAPSHOT

**Comment by rochala** [comment]
It also fails after latest changes, so this is problem in dotty. I'll try to fix this.

**Comment by rochala** [comment]
I've fixed this in dotty, the problem is the issue is in the `Signatures.scala` which is the part of scala3-compiler. This makes it not possible to backport unless we decide to move signatures back to presentation compiler. @tgodzik I leave the decision to you.

**Comment by tgodzik** [comment]
That's fine, especially that we would need to anyway have it under newer compiler version.
