### ISSUE TITLE
Test fails with exception, but Metals reports that test succeeded

### ISSUE THREAD

**Issue by dbronecki** [scalameta/metals#6052]
### Describe the bug

I'm using Metals in VS Code with Weaver test framework.
When test raises exception, it is reported that test passed successfully.
IJ and SBT correctly detects failed test case.

See attached image and example project

[metals-test.zip](https://github.com/scalameta/metals/files/14072335/metals-test.zip)

![image](https://github.com/scalameta/metals/assets/25744491/d6b20c85-b793-45ac-bd6d-2d1cde91fef2)

### Expected behavior

Test window should indicate that test failed

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.2.0

**Comment by tgodzik** [comment]
Thanks for reporting and the reproduction! We will take a look into it!

**Comment by kasiaMarek** [comment]
We don't yet support Weaver, and since no test cases are discovered "all pass" in a sense.

**Comment by dbronecki** [comment]
@kasiaMarek makes sense. Feel free to close this issue if you are not planning to support Weaver in near future.
