### ISSUE TITLE
Implicits (`cats.implicits.given`) slow down completion to the point of timeout

### ISSUE THREAD

**Issue by KaranAhlawat** [scalameta/metals#6054]
### Describe the bug

Having the `cats.implicits.given` or `cats.implicits.*` import at the top of a file hinders the completions at certain points in the file greatly (e.g. type constraints).

1. Create a project with Typelevel `cats` as dependency.
2. Create a class with a generic type and some constraints on it.
3. Use the constraint so that a given instance is required. At this point, the compiler should complain that no given instance for the type constraint is found.
4. Import `cats.implicits.*` and save, the compiler should compile fine now.
5. Try to get completions for the type constraint above, the completions usually time out for it.
6. If you remove the implicit import, and save a couple times, the completions work as normal but then the compiler errors out due to no given instances being found.

### Expected behavior

Having the import should not impact the speed or working of autocompletions.

### Operating system

Linux

### Editor/Extension

Emacs (lsp-metals)

### Version of Metals

v1.2.0

**Comment by tgodzik** [comment]
Looks like this is the same issue as I raised in https://github.com/lampepfl/dotty/issues/19320

**Comment by tgodzik** [comment]
This is fixed upstream and will be available in 3.4.1 and 3.3.3
