### ISSUE TITLE
Test Explorer cannot detect unit test when using mill-bsp

### ISSUE THREAD

**Issue by PeterWang-dev** [scalameta/metals#6090]
### Describe the bug

Use Chisel Template project as an example:

1. Clone [this repository](https://github.com/PeterWang-dev/TestProject) that I created from template.
2. Initialize project with bloop and open Test Explorer. You will find every thing works well.
3. Clean up repository `git clean -fdx` and reload the vscode window.
4. Do not import build at first. Then press `Ctrl+Shift+P`, typing `Metals: Switch build server` to change build server to `mill-bsp`
5. Initialize project. Open Test Explorer and observed that no tests display here.

### Expected behavior

Unit test can be detected and displayed in Test Explorer when using mill-bsp.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.2.0

**Comment by tgodzik** [comment]
Thanks for reporting! Running tests with mill-bsp is not currently supported. This is blocked by https://github.com/scalameta/metals/issues/5928 Once the other issue is done it should work correctly.
