### ISSUE TITLE
Bazel restarts between CLI and Bazel BSP

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#6094]
### Describe the bug

1. Open Bazel project
2. Wait until everything is imported
3. Run bazel in CLI

### Expected behavior

Bazel is run, but instead we get a message:
```
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
```

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

1.2.1

### Extra context or search terms

bazel restart bsp

**Comment by susliko** [comment]
I'm experiencing this behavior as well

**Comment by tgodzik** [comment]
Trying to fix it in https://github.com/scalameta/metals/pull/6132 after it's merged we should be able to test things out on the nightly.
