### ISSUE TITLE
Too many compilation triggers showing progress that isn't useful

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#6099]
### Describe the bug

When using the new `progress` support added in [this pr](https://github.com/scalameta/metals/pull/6055), which is great btw, you start to notice that there is a lot of compilation requests sent at times that we either don't need to, or really shouldn't be shown to the user. For example in the video below you see me just navigating to a definition in a java file and when I come back to the Scala file a bunch of progress notifications about compiling different modules start coming. If I do the same thing again, it happens again. When navigating around this can become very distracting as a ton of these can be sent for your codebase.

https://github.com/scalameta/metals/assets/13974112/e6657339-c775-43d5-a6cf-86a66deac874

### Expected behavior

I'd expect this to be a bit more restricted. The user obviously wants to know when compilations are happening and maybe that is blocking something from working as expected or as quickly as they want. However, in scenarios like this where all the user is doing is navigating back and forth from sources that have already been fully compiled, they probably don't want to see this.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.2.0+123-450514c7-SNAPSHOT

**Comment by kasiaMarek** [comment]
I see what you mean, I'm just not sure how to handle this reasonably.
> So even in that scenario no matter what compilations are triggered?
Yes, every time build target in focus is changed. 
> Could we maybe filter out no-op compilations and not show those?
My guess is that we know it was a no-op **after** the compilation was finished. We could do some delay with the status, so very fast compilations (like no-ops) won't be shown. However, if things get slow on the build server side for whatever reason it might not work.

So far I see the following options:
1. add delay to status, so quick compilations are not shown,
2. don't show compilations triggered by specific actions (like `didFocus`),
3. make to logic of when a compilation should be triggered better.

**Comment by ckipp01** [comment]
> Yes, every time build target in focus is changed.

Gotcha, didn't catch that before, but makes sense.

> add delay to status, so quick compilations are not shown,

No, I don't think this is the way to go. Adding in delays just... make things seem delayed 😆 which they would be.

> don't show compilations triggered by specific actions (like didFocus),

I also don't think this would be a good approach since there are situation (like the very first time you enter a target) that you _would_ want to see that compilations are happening, _since they need to happen_.

> make to logic of when a compilation should be triggered better.

Yea, I'm thinking this should be the path taken. I saw that with realizing that it'll be the trickiest. But again, I think we should look at this as a UX issue and really think about:

1. What information does the user _need_ to know? Let's show it to them
2. What information is just noise? Let's avoid showing this

**Comment by ckipp01** [comment]
So I was playing around with this again today because I noticed in a minimal hello-world scala-cli project I was getting a bunch of duplicates. I've included the LSP logs to show that just opening a hello world scala-cli project, doing nothing at all sends 4 different "Compiling <name>" `$/progress` notifications. The logs are [here](https://gist.github.com/ckipp01/d74593bb8bfecd8377835f5dee383c22).

And the duplicate notification looks like this:

```
[Trace - 00:16:04 PM] Sending notification '$/progress'
Params: {
  "token": "5aef7eb8-421c-4b25-8ad5-fd5842cb6595",
  "value": {
    "kind": "begin",
    "title": "Compiling minimal_f4dd477a3a"
  }
}
```

I'm curious to try and trace these 4 to better understand exactly in that process what is triggering them because it seems a bit excessive to send 4 separate ones for doing nothing but opening a project.

**Comment by tgodzik** [comment]
I think we invoke `compile` just in case in a couple of situations to make sure project is compiled. We might try to not do that, just only check the project is compiling or wait on an ongoing compilation.

As for Bloop we can skip the notification for sure, it's actually checked here https://github.com/scalameta/metals/blob/d0bab7182091123f7bc0e314300b18863a80470e/metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala#L177

Would be awesome to support a separate noop field to make it work across the build tools.

**Comment by tgodzik** [comment]
Fixed in Bloop, need a new release.

**Comment by kasiaMarek** [comment]
Fixed in bloop.
