### ISSUE TITLE
Completions for unimported global symbols

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#61]
Currently, completions only suggest symbols that are available in your active scope. It would be nice if the completions also included symbols that are accessible with an import. LSP CompletionItem has an optional `textEdit` field to support inserting the import on completion

```
 	/**
	 * An edit which is applied to a document when selecting this completion. When an edit is provided the value of
	 * `insertText` is ignored.
	 *
	 * *Note:* The range of the edit must be a single line range and it must contain the position at which completion
	 * has been requested.
	 */
	textEdit?: TextEdit;
```

The Java LSP seems to be taking advantage of this.

<img width="485" alt="screen shot 2017-11-25 at 23 02 39" src="https://user-images.githubusercontent.com/1408093/33235259-cbec2744-d234-11e7-83c0-4f0ebd23a4d8.png">

Complete, and import is inserted
<img width="537" alt="screen shot 2017-11-25 at 23 02 52" src="https://user-images.githubusercontent.com/1408093/33235260-cc083006-d234-11e7-93c4-ebafd6b68b9a.png">

**Comment by gabro** [comment]
Just adding that also the TypeScript LSP does this (and it even handles binpacking :O )

**Comment by olafurpg** [comment]
I actually worked on this feature about a month ago but never got around to complete the PR

![2018-01-11 16 24 45](https://user-images.githubusercontent.com/1408093/36225175-1d461ef4-11ca-11e8-82ed-b4d01b45a560.gif)

The missing piece was that I don't know yet where to insert the import. I was thinking that it might be nice for starters to insert the import in the leading line above the completion. That would allow you to manually place the import where you like. Any thoughts?

**Comment by gabro** [comment]
That's cool!

I would just put it on top of the file, after the last import, similarly to what `addGlobalImport` does.

A future improvement could be adding it to an existing import group if any.

**Comment by olafurpg** [comment]
Metals doesn't support completions anymore. Completions may get added back in the future but for now I think it's best to close completion-related tickets.
