### ISSUE TITLE
LSP references are found incorrectly for dependency symbols

### ISSUE THREAD

**Issue by Z1kkurat** [scalameta/metals#6101]
### Describe the bug

When trying to find LSP references for a library symbol (`sealed abstract class` in particular) from the library sources, it doesn't show some of the usages.  
I wasn't able to figure out a pattern, sometimes it shows usages only in one module of a multi-module build; sometimes it shows only a part of usages inside the same module. It seems to be affecting multi-module builds only, though I wasn't able to confirm that. 

Steps to reproduce:  
1. Checkout https://github.com/Z1kkurat/find-references-metals-repro
2. Go to either `Mod1.scala` or `Mod2.scala`
3. Use `Go to definition` on `Decision` symbol (doesn't matter if used on an import or usage line), go to the definition in the library sources
4. Try to find references of the symbol `com.evolutiongaming.retry.OnError.Decision` from inside of the library sources --  either object or sealed abstract class

Another issue I've noticed that might be related to this one is showing references from the same module only when trying to find references of a library symbol from local sources (not the library sources).
Steps to reproduce
1. the same
2. the same
3. Place the cursor on any of the usages of `Decision` (either import or usage)
4. Try to find references
5. Only references from the same module are shown

### Expected behavior

Three sets of references are returned:
1. Local references from the same dependency file
2. References from Mod1.scala
3. References from Mod2.scala

Actual result: only 1. and 2. are returned

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v.1.2.1

### Extra context or search terms

![Screenshot 2024-02-08 at 15 06 23](https://github.com/scalameta/metals/assets/7479593/1e31ea4b-9e30-4147-b4c7-91d9aca65d43)

**Comment by Z1kkurat** [comment]
Just to be sure, I've also tried it in vscode, outcome is the same.  
![Screenshot 2024-02-08 at 15 26 33](https://github.com/scalameta/metals/assets/7479593/e1891b7a-e3db-4dcc-be8f-3ece03613b84)

**Comment by kasiaMarek** [comment]
Thanks for the report and the reproduction.
