### ISSUE TITLE
Changing class parameters doesnt recompile dependent code

### ISSUE THREAD

**Issue by sake92** [scalameta/metals#6112]
### Describe the bug

I got an interesting error in VSCode+Metals.
Project is using scala 3.3.1 and Mill.
If I add/remove class parameters, the code that is calling it still compiles..

Seems like with 2.13 it works fine, not sure if it is Mill, Metals or Zinc issue.. :/

Repro: https://github.com/sake92/metals-mill-scala3-class-params-repro

### Expected behavior

Code doesnt compile after updating parameters

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

1.2.1

**Comment by kasiaMarek** [comment]
Thanks for the report. I can reproduce that. It's not a metals issue, we only send requests to the build server to compile a specific build target. I can reproduce this with both `bloop` and `mill`, and even if I switch the build tool to be `sbt` so I'd say it's probably a Zinc issue.

**Comment by eed3si9n** [comment]
Not sure if this is the right fix, but changing one line in Scala 3 compiler fixes this - https://github.com/scala/scala3/pull/19911

**Comment by kasiaMarek** [comment]
Closing this as resolved by: https://github.com/scala/scala3/pull/19911
