### ISSUE TITLE
should truncate show type hints when the hint is too long

### ISSUE THREAD

**Issue by doofin** [scalameta/metals#6118]
### Describe the bug

when the hint is too long, show type hints will become visually bad
<img width="980" alt="image" src="https://github.com/scalameta/metals/assets/6041353/32854d80-c0bd-4843-937e-40ff76cfd9b1">

### Expected behavior

truncate show type hints when the hint is too long

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.2.1

```[tasklist]
### Tasks
- [ ] specify a length limit to truncate
```

**Comment by tgodzik** [comment]
Thanks for reporting, but this was already moved to feature requests in https://github.com/scalameta/metals-feature-requests/issues/372
