### ISSUE TITLE
Bazel: false message about non-working code navigation

### ISSUE THREAD

**Issue by susliko** [scalameta/metals#6130]
### Describe the bug

Prerequisites: installed [bazelisk](https://github.com/bazelbuild/bazelisk?tab=readme-ov-file#installation), cloned [reproduction repository](https://github.com/susliko/metals-bazel)

Steps to reproduce:
- open project in editor, accept suggestion to import bazel build
- wait until notification "Code navigation for Bazel projects is not supported yet" pops out. It occurs right after message "2024.02.16 17:14:51 INFO  time: Imported build in 23s" in logs. And it's not the last message in the log: It's followed by some `bazel cquery`, `bazel build` commands
- enter any Scala file and use go to definition to other modules and 3d party dependencies - both cases are functional

Metals Doctor marks semanticdb as not working, but "Show proto semanticdb" command works.

<img width="401" alt="image" src="https://github.com/scalameta/metals/assets/15569000/403bbceb-6bc4-4e88-b42b-b0428e363e8a">

### Expected behavior

If this message is false, it should not appear

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v1.2.2

### Extra context or search terms

bazel

**Comment by tgodzik** [comment]
Thanks for reporting! It seems that we don't get info about semanticdb at all via BSP, which is why you are seeing the false positive warning. We could possibly make this check more lazy, so that it doesn't show up without a reason.

**Comment by susliko** [comment]
One more strange observation: repro project has .bazelversion set to 7.0.2, which is said to be unsupported

> Currently, newest Bazel 7.x.y is not supported by Bazel BSP, so it will also not work with Metals

But with bazel 6.5.0 I can't get build imported at all - only presentation compiler used

**Comment by tgodzik** [comment]
> One more strange observation: repro project has .bazelversion set to 7.0.2, which is said to be unsupported

That's what I thought, but maybe the issue was actually fixed :thinking: 

Do you get any errors with 6.5.0?

**Comment by susliko** [comment]
With 6.5.0 I can't get it working at all (on the same project by the link in issue description) 🤷🏻‍♂️ 
Logs are
```
2024.02.17 16:37:45 INFO  time: Connected to build server in 14s
2024.02.17 16:37:45 INFO  Connected to Build server: bazelbsp v3.1.0-20240207-7439f14-NIGHTLY
2024.02.17 16:37:44 INFO  Invoking:  /usr/local/bin/bazel mod graph --output=json
2024.02.17 16:37:46 INFO  Invoking:  /usr/local/bin/bazel query --output=xml --order_output=no //external:*
2024.02.17 16:37:46 INFO  Task 'Discovering supported external rules' completed in 2s
2024.02.17 16:37:46 INFO  Invoking: CARGO_BAZEL_REPIN=1 /usr/local/bin/bazel build --build_event_binary_file=/var/folders/qq/lx3szpps6m7cntk6v_v12hr80000gq/T/bazel-bsp-binary6009765851870933
386.tmp --bes_outerr_buffer_size=10 --isatty=true --override_repository=bazelbsp_aspect=/path-to-project/.bazelbsp --aspects=@@bazelbsp_aspect//aspects:core.bzl
%bsp_target_info_aspect --output_groups=bsp-target-info-transitive-deps,external-deps-resolve-transitive-deps,rust_analyzer_crate_spec --keep_going --color=yes --build_manual_tests --curses=
no --experimental_google_legacy_api -- //...
2024.02.17 16:37:47 INFO  INFO: Invocation ID: a5b2d02b-143d-44e9-9e9e-5695e5580023
2024.02.17 16:37:47 INFO  Loading:
2024.02.17 16:37:49 INFO  Loading: 0 packages loaded
2024.02.17 16:37:49 INFO  Analyzing: 6 targets (5 packages loaded, 0 targets configured)
2024.02.17 16:37:50 INFO  INFO: Analyzed 6 targets (154 packages loaded, 1155 targets configured).
2024.02.17 16:37:50 INFO  checking cached actions
2024.02.17 16:37:50 INFO  INFO: Found 6 targets...
2024.02.17 16:37:50 INFO  [24 / 273] [Prepa] BazelWorkspaceStatusAction stable-status.txt
2024.02.17 16:37:52 INFO  [326 / 326] checking cached actions
2024.02.17 16:37:52 INFO  INFO: Elapsed time: 5.254s, Critical Path: 0.56s
2024.02.17 16:37:52 INFO  INFO: 1 process: 1 internal.
2024.02.17 16:37:52 INFO  INFO: Build completed successfully, 1 total action
2024.02.17 16:37:52 INFO  INFO: Build Event Protocol files produced successfully.
2024.02.17 16:37:52 INFO  Command completed in 5.3s (exit code 0)
2024.02.17 16:37:52 INFO  Command completed in 5.2s
2024.02.17 16:37:52 INFO  Task 'Building project with aspect' completed in 5.8s
2024.02.17 16:37:52 INFO  Task 'Parsing aspect outputs' completed in 222ms
2024.02.17 16:37:53 INFO  Task 'Saving project to local cache' completed in 483ms
2024.02.17 16:37:53 INFO  time: Imported build in 8.68s
2024.02.17 16:37:57 INFO  time: indexed workspace in 3.96s
2024.02.17 16:37:57 WARN  no build target for: /path-to-project/.metals/.tmp/Main2642511652894798665.scala
2024.02.17 16:37:57 WARN  no build target for: /path-to-project/gogo/src/main/scala/gogo/Gogo.scala
2024.02.17 16:38:01 INFO  no build target found for /path-to-project/gogo/src/main/scala/gogo/Gogo.scala. Using presentation compiler with project's scala-libra
ry version: 3.3.1
Exception in thread "pool-8-thread-1" java.lang.InterruptedException
        at scala.meta.internal.metals.FutureCancelToken.checkCanceled(FutureCancelToken.scala:29)
        at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:243)
        at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:152)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Feb 17, 2024 4:39:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 26
```

**Comment by tgodzik** [comment]
@susliko for 6.5.0 it doesn't currently work if you leave the empty `MODULE.bazel` file since bazel BSP changes the paths it uses in that case. We'll try to fix it in Bazel BSP
