### ISSUE TITLE
Bazel: run and test code lenses are not generated

### ISSUE THREAD

**Issue by susliko** [scalameta/metals#6134]
### Describe the bug

Reproduction steps:
1. Import [reproduction](https://github.com/susliko/metals-bazel) repository
2. Import build automatically
3. There are no code lenses to run main file or test suite

Go to super super method lense is generated, though
<img width="307" alt="image" src="https://github.com/scalameta/metals/assets/15569000/c9b60087-d0e1-4679-aa94-e6800f61e66d">

### Expected behavior

"run" and "test" code lenses are generated for a compiling project

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v1.2.2

### Extra context or search terms

bazel

**Comment by tgodzik** [comment]
That's currently expected since we don't support DAP in Bazel. Run lenses will appear in VS Code, but only because this is being done differently.

This will be fixed by https://github.com/scalameta/metals/issues/5928
