### ISSUE TITLE
Show using in synthetic inlay hints for using parameters

### ISSUE THREAD

**Issue by keynmol** [scalameta/metals#6148]
### Describe the bug

Here's the repro:

```scala
//> using scala 3.3.2

case class Config()

type Appender = Config ?=> String => Unit

inline def line: Config ?=> Appender = ???
def run(using Config) = 
  line("hello")
```

The `x$1` is unfortunate but probably comes from the compiler - there's some bikeshedding to be done in how to name this to avoid confusion.

The fact that it's duplicated seems to be a bug.

![CleanShot 2024-02-21 at 12 04 31](https://github.com/scalameta/metals/assets/1052965/03f35481-ec45-4683-816e-cdb9d5a46944)

### Operating system

None

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.2.2+28-d52180a4-SNAPSHOT

### Extra context or search terms

inlay hints, given, context function, scala 3, using

**Comment by jkciesluk** [comment]
Thanks for reporting!
You're right, this `x$1` name comes from the compiler. We are thinking about changing decorations for implicit arguments to `(using x$1)` which should be a bit cleaner.

I don't think duplication of `x$1` is a bug - we need to apply the contextual parameter twice here (once to `line`, once to `Appender`)
<img width="426" alt="image" src="https://github.com/scalameta/metals/assets/72950514/25fdf11d-1196-4bf8-a3cb-1504bdf11927">

**Comment by jkciesluk** [comment]
fixed in https://github.com/scalameta/metals/pull/6176
