### ISSUE TITLE
Type information of macro is incorrectly formatted (unreadable code)

### ISSUE THREAD

**Issue by hmf** [scalameta/metals#6178]
### Describe the bug

I have the following code snippet in a file:

```scala
package examples.tips_and_tricks

import scala.quoted.*

object MTypes:

  def matchTypeImpl[T: Type](param1: Expr[T])(using Quotes): Expr[String] = 
    import quotes.reflect.*
    Type.of[T] match
      case '[List[f]] => 
        val fr = TypeRepr.of[f]
        Expr(s"Is a List of ${fr.show}")
      case '[Option[f]] => 
        val fr = TypeRepr.of[f]
        Expr(s"Is an Option of ${fr.show}")
      case '[f] => 
        val fr = TypeRepr.of[T]
        Expr(s"Unmatched type: ${fr.show}")

  inline def mirrorFields[T]: List[String] = ${mirrorFieldsImpl[T]}

  def mirrorFieldsImpl[T: Type](using Quotes): Expr[List[String]] =
    
    def rec[A : Type]: List[String] = 
      Type.of[A] match
        case '[field *: fields] =>
          Type.show[field] :: rec[fields]
        case '[EmptyTuple] =>
          Nil
        case _ =>
          quotes.reflect.report.errorAndAbort("Expected known tuple but got: " + Type.show[A])

    Expr(rec)

end MTypes
```

When saved, the integrated Bloop server compiles, and the type information is shown. The type information seems to appear between code text, which makes it unreadable. 

### Expected behavior

I would expect the type information to appear as it does in *"standard"* code. 

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.29.0

### Extra context or search terms

**Metals Java:** 17.0.10 from Private Build located at /usr/lib/jvm/java-17-openjdk-amd64
**Metals Server version:** 1.2.2+48-8ac1f70a-SNAPSHOT

**Comment by hmf** [comment]
Below is a screenshot of what I see:

![Screenshot from 2024-02-29 12-21-13](https://github.com/scalameta/metals/assets/1138178/a63c4573-83c9-4597-b975-1dfc7259810e)

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like we might be getting wrong positions from the compiler.
