### ISSUE TITLE
Named argument completion is prioritized over exact match identifier in scope

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#619]
<img width="706" alt="Screenshot 2019-04-02 at 14 34 42" src="https://user-images.githubusercontent.com/1408093/55402745-79c3ce00-5554-11e9-91c9-1dfb0b86fcb8.png">

I expected the local variable `argument`  to be placed above the named `argument =` item because the variable has exactly the same name as the parameter.

**Comment by tgodzik** [comment]
I will take a look here
