### ISSUE TITLE
Code completion fails inside macro-annotated class/object

### ISSUE THREAD

**Issue by shadaj** [scalameta/metals#622]
**Describe the bug**
Requesting code completions inside macro-annotated (via Macro Paradise) classes and objects fails, giving just the default VS Code completions.

**To Reproduce**
1. Import https://github.com/shadaj/slinky
2. Open `ReactAnnotatedComponentTest.scala`
3. Go inside any of the macro-annotated classes and try to code complete
4. See language server fail to generate completions

**Expected behavior**
Ideally, the language server could provide full code completions inside annotated classes/objects. However, just ignoring the annotation when completing inside the class/object would go a long way, at least for Slinky applications where code inside rarely depends on what the annotation generates.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: d8f03672-SNAPSHOT

**Comment by olafurpg** [comment]
Thanks for reporting! I'm able to reproduce.

We already automatically restart the presentation compiler when macroparadise crashes, which makes it almost work correctly in source files with macro annotations at the price of a ~100-200ms penalty on every completion. It seems this approach doesn't help when the cursor is inside the expanded body.

I'm investigating what we can do, worst case we disable macroparadise and claim it's not possible to support in the current open file. Note that completions will still pick up expanded members from other source files.

**Comment by olafurpg** [comment]
We already disable all compiler plugins excluding macroparadise, kind-project and better-monadic-for. I can live with removing macroparadise from the list if it provides a more reliable experience, but it would mean typechecking for hover/completions/signatureHelp will be broken for code that relies on expanded macro annotations in the current open file.

**Comment by olafurpg** [comment]
After investigating I'm leaning towards always disabling macroparadise. My theory why completions don't work inside the expanded body is because macroparadise doesn't work with the `-Ymacro-expand:discard` setting. When trying to locate the smallest enclosing tree at the completion position, we traverse the macro expanded code (which has incorrect positions) instead of the original tree from the parser.
