### ISSUE TITLE
Metals does not infer concrete type of path dependent types

### ISSUE THREAD

**Issue by pityka** [scalameta/metals#6230]
### Describe the bug

In this snippet the identifier `y` in the lambda has type  `A{type T = Int}` as verified by the compiler if type ascription is present. However if type ascription is not present, then metals infers it to `A{type T = x.T }`. 
``` scala
//> using scala 3.4.0
object Obj {
  trait A { self =>
    type T
    def fun(
        body: A { type T = self.T } => Unit
    ) =
      ()
  }
  val x: A { type T = Int } = ???

  // hover shows A{type T = x.T }
  x.fun { y =>
    y
    ()
  }
  // compiler infers as A of T = Int
  x.fun { (y:A{type T = Int}) =>
    y
    ()
  }

}
```

### Expected behavior

Metals infers the same type as the compiler.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.2.2

**Comment by pityka** [comment]
After some thoughts and discussion on the scala discord, I am unsure whether there is an issue here. One can argue that the type of `y` is `A{type T = x.T }` which is equivalent to `A{type T = Int}`. 

Auto-complete for e.g. extension methods do work in an extended example:
![image](https://github.com/scalameta/metals/assets/106101/f4628c8e-0447-48dd-87b9-65935baf6588)

**Comment by tgodzik** [comment]
Looks like this is an issue in the compiler, mentioned by @rochala

**Comment by pityka** [comment]
I found a simpler case.
In the line `val z = x.a`, if I hover on 'z' then it shows the type as `x.T`, if I hover on 'a' then it shows the type as `Int`.
~~~ scala
//> using scala 3.4.0
object Obj {
  trait A { self =>
    type T
    def a  : T = ???

  }
 
  val x: A { type T = Int } = ???

  val z = x.a


}

~~~

**Comment by kasiaMarek** [comment]
Hi, @pityka, sorry for nudging but are you still planning to continue your work on this issue or would you rather someone took over?

**Comment by pityka** [comment]
I do plan, i did not forget. Sorry I was distracted. As this is hobby I can not commit for a deadline so it is also fine if somebody else finishes if you find bandwidth and need it before I get to it. On 25 Apr 2024, at 09:01, Katarzyna Marek ***@***.***> wrote:﻿
Hi, @pityka, sorry for nudging but are you still planning to continue your work on this issue or would you rather someone took over?

**Comment by kasiaMarek** [comment]
No worries, take your time, I'm just making sure it's not forgotten about 😄
