### ISSUE TITLE
Fatal invariant violated with Scala CLI v1.2.1 & Bloop `1.5.16-sc-1`

### ISSUE THREAD

**Issue by Gedochao** [scalameta/metals#6271]
A simple hello-world project with Scala CLI v1.2.1 seems having Bloop failures.
```scala
@main def main = println("Hello, world!")
```
this results in
```markdown
error id: 36kpDh2KIxQlQpHPL7NwvQ==
### Bloop error:

Fatal invariant violated: `reportEndCompilation` was called before `processEndCompilation`
#### Short summary: 

Fatal invariant violated: `reportEndCompilation` was called before `processEndCompilation`
```
![image](https://github.com/scalameta/metals/assets/18601388/eb8c280a-c53d-4941-b252-af27a14359bd)

### Expected behaviour:
Doctor shouldn't raise any errors in this case.

### Known workarounds
Reverting to the previous version of `bloop-core` seems to solve the issue.
```bash
scala-cli clean .
scala-cli --power bloop exit
scala-cli setup-ide . --bloop-version 1.5.12-sc-1
```

**Operating system:**
Mac OS X

**Java version:**
17.0.9

**Editor/extension:**
Visual Studio Code v1.87.2

**Metals version:**
1.2.2+103-89c0109a-SNAPSHOT

### Workspace information:
 - **Scala versions:** 3.4.1
 - **Build tools:** 0. scala-cli
 - **Build servers:**
    0. scala-cli v1.2.1

**Comment by Gedochao** [comment]
Tracked on Scala CLI's side in https://github.com/VirtusLab/scala-cli/issues/2829

**Comment by joan38** [comment]
Get the same here

**Comment by tgodzik** [comment]
We wanted to get the release a bugfix version before the weekend, but there was a small issue with the tests. We'll release this week.
