### ISSUE TITLE
Provide override def completions on "override" and "def" keywords

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#631]
Currently, you can override members from the superclass by writing `def <COMPLETE>`

<img width="762" alt="Screenshot 2019-04-04 at 08 38 09" src="https://user-images.githubusercontent.com/1408093/55534559-0a192480-56b5-11e9-8b48-9e292743679f.png">

However, typing `override` or `def` does not trigger those completions

<img width="762" alt="Screenshot 2019-04-04 at 08 38 42" src="https://user-images.githubusercontent.com/1408093/55534585-1bfac780-56b5-11e9-89b4-9dd687c624c6.png">

It would be nice if users could type `overri<COMPLETE>` to trigger the override def completions.

PS, @ayoub-benali, this could also work around the `textEdit` limitation in Sublime Text.

**Comment by gabro** [comment]
I do this all the time and it would be 👏, especially when you want to use `override` explicitly, which makes the path to a useful completion longer

**Comment by olafurpg** [comment]
A good place to start would be here https://github.com/scalameta/metals/blob/a306b24244524ee18908ff1adc4fc886829c2dcd/mtags/src/main/scala/scala/meta/internal/pc/Completions.scala#L465-L469 

We are missing a case that handles the chain `List(Ident("override"), Template, ...)`

**Comment by tgodzik** [comment]
I''ll take look
