### ISSUE TITLE
Semantic highlighting not working with extension methods (Scala 3.3.3)

### ISSUE THREAD

**Issue by DLakomy** [scalameta/metals#6310]
### Describe the bug

Minimal reproducible case:
```scala
extension (s: String)
  def extMethod(i: Int) = i

@main def hello(): Unit =
  // Scala 3.3.3 - extMethod is not highlighted (appears as a grey text)
  // Scala 3.4.1 - extMethod is highlighted (expected behaviour)
  "aqq".extMethod(3)
```
![extMethod](https://github.com/scalameta/metals/assets/12951400/e451b0cb-cbb0-4207-8155-d2254c2dacf8)

### Expected behavior

An extension method should be correctly highlighted as a method.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.2.2

### Extra context or search terms

VS Code version: 1.88.1
Build server: Bloop v1.5.15

**Comment by kasiaMarek** [comment]
Thanks for the report. This seems to be already fixed on the most recent snapshot and a release is on the way :)

![Screenshot 2024-04-15 at 17 42 00](https://github.com/scalameta/metals/assets/26606662/cd9c6476-00c2-4462-ab08-f51d41b4be28)
![Screenshot 2024-04-15 at 17 43 25](https://github.com/scalameta/metals/assets/26606662/d7ebdad1-7c4c-4dd4-95be-69a182bb7c01)
