### ISSUE TITLE
hover types fails with type alias

### ISSUE THREAD

**Issue by andyczerwonka** [scalameta/metals#6315]
### Describe the bug

If I have a type alias, e.g. 
```scala
type SessionEitherT[T] = EitherT[Future, SessionError, T]
``` 
and I have a method that returns that type alias 

```scala
  private def loadCachedReadyPredictor(
      predictorId: PredictorId,
      version: EntityVersionInput,
      predictorClient: PredictorClient,
      acl: AccessControlSession,
      ctx: OrionContext
  ): SessionEitherT[LoadedPredictor] = { ...
```

if I use that method is a for comp, e.g.

```scala
val result = for {
      loadedPredictor <- loadCachedReadyPredictor(predictorId, version, predictorClient, acl, ctx)
...
```

Hovering over `loadedPredictor` does not show the type. If I change the return value to not use the type alias, it works.

### Expected behavior

I expect the hover to work in all cases

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

1.3.0

**Comment by kasiaMarek** [comment]
Thanks for the report. Which Scala version are you using?

Side note: if you are using `VS Code`, you can click on `Open a GitHub issue` in the help and feedback tab, and this will collect some of the information about your workspace for you.

**Comment by andyczerwonka** [comment]
@kasiaMarek 2.13.12

The `Open a Github Issue` fails for me. 
![image](https://github.com/scalameta/metals/assets/138898/94bb7ad8-89a4-4c5a-97d7-19890225894c)

**Comment by andyczerwonka** [comment]
I was able to generate the reports.
[reports.zip](https://github.com/scalameta/metals/files/15018019/reports.zip)

**Comment by kasiaMarek** [comment]
Are you able to reproduce it on a self-contained example? I tried doing more or less what you have in the example and it seems to work for me.
![Screenshot 2024-04-22 at 07 50 06](https://github.com/scalameta/metals/assets/26606662/b370c2fe-dd21-4a29-ab1b-ebdcf3db7a6f)
