### ISSUE TITLE
"Missing valid Bloop build" when opening existing project for the first time

### ISSUE THREAD

**Issue by ghostbuster91** [scalameta/metals#6346]
### Describe the bug

When trying to open an existing project for the first time metals fails with the following error:
```
Missing valid Bloop build in /home/kghost/workspace/demos/.bloop.

  1. Did you run bloop outside of the working directory of your build?
     If so, change your current directory or point directly to your `.bloop` directory via `--config-dir`.

  2. Did you forget to generate configuration files for your build?
     Check the installation instructions https://scalacenter.github.io/bloop/setup
    
```

This was not happening on 1.2.1 
Tested both with neovim and vs-code.

If I run manually `sbt bloopInstall` and then open the project, everything works fine and there is no such error. 

[Screencast from 2024-04-25 14-08-14.webm](https://github.com/scalameta/metals/assets/5662622/17f928db-40f6-4a63-9db1-03ee32fa346b)

### Expected behavior

I would expect metals to detect that there is no `.bloop` directory and ask if it should import the project as it was before.

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.3.0

### Extra context or search terms

bloop

**Comment by ghostbuster91** [comment]
> It looks like it started Bloop without asking to import the build

Correct.

> Is it happening in more projects for you?

It happened in a commercial project and then I setup a new small project and it happened also there. So by now I am pretty confident that it will happen in every project.

> I can't reproduce it currently when opening a new workspace

Hmm that's not good :upside_down_face:

**Comment by tgodzik** [comment]
We did change some things related to that, so this might be an actual issue, but I wonder why it happens for you. Did you try any of the new settings that come with 1.3.0?

**Comment by ghostbuster91** [comment]
I don't think so, I only updated metals version. No changes besides that.

**Comment by ghostbuster91** [comment]
@tgodzik what bloop version do you use?

I have:
```
bloop v1.5.17

Using Scala v2.12.19 and Zinc v1.9.6
Running on Java JDK v19.0.2 (/nix/store/6375rn8kiq9pn4pgdkdiqgvg8b0gdycy-openjdk-19.0.2+7/lib/openjdk)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center and the community.
```

**Comment by tgodzik** [comment]
I don't think it's related to Bloop. It's correctly saying that there is no targets because nothing was imported yet.

**Comment by tgodzik** [comment]
> After upgrading to 1.5.17 I did rm -rf .bloop .metals .sbt **/target .bsp in the project directory and also killed all jvm apps (including old bloop) thinking that this will be sufficient.

You shouldn't need to do any of that, though if .bloop existed that would explain why we were not asking to import. It looked like it was already imported. Bloop version change should not be a reason to delete anything.

**Comment by ghostbuster91** [comment]
I see, so it turns out it was because of the precautions I took. Lesson learned :)

**Comment by mullerhai** [comment]
> Thanks for reporting! It looks like it started Bloop without asking to import the build. Is it happening in more projects for you? I can't reproduce it currently when opening a new workspace 🤔

I have meet same error , 
how to detect bloop  process on windows , when  I  use ps -ef |grep bloop  can not find it,but  metals  say  it running

Missing valid Bloop build in E:\code\scala-native-bloop\.bloop.

  1. Did you run bloop outside of the working directory of your build?
     If so, change your current directory or point directly to your `.bloop` directory via `--config-dir`.

  2. Did you forget to generate configuration files for your build?
     Check the installation instructions https://scalacenter.github.io/bloop/setup

**Comment by mullerhai** [comment]
https://github.com/scalacenter/bloop/issues/1197

**Comment by mullerhai** [comment]
https://github.com/scalameta/metals/issues/6346
