### ISSUE TITLE
Broken completion and highlighting in multi-line string interpolation in worksheets

### ISSUE THREAD

**Issue by iusildra** [scalameta/metals#6361]
### Describe the bug

EDIT: worksheets only

When using multi-line string interpolation, things get a bit awkward :)
For instance with
![image](https://github.com/scalameta/metals/assets/64749208/8d7ced67-b7be-43c5-9a56-0d5f6455c99b)

There are no completion suggestions, but compiling is ok as well as go-to definitions 

### Expected behavior

Normal colors & completions :)

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.3.0

### Extra context or search terms

semantic highlighting, multi-line string, string interpolation

**Comment by tgodzik** [comment]
Thanks for reporting! Do you get any any logs or reports in .metals/reports ? It looks like the file is failing to compiling at least partially.

**Comment by iusildra** [comment]
Hey @tgodzik ! Sorry for the delay, I missed your reply :(

No reports appear to be generated and compilation seems fine as expressions defined later are correctly evaluated (and nothing special appear in the logs either)

However, there's one key aspect that I forgot in the issue description (I've edited the comment): it's only the case in worksheets. On regular Scala file it's perfectly fine

**Comment by tgodzik** [comment]
Ach, that's an important piece of information, thanks!
