### ISSUE TITLE
Please support Scala 2.13.14

### ISSUE THREAD

**Issue by SethTisue** [scalameta/metals#6362]
...which is now on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-13-14-release-planning/6581/13

maybe it already works? checking anyway

**Comment by SethTisue** [comment]
just to double check: this auto-closed because #6364 was merged; does something also need to be published...?

**Comment by tgodzik** [comment]
I published the last version beforehand, then we also needed to update it in the nightlies. Anyway, we should be good.

**Comment by jpaju** [comment]
Is the usage of snapshot/nightly versions of Metals be documented somewhere?

**Comment by tgodzik** [comment]
https://scalameta.org/metals/docs/editors/vscode#using-latest-metals-snapshot

But it should also be available on 1.3.0 version.

**Comment by jpaju** [comment]
"it" being the support for 2.13.14 ?

**Comment by tgodzik** [comment]
Yes, that's correct

**Comment by jpaju** [comment]
Here's the output from `metals --version`:

```
metals 1.3.0

# Note:
#   Supported Scala versions:
#     Scala 3: 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.3.1, 3.3.2, 3.3.3
#     Scala 2:
#       2.11.12
#       2.12.19, 2.12.18, 2.12.17, 2.12.16, 2.12.12, 2.12.13, 2.12.14, 2.12.15
#       2.13.13, 2.13.10, 2.13.11, 2.13.12, 2.13.6, 2.13.7, 2.13.8, 2.13.9
```

Do I understand correctly that even though the output above does not include 2.13.14, it should still work?

**Comment by tgodzik** [comment]
Yes, that hasn't been updated because I back published the support.

**Comment by SethTisue** [comment]
Maybe it should say something like "Newer versions may also work, if support was back-published. If in doubt, upgrade Metals."

**Comment by jpaju** [comment]
Probably a silly question but what does back publishing mean here? Do I need to reinstall metals v1.3.0 to get Scala 2.13.14 support? Or does it happen somehow automagically?

**Comment by tgodzik** [comment]
It should happen automatically if you open a project on Scala 2.13.14

@SethTisue there is a PR open to fix it using coursier but was never finished :(

**Comment by jpaju** [comment]
I see. Earlier this week when I tried to use metals v1.3.0 with a project that was updated from 2.13.13 --> 2.13.14, I had issues with metals falsely reporting errors. Now that I tried again, it seems to be working just fine 👍
