### ISSUE TITLE
metals doesn't detect `./gradlew` script in a project with multiple build tools

### ISSUE THREAD

**Issue by gersonsosa** [scalameta/metals#6370]
### Describe the bug

my project uses gradle 7.6.x and it requires "verification-metadata"

by looking at the code here
https://github.com/scalameta/metals/blob/ba7763e0f49c2f2cc6da64c3c1e2dada36454537/metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala#L24-L37

I see a specific version of gradle-bloop is used which results in the gradlew bloopInstall command failing if the verification metadata is not present

the issue happens because the "./gradlew" script is not detected by metals on startup and it attempts to use an embedded one, since the embedded one is based on gradle version 7.5 the gradle-bloop dependency is different than the one in my project (https://repo1.maven.org/maven2/ch/epfl/scala/gradle-bloop_2.13/1.6.1/)

https://github.com/scalameta/metals/blob/ba7763e0f49c2f2cc6da64c3c1e2dada36454537/metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala#L92-L98

I don't see any alternative to fix this rather than passing a custom script in the startup command but that seems unnecessary considering metals attempts to detect it here https://github.com/scalameta/metals/blob/ba7763e0f49c2f2cc6da64c3c1e2dada36454537/metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala#L93-L95

### Expected behavior

Metals detects my gradlew wrapper and use it with the version of bloop already installed

### Operating system

MacOS
### Editor/Extension

Neovim/nvim-metals
### Version of Metals

v1.3.0
### Extra context or search terms

gradle, build tools, gradle-bloop

**Comment by Arthurm1** [comment]
@gersonsosa 

> it exists, when I pass the parameter [gradleScript](https://scalameta.org/metals/docs/editors/user-configuration#gradle-script) as "./gradlew" it executes without a problem

Sorry - I don't have a mac so can't diagnose or test to see why `AbsolutePath#isFile` would possibly fail to detect `gradlew` in the workspace folder.

> I manually added the verification metadata and it seems to work now, it would be awesome if based on the build tool you could get the current dependency version before attempting to use that one since there are technically two versions here the scala 2.12 (if I understand correctly) and the gradle bloop 1.6.1

It's likely only the `1.6.1` part will ever change and not the `2.12` part, i.e. `ch.epfl.scala:gradle-bloop_2.12:+`

**Comment by kasiaMarek** [comment]
It does seem we are looking for `gradlew` in the `workspace` root where we should be looking for it in the `project root`. Do those things differ in your setup @gersonsosa? Meaning is `gradlew` exactly at the top level of your workspace/workspace folder?

**Comment by gersonsosa** [comment]
> It's likely only the 1.6.1 part will ever change and not the 2.12 part, i.e. ch.epfl.scala:gradle-bloop_2.12:+

That's good to know, so this version should also work if my project uses scala 2.13.x?

> Meaning is gradlew exactly at the top level of your workspace/workspace folder?

It seems that's the case, I have a particular setup because there are multiple levels of directories with "build.gradle.kts" files which might be detected as the root but as far as I see the root directory is being detected correctly

I'll try to debug in my local if that's helpful but I'd love some guidance as how to do it with a flag or if I should put some debug lines in the code.

**Comment by Arthurm1** [comment]
> That's good to know, so this version should also work if my project uses scala 2.13.x?

The plugin version is completely separate from whatever version of scala your project is using

**Comment by kasiaMarek** [comment]
@gersonsosa you can check if https://github.com/scalameta/metals/pull/6428 helps with your issue.

**Comment by gersonsosa** [comment]
@kasiaMarek a delayed response here, yes it works now perhaps I had an old version of metals and updating fixed it! thanks
