### ISSUE TITLE
Metals doesn't import build using Maven or Gradle when using `"metals.defaultBspToBuildTool": true`

### ISSUE THREAD

**Issue by carlosedp** [scalameta/metals#6381]
### Describe the bug

I normally use pure Scala projects with Mill so I've set `"metals.defaultBspToBuildTool": true` on VSCode but I noticed on a project I have which has both Maven and Gradle build configs, Metals doesn't import the project with that setting as true.

If I comment the "metals.defaultBspToBuildTool": true line, both Maven and Gradle projects are imported fine.

![image](https://github.com/scalameta/metals/assets/20382/2fce7466-220a-41b1-bbdb-de9284a04c5f)

### Expected behavior

Maven and Gradle projects imported normally.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.0+56

**Comment by kasiaMarek** [comment]
Thanks for the report, it does seem this case is incorrectly handled.

**Comment by carlosedp** [comment]
Thanks for the crazy fast fix!
