### ISSUE TITLE
Limit workspace/symbol to workspace-only sources by default

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#639]
This is a proposal to reduce noise from workspace/symbol results while improving performance for majority of queries.

Currently, workspace/symbol triggers a search in 

- workspace sources: symbols that you have defined locally
- library sources: symbols that are defined in dependencies

Most of the time, I'm only interested in results from workspace sources.
There's a big overhead in computing the results for library sources because we need to write library sources to disk and compute definition line numbers on the fly for all results (even results that you don't click on).

Here is a proposal: search only within workspace sources by default, and library sources when the query either starts or ends with a space character. Examples:

- "Files": workspace
- " Files": library + workspace
- "Files ": library + workspace

We could make workspace-only queries fallback to classpath search in the following cases without compromising noise or performance

- workspace has 0 results
- classpath has exact match ("Files" would include "java.nio.file.Files" as a result). The overhead for exact matching on the classpath is ~5-10ms, which should be manageable.

One concern with this solution is discoverability of "type space to include library dependencies". A proposal by @gabro from an offline discussion, was to include a dummy result that proposes to add a space to include more results.

**Comment by jvican** [comment]
Great proposal, I'm all in.

> One concern with this solution is discoverability of "type space to include library dependencies". A proposal by @gabro from an offline discussion, was to include a dummy result that proposes to add a space to include more results.
  
A dummy result that makes it clear what actions can the user take to get more results is an ideal solution. :+1:

**Comment by gabro** [comment]
Just tried this live (thanks @olafurpg for blowing my mind with VSCode Live Share 😱  ) and the proposed behavior feels very natural:

- if you have matches in the local workspace, show only those results + a dummy result asking to add `;` to search dependencies

- if you have 0 results in local workspace, search dependencies right away

- if you have 0 results in general, just display empty results

**Comment by olafurpg** [comment]
Opened a PR https://github.com/scalameta/metals/pull/642 implementing this proposal.
