### ISSUE TITLE
constant state of 'Indexing'

### ISSUE THREAD

**Issue by andyczerwonka** [scalameta/metals#6418]
### Describe the bug

After the latest upgrade last night, my project is now in a constant state of indexing, with one of my cores pinned at 100%. The new version is unusable to me. I've attached the index error report.

[reports.zip](https://github.com/scalameta/metals/files/15351280/reports.zip)

### Expected behavior

Indexing completes.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

### Extra context or search terms

I'm also noticing that many of my project now report SemanticDB errors, but I'm assuming that's because the indexing is not completing. 
![image](https://github.com/scalameta/metals/assets/138898/f86ed034-bce2-4a37-84d3-0c722e4fa5b3)

**Comment by tgodzik** [comment]
Thanks for reporting! Any chance to get a stack trace of the case where indexing hangs? Would probably make it much easier to figure out

**Comment by andyczerwonka** [comment]
> Thanks for reporting! Any chance to get a stack trace of the case where indexing hangs? Would probably make it much easier to figure out

If you pull in the latest spark-core you will see that it hands on the hadoop client dependency. It's in the [reports.zip](https://github.com/scalameta/metals/files/15351280/reports.zip) I attached.

**Comment by tgodzik** [comment]
Ok, this was interesting. Our issue was caused by hadoop releasing broken sources with:
`public static final String REFERRER_ORIGIN_HOST = "audit.example.org.apache.hadoop.shaded.org.;`
And we couldn't find the end quote.

We assumed that sources released actually compile, which is a reasonable assumption I though. Added a workaround for that possibility.

**Comment by andyczerwonka** [comment]
> We assumed that sources released actually compile, which is a reasonable assumption

💯 There's no way sources should be broken. I'll report that to the project.

**Comment by andyczerwonka** [comment]
Turns out that I was able to get rid of that dependency in my project, so there is to rush to release the fix, at least for me. I think it's a pretty rare occurrence, saying that, it did come in via Spark, which I don't think is that rare.

**Comment by andyczerwonka** [comment]
> I'll report that to the project.

I tried. They're making it too hard to do so. 
![image](https://github.com/scalameta/metals/assets/138898/2f9edfc0-2268-4710-8413-7a00286046f3)

**Comment by tgodzik** [comment]
No worries, I will just merge the workaround and hopefully this should no happen with the next release. Though I think it's worth investigating on their side why this happened. I am pretty sure we are not the only tooling that might use sources.

**Comment by tgodzik** [comment]
We started indexing Java jars, but that should not cause that much of an increase :thinking: 

Any chance to get this as a repro or at least a basic build.sbt with the artifacts? The issue you are experiencing is for sure something different.

**Comment by tgodzik** [comment]
Is the project using a lot of Java deps? Could that explain a difference in indexing? Also this should only be at the start

**Comment by tgodzik** [comment]
No worries, we started to index Java dependencies to for searching dependencies, which is why I asked about it. We might have a bug there

**Comment by tgodzik** [comment]
Sure! Makes sense. I haven't had the chance to look into it yet.
