### ISSUE TITLE
Formatting (i.e. using Scalafmt) is unnecessarily slow

### ISSUE THREAD

**Issue by crt-31** [scalameta/metals#6459]
### Describe the bug

When using VSCode and doing the textDocument/formatting task, it is very slow on our large codebase. It should be super fast as it is when we run scalafmt from commandline.

Doing some investigation, it seems the issue lies on this call where the code is trying to obtain the projectRoot path, but it does a whole lot of (seemingly unecessary) processing like reading the database and determine builtools. In particular, it appears to perform the buildtool.digest() which is pretty slow on our large codebase.
https://github.com/scalameta/metals/blob/b9b8c5b991f053cf54a00ef9a476570987290650/metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala#L1070

### Expected behavior

It seems like the projectRoot (and build tools) should have already been figured out and don't need to be recalculated during a Format routine.

Hopefully this can be fixed soon so we can have super fast formatting. 

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.2.2

**Comment by tgodzik** [comment]
Thanks for reporting! This seems super curious, it should be cached and and not an issue at all. Do you see it being recalculated every time?

**Comment by crt-31** [comment]
This is not fixed. I just tried latest code (as of 6/27/23) and the issue still remains.

**Comment by tgodzik** [comment]
We no longer recalculate build tools when formatting so it should be good, maybe that was not the reason for it being slow then?

**Comment by tgodzik** [comment]
I did another fix, but it would be good to see if what you're seeing is even related here.

**Comment by crt-31** [comment]
Tried your changes, still happening.
I think the problem is that its unecessarily calling the BuildTool.Digest function when it tries to get BuildTool object.

Here's the callstack

**MavenBuildTool.digest**(AbsolutePath): Option (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\builds\MavenBuildTool.scala:61)
BuildTool.digestWithRetry(AbsolutePath,int): Option (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\builds\BuildTool.scala:18)
BuildTool.digestWithRetry$(BuildTool,AbsolutePath,int): Option (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\builds\BuildTool.scala:13)
MavenBuildTool.digestWithRetry(AbsolutePath,int): Option (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\builds\MavenBuildTool.scala:9)
ProjectMetalsLspService.isCompatibleVersion(BuildTool): BuildTool$Verified (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\ProjectMetalsLspService.scala:809)
ProjectMetalsLspService.$anonfun$buildTool$3(ProjectMetalsLspService,BuildTool): Option (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\ProjectMetalsLspService.scala:794)
ProjectMetalsLspService$$Lambda$1497/0x0000000801197988.apply(Object): Object (Unknown Source:-1)
Option.flatMap(Function1): Option (file:\\\C:\Users\user\AppData\Local\Coursier\cache\v1\https\maven.local.com\artifactory\maven2\org\scala-lang\scala-library\2.13.10\scala-library-2.13.10-sources.jar!\scala\Option.scala:283)
ProjectMetalsLspService.$anonfun$buildTool$1(ProjectMetalsLspService,String): Option (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\ProjectMetalsLspService.scala:793)
ProjectMetalsLspService$$Lambda$1495/0x0000000801196630.apply(Object): Object (Unknown Source:-1)
Option.flatMap(Function1): Option (file:\\\C:\Users\user\AppData\Local\Coursier\cache\v1\https\maven.local.com\artifactory\maven2\org\scala-lang\scala-library\2.13.10\scala-library-2.13.10-sources.jar!\scala\Option.scala:283)
ProjectMetalsLspService.**buildTool**(): Option (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\ProjectMetalsLspService.scala:792)
ProjectMetalsLspService.optProjectRoot(): Option (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\ProjectMetalsLspService.scala:439)
MetalsLspService.$anonfun$formatting$1(MetalsLspService,DocumentFormattingParams,CancelToken): Future (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\MetalsLspService.scala:1064)
MetalsLspService$$Lambda$5123/0x000000080198bdf0.apply(Object): Object (Unknown Source:-1)
CancelTokens$.future(Function1,ExecutionContextExecutorService): CompletableFuture (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\CancelTokens.scala:38)
MetalsLspService.formatting(DocumentFormattingParams): CompletableFuture (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\MetalsLspService.scala:1059)
WorkspaceLspService.formatting(DocumentFormattingParams): CompletableFuture (c:\SDKs\metals-main\metals\src\main\scala\scala\meta\internal\metals\WorkspaceLspService.scala:462)

**Comment by tgodzik** [comment]
Ach, good catch! https://github.com/scalameta/metals/pull/6561 should help then

**Comment by tgodzik** [comment]
I will work on a release this week, so do let me know if it doesn't solve your issues

**Comment by crt-31** [comment]
You da man! That seems to have solved that issue.
(Additionally, it seems that Metals is starting up faster, so I don't have to wait as long to start using it.)
