### ISSUE TITLE
Auto-import is not suggested for classes with long name

### ISSUE THREAD

**Issue by brndt** [scalameta/metals#6475]
### Describe the bug

1. Create a new class CreateLatestCommentSubscriber
2. Try to import it in other package
3. Rename class to CreateLatestCommentByItemSubscriber
4. Try to import it in other package
5. Auto-import is not working because of class name length

### Expected behavior

Auto-import should be suggested to classes with long name

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

**Comment by kasiaMarek** [comment]
Thanks for the report, it seems to be offering the auto import correctly for me:
![Screenshot 2024-06-03 at 18 29 27](https://github.com/scalameta/metals/assets/26606662/3e944b82-fd83-4462-95a8-261cfe5c7f92)

Which scala version are you using? Also does the rename cause compile errors?

**Comment by brndt** [comment]
I'm using Scala 3.4.2

Seems like it also depends on packaging length. Can you try to put it to something like
com.scalaFakePackage.test.latestCommentByItem.domain.projection.latestCommentByItemView.subscriber. CreateLatestCommentByItemSubscriber?

**Comment by brndt** [comment]
@kasiaMarek 
I checked it with the latest snapshot of Metals and still can't see auto import suggestions.
For example, `com.randomMetalsTest.app.latestCommentByItem.domain.projection.latestCommentByItemView.subscriber.DeleteLatestCommentByItemViewOnLatestCommentByItemDeleted` is not suggested.
I tried both Scala 3.3.3 and 3.5.0-RC1.

**Comment by kasiaMarek** [comment]
Oh, that is even longer than the other example. I have a theory why that may be and I think I have to adjust how bloom index is built even further. 🤔 Reopening this.
