### ISSUE TITLE
Extract selection as method doesn't infer correct return type

### ISSUE THREAD

**Issue by brndt** [scalameta/metals#6476]
### Describe the bug

1. For instance write `ZIO.succeed(true)` and try to extract it as a method
2. The method is extracted but the return type is not correct and some pieces are not imported

<img width="542" alt="Screenshot 2024-06-03 at 18 14 06" src="https://github.com/scalameta/metals/assets/21007364/77e225f7-4217-48b8-9b45-5f62440d2f5b">

### Expected behavior

The return type should be inferred correctly with all missing stuff imported.

Maybe also it'd be better not to put the return type or at least add this possibility to the preferences. 

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

**Comment by kasiaMarek** [comment]
Self contained reproduction:
```Scala
object O {
  class C
  def foo(i: Int)(implicit o: C) = i
  val o = {
    implicit val c = new C
    foo(2) //extract this as method or val
    ???
  }
}
```
