### ISSUE TITLE
Worksheet doesn't show correct Array Output

### ISSUE THREAD

**Issue by Leon0402** [scalameta/metals#6499]
### Describe the bug

Creating an array in a worksheet, outputs (part) of the object reference instead of the values: 
![image](https://github.com/scalameta/metals/assets/33933142/c2879c76-7d86-45a7-88ed-25c9305cb455)
As you can see with ArrayBuffer the output is as expected, while with fixed arrays object references are shown instead of values. And only a single, the rest is cutt off (hovering doesn't reveal more either).

I'm rather new to scala, but I don't think this is expected. It is certainly not what the REPL does.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

**Comment by tgodzik** [comment]
Thanks for reporting! This one looks like another issue with mdoc.

**Comment by Leon0402** [comment]
I assume it is using the toString method, which yields exactly that result.

**Comment by tgodzik** [comment]
Ach, actually it's a special mechanism, which usually looks a bit better than normal toString, but we seem to have a bug here.

**Comment by tgodzik** [comment]
Ach, actually I think for Scala 3 we use the normal to String and that's the actual toString method. Better to use List in worksheets. 

Take a look at https://scastie.scala-lang.org/msia7oRwQdav11jDrGGVag

**Comment by Leon0402** [comment]
Makes sense, seems like List is preferred over Array in most cases. In the book I use (scala for the impatient) arrays are introduced first and lists mentioned much later, I wonder why.

Nevertheless, it would probably  be still good to fix this case, right? There are probably other cases, where the logic currently fails if it relies on the toString method (Possibly everywhere, where we deal with more classic Java types?).

**Comment by tgodzik** [comment]
> Nevertheless, it would probably be still good to fix this case, right? There are probably other cases, where the logic currently fails if it relies on the toString method (Possibly everywhere, where we deal with more classic Java types?).

I think from the usability standpoint yes, but correctness wise it might not be a perfect solution. If one expects things on the right to be just a `toString` then this will make people think that Arrays are nicely printable, but they're not, they lack a proper toString. Most Java types have a sensible toString, so this is really mostly an issue with Arrays which is the wrapper around the primitive arrays.

The other solution is to use pprint library as for Scala 2, but I was faced with opposition to it as it is more principled for some people to always just use toString. So, overall I am not sure what is best here :/
