### ISSUE TITLE
Worksheet output of previous lines is wrongly updated

### ISSUE THREAD

**Issue by Leon0402** [scalameta/metals#6500]
### Describe the bug

When objects are modified in a worksheet the previous lines are updated. E.g. see here that the output is everywhere the same: 
![image](https://github.com/scalameta/metals/assets/33933142/0fe8f2d1-8db8-4881-bae6-bf4af9041e88)

### Expected behavior

I would expect that each line shows the current state of the object. This is how it is done in intellij: 
![image](https://github.com/scalameta/metals/assets/33933142/8cc6411a-e208-4982-bf1e-50e70c0c0297)

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

**Comment by tgodzik** [comment]
Thanks for reporting! looks like an issue in mdoc, should be easy to reproduce.
