### ISSUE TITLE
Java source indexing looks to indexing has innefficient file I/O

### ISSUE THREAD

**Issue by spangaer** [scalameta/metals#6503]
### Describe the bug

Split from #6418 

```
Metals version: 1.2.2
time: indexed workspace in 29s
```

```
Metals version: 1.3.1
time: indexed workspace in 2m15s
```

After indexing it shows 180 deps, but that's including the SBT deps  (because bloop files gnerated for build; 72 real deps ).

I monitored both metals 1.2.2. and 1.3.1, specifically looking for file events in to my ivy and maven repo's.
| version | file events |
|  --- | ---|
| 1.2.2 | 38k | 
| 1.3.1 | 1.5m | 

What's more then a bit suspicious to me it that  (starting 14:26:30) over a period of 15 seconds it seems to be opening and closing the same file 3k times. Each time navigating the file tree in the process.
![image](https://github.com/scalameta/metals/assets/677147/5b622e8c-56ca-49b0-adf4-b7d3556bd198)

This is just one example it seems to be a recurring phenomenon with (all) other deps. Looks like something is unnecessarily chatty with these files?

### Expected behavior

While I can't make up my mind from browsing the sources of the different meta projects (on GH) and I know I'm freewheeling here, but...

It looks like somehow it's re-opening that jar file (multiple times even) for each source file it contains. (in case of this guava file 636 files)

Ideally once a zipfile is open, the handle should be reused until all files it contains are indexed?

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

**Comment by tgodzik** [comment]
I am not sure how this is possible actually, we only open the jar file system once for each jar:
https://github.com/scalameta/metals/blob/main/mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala#L74

Is it possible that it's just reporting the fact that multiple files are being read? Maybe those additional jars are causing longer indexing times? Any chance to get a list of dependencies you are using, I could put that into a project.

We have 382 dependencies in Metals including Guava and it only takes 26 seconds to index them. Maybe it's an issue with one of our libraries on windows? 

You could potentially add `-Dmetals.statistics=all` and `-Dmetals.loglevel=debug` to server properties to see some more info, though might not be enough.

**Comment by tgodzik** [comment]
Checking my Windows machine yields even faster times with indexing of 15 seconds 😅 

Could it be related to some kind of antivirus?

**Comment by tgodzik** [comment]
> This is the pattern I essentially see for all my libs. It navigates the entire directory tree over and over and over.

Curious, Metals gets a list of source jars and doesn't need to navigate the ivy repository. Are you using Bloop? Or another BSP server? This could also be coursier, but I don't understand why would that happen.

**Comment by tgodzik** [comment]
I am not sure what changed that helped in your case, but I guess we can close now, we can reopen if this happens for you again.
