### ISSUE TITLE
recent upgrade fails to run tests

### ISSUE THREAD

**Issue by andyczerwonka** [scalameta/metals#6525]
### Describe the bug

With the upgrade yesterday to the most recent version, I'm not able to run tests from vscode.

```
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
```

### Expected behavior

Tests should run, or the error should suggest where I can configure the setting.

### Operating system

Other (note only the above 3 are officially supported)

### Editor/Extension

VS Code

### Version of Metals

v1.3.2

**Comment by tgodzik** [comment]
Looks like it's an issue with https://github.com/scalameta/metals/pull/6505 :/  

Do you have any .jvmopts set? We need to have a separate one for tests I guess if this is indeed an issue

**Comment by andyczerwonka** [comment]
Yes, I have `.jvmopts` in my root. What's the workaround?

**Comment by tgodzik** [comment]
> Yes, I have `.jvmopts` in my root. What's the workaround?

Remove it or decrease heap size. Somehow this doesn't work very well for tests. I will filter out -X options in a PR later

**Comment by andyczerwonka** [comment]
@tgodzik I can confirm that removing `.jvmopts` works, but I need the memory for running other things, e.g. sbt, utilities, etc.

**Comment by tgodzik** [comment]
Sorry about that, I am doing fix in https://github.com/scalameta/metals/pull/6526

However, I wonder if we can also figure out why it's failing for you. Could you post the .jvmopts you are using?

**Comment by andyczerwonka** [comment]
Not a show stopper, I'll just move to using `SBT_OPTS` for now and will be fine until the next release. Thanks!!!!

**Comment by tgodzik** [comment]
The PR is merged, you should be able to confirm on the snapshot, but would be great to figure out how the jvmopts were conflicting for the tests

Could you send us you `.jvmopts` file contents?
