### ISSUE TITLE
Show aliased type for singleton completions

### ISSUE THREAD

**Issue by nguyenyou** [scalameta/metals#6540]
Follow up https://github.com/scalameta/metals/pull/6498

I create this issue to list all the improvements about value completions for union types.

## Named args

![image](https://github.com/scalameta/metals/assets/38455472/68ae82dc-8dd4-4624-980d-4ba51b6a9389)

Expectation: support value completions

## Pattern matching

![image](https://github.com/scalameta/metals/assets/38455472/7e6a65bb-64a9-48ed-aee9-e28167c94f12)

Expectation: support value completions

## Map

![image](https://github.com/scalameta/metals/assets/38455472/29f92796-7e8e-4f3c-99e9-1dba3c54654b)

Expectation: support value completions

## List

![image](https://github.com/scalameta/metals/assets/38455472/4d312471-a75c-4fdb-8719-ac0982d66152)

Expectation: I think just show the value for each suggestion item is enough.

cc @kasiaMarek @tgodzik

**Comment by kasiaMarek** [comment]
> Expectation: I think just show the value for each suggestion item is enough.

This part is up for discussion, normally we add the type and it would be an odd inconsistency not to add it. I think the actual problem is that, because of the way that type is extracted, we get it in a dealised form here.

**Comment by nguyenyou** [comment]
HI @kasiaMarek,

I think it makes sense to keep things consistent. Can you change it to show the type name? Like we already have here:

![Screenshot 2024-06-26 at 18 59 09](https://github.com/scalameta/metals/assets/38455472/b6d813a4-1707-4c28-9943-c4c2224e90c2)

**Comment by kasiaMarek** [comment]
> Can you change it to show the type name?

That would be the desirable way to show it. The problem is that I'm extracting the "expected" type from the typed tree, and in the list case it is present in the tree already dealised by the compiler. I'd have to somehow alias it back - probably doable by looking at types in the scope, or come up with a better way to deal with this. Not sure how to do it properly yet.

**Comment by nguyenyou** [comment]
Please help to decide this 😄 I think this is just a nice to have improvement.

**Comment by nguyenyou** [comment]
Closed as completed.
