### ISSUE TITLE
workspace/symbol without ; includes excluded packages

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#658]
**Describe the bug**
Without ;

![image](https://user-images.githubusercontent.com/691940/56075438-12631500-5dc3-11e9-956b-89d382512fdc.png)

(`saltedge` is a package in my workspace)

With ;

![image](https://user-images.githubusercontent.com/691940/56075508-23f8ec80-5dc4-11e9-8237-a4352cf3040a.png)

**To Reproduce**
- Clone https://github.com/gabro/finanzio
- Import build
- Do a workspace/symbol search for "Transaction" 

**Expected behavior**
I only see results from my workspace when I don't include a ;

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.5.0

**Search terms**
workspace, symbol, semicolon

**Comment by gabro** [comment]
This seems to happen in any repo:

- add a dummy `trait Transaction` anywhere
- let metals compile and build its indices
- symbol search for Transaction
- you get a bunch of results from `org.omg.CORBA`, `javax.sql` and similar

This is an example in the Metals repo

![image](https://user-images.githubusercontent.com/691940/56075901-fca51e00-5dc9-11e9-9028-0d833a2d2d4e.png)

It looks like workspace/symbol is not filtering out the "excluded packages" defined at  https://github.com/scalameta/metals/blob/4bc12b7238d73abc9a340ba7b5fee31bfd1b0614/mtags/src/main/scala/scala/meta/internal/metals/CompressedPackageIndex.scala#L24

**Comment by olafurpg** [comment]
Hmm, weird, I am unable to reproduce 🤔 

<img width="674" alt="Screenshot 2019-04-13 at 10 27 16" src="https://user-images.githubusercontent.com/1408093/56076978-e3569e80-5dd6-11e9-8f36-b33e8b2706e8.png">

The relevant code lives in `WorkspaceSearchVisitor`

**Comment by gabro** [comment]
Mm, what can be machine dependent? JDK sources perhaps?

**Comment by gabro** [comment]
FWIW I've also tried to delete the `.metals` dir in the odd chance there was index being cached, and the result is the same.

**Comment by gabro** [comment]
Aha, good news: deleting the `.metals/readonly` dir **and** reloading VSCode fixes it.

This seems an issue due stale files in `.metals/readonly`, probably produced by an older version of Metals.

If someone else runs into the issue, I recommend to:

- delete `.metals/readonly`
- reload the window

**Comment by gabro** [comment]
Ok I found the actual cause: this happens when you also have the Java LS installed.

Steps to reproduce:

- install both Metals and the Java LS
- jump to org.eclipse.lsp4j.SymbolInformation (you can open any file that references it and use go to definition, e.g. `WorkspaceSymbolSlowSuite.scala`)
- do a symbol search for `Transaction`

It's still not clear to me why those symbol are indexed by Metals, but at least that's a clear reproduction

**Comment by olafurpg** [comment]
It looks like the JLS indexes Java sources under `.metals/readonly/**/*.java`, maybe using a file watcher 🤔 I personally disabled the Java LS since it doesn't work so well with sbt builds.
