### ISSUE TITLE
BSP tracing in a quantum state

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#6582]
### Describe the bug

1. Create a new project
2. Import the project in Metals
3. Create the `.metals/bsp.trace.json` file to enable tracing
4. Run the `Metals: Connect to build server` to reconnect and start the tracing

The logs of step 4 are:
```
2024.07.11 14:00:04 INFO  Disconnecting from Bloop session...
2024.07.11 14:00:04 INFO  Shut down connection with build server.
2024.07.11 14:00:04 INFO  Shut down connection with build server.
2024.07.11 14:00:04 INFO  Attempting to connect to the build server...
2024.07.11 14:00:04 INFO  tracing is enabled: example/.metals/bsp.trace.json
2024.07.11 14:00:04 INFO  Attempting to connect to the build server...
2024.07.11 14:00:04 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at example/.metals/bsp.trace.json or /home/piquerez/.cache/metals/bsp.trace.json
2024.07.11 14:00:04 INFO  time: Connected to build server in 57ms
2024.07.11 14:00:04 INFO  Connected to Build server: Bloop v1.5.18
2024.07.11 14:00:06 INFO  time: indexed workspace in 1.19s
```

On line 5 it says that tracing is enabled, but then on line 7 it says that tracing is disabled because the `bsp.trace.json` file does not exist, which seems wrong. There is no logs in `bsp.trace.json`.

### Expected behavior

Tracing should work after `Metals: Connect to build server` if the `.metals/bsp.trace.json` file exists.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.3.2

**Comment by kasiaMarek** [comment]
I can't really reproduce that issue. Did the path get actually printed as `example/.metals/bsp.trace.json` or did you change it manually?

Also, are you using bloop with sbt? For that combo we have two connections, the second one for meta build. So there would be no `bsp.trace.json` for meta build connection, and that may be where line 7 comes from. Though the correct path should be something like `.../project/.metals/bsp.trace.json`

**Comment by adpi2** [comment]
> I can't really reproduce that issue. Did the path get actually printed as example/.metals/bsp.trace.json or did you change it manually?

I changed it manually. The original path is something like `/home/adpi2/projects/example/.metals/bsp.trace.json`.

> Also, are you using bloop with sbt?

I am using sbt build server directly.

**Comment by adpi2** [comment]
I tried again and it's working. Maybe the reproduction is wrong or the bug has been fixed in the last released.
