### ISSUE TITLE
Find references doesn't detect destructuring

### ISSUE THREAD

**Issue by filipwiech** [scalameta/metals#6589]
### Describe the bug

Metals doesn't return references to destructured fields, example:

```scala
case class TestType(<<foo>>: String, bar: Int) // Call "find all references" on a `foo` property.
val test = TestType("abc", 0)

// This reference is found:
val name = test.foo

// These references are not found:
val TestType(foo, bar) = test
val TestType(xyz, _) = test
```

Tested on Scala 2.13.12.

### Expected behavior

Find references detects and returns destructuring usage.

### Operating system

Linux

### Editor/Extension

Other

### Version of Metals

1.3.2+41-c4c1d297-SNAPSHOT

### Extra context or search terms

find all references, destructuring

**Comment by tgodzik** [comment]
Thanks for reporting! The other foo is actually a totally different symbol that is being declared in `(foo, bar)` <- it is completely unrelated.
