### ISSUE TITLE
Compilation in Scala 3.5.0-RC5 gives possibly false errors

### ISSUE THREAD

**Issue by brndt** [scalameta/metals#6627]
### Describe the bug

Tests compilation gives some errors related to macros (the usage of ZLayers of zio) in editor but if you compile it using sbt you won't see any errors.
If I change the version to 3.4.2 errors disappear.

I don't see any errors when checking logs.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.3.4

**Comment by filipwiech** [comment]
I seem to be experiencing a similar issue.

```
"dev.optics" %% "monocle-core"  % "3.2.0" % "test",
"dev.optics" %% "monocle-macro" % "3.2.0" % "test",
"dev.optics" %% "monocle-law"   % "3.2.0" % "test",

import monocle.macros.GenLens

case class Person(name: String, age: Int)

val lens: Lens[Person, String] = GenLens[Person](_.name)
```

SBT builds fine, but Bloop complains:
```
bloop: Found:    Any
Required: monocle.Lens[Person, String]
```

If I hover the cursor over the `GenLens` I get:
```
Expression type:
MkFocus[Person]

Symbol signature:
def apply[A]: MkFocus[A]
```
Which does appear to be correct.

Scala 3.5.0-RC6, Bloop 1.6.0, SBT 1.10.1, Metals 1.3.4+23-c744a47f-SNAPSHOT

**Comment by tgodzik** [comment]
Looks like it's the same issue as https://github.com/scalameta/metals/issues/6628 correct me if I am wrong

**Comment by brndt** [comment]
> Looks like it's the same issue as #6628 correct me if I am wrong

No it's not.
This one is something that you can reproduce without Best Effort compilation and modifying the code.
Just try to build test in the main branch of the repo that I shared with you and you will see some errors in Bloop that are not seen while using sbt.

**Comment by brndt** [comment]
Ok, I didn't know it, I thought it wasn't related to Best Effort.
So in this case yes, you're right to close this issue as duplicated.

**Comment by tgodzik** [comment]
It should easily be fixed by reverting to earlier version of Metals since we do default to false, but somehow it still doesn't work. Switching Bloop version to an earlier one should work instead.

**Comment by tgodzik** [comment]
Looks like restarting the build server also helps, we might be caching it somewhere :thinking: 

Anyway, setting it explicitly works also, so will do that for now and create a new release
