### ISSUE TITLE
Using textDocument/codeAction to get code actions seems to produce extra error messages about organizing imports

### ISSUE THREAD

**Issue by mprihoda** [scalameta/metals#6629]
### Describe the bug

In the last at least two releases, I observe a warning message popping up every time I change the location in a Scala file, if the code cannot be compiled at the moment, which is most of the time.

<img width="475" alt="Snímek obrazovky 2024-07-25 v 19 24 50" src="https://github.com/user-attachments/assets/561f08de-8910-429d-b66f-55e0d0744009">

I suspected some attempts to organize imports from the editor, but inspecting the log seems to indicate that the culprit being Metals itself, the following set of messages follows every textDocument/codeAction query:

```jsonc
// Send:
{"jsonrpc":"2.0","id":114,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/mph/Devel/commercial/e-bs/personalni-databaze-mdr/server/src/main/scala/mdr/pdb/server/api/PDBApiEndpoints.scala"},"range":{"start":{"line":15,"character":6},"end":{"line":15,"character":6}},"context":{"diagnostics":[],"only":["","quickfix","refactor","refactor.extract","source"]}}}
// Receive:
{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":2,"message":"Fix PDBApiEndpoints.scala before trying to organize your imports"}}
// Receive:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2024.07.25 19:19:05 INFO  Can not organize imports if file has error"}}
// Receive:
{"jsonrpc":"2.0","id":114,"result":[{"title":"Rewrite in to braces","kind":"refactor.rewrite","diagnostics":[],"edit":{"changes":{"file:///Users/mph/Devel/commercial/e-bs/personalni-databaze-mdr/server/src/main/scala/mdr/pdb/server/api/PDBApiEndpoints.scala":[{"range":{"start":{"line":13,"character":9},"end":{"line":13,"character":10}},"newText":"{"},{"range":{"start":{"line":15,"character":6},"end":{"line":15,"character":7}},"newText":"}"}]}}},{"title":"Convert \u0027in(...)\u0027 to named arguments","kind":"refactor.rewrite","diagnostics":[],"edit":{"changes":{}},"command":{"title":"Convert positional arguments to named ones","command":"convert-to-named-arguments","arguments":[{"position":{"textDocument":{"uri":"file:///Users/mph/Devel/commercial/e-bs/personalni-databaze-mdr/server/src/main/scala/mdr/pdb/server/api/PDBApiEndpoints.scala"},"position":{"line":15,"character":7}},"argIndices":[0]}]}}]}
```

From what I gather, the textDocument/codeAction should only prompt for available actions, but as a side effect it seems to produce the warning and log messages.

### Expected behavior

I would expect not to receive a warning when querying for available actions, only if I actually want to perform the source.organizeImports action.

### Operating system

macOS

### Editor/Extension

Other

### Version of Metals

v1.3.4

**Comment by filipwiech** [comment]
See the related #6595. :+1:

**Comment by mprihoda** [comment]
Thank you for pointing out, closing this issue as it is already addressed. 👍
