### ISSUE TITLE
No scala-cli artifact completions for `test.dep`

### ISSUE THREAD

**Issue by susliko** [scalameta/metals#6700]
### Describe the bug

No completions received while typing dependencies for the test scope

Steps to reproduce:
1. Ensure there are completions while typing `//> using dep ...some dep here...`
2. Try typing `//> using test.dep ...some dep here....`

### Expected behavior

Artifact completion is working regardless of the dependency scope.

### Operating system

Linux

### Editor/Extension

Nvim/Vim (other)

### Version of Metals

v1.3.5

**Comment by kasiaMarek** [comment]
Thanks for the report.
