### ISSUE TITLE
Clean builds after switching CLI and Bazel BSP since Bazel 7.x

### ISSUE THREAD

**Issue by susliko** [scalameta/metals#6713]
### Describe the bug

Hi! 🖖🏻 I don't know whether it's a Metals or bazel-bsp issue. I'll start here hoping to get some feedback.

Metals works both with Bazel 6.x and 7.x, judging by the Doctor output.

However, with 7.x, command line executions of Bazel commands interfere with editor-executed commands through bazel-bsp, resulting in clean (hence, slow) builds on every switch.

Meanwhile it doesn't look similar to https://github.com/scalameta/metals/issues/6094 - there are no warnings on bazel restarts.

I've created a reproduction repo: https://github.com/susliko/bazel-restarts-issue

### Expected behavior

Build cache is shared between invocations of bazel-commands via bazel-bsp and via command line and switching is seamless.

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v1.3.5

**Comment by susliko** [comment]
Mezel (https://github.com/ValdemarGr/mezel) doesn't seem to have this issue.
Probably, because of this:
```
Build isolation, uses a custom --output_base to avoid destroying your build cache.
```

**Comment by tgodzik** [comment]
Is it possible that JAVA_HOME set inside metals is different from the one inside the terminal?

Everything seems to work ok for me with your example. It's also possible that PATH differs, either of those two might cause the issue.

Of course, using Mezel is also an option, I hoped Bazel BSP would be more stable since it has a big company behind it, but it might be worth adding to docs as an alternative or even set it in Metals as a default alternative

**Comment by susliko** [comment]
It's unlikely that PATH or JAVA_HOME could differ in metals and terminal since both are started from nvim process. But is there a way to make Metals print env variables to logs upon startup?

> Of course, using Mezel is also an option, I hoped Bazel BSP would be more stable since it has a big company behind it, but it might be worth adding to docs as an alternative or even set it in Metals as a default alternative

There's certainly something to polish in Mezel, but it's defenitely worth to mention it as an alternative in Bazel section of Metals documentation. It is being developed and tested with Scala support in mind and maintainer (@ValdemarGr) is very responsive and helpful.

**Comment by tgodzik** [comment]
> But is there a way to make Metals print env variables to logs upon startup?

Unfortunately no, but JAVA_HOME will be the same as printed in the logs. Would be great if bazel had an option to print that actually :thinking:

**Comment by tgodzik** [comment]
Probably https://bazel.build/reference/command-line-reference#flag--incompatible_strict_action_env would be useful here.

**Comment by susliko** [comment]
> Probably https://bazel.build/reference/command-line-reference#flag--incompatible_strict_action_env would be useful here.

Ah, yes. Adding `build --incompatible_strict_action_env=true` to `.bazelrc` helps.

I remember that I already encountered this issue with Idea and its terminal but forgot that fix.
Thanks!

Maybe this option is worth a mention in the docs.
