### ISSUE TITLE
Quick fix "Import" does not work for modifier private with access qualifier

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#6732]
### Discussed in https://github.com/scalameta/metals/discussions/6730

<div type='discussions-op-text'>

<sup>Originally posted by **LeUser111** August 28, 2024</sup>
Hi there,

I'm making massive use of access modifiers in combination with access qualifiers (see [Scala 2 language specification](https://scala-lang.org/files/archive/spec/2.13/05-classes-and-objects.html#modifiers)) throughout my code bases.

Unfortunately, metals does not suggest imports for members with modifier _private_ and matching qualifier.

A simple example would be: 

```scala
package com.airhack.a

private[airhack] object A {
  
    val hello = "hello"

}
```

```scala
package com.airhack.b

object B {
  
    // A is missing the import, metals doesn't suggest importing A, even though the import would be valid
    val hello = A.hello

}
```

The import quick fix works perfectly fine when _A_ is public. Right now this means that I have to write a lot of imports by hand. It would be really nice if metals could suggest the imports automatically!

I'm not sure if this would be a bug or feature request and whether metals is even the right project - it might be an upstream issue.

I'd be grateful if someone could point me in the right direction!
</div>

**Comment by masonedmison** [comment]
Has anyone started looking at this one yet? If not, I'd be happy to take a look at this.

**Comment by tgodzik** [comment]
I don't think anyone had the time, so you're welcome to take a look.

Some places to take a look at:
- https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala

This one is used for the auto imports code action.

- https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-2/scala/meta/internal/pc/WorkspaceSymbolSearch.scala#L152

We used this one to get members to import found from indexing via metals.

- https://github.com/scalameta/metals/blob/f3657def9a69b77a43e9cef8d5f51273c005674b/metals/src/main/scala/scala/meta/internal/metals/WorkspaceSearchVisitor.scala#L29

Here we provide the potential matches

**Comment by masonedmison** [comment]
Thanks @tgodzik! I believe I've [found in the code](https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-2/scala/meta/internal/pc/WorkspaceSymbolSearch.scala#L188) where symbols are being filtered by visibility. It looks like something similar is done in the [scala 3](https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-3/scala/meta/internal/pc/CompilerSearchVisitor.scala#L30) implementation.

I'll have to have a deeper look into the scala reflection documentation (I can start with scala 2 if that's OK with you) to get a better sense on how to get the "access" modifier from a `Symbol`.

**Comment by tgodzik** [comment]
Actually, this might be as simple as doing `sym.isPublic || sym.hasAccessBoundary`, from what I see we do check accessibility anyway later on.

You could just try that with some tests for good measure.

**Comment by masonedmison** [comment]
@tgodzik I made a bit of progress on this and opened up a [draft PR](https://github.com/scalameta/metals/pull/6765). If we like this approach, it should be fairly easy to take a similar approach for the Scala 3 `AutoImportsProvider` implementation.
