### ISSUE TITLE
Prune repository

### ISSUE THREAD

**Issue by gonsolo** [scalameta/metals#6783]
### Describe the bug

Cloning metals requires 1.6GB for a 21MB repository.
Please prune the history! There is no need for dozens of "search-index.json" blobs.

### Expected behavior

Quick clone of about 50MB would be acceptable.
And yes, I know I could use "--depth" but this makes it hard sometimes to work with the history.

### Operating system

Linux

### Editor/Extension

Other

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! I don't think it's possible to prune a remote github repository, I couldn't find a way to do it

**Comment by gonsolo** [comment]
You can always prune your local repository and force push, but that's probably too invasive.
Maybe a new repository when 2.0 comes out.

**Comment by tgodzik** [comment]
That might be a long way off, but if anyone figures how to do it less invasive do let me know. For now the recommended way to limit downloaded data is to use --depth

**Comment by tanishiking** [comment]
Since every blob belongs to `gh-pages` branch, maybe we can create a separate repo for the document, and remove gh-pages branch?

**Comment by tgodzik** [comment]
that might be an option yeah, though I am not sure I will be able to sensibly do that. We would need to redirect scalameta/metals and I think I don't have access to it
