### ISSUE TITLE
Implement textDocument/rename

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#679]
The rename request is sent from the client to the server to perform a workspace-wide rename of a symbol. https://microsoft.github.io/language-server-protocol/specification#textDocument_rename

Some challenges:
-  overridden methods, should we rename only the focused symbol or all overrides + their implementations? IntelliJ lets you choose the behavior but this UI is not available in LSP (although we can optionally implement it for VS Code).
- broken code, should we require the sources to compile successfully? I vote for always renaming even in the presence of broken code.

**Comment by olafurpg** [comment]
Blocked by fix in https://github.com/scalameta/scalameta/pull/1859 to handle renaming of overridden methods in anonymous classes

**Comment by olafurpg** [comment]
Up for debate: should "rename symbol" work for symbols that are not defined in the workspace? For example, should it be possible to rename references to a class defined in library dependencies? In IntelliJ, the symbol must be defined in the workspace but sometimes this limitation might be undesirable.

**Comment by gabro** [comment]
@olafurpg I'm a bit puzzled by the use case?

If the symbol is defined in a dependency, wouldn't renaming references to that symbol just break the usage site? 
I'm sure I'm missing something, can you provide an example?

**Comment by olafurpg** [comment]
I think you are right, we should restrict rename for symbols that are defined in the workspace.

**Comment by cb372** [comment]
Is anyone currently working on this?

Just as an anecdotal data point, I just watched a colleague try VS Code + Metals for the first time, discover that they couldn't rename symbols, and switch back to IntelliJ within 5 minutes 😢

**Comment by tgodzik** [comment]
@olafurpg started to work on some necessary work with `goto implementation`, but not sure when he will be able to work on this. We will most likely plan something after he gets back.
