### ISSUE TITLE
Scala 3: rename broken in several ways

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#6795]
### Describe the bug

I can split these up into separate issues if necessary, but they seem related so I'll start by posting them together.

Example code:

```scala
object main {
  def myMethod(
      s1: String,
      s2: String,
      s3: String,
      s4: String,
  ) = s1 ++ s2 ++ s3 ++ s4

  val word1 = "hello"
  val word2 = "world"

  myMethod(
    word1,
    word2,
    s3 = word1,
    s4 = word2,
  )
}
```

## Issue 1: renaming a val at its definition site doesn't get reflected in function parameters.

To reproduce:

1. Put cursor here: `val wo<CURSOR>rd1 = "hello"`
2. Rename to e.g. `aaaaaa`

Actual result:

```scala
val aaaaaa = "hello"
val word2 = "world"

myMethod(
  word1,
  word2,
  s3 = word1,
  s4 = word2,
)
```

Expected:

```scala
val aaaaaa = "hello"
val word2 = "world"

myMethod(
  aaaaaa,
  word2,
  s3 = aaaaaa,
  s4 = word2,
)
```

## Issue 3: renaming a final parameter with a trailing comma thinks the comma is part of the name (and doesn't update anything)

To reproduce:

1. Put cursor here: `s4 = wo<CURSOR>rd2,`
2. Run a rename. The pop-up will show `word2,` as the "old" name
3. Rename to anything
4. Notice nothing happening

Expected behavior: the comma isn't shown as part of the old name. Renaming in that position works (both the definition and the call-site).

Relevant LSP trace:

```json
[Trace - 04:40:27 PM] Sending response 'textDocument/prepareRename - (22)'. Processing request took 1054ms
Result: {
  "start": {
    "line": 15,
    "character": 9
  },
  "end": {
    "line": 15,
    "character": 15
  }
}
```

### Expected behavior

Described above in each case.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! What is your scala version? I can only reproduce the last issue? Was there any warnings? Was the code compiled?

**Comment by kubukoz** [comment]
hmm I'm on Scala 3.5.1. The assumption was that the code had been compiled already, no warnings.

I can now say that renaming `word1` seems to work correctly in all the locations, which would mean issues 1&2 are not there.

With `word2`, if I rename it at the definition, it only updates the first parameter in the call:

```scala
  val aaaaa = "world"

  myMethod(
    word1,
    aaaaa,
    s3 = word1,
    s4 = word2,
  )
```

If I rename it at the first use site, the result is the same.

However! If I rename `word2` in an unsaved state, it updates the call-sites correctly.

**Comment by tgodzik** [comment]
> However! If I rename word2 in an unsaved state, it updates the call-sites correctly.

Might be the algorithm we use for finding moved symbols. The issue with the coma disappears then. (or in some cases the presentation compiler can be used, which also doesn't have that issue)

Anyway, I raised a PR with a fix for that particular situation.
