### ISSUE TITLE
Multistring with `stripMargin` misaligned when pasting into last line

### ISSUE THREAD

**Issue by soronpo** [scalameta/metals#6798]
### Describe the bug

1. Start with this code:
```scala
val x =
  s"""|Hello
      |Good""".stripMargin
```
2. Paste `bye` after `Good`. You will get
```scala
val x =
  s"""|Hello
                |Goodbye""".stripMargin
```

Here is a recording of how it looks like on my machine:
![persistant](https://github.com/user-attachments/assets/e5171e0f-769d-4908-bf10-0e13d0868345)

### Expected behavior

Alignment should not change

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! It's really tricky to get all the edge cases right :/
