### ISSUE TITLE
Metals doesn't recognize all the new syntax under the experimental:modularity flag

### ISSUE THREAD

**Issue by felher** [scalameta/metals#6800]
### Describe the bug

Given the following small file:

```
trait TypeClass:
  type Self

given Int is TypeClass

def foo[T: {Ordering, TypeClass}]: Unit = ()
```
Metals reports
> abstract givens cannot be anonymous

 for the `given Int is TypeClass` line and reports
> illegal start of declaration

for the `def foo` line, even though
```
    scalacOptions ++= Seq(
      "-source:future",
      "-language:experimental.modularity",
    )
```
are set in build.sbt. It compiles and runs fine in SBT.

### Expected behavior

It should not show any errors

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! I looked at https://dotty.epfl.ch/docs/reference/experimental/modularity.html and it seems that it only adds the `tracked` modifier. Do you have link to the syntax that results in `given Int is TypeClass` ?

**Comment by antonsviridov-src** [comment]
@tgodzik I think modularity + source:future give you https://dotty.epfl.ch/docs/reference/experimental/typeclasses.html

**Comment by felher** [comment]
Yeah, that's right. Both the modularity and the typeclass features are hidden behind the modularity flag. Sorry for the confusion. As @antonsviridov-src  said, it is specified in the "Better Support for Type Classes" document he linked

**Comment by tgodzik** [comment]
Ach, thanks! I will take a look once I am back from holidays circa 07.10
