### ISSUE TITLE
Severe compiler error occurred (StackOverflowError)

### ISSUE THREAD

**Issue by povder** [scalameta/metals#6821]
### Describe the bug

When using the Iron newtype library (https://github.com/Iltotore/iron), when `import io.github.iltotore.iron.*` is present, a "severe compiler error" message is printed to the logs upon trying to trigger autocompletion after typing in a dot. The autocompletion then doesn't work.

I isolated the issue in the following repo: https://github.com/povder/metals-bug-01.

Scala version: 3.5.1

Steps to reproduce:
1. Check out https://github.com/povder/metals-bug-01
2. Import the project
3. Navigate to `Bug.scala`, and in Bug object body type `1.`.

---

Report from the logs:

file://<WORKSPACE>/src/main/scala/bug/Bug.scala
### java.lang.StackOverflowError

occurred in the presentation compiler.

presentation compiler configuration:

action parameters:
offset: 48
uri: file://<WORKSPACE>/src/main/scala/bug/Bug.scala
text:
```scala
package bug

import newtypes.*

object Bug {
 1.@@
}

```

#### Error stacktrace:

```
dotty.tools.dotc.core.TypeApplications$.tryReduce$1(TypeApplications.scala:401)
	dotty.tools.dotc.core.TypeApplications$.appliedTo$extension(TypeApplications.scala:418)
	dotty.tools.dotc.core.TypeApplications$.applyIfParameterized$extension(TypeApplications.scala:444)
	dotty.tools.dotc.core.Types$AppliedType.superType(Types.scala:4658)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:667)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:665)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:667)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:667)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:665)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:667)
....
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:665)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:667)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:667)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:665)
	dotty.tools.dotc.core.Types$Type.isMatchableBound(Types.scala:667)
```
#### Short summary: 

java.lang.StackOverflowError

### Expected behavior

Autocompletion should trigger.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.3.5+143-e6110753-SNAPSHOT

### Extra context or search terms

iron 3.5.1

**Comment by povder** [comment]
The problem still occurs with Metals 1.4.0 and Scala 3.5.2.

Out of curiosity, I checked whether I could reproduce it using Scala 3.6.1. I couldn't.

**Comment by tgodzik** [comment]
Looks like it was fixed inside the compiler then. Let's reopen if this happens in 3.6+ again. The presentation compiler is inside the scala3 repo so this can't anyway be fixed in Metals
