### ISSUE TITLE
"Implement all members" is broken when using braceless syntax

### ISSUE THREAD

**Issue by brndt** [scalameta/metals#6841]
### Describe the bug

1. Create new method in interface
2. Go to the implementation and click "Implement all members"
3. The insertion breaks the code
https://github.com/user-attachments/assets/9f6fe405-2fc1-4bea-8ac1-5da9c2ee2254

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! Could you double check with the newest snapshot version? It seems to work for me at least in the scenario I was testing. If it still doesn't work, could you add the reproduction here? Or at least something that doesn't work for you

**Comment by brndt** [comment]
> Thanks for reporting! Could you double check with the newest snapshot version? It seems to work for me at least in the scenario I was testing. If it still doesn't work, could you add the reproduction here? Or at least something that doesn't work for you
I attached the video in the **Describe the bug** section
It doesn't work with the latest snapshot neither.
