### ISSUE TITLE
Server initialization failed. Metals client: couldn't create connection to server. 

### ISSUE THREAD

**Issue by Enhowww** [scalameta/metals#6847]
### Describe the bug

Today I opened Metals and it asked me to update something. I select ok and the update is complete. And then I turned Metals back on and this happened

### Expected behavior

Metals should start normally

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

I tried releases and pre-releases

### Extra context or search terms

Metals version: 1.3.5+171-b77fedf0-SNAPSHOT
Using coursier located at /home/leh/.metals/cs
Searching for Java on PATH. Found java executable under /usr/bin/java that resolves to /usr/lib/jvm/java-17-openjdk-amd64/bin/java
Using Java Home: /usr/lib/jvm/java-17-openjdk-amd64
Warning: ignoring unhandled -J argument: -J-Xmx1G
Error fetching artifacts:
https://maven.aliyun.com/repository/central/org/scalameta/semanticdb-metap_2.13.15/4.10.2/semanticdb-metap_2.13.15-4.10.2.jar: not found: https://maven.aliyun.com/repository/central/org/scalameta/semanticdb-metap_2.13.15/4.10.2/semanticdb-metap_2.13.15-4.10.2.jar
https://maven.aliyun.com/repository/central/org/scalameta/trees_2.13/4.10.2/trees_2.13-4.10.2.jar: not found: https://maven.aliyun.com/repository/central/org/scalameta/trees_2.13/4.10.2/trees_2.13-4.10.2.jar
https://maven.aliyun.com/repository/central/io/get-coursier/coursier-cache_2.13/2.1.14/coursier-cache_2.13-2.1.14.jar: not found: https://maven.aliyun.com/repository/central/io/get-coursier/coursier-cache_2.13/2.1.14/coursier-cache_2.13-2.1.14.jar
https://maven.aliyun.com/repository/central/io/get-coursier/coursier-core_2.13/2.1.14/coursier-core_2.13-2.1.14.jar: not found: https://maven.aliyun.com/repository/central/io/get-coursier/coursier-core_2.13/2.1.14/coursier-core_2.13-2.1.14.jar
https://maven.aliyun.com/repository/central/org/scalameta/scalameta_2.13/4.10.2/scalameta_2.13-4.10.2.jar: not found: https://maven.aliyun.com/repository/central/org/scalameta/scalameta_2.13/4.10.2/scalameta_2.13-4.10.2.jar
https://maven.aliyun.com/repository/central/io/get-coursier/coursier-proxy-setup/2.1.14/coursier-proxy-setup-2.1.14.jar: not found: https://maven.aliyun.com/repository/central/io/get-coursier/coursier-proxy-setup/2.1.14/coursier-proxy-setup-2.1.14.jar
https://maven.aliyun.com/repository/central/ch/epfl/scala/bloop-rifle_2.13/2.0.3/bloop-rifle_2.13-2.0.3.jar: not found: https://maven.aliyun.com/repository/central/ch/epfl/scala/bloop-rifle_2.13/2.0.3/bloop-rifle_2.13-2.0.3.jar
https://maven.aliyun.com/repository/central/org/scalameta/common_2.13/4.10.2/common_2.13-4.10.2.jar: not found: https://maven.aliyun.com/repository/central/org/scalameta/common_2.13/4.10.2/common_2.13-4.10.2.jar
https://maven.aliyun.com/repository/central/io/get-coursier/coursier_2.13/2.1.14/coursier_2.13-2.1.14.jar: not found: https://maven.aliyun.com/repository/central/io/get-coursier/coursier_2.13/2.1.14/coursier_2.13-2.1.14.jar
https://maven.aliyun.com/repository/central/org/scalameta/semanticdb-shared_2.13/4.10.2/semanticdb-shared_2.13-4.10.2.jar: not found: https://maven.aliyun.com/repository/central/org/scalameta/semanticdb-shared_2.13/4.10.2/semanticdb-shared_2.13-4.10.2.jar
https://maven.aliyun.com/repository/central/org/scalameta/semanticdb-scalac-core_2.13.15/4.10.2/semanticdb-scalac-core_2.13.15-4.10.2.jar: not found: https://maven.aliyun.com/repository/central/org/scalameta/semanticdb-scalac-core_2.13.15/4.10.2/semanticdb-scalac-core_2.13.15-4.10.2.jar
https://maven.aliyun.com/repository/central/ch/epfl/scala/scalafix-interfaces/0.13.0/scalafix-interfaces-0.13.0.jar: not found: https://maven.aliyun.com/repository/central/ch/epfl/scala/scalafix-interfaces/0.13.0/scalafix-interfaces-0.13.0.jar
https://maven.aliyun.com/repository/central/io/get-coursier/coursier-util_2.13/2.1.14/coursier-util_2.13-2.1.14.jar: not found: https://maven.aliyun.com/repository/central/io/get-coursier/coursier-util_2.13/2.1.14/coursier-util_2.13-2.1.14.jar
https://maven.aliyun.com/repository/central/org/scalameta/parsers_2.13/4.10.2/parsers_2.13-4.10.2.jar: not found: https://maven.aliyun.com/repository/central/org/scalameta/parsers_2.13/4.10.2/parsers_2.13-4.10.2.jar

Downloading Metals failed with the following:
Process exited with code 1
  Metals version: 1.3.5+171-b77fedf0-SNAPSHOT  
  Server properties: -Xmx1G 
  Java configuration: 
    - coursier: /home/leh/.metals/cs
    - coursier mirror: undefined
    - extra environment: [object Object]
    - java options: 
    - java path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    
Trying again with the embedded coursier. This might take longer.
Metals version: 1.3.5+171-b77fedf0-SNAPSHOT
Using coursier located at undefined
Searching for Java on PATH. Found java executable under /usr/bin/java that resolves to /usr/lib/jvm/java-17-openjdk-amd64/bin/java
Using Java Home: /usr/lib/jvm/java-17-openjdk-amd64
Exception in thread "main" java.lang.NoClassDefFoundError: scala/meta/io/RelativePath$
	at scala.meta.internal.metals.logging.MetalsLogger$.<clinit>(MetalsLogger.scala:42)
	at scala.meta.metals.Main$.main(Main.scala:42)
	at scala.meta.metals.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.meta.io.RelativePath$
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 3 more
[Error - 4:37:29 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:37:29 PM] Connection to server got closed. Server will restart.
true
[Error - 4:37:29 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Exception in thread "main" java.lang.NoClassDefFoundError: scala/meta/io/RelativePath$
	at scala.meta.internal.metals.logging.MetalsLogger$.<clinit>(MetalsLogger.scala:42)
	at scala.meta.metals.Main$.main(Main.scala:42)
	at scala.meta.metals.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.meta.io.RelativePath$
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 3 more
[Error - 4:37:30 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:37:30 PM] Connection to server got closed. Server will restart.
true
[Error - 4:37:30 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Could not launch Metals Language Server:
Pending response rejected since connection got disposed
Release notes was not shown: is a remote environment ssh-remote
Exception in thread "main" java.lang.NoClassDefFoundError: scala/meta/io/RelativePath$
	at scala.meta.internal.metals.logging.MetalsLogger$.<clinit>(MetalsLogger.scala:42)
	at scala.meta.metals.Main$.main(Main.scala:42)
	at scala.meta.metals.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.meta.io.RelativePath$
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 3 more
[Error - 4:37:30 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:37:30 PM] Connection to server got closed. Server will restart.
true
[Error - 4:37:30 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:37:30 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Exception in thread "main" java.lang.NoClassDefFoundError: scala/meta/io/RelativePath$
	at scala.meta.internal.metals.logging.MetalsLogger$.<clinit>(MetalsLogger.scala:42)
	at scala.meta.metals.Main$.main(Main.scala:42)
	at scala.meta.metals.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.meta.io.RelativePath$
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 3 more
[Error - 4:37:30 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:37:30 PM] Connection to server got closed. Server will restart.
true
[Error - 4:37:30 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:37:30 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Exception in thread "main" java.lang.NoClassDefFoundError: scala/meta/io/RelativePath$
	at scala.meta.internal.metals.logging.MetalsLogger$.<clinit>(MetalsLogger.scala:42)
	at scala.meta.metals.Main$.main(Main.scala:42)
	at scala.meta.metals.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.meta.io.RelativePath$
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 3 more
[Error - 4:37:31 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:37:31 PM] The Metals server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 4:37:31 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:37:31 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by tgodzik** [comment]
Thanks for reporting! Did you switch to a prerelease version? It will suggest to update metals snapshot version, which is not on Maven central and I guess you are using maven central mirror. In that case you should probably stay with the stable version of the plugin. Please remove the metals.server version from vs Code settings or change it to 1.3.5

**Comment by Enhowww** [comment]
Thanks for your reply, I did as you said, but he popped up different errors

![屏幕截图 2024-10-15 171602](https://github.com/user-attachments/assets/21682937-3236-4c3f-a3e2-be5f8d6d4924)

**Comment by tgodzik** [comment]
It looks it's still trying to download snapshot version of metals. You have to make sure that metals.serverVersion for both workspace and user is set to 1.3.5.

**Comment by Enhowww** [comment]
Yes, I just checked the remote and local Metals for version 1.3.5, and when I checked the Metals Settings, I found this, I wonder if this is the problem?
![image](https://github.com/user-attachments/assets/22be5fcc-7dc1-4716-bc23-e271c9b2f583)

**Comment by Enhowww** [comment]
Oh, it really was a problem, I changed it to 1.3.5 and the problem was solved!!!
Thank you for guiding me to a solution, otherwise I would have been very upset for who knows how many days!!!
![image](https://github.com/user-attachments/assets/7028fb8a-a80e-4b20-96ef-92da61cde314)

**Comment by Enhowww** [comment]
But there is another problem, I don't know what the default value of this option is, in other words, if I update Metals, will it still go wrong?

**Comment by tgodzik** [comment]
You might want to remove the option altogether from the json files that is the base for the settings. In the upper right corner you can open that json:

![image](https://github.com/user-attachments/assets/3dffb04a-b5aa-4cb2-9b26-357b465edee6)

If you remove the metals.serverVersion option we will always use the defaults

**Comment by Enhowww** [comment]
Thank you soooooo much, the problem is completely solved! And do you recommend upgrading to v1.3.9?

**Comment by Enhowww** [comment]
I'm sorry I asked such a stupid question. I just found out that v1.39.0 is 1.3.5.
Thank you for being so patient in answering our questions. 
Have a nice day!!!
