### ISSUE TITLE
Details is duplicated into label in completions, causing odd behaviour in some editor setups

### ISSUE THREAD

**Issue by Sorixelle** [scalameta/metals#6849]
### Describe the bug

The `details` value of completion items from the language server seems to be duplicated into the `label` field. This causes issues with some editors, notably Emacs, using Eglot for LSP support and Corfu for completion:

![image](https://github.com/user-attachments/assets/b379498a-cb1f-4e0d-8804-e0395b53e9f0)

If Corfu is configured for [TAB-and-Go completion](https://github.com/minad/corfu?tab=readme-ov-file#tab-and-go-completion), typing anything to apply the selected configuration results in the `scala.collection.mutable` part being left in the file, which is undesired.

**To reproduce:**

1. Put together an Emacs configuration using Eglot and Corfu configured for TAB-and-Go completion (if a configuration is necessary, [mine is available here](https://git.isincredibly.gay/srxl/dotfiles/src/branch/main/config/emacs-config.org), although a little overkill for this repro)
2. Open a Scala file in a project, ensuring Metals is available on the path
3. Enable Eglot (if it isn't already) with `M-x eglot`
4. Into the buffer, type `import scala.collection.mutable.Has`
5. Wait for completions to appear, hit `TAB` to select an option, and continue typing (eg. type `.`)
6. The line becomes `import scala.collection.mutable.HashMap scala.collection.mutable.`

### Expected behavior

When step 5 is completed, the line should become `import scala.collection.mutable.HashMap.`

### Operating system

Linux

### Editor/Extension

Emacs (other)

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting, would need to add a new setting in [MetalsServerConfig](https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala) and the [PresentationCompilerConfig](https://github.com/scalameta/metals/blob/main/mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java) which then we can use it around [here](https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala#L130)
