### ISSUE TITLE
Not a valid command: metalsEnable 

### ISSUE THREAD

**Issue by cloudcalvin** [scalameta/metals#685]
Good day all, 

I am new to metals an might have something set up wrong, so I apologize in advance. I did try what was mentioned in the troubleshooting section to no avail:

Using metals with vscode I get the following error when trying to build a project. (It happens for all the projects I have tried so far).

```
[error] Not a valid command: metalsEnable
[error] Not a valid project ID: metalsEnable
[error] Expected ':'
[error] Not a valid key: metalsEnable
[error] metalsEnable
[error]             ^
sbt exit: 1
```
I have added `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M13")'
to /home/userd/.sbt/1.0/plugins/plugins.sbt but have also tried it with M14.

- Operating system:  Arch Linux
- Editor: Visual Studio Code
- Metals version: v0.5.0
- Coursier installed via AUR: 1.1.0-M14

Kind regards
Calvin

**Comment by ayoub-benali** [comment]
It is a know bug in coursier, please upgrade to `1.1.0-M13-2`

**Comment by cloudcalvin** [comment]
> It is a know bug in coursier, please upgrade to `1.1.0-M13-2`

Yes, I saw that from issue #383 which lead me to try using 1.1.0-M14, but it does not work.

**Comment by ayoub-benali** [comment]
which sbt and java versions are you using ?

**Comment by cloudcalvin** [comment]
The project I am running is vanilla udash template: sbt new UdashFramework/udash.g8 
with javac 1.8.0_212.
sbt version = 1.2.8

**Comment by ayoub-benali** [comment]
Can't reproduce the issue with the project template even with coursier `1.1.0-M14`. Maybe @olafurpg have better ideas

**Comment by cloudcalvin** [comment]
Ok thank you for your effort!
I think I have this working now. Had to delete /tmp/metals6902378459201529676/sbt-launch.jar and then restarting vscode. (but now I have a different error..) 
```Failed to connect with build server, no functionality will work.
scala.meta.internal.metals.BloopServers$NoResponse$: no response: bloop bsp```

I will close and browse the issues for this new error.

**Comment by ayoub-benali** [comment]
have you tried deleting your `.metals` `.bloop` directories as well ?

**Comment by cloudcalvin** [comment]
Ok I just tried it: 1) deleted .metals and .bloop then 2) metals import build. It did not work. 
I closed vscode, deleted them again, opened vscode, and this time it worked..

**Comment by cloudcalvin** [comment]
I appreciate the help!
