### ISSUE TITLE
vscode metals not working

### ISSUE THREAD

**Issue by qianlong-zhang** [scalameta/metals#6850]
### Describe the bug

I'm using vscode 1.94.2, metals 1.29, scala:2.13.10, java 11, metals server version 1.2.2, bloop v.5.15,  after import scala project  everthing goes fine and metals doctor report perfect,  but code can not be indexd and go to defination
![image](https://github.com/user-attachments/assets/eb9efbe6-42ab-470a-8022-170cceb064e6)

### Expected behavior

code can be indexed and go to defination

### Operating system

None

### Editor/Extension

None

### Version of Metals

v1.2.2

**Comment by tgodzik** [comment]
Thanks for reporting, do you have anything in .metals/metals.log ? It might also be helpful to update to latest Metals version 1.3.5
