### ISSUE TITLE
spaces in .sbtopts are interpreted wrong

### ISSUE THREAD

**Issue by mio-19** [scalameta/metals#6858]
**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

Have .sbtopts like this

```
-J-Xmx5G -J-XX:+UseG1GC
```

1. Try to use metals on windows

```

2024.10.16 22:32:29 INFO  Successfully validated 6 migrations (execution time 00:00.025s)
2024.10.16 22:32:29 INFO  Current version of schema "PUBLIC": 6
2024.10.16 22:32:29 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2024.10.16 22:32:29 INFO  sbt 1.10.2 found for workspace.
2024.10.16 22:32:30 ERROR Invalid maximum heap size: -Xmx5G -J-XX:+UseG1GC
2024.10.16 22:32:30 ERROR Error: Could not create the Java Virtual Machine.
2024.10.16 22:32:30 ERROR Error: A fatal exception has occurred. Program will exit.
2024.10.16 22:32:30 INFO  time: ran 'sbt bspConfig' in 0.16s
2024.10.16 22:32:30 WARN  Build server is not auto-connectable.

```

**Expected behavior**

**Screenshots**

**Installation:**

- Operating system: Windows
- VSCode version: 1.93.1
- VSCode extension version: 1.39.6
- Metals version: (found in VSCode settings, under `metals.serverVersion`)

**Additional context**
If I set launch script to path to sbt.bat, many things work, but bsp is broken .
**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! Do you know where .sbtopts is actually specified?
