### ISSUE TITLE
UnexpectedInputEndException and OutOfMemoryError

### ISSUE THREAD

**Issue by brndt** [scalameta/metals#6872]
### Describe the bug

As I said on discord, I don't know what's the cause and how to reproduce it.

[logs.txt](https://github.com/user-attachments/files/17462490/logs.txt)

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
This might be related to the bug we fixed in scalameta. Are you able to check latest snapshot? I want to do a new release this week.

**Comment by brndt** [comment]
Since I don't know how to reproduce it, we can close it and if it happens again with the latest snapshot, I well reopen this issue.
