### ISSUE TITLE
Missing targetDialect for `OrganizeImports = { targetDialect = Scala3 }`

### ISSUE THREAD

**Issue by jsilasbailey** [scalameta/metals#6886]
### Describe the bug

To reproduce:

1. Clone the [scalafix example repo](https://github.com/scalacenter/sbt-scalafix-example)
2. Edit the `.scalafix.conf` with the following
```
rules = [
  RemoveUnusedImports
  OrganizeImports
]

OrganizeImports = {
  targetDialect = Scala3
}
```
3. Open `A.scala`
4. Run organize imports
5. Observe warning message

<img width="1434" alt="image" src="https://github.com/user-attachments/assets/8c75f491-8648-48b2-ae0d-ed65c622be0c">

### Expected behavior

The OrganizeImports configuration should be recognized in any valid configuration format

With some quick digging it seems the issue might be coming from not parsing the scalafix conf file correctly? Specifically, it seems to be asking to amend "OrganizeImports.targetDialect" due to a direct text comparison looking for this exact line?
https://github.com/scalameta/metals/blob/73dc6db8b53cb04291726cfa57cf1c0a9fc37a46/metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala#L481

```scala
for {
  config <- scalaconfFileText
  newSettings = amendSettings.filterNot { case (name, _) =>
    config.contains(name)
  }
  if !newSettings.isEmpty
}
```

Happy to dig more into this and submit a fix if I'm on the write track as to the root issue.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

1.3.2

**Comment by tgodzik** [comment]
Thanks for reporting and figuring out where the issue is.

**Comment by andyczerwonka** [comment]
Yeah, I had to work around it and just use the `.` syntax.
