### ISSUE TITLE
Implicit inlay hints only show the first implicit call of a chain

### ISSUE THREAD

**Issue by francesconero** [scalameta/metals#6890]
### Describe the bug

```scala
//> using scala 2.13.15

implicit def aString: String = "a"
implicit def lengthOfString(implicit s: String): Int = s.length
implicit def toLong(implicit i: Int): Long = i.toLong

def toDouble(implicit l: Long): Double = l.toDouble

toDouble // the inlay hint only shows (toLong) but I expected it to show (toLong(lengthOfString(aString)))
```

### Expected behavior

Implicit inlay hint should show `(toLong(lengthOfString(aString)))` for the `toDouble` call but only shows `toLong`

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.4.0

### Extra context or search terms

inlay-hints, implicits

**Comment by tgodzik** [comment]
Thanks for reporting! I can reproduce, must be regression connected to the change to compiler backed ones.
