### ISSUE TITLE
 metals.customProjectRoot is very fragile (in a devcontainer)

### ISSUE THREAD

**Issue by spangaer** [scalameta/metals#6950]
### Describe the bug

As per suggestion [here](https://github.com/scalameta/metals/issues/5512#issuecomment-1806082696), I started using  `metals.customProjectRoot` in some of my projects. Specifically in devcontainers.

Before I was running in to trouble every once in a while and [a full clean-up seemed to fix it](https://github.com/scalameta/metals/issues/5512#issuecomment-2203953130).

Recently, I've rebooted a project that was using this setting and it seems fully broken now.

There seems to be a split chance that it works the first time, but after it's broken and can't get it to work, no matter how much cleaning I do.

I've created a reproducer here and it consistently fails. Both locally and even in GitHub Codespaces.

https://github.com/spangaer/vscode-metals-customProjectRoot

Everything indicates that it's ignoring that specific setting most of the time.

![image](https://github.com/user-attachments/assets/0f6232a0-3816-49ac-bd33-7ba80629cbec)

![image](https://github.com/user-attachments/assets/488991b8-48a3-4312-8cdd-a32abfee7293)

### Expected behavior

It should run bloop (client) and all other related items in the designated sub-folder.
I guess at the extreme just running metals in that folder would be less fragile.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.4.1

### Extra context or search terms

I tried tricking metals myself by means of `-Duser.dir=` to no avail.

I also tried to find other metals system properties, with which I could possible effect this, but failed to find related docs.

**Comment by spangaer** [comment]
After scanning through the code I figured "-Dmetals.custom-project-root=my-project/" should do the same in theory, but without any success, sadly.

**Comment by spangaer** [comment]
It ain't gonna win beauty prises, but this is the best workaround I could come up with so far.

https://github.com/spangaer/vscode-metals-customProjectRoot/commit/2d852ea177dfecb3874a4fc4ea5637e0bede3adf#diff-523a007d783488b831934f3104c60a868623f10cc67c1edbce5a4af7f2ad24afR4

**Comment by tgodzik** [comment]
Thanks for reporting! Maybe it's a race between user settings being applied and starting the build server? It doesn't happen locally, right?

**Comment by spangaer** [comment]
Oh boy, I tried to run it in the debugger, and failed, but refused to give up and with plenty of cuckoo statements I figured it out (I think).

To first respond to your question, the debugging I did in WSL, which is not a dev container but still remote though.

So the user settings do seem to propagate correctly, but...

What I figured is that it's an initialization race. 

Specifically, if `bloopInstall` is run before metals is run the first time, it sees 2 build tools.
`Bloop+sbt`

Because it sees 2, it fails to autoselect here
https://github.com/scalameta/metals/blob/d1fce175713cbfb7a43266f38bd51cff3e800164/metals/src/main/scala/scala/meta/internal/builds/BuildToolSelector.scala#L29-L33

It looks like it's supposed to offer a dialog there, but that never happens.

Anyhow, because it fails to select a buildtool, this line of code even though having 2, returns `None` anyway.
https://github.com/scalameta/metals/blob/d1fce175713cbfb7a43266f38bd51cff3e800164/metals/src/main/scala/scala/meta/internal/metals/ConnectionProvider.scala#L477-L482

And `None` there means that it will resort to the `workspace` folder here
https://github.com/scalameta/metals/blob/d1fce175713cbfb7a43266f38bd51cff3e800164/metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala#L83-L89

With that fallback it of course works for most cases anyway, but not for this case.

So the thing I newly did now (knowing I had to clean-up) is automate the clean-up and install, which makes me land in the 2 buildtool situation. And indeed if I start metals, before I run bloopInstall, it writes SBT to it's database. Once the database is there, with the buildtool selection, it doesn't matter that there's two, because now it gets the choice from DB.

So that makes up the problem, I'm hoping this sufficiently tickles your knowledge of the codebase for a solution to come to mind. 🤭

FYI, in the process I also found some questionable code here.
https://github.com/scalameta/metals/blob/d1fce175713cbfb7a43266f38bd51cff3e800164/metals/src/main/scala/scala/meta/internal/metals/ChosenBuildTool.scala#L15-L31
Specifically there not much sense in updating the atomic, if you successfully obtained a value from it. If anything it could even become a race condition with `chooseBuildTool()` below.

**Comment by spangaer** [comment]
I guess the foremost problem is the failure to display the dialog. I'm sure I've seen it pop-up before. Until now I had never understood why. I also don't know how much difference it makes, since Metals seems very bloop-centric anyway.

A possible solution could be to allows specifying a value by means of workspace setting, so the dialog is not required?

**Comment by tgodzik** [comment]
I think this is all due to the fact that Bloop is special cased, so it's not treated as a build tool. Overall I think this should be reproducible:
1. run sbtBloopInstall
2. change customRoot
3. start metals
4. see the issue

Is that about right?

**Comment by spangaer** [comment]
If 3. is a clean start, so when the H2 DB is created for the first time, then that sounds like it would do it.

**Comment by spangaer** [comment]
> I think this is all due to the fact that Bloop is special cased, so it's not treated as a build tool.

Given that statement, is it wrong to suggest adding an additional case statement in below code snippet, which checks if it's `Bloop` and a real build tool and defaults to the latter?

Or is that hopelessly naive?

https://github.com/scalameta/metals/blob/d1fce175713cbfb7a43266f38bd51cff3e800164/metals/src/main/scala/scala/meta/internal/builds/BuildToolSelector.scala#L29-L33

**Comment by spangaer** [comment]
Created 2 PR's one for a fix and one for the other observation, permitting them to be consumed separately.

**Comment by spangaer** [comment]
>And indeed if I start metals, before I run bloopInstall, it writes SBT to it's database. Once the database is there, with the buildtool selection, it doesn't matter that there's two, because now it gets the choice from DB.

So I'm trying to apply this workaround with on my actual project with  v1.4.1 and it doesn't work. While seemed to be working with 1.4.2-SNAPSHOT.
