### ISSUE TITLE
metals fails to start on Java11 requires Java17 refuses class file version 55.0

### ISSUE THREAD

**Issue by frgomes** [scalameta/metals#6952]
### Describe the bug

$ java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

$ scala -version
Scala code runner version 2.12.20 -- Copyright 2002-2024, LAMP/EPFL and Lightbend, Inc.

$ metals
Exception in thread "main" java.lang.UnsupportedClassVersionError: scala/meta/metals/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at coursier.bootstrap.launcher.a.a(Unknown Source)
        at coursier.bootstrap.launcher.Launcher.main(Unknown Source)

I'm actually having trouble with metals-emacs, which presents exactly the same stack trace:

$ metals-emacs
Exception in thread "main" java.lang.UnsupportedClassVersionError: scala/meta/metals/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at coursier.bootstrap.launcher.a.a(Unknown Source)
        at coursier.bootstrap.launcher.Launcher.main(Unknown Source)

### Expected behavior

I would expect that Metals works fine on "widely adopted" versions of the Java platform.
I certainly agree that "widely adopted" is a subjective judgement.

This criteria would probably match Java1.8, which is definitely quite old, etc, TLDR... so maybe we should accept that Java11 would be a better candidate for "widely adopted".

In my case in particular, I use Spark, which requires Java1.8 or Java11.

I can circumvent the difficulty, since I employ multiple virtual environments.
I just need to run emacs under Java17 for editing text, etc... and have another window under Java1.8 or Java11 running SBT so that I can run integration tests.

This is inconvenient. It would be "better" (another subjective judgement) if I haven't to care about multiple environments at all.

### Operating system

Linux

### Editor/Extension

Emacs (lsp-metals)

### Version of Metals

v1.4.1

**Comment by tgodzik** [comment]
> Setting the javaHome to point to JDK17 

You would have to point it to JDK 8 or 11 if you need them to be used in compilation.

**Comment by frgomes** [comment]
Since I use DoomEmacs, I've added the configuration below into my _config.el_.

```
;; Metals requires Java17 but user projects may require older versions of Java.
;; More info: https://github.com/scalameta/metals/issues/6952
;; Below we configure Metals globally so that it assumes that Java11 is a good choice
;; for all projects. This is probably a bad idea. I guess that a better choice would be
;; retrieving the desired JDK version from every project, from its build.sbt. 
(after! scala
  (setq lsp-metals-java-home "~/tools/jdk-11")) ;; this is a symlink to the actual JDK
```

And then:

```
$ doom sync
```

Apparently, it works.
I can now see under _lsp-metals-doctor-run_ that Metals requires Java17 and my project requres Java11.

**Comment by tgodzik** [comment]
That issue is no longer relevant, it's connected to the previous way of setting JDK for the bloop compile server

**Comment by realstraw** [comment]
Did you get it working @MichelKazi ? I'm using nvim-metals, setting javaHome to JDK 11 doesn't seem to work for me.

**Comment by MichelKazi** [comment]
@realstraw i ended up just getting everything to work with Java 17

Not the sexiest answer 😓

**Comment by tgodzik** [comment]
What issues do you get by setting java home setting to JDK 11? Would great to try to fix that

**Comment by realstraw** [comment]
could it be I'm not setting it correctly or nvim-metals issue? it just does not seem to have an effect when I have the following configuration

```
metals_config.settings = {
  showImplicitArguments = true,
  excludedPackages = {
    ...
  },
  javaHome = "/Users/realstraw/.sdkman/candidates/java/11.0.25-zulu"
}
```

When I start it, I have the following log lines produces by nvim lsp:

```
[START][2024-12-06 15:41:27] LSP logging initiated
[ERROR][2024-12-06 15:41:27] .../vim/lsp/rpc.lua:770    "rpc"   "~/.cache/nvim/nvim-metals/metals"       "stderr"        'Exception in thread "main" '
[ERROR][2024-12-06 15:41:27] .../vim/lsp/rpc.lua:770    "rpc"   "~/.cache/nvim/nvim-metals/metals"       "stderr"        "java.lang.UnsupportedClassVersionError: scala/meta/metals/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0\n"
[ERROR][2024-12-06 15:41:27] .../vim/lsp/rpc.lua:770    "rpc"   "~/.cache/nvim/nvim-metals/metals"       "stderr"        "\tat java.base/java.lang.ClassLoader.defineClass1(Native Method)\n"
[ERROR][2024-12-06 15:41:27] .../vim/lsp/rpc.lua:770    "rpc"   "~/.cache/nvim/nvim-metals/metals"       "stderr"        "\tat java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)\n\tat java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)\n\tat java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)\n\tat java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)\n\tat java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)\n\tat java.base/java.security.AccessController.doPrivileged(Native Method)\n\tat java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)\n\tat coursier.bootstrap.launcher.a.a(Unknown Source)\n\tat coursier.bootstrap.launcher.Launcher.main(Unknown Source)\n"
```

Setting java to 17 would just work.

**Comment by tgodzik** [comment]
The Java version to use for metals need to be JDK 17, though I am not sure how that is handled in neovim, maybe both use the same setting? metals.javaHome should be used internally by metals, not to start metals server itself

**Comment by realstraw** [comment]
Got it, it makes sense. I need to make sure nvim-metals start metal with jdk 17, and the setting should work with jdk11 projects. Thank you @tgodzik .

**Comment by tgodzik** [comment]
Let us know if anyone has any issues even if everything is set correctly. Closing for now

**Comment by jsatk** [comment]
I suddenly started seeing this issue after upgrading my version of metals in neovim via `:MetalsUpdate`.

`:LspLog` info.

```log
[START][2025-02-03 21:06:10] LSP logging initiated
[ERROR][2025-02-03 21:06:10] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jesse.atkinson/.cache/nvim/nvim-metals/metals"	"stderr"	'Exception in thread "main" '
[ERROR][2025-02-03 21:06:10] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jesse.atkinson/.cache/nvim/nvim-metals/metals"	"stderr"	"java.lang.UnsupportedClassVersionError: scala/meta/metals/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0\n"
[ERROR][2025-02-03 21:06:10] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jesse.atkinson/.cache/nvim/nvim-metals/metals"	"stderr"	"\tat java.base/java.lang.ClassLoader.defineClass1(Native Method)\n\tat java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)\n"
[ERROR][2025-02-03 21:06:10] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jesse.atkinson/.cache/nvim/nvim-metals/metals"	"stderr"	"\tat java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)\n\tat java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)\n\tat java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)\n\tat java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)\n\tat java.base/java.security.AccessController.doPrivileged(Native Method)\n\tat java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)"
[ERROR][2025-02-03 21:06:10] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jesse.atkinson/.cache/nvim/nvim-metals/metals"	"stderr"	"\n\tat coursier.bootstrap.launcher.a.a(Unknown Source)"
[ERROR][2025-02-03 21:06:10] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/jesse.atkinson/.cache/nvim/nvim-metals/metals"	"stderr"	"\n\tat coursier.bootstrap.launcher.Launcher.main(Unknown Source)\n"
```

I am using [LazyVim](https://www.lazyvim.org/extras/lang/scala) w/ the Scala plugin enabled. After reading through this thread I created a file w/ the following contents: 

```lua
return {
  {
    "scalameta/nvim-metals",
    opts = {
      javaHome = "/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home",
    },
  },
}
```

At the path `~/.config/nvim/lua/plugins/nvim-metals.lua`. 

My project is actually still on 1.8 but locally I build with 11. I attempted to point this at 17 like the comments suggested but I still see the same failure on start up.

Any help or tips?

**Comment by tgodzik** [comment]
Since we are using JDK 17 API Metals needs to run on JDK 17+.

Actually, `javaHome` is used for the version you want to compile for, while Metals will probably pick up version form JAVA_HOME or from PATH, not exactly sure in case of nvim.

**Comment by jsatk** [comment]
@tgodzik I don't understand. What am I doing wrong? I only added that file that overrides the `javaHome` after reading this thread. 

How do I get metals to run on JDK 17+?

**Comment by tgodzik** [comment]
I think that java might be coming from how metals binary is setup. @ckipp01 was digging around there recently so he might have some more background

**Comment by jsatk** [comment]
Thanks @tgodzik. I was avoiding bugging @ckipp01 as I feel like I bug him a lot with my neovim + metals issues 😆 . Hoping to get this fixed though.

**Comment by ckipp01** [comment]
Yea, basically exactly what @tgodzik said above

> Actually, javaHome is used for the version you want to compile for, while Metals will probably pick up version form JAVA_HOME or from PATH, not exactly sure in case of nvim.

It might not be intuitive, but you have two java version in reality that you might need:

1. The Java version Metals requires to run
2. The Java version your project needs

So in your case, you're Java version that your project needs (#2 above and 1.8 from what I understand you saying) should be set with the `javaHome` setting in your metals config.

Locally Metals (#1 above) needs to be on Java 17. So on your local machine if you set your `JAVA_HOME` to 17, this should do the trick. This would ensure that

1. Metals is running on 17
2. Your projects is on 1.8

You're not the first person to get bit by this, and that's why I was asking about it recently. Under the hood I use coursier to bootstrap metals and create a `metals` executable script in your cache. This is then what nvim-metals uses to start Metals. The tricky part is that this script picks up your `JAVA_HOME` to run. So in your case, the solution to get Metals to run is to set your `JAVA_HOME` to 17, however you might be using other tools that don't like that. So it's not a great solution.

I haven't looked at it yet, but @tgodzik do you know if you can tell coursier during bootstrap to stick to a certain Java version so that when the executable the bootstrap command creates always runs on that version to not force the user to have to set `JAVA_HOME` to the right version?

**Comment by jsatk** [comment]
Ah. I understand now. That fixed it. The disconnect for me was that my `$JAVA_HOME` should be >= 17. I set my compile `javaHome` to 1.8 (yes we are still compiling to 1.8 ☹ ). Seems to be working fine now. 

Thanks again and sorry to bother @ckipp01. You're the best.
