### ISSUE TITLE
Deleted files still keep published diagnostics

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#696]
**Describe the bug**

Diagnostics are not cleared for deleted files.

**To Reproduce**
1. Introduce compile error in file `A.scala`, error diagnostics are published as expected
2. Delete file `A.scala`
3. Error diagnostics are still present in VS Code problem panel

**Expected behavior**

I expected the diagnostics to clear for `A.scala` since it's deleted.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.5.0

**Search terms**

Stale squiggles remove

**Comment by gabro** [comment]
I can confirm this bug, and it's especially evident when switching branches in git

**Comment by olafurpg** [comment]
Fix on the way in #695  :)
