### ISSUE TITLE
Warn users with deprecated Scala versions

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#699]
Currently, we support the Scala versions 2.12.{8,7,6,5,4} and 2.11.{12,11,10,9}. Soon we'll drop support for 2.12.{6,5,4} and 2.11.{11,10,9} due to several reasons:

- download numbers are very small for these artifacts.
- publishing these artifacts is slow, resulting slower progress overall because so much time is spent on releases.

Before dropping these versions, it would be nice if Metals gave a heads up warning. For example, a `window/showMessageRequest`

> You are using a legacy Scala compiler version 2.12.6, please upgrade to 2.12.8. Learn more | Not now | Don't show again

**Comment by olafurpg** [comment]
Thanks @gabro for suggesting this idea.

**Comment by gabro** [comment]
I would specifically advertise that Metals won't work anymore with those versions:

> You are using a legacy Scala version 2.12.6. Future releases of Metals will not work with this version. Please upgrade to 2.12.8.
