### ISSUE TITLE
Is is possible to either disable or bind to a key the new Hover (aka. type at point) feature?

### ISSUE THREAD

**Issue by agilesteel** [scalameta/metals#700]
I'm on Sublime Text btw.

**Comment by gabro** [comment]
Hi @agilesteel, can you explain what's your use case? Some context would help in order to understand what you're asking.

**Comment by agilesteel** [comment]
Oh it's just distracting. I don't always want things to pop up only because I hover over them. It would be good if I could hold Ctrl for example and then hover. Because right now I have to make sure that I don't accidentally position my mouse over something that can produce a popup. In general popups are like notifications to me. I want to have more control over them or as a measure of last resort disable them.

**Comment by ayoub-benali** [comment]
Hi @agilesteel, 
 - you can bind the hover info to a key binding, the command name is  `lsp_hover`
 - as far as I know it isn't possible to disable the popup showing up on mouse hover

You might want to create a feature request in the sublime plugin [repo](https://github.com/tomv564/LSP)

For this kind of questions gitter chat is better suited:
 - LSP for sublime: https://gitter.im/SublimeLSP/Lobby
 - Metals: https://gitter.im/scalameta/metals

**Comment by olafurpg** [comment]
@agilesteel thanks for the question! There is not much we can do on the Metals side for this particular issue since it's the responsibility of the Sublime LSP package to decide when to trigger hover.

**Comment by agilesteel** [comment]
Thx, I was looking for the gitter links but somehow missed them.
