### ISSUE TITLE
Complete keywords 

### ISSUE THREAD

**Issue by raboof** [scalameta/metals#711]
**Is your feature request related to a problem? Please describe.**

In vscode, when I intend to type `super.postStop()`, but for example a variable called `supervisorStrategy` is also in scope, `super.` will expand to `supervisorStrategy.`.

**Describe the solution you'd like**

If `super` would be present in the list of auto-completions, I could just select that (or keep typing).

**Describe alternatives you've considered**

An alternative solution to my immediate frustration could be to change vscode not to expand the first autocomplete option when a '.' is typed. That would probably be ~both harder to achieve and~ less convenient for the user compared to making sure 'super' can also be autocompleted, though.

**Comment by olafurpg** [comment]
Me and @markus1189 took a stab at this issue at the flatMap(Oslo) spree  and I'm hopeful we'll have this fixed for the next release.

**Comment by olafurpg** [comment]
Fixed in #712
