### ISSUE TITLE
Add automatic build import for Maven Scala projects

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#713]
Currently, you need go through several manual installation steps to use Metals with Maven project. It would be nice if Metals provided the same user experience as with sbt and gradle:

When user opens new Maven project: "Detected new Maven workspace. Would you like to import the build? Yes / No / Don't ask again"
When user changes an existing Maven project: "Would you like to import changes? Yes / No / Don't ask again"

This should be easy to achieve after recent refactor for the Gradle imports.

Some challenges:
- make sure we have a scala project and not allow importing when the project doesn't contain scala sources
- there are several issues currently with the maven bloop plugin that should be fixed as a part of work on this issue

**Comment by olafurpg** [comment]
Fixed in #722 🎉
