### ISSUE TITLE
Escape doesn't hide the method documentation tooltip

### ISSUE THREAD

**Issue by suryagaddipati** [scalameta/metals#714]
I am using vscode with metals and vim extensions. 

Escape key doesn't hide the method doc tooltip. Only way to hide that box seems to be clicking with the mouse in the editor. 

![Screenshot from 2019-05-08 11-53-29](https://user-images.githubusercontent.com/64078/57395959-ebfc8380-718e-11e9-9e93-aa74b212362d.png)

**Comment by gabro** [comment]
Hi @suryagaddipati, thanks for reporting! Which vim client are you using? Is it neovim.coc? In any case, this seems an issue with the specific client, so we can't do much on our side.

**Comment by olafurpg** [comment]
Thanks for reporting! The default shortcut to hide the parameter hints is shift+escape. You can remap this command to escape by running "Preferences: Open keyboard shortcuts (JSON)" and pasting the following configuration

```json
  {
    "key": "escape",
    "command": "closeParameterHints",
    "when": "editorFocus && parameterHintsVisible"
  }
```

**Comment by gabro** [comment]
Woops, sorry @suryagaddipati. I misread the comment and though you were using vim :) Disregard my message, thanks @olafurpg for chiming in

**Comment by suryagaddipati** [comment]
thank you. That works perfectly.

**Comment by suryagaddipati** [comment]
@olafurpg @gabro is it possible to disable parameter hint popup and only show on demand. 

I think its a little too aggressive right now and quite jarring to keep hitting a key to hide that.

**Comment by olafurpg** [comment]
I agree signature help can be noisy sometimes. I don’t know how to configure that for vscode I’m afraid
