### ISSUE TITLE
Running bloop throught python

### ISSUE THREAD

**Issue by fduraffourg** [scalameta/metals#732]
**Describe the bug**
Metals cannot run bloop through python. Bloop is installed on my computer but python is not exposed as an executable available on the PATH (because it's a dependency of bloop, not something that bloop provides).

But metals calls bloop via the `callBloopMain` method, which calls `python` with a python file provided by `Embedded.bloopPy`.

An easy patch for me is to replace the python call by a call to bloop. Then everything works fine.

 ```
--- a/metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
+++ b/metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
@@ -186,7 +186,7 @@ final class BloopServers(
     if (bloopCommandLineIsInstalled(8212)) {
       scribe.info(s"running installed 'bloop ${args.mkString(" ")}'")
       val bspProcess = Process(
-        Array("python", embedded.bloopPy.toString()) ++ args,
+        Array("bloop") ++ args,
         cwd = workspace.toFile
       ).run(
         ProcessLogger(
```
 But on Embedded there is a specific comment about this python file:

```
  /**
   * Returns local path to a `bloop.py` script that we can call as `python bloop.py`.
   *
   * We don't `sys.process("bloop", ...)` directly because that requires bloop to be
   * available on the PATH of the forked process and that didn't work while testing
   * on Windows (even if `bloop` worked fine in the git bash).
   */
```

When you install bloop it provides a single executable. It seems to me that metals should use this executable (using something else would be assuming too much about the way bloop is packaged/installed). But the comment above contradicts this.

I also saw from some other ticket that the plan would be to use some bloop launcher, so maybe this will totally change in a new future.

Is there something planned about that? Should I provide a PR with a fix to run `bloop` and not `python` or do you want to stick to using `python`?

**To Reproduce**
1. Install bloop but removes python from the PATH (or use a distribution that exposes only what you ask for)
2. Open a scala file with your text editor and import the project
3. Look at the log and contemplate this `python` not found exception

**Expected behavior**
Bloop should be able to run with it's own entrypoint.

**Installation:**
- Operating system: NixOS
- Editor: Neovim + vim-lsc
- Metals version: master (196fe365307f7a96ef24b941dcdf5d55dccc050f from Tue May 28 13:09:56 2019 +0200)

**Search terms**
bloop python

**Comment by olafurpg** [comment]
Thanks for reporting! The reason we call `python` instead of `bloop` is because it's more likely to appear on the `PATH`, especially for GUI applications like VS Code that are frequently launched with a different `PATH` compared to the user's terminal.  I don't expect the requirement to have `python` on the `PATH` to change in the near future. Would it be possible for you to make `python` a dependency of Metals?

**Comment by fduraffourg** [comment]
Too bad... I'll patch bloop locally before installing it then.

Thanks for the quick reply!
