### ISSUE TITLE
Auto-import doesn't work for nested objects

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#753]
**Describe the bug**
When completing a term enclosed in a top-level, Metals prefixes the term with the top-level but it doesn't import the top-level itself.

```scala
// a/src/main/a/A.scala
package a

object A {
 object Nested
}

// b/src/main/b/B.scala
object B {
  Nest@@
}
```

Obtained:

```scala
// b/src/main/b/B.scala
package b

object B {
  A.Nested
}
```

Expected:

```scala
// b/src/main/b/B.scala
package b
import a.A.Nested

object B {
  Nested
}
```

or 

```scala
// b/src/main/b/B.scala
package b
import a.A

object B {
  A.Nested
}
```

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.6.1

**Search terms**
autoimport, import, autocompletion, nested

**Comment by tgodzik** [comment]
Fixed in https://github.com/scalameta/metals/pull/778
