### ISSUE TITLE
Fallback to "show usages" from "Goto definition" if reference is definition itself.

### ISSUE THREAD

**Issue by rossoha** [scalameta/metals#755]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem. 

**Describe the solution you'd like**
Simply feature is a "fallback" for "go to" in cases when you click root definition itself. Instead of ignoring this request (cause it's a definition but not a reference), it would be nice to show a list of usages/references ("peek references" in VSCode is an example).

**Describe alternatives you've considered**
no, so far

**Additional context**
![](https://www.jetbrains.com/help/img/idea/2019.1/show_usages.png)

**Search terms**:
 "find usages", "show usages", "peek references"

**Comment by olafurpg** [comment]
Thank you for reporting! @tanishiking, @tgodzik and me looked into implementing this feature at the Spree in Lausanne today and we should be able to support this feature in the near future :)

**Comment by tgodzik** [comment]
Fixed in https://github.com/scalameta/metals/pull/775
