### ISSUE TITLE
Gradle Bloop import on Windows has malformed semanticdb location

### ISSUE THREAD

**Issue by Arthurm1** [scalameta/metals#769]
**Describe the bug**
The Bloop JSON project file contains a malformed location for the semanticDB when running the Gradle import from VSCode on Windows.

**To Reproduce**
Import a Gradle project using VSCode on Windows
The Bloop JSON file contains...
`"-Xplugin:\\Users\\......\\semanticdb-scalac_2.12.8-4.1.4.jar;C"`

**Expected behavior**
File should contain...
`"-Xplugin:C:\\Users\\......\\semanticdb-scalac_2.12.8-4.1.4.jar"`

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v1.4.3

**Additional context**
I think the code should use `File.pathSeparator` instead of `:` here...
https://github.com/scalameta/metals/blob/2fa408a5c56454e526d1ec4c9f810f0ed7ca5c45/metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala#L65

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! I will check it and I think I know what might be wrong.

**Comment by tgodzik** [comment]
PR with fixes:
https://github.com/scalameta/metals/pull/771

I was sure I tested it on windows, but must have slipped my mind, very sorry about that.

**Comment by tgodzik** [comment]
PR merged
