### ISSUE TITLE
Re-enable disabled presentation compiler tests for Scala 2.13

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#777]
See the `bm4` and `product-args` tests in `MacroCompletionSuite` for a reproduction.

From https://github.com/scalameta/metals/pull/763/commits/4018bc980be96377054e8a0971bd06d1564401f9:

> The presentation compiler returns empty results in both cases.  It looks
like the method `Global.addContext` is no longer called for the
bm4-parser and kind-projector phases in 2.13. At a quick glance, this
commit here in TypingTransformers might be relevant
(scala/scala@f7f85f2)
but we'll need more time to investigate properly.

**Comment by olafurpg** [comment]
I believe the two test failures look unrelated. The `product-args` test case fails even with compiler plugins disabled. The bm4 compiler plugin doesn't seem enabled at all, here's the tree during completions
```scala
// 2.12: plugin is running
package bm4 {
  object a {
    Option("").foreach(((x$1: String) => x$1 match {
      case (x @ _) => {
        implicit val x$implicit$1: String = x;
        implicitly[String].toCharArr_CURSOR_
      }
    }))
  }
}
// 2.13: plugin is not running
package bm4 {
  object a {
    Option("").withFilter(((check$ifrefutable$1: String) => (check$ifrefutable$1: @scala.unchecked) match {
  case implicit0((x @ ((_): String))) => true
  case _ => false
})).foreach(((x$1: <error>) => (x$1: @scala.unchecked) match {
      case implicit0((x @ ((_): String))) => implicitly[String].toCharArr_CURSOR_
    }))
  }
```

**Comment by gabro** [comment]
For the record, the `bm4` fails also on 2.12.9 (I've disabled the test in #867)

**Comment by tgodzik** [comment]
Test are working again in `2.12.10` and `2.13.1`, so I'm going to close this one.
