### ISSUE TITLE
Jump to Implementations Not working

### ISSUE THREAD

**Issue by vito-c** [scalameta/metals#779]
**Describe the bug**
I'm using max os, coc-nvim and running sbt in the shell to compile the source code.

I have this in my sbt plugins:
```
addSbtPlugin("org.scalameta" % "sbt-metals" % "0.6.2-SNAPSHOT")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.3.2+0-e473d887+20190614-0041")
```
my source code is `2.11.12` and using sbt version `0.13.17`

I'm able to goto declaration and find references just fine. But if I have a trait that has a delegate I'm unable to jump to the implementation.

./src/some/Foo.scala
```
trait Foo {
  def bar = {}
}
```
./src/some/delegate/FooImpl.scala
```
class FooImpl extends Foo {
  override def bar = {}
}
```

./src/some/usage/Fuz.scala
```
class Fuz(foo:Foo) {
  def fiz = {
    foo.bar()
  }
}
```

Then I put my cursor on bar and try to jump to the implementation of `bar` but it returns
`[coc.nvim] Implementation provider not found for current document`

**Comment by tgodzik** [comment]
Hi, thanks for reporting. I think `coc.nvim` is showing that because we didn't implement it yet.

It will be done in the next milestone https://github.com/scalameta/metals/issues/680
