### ISSUE TITLE
-Xfatal-warnings

### ISSUE THREAD

**Issue by vito-c** [scalameta/metals#780]
**Describe the bug**
I'm using max os, coc-nvim and running sbt in the shell to compile the source code.

I have this in my sbt plugins:
```
addSbtPlugin("org.scalameta" % "sbt-metals" % "0.6.2-SNAPSHOT")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.3.2+0-e473d887+20190614-0041")
```
my source code is `2.11.12` and using sbt version `0.13.17`

I noticed that when I had x-fatal warnings enabled it said my source wasn't compiling in the metals log but I was able to compile it via sbt.

**Comment by tgodzik** [comment]
I checked that and it seems we don't propagate `-Xfatal-warnings` to bloop so a situation where it doesn't compile in sbt but compiles in bloop should be possible, but don't see how it can be the other way around. Do you have `-Xfatal-warnings` in bloop json config?

**Comment by jvican** [comment]
We take whatever sbt and metals gives us, we don't do anything special. @vito-c Can you show me how you're setting fatal warnings in sbt? Check also what Tomasz has proposed and look if you have `-Xfatal-warnings` in the bloop JSON config of the project that fails.

**Comment by tgodzik** [comment]
Ok right, we actually disable the warnings in the metals sbt plugin.
```
          scalacOptions.in(p) --= List(
            // Disable fatal warnings so that SemanticDBs are generated even for unused warnings.
            // Down the road, metals can even remove unused imports for you if they are reported
            // as warnings but not if they are errors.
            "-Xfatal-warnings"
          ),
```

**Comment by jvican** [comment]
That way of filtering scalac options is not bullet-proof because the reference to the scalac options setting is not as precise as it can be. That could be the reason why @vito-ci is experiencing a leaked fatal warning. To fix it, scope `scalacOptions` to the `Keys.compile` task too:
  
```scala
scalacOptions.in(Keys.compile).in(p) --= List(
  // Disable fatal warnings so that SemanticDBs are generated even for unused warnings.
  // Down the road, metals can even remove unused imports for you if they are reported
  // as warnings but not if they are errors.
  "-Xfatal-warnings"
),
```
  
This is how we do it in bloop itself https://github.com/scalacenter/bloop/blob/e473d8873d69a62d0ac8289bc6adeeb9b51e6649/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L835

**Comment by tgodzik** [comment]
Thanks @jvican ! I think we can merge that fix and @vito-c can check if that helps in his situation.

**Comment by olafurpg** [comment]
Metals disables fatal warnings when exporting the build to Bloop, I don't see how that can cause a compile error in Bloop that's not in sbt however. Are you able to reproduce after a clean import of the build @vito-c ?

**Comment by vito-c** [comment]
@olafurpg what steps should I take to do a clean build?

will this be enough:
```
bloop clean myproject
cd ~/code/metals 
git pull upstream master
sbt ++publishLocal #I do this because I need 2.11
# update ~/.sbt/0.13/plugins/plugins.sbt
curl -L -o coursier https://git.io/coursier
chmod +x coursier
./coursier bootstrap \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=coc.nvim \
  org.scalameta:metals_2.12:0.6.1 \
  -r bintray:scalacenter/releases \
  -r sonatype:snapshots \
  -o /usr/local/bin/metals-vim -f
```

**Comment by jvican** [comment]
I don't know if the other steps are corect, but the bloop one isn't. Use `bloop clean myproject --propagate`, read the Quickstart guide https://scalacenter.github.io/bloop/docs/usage for more information

**Comment by vito-c** [comment]
Maybe my expectations are incorrect.
Currently I have fatals enabled on one project (myproj). When I run `bloop compile myproj --cascade` I get fatals. When I run compile in sbt on any of the projects I get no errors. I searched the .bloop directory for `fatals` but couldn't find any matches.

There is a sub project that has some warnings (subproj). On this project fatals are not enabled but it fails to compile when I run bloop.

So it looks to me like bloop is picking up configurations from the main project when I run cascade.


One thing I am wondering about my expectation with metals: Should metals ignore the `-Xfatal-warnings` compiler option?

**Comment by tgodzik** [comment]
Metals tries to ignore the warnings when generating bloop config, but if bloop fails because of warnings in subproject, then I guess it will make it also fail in Metals. However, if youd cannot find `-Xfatal-warnings` inside .bloop directory then it's quite impossible that you get fatal warnings.

**Comment by vito-c** [comment]
@jvican I can send you my builid sbt if you want to take a look

**Comment by vito-c** [comment]
I think this is now unrelated to metals I will close this ticket out and open elsewhere with a reproducible project.

**Comment by jvican** [comment]
Might be interesting to try your project with the next release of bloop which will have its own implementation of fatal warnings instead of using scalac's, see https://github.com/scalacenter/bloop/pull/1001

**Comment by vito-c** [comment]
sure thing do you want me to wait for the PR to be merged or try a snapshot?
