### ISSUE TITLE
metals fails to start if bloop server is already running

### ISSUE THREAD

**Issue by svalaskevicius** [scalameta/metals#796]
**Describe the bug**

Metals fails to start in vscode if bloop server is already running on the host.

**To Reproduce**
1. start `bloop server` (I'm using 1.3.2 version) 
2. launch vscode for scala project, with metals
3. metals shows an error in bottom right

**Expected behavior**
Things working well

**Screenshots**

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: ??? (vscode ext 1.4.3)

**Additional context**
1. if vscode is launched first, and then bloop, all things work ok
2. I cannot find extension error logs but bloop server prints this when vscode starts:
```
[W] Internal error in sessionjava.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at com.martiansoftware.nailgun.NGCommunicator.readCommandContext(NGCommunicator.java:140)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:197)
```

**Search terms**

**Comment by tgodzik** [comment]
@svalaskevicius Hi, that error shouldn't break anything. What is the error shown in Metals? You can look into `.metals/metals.log` or in VS Code output

**Comment by svalaskevicius** [comment]
```
INFO  time: initialize in 0.32s
INFO  running installed 'bloop bsp --protocol local --socket /tmp/bsp722912695636305976/-tesedgc9vz6c.socket'
ERROR Failed to connect with build server, no functionality will work.
java.io.IOException: Cannot run program "python" (in directory "/home/sarunas/dev/finance/server"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:105)
```

**Comment by svalaskevicius** [comment]
if I run it manually:
```
$ bloop bsp --protocol local --socket /tmp/bsp722912695636305976/-tesedgc9vz6c.socket    
The server is listening for incoming connections at local:///tmp/bsp722912695636305976/-tesedgc9vz6c.socket...
```

and no errors

**Comment by svalaskevicius** [comment]
installed python and it's working. have I skipped any instructions to install it? :)

**Comment by svalaskevicius** [comment]
will close the ticket, thanks!

**Comment by olafurpg** [comment]
Great that you resolved the issue! Metals has an undocumented requirement on `python` to be on the `$PATH` when using the installed Bloop server. I expect this requirement to go away soon once we move to the Bloop launcher which will soon use the new Snailgun JVM client instead of the `bloop.py` script https://github.com/jvican/snailgun

**Comment by svalaskevicius** [comment]
Excellent, thanks!

Have not seen snailgun before, what a name! :)
