### ISSUE TITLE
Failed to detect reference of value usage in case class with default fields

### ISSUE THREAD

**Issue by sadiqs** [scalameta/metals#798]
**Describe the bug**
Metals is not able to detect usage of value when used as one of the fields in a case class instantiation which has default field values.

**To Reproduce**
- Use below class as a minimal example. Put this in any metals project, for example, as `Metals.scala`.
```scala
object Metals {
  case class Msg(body: String, head: String = "Test", tail: String)

  val bodyText = "Hello" // usage 1
  val msg = Msg(bodyText, tail = "tail") // usage 2
  println(bodyText) // usage 3
}
```
- Click on `bodyText` in println line, it will only highlight the `bodyText` in usage 1 and usage 3, but not in usage 2.
- Also, when right click on usage 3, and select "Find All Usages", it will only show usage 1 and 3, but not 2.
- If all `head` field is also provided in usage 2, then everything works as expected.

**Expected behavior**
- It should find all usages of the value, even if used inside case class with default fields.

**Screenshots**

- When searching all references using usage 3
![image](https://user-images.githubusercontent.com/6613949/60269731-aba6bf80-990c-11e9-9104-2a1f573deaeb.png)

- When searching all references using usage 2
![image](https://user-images.githubusercontent.com/6613949/60269745-b1040a00-990c-11e9-9402-97edd4f5505a.png)

- When searching all references using usage 3, but with default value in case class specified, works as expected
![image](https://user-images.githubusercontent.com/6613949/60269760-b6f9eb00-990c-11e9-9791-b6eb7e358f6e.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.4.3

**Comment by tgodzik** [comment]
@olafurpg it seems that this is a scalameta issue - bodyText symbol seems to be shown as "local"

**Comment by olafurpg** [comment]
Thank you for reporting! I’ve seen goto definition similar issues with “check” methods in the metals test suites. This is indeed a SemanticDB bug. Default arguments desugar into blocks with synthetic local variables with the synthetic and artifact flags.

**Comment by tgodzik** [comment]
Reported it in https://github.com/scalameta/scalameta/issues/1883

**Comment by jameskoch** [comment]
I put together a fix, though I'm a first-time contributor, so low-confidence that it's appropriate - https://github.com/scalameta/scalameta/pull/1886
