### ISSUE TITLE
metals fails to start

### ISSUE THREAD

**Issue by drdozer** [scalameta/metals#809]
I started with an existing sbt project. Installed the metals plugin. I manually set the location of a java 8 JVM. Then on loading it failed with this in the console:

```
Java home: /usr/lib/jvm/java-8-oracle
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/1.1.0-M13-2/coursier-cli_2.12-1.1.0-M13-2-standalone.jar: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty, ignoring it
```

The dialogue says:

```
Failed to download Metals, make sure you have an internet connection and the Java Home '/usr/lib/jvm/java-8-oracle/bin/java' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.
```

I am not using a proxy.

**Comment by drdozer** [comment]
Bumping my build.sbt scalaVersion to 2.13.0 doesn't help.

**Comment by tgodzik** [comment]
Hi, thanks for reporting! There might be an issue with `/etc/ssl/certs/java/cacerts` I am not sure what system you are running, but on ubuntu there is [https://askubuntu.com/questions/971059/17-10-openjdk-and-oracle-jdk-8-and-9-the-trustanchors-parameter-must-be-non-empt](this thread). Looks like a common issue.

I am not sure if it's exactly connected to Metals, but if you manage to add more information, like specified in the bug report template (information about the system, full log etc.), it would be useful. There is not really much to go on here.

**Comment by tgodzik** [comment]
@drdozer This might also be an issue with custom `.jvmopts` - do you have anything specified?

**Comment by tgodzik** [comment]
Closing this, since we don't have enough information to go on here. We can reopen this if we have some further information.
