### ISSUE TITLE
Autocomplete with source info is broken by interleaved comments

### ISSUE THREAD

**Issue by ivanopagano** [scalameta/metals#813]
**Describe the bug**
When cascading multiple method calls on separate lines autocompletion gives detailed information on the available methods from semantic-db (I guess).
Yet if the lines are interleaved with a comment (as in the snippet below) only "local" completion is working

```scala
(1 to 10).toList
  .map(_ + 1) //interleaved comment here <--
  .sum
```

**To Reproduce**
1. Create any code snippet like the one above
2. Try autocomplete (Ctrl+Space) with and without the inlined comment
3. Look at the different behaviour

**Expected behavior**
The autocompletion should give full detailed information available in both cases

**Screenshots**
Working normally
![working](https://user-images.githubusercontent.com/1067461/60420754-bdc47e80-9be8-11e9-8653-bfe124cd1216.png)

Not working due to the line-comment
![not-working-with-comment](https://user-images.githubusercontent.com/1067461/60420751-bd2be800-9be8-11e9-926a-82ed19d8544b.png)

**Installation:**
- Operating system: macOS Mojave 10.14.5 [15-inch mpb 2018 2.6G i7, 32GB Ram]
- Editor: Visual Studio Code Version 1.35.1 (1.35.1)
- Metals version: 0.7.0

**Additional context**

**Search terms**
inline comment, auto-completion, line comment

**Comment by tgodzik** [comment]
Thanks for reporting! Confirmed it's indeed a bug, I will take a look and try to fix that as soon as possible.

**Comment by tgodzik** [comment]
A workaround merged into master and a fix into scala : https://github.com/scala/scala/pull/8193
