### ISSUE TITLE
Metals Doctor proposed Scala version is the same as current one

### ISSUE THREAD

**Issue by eugenemedvediev** [scalameta/metals#834]
**Describe the bug**
Metals Doctor proposed Scala version is the same as current one

**To Reproduce**
1. Go to build.sbt and set scalaVersion to 2.11.12
2. Save build.sbt and run MetalsDoctor
3. See error

**Expected behavior**
Recommendation should say that everything is ok as current scalaVersion listed in supported versions

**Screenshots**
![Screen Shot 2019-07-18 at 1 57 20 PM](https://user-images.githubusercontent.com/2952361/61455495-ffcd1e80-a963-11e9-841f-b4cbbb9231b1.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.5.1

**Additional context**
Same error in popup:
![Screen Shot 2019-07-18 at 2 11 42 PM](https://user-images.githubusercontent.com/2952361/61456342-170d0b80-a966-11e9-9edd-8dc0c573ae3d.png)

**Search terms**

**Comment by tgodzik** [comment]
Hi, thanks for reporting! This is already fixed in master and waiting for the next release.
