### ISSUE TITLE
Misleading warning in `doctor` when using Scala 2.11.12

### ISSUE THREAD

**Issue by amanjpro** [scalameta/metals#835]
**Describe the bug**
When running metals on a project built with Scala 2.11.12, you get the following warning:

```
You are using a legacy Scala version 2.11.12, which will not be supported in future versions of Metals. Please upgrade
e to Scala 2.11.12.:

1. More information
2. Don't show again
Type number and <Enter> or click with mouse (empty cancels):
```

**To Reproduce**
1. Create an empty project, add a `build.sbt`:
   ```scalaVersion := "2.11.12"```
2. Open an empty Scala class (e.g. `nvim src/main/scala/Test.scala`)
3. Import project to metals (bloop)
4. Wait for the build to finish, and see the error

**Expected behavior**
No errors

**Installation:**
- Operating system: Linux
- Editor: Vim with `coc`
- Metals version: v0.7.0

**Comment by amanjpro** [comment]
Ah! duplicate of #834 and is being fixed in master. Sorry for reporting again :(

**Comment by tgodzik** [comment]
No worries, that was actually fixed couple of weeks ago and we should most likely get a new release soon with some smaller fixes.
