### ISSUE TITLE
[coc.nvim] No SemanticDB

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/metals#840]
**Describe the bug**
Unable to jump to definition in Vim.

**To Reproduce**
1. Setup Vim, Coc, Metals
2. Put cursor on a class
3. Type `gd`
4. See error:
   ```
   [coc.nvim] No SemanticDB
   ```

**Expected behavior**
Jumping to class definition.

**Installation:**
- Operating system: macOS
- Editor: Vim
- Metals version: v0.7.0

**Comment by arbitrary-dev** [comment]
Though lots of `semanticdb` files present:
```
$ find . -iname semanticdb
./.bloop/metrics/scala-2.12/bloop-bsp-clients-classes/classes-Metals-sTQJnvxRR6aOuzwx2X67VQ==/META-INF/semanticdb
...
```

**Comment by arbitrary-dev** [comment]
Fixed the problem by removing `.bloop` & `.metals` directories left from previous version of Metals and re-importing the project again.

**Comment by tampler** [comment]
I'm using VsCode 1.40.1 with Metals 1.6.3

**Comment by olafurpg** [comment]
@tampler please report to Metals. This is not a coc bin issue.

**Comment by tgodzik** [comment]
@tampler The warning is usually connected to the fact that the project was not compiled. SemanticDB files are generated during compilation and are needed for a couple of functionalities, but most should work without it. Does the doctor show anything? If the doctor is clear then most likely the project didn't manage to get compiled.

Best to open a separate issue with any output of `metals.log` that you can give us.

**Comment by kamac** [comment]
I've had the same problem. Like @tgodzik said, the issue was that the project was not compiled. Running `bloop compile root` and fixing compilation errors for the file that had it's semanticdb file missing fixed the problem.
