### ISSUE TITLE
metals-emacs crashes on launch

### ISSUE THREAD

**Issue by gregghz** [scalameta/metals#844]
**Describe the bug**

When I attempt to start metals-emacs (whether via emacs or at the command line directly) it immediately crashes with the following stacktrace:

```
Exception in thread "main" java.lang.NoSuchMethodError: io.github.soc.directories.ProjectDirectories.from(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lio/github/soc/directories/ProjectDirectories;
	at scala.meta.internal.metals.GlobalTrace$.globalDirectory(GlobalTrace.scala:52)
	at scala.meta.internal.metals.GlobalTrace$.globalLog(GlobalTrace.scala:22)
	at scala.meta.internal.metals.GlobalTrace$.setup(GlobalTrace.scala:18)
	at scala.meta.metals.Main$.main(Main.scala:19)
	at scala.meta.metals.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coursier.Bootstrap.main(Bootstrap.java:428)
```

**To Reproduce**

I'm able to reproduce easily by running `metals-emacs` after following the instructions at https://scalameta.org/metals/docs/editors/emacs.html (specifically the portion for downloading/installing metals-emacs).

**Expected behavior**

I expect no crash.

**Installation:**
- Operating system: macOS 10.14.6
- Editor: Visual Studio Code and Emacs
- Metals version: v0.7.0

**Additional context**

This started happening when I moved to a new laptop. The previous one was the same setup but it worked fine.

Bloop had a similar bug: https://github.com/scalacenter/bloop/issues/463

**Comment by tgodzik** [comment]
Have you tried removing .bloop and .metals directories? I am not sure why a wrong version of directories is used though.

It looks like version 9 is being used which is nether in bloop nor in metals. Could you paste the classpath that is being used?

That should be seen after running `ps aux` after `-classpath` parameter (or something similar).

**Comment by olafurpg** [comment]
@gregghz thank you for reporting! What version of coursier are you using to build to bootstrap script? Please try with the latest version of coursier.

**Comment by gregghz** [comment]
@tgodzik I have tried that. I've also tried it with completely new projects. I'm don't believe I have time to check the classpath that metals starts with since it crash almost immediately. I've tried running ps aux | grep 'classpath' in an infinite loop while launching the server but nothing shows up.

@olafurpg I'm using which ever version is installed when following the instructions here: https://scalameta.org/metals/docs/editors/emacs.html (I don't know how to check the version)

**Comment by tgodzik** [comment]
If you rename `metals-emacs` executable to `metals-emacs.jar` you should be able to open it with archive manager. Could you look into boostrap-jar-urls and see if the right version of directories is there. It should be:
`https://repo1.maven.org/maven2/io/github/soc/directories/11/directories-11.jar`

I think that's what is supposed to end up on the classpath.

**Comment by gregghz** [comment]
I just nuked everything (metals-emacs and coursier) then installed coursier from brew. Things are working now, I think I had accidentally kept around an old metals-emacs when i moved to the new computer. I'll close this, thanks for helping!
