### ISSUE TITLE
False Compiler Error

### ISSUE THREAD

**Issue by vito-c** [scalameta/metals#845]
I am getting a compiler error here but there is no compiler error.

```scala
class memoize extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
//       ^ compile error here
    defn match {
      //q is for quasiquote the .. means matached must be a list of terms
      //and ... means it must be a list of list of terms
      case q"def $name(...$paramss): $result = { ..$body }" =>
        val newBody = Seq(
          // q"println(${"Macro hello"})"
          q"pprint.log(${"Macro hello"})"
        ) ++ body
        pprint.log(newBody)
        q"def $name(...$paramss): $result = { ..$body }"
      case _ => abort("@Memoize must annotate an function.")
    }
  }
}
```

This is on neovim using `coc.nvim` and a snapshot of scalametals. I can supply you with a zipped codebase if you need it.

**Comment by marek1840** [comment]
> I can supply you with a zipped codebase if you need it

It would be useful to have it and to know the error message. In the end, metals only propagates errors from the build tool.

**Comment by marek1840** [comment]
Also, have you verified it works correctly when not using metals?

**Comment by vito-c** [comment]
Error message: `[scalameta] [E] ; expected but def found ...`
I don't think it's coming from the build tool as bloop and sbt both compile successfully.
![image](https://user-images.githubusercontent.com/820137/62147534-8e1e9a00-b2ac-11e9-93a6-8030a7d12029.png)

I'll get the project together today.

**Comment by tgodzik** [comment]
Is inline already a keyword in Scala? I thought it's coming to dotty.

**Comment by tgodzik** [comment]
Alright, found the issue. Seems this is caused by https://github.com/scalameta/scalameta/issues/1776

**Comment by kitbellew** [comment]
> Is inline already a keyword in Scala? I thought it's coming to dotty.
> 
> Edit: Ok, that's from Macros, never wrote them myself. Nvm me.

@tgodzik did you determine that `inline` is a valid keyword in scala2? how does that relate to macros?
