### ISSUE TITLE
Treeview symbols being cached by client and not supplied by Metals?

### ISSUE THREAD

**Issue by dsyzling** [scalameta/metals#846]
I've implemented a client side Treeview for Scala Metals For Emacs - using the new treeview protocol. I'm confused however over the visibility of symbols in the Build view. If I clear down my .metals and .bloop directories in my project directory, import the project - my views (Build and Compile) are populated with the number of projects and libraries. After I expand projects a compilation is triggered for the project and eventually an async message is sent back with the new nodes in the tree. As I expand the nodes Metals responds showing me the classes, objects, fields etc. in response to the metals/treeViewChildren.

However if I exit the project and reload (without re-importing),  start the lsp workspace - there's nothing to compile - which is correct. When I then ask Metals to tell me the children of my projects Metals returns an empty list - no symbols are returned.

I've traced VSCode and Metals looking through the lsp message trace and when I do the same in vscode - no request is sent from the client in this latter scenario. It looks like vscode or the metals/vscode client is caching the symbols, rather than Metals providing this information? Given the specification of the treeview protocol this isn't implied behaviour and I would have thought if I explicitly ask for children of a project node it would respond with the symbols within that project via the lsp treeview protocol? 

Am I missing something obvious?

**Installation:**

Tested under Windows 10 and Arch Linux with Emacs 26.2
Metals version is 0.7.0+45-2d3960b4-SNAPSHOT and -Dmetals.execute-client-command=on

**Comment by dsyzling** [comment]
Actually after some further testing the behaviour is more inconsistent. It seems to depend on the file I load initially from my project. I've been testing by loading the build.sbt file in the root of my project - this triggers the lsp server to load and the views (compile and build) to be returned. However in this case when I expand the tree (assuming the project has been compiled and I'm opening the editor fresh) Metals doesn't return any classes or symbols for my projects.

However if I load my editor fresh and open a scala class file in my project which triggers the lsp server to load I then find that Metals returns children under my projects (i.e. classes/symbols).

So may be build.sbt or other project related files that may not be scala files cause a change in behaviour of the tree. A colleague of mine has noticed some inconsistency with the tree returning classes when used under vscode - he now wonders if this is related to opening project files that are non scala files but we haven't pursued further testing in these scenarios as yet.

**Comment by tgodzik** [comment]
@olafurpg will mostly know, not totally familiar with the logic here.

**Comment by olafurpg** [comment]
Thank you for reporting! I'm excited to hear that the tree view protocol has an implementation in Emacs!

I'm not sure I understand the steps to reproduce the issue. Can you maybe elaborate? Is the problem only in Emacs or also in VS Code?

It's expected that the list of projects is empty if the Metals server has just started it hasn't established a connection with the build server. Metals should send a "did change" notification after connecting to the build server, https://scalameta.org/metals/docs/editors/tree-view-protocol.html#metals-treeviewdidchange

**Comment by olafurpg** [comment]
The editor client is not supposed to cache results between Metals server processes.

**Comment by dsyzling** [comment]
I may have to send you a trace of the lsp conversation. In Emacs and lsp-mode opening a file within a project directory will trigger the starting of an lsp server. Sbt build files and scala files are associated with automatically starting a the scala mode lsp server - in this case Metals. If I open a scala file in my project directly and Metals starts, I will eventually be able to expand the tree elements and it shows me classes, symbols etc. If I first open the project's build.sbt - the initialisation is the same, i.e. Metals sends me the views (build, compile) and the project list. This time however when I try to expand the projects and my code sends the get children request nothing is returned. The only difference in this case is me opening the sbt build file instead of a scala source file. On the client side I don't think these are treated any differently - they are file extensions associated with scala-mode and the mode is used to look up the lsp server to start when one of these files is opened.

**Comment by dsyzling** [comment]
I can trigger the same behaviour in VSCode by doing the following:

- Open the project in VSCode, let Metals load and import the project. Close all active files and leave the build.sbt file open.
- Close VSCode 
- Re-open VSCode and load the workspace.
- Now go to the Metals tab and it will load the project details, eventually the projects will be displayed.
- Now if I expand the projects nothing is returned, from the Emacs trace I know I send metals a request asking for children and an empty list is returned.

- Now close build.sbt and open a scala file in the project.
- Close the workspace
- Re-Open the workspace.
- Now once Metals has loaded the projects tree will expand correctly and show children. 

There seems to be an internal state within metals that is changed after a scala file is loaded which affects the tree. On Emacs with new projects I may typically load the build file to trigger the project and metals to load and then navigate through the project. Currently this doesn't allow me to interact with the treeview, I'm forced to load a scala file first in order to get the treeview to function correctly.

Any situation that forces a compilation will subsequently show children in that part of the tree.

**Comment by olafurpg** [comment]
Opened #997 to fix this issue. The fix itself was fairly easy but it was trickier to minimize the bug in a test case.
