### ISSUE TITLE
Build import fails with maven behind proxy

### ISSUE THREAD

**Issue by antonoal** [scalameta/metals#851]
**Question**

Hi.

I'm trying out metals with a maven project I've got but alas it fails when trying to download Maven with an UnknownHostException. My machine is behind a proxy. 

Is there a way I can specify proxy settings for a maven build? I've tried .jvmopts (like I do for sbt builds) but that didn't work.

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v1.5.2

**Comment by tgodzik** [comment]
Hi, there is instruction on that here: https://scalameta.org/metals/docs/editors/vscode.html#custom-artifact-repositories-maven-or-ivy-resolvers 

If there is any issue with coursier, let me know.

**Comment by tgodzik** [comment]
Ach, `download Maven` not `download from Maven`! You can just specify in VS Code settings the mvn executable you want to use and it will use your machine proxy settings.

![image](https://user-images.githubusercontent.com/3807253/62220891-14bc9f80-b3b1-11e9-8891-4a0ecff5598d.png)

**Comment by antonoal** [comment]
Awesome, thanks a lot!
