### ISSUE TITLE
No code insights for generated sources

### ISSUE THREAD

**Issue by megri** [scalameta/metals#854]
**Describe the bug**
Sources generated through SBT and stored under `sourceManaged` do not seem to be taken into account by Metals.

**To Reproduce**
https://github.com/megri/metals-generated-sources

**Expected behavior**

**Installation:**
- SBT version 1.2.8
- Metals VSCode extension version: 1.5.2

**Comment by megri** [comment]
Heh, I failed to reproduce the bug with this example. Will try again later.

**Comment by tgodzik** [comment]
Thanks, it would be very useful to have an example - we can fix it much quicker.
