### ISSUE TITLE
Add support for Scala 2.12.9

### ISSUE THREAD

**Issue by regadas** [scalameta/metals#856]
After upgrading to scala 2.12.9 and re-importing the build Navigation is disabled and Metals Doctor reports:

```
Upgrade to Scala 2.12.8 and run 'Build import' to enable code navigation.
```

**Comment by regadas** [comment]
Hmm ok, after a brief look the fix is really just publishing with 2.12.9. Although this is blocked by https://github.com/scalameta/scalameta/issues/1892

**Comment by tgodzik** [comment]
I will try to push that along in scalameta/scalameta. I was looking yesterday and we still didn't have macro paradise published.

**Comment by tampler** [comment]
Hello any progress on this issue? Any help in testing/implementation required ?
I'd like to have this feature asap

Thanks,
Boris

**Comment by gabro** [comment]
@tampler we have an open PR (#867) but things are moving slow since @olafurpg and I are both quite busy at work and @tgodzik is on vacation. We're not too far, but the upgrade requires fixing a few tests on our side.

Watching the PR for updates :)

**Comment by regadas** [comment]
@gabro Awesome! Thx!

**Comment by tampler** [comment]
@gabro @olafurpg @tgodzik  Thanks a lot guys!
