### ISSUE TITLE
[coc.nvim] Build misconfiguration

### ISSUE THREAD

**Issue by hurjaewon** [scalameta/metals#858]
Hi, I'm extremely new to scala and metals (also sbt)

I followed the guide in metals reference page
but whenever I do 'build import' 
I meet [coc.nvim] Build misconfiguration

My scalacVersion is 2.12.7
and I added

scalacOptions += "-Yrangepos"
scalacOptions += "-P:semanticdb:sourceroot:$WORKSPACE(my absolute route)" 

addCompilerPlugin(scalafixSemanticdb)
addCompilerPlugin("org.scalameta" % "semanticdb-scalac" % "4.1.0" cross CrossVersion.full)
bloopAggregateSourceDependencies in Global := true

on build.sbt

does anyone know this problem?

**Comment by hurjaewon** [comment]
metals doctor says

![image](https://user-images.githubusercontent.com/33274411/62707493-6ce84700-ba2c-11e9-9c89-0423e1dd7475.png)

**Comment by tgodzik** [comment]
Hi, you don't need to add any of those options, they are added by default by Metals. If you need to add them because of your project requirements then it's currently the same issue as https://github.com/scalameta/metals/issues/808 - which we are currently working on.

**Comment by tgodzik** [comment]
Closing the issue - pretty sure it's the same as #808 and if you are not using scalafix then no need to add it.
