### ISSUE TITLE
Insert pipe character | when editing multiline strings with stringMargin

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#859]
**Is your feature request related to a problem? Please describe.**

When editing multiline strings with `.stripMargin` it's currently necessary to manually type the `|` character and indent it.

**Describe the solution you'd like**

It would be nice if Metals inserted the `|` character at the correct indentation as we type, the same way it works in IntelliJ.

![2019-06-21 20 15 30](https://user-images.githubusercontent.com/1408093/59943043-97bd1280-9461-11e9-8d22-3ddd5089c046.gif)

**Describe alternatives you've considered**

In the PR https://github.com/scalameta/metals-vscode/pull/121, we added basic support for similar functionality in the VS Code extension. This solution has several limitations however:

- it triggers even when editing outside multiline strings

![2019-06-21 20 05 30](https://user-images.githubusercontent.com/1408093/59942646-8b848580-9460-11e9-94e8-4d14f709f7f4.gif)

- it doesn't auto-insert `|` for copy-pasted multiline code

![2019-06-21 20 11 00](https://user-images.githubusercontent.com/1408093/59942717-b5d64300-9460-11e9-87af-0eb3f59f1f59.gif)

- it only works for VS Code

**Additional context**

In LSP there is a `textDocument/formattingOnType` request that allows us to produce the same behaviour that allows us to implement this analysis on top of tokens and make it work for all editors.

**Comment by marek1840** [comment]
partially fixed by https://github.com/scalameta/metals/pull/865

What is still missing is inserting "|" when copy-pasting inside a multiline strings
