### ISSUE TITLE
Auto add package

### ISSUE THREAD

**Issue by antoinesauray** [scalameta/metals#860]
**Is your feature request related to a problem? Please describe.**
When creating a new file in a folder, the package needs to be typed manually or copied from files in the same folder. It is a repetitive task that is quite painful.

**Describe the solution you'd like**
Would it be possible to infer the package from the folder the file has been placed and to auto add the package to the top of the file with a shortcut ?

**Describe alternatives you've considered**
* Typing manually
* Copying from other files

**Additional context**

**Search terms**:
metals package

**Comment by tgodzik** [comment]
We still need to implement moving files between packages.

**Comment by olafurpg** [comment]
@tgodzik close as fixed? I would say that "moving files between packages" is a separate feature which requires more thought.

**Comment by olafurpg** [comment]
I think "move file between packages" falls under the broader topic of refactoring, which is currently unsupported.

**Comment by tgodzik** [comment]
> I think "move file between packages" falls under the broader topic of refactoring, which is currently unsupported.

You're right, we need to figure out the strategy for updating files in the workspace. Let me open a separate issue.
