### ISSUE TITLE
Presentation compiler not working on Scala 2.12.9

### ISSUE THREAD

**Issue by megri** [scalameta/metals#868]
**Describe the bug**
When hovering over a symbol, only "Loading..." is shown.

**To Reproduce**
1. Set `scalaVersion := "2.12.9" in SBT`
2. Import build
3. Hover over a symbol

**Expected behavior**
Tooltips should show scaladoc and type information.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals server version: 0.7.0+93-70fec4d6-SNAPSHOT

**Extra info:**
Tooltips begin to function again after setting `scalaVersion` to 2.12.8 and importing the build again. The server version needn't be changed.

**Comment by gabro** [comment]
Thanks for reporting! I’ll try to take a look at it in the next couple of days

**Comment by gabro** [comment]
I can reproduce this, and completions aren't working either.

I've tried instrumenting the server a bit, and it seems that the request never completes. I haven't yet tracked down where it gets stuck, but I'm currently suspecting something around `withNonInterruptableCompiler` here

https://github.com/scalameta/metals/blob/f7dc2c5d6732bb484420451cccc8e386807d49fd/mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala#L113-L121

@olafurpg do you have any idea of why the tests aren't catching this?

**Comment by gabro** [comment]
Ok, thanks to @olafurpg we have an idea of the cause and a workaround for it.

I'll work on a PR to wrap this up tomorrow.
