### ISSUE TITLE
Insert | when copy-pasting inside a multiline strings

### ISSUE THREAD

**Issue by marek1840** [scalameta/metals#870]
This is a follow-up to #859 

**Is your feature request related to a problem? Please describe.**

When copy-pasting many lines into multiline strings  it's currently necessary to manually type the `|` character.

**Describe the solution you'd like**

It would be nice if Metals inserted and indented the `|` after every new line in the copy-pasted string.

**Comment by MateuszKubuszok** [comment]
I would be happy if this could exclude custom `String` interpolators from this behavior - e.g. if I copy-paste SQL for `fr` interpolator from Doobie, these `|` are always inserted and I have to remove them manually every single time.

**Comment by olafurpg** [comment]
@MateuszKubuszok The current behavior for inserted `|` is currently buggy in that it is enabled even for strings that don't have a `.stringMargin` prefix. Please open a separate issue.

**Comment by MateuszKubuszok** [comment]
@olafurpg OK, I'll do it! Thanks for your effort! :)
