### ISSUE TITLE
maven multi project build

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals#882]
Given this workspace:
```
root
| - A
| - B
```
with project B depending on project A. Maven can't compile project B because project's A jar isn't available. Probably the generated bloop configuration isn't correct.

Current workaround is to do a `mvn install -DskipTests` to force JARs to be published locally but this isn't ideal for development .
 
**To Reproduce**
1. Clone `https://github.com/dcmn-com/herringbone.git` and switch to `upgrade-scala-2.12` branch
2. install thrift locally (`apt-get install` or `brew`) 
3. import build with Metals in any text editor

```
metals: [ERROR] Failed to execute goal on project herringbone-main: Could not resolve dependencies for project com.stripe:herringbone-main:jar:0.0.1: Could not find artifact com.stripe:herringbone-impala:jar:0.0.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
metals: [ERROR] 
metals: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
metals: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
metals: [ERROR] 
metals: [ERROR] For more information about the errors and possible solutions, please read the following articles:
metals: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
metals: [ERROR] 
metals: [ERROR] After correcting the problems, you can resume the build with the command
metals: [ERROR]   mvn <goals> -rf :herringbone-main
metals: build tool exit: 1
metals: time: ran 'mvn bloopInstall' in 7.94s
metals: Maven command failed: /tmp/metals516909384235530052/mvnw ch.epfl.scala:maven-bloop_2.10:1.3.2:bloopInstall -DdownloadSources=true
metals: Import project partially failed, limited functionality may work in some parts of the workspace. See the logs for more details. 
metals: running installed 'bloop bsp --verbose --protocol local --socket /tmp/bsp1697843160558780888/-rbfh4dcwxpo1.socket'
metals: tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty 
```

**Expected behavior**
The build to work

**Installation:**
- Operating system: Linux
- Editor: Sublime
- Metals version: 0.7.0+111-0039eb7c-SNAPSHOT
- Bloop version: v1.3.2

**Search terms**
maven, multi project, bloop

**Comment by tgodzik** [comment]
I see it's already open in https://github.com/scalacenter/bloop/issues/1020 - this is an issue in Bloop, will close it here.

**Comment by ayoub-benali** [comment]
They are different issues, for this one Metals isn't properly setting up the bloop project which results in bloop not building the dependency.

The other one is different I believe, as it is related to a compiler error

**Comment by tgodzik** [comment]
> @tgodzik They are different issues, for this one Metals isn't properly setting up the bloop project which results in bloop not building the dependency.
> 
> The other one is different I believe, as it is related to a compiler error

Och, my bad. Sorry about it. This is an issue in Bloop though. We don't setup anything for Maven, just run bloopInstall. The problem here is that bloopInstall needs a normal install before.

**Comment by tgodzik** [comment]
Opened a new issue here: https://github.com/scalacenter/bloop/issues/1022. Sorry about the misunderstading, I only glanced briefly and it looked like the same issue.

**Comment by ayoub-benali** [comment]
No problem. Thanks for moving the issue to the right repo

**Comment by shonfeder** [comment]
So the linked issue was closed without a fix. For future readers (likely myself) who hit this, the workaround seems to be first doing

```
mvn install
```

in your project.
