### ISSUE TITLE
When inserting "|" automatically into multiline strings check for `stripMargin`

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalameta/metals#893]
**Describe the bug**

As mentioned in https://github.com/scalameta/metals/issues/870 when multiline string is inserted, then `|` is added. It is generally OK unless:

 * we use some string interpolation other than `s""`, e.g. `fr""` from Dooby (there `|` could break somthing)
 * there is no `.stripMargin` after the string

In both of these cases this feature might accidentally introduce a bug into code.

**To Reproduce**

1. copy-paste multiline string
2. check the output

**Expected behavior**

Probably something like _check if there is no-interpolation/interpolations known to be safe to work with `|` and `.stripMargin`_ and/or _add `.stripMargin` if neccessary_.

**Installation:**
- I guess `master` of metals?

**Additional context**
This issue was created to not block https://github.com/scalameta/metals/issues/870 while also preserving information that some improvement could be made.

**Search terms**
string interpolation, strip margin, pipe character

**Comment by tgodzik** [comment]
Thanks for reporting! I think we could just verify that `.stripMargin` is at the end. Is that enough for you?

Also, is the current behaviour adding `|` for you when copy pasting or do you refer to the future feature?

**Comment by MateuszKubuszok** [comment]
I think both would be valid improvements: verifying presence of `.stripMargin` during writing as well as during copy-pasting.
