### ISSUE TITLE
Mill integration does not work on 2.12.9 projects

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#897]
The solution for this is already merged on Mill (see https://github.com/lihaoyi/mill/pull/678) but we're blocked until a new Mill version is released.

Once the new Mill version is released, we have to:

- upgrade our Mill tests to use 2.12.9
- bump the Mill version in `MillBuildTool`

**Comment by gabro** [comment]
In the meantime, we should be able to try mill-0.5.0-18-d2b311 to see whether it works as expected

**Comment by tgodzik** [comment]
Updated Mill version is now merged.
