### ISSUE TITLE
Scala Metals for Emacs: Unresolved Dependencies

### ISSUE THREAD

**Issue by nloyola** [scalameta/metals#903]
**Describe the bug**
I followed the instructions on how to install Scala Metals for Emacs. I installed version 0.7.2+17-94b1cf89-SNAPSHOT. Now when I use command `lsp-metals-build-import` I get a message stating that there are unresolved dependencies. I can see this message in the `*lsp-log*` buffer and in `.metals/metals.log`.

```
INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
INFO  [warn] 	::          UNRESOLVED DEPENDENCIES         ::
INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
INFO  [warn] 	:: org.scalameta#sbt-metals;0.7.2+17-94b1cf89-SNAPSHOT: not found
INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
INFO  [warn] 
INFO  [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
INFO  [warn] 		org.scalameta:sbt-metals:0.7.2+17-94b1cf89-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
INFO  [warn] 
INFO  [warn] 	Note: Unresolved dependencies path:
INFO  [warn] 		org.scalameta:sbt-metals:0.7.2+17-94b1cf89-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0) (/home/nelson/.sbt/1.0/plugins/metals.sbt#L13-31)
INFO  [warn] 		  +- org.scala-sbt:global-plugins:0.0 (scalaVersion=2.12, sbtVersion=1.0)
INFO  [error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scalameta#sbt-metals;0.7.2+17-94b1cf89-SNAPSHOT: not found
INFO  [error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
INFO  [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
INFO  [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
...
```

**To Reproduce**
1. Within Emacs: `M-x lsp-metals-build-import`

**Expected behavior**
The dependency should be downloaded by Ivy.

**Installation:**
- Operating system: Ubuntu Linux 19.04
- Editor: Emacs version 27.0.50
- Metals version: 0.7.2+17-94b1cf89-SNAPSHOT

**Additional context**
Before installing this version, I was using the previous snapshot version given on the same web page on September 5, 2019 and all was working correctly.

**Search terms**
Ivy Unresolved Dependencies

**Comment by tgodzik** [comment]
Thanks for reporting! The jar version does exist and I can resolve it:

```
Out of 1 candidates we found for org.scalameta#sbt-metals;0.7.2+17-94b1cf89-SNAPSHOT in sonatype-snapshots, we are choosing sonatype-snapshots.
```
are maybe behind a proxy? Do you see `sonatype-snapshots` repo being used?

Maybe rerunning import would work? You can always go back to 0.7.2 version and that should work for sure.

**Comment by nloyola** [comment]
Thanks for looking into this @tgodzik . Where should I add the `sonatype-snapshots` repository. The instructions don't mention this (https://scalameta.org/metals/docs/editors/emacs.html).

**Comment by nloyola** [comment]
Just to clarify: the following command executes successfully.

```
./coursier bootstrap \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=emacs \
  org.scalameta:metals_2.12:0.7.2+17-94b1cf89-SNAPSHOT \
  -r bintray:scalacenter/releases \
  -r sonatype:snapshots \
  -o /usr/local/bin/metals-emacs -f
```

**Comment by tgodzik** [comment]
That is added in `~/.sbt/1.0/plugins/metals.sbt` when running with `METALS_ENABLED=true`. 

It should set whenever you run import via Metals. Looks like something is interfering with that in sbt. You could add it in your sbt build file to be on the safe side.

**Comment by nloyola** [comment]
I still can't get it to work. I've tried deleting all metals files with the command (in my project directory):

```
rm -rf .metals .bloop project/target ~/.sbt/1.0/plugins/target
```

I also tried adding this to my project's build.sbt:

```scala
envVars ++= Map("METALS_ENABLED" -> "\"true\"")
```

**Comment by nloyola** [comment]
I went back to using version 0.7.2. However, I had to remove file `~/.sbt/1.0/plugins/metals.sbt` before SBT could build my project again.

**Comment by tgodzik** [comment]
> I went back to using version 0.7.2. However, I had to remove file `~/.sbt/1.0/plugins/metals.sbt` before SBT could build my project again.

Why did you need to remove it? It gets automatically added by Metals, so there should be no need to remove it :thinking:

**Comment by nloyola** [comment]
Metals would not remove it because it was trying to download the snapshot version and that failed to begin with...

**Comment by tgodzik** [comment]
`~/.sbt/1.0/plugins/metals.sbt` is written before sbt is even invoked and would replace the version with 0.7.2, which would not cause any issues.

I am asking, because there might be the real issue somewhere hidden here.

**Comment by nloyola** [comment]
The file was not being overwritten when I started SBT from the command line at my project's root directory. SBT would try and download `org.scalameta#sbt-metals;0.7.2+17-94b1cf89-SNAPSHOT` and fail.

**Comment by tgodzik** [comment]
> The file was not being overwritten when I started SBT from the command line at my project's root directory. SBT would try and download `org.scalameta#sbt-metals;0.7.2+17-94b1cf89-SNAPSHOT` and fail.

Ok, that would explain it. It would be overwritten if it was run via Metals.  

I can't say why it's not working for you, but what you can do to go around the issue:
1. Go to  `~/.sbt/1.0/plugins/metals.sbt`
2. Remove both IFs `if (System.getenv("METALS_ENABLED") == "true") `
3. Run bloopInstall from cmd

**Comment by nloyola** [comment]
Thanks @tgodzik. I was able to make it work with the workaround you gave.

**Comment by tgodzik** [comment]
Not entirely sure what was happening, but this should be fixed in https://github.com/scalameta/metals/pull/852
