### ISSUE TITLE
Autocompletion of type alias insert [] even when there are no type parameters

### ISSUE THREAD

**Issue by kklorenzotesta** [scalameta/metals#920]
If I define a type alias without type parameters but that aliases a type that has parameters then when I autocomplete the alias the square brackets are automatically inserted at the end of the type.

**To Reproduce**
1. define a type alias like `type MyType = List[Int]`
2. define a function like `def foo(): MT` (it also works with val or var)
3. autocomplete on `MT` expands to `MyType[]`

**Expected behavior**
`MT` should expand to `MyType`

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.7.5

**Comment by tgodzik** [comment]
Thanks for reporting and with a reproduction! Hopefully we can fix it quickly.
