### ISSUE TITLE
Gradle scripts that reference mavenLocal() does not resolve

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals#924]
**Describe the bug**
Gradle scripts that include `mavenLocal()` in the `repositories {}` block fails to resolve dependencies.

**To Reproduce**
1. Project A, publish to local maven: `./gradlew publishToMavenLocal`
2. Project B, add project A as dependency and add `mavenLocal()` to `repositories`.
3. Build B...

**Expected behavior**
Successful build.

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.7.5

**Comment by tgodzik** [comment]
Thanks for reporting! It certainly looks like a bug.

**Comment by nilskp** [comment]
Actually, I think this is invalid. The real cause seems to be #926.
