### ISSUE TITLE
Metals VSCode UI loses all information when dependencies don't resolve

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals#925]
**Describe the bug**
See screenshot.

**To Reproduce**
1. Use #924 as reference
2. See error

**Expected behavior**
Still have access to the Metals task output. And retain access to links in the _Help and Feedback_ section. Probably more.

**Screenshots**
![image](https://user-images.githubusercontent.com/74843/64878821-043b4e00-d61a-11e9-97e1-238670a7ef29.png)

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.7.5

**Search terms**
output, empty, lost, gone, missing,

**Comment by olafurpg** [comment]
Thank you for reporting! This is working as expected. The "Help and Feedback" section links to commands that are implemented by the server so it's not possible to render them before the server has started. I'm happy to discuss ideas in the https://github.com/scalameta/metals-vscode issue tracker for alternative ideas to improve the UX when the server fails to start.
