### ISSUE TITLE
Gradle: Mixed Scala/Java projects fail to compile

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals#926]
**Describe the bug**
Gradle build scripts that have both Scala and Java sources fail to build.

**To Reproduce**
1. Add a simple Scala class to project
2. Add a simple Java class to project, which depends on the Scala class
3. See error `<Scala class> cannot be resolved to type`.

**Expected behavior**
Successful build.

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.7.5

**Search terms**
java, mixed,

**Comment by tgodzik** [comment]
Thanks for reporting, will try to look at it.

**Comment by olafurpg** [comment]
Any update on this?

**Comment by tgodzik** [comment]
> Any update on this?

Nothing yet, will try to take a look at it next week!

**Comment by Arthurm1** [comment]
@nilskp  How is your _sourceSets_ section for that project defined in Gradle?  And what does the _scala/setup/properties/order_ section of your Bloop JSON file look lilke?

See this [Issue](https://github.com/scalacenter/bloop/issues/992) for an explanation of how Gradle Java/Scala compile order translates into Bloop compile order.

The 2nd example in that link (empty Java _srcDirs_ and Java sources moved into Scala _srcDirs_) _should_ give you a mixed compile ordering which I think is what you need.

[Here's](https://github.com/scalacenter/bloop/blob/cff76bd7d7aa96fb3a73b3f7357bbc5f43fe32e8/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L642) the relevant Gradle export code in Bloop if you wanted to delve into it

**Comment by sswistun-vl** [comment]
From what I’ve seen if you don't have source sets defined then build is failing because both Scala plugin for Gradle and Gradle support module in Bloop default to “Java -> Scala” build order. You can bypass it by setting both Scala and Java source sets as Scala set and setting Java set as empty like here:
```
sourceSets {
    main {
        java {
            srcDirs = []
        }
        scala {
            srcDirs = ['src/main/scala', 'src/main/java']
        }
    }
}
```

**Comment by nilskp** [comment]
@Arthurm1 

My problem is that a Java `test` file is unable to find a Scala `main` file.

For `main` we share the packages/folders, but for `test` we keep them separate. Thus our Gradle source sets look like this:

```gradle
sourceSets {
    main {
        scala {
            srcDirs = ['src/main/jvm']
        }
    }
    test {
        scala {
            srcDirs = ['src/test/scala', 'src/test/java']
        }
    }
}
```

So, to recap, when compiling a `test` Java file, the compiler cannot resolve a `main` Scala file.

**Comment by Arthurm1** [comment]
@nilskp 
Then it doesn't sound as though Scala/Java compile order is the issue.

Gradle exports ```src``` and ```test``` sources as 2 separate Bloop projects and I think your setup should work.

In the ```.bloop``` directory, you should see 2 JSON files...
```projectname.json``` should contain something like the following...
```json
  "sources" : [
    "???/src/main/jvm"
  ],
  "classesDir" : "FooOutputPath"
```

```projectname-test.json``` should have the following...
```json
  "dependencies": [
    "projectname"
  ],
  "classpath": [
    "FooOutputPath"
  ]
```

So the test project should reference the main project in both its dependencies and classpath section.

If there's nothing obvious missing from your json files then could you post them?

**Comment by nilskp** [comment]
One difference, and the likely problem, is that `"sources"`, for `main`, also contains reference to `src\main\java` even though that folder neither exists nor is defined in the `sourceSets` for `main`.

**Comment by Arthurm1** [comment]
I don't see why additional empty sourcesets should make a difference but it might be worth adding the following to your Gradle ```main``` and ```test``` ```sourcesets``` sections as @sswistun-vl suggested so that sourceset disappears and then re-exporting...
```
sourceSets {
  main {
    java {
      srcDirs = []
    }
    scala {
      srcDirs = ['src/main/jvm']
    }
  }
  test {
    java {
      srcDirs = []
    }
    scala {
      srcDirs = ['src/test/scala', 'src/test/java']
    }
  }
}
```

Does your compiled Scala class exists in the project's ```classesDir``` directory when the error appears?

**Comment by nilskp** [comment]
@Arthurm1 
That did get rid of the Java srcDir, but the project still cannot resolve.

The `classesDir` looks like this, which is a non-existing path.

```json
"classesDir" : "???\\.bloop\\delphi-core\\build\\classes"
```

The `build` folder contains `bloop-bsp-clients-classes` exclusively.

**Comment by Arthurm1** [comment]
Strange.  I'm not entirely familiar with the classes directory structure but there should be another directory there where the compiled classfiles live.  Something like...
```???\\.bloop\\delphi-core\\build\\bloop-internal-classes\\classes-Metals-???\\???```

It seems like your main project has not compiled.

Opening one of your main project's Scala files in VS Code should trigger recompilation and generate class files.  Does it?

Alternatively - if you have installed Bloop separately and have it running then you should be able to trigger a recompile through the command line using ```bloop compile delphi-core``` (if that's the project name)

**Comment by nilskp** [comment]
Odd, when I checked now, the `build` folder does indeed have `bloop-internal-classes` (along with `bloop-bsp-clients-classes`).

My main project has compiled, and I can view the structure in the _Projects_ dropdown in the _Build_ view of Metals.

**Comment by Arthurm1** [comment]
Metals won't trigger a compile until a Scala file in the relevant project is opened so that may be why the classes dir was missing.

So now if you open a *Scala* file in the test project that was failing - do you still get the same error or does the test project now also compile?

I'm saying Scala file because I'm not sure if opening Java files triggers a compilation as Metals doesn't understand them but Bloop does, so your whole test project (including Java files) should compile

**Comment by nilskp** [comment]
The `test` project compiles and I can view the build tree, including Java classes, but the same error persists.

**Comment by Arthurm1** [comment]
I've created a basic project with the same structure as yours and it compiles without error.

Removing the Scala class results in a ```Cannot find symbol``` error rather than a ```cannot be resolved to a type``` error.

Could you post your java class and your scala classes here?

**Comment by nilskp** [comment]
This compiles, and runs, from command line, but fails in VSCode: [mixed.zip](https://github.com/scalameta/metals/files/3816446/mixed.zip)

![import cannot be resolved](https://user-images.githubusercontent.com/74843/68332993-568a6f80-009d-11ea-9e04-8fbd5529cfaa.png)

**Comment by Arthurm1** [comment]
Your example works fine for me.

Currently Java errors from Bloop/Metals only report line numbers, not positions on those lines, so the red squiggles are a give away.  I'm guessing you have the Java Extension Pack installed and that is reporting these errors.

You can uninstall that extension and the errors should go away.

There is a Feature Request for Java support in Metals which you can upvote [here](https://github.com/scalameta/metals-feature-requests/issues/5)

**Comment by nilskp** [comment]
@Arthurm1

You are correct. Thanks for figuring this out.
