### ISSUE TITLE
Add support for Scala 2.12.10

### ISSUE THREAD

**Issue by thesamet** [scalameta/metals#927]
**Describe the bug**
After upgrading my project to Scala 2.12.10, I am getting "Upgrade to Scala 2.12.9 and run 'Build import' to enable code navigation"

**Expected behavior**
1. Would it be possible to make it so metals is not coupled with a specific minor version of Scala?
2. The current error message recommends to upgrade Scala, but it actually wants me to downgrade - the text may need to be changed accordingly.

**Comment by gabro** [comment]
Hey @thesamet, thanks for reporting!

We have already merged #913 yesterday, which will be included in a release soon (likely next week).

As per 

> * Would it be possible to make it so metals is not coupled with a specific minor version of Scala?

we might make progress in this area in the future, but for now we depend on semantcidb-scalac which depends on a specific patch version.
