### ISSUE TITLE
NPE when using hover

### ISSUE THREAD

**Issue by svalaskevicius** [scalameta/metals#929]
**Describe the bug**

```
Sep 14, 2019 6:58:06 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
        at scala.meta.internal.pc.HoverProvider.seenFromType(HoverProvider.scala:106)
        at scala.meta.internal.pc.HoverProvider.hover(HoverProvider.scala:42)

```

**To Reproduce**

Use hover. it does work for simple cases, but for cases after case matching it seems to ... npe

**Expected behavior**
hover working well

**Screenshots**

**Installation:**
- Operating system: Linux
- Editor: nvim+coc
- Metals version:

```
~/bin/metals-vim --version
^C⏎
~/bin/metals-vim --help
^C⏎
~/bin/metals-vim -v   
^C⏎ 
```

also not in `.metals/metals.log`

I updated it a few days ago... Not sure if it was working in earlier versions as I've just resumed trying vim+metals again. Would be nice if I could switch to this setup :)

**Additional context**
Happy to provide more info if needed.

**Search terms**

hover, type info, NPE, null pointer exception

**Comment by svalaskevicius** [comment]
hmm, also, it looks like this NPE and missing hover notifications might not be as strictly related as I thought.. I get only a few successful hover infos now but no more NPE exceptions logged..

**Comment by svalaskevicius** [comment]
btw this is from both vscode and vim+coc - vscode is a bit more helpful in missing hover info as it shows the definition instead of the full info (when hover info is available it shows both) - coc however does not show the former and instead does absolutely nothing.

**Comment by svalaskevicius** [comment]
seems like most of the time it fails to get the type if a have a value wrapped in HFix and call unfix on it..

`case class HFix[F[_[_], _], A](unfix: F[HFix[F, ?], A]) extends AnyVal`

**Comment by tgodzik** [comment]
Thanks for reporting! Seems there is an issue with presentation compiler in more complex cases. Will take a look!

**Comment by sswistun-vl** [comment]
Hi, thanks for all this info, but could you also provide minimal project in which this problem occurs? That way we'd be able to replicate it more accurately and fix it quicker.

**Comment by svalaskevicius** [comment]
hmm it looks like it's working now on that codebase... will close for now as I cannot reproduce it anymore :)
