### ISSUE TITLE
Metals (lsp?) fails to start with "Symbol’s value as variable is void: method"

### ISSUE THREAD

**Issue by sritchie** [scalameta/metals#937]
**Describe the bug**
Hey all,

I've followed the install instructions at https://scalameta.org/metals/docs/editors/emacs.html exactly. When I open my first scala file in emacs, I get this error:

```
LSP :: Connected to [metals:62349 status:starting].
error in process filter: lsp--parser-on-message: Symbol’s value as variable is void: method
error in process filter: Symbol’s value as variable is void: method
error in process filter: lsp--parser-on-message: Symbol’s value as variable is void: method
error in process filter: Symbol’s value as variable is void: method
error in process filter: lsp--parser-on-message: Symbol’s value as variable is void: method
error in process filter: Symbol’s value as variable is void: method
error in process filter: lsp--parser-on-message: Symbol’s value as variable is void: method
error in process filter: Symbol’s value as variable is void: method
error in process filter: lsp--parser-on-message: Symbol’s value as variable is void: method
error in process filter: Symbol’s value as variable is void: method
```
When I continue scrolling around in the file, I see these notes:

```
eldoc error: (setting-constant :registered-capability)
Error running timer: (setting-constant :registered-capability) [2 times]
eldoc error: (setting-constant :registered-capability)
```

I've verified that `metals-emacs` is installed and accessible by emacs. I've seen some references to this being a `dash` version issue... Dash is fully upgraded for me, so I don't think it's that.

I'm stuck and can't move forward. Can I provide more information? Do you have any further advice?

Thanks!

**Installation:**
- Operating system: macOS
- Editor: Emacs
- Metals version: latest

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like an issue with lsp mode: https://github.com/emacs-lsp/lsp-mode 
Could you ask there?

Also just to make sure, when are you  getting an issue? While doing something in the editor?

**Comment by sritchie** [comment]
@tgodzik , sorry for my delay, here. This happened when I first opened a file and lsp attempted to connect.

I've abandoned my debug effort and started out with a new, absolutely up to date version of Emacs, configured via a Spacemacs layer... and the problem is gone!

Thanks for your response, and sorry I don't have more info.
