### ISSUE TITLE
Scala 2.13.1 code navigation not supported

### ISSUE THREAD

**Issue by DieBauer** [scalameta/metals#939]
**Describe the bug**

code navigation does not work for the file 'Main.scala' because the Scala version 2.13.1 is not supported. To fix this problem, change the Scala version to 2.13.0 or 2.12.9 or 2.11.12.

**To Reproduce**
Set scala version to 2.13.1 (from 2.13.0) 

**Expected behavior**
Working code navigation (ctrl+click)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: vscode plugin version 1.5.4

**Search terms**
Scala 2.13.1

Related PR: #928

**Comment by tgodzik** [comment]
PR #928 merged

**Comment by DieBauer** [comment]
Thanks, do you know when a release will follow?

**Comment by DieBauer** [comment]
nvm missed the announcement of 0.7.6. thanks again :)
