### ISSUE TITLE
`goToDefinition` doesn't resolve symbols when the cursor is at the end of them

### ISSUE THREAD

**Issue by mirichan** [scalameta/metals#945]
`editor.action.goToDeclaration` works generally, but when the cursor is at the terminal point of a symbol, it fails to. This seems to be a bug in the extension rather than the editor, because VSCode still appears to recognise that the cursor is on the symbol, and the action works from that cursor position with other languages.

This is a little frustrating because I use word-jumping shortcuts a lot, and also because a lot of DSLs use single-character symbols, and then 50% of the possible cursor positions to resolve it don't work.

It should be noted that `editor.action.showHover` handles this case fine.

**To Reproduce**

1. Open a scala file
2. Place the cursor at the end of an arbitrary symbol
3. Invoke `editor.action.goToDeclaration` via keyboard shortcut (default=`F12`) or "Go to Definition" command
4. Nothing happens.

**Expected behavior**

Cursor jumps to the symbol definition.

**Screenshots**

Strictly, this is a screen capture, but here you go (includes expected behaviour in a JS file):

[metals-vscode-bug.mov.zip](https://github.com/scalameta/metals-vscode/files/3640231/metals-vscode-bug.mov.zip)

**Installation:**

- Operating system: macOS
- VSCode version: 1.38.1
- VSCode extension version: 1.5.4
- Metals version: 0.7.5

**Comment by olafurpg** [comment]
BTW, "go to declaration" is not supported (I'm not sure what it would mean for Scala) so I renamed the title to be about "go to definition".

**Comment by tgodzik** [comment]
@olafurpg I think the issue was related to how different editors represent the symbol at the end. In vim that would show the next space, so not that natural to goToDefinition from there. Pretty sure we can change the setting depending on the editor? Or change it to always include the end?

**Comment by olafurpg** [comment]
I think we can change it to always include the end. VS Code is also affected, judging by the included screen recording. Implementing the fix itself should be easy but I think we may need to do some changes to make the tests continue to pass.
