### ISSUE TITLE
Don't insert pipe on paste when it's already included in the pasted content

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#952]
**Describe the bug**
Whenever we paste input into formatted multiline string with pipes, the get doubled instead of replaced.

**To Reproduce**
1. Create multiline string with `|` and strip margin.
2. Copy:
```
| content with
| pipes
```
3. Paste into existing multiline string
4. '|' will be added double.

**Expected behavior**
New '|' will not be added and formatting will be corrected

**Screenshots**

![image](https://user-images.githubusercontent.com/3807253/65951886-37b31080-e441-11e9-921f-0edd019475c2.png)

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.7.6

**Additional context**
The code can be found in `MultilineStringFormattingProvider`

**Search terms**
pipe multiline string

**Comment by ckipp01** [comment]
Just throwing in a note in here that I'll start working on this  👍

**Comment by ckipp01** [comment]
![Screen Recording 2019-10-06 at 12 19 20](https://user-images.githubusercontent.com/13974112/66267650-f1402600-e833-11e9-8c33-e30d6511a17a.gif)

So, I have this working as expected (I believe). I was looking into the tests and wasn't sure exactly what was expected in terms of testing. I noticed there were some tests specifically targeting onTypeFormat, but not really onRangeFormat, unless I missed it. Should I just add some tests that try to target that? Change some current ones that may utilize them? Not 100% sure on this part.
