### ISSUE TITLE
Parameter hints don't actually highlight the right parameter for position

### ISSUE THREAD

**Issue by ivanopagano** [scalameta/metals#955]
**Describe the bug**
When showing the popup to list the parameters for a method, the highlighted (bold font) parameter name and type is always the first, independently of where the cursor is actually.

This used to work correctly, highlighting the correct parameter, based on how the cursor was positioned when writing the method call arguments.

**To Reproduce**
- write a method with more than a single parameter
- write code that actually calls the method and open up the parameter hints
- write more than one argument for the method call and move the cursor between different arguments

**Expected behavior**
The argument under the cursor should match the parameter highlighted on the hint (based on position? name?)

**Screenshots**
![image](https://user-images.githubusercontent.com/1067461/66054315-1252ff00-e534-11e9-8dc3-9334411f9d6c.png)
![image](https://user-images.githubusercontent.com/1067461/66054333-1a12a380-e534-11e9-94a5-982e4edbaefc.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.5.5

**Search terms**
parameter hints, method

**Comment by ivanopagano** [comment]
Something singular is happening.
I just got back to the editor after sending the issue and now the highlight is simply slow to take up the cursor position, but it's actually working as expected...
It happened as I was filling in more values for the arguments...

Might be a slowdown from the semantic server?

**Comment by tgodzik** [comment]
> Something singular is happening.
> I just got back to the editor after sending the issue and now the highlight is simply slow to take up the cursor position, but it's actually working as expected...
> It happened as I was filling in more values for the arguments...
> 
> Might be a slowdown from the semantic server?

Thanks for reporting! I noticed something myself and pretty sure I can reproduce.

**Comment by sswistun-vl** [comment]
That's quite odd - I'm checking it out right now and everything is working fine.

**Comment by tgodzik** [comment]
> > Something singular is happening.
> > I just got back to the editor after sending the issue and now the highlight is simply slow to take up the cursor position, but it's actually working as expected...
> > It happened as I was filling in more values for the arguments...
> > Might be a slowdown from the semantic server?
> 
> Thanks for reporting! I noticed something myself and pretty sure I can reproduce.

Actually, I haven't managed to reproduce. Seems there are no longer any issues for me.

Is it possible you can get us some reproduction? Or are repo that is very slow to work with Metals?
Not sure where the issue actually lays, whether in Metals or in Emacs.

**Comment by ivanopagano** [comment]
Will try again later and let you know.
I'm using vscode btw

**Comment by tgodzik** [comment]
I will close this for now until we can find a reproduction. Most likely there was some slowness in the server, which while pretty important to fix, will be very hard to repro.
