### ISSUE TITLE
Failed to connect with build server, no functionality will work

### ISSUE THREAD

**Issue by entangled90** [scalameta/metals#969]
**Describe the bug**
Metals fails to initialize because it's unable to connect to bloop.

**To Reproduce**
I don't how it can be reproduced yet.

**Expected behavior**
Metals should connect to bloop correctly

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.7.1-v0.7.6
- Bloop version: 1.3.3, 1.3.4

**Additional context**
I have been using Metals for quite a while but suddenly it stopped working, without any new updates of neither metals nor bloop.
Today I tried with the updated bloop (1.3.4) & metals (0.7.6) but that did not solve the issue.
Bloop logs does not contain any error, but I can provide the correct logs if needed.
I tried removing `.bloop` & `.metals` with and without VSCode open but that didn't fix it.

**Search terms**
Failed to connect with build server, bloop, bsp

**Comment by tgodzik** [comment]
Hi, thanks for reporting! Is there anything in `metals.log` ? And what VS Code extension version do you have?

**Comment by entangled90** [comment]
`.metals` log looks fine until it tries to contact `bloop`:
```
INFO  build tool exit: 0
INFO  time: ran 'sbt bloopInstall' in 17s
INFO  running installed 'bloop bsp --protocol local --socket /var/folders/ks/12wnmd4s69d0wpy6p4r28ngcb44bkp/T/bsp1228825903453031090/f0m0lz0rpwhw.socket'
INFO  The server is listening for incoming connections at local:///var/folders/ks/12wnmd4s69d0wpy6p4r28ngcb44bkp/T/bsp1228825903453031090/f0m0lz0rpwhw.socket...
WARN  BSP retry 1 due to: no response: bloop bsp
scala.meta.internal.metals.BloopServers$NoResponse$: no response: bloop bsp
	at scala.meta.internal.metals.BloopServers.NoResponse$lzycompute$1(BloopServers.scala:283)
	at scala.meta.internal.metals.BloopServers.NoResponse(BloopServers.scala:283)
	at scala.meta.internal.metals.BloopServers.$anonfun$callBloopMain$1(BloopServers.scala:182)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tgodzik** [comment]
You might try stopping the Bloop server and running the embeded one, but honestly I ahve no idea why we can't connect. Is there anything in bloop logs? Can you compile using bloop commandline?

**Comment by entangled90** [comment]
Yes metals retries for three times, but fails every time. Bloop from the command line works.
At this point it may be an issue with bloop itself probably.

**Comment by entangled90** [comment]
I think I found the reason:
I had a bloop process running in background which was not started by `brew services`. Once I killed it & restarted the service metals started working.
It's strange because from the command line I was able to run bloop commands.
Thanks for the support!
