### ISSUE TITLE
CI is flaky on master

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#975]
I'm seeing a lot of flaky CI failures cuased by timeouts connecting to Bloop https://github.com/scalameta/metals/pull/973/checks?check_run_id=252264261. I'm wondering if the flakiness started after the upgrade to Bloop v1.3.3 🤔

**Comment by ckipp01** [comment]
Just throwing ideas, but I'm not 100% sure how actions is working, but I noticed that last night when I pushed, locally on my fork, the CI ran and passed just fine. However the pr one on metals failed, but there were also 2 others running at the same time. I've noticed this twice now that my builds on metals with Actions failed when there were concurrent builds going. Could that have anything to do with it seeing that there can only be one bloop server running per machine? I'm assuming they are isolated though?

**Comment by olafurpg** [comment]
Jobs are isolated on GitHub Actions so I would be surprised if concurrent jobs cause problems..

**Comment by olafurpg** [comment]
I'm wondering if the recent blackouts in the US have been causing data center problems 🤔 Or maybe they've just started receiving a lot of new traffic (which wouldn't be surprising). Either way, GitHub Actions seems to be back to normal now and more reliable. The Metals codebase is more to blame for flaky test failures I think

**Comment by tgodzik** [comment]
We are mostly back in green - aside from a few flaky test that haven't yet popped up.
