### ISSUE TITLE
Metals uses hardcoded path to sbt plugin directory

### ISSUE THREAD

**Issue by liff** [scalameta/metals#991]
**Describe the bug**

Metals [writes `metals.sbt` into `~/.sbt/<version>/plugins/`](https://github.com/scalameta/metals/blob/c1cc34a3ba31f760c0d75f9ffd953392e8b9f12c/metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala#L68). sbt resolves the plugin directory using `sbt.global.plugins` system property (maybe also `sbt.global.base`).

**To Reproduce**
1. Set environment variable `_JAVA_OPTIONS` to `-Dsbt.global.plugins=$XDG_CONFIG_HOME/sbt/plugins`
2. Open VS code (though I suppose any editor will do?)
3. Import project
4. Import fails with this error in `.metals/metals.log`:
    ```
    INFO  [error] Not a valid command: metalsEnable
    INFO  [error] Not a valid project ID: metalsEnable
    ```

**Expected behavior**

Metals writes `metals.sbt` according to system properties used by sbt.

**Screenshots**

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.7.6

**Additional context**

**Search terms**

**Comment by olafurpg** [comment]
Thank you for reporting! The latest SNAPSHOT of Metals doesn't write to global plugin directory anymore. Metals only writes to the workspace `project/metals.sbt` file now. Please try out the latest SNAPSHOT and confirm if that fixes your issue http://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot

**Comment by liff** [comment]
Oh. Should have read the comment a few lines above the one I linked :anguished:. Sorry about that. I’ll just wait for the next release then, thanks!
