### ISSUE TITLE
Code lenses don't disappear after recompiling with error

### ISSUE THREAD

**Issue by marek1840** [scalameta/metals#992]
**Describe the bug**
Code lenses are not being refreshed after compilation error.

**To Reproduce**
1. Open following source code as a file and compile it:
```scala
object Foo {
  def main(args: Array[String]): Unit = ???
}
```
2. wait to see the `run` code lens
3. remove trailing `}` and save the file
4. observe the code lens not disappearing despite the error being reported correctly

**Expected behavior**
The code lens should disappear in `4.`

**Search terms**
lens disappear compilation error

**Comment by marek1840** [comment]
In the end, we have [decided](https://github.com/scalameta/metals/pull/994#discussion_r335356366) that this behavior is desirable. Now, we need to formalize it by adding some tests.

**Comment by olafurpg** [comment]
Can you elaborate which behavior is desirable? I believe that code lenses should stay unchanged during compile error.

**Comment by marek1840** [comment]
> Can you elaborate which behavior is desirable? I believe that code lenses should stay unchanged during compile error.

The comment got clarified
